### ISSUE TITLE
JOSM remote control request failing in firefox due to content security policy

### ISSUE THREAD

**Issue by risicle** [hotosm/tasking-manager#1000]
In firefox I've recently seen TM3, being an https site, making http requests to the remotecontrol, which is of course failing as it is "mixed active content". Results in console error message like:

```
Blocked loading mixed active content "http://127.0.0.1:8111/load_data?new_layer=true&mime_type=application/x-osm+xml&layer_name=OSM%20Data&data=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf8%22%3F%3E%3Cosm%20generator%3D%22JOSM%22%20version%3D%220.6%22%3E%3C%2Fosm%3E"
```

Possibly related to https://github.com/hotosm/tasking-manager/issues/927

(I'm on firefox 52.5.2, but I've seen it on other firefoxes)

**Comment by alekno** [comment]
Apple device specific, as far as I do remember.  Can you confirm firefox on iOS?

**Comment by risicle** [comment]
Was happening for me on linux.

**Comment by dkocich** [comment]
Works fine for me in Ubuntu Firefox 58.0.1 64b

**Comment by bgirardot** [comment]
@dkocich Thank you very much for the testing.

@risicle Does this seem to still be happening for you?

I think we fixed this, although I lost track of when, but I believe this has been fixed.

**Comment by risicle** [comment]
Ahhhh I think this https://bugzilla.mozilla.org/show_bug.cgi?id=903966 is the source of the issue. In short - firefox 55+ allows mixed content against localhost. Firefox ESR is still 52.

Still I think it's weird that the app is attempting to load an http url from within an https context. Surely it should know it's in an https context and attempt to load `https://127.0.0.1:8112` instead.

**Comment by bgirardot** [comment]
Ya, I agree, I thought we did fix that but looking at the code I guess not. Thank you @risicle for the follow up, I was not searching for the right thing, your last comment helped me find what I was looking for.

https://github.com/hotosm/tasking-manager/search?utf8=%E2%9C%93&q=8111

**Comment by dkocich** [comment]
it is weird but I am not sure that it will work:
"The protocol used is HTTP, so that web applications wishing to let the user edit a certain area can simply generate suitable HTTP links. Browsers should always call the http endpoint, not the deprecated https endpoint. It is important to make calls on the 127.0.0.1 loopback IP address and not the localhost hostname: browsers whitelist calls to http://127.0.0.1 from https pages, but not calls to http://localhost." https://wiki.openstreetmap.org/wiki/JOSM/RemoteControl

**Comment by bgirardot** [comment]
Yes, @dkocich I was just looking for this, I thought I heard that the https end point was going to be removed at some point, but I thought I must be wrong about that. I do not pretend to understand why exactly, but as you quoted above "... not the deprecated https endpoint" is the key phrase. I think we have to stick with that non ssl url.

**Comment by harry-wood** [comment]
I noticed this PR https://github.com/openstreetmap/openstreetmap-website/pull/1707 on the main openstreetmap.org website swapping remote control links from https back to http ahead of deprecation by JOSM.

Interesting notes on browser compatibility. It looks like Firefox ESR & Safari will block it with mixed content warnings. I wonder what can be done to work around that, or at least improve the error message for people with these browsers

**Comment by harry-wood** [comment]
Pretty sure we can improve this for Firefox ESR and Safari users. The browsers are perfectly capable of launching JOSM, they just don't like doing so in an AJAXy way from a https website. A regular document load of the JOSM launch URL will work fine.

Could somebody who knows angular try the follow simple thing? :

Add something to the end of this error message _"JOSM remote control did not respond. Do you have JOSM running and configured to be controlled remotely?"_  .... it could just say "(Try direct url)" where this is a regular "a href" link to the JOSM launch URL. That link href will need (re)setting whenever we're about try launching [here](https://github.com/hotosm/tasking-manager/blob/master/client/app/services/editor.service.js#L120).

We could probably take that idea towards a more complete fix, if we detected browser versions or something, but I think providing that link will work, and will be a big improvement.

**Comment by gorn** [comment]
I have added manually exception to the brorwser so now both http://localhost:8111 and https:/localhost:8112 work, but the "Start editor" button still does not work

**Comment by twpol** [comment]
FYI I've just run into the exact same problem trying to start JOSM from Edge (16.16299).

> SEC7111: HTTPS security is compromised by http://127.0.0.1:8111

**Comment by gorn** [comment]
Great, thanks!
