### ISSUE TITLE
Invoke iD with custom presets for Africa

### ISSUE THREAD

**Issue by johnwhelan** [hotosm/tasking-manager#1009]
Currently a large number of African highways are being mapped as footways or living_streets neither of which are listed in the African highway wiki. 

Buildings are being tagged with values of other than yes.  Again the HOT recommendation is when mapping from imagery building=yes is used so restricting the choice to yes would be helpful.

These are a couple of examples of what could be done to improve data quality with the use of a custom iD editor preset using the current version of iD.

**Comment by bgirardot** [comment]
Hi @johnwhelan , I am not aware of being able to invoke the standard iD editor with custom presets.

Can you provide a link or other information that explains how to do that?

**Comment by johnwhelan** [comment]
It was mentioned by Bryan recently and additionally it was offered as an
option to Stats Canada on the building project.

The technical side I haven't dug into but I'm sure Bryan can point you in
the right direction.

I assume it's just a parameter you pass when invoking iD.

Bug me if you'd like me to dig.

Thanks John

**Comment by bgirardot** [comment]
Hi @johnwhelan I just do not think it works that way. 

My understanding is that they only thing you can do is fork the iD editor and maintain your own instance with a custom presets file.

I will leave this open for now if you want to find out if my understanding is mistaken.

**Comment by johnwhelan** [comment]
So for African projects TM3 could invoke a HOTAfricaForkediD editor that
just had a different preset file rather than iD directly?  Maintenance
would just be copy the preset file across to a new version.

Cheerio John

**Comment by xamanu** [comment]
This has been addressed by with PR https://github.com/hotosm/tasking-manager/pull/1487 that introduces a selection of editors on a project. As one example it got extended by "RapiD" (https://github.com/hotosm/tasking-manager/pull/1550). In case a special iD is needed it can now be achieved from the TM side.

As a cleaner approach we would like to integrate [MapRules](https://wiki.openstreetmap.org/wiki/MapRules) flexibly on a project basis, that can give presets based on what is the project focused on, taking into consideration local particularities.
