### ISSUE TITLE
Number of active mappers does not reflect project map indicators - not counting validators

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#1014]
I see blue tasks indicating that people are working on those task squares, but the number of active mappers both on the project page and on the card in the contribute list do not reflect that.

![2018-01-07_14h43_15](https://user-images.githubusercontent.com/265831/34650508-9683e826-f3c2-11e7-8d43-1dadd37fc248.png)

![2018-01-07_15h45_54](https://user-images.githubusercontent.com/265831/34650502-826afa1e-f3c2-11e7-9e6c-b8e1074837fa.png)

**Comment by sunidhiraheja** [comment]
This seems to be working fine for me.
Can you please confirm? The active mappers count is cached for a period of 30 seconds, so that might have caused this discrepancy.

**Comment by bgirardot** [comment]
I am going to chalk this up to caching and keep an eye out for it and close it for now. Thank you for looking @sunidhiraheja

**Comment by bgirardot** [comment]
@russdeffner Just asked this same question so it still happens, he waited 30 seconds, refreshed and it was still incorrect so it might be a cache issue, but it is cached too long if it is.

Ok, we know what the issue is, that active mappers count seems to not include people with tasks checked out for validation.
