### ISSUE TITLE
my task "box" isn't a box

### ISSUE THREAD

**Issue by govvin** [hotosm/tasking-manager#1018]
The tasks we generate aren't box-shaped, so the current warning seen on iD isn't exactly suitable. It's not a major issue, just a niggling description.

Perhaps change the text to something like: `Do not edit outside this colored area` ?

![image](https://user-images.githubusercontent.com/5821688/34855420-9813bd7c-f77a-11e7-88b9-c65bc35eee56.png)

**Comment by bgirardot** [comment]
This was fixed by the merge listed above. Thank you for bug report!
