### ISSUE TITLE
multiple tasks validation - no data sent to JOSM

### ISSUE THREAD

**Issue by govvin** [hotosm/tasking-manager#1022]
![image](https://user-images.githubusercontent.com/5821688/34906995-a6ee6ebc-f8b2-11e7-88d0-5a3aaf4c09e2.png)

On TM3, while trying to validate a particular user's tasks (Option 5), the "OSM data" layer is empty, and so is the "Data Layer", which I don't know what to expect to have.

![image](https://user-images.githubusercontent.com/5821688/34907003-ba0e72e4-f8b2-11e7-8d05-5c0428b8fe71.png)

Validating individual tasks work as expected, but not with multiple tasks.

**Comment by russdeffner** [comment]
This is actually how it works - if you think about a large project, if you have tasks on opposite sides, JOSM will try to download the entire area and most likely fail, so you have to manually download the data when doing multiple task validation.

**Comment by bgirardot** [comment]
@govvin What russ said. Also, I usually right click on the layer and convert it to gpx to it turns yellow and is easier to see.

**Comment by govvin** [comment]
@russdeffner , thank you. That's actually how I ended up doing it. 

@bgirardot , thank you for sharing your tip. You're right,  i ended up having to changing the layer color to make them easier to find.
