### ISSUE TITLE
Center world maps on user location

### ISSUE THREAD

**Issue by JesseWeinstein** [hotosm/tasking-manager#1023]
Specifically, it leaves out the strip between 155 and -159 longitude. I noticed this because New Zealand is included in this strip.

This is on Firefox, on a 1360x768 pixel display. On another monitor, it was slightly different, but still left out a similar strip.

I suspect this may not be a tasking-manager issue, but I wasn't sure where else to file it. This is, obviously, a very minor problem -- but it is (mildly) misleading.

**Comment by xamanu** [comment]
We have been talking about this in the ongoing redesign process and we considered the map more as a tool for orienting a search for projects, based on the user's geographic interest. The idea is to focus the map on a size of a continent, eventually centered on the user's location, which we want introduce:

![image](https://user-images.githubusercontent.com/97706/58167568-bf129b00-7c7b-11e9-9b9b-c74fb3e2011c.png)

**Comment by xamanu** [comment]
This is still an issue on TM4. I suggest we make this an issue that centers the map based on the user location given in the profile.

**Comment by willemarcel** [comment]
I believe the world map view is the better solution here. We are improving the project selection on: https://github.com/hotosm/tasking-manager/issues/3805
