### ISSUE TITLE
Tiles recorded as mapped include invalidated ones

### ISSUE THREAD

**Issue by shiller27** [hotosm/tasking-manager#1027]
Hi, I noticed that project #3389 is shown as 100% mapped, even though several tiles are invalidated and need to be done.  As far as I remember, TM2 counted invalidated tiles as not done, which makes far more sense as mappers will go back to the project (marked as, say 98%) and finish those invalidated ones.

Thanks!

**Comment by ethan-nelson** [comment]
Hi @shiller27 I want to say this may be finally fixed based on some stats changes we've made, including https://github.com/hotosm/tasking-manager/pull/1123. I checked this project specifically and it is no longer at 100% for mapped (eyeballing it, the current 92% figure seems close). If you continue to encounter strange calculations, please reopen the issue. Thanks for the report!
