### ISSUE TITLE
managing messages

### ISSUE THREAD

**Issue by govvin** [hotosm/tasking-manager#1029]
![image](https://user-images.githubusercontent.com/5821688/35248627-cd8311aa-0009-11e8-981d-ed258f85e789.png)

I hope in the future, there's a better way of deleting notification messages from the inbox, other than doing it one at a time. The amount of messages you get for these could feel overwhelming.

**Comment by bgirardot** [comment]
Hi @govvin Thank you very much for your comment. I agree, it gets pretty tedious. We do have this as an exsiting issue #916 so I am going to close this one, but your entry will now be listed as referenced on that issue. Again, thank you very much.
