### ISSUE TITLE
Unable to init database

### ISSUE THREAD

**Issue by kriscarle** [hotosm/tasking-manager#1032]
When running `manage.py db upgrade` on a new empty database I get the error `relation "tasks" does not exist`

Looks like it was introduced here https://github.com/hotosm/tasking-manager/commit/0ed20f22e4e36fe995cc825f55384017972dc13f#diff-632b651e5579af0e928ed63482e9bc77

After commenting out `init_counters()` I was able to init the db
https://github.com/hotosm/tasking-manager/blob/develop/manage.py#L20

**Comment by bgirardot** [comment]
@kriscarle This should be fixed in the latest development branch now. Please let us know if it is not fixed. Thank you very much for the issue entry!
