### ISSUE TITLE
Optimize web app (Lighthouse)

### ISSUE THREAD

**Issue by dkocich** [hotosm/tasking-manager#1040]
Accessibility and loading speed of the web app could be improved (based on the Lighthouse report - more info here https://developers.google.com/web/tools/lighthouse/ ; it can be also automated later https://github.com/ebidel/lighthouse-ci).

To read the detailed report, please run your own audit or open mine in the web viewer here https://googlechrome.github.io/lighthouse/viewer/?gist=0a9e4362e8869d78056e69282b12ee29

**Comment by willemarcel** [comment]
We made some work recently on that part.
