### ISSUE TITLE
Mark all tasks as mapped/completely mapped

### ISSUE THREAD

**Issue by giblet22** [hotosm/tasking-manager#1041]
There's an option to validate/invalidate all tasks of a project, but not to mark all as done. There may be few times when this is needed to be used but I'd find it useful as a project manager.

<img width="827" alt="screen shot 2018-02-01 at 9 01 30 am" src="https://user-images.githubusercontent.com/7945333/35667592-8898a434-072e-11e8-9d53-56a21a16952a.png">

**Comment by ethan-nelson** [comment]
This is another good example for someone interested in understanding the full process to add an API feature. It will entail:

1. Adding an endpoint in the project API (like https://github.com/hotosm/tasking-manager/blob/develop/server/api/project_admin_api.py#L395-L434)

**Comment by sunidhiraheja** [comment]
Hi, I'd like to take this up!

**Comment by bgirardot** [comment]
Just a note on this one, there is a related feature as mentioned, "mark all tasks as validated" which has a bug that needs to be fixed. It would be good to get that bug fixed. issue #986 At the very least this new, related feature should not have that same bug :)

**Comment by sunidhiraheja** [comment]
@ethan-nelson Thanks for the guidance, I think I understand the flow now.

I just wanted to confirm whether done/completed refers to the MAPPED `TaskStatus` type (since you mentioned creating the service function in `mapping_service.py`.

**Comment by bgirardot** [comment]
@giblet22 In my thinking, if the project has already validated tasks, those should stay validated and not be "reset" to just "Mapped" by this button, correct?

cc: @sunidhiraheja

**Comment by giblet22** [comment]
@bgirardot that is correct. good catch

**Comment by ethan-nelson** [comment]
@giblet22 we've added this feature now thanks to @sunidhiraheja ... feel free to try it out on the staging instance at https://tasks-stage.hotosm.org (see example at https://tasks-stage.hotosm.org/project/3403/dashboard). This addition will be rolled out to the main instance in our next update.
