### ISSUE TITLE
API Error unlocking task - "multiple rows were found for one()"

### ISSUE THREAD

**Issue by rustyb** [hotosm/tasking-manager#1045]
See -> https://tasks.hotosm.org/project/3885?task=75

If we try to unlock the task we get a 500 error from the DB in the frontend indicating "Tasking API Error...multiple rows were found for one()".

Just flagging in case the error pops up elsewhere.

**Comment by smit1678** [comment]
@rustyb Was this on that specific task, 75? or seeing this on other tasks in this project? I'm seeing that 75 was unlocked. 

![hot tasking manager 2018-02-08 13-54-41](https://user-images.githubusercontent.com/796838/35976309-9f41cb4e-0cd7-11e8-8e90-66b43b0d7874.png)

**Comment by rustyb** [comment]
It was on task 75 only, we waiting for it to be automatically unlocked in the end.

**Comment by bgirardot** [comment]
We have seen this before I think during development, but it was fixed.

We had to run a script from @hunt3ri to correct the state some of them were left it.

I also got a report of this recently too that I will find.

@hunt3ri Do you remember this and the script that you asked David to run to fix the tasks that could not be unlocked? I think we need to run that script again and look for the underlying cause.

**Comment by bgirardot** [comment]
![image 1](https://user-images.githubusercontent.com/265831/35977900-8d9d1954-0ce4-11e8-905d-f881e3e58358.png)

https://tasks.hotosm.org/project/3603

and

https://tasks.hotosm.org/project/4021?task=9#bottom

**Comment by bgirardot** [comment]
Oh, now that I look, these are slightly different errors, one is "no row found" and one is "multiple rows found"

**Comment by bgirardot** [comment]
Here is a Gist of recent errors exactly like this one and similar to it:

https://gist.github.com/bgirardot/c378deb4b6dc725ab71fec1407133724

**Comment by sunidhiraheja** [comment]
@bgirardot Can we see the rows that are returned on that query match?
If they're deleted for this particular instance (on unlocking), maybe we could log them for future occurrences.
I think this will be of great help in debugging.

**Comment by smit1678** [comment]
@sunidhiraheja Did digging into the NewRelic logs and error reporting help here? 

From what I can see, it looks like the function `server.api.validator_apis:unlocktasksaftervalidationapi` is the slow point that is related. The database query returns quickly but the function seems to consistently takes about 3 minutes to respond.

**Comment by ethan-nelson** [comment]
Is there anyway to check those calls compared to SES email sends? It could be hanging on https://github.com/hotosm/tasking-manager/blob/56d1d13056bbea342132cf6e78b12f01c73d5dd3/server/services/validator_service.py#L103 if the email process is not an instant response.

**Comment by ethan-nelson** [comment]
I've spent a lot of time digging into the data model internals. It seems like these errors crop up frequency specifically when:

* A task history element has been inserted
* The `task_status` row of the task has not been updated properly

The task data model does not inherit the status of the most recent history associated with that id, but is rather set during a given action. So in a function either a race condition is occurring where the task_status is being set before the history element is added or the task_status is just not being set.

Not sure yet where this happens, but I'm just jotting down thoughts while they are still fresh in my mind.

**Comment by Hulios** [comment]
Hi @ethan-nelson 
I've found possible occurrence of this race condition, where status is updated before task history. 

https://github.com/hotosm/tasking-manager/blob/6c3bc76a5cf30fb8bf4c031da6db53eec8909f19/server/models/postgis/task.py#L321-L332

I've changed it in #1217 and with additional changes to automatic unlocking, it should solve problem of "multiple rows were found for one()"
I'm not sure if it will help for other error "No row was found for one()"
