### ISSUE TITLE
Add delete message button on individual message page

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#1047]
Another easy upgrade to the messages is if I could delete the message I am currently reading instead of having to return to the inbox first. Thanks!

**Comment by Yagya-Chaudhary** [comment]
Can you elaborate your problem ?

**Comment by Yagya-Chaudhary** [comment]
Can you guide me more about this ?

**Comment by russdeffner** [comment]
I can answer questions from the user perspective, but not a developer myself.  Are you looking at this for GSoC or Outreachy?

**Comment by Yagya-Chaudhary** [comment]
I just got interested in contribution so here I am .

**Comment by russdeffner** [comment]
Ah, ok - hopefully someone who can better help you will answer here; otherwise/also you can join slack.hotosm.org #tasking_manager_3 channel

**Comment by Yagya-Chaudhary** [comment]
thanks

**Comment by uwaiszaki** [comment]
@xamanu I would like to work on this issue.

**Comment by uwaiszaki** [comment]
@smit1678 @xamanu @ramyaragupathy I have created a pr #1390, Please give ur reviews.

**Comment by xamanu** [comment]
This went into the upcoming release. Closing here.
