### ISSUE TITLE
Cloned project should copy the project name from Step 5 of the process

### ISSUE THREAD

**Issue by govvin** [hotosm/tasking-manager#1061]
When cloning a project, Step 5 asks for a project name:
![image](https://user-images.githubusercontent.com/5821688/36661313-e24c705a-1b15-11e8-935e-ea547e5b560f.png)

Currently, however, this value is not immediately used when you get to the part where you edit the project details
![image](https://user-images.githubusercontent.com/5821688/36661364-023a41bc-1b16-11e8-9f18-2bd6347f9a23.png)

This could've been one less step to do when cloning projects.

**Comment by russdeffner** [comment]
see also #1046
