### ISSUE TITLE
Unable to display projects

### ISSUE THREAD

**Issue by govvin** [hotosm/tasking-manager#1063]
Currently, on Firefox and Chromium, I couldn't display any of the projects I created (published, archived, or in draft). Here is a screen shot:
![image](https://user-images.githubusercontent.com/5821688/36728232-0b132066-1bfb-11e8-8dbd-84dfe5d1953b.png)

The browser debugger reports
`Source map error: request failed with status 404 Resource URL: https://cdn.jsdelivr.net/openlayers.geocoder/latest/ol3-geocoder.js Source Map URL: ol3-geocoder.js.map`

**Comment by bgirardot** [comment]
@govvin Could it have been a temporary issue? This seems to be working for me at this moment.

**Comment by govvin** [comment]
@bgirardot I'm not sure about that. I've had that error for at least three hours now. And I also tried switching to another Internet service provider, and I got the same results.

I can search for the specific projects I created, and I can edit them, too. It's just in the dashboard that I'm encountering this error.

**Comment by govvin** [comment]
I can search/access the projects I created from the Contribute page, but checking the debugger, I have the same exact error, without any on-screen indicator for the same:

`Source map error: request failed with status 404
Resource URL: https://cdn.jsdelivr.net/openlayers.geocoder/latest/ol3-geocoder.js
Source Map URL: ol3-geocoder.js.map`

Kindly let me know if there's anything else I can check to help resolve this.

**Comment by LindaAlblas** [comment]
That 404 should be unrelated (although strange!). It looks like the issue is in the my-projects API (https://tasks.hotosm.org/api/v1/admin/my-projects). It could be helpful to know what the API returns as the error message instead of the error message you are seeing on screen. You should be able to find that in the Response tab after clicking on the 'my-projects' request in the developer tools of the browser.

**Comment by ethan-nelson** [comment]
Are you running any ad or resource blockers, e.g. Ad Block Plus, Privacy Badger, uOrigin?

**Comment by govvin** [comment]
@LindaAlblas this is what I got from the response tab:
![image](https://user-images.githubusercontent.com/5821688/36762529-06094794-1c5f-11e8-9564-6fb28f4fb68c.png)

i hope that's helpful.

@ethan-nelson 
i've disabled them with hotosm domain. By the way, this was working fine before yesterday, and there were no configuration changes in my browser.

**Comment by govvin** [comment]
Do you have any workaround suggestions for this? I'm still experiencing this issue.

**Comment by ethan-nelson** [comment]
A few more questions:

* Had you previously logged into TM2 before TM3 was launched?
* Have you changed your OSM username recently or ever?
* Are you able to check out tasks at the moment?

**Comment by govvin** [comment]
Hi @ethan-nelson 
- Yes
- Never
- Yes. I can check / contribute on tasks. I can edit/create projects.
- It's "[GOwin](https://osm.org/user/GOwin)".

**Comment by ethan-nelson** [comment]
@govvin great, thanks. I will do some more troubleshooting this evening and let you know.

**Comment by govvin** [comment]
Hello again. Are there any developments with this issue?

**Comment by ramyaragupathy** [comment]
@govvin - Do you still face this issue?

**Comment by govvin** [comment]
> @govvin - Do you still face this issue?

Currently, not anymore.
