### ISSUE TITLE
Auto unlocked task stays in locked UI state

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#1065]
When a task times out due to the 2 hour limit, it seems to get released just fine, but the UI shown to the user still looks like they have the task checked out.

It should instead:

1. put up a dialog that indicates this task expired and was auto unlocked after 2 hours
2. keep the user on that selected task in case they want to check it out again.

Below is are screen shots of what it looks like after a time out. You can see the map is updated to reflect they no longer have a lock on the selected task, but the UI has remained the same as if they do. The second screen shot shows that the system correctly identifies they can not mark a task as mapped or stop mapping or anything else because they do not have it locked.

![2018-03-01_16h58_32](https://user-images.githubusercontent.com/265831/36933701-1b52bcd0-1ede-11e8-8978-0a5f9351af97.png)

![2018-03-01_16h58_56](https://user-images.githubusercontent.com/265831/36933704-228d31f6-1ede-11e8-8263-8ede6d6c5ce5.png)

**Comment by bgirardot** [comment]
@sunidhiraheja this might be a quick fix for you since you are working so closely on the timer issue.

**Comment by Madhumathi97** [comment]
@bgirardot Can I work on this issue as my first contribution to the project "creating a tasking manager stat explorer"?

**Comment by bgirardot** [comment]
@Madhumathi97 Hi, yes, for sure you can start on this. Please realize it is primarily a UI issue so is in the AngularJS code.

I will add the in progress tag, please let us know if you stop working on it for some reason. cheers

**Comment by Madhumathi97** [comment]
Oh I am not familiar with AngularJS.Is there anything I can work on using
JS and HTML?Thank you

**Comment by bgirardot** [comment]
@Madhumathi97 The front end is written in AngularJS, which is a JS framework. There is not really any part of the front end that does not make use of AngularJS

**Comment by bgirardot** [comment]
@Madhumathi97 I will keep my eye out as I am working on this repo today for a small contribution that might be better for you. I also see that @sunidhiraheja is working on this one anyway. My apologies to both of you for not seeing that before now.

**Comment by Madhumathi97** [comment]
Ok no worries and yes would be great if you could give me a small area to
work on as my first contribution as I seem to really struggle to find my
way as it is my very first contribution.Thank you

*Thanks,*
*Madhumathi*
*S6 CSE*

*"You can't expect to hold supreme executive power just because some watery
tart lobbed a sword at you"*

**Comment by bgirardot** [comment]
@Madhumathi97 How are you with CSS? we use something call SASS to generate CSS, but it is essentially CSS. We for sure need some SASS/CSS changes.

**Comment by Madhumathi97** [comment]
Yes I can work with SASS/CSS.Please let me know on which I can work.thank
you
