### ISSUE TITLE
Authentification fail from local machine

### ISSUE THREAD

**Issue by rhcu** [hotosm/tasking-manager#1066]
I have installed Tasking Manager on my local machine. However, when I am trying to press "Log in", the following error is shown:  flask_oauthlib.client.OAuthException: Failed to generate request token.

**Comment by ethan-nelson** [comment]
Hi rhcu, are you still having this problem or did you get it sorted out? Cheers

**Comment by ethan-nelson** [comment]
Gonna go ahead and close this due to no response; please reopen if it is still an issue. Thanks!

**Comment by jgrocha** [comment]
Sorry for the noise.
I had to go to https://www.openstreetmap.org/user/your-username/oauth_clients/new to create a new authorization.
Problem solved.
