### ISSUE TITLE
Speedy Validating

### ISSUE THREAD

**Issue by Geocruizer** [hotosm/tasking-manager#107]
Can we build a tool that allows the task editors username to be visible and select (or see) all the cells that person edited?  For example if "Marion Barry" mapped 5 cells, and the first 3 were perfect there is a really good chance the next two will also be high quality.  It might encourage me to visit the remaining two and quickly knock them out.  This could really help speed up validating (while encouraging cherry picking)

**Comment by bgirardot** [comment]
This will be part of TM3 functionality.

**Comment by Geocruizer** [comment]
Perfect, thanks for all the great work Blake and ThinkWhere!

**Comment by d3netxer** [comment]
this is good, because with my virtual interns I am asking them to tell me which squares they worked on so I can check their work. If I can just select their username and see what they mapped, it would save a step

**Comment by bgirardot** [comment]
The first version of this is supported. Works great on iD. JOSM is save/load gpx based, which is not ideal. But we have the required functionality in place to community refine it to work like it does in iD, but in JOSM.
