### ISSUE TITLE
Warning for large geometry files

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1080]
From #1079, the UI should probably alert someone when creating a project if the file they upload is over a certain limit--maybe 5 or 10 MB--as users with lower CPU capacity computers may be impacted performance-wise.

**Comment by xamanu** [comment]
@JorgeMartinezG Can this be included in the TM4 project creation (#1888) you are currently working on?

**Comment by JorgeMartinezG** [comment]
The check for large geometries has been included in https://github.com/hotosm/tasking-manager/pull/1999 cc. @xamanu
