### ISSUE TITLE
When a select task is not in a state that allows validation, automatically switch to "Map" mode

### ISSUE THREAD

**Issue by govvin** [hotosm/tasking-manager#1085]
Instead of this error message:
![image](https://user-images.githubusercontent.com/5821688/38654308-391428da-3e41-11e8-9340-5bdb1149bcc6.png)

Could you just switch the user to map mode?

**Comment by xamanu** [comment]
Thanks for the input! We are in a redesign process and were thinking about how to improve this. For this we came up with the idea of providing a lists of tasks for people that are suitable and possible to map or validate.

![image](https://user-images.githubusercontent.com/97706/58168807-ae175900-7c7e-11e9-98d2-0e8ac8ab3a35.png)

This should already help mappers and validators to find tasks. And the selected task on the map should be selected in the list, too. This means we have to jump to their state and tab.

**Comment by xamanu** [comment]
Done for TM4
