### ISSUE TITLE
Documentation server migration TM2 to TM3

### ISSUE THREAD

**Issue by kleper** [hotosm/tasking-manager#1088]
Hello,

I recently made the TM2 server migration from OpenStreetMap Colombia, I had some problems that are not documented.
I made the following document, maybe it could be useful for another person.
https://github.com/kleper/Cartografia/blob/master/MigratingTM2toTM3ENG.md

Sorry to send it by this means, but I did not find another way.
Greetings.

**Comment by ethan-nelson** [comment]
Hi @kleper thank you for this guide. I have updated the wiki page at https://github.com/hotosm/tasking-manager/wiki/Migrating-from-TM2-to-TM3 and am now working on a PR (#1307) to make this process a bit easier based on that guide.
