### ISSUE TITLE
osm.earth trademark issues

### ISSUE THREAD

**Issue by simonpoole** [hotosm/tasking-manager#1097]
As you may know the OSMFs trademark policy is now in force see https://wiki.osmfoundation.org/wiki/Trademark_Policy which provides a wide ranging lenient licensing for community projects.

However your 

- registration of osm.earth
- use of "Open Earth Map" as a project name

are not in line with the uses of the OSMF marks that do not require a license. You can apply for a license by completing and submitting the form at https://wiki.osmfoundation.org/wiki/Project_Licence_and_Domain_Grandfathering_Application

I would further suggest that  you add notices as required in section 2.2 as the site would seem to violate 2.3 without them.

**Comment by simonpoole** [comment]
Seems as if is not run by HOT .... closing

**Comment by verdy-p** [comment]
However the term "OSM" is not owned by the OpenStreetMap Foundation. There are even preexisting trademarks unrelated to OpenStreetMap, which have existed long before.

"OSM" (and "OSMF") are just convenient abbreviations used in context where their meaning is clearly and visibly associated with "OpenStreetMap" (the protected trademark).

But well it's true that "OSM.Earth" and "HOTOSM" are both built and named in strong association of OpenStreetMap projects and data. The "OSM.Earth" page does not even contain the word "OpenStreetMap" (so it may be misleading). But it does not violate the copyright for the data it uses and gives correct attribution where such data is used.

But to avoid all confusion, "OSM.Earth" should have a clear statement that:
- it is managed by HOTOSM (the small link at bottom of page is really too small)
- as it promotes using OSM data and using OSM resources and servers, and the involvment of their users as members of the OSM community, these relations should be clear: participants to OSM.Earth should clearly know they will participate to OSM projects and will use them.

So I don't see that as a clear violation, jsut a need of clarification of what this project is, who manages it and who is responsible of the content of the site, and the fact that the OSMF is not directly affiliated to this community page.

There's some good examples of such statement for example on the Mapbox website which have such clear statement (hwoever it does not need to build up on OSMF trademarks to have its own company and brand names, and also does not require that all uses of Mapbox will be based on OSM data and projects, in fact Mapbox develops generic GIS solutions which can also be used with proprietary data: OSM is just offered as a choice and highly promoted, but not required and Mapbox users are then not required to accept the OSM policies, just the policies of what they use with Mapbox).

But here it's imposible to detach "OSM.Earth" projects from OSM projects. so the relations are necessarily tight. So I agree that a clear statement on the homepage should then be visible.

This OSM.Earth site is still very new, beta starting; it's not dramatic for now, there are probably lot of things to do there.

**Comment by verdy-p** [comment]
Visibly the introduction text was modified. The site is clearer now !
The additional link at bottom of page is also a good improvement.

**Comment by simonpoole** [comment]
@verdy_p while OSM is not a registered trademark, that doesn't mean we (the OSMF) don't have rights to it, particularly when used in a context referring to geographic information.

**Comment by verdy-p** [comment]
It.s not aquestion of right here as there was no evident abuse. It.s just
the fact that the term OSM chosen was initially properly linked to what it
meant and this has consequences on users of this site that should know in
which sphere they'll work with.

Bit with the small improvements now bisibke on the site I do not see any
problem caused by your onitial statemrnt about trademark issue or legal
issue. We just want things to be clear for all about who is who and who
supports the project or is liable for.
