### ISSUE TITLE
Translations needed for: Português, Lietuvos, Dansk, Tamil (தமிழ்), Sinhala  

### ISSUE THREAD

**Issue by aaj013** [hotosm/tasking-manager#1098]
Missing JSON files for following languages:

- Português
- Lietuvos
- Dansk
- Tamil (தமிழ்)
- Sinhala (සිංහල)
![missing languages](https://user-images.githubusercontent.com/5847582/39304935-0cfe17f4-4979-11e8-96c0-86687bd2a0ac.png)
@bgirardot

**Comment by aaj013** [comment]
I've done translating and created the json files

**Comment by xamanu** [comment]
The problem here are not the files, but having the TM translated into these languages by native speakers.

**Comment by xamanu** [comment]
Related to #1678

**Comment by xamanu** [comment]
This is not occurring with the current version. Considering this as fixed. Please reopen in case there is still a problem.
