### ISSUE TITLE
Search API "unhandled error: division by zero"

### ISSUE THREAD

**Issue by harry-wood** [hotosm/tasking-manager#1108]
Using the `project/search` API I'm seeing a 500 error:
`{"error": "Project GET - unhandled error: division by zero"}`

...but only on some pages of the resultset:
https://tasks.hotosm.org/api/v1/project/search?page=71  <-- works
https://tasks.hotosm.org/api/v1/project/search?page=72  <-- error
https://tasks.hotosm.org/api/v1/project/search?page=72  <-- error
https://tasks.hotosm.org/api/v1/project/search?page=74  <-- works

...and all the other pages work I think. I guess it means there's problematic data in only one or two project records.

**Comment by bgirardot** [comment]
Hi Harry. We have an issue in here that is on the front end blank pages in the search results I wonder if this is the error in the back and that  causes the blank pages on the front end in the search results listing listing then a page with nothing then listing listing

**Comment by harry-wood** [comment]
Sounds plausible yes. I imagine it would easy to find and fix this by looking at the live logs (On what line of code is this "division by zero" happening?)

**Comment by harry-wood** [comment]
This error seems to have gone away. I just fetched all 136 pages without errors

**Comment by ethan-nelson** [comment]
Hi @harry-wood can't say I know what has "fixed" this, but good to know it is for the time being. I suspect it may be dependent on the number of projects. Alternatively, it may stem from the caching issues we had for a while. In any case, thanks for the follow-up!
