### ISSUE TITLE
Local install without set SMTP variables throws unhandled errors on email call

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#1115]
When I do a local development install, with no smtp support, when I try to add my email address to my profile i get the following error in the console:

> CRITICAL in user_apis [/home/bg/tasking-manager/server/api/users/user_apis.py:115]:
> User GET - unhandled error: please run connect() first

In the UI I get an error updating my contact details as well.

This is because I have no stmp environmental variables set.

Setting them to working smtp solves the issue, but it should gracefully recognize there is no smtp and give an error that indicates the issue.

It should really work with out smtp, but at least fail with a more useful message. Just needs to catch the exception in user_apis.py and remote a more specific error message.

**Comment by willemarcel** [comment]
Fixed on TM4
