### ISSUE TITLE
Set "use this image layer" every time I start a task

### ISSUE THREAD

**Issue by tordans** [hotosm/tasking-manager#1122]
This is a feature request to improve the transition from task manger to iD Editor. Looking at the image layer selection.

# My user journey
- I just started https://tasks.hotosm.org/project/4710?task=36 and the first thing I have to do is to check the image layer.
- I go back to the task page and read again "Please use Digital Globe imagery".
- So I check the iD Editor again, but cannot find this wording, there is "Digital Globe Premium Images" and "Digital Globe Standard Images". What should I use?
- I start cycling the two to check what might be newer, which IMO is impossible to tell for https://www.openstreetmap.org/edit?editor=id&#map=18/-1.59402/31.52544, since there is no telling if a street or building is in construction or demolished. In any case, I want to map, not to compare images …
- I recently learned about the image-date-layer in https://github.com/openstreetmap/iD/issues/2492#issuecomment-394138322, so I try this. But this does not help as well, since no image date is available.

So now, what should I do?
What is the right image to work with?
Depending on this selection I would remove houses and roads that others mapped.

I did a review of an area recently which was clearly mapped based on BING images and not the specified "some of the digital globe once". I had to remove and change most of what was done before. Most likely, because a mapper forgot to check the image layer after opening the editor.

# Goal

As a mapper, I want to trust the "start mapping with iD editor" button to provide the correct setup that was planned, so I just can start mapping. Without checking configuration.

# Suggestions

- Add the feature to set the layer that should be used when opening iD Editor (Same as with custom image layers); a quick workaround would be to always use a custom URL for all tasks; even if it mirrows the URL of an existing layer.

- Clearly specify the image layer one should use in the task. The same wording as the layer indes uses https://github.com/osmlab/editor-layer-index/.

- Push forward the date-feature for iD Editor discussed in this thread and the one linked there https://github.com/openstreetmap/iD/issues/2492#issuecomment-395445297.

**Comment by bgirardot** [comment]
@tordans Thank you very much for the detailed feedback. I think almost all of this is basically a training issue for the people who create projects, which we are addressing. 

It is up to the Project Managers who create the mapping projects to do a detailed review of the area, existing mapping and what imagery is the best imagery to use for mapping. It is also up to them to create clear instructions that should specify the imagery, exactly as you described so it matches what you find in the iD editor.

They can put the TMS end points for the available osm imagery layers in there now to have them automatically loaded as you point out. There is no UI for automatically adding those in the TM, but filling it in by hand is not especially difficult and not really a workaround.

There are some issues with imagery that make dating it quite difficult, but the project creators should be doing that before they create the project. As you can see on the iD issue you linked to, the comment I made with illustrations, there is unfortunately no way to automatically date DigitalGlobe Premium imagery at the moment and I do not see a solution to that any time soon. The project managers just have to spend the time to date the imagery at various zoom levels and try to clearly explain in the instructions what imagery to use.

**Comment by smit1678** [comment]
> could the task-manager-interface provide a dropdown of the editor-layer-index-options and save the layer as an ID, so the translation of the layer can be pulled and displayed for the user in the same way that she sees it in the iD Editor UI?

100% agreed that at minimum this should be handled. From the quick analysis in the [blog post about imagery layers used](https://www.hotosm.org/updates/open-imagery-for-humanitarian-mapping/), it's clear not many people fill in the imagery field and this could certainly be mitigated by making it mandatory. 

If we make the imagery metadata field mandatory, and include a dropdown using the iD layer index, this will then capture the right imagery source for the project and for every time a user clicks Start Editor, this should open iD up with the correct imagery layer enabled. 

Now additional instructions and training can happen around how to communicate using a second imagery layer -- in the case of clouds or using a second layer for confirming mapping.

**Comment by xamanu** [comment]
With the planned integration of iD into the TM (#1358) we can reevaluate the provision of .imagery as information we can pass on from the TM into iD.

**Comment by willemarcel** [comment]
Replaced by https://github.com/hotosm/tasking-manager/issues/3051
