### ISSUE TITLE
Extract EN strings for translation via transifex

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#1126]
We need to update the strings for transifex

**Comment by bgirardot** [comment]
If at all possible, if we could keep the strings NON Sorted, and just in the natural order they are found on the pages that would be best.

**Comment by bgirardot** [comment]
@ethan-nelson Is this something you could do for us as your convenience please? Or if there is a script in the code now if you could just point me toward it.

**Comment by Andygol** [comment]
😍 waiting for it ASAP

**Comment by bgirardot** [comment]
Ethan actually did the first step of this that I will review now. Yes, it needs doing. @Andygol thank you for the reminder.

**Comment by bgirardot** [comment]
Ethan did this, we have it, thank you @ethan-nelson
