### ISSUE TITLE
Retrieve archived projects using non-authenticated API request

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1127]
At present https://tasks.hotosm.org/api/v1/project/search endpoint outputs all `active` projects from Tasking Manager. When a session key is provided as a query parameter with this url, `archived` projects can also be retrieved. However, each session key seems to return the archived projects just once. Further API queries with the same session key returns only active projects. I could repeat this behaviour with my OSM user id (Project Manager access on TM) almost 3 times yesterday.

- Generate session key
- Use the session key with the test link in the [documentation](https://tasks.hotosm.org/api-docs/swagger-ui/index.html?url=https://tasks.hotosm.org/api/docs#!/search/get_api_v1_project_search). 
- Update the `projectStatuses` parameter to `ARCHIVED` and test the link

Would be great if the API could fetch all archived + active projects without the authentication key. This would be super useful to update stats in the new website, where the numbers are refreshed once every 6 hours. 

cc @smit1678 @sunidhiraheja

**Comment by bgirardot** [comment]
This has come up before I think. I think it makes sense to allow access to archived project by non authenticated users. Even the front end UI should probably allow mappers to included archived projects in their searches.

**Comment by ethan-nelson** [comment]
This has been added in #1130...will be pushed to master soon (TM).

**Comment by ramyaragupathy** [comment]
@ethan-nelson @sunidhiraheja How long would this take to reflect in the API testing interface at swagger? I'm checking this https://tasks.hotosm.org/api-docs/swagger-ui/index.html?url=https://tasks.hotosm.org/api/docs#!/search/get_api_v1_project_search

**Comment by bgirardot** [comment]
hi @ramyaragupathy Try:

https://tasks-stage.hotosm.org/api-docs/swagger-ui/index.html?url=https://tasks-stage.hotosm.org/api/docs#!/search/get_api_v1_project_search

that has the changes now. It will be next week sometime before it makes it to the production server.

**Comment by ramyaragupathy** [comment]
Thanks @bgirardot 🙏 , I'm able to retrieve the archived projects through staging 🎉
