### ISSUE TITLE
French language option and fr language project causes project to be listed twice

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#1131]
I am not sure what is happening here, but I added a set of French title, descriptions and instructions to a project and then switched my language to French to see how things looked.

Somehow that seems to have caused that project to be listed twice in the search results for the campaign, please see below.

![2018-07-04_13h34_48](https://user-images.githubusercontent.com/265831/42275242-f4f8454c-7f8f-11e8-9c9b-4629d65207ff.png)

**Comment by KMR-zoar** [comment]
In my environment(Japanese) too, same issue is available.

![jp](https://user-images.githubusercontent.com/6219187/42418939-019175ae-82e6-11e8-9613-1f73b6c2cea2.PNG)

It is displayed correctly in English.

![en](https://user-images.githubusercontent.com/6219187/42418940-08a86352-82e6-11e8-9f19-8ed5f310f86c.PNG)

I am running TM3 on my own VPS.
I have migrated TM3's database from TM2.
