### ISSUE TITLE
Move the "Detailed Instructions" section to the top of the instructions page

### ISSUE THREAD

**Issue by tawirth** [hotosm/tasking-manager#1139]
I often find that new mappers do not read down far enough to the "project specific mapping notes" which contain critical information such as aligning imagery to existing mapping.  I believe by making the specific instructions more prominent and simple we could improve initial data quality and reduce the workload on validators.

Would it be possible to move the "Detailed Instructions" section to the top of instructions page? 

This would allow project managers to create step by step instructions that would show up prominently at the top of the instructions page, e.g.

**INSTRUCTIONS**
1. Align DG Premium imagery to existing mapping (Link to how to)
2. Trace buildings and square them (Link to how to)
3. etc...

Below the step by step you could have additional details, but the steps would cover the most important points in a sequential manner.

Thank You,

Troy

**Comment by xamanu** [comment]
Thanks for contributing your idea! This has been addressed in the [current redesign](https://github.com/hotosm/projects/issues?q=is%3Aissue+label%3A%22ML4TM+Design%22) with @hotosm/major.
