### ISSUE TITLE
Messaging by Role

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#1143]
A new feature/modified feature request to enable the ability to message all users with a specific role. This could be useful at a project, campaign or even TM instance scale. 

Example/Use Cases
- Administrators messaging Project Managers about new features, tips to keep from exceeding TM capacity/capabilities, etc.
- Project Managers messaging all Validators on their project(s) with tips/thanks/etc.
- Maybe even Validators messaging all mappers on a project?

**Comment by xamanu** [comment]
As we talked today with @hotosm/major I wanted to highlight this as another request for messaging, besides the ones we have been talking about.

**Comment by willemarcel** [comment]
We're adding the possibility to message team members on #2938
