### ISSUE TITLE
Modal dialog to collect email address on first login

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#1146]
When users first log in to the tasking manager they have a message that suggests they provide their email address.

It would be more effective if on first login, we put up a modal dialog that very nicely, explained why it is so important they put in their email address, which is optional, but very important to our mapping process we can communicate with them, and provide them a field to fill it in right then and there so they do not have to do anything else or click anywhere etc. Just provide it once and done.

**Comment by xamanu** [comment]
Closing here in favour of #1365
