### ISSUE TITLE
Adding more stats

### ISSUE THREAD

**Issue by sunidhiraheja** [hotosm/tasking-manager#1147]
This issue is meant to track the development of the `/stats` endpoint.
Here's a list of all features (existing and planned):

Homepage
- [x] Mappers online
- [x] Tasks mapped
- [x] Tasks validated
- [x] Total mappers
- [x] Total number of users who validate
- [ ] Total area mapped and validated
- [ ] Average task completion time
- [x] Number of projects by organization
- [ ] Enable querying by date

User stats
- [x] Mapper level progress indicator
- [x] OSM details
- [x] Contributions to projects (tasks mapped and validated)
- [ ] Total area mapped and validated
- [x] Total time spent mapping

Project stats
- [x] Activity log
- [x] List of contributors with # of tasks mapped and validated
- [x] % mapped and validated
- [ ] Total area mapped and validated
- [ ] Average task completion time
- [ ] Estimate of when a mapping project will be completed based on past contributions [#1083](https://github.com/hotosm/tasking-manager/issues/1083)
- [ ] Graph for mapped and validated tasks [#931](https://github.com/hotosm/tasking-manager/issues/931)

Suggestions welcome!

**Comment by dalekunce** [comment]
Love the list. For users I'd add total _tasks_ mapped and validated. I would also enable date queries for almost all of these that you have listed.

**Comment by russdeffner** [comment]
This is great @sunidhiraheja - thank you!
Regarding User stats:
* What "OSM details" are you thinking? Total changesets, age of account, etc? 
* For 'contribution to projects' I would also include total number of projects contributed to (i.e. mapped and/or validated on X projects).
* And last, would include projects created; maybe only displayed if given PM or Admin role.

**Comment by giblet22** [comment]
In addition to @dalekunce user stats, the number of times a user has been invalidated would be useful for mapper engagement. 

Another would be amount of comments a user has made. This would be lower priority I think because I'm not sure if the payoff is worth it. But shows if users are engaging with others.

**Comment by bgirardot** [comment]
one additional thing that is only slightly related, but I will mention it in case it fits into the development somehow:

list of the individual tasks someone has marked done, and more importantly, marked validated :)

We will often find a new person doing validation, not very well, then we have no way to find all the others ones they might have validated. There is an issue for this already, but seeing the discussion about tasks validate and mapped, I thought I would mention it here.

**Comment by govvin** [comment]
It would be helpful to have separate information about regions marked as priority areas, about how many tasks are outstanding, or the percentage of what's been mapped, or validated.

**Comment by MelEckle** [comment]
Hi all! And thank you for the great work @sunidhiraheja! We (GIScience Research Group Heidelberg/HeiGIT) are currently working on stats for Missing Maps in which we also make use of the Tasking Manager API. I was already in touch with Nate as well as we would therefore need a direct API request that allows to filter changeset comments in projects. As of now we have to 1) request all projects, 2) store them locally, 3) search for all #xxx in the comments and 4) Filter relevant ones. This is working as well, but not the ideal way. we are for sure happy to support or provide further details.

**Comment by smit1678** [comment]
@MelEckle To add to this based on our Slack chat, it sounds like in addition to querying by date that querying by `changesetComment` might be useful to be able to aggregate projects based on a common term instead of via an organization or campaign. 

A slight challenge here is that we would need to parse the comment field into its individual comments to then be able to search by them. But in general this seems like a potentially useful way to filter the aggregated stats. 

Discussion point: In some ways this type of tracking should be better integrated into the campaign or grouping feature and that we're solving an old problem by enabling filtering based on comment hashtag. Other thoughts?

**Comment by MelEckle** [comment]
Thank you Nate,
> it sounds like in addition to querying by date that querying by changesetComment might be useful to be able to aggregate projects based on a common term instead of via an organization or campaign.
Exactly, basically looking for all projects with specific #, however then also in following step checking for the different campaigns and organizations

**Comment by arunasank** [comment]
Would love to see additional task related stats at the project level, like
* Total number of tasks
* Number of tasks locked
* Number of tasks validated
* Number of tasks mapped
* Number of tasks completed etc

**Comment by matyasbach** [comment]
Hi!

+1 for _Enable querying by date_, especially for _/stats/project/{project_id}/activity_.

And adding `mappedValid/mappedInvalid` for individual users to _/stats/project/{project_id}/contributions_ would be very helpful (we'd like to show that on dashboard to motivate users not only for quantity but also for quality).

**Comment by xamanu** [comment]
A lot of work has been gone into improving the stats and this issue has become superseeded by many others. Closing here.
