### ISSUE TITLE
Add ability to sort Contribute list of projects by number of active mappers

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#1151]
In some cases it would be very useful to see what projects mappers are working on. 

Use cases are several:

As a validator I want to see where the most activity is so I can validate while people are online and mapping.

As a system administrator I would like to know what projects have the most active mappers while troubleshooting any system issues.

As a project manager I would like to know what projects are getting the most mappers so I can understand how to better draw mappers to my projects.

**Comment by sunidhiraheja** [comment]
Should I sort them by decreasing number of active mappers by default, or provide an option?

If it's the second, then what are the other possible parameters to allow sorting by?

**Comment by ethan-nelson** [comment]
I think the idea would be to have a `sort by` menu (like on TM2...example instance still live at http://tasks.openstreetmap.in/) with one of the items being active mappers.

But we default to sort by priority already, so a problem/decision to be made is whether to include priority in that menu as an option (defaulted on) or always keep the results sorted by priority. I guess a third option could be to break priority sort into a separate clickable option. Further thoughts @bgirardot

**Comment by xamanu** [comment]
Bringing this up to the attention of @hotosm/major, because there are good plans to introduce a sorting functionality: Check out https://github.com/hotosm/projects/issues/19

**Comment by xamanu** [comment]
We included a sort option for "active projects" in the explore projects (former contribute) section in TM4. This should address the motivation for this request.
