### ISSUE TITLE
Show exact time in "time ago" alt text

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1152]
The prior version of this software displayed the exact date and time whenever hovering over the "X ago" under a given history element. We should try to implement the same here.

I previously attempted this in https://github.com/hotosm/tasking-manager/pull/1155/files, but the area where this is added has changed a bit. So this issue involves taking the changes in #1155 and adding them to the correct locations in the updated files.

**Comment by stufinn** [comment]
I'd like to give this a shot!

**Comment by ethan-nelson** [comment]
Fixed with #1226
