### ISSUE TITLE
Refactor project page refresh

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1153]
The basic idea here is to create a new endpoint for project refreshes that contains the project metadata and _only a portion_ of the task information after initial loading.

### Background 

As a user sits on a project's page--mapping, validating, or watching--their browser is polling the `/project/#` endpoint [every 10 seconds](https://github.com/hotosm/tasking-manager/blob/1fdba13050a3f8dc3b7a16547858cdf74e3aef4a/client/app/project/project.controller.js#L130). This [API endpoint](https://github.com/hotosm/tasking-manager/blob/1fdba13050a3f8dc3b7a16547858cdf74e3aef4a/server/api/project_apis.py#L13-L75) returns to the user's browser the full project metadata and information about every task: geometry, status, history ([example here](https://tasks.hotosm.org/api/v1/project/3000)). 

While this information is necessary to initially populate the project page, it is not necessarily needed for every refresh cycle. We really only need information to keep the map animated with task statuses (as users lock, unlock, mark mapped, mark bad imagery, validate, or invalidate tasks; or when priority areas are modified), though there is a caveat related to task splitting that will be addressed below.

### Work required

This will touch on both backend and frontend code.

On the backend, a new API endpoint will be required (something like `/project/#/status-update` or a better verb there). This endpoint either needs a new project service and project model function to provide this, or function calls added to the [existing project service](https://github.com/hotosm/tasking-manager/blob/1fdba13050a3f8dc3b7a16547858cdf74e3aef4a/server/services/project_service.py#L46) and [model function](https://github.com/hotosm/tasking-manager/blob/1fdba13050a3f8dc3b7a16547858cdf74e3aef4a/server/models/postgis/project.py#L377-L384) to not include coordinates.

For the frontend, the current refresh mode will be utilized initially (and perhaps every few minutes just for safety's sake), while the update endpoint will be used in between at a similar frequency to the current refresh cycle. The js will need a new function to poll the new point, read the update version of the json, and update the task status on the map based on id number of each feature (since geometry is not included). Furthermore, **it is important to note** the number of tasks will need to be retained and compared against every subsequent update. This is because tasks can be split, altering their geometry, ids, and count. If the frontend notices the number of tasks has changed, it should revert back to the original endpoint to update the geometry of the task features along with everything else.

### Refactor benefits

This will improve performance nearly everywhere. For the mapper, their bandwidth and browser resources will be decreased as the volume of data transfer and processing will decrease. For the TM host, database load will be reduced as queries for geometry will be removed, web server load will be reduced as these geojson objects will not have to be built, and bandwidth will be reduced by lowering the amount of data transferred. These savings will be significant particularly on projects with complex geometries (testing on complex projects that are live have yielded upwards of 2 MB of uncompressed geojson per 10 second refresh). Though it is noted above that the original endpoint will need to be utilized in the event of task splitting, that does not occur on a frequent enough scale to minimize the use of this proposed refactor.

**Comment by hunt3ri** [comment]
@ethan-nelson love the idea.  One immediate thought to reduce load on the database would be to cache the response for the project, using a LRU cache.  Do you know how much available memory the servers in production have, what size of instances are you running on?

To give you an indication we could cache the project response for 1 second, which if you say can be up to 2 mb.  We could cache the project response for 100 projects which would use up 200Mb on the server across 5 gunicorn workers, so that would consume 200x5 = 1Gb of memory per server.

Of course if more than 100 projects are being worked on simultaneously we lose some of the benefit, but if you were using amazon m5.large servers, you'd have 8Gb per server, so you could easily afford to cache 200 projects or 2Gb of memory

cc @smit1678

**Comment by xamanu** [comment]
Is this done by merging in #1514? Or are there follow ups that need to be addressed @ethan-nelson?

**Comment by ethan-nelson** [comment]
Should be good--will close out. Re memory, not sure now that we are moving to a new deployment stack.
