### ISSUE TITLE
Include project created date in `fetch by project id` endpoint

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1162]
I'm currently working on improving the mapviz for [country pages in HOTOSM website](https://www.hotosm.org/where-we-work/india/). As part of the [proposal](https://github.com/hotosm/hotosm-website/pull/351), we have a year filter for projects, wherein the end user gets to filter out tasking manager projects by the year in which the project was created.  TM API returns the created date with the project summary endpoint. It'd be great if this could be integrated with the  project id endpoint as well: https://tasks.hotosm.org/api-docs/swagger-ui/index.html?url=https://tasks.hotosm.org/api/docs#!/mapping/get_api_v1_project_project_id

For the current visualisation changes in the HOT website, we're using a lambda that preprocesses data from multiple sources - missing maps, TM and generates relevant datasets for the website. We get most of the project details from the project id endpoint, except for created date. Now including a summary endpoint is helpful for created date, but results in duplicate data storage for nearly 4K projects leading to memory failure. So It'd be super useful to have the project created date included in the project id endpoint

cc @smit1678 @bgirardot @ethan-nelson

**Comment by ethan-nelson** [comment]
Easy fix--I will do it tonight!

**Comment by ramyaragupathy** [comment]
Thanks @ethan-nelson! I could see the changes in the staging  https://tasks-stage.hotosm.org/api/v1/project/3597?as_file=false
