### ISSUE TITLE
querying for invalidatated tasks

### ISSUE THREAD

**Issue by govvin** [hotosm/tasking-manager#1164]
Is there a way to query or find for invalidated tasks in your project? I just realized this isn't easy with arbitrary geometries that cover large areas, unlike square grids.

![image](https://user-images.githubusercontent.com/5821688/44128836-b0c030b6-a077-11e8-9952-1986f6f30385.png)

**Comment by ethan-nelson** [comment]
Do you mean from a standpoint of a user on the TM or data consumption in general? For the former, it may already be covered by the select random tile functionality but I can double check. For the latter, it's probably easiest to poll the project API (https://tasks.hotosm.org/api-docs/swagger-ui/index.html?url=https://tasks.hotosm.org/api/docs#!/mapping/get_api_v1_project_project_id) and iterate through tasks to look for an INVALIDATED status.

**Comment by govvin** [comment]
Hello  @ethan-nelson. I meant from the standpoint of a user, specifically a validator or a a project manager,  who may be monitoring the project on the TM.

**Comment by xamanu** [comment]
This shall be covered by https://github.com/hotosm/tasking-manager/issues/1360, which is going to be part of the next release. Closing here.
