### ISSUE TITLE
Switching branding to default

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1167]
This is perhaps a bit more long-term goal...

We've had some complaints in the past regarding TM instances that were not run by HOT but were thought to be because the default style is HOT, the default changeset comment is HOT, the default contact information is HOT, or so on out of the box. I know this came up during one of the planning sessions as well.

So, we should consider whether we want to neutralize the default branding in the TM3 repo. From the HOT perspective, this would require some work on the deployment pipeline in terms of integrating the customization back to what it was before the removal. As I can find time to play around with this some more, I will keep adding thoughts and info at https://github.com/hotosm/tasking-manager/wiki/Customizing-the-TM3 for other deployments in the mean time.

**Comment by smit1678** [comment]
@ethan-nelson Good point and I think this would be helpful for others to setup and run there own version. Relatedly, here's a question for priority: do we want to whitelabel deployment as well? I almost feel like the deployment code is a higher priority as it can help streamline contributions back. As we look to incorporate back some work from other groups running TM3, I know there have been some complexities merging things back based on how we have our elastic beanstalk and other custom HOT deployment code within the repo as well.

**Comment by xamanu** [comment]
This is ongoing work with the current design imrprovements with @hotosm/major https://github.com/hotosm/projects/issues/17

**Comment by xamanu** [comment]
Closing here in favour of #1383.
