### ISSUE TITLE
Clicking the "Contribute" tab should reload the page with no filters applied

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#1168]
It is often a UI navigation comfort that you can always click on a navigation element and have it take you to that page, even if you are already on that page. It will generally reload the page so you can start over on something.

The TM should do that with the Contribute link. It should clear all the current searches and filters and display the page as if you had just clicked to land on it for the first time.

also see issue #613, No way to clear searches, this is related. If there was a "clear" button, people like me would not click on the Contribute tab trying to get the page to reload and clear our search / filters.

**Comment by matizzy** [comment]
Hi guys, can I take on this issue?

**Comment by ethan-nelson** [comment]
Hi @matizzy sure, I will mark it as in progress. Please let me know if you have any questions or troubles.

**Comment by Redarcher9** [comment]
Hii, is someone still working on this issue?

**Comment by matizzy** [comment]
@Redarcher9 Hi yes sorry, I am. I had a busy week at work but I'm gonna finish it up today or by tomorrow morning.

**Comment by matizzy** [comment]
https://github.com/hotosm/tasking-manager/pull/1208

I opened a PR for this issue

**Comment by xamanu** [comment]
This works now on the new frontend in TM4.
