### ISSUE TITLE
Add "role" to project manager

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#1177]
Someone from TeachOSM suggested that there should be a profile item that specified the project manager's role to help identify who they are, like "Professor" or "Mapping Coordinator". This could help users and TeachOSM staff to know more about the project manager.

**Comment by kishan3** [comment]
Hi, Which file and folder is this project manager?

**Comment by willemarcel** [comment]
We're adding the possibility to message team members on #2938
