### ISSUE TITLE
Re-arrange buttons on TM3  map page

### ISSUE THREAD

**Issue by FransS1945** [hotosm/tasking-manager#1181]
Re arrange buttons on Main page of TM3 

https://tasks.hotosm.org/project/5025?task=89

First button shows "marked as completely mapped."
Exchange this with the "stop mapping" button
Why?  I see often tasks which has been marked as "completely mapped" despite there are still a lot of objects to be mapped. 
Fact is that many mappers can contribute on a task and stop mapping, leaving the task open for other mappers. But there is just 1 mapper who declare a task as "complete mapped" 
So this button should not be positioned on top should I think.
When I took a look to the mappersprofile who declared a task as complete mapped, mostly the are new mappers.
I questioned several mappers about the why, they responded that they just wanted to stop mapping.
It seems that they have no idea what this button means. 
Changing the "stop mapping" button to the first line can solve this. Change colour as well ?

![screen shot 09-05-18 at 02 17 pm](https://user-images.githubusercontent.com/31804031/45092739-a4f95280-b116-11e8-9d50-bd25945f3fae.JPG)

**Comment by smit1678** [comment]
@FransS1945 thanks for opening this ticket. This has been seen before and I think we can improve the layout with some simple changes. 

Adding some initial guidance that I think would be an improvement to the experience here. This is from a brief conversation between @ramyaragupathy and myself about how we could reorganize. 

<img width="474" alt="wireframe cc - minimal wireframing tool 2018-10-01 12-58-25" src="https://user-images.githubusercontent.com/796838/46272135-ea743880-c579-11e8-99d0-fcbf188a68e3.png">

The thinking here is that we can add some more text instructions and then separate the type of actions. For the stop and mark as completely mapped, we order them according to flow. You may need to stop mapping before you mark it completely mapped. For all buttons, we add a simple icon that helps users understand what the action is. 

✋ icon for Stop Mapping (a hand or stop sign icon)
💯 icon for Mark as Complete Mapped (a 100% icon)
❌ for Mark as Bad Imagery (some type of X icon)
🔲 for Split Task (some type of square grid icon)

Other comments: set to a single color and use order and icons to communicate hierarchy and action.

Open for discussion or other ideas for how we could implement these improvements.

**Comment by goldfndr** [comment]
For the Split Task icon, how about  :heavy_division_sign: (heavy division sign)?

* Universal division symbol
* Similar look to how the grid square gets divided

**Comment by FransS1945** [comment]
Yes, for my intuition it looks better.
Thaks,

**Comment by jillhkm** [comment]
Hello,

I would like to contribute to this project. Are you looking for someone to update the UI with the new icons?

Thanks!

**Comment by smit1678** [comment]
@jillhkm Yes, we’re looking for someone to update the layout of the section (along the lines of the wireframe above) with the text updates and icon additions. Is that something you want to take on? If so, we can mark this in progress. 

Post if you need some more clarification on the wireframe or have other ideas for ways that we could improve the layout.

**Comment by jillhkm** [comment]
@smit1678  
Hi, so I submitted a pull request that adds the desired icons to the buttons. However, I am having trouble running the project locally, so I wasn't able to rearrange the buttons. 

I was trying to run it on cloud9.  I'll keep trying though!

Thanks

**Comment by ethan-nelson** [comment]
As I understand it, this was mostly solved in #1206 and #1220. Please let me know if that is not the case.

Thank you to @jillhkm and @ramyaragupathy for your contributions! This looks much neater.
