### ISSUE TITLE
Bugs in TM2 to TM3 migration script.

### ISSUE THREAD

**Issue by wildintellect** [hotosm/tasking-manager#1183]
- [ ] Admin users are not mapped from previous value of 3 to new value of 1.
- [ ] ln 72 & ln 77 should be hotold.project not hotold.projects
- [ ] The instructions on using the script should be updated also, as it can be very tricky to get both osmtm2 and osmtm3 schemas into the same db with postgis working. Based on https://github.com/kleper/Cartografia/blob/master/MigratingTM2toTM3ENG.md

1. My recommendation is create the new database based on the old one.
2. Create the hotold schema
3. ```ALTER TABLE <tablename> SET SCHEMA hotold;``` To move the 14 old tables to the hotold schema
4. run the migrate.py upgrade to create a new public schema with the new tables
5. run the migration.sql with the appropriate schema names.
6. remove the hotold schema an vacuum.

I'll try and get some of these changes and suggestions into a pull request.

**Comment by wildintellect** [comment]
Worked with the changes mentioned in the ticket. 

- I should be clear https://github.com/hotosm/tasking-manager/blob/develop/devops/tm2-pg-migration/migrationscripts.sql is the script.
- To create a db based on an existing do something like ```CREATE DATABASE osmtm3 WITH TEMPLATE osmtm2 OWNER "www-data"; ```

**Comment by ethan-nelson** [comment]
Great, thank you for the info and for your diligence in completing this task @wildintellect ! If you'd like to file a PR, that would be welcomed. Otherwise, I will eventually transfer some of this information over.

**Comment by ethan-nelson** [comment]
Hi again @wildintellect thank you again for all of your feedback. I have updated the wiki page at https://github.com/hotosm/tasking-manager/wiki/Migrating-from-TM2-to-TM3 and am now working on a PR to address these issues (#1307)!
