### ISSUE TITLE
Improving search fields in the Tasking Manager API

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1184]
I've been currently working on data collation for the [website's project page](https://www.hotosm.org/projects/urban_innovations_crowdsourcing_non-camp_refugee_data). This involves matching relevant tasking manager projects to the [larger HOT project files ](https://github.com/hotosm/hotosm-website/tree/gh-pages/_projects)in Github. A few approaches I tried include:
- Simple text search
- Search by Organisation tag
- Search by Campaign Tag
- Combining text search + tag search

_Including the [search results](https://paper.dropbox.com/doc/Project-matching--AMz5nGWAf6cCaZHZCitaQZCjAg-pPsHSEwNuBO3G60jXdqU4) of all the existing HOT projects._
 ### Observations 🔍 
**Text Search**: This searches for the words in the project description and it picks all those projects with at least one matching word. If the search is for `nepal earthquake`, results include projects containing the keyword  `earthquake` + `nepal`. So this is not an exact filter as it return all the projects related to earthquakes and not just `nepal earthquake`. So a major flag here is:
🔴 Finding the right keyword for larger HOT projects

**Tag Search**: These are case sensitive and returns only projects with exact text match. Certain flags here:
🔴 Tags are not always consistent across projects. For Eg: campiagn tag could be `ramani huria` or `Ramani Huria`. Organisation could be `Clinton Health Access Initiative` or `Clinton Health Access Initiative (CHAI)`. 
🔴  Tags are used across projects, so this has to be always combined with text search for closer results. But with inconsistent tags combining fields doesn't help

### Immediate solution for project pages 🚢 

Initial idea was to use the API to return project results and have the script run on a regular basis to update the list. But since the results are not a very close match, we've to stick to manual options. 

### Long term ideas 💡 

**At the API level**

- Include a name search field
- Revisit the search algorithm for better matching

**At the project management level**

- Project managers to decide on tag for a larger HOT project 
- Pre-populate tag names during project creation thus forcing the user to stick to existing tags

cc @smit1678 @ethan-nelson @dakotabenjamin @bgirardot

**Comment by xamanu** [comment]
This has been implemented for TM4.
