### ISSUE TITLE
Automatically Unlocking Tasks

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#1185]
There are some tasks that are 'automatically unlocking', such as https://tasks.hotosm.org/project/5236?task=1554 and https://tasks.hotosm.org/project/5025?task=1365
![auto-unlock](https://user-images.githubusercontent.com/6763645/45597860-76d60700-b98f-11e8-887a-2cc0241aec51.PNG)

This is causing many contributors to try locking these tasks many times, and projects to not be 'complete'.

**Comment by lusdavo** [comment]
This task as well automatically unlocking: https://tasks.hotosm.org/project/5129?task=58
