### ISSUE TITLE
Adjust onboarding experience to better capture data and provide information to the user

### ISSUE THREAD

**Issue by smit1678** [hotosm/tasking-manager#1186]
Creating an overarching ticket regarding potential onboarding improvements to include for consideration on the development roadmap. From feedback and discussions, there are several ways that onboarding could improved in the near term. To define onboarding -- the process of registering/signing in, filling out your profile (including email), receiving any training instructions, and getting to your first task. 

### Problem Summary: 

For new users, it is easy to miss adding your email. We provide a message in your profile with instructions but this is easy to pass over. We also do not collect any other information about users to help provide the right training materials. We do not provide a tutorial walkthrough or feed a user into an example project to test their skills. We also do not provide any guidance for getting to the right project that meets their skill level. 

### Considerations for improvements: 

* Change the experience for first time users. For users that have never logged in, create a new experience for capturing the required information like email or other additional profile information that makes communicating and understanding who they are better. Related to https://github.com/hotosm/tasking-manager/issues/1146
* Collect additional information upon sign in. This could be demographic or other information that can help provide feedback to mappers.  
* Provide a walk through for training. Users are required to step through an interactive that tells the steps to good mapping
* Provide an example test project that a user can practice on
* Change the experience on the contribution page to better expose projects and training materials for for first time users

**Comment by dakotabenjamin** [comment]
I'd like to add an idea to this:
- implement gamification to increase user experience and promote returning user
- add information about creating an OSM account

**Comment by smit1678** [comment]
Last week we held a brainstorming session between project managers and mappers on potential ways to improve the onboard process. I added some notes here in a wiki page: https://github.com/hotosm/tasking-manager/wiki/Onboarding-Idea-Generation-Session-Notes. 

One of the next actions from all the ideas was to propose an initial path forward for some incremental improvements. First I'd like to take a look at some data within the TM database around percent of users who have logged in (since the relaunch) who have added their email.

**Comment by russdeffner** [comment]
In Jakarta we had a chance to chat about this. I like the idea of the TM creating 'buckets' for users that determine where they land when logging into the TM.

Thought of 3 categories/buckets of users:

-  New to OSM: these mappers need to go create an OSM profile and think the way it works currently when people try to log-in is fine for this; however, when they return to the TM with a brand new OSM profile the first time, maybe it should go straight to their profile (or separate 'training'/landing page) that asks them to complete their profile (add email and SM to 'stay in touch with the community'), watch a few how-to videos, links to LearnOSM.org, etc. and maybe suggests to them the highest priority beginner project to start with.
- New to HOT/TM but have existing OSM username with edits: these mappers may need a bit of explanation on the TM but not as much basic OSM help. Not sure this would be same landing as brand new folk with a difference emphasis/wording/videos but should get them to the contribute page quicker.
- Experienced HOT Mappers - if they have a decent history with the particular TM, then they should maybe just go straight to the contribute page.

**Comment by smit1678** [comment]
> First I'd like to take a look at some data within the TM database around percent of users who have logged in (since the relaunch) who have added their email.

Did a quick look and it's only 4%. This is quite low but a starting point for where we can improve. 

To help get started, I created two new tickets around these issues at the moment: 

1. Create an onboarding modal for new users https://github.com/hotosm/tasking-manager/issues/1244. This only focuses on new users at the moment but would be a starting point for how we can extend.
2. Flag for existing users without email address https://github.com/hotosm/tasking-manager/issues/1243. This looks to help alert existing users that they are missing information.

**Comment by xamanu** [comment]
This is connected with #1370 - "New fields for user profiles to encourage interaction".

**Comment by xamanu** [comment]
This is related to the ongoing design work of @hotosm/major

**Comment by xamanu** [comment]
As we moved the wiki to the code base I copy here the session note @smit1678 linked to earlier:

> *Notes from onboarding brainstorming session with HOT Indonesia team, Mhairi O'Hara, Russell Deffner, Ramya Ragupathy, and Nate Smith on Sept 25.*
> 
> We held a short meeting to dig into onboarding within the Tasking Manager. Purpose was to dig into https://github.com/hotosm/tasking-manager/issues/1186. We held an exercise to dig into the problems that we wanted to solve and potential ideas to implement. We ran an exercise where we each envisioned a workflow/userflow for onboarding new users. 
> 
> All 10 of us came up with an idea and discussed it. Pictures from the whiteboard below. Next actions to be captured here soon which include proposing an MVP near-term solution, determining what and if we need to gather some more data, and setting a longer-term vision for continual improvement.
> 
> ![Alt text](https://monosnap.com/image/84wNJLRS5csjpkT4l3sOfsZsRTK2cj.png)
> *Problem identification*
> 
> ![Alt text](https://monosnap.com/image/43qsPelslRSuJzNGn5OCzs8MsvpoYq.png)
> *Workflow sketching*

**Comment by xamanu** [comment]
This has been extensively reviewed and tested for TM4. Feedback has been excellent.
