### ISSUE TITLE
Show loading text when project is loading

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1188]
Right now, when a user navigates to a project, the project template is shown immediately without information from the API. For users on lower bandwidth connections, there is no communication about what is happening. So, it would be good to display some sort of loading text while the project API is loaded. I added a simple loading feature in #1154 for the search window--perhaps that could be a start for this.

**Comment by ethan-nelson** [comment]
Here's an example:

<img width="1375" alt="screen shot 2018-09-27 at 6 55 34 am" src="https://user-images.githubusercontent.com/8998918/46150842-642ac000-c222-11e8-9cb4-533f13195390.png">

**Comment by ethan-nelson** [comment]
Hi @htalat great! I will mark the issue as in progress since you are working on it. Please let me know if you have any questions.

**Comment by htalat** [comment]
okay! will get started on it in a couple of days ... hope it's okay!

**Comment by htalat** [comment]
is there any way seed sample data into the db?

**Comment by uwaiszaki** [comment]
@ethan-nelson I would like to work on this.

**Comment by xamanu** [comment]
This has been addressed by @uwaiszaki in PR https://github.com/hotosm/tasking-manager/pull/1410. Thanks! Closing here.
