### ISSUE TITLE
Show loading text when Contribute page is loading

### ISSUE THREAD

**Issue by smit1678** [hotosm/tasking-manager#1189]
Related to #1188, on slow connections Contribute page displays `No projects found` on the page before the data is loaded. This can be confusing as it's unclear whether there is a real error or that the data is being loaded. Sometimes it takes 10 seconds for the data to load when on a slower connection. 

Potential improvement to the experience would be to add a loading indicator instead of default text. If error, show an error or `No projects found` message. 

<img width="1274" alt="hot tasking manager 2018-10-01 09-43-51" src="https://user-images.githubusercontent.com/796838/46267384-ce16d280-c55e-11e8-95cf-2e56d9cf0b88.png">

**Comment by ethan-nelson** [comment]
This should be fixed in #1154 but may perhaps be implemented another way.

**Comment by smit1678** [comment]
@ethan-nelson Ah I totally read that ticket but missed that you had implemented a solution here. I will close this and we can reopen if this should be implemented in another way in that PR.

**Comment by ethan-nelson** [comment]
No sweat :)

**Comment by xamanu** [comment]
This isssue shall be fixes once #1410 comes in.

**Comment by xamanu** [comment]
TM4 is showing a preliminary screen while loading that show that clearly to the users.
