### ISSUE TITLE
Add ability to generate auth token in user profile

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1197]
Right now, there is no way for a user to generate an authentication token for API except to carve it out of the HTTP headers after logging in. This is a request to add an authentication token generation ability in the user profile. It would ideally be a button you click that either opens a modal with the key or populates a disabled text box near it with the key.

This will require creating an API endpoint:

1. That receives a user authentication token;
2. If valid, [generates another user authentication token](https://github.com/hotosm/tasking-manager/blob/develop/server/services/users/authentication_service.py#L124-L134); and
3. Returns the new authentication token.

Additionally, the front end will then need:

1. A new promise to access that endpoint;
2. A button to activate the promise; and
3. Populate either a model or a disabled text box with the received auth token.

**Comment by ethan-nelson** [comment]
I split the up into two components because the API endpoint could feasibly be added first separately, then the front end added later by another person or PR.

**Comment by jtj9817** [comment]
I would like to try to work on this issue!

**Comment by ethan-nelson** [comment]
Great, I will mark it in progress!

**Comment by uwaiszaki** [comment]
@ethan-nelson I would like to work on this.

**Comment by ethan-nelson** [comment]
Hi, we've actually transformed this a bit in #1349. Within that is the ability for an application based auth token to be generated. The issue with exposing the ability to generate regular user auths to web users is that a compromised account could be compromised in perpetuity by a malicious actor generating a new auth token before the previous one expired. Instead, the application based auth token allows certain users to generate a new class of tokens for auth that can be revoked at any time instead.

**Comment by ethan-nelson** [comment]
In fact, I'm going to go ahead and close this issue since I consider the original ability no longer preferable. Thanks for the interest in this one, though!
