### ISSUE TITLE
Documentation: Dockerfile etc 

### ISSUE THREAD

**Issue by flohoff** [hotosm/tasking-manager#1207]
Hi
i tried setting up a local task manager quickly in Docker so i built the Docker image

docker build -t tasking-manager3 .

Then i created a postgres user, database and password and a docker.env file and started the container with:

docker run --rm -p 8000:8000 --env-file docker.env -it tasking-manager3

Which starts a container with the newrelic -> gunicorn WSGI - And now? All urls at localhost:8000 i tried return an error - no debugging

I fail to find the 5 commands i need to setup a tasking manager instance in docker.

Flo

**Comment by ethan-nelson** [comment]
Hi Flo, thanks for opening this ticket. Could you talk about what environmental variables you are setting in the docker.env file? And what error appears?

My first guess would be that the `TM_ENV` variable is set to something other than `Dev`, [which affects the URL at which the server is available from](https://github.com/hotosm/tasking-manager/blob/develop/server/config.py). However, that data will provide some more info on the problem.

**Comment by xamanu** [comment]
This is resolved with the latest inclusion of #1419
