### ISSUE TITLE
Finnish language translation

### ISSUE THREAD

**Issue by ernoma** [hotosm/tasking-manager#1214]
Finnish translation is missing. I am about to contribute Finnish translation for the Tasking Manager and I have quite a lot [experience on using the Tasking Manager](https://tasks.hotosm.org/user/erno).

@ethan-nelson You mentioned the translations in the HOTOSM Slack 4th of October, so I just want let you know that I am working on the Finnish translation. I have read the [Localisation page](https://github.com/hotosm/tasking-manager/wiki/Localisation) and the [Contributing page](https://github.com/hotosm/tasking-manager/blob/develop/CONTRIBUTING.md).

@bgirardot You seem to have accepted requests in Transifex before, so I just created a request to include Finnish language to the Tasking Manager 3 tasks, so that I could also request to be included in the translation team and proceed.

**Comment by ethan-nelson** [comment]
@ernoma I have now added Finnish as a language on Transifex. Additionally, I imported the file from your PR into Transifex so the translations are mostly finnished! The remaining ones are likely strings we no longer have in the TM (but Transifex retains in case they are added back I guess). I will review and merge the PR when I am home this evening!

**Comment by ernoma** [comment]
@ethan-nelson Thank you! I am happy to hear that the translation is welcome!

**Comment by ethan-nelson** [comment]
Closing due to #1215 merge
