### ISSUE TITLE
Review unreviewed translations on Transifex

### ISSUE THREAD

**Issue by smit1678** [hotosm/tasking-manager#1218]
Currently on Transifex we have 25 languages: https://www.transifex.com/hotosm/tasking-manager-3/dashboard/. Support for reviewing existing translations is need. Below is a list of what's been completed and what's left for review. 

#### Languages that are fully translated but need review of some or all strings: 

* [ ] Chinese (Taiwan) (zh_TW)
* [ ] Czech (cs)
* [ ] Dutch (Netherlands) (nl_NL)
* [ ] French (fr) 
* [ ] German (de)
* [ ] Japanese (ja)
* [ ] Polish (pl)
* [ ] Portuguese (pt)
* [ ] Spanish (es)
* [ ] Ukrainian (uk)

#### Languages that are not fully translated but have strings that need review: 

* [ ] Finnish (fi)
* [ ] Norwegian Bokmål (nb) 
* [ ] Slovenian (sl)
* [ ] Malagasy (mg)
* [ ] Vietnamese (vi) 
* [ ] Portuguese (Brazil) (pt_BR) 
* [ ] Hungarian (hu) 
* [ ] Galician (gl)
* [ ] Russian (ru)
* [ ] Persian (Iran) (fa_IR)

**Comment by ethan-nelson** [comment]
Please ping on this PR with your username if you need access to Transfix and we will make sure permissions are added!

**Comment by agnesoshiro** [comment]
Hi! Happy to help review Japanese strings. My Transifex account username is agnesoshiro. Thank you!

**Comment by ethan-nelson** [comment]
@agnesoshiro added you--thanks!

**Comment by AndreaGriffiths11** [comment]
Hi! Happy to help with Spanish. My Transifex account username is AndreaGriffiths11

**Comment by Woestijnprinses** [comment]
Can I review Dutch  please. My Transifex account username is Woestijnprinses

**Comment by ethan-nelson** [comment]
For those interested in translating, we've updated Transifex with strings that were previously missed, so there is plenty to translate in every language!

**Comment by hi15** [comment]
Hi! Can I review portuguese (br). My Transifex account username is hi15

**Comment by Leodau** [comment]
Hey, i saw you guys still have tons of spanish strings to translate, I would love to get those done!

My Transifex username is **leodau**
:)

**Comment by xamanu** [comment]
Related to #1678

**Comment by xamanu** [comment]
I will close here, in favour of a translation call together with the next round for testing.
