### ISSUE TITLE
Include activity time length text in updated task history UI

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1219]
As of the prior stable TM release, task history entries show the length of time for some events, e.g.

![](https://user-images.githubusercontent.com/12103383/46592042-47776d80-cae9-11e8-8ac8-3e7f21545c2d.png)

The latest overhaul in #1204 has changed the history view to group successive events by a user so that it is easier to digest the history:

![](https://user-images.githubusercontent.com/12103383/46592117-e69c6500-cae9-11e8-9592-1641e25070ff.png)

However, the length of the event was not implemented into that.

This issue requests someone re-implement the `X for Y time` string for mapping, validating, auto-unlock mapping, and auto-unlock validating entries in the updated UI. The code diff in the PR mentioned above includes some code that could be repurposed based on the new format.

**Comment by PierrePIRONIN** [comment]
I'll take a look if you want ;)
