### ISSUE TITLE
Track down UI strings without `{{  | translate }}`

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1234]
Translations on the front end are handled using the `{{ a string or sentence here | translate }}` syntax. There are some strings that do not have this syntax. [Here's](https://github.com/hotosm/tasking-manager/blob/develop/client/app/about/faq.html) a prime example.

**Please note**: This does not apply specifically to returned errors from the API. Perhaps in the future we can look at a mechanism for translating these (probably by loading all errors with translations and substituting them in real time).

Also, if anyone has experience with including html as a string substitution in these types of places, that would be welcomed. Something like (pythonically) `"Please make sure to register at %s for OSM" % (link)`. That would be easier than making translators include the HTML code in their translations or breaking up strings outside the links. Here's an example of that which we're doing right now:
https://github.com/hotosm/tasking-manager/blob/develop/client/app/home/home.html#L91

**Comment by DorukUlucay** [comment]
Hello. I'm interested. Can you assign it to me ?

**Comment by ethan-nelson** [comment]
Hi @DorukUlucay yes we have PR addressing many, if not all, of these. There may be a few that are missed by the PR, so feel free to check back after that is merged in a few days. Thanks for your interest.

**Comment by ethan-nelson** [comment]
This may not be 100% but the number remaining has been greatly reduced in #1235
