### ISSUE TITLE
Create dummy database via script

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1237]
Right now when someone installs TM3 locally, there is no database for someone to use in testing and development. Let's make a script that generates:

1) A project with TM generated grid and a project with an uploaded geometry of irregular shape
2) Four users, two who are validators
3) A variety of history including mapping and unlocking with/without comment, mapping and marking mapped with/without comment, validating and unlocking with/without comment, validating and marking invalid with/without comment, and marking bad imagery and validation/invalidation.

**Comment by xamanu** [comment]
@ethan-nelson, do you think we need this? Or can we consider this is covered by the unit tests and the testing database that was added recently in https://github.com/hotosm/tasking-manager/pull/1453.

**Comment by ethan-nelson** [comment]
I'm still leaning towards having a database created from scratch using a script (similar to a migration), but that may just be an irrational desire :). My thought is that with well established actions and orders of actions, we could ensure that actions dependent on other actions are properly cascaded, executed in order, etc. Perhaps that can just be achieved in unit tests.

**Comment by xamanu** [comment]
For now, we included a base database for testing in the code base.
