### ISSUE TITLE
Capturing all contributing mappers in project dashboard

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1238]
### Current behaviour:

At present the [user contribution endpoint](https://tasks.hotosm.org/api/v1/stats/project/3567/contributions) includes mappers with atleast one task mapped/validated.

![image](https://user-images.githubusercontent.com/12103383/47064689-ae440780-d20a-11e8-923c-0eb406afc80a.png)

### Expected behaviour:
I feel this should include all mappers who have added or edited OSM data. By counting only mappers with mapped/validated tasks, we miss out a lot of mappers.

📈 eg: Project [4983](https://tasks.hotosm.org/project/4983)
Dashboard [lists 318 mappers](https://tasks.hotosm.org/project/4983/dashboard)
Missing maps [lists 630 mappers](http://www.missingmaps.org/leaderboards/#/hotosm-project-4983)
There's a difference of 300 mappers between HOT and missing map stats. Thanks for flagging this difference @smit1678!

@ethan-nelson @bgirardot @smit1678 - What are your thoughts 💭 on including every mapper in the stats dashboard?

**Comment by ramyaragupathy** [comment]
I was looking at this today - we should have a way to figure out if a user has actually uploaded an edit to OSM for a HOT project after locking a task. Counting every user who has locked & unlocked a task without contributing an edit would lead to over projection of impact. what if we could pull this from the Missing Maps leaderboard? or have our API modified to filter out all the edits with a given project hashtag?

@xamanu @ethan-nelson @smit1678

**Comment by smit1678** [comment]
> Counting every user who has locked & unlocked a task without contributing an edit would lead to over projection of impact.

I agree, because there are some times that I have locked a task, opened iD, but then closed and didn't do any mapping. One thought here as we think ahead -- this could be something that is captured as we look to integrate/wrap iD editor. If the user uploaded any data to OSM, we could then capture that the event happened and then they would be considered that they mapped. I think the hesitation on relying solely on Missing Maps API is this wouldn't be a perfect count either (requires a hashtag to be used) and it wouldn't apply to non-HOT deployments of the TM.

**Comment by ethan-nelson** [comment]
I think it would be helpful to list the users in the project display with 0 mapped, 0 validated if they had any interaction with the project on the TM for reasons like a validator wondering why someone added data in a given AOI or to give a quick metric of number of users marking things done versus not (perhaps many many people with 0/0 may be an indication for the PM there could be a problem). Also cc #632

**Comment by uwaiszaki** [comment]
@ramyaragupathy @smit1678 @ethan-nelson @xamanu List of active members in the project without showing mapped and validated tasks can solve the problem.
