### ISSUE TITLE
Encourage users to add email address

### ISSUE THREAD

**Issue by smit1678** [hotosm/tasking-manager#1243]
During our current onboarding process we only create a welcome message to new users which directs users to add information, like email, to their profile. Once they read the visual indicator goes away and users may forget that this information is helpful to fill out. Only 4% of users have added their email to their profile on tasks.hotosm.org. 

<img width="701" alt="hot tasking manager 2018-10-19 16-54-41" src="https://user-images.githubusercontent.com/796838/47211556-f5bfc480-d3bf-11e8-8aaf-2165044cb7c4.png">

## Idea for improvement
One idea for near-term improvement is that for existing users who have not filled out profile information we add a flag that is similar to the messages flag. Instead of showing the number of unread messages, we have a exclamation mark that gives a visual indicator that profile information needs to be filled out. 

<img width="638" alt="hot tasking manager 2018-10-19 16-48-10" src="https://user-images.githubusercontent.com/796838/47211081-d4120d80-d3be-11e8-8c10-36ad6c833454.png">

<img width="606" alt="hot tasking manager 2018-10-19 16-59-00" src="https://user-images.githubusercontent.com/796838/47211686-53eca780-d3c0-11e8-8e98-004e007d9af2.png">

This is looking to solve the issue for existing users and doesn't address new users and a better onboarding process to capture profile information.

**Comment by xamanu** [comment]
This is probably a big bottleneck for all kind of communication that can happen on the Tasking Manager, like getting feedback from validators, success of projects the mapper participated, etc.

Said this, I would go even further and suggest to just require every user that maps to have a verified email address in their profile.

**Comment by xamanu** [comment]
@smit1678 Is it ok for you to close this issue in favor of this already implemented follow-up? (#1365) Please check, whether any aspect is missing there from your requirements. Thanks!

**Comment by smit1678** [comment]
Thanks. @xamanu I'm in favor of closing this for #1365 👍
