### ISSUE TITLE
Create onboarding modal for new users

### ISSUE THREAD

**Issue by smit1678** [hotosm/tasking-manager#1244]
This is a proposal for a first step on improving the onboarding experience for new users. Related to #1186 and #1146 (extends the email address collection).

### Current process for registering and logging in new users: 

1. New user lands on tasks.hotosm.org. They click login to start the process. 
2. Users are taken away from tasks.hotosm.org to an oauth authorization page on openstreetmap.org and required to Grant Access to their account (typical process seen with things like Google or Facebook logins as well)
3. Users grant access and then are taken back to tasks.hotosm.org
4. The application gives a visual indicator on their account menu that there are unread messages.
5. Users need to click the menu and go read their unread messages

### Proposed new process: 
1. New user lands on tasks.hotosm.org. They click login to start the process. 
2. Users are taken away from tasks.hotosm.org to an oauth authorization page on openstreetmap.org and required to Grant Access to their account (typical process seen with things like Google or Facebook logins as well)
3. Users grant access and then are taken back to tasks.hotosm.org
4. A welcome modal pops up and users see their basic profile information with fields that are not filled in. 
5. Users then fill in the details and click Next
6. Users are then presented with training videos that they can quickly play (alternatively these could be simple gifs/animations that explain the process and get people excited about continuing to map)
7. Users then click next and are presented with two or three active beginner projects that they can jump immediately into to start mapping. 

This doesn't accomplish everything laid out in #1186 and only addresses the onboarding of new users. Thinking that a simple first step around new users can help get an MVP online for us to then evaluate and further refine.

**Comment by xamanu** [comment]
Pinging here @hotosm/major as they are redesigning currently the registration process.

**Comment by xamanu** [comment]
A short note: We might want to consider to have a sign in and a registration button (as [proposed in the design](https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357896041)). And for the registration we ask only for an email address before sending users over to OSM for authentication. This allows us to send the user instructions in case they don't make it through the login process.

**Comment by hexiaok** [comment]
I propose two options of flows for 3 different groups of users: 
**OPTION 1** 
UI ref: 
<img width="668" alt="Screen Shot 2019-10-15 at 7 41 13 PM" src="https://user-images.githubusercontent.com/26889634/66829106-388d8b80-ef85-11e9-9842-1d47fd986c62.png">

[User Group A--existing OSM & TM users]: 
1. click <log in> 
2. direct to OSM 
3. grant access and back to TM automatically from OSM 
4. explore TM  & start mapping

[User Group B--existing OSM & first-time TM users]: 
（option I）： 
1. click <log in> 
2. direct to OSM 
3. grant access and back to TM automatically from OSM 
4. provide an email address 
5. explore TM  & start mapping

（option II）： 
1. click <Sign up> 
2. provide email (Pop-up) 
3. direct to OSM 
4. grant access and back to TM automatically from OSM   
5. explore TM  & start mapping

[User Group C--first-time OSM & first-time TM users]: 
1. click <sign up> 
2. provide email (Pop-up)
3. direct to OSM 
4. register at OSM 
5. user visit TM again
6. explore TM  & start mapping

**OPTION 2** 
UI ref:
<img width="600" alt="Screen Shot 2019-10-15 at 7 52 40 PM" src="https://user-images.githubusercontent.com/26889634/66829174-6672d000-ef85-11e9-90c9-7ba98bc901d8.png">

[User Group A--existing OSM & TM users]: 
1. click <Start mapping> & choose <I have OSM account>
2. direct to OSM 
3. grant access and back to TM automatically from OSM 
4. explore TM  & start mapping

[User Group B--existing OSM & first-time TM users]: 
1. click <Start mapping> & choose <I have OSM account>
2. direct to OSM 
3. grant access and back to TM automatically from OSM 
4. provide an email address 
5. explore TM  & start mapping

[User Group C--first-time OSM & first-time TM users]: 
1. click <Start mapping> & choose <I don't have OSM account>
2. provide email (Pop-up)
3. direct to OSM 
4. register at OSM 
5. user visit TM again
6. explore TM  & start mapping

**Comment by xamanu** [comment]
I like to ask the user the question about having an OSM account or not. Much more explanatory than (log-in and sign-in).

Thanks for sharing the user flow steps for the three groups. Just a quick note: With the new design we will introduce a welcome page after login (#1829) that allows new users to get started easily (see description in https://github.com/hotosm/tasking-manager/issues/1645#issuecomment-521057209). Probably the `explore TM` can be replaced with `welcome page`.

**Comment by willemarcel** [comment]
@hexiaok I prefer the option 1.

I think the login button can always lead the user to the OSM login page.

My proposal for new users:
When the user clicks on the "Sign up" button, show a modal explaining that Tasking Manager is coupled with OpenStreetMap and uses it as authentication and ask the user if they already have an OSM account. (It can be unclear to new users what is OSM and that they need an account on OSM to use TM)

If the user doesn't have, ask him his email and redirect to the registration page on OSM website.

It the user click on already have an email, redirect to the login page.

**Comment by JorgeMartinezG** [comment]
@hexiaok I also prefer option 1. Option 2 involves an additional step which is opening the dropdown menu. i agree with @willemarcel  comment. Another option is to include a help paragraph as tooltips when hovering the buttons, explaining the differences between login and signup.

If the user hits the sign-up button, then the modal pops up to write the email address.

**Comment by hexiaok** [comment]
Thanks @JorgeMartinezG @willemarcel agree on Option 1. Please see the updated user flow here: 
![Tasking Manager onboarding](https://user-images.githubusercontent.com/26889634/66910992-3a695480-f042-11e9-9002-560226f04862.jpg)
#1645

**Comment by willemarcel** [comment]
Closing this issue as this feature is already implemented. I opened another issue (https://github.com/hotosm/tasking-manager/issues/1975) with a couple ideas on how we can make the onboarding process easier.
