### ISSUE TITLE
Can't unlock Task

### ISSUE THREAD

**Issue by kleper** [hotosm/tasking-manager#1251]
In the OpensStreetMap Colombia task server, a problem has been presented in a task: https://tareas.openstreetmap.co/project/111#bottom.
Specifically in task 22, after someone tried to do it I could not unblock it either to do the job or to validate it, do you know how I can unlock it manually?

**Comment by ethan-nelson** [comment]
Hi @kleper it looks like this is related to #1282. That task has actually moved to https://tareas.openstreetmap.co/project/111?task=132#bottom. I unfortunately don't have an answer for fixing it at this moment, but it's coming up soon on my to-do list. Just for a data point, do you know what version or commit this instance is currently running? Cheers, Ethan

**Comment by xamanu** [comment]
Closing here, as this is handled in #1282.
