### ISSUE TITLE
I have read the instructions

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#1258]
This is more of an idea we have floated around the Activation Working Group but is related to onboarding new mappers. We might want mappers to have to click a button that they have read the instructions before being able to map/validate.

**Comment by xamanu** [comment]
This is to be considered in the ongoing redesign with @hotosm/major hotosm/projects#24

**Comment by willemarcel** [comment]
We show instructions first to users that have not contributed to project yet on TM4
