### ISSUE TITLE
Machine learning additions to TM

### ISSUE THREAD

**Issue by wronk** [hotosm/tasking-manager#1264]
## Vision for updates
Development Seed is working with CosmiQ Works and @smit1678 to bring some new machine learning tools to the TM interface. We want to deploy ML within TM inform mappers about the project they're working on and boost their efficiency. We're starting with estimating total building footprint per task square, and you can see version 0 in our [blog post](https://medium.com/devseed/weaving-automation-into-the-mapping-workflow-adding-ai-to-the-tasking-manager-52172ed2ece8) on the topic. Basically, it takes an ML estimate of building footprint (in sq. meters), building area from OSM, and displays the difference using color coded task squares.

## Goals
Our main focus here, is to make a model agnostic pipeline for deploying ML. You should be able to use any type of per-tile ML model (e.g., road length estimator, green area estimator, etc.) on a task-by-task basis and display that information in the TM. We expect that mappers will be faster and have a better experience within TM when they roughly know the difficulty of each task and can see at a glance how much remaining infrastructure in their project is missing from OSM.

**In this round of work, we will focus on:**
1. Initiating and running an ML model on the cloud (AWS Lambda) from TM's backend to calculate per-tile statistics
1. Storing and accessing per-task predictions on TM's backed as well as visualizing this information on the frontend

**Future work will focus on:**
1. Updating the project creation interface so that project owners can run this ML pipeline themselves
2. Expanding to other infrastructure estimates (e.g., roads)

## Design and suggestions
**We want to hear from the community on plans concerning the project visualization.** Specifically, what do you think is the best way to display information like an estimate of missing building area? Again, see the blog post demo ☝️for our first iteration. We have some ideas for the next design iteration, but we'd like to hear from mappers on their preferences.

**Rough design specs:**
1. We'll need to display a gradient of information. With missing buildings for example, that might be (1) no missing building area (2) <1000 sq. m. of missing building area and (3) >= 1000 sq. m. of building area.
1. If possible, we should incorporate this information into the default screen rather than create a new toggle-able layer like we did in the linked demo.
1. Avoid adding new colors -- there are already 7 states with 6 different colors.
1. Obviously, be as intuitive as possible -- the more complex this is, the harder it is to explain to new mappers.

**Comment by smit1678** [comment]
> If possible, we should incorporate this information into the default screen rather than create a new toggle-able layer like we did in the linked demo.

I would agree with this. While the toggle-able layer is helpful to see the potential in the demo, the integration should be default (when ML is used) and somehow helps a mapper not have to think too hard about the task square they choose. 

Another consideration is the recent legend/map colors discussion: https://github.com/hotosm/tasking-manager/issues/1257. My opinion is that there are too many colors at the moment. I don't have a good suggestion at the moment but raising this as something that needs to be designed around.

**Comment by wronk** [comment]
*This is an updated plan for the front-end ML design after talking with @smit1678 and @geohacker. There will be more discussions on this topic, but anyone is welcome to weigh in here if you have a suggestion.* 

## Front-end design goal
Tweak the TM visualization to (1) simplify things for new users and (2) start incorporating machine learning analytics.

## Problem 
The current visualization displays a lot of information. This makes for a rich interface, but it's too easy to overwhelm users with all the colors and states. And if we're going to start adding Machine Learning (ML) analytics (e.g., amount of missing building area), this will mean additional visual information for them to wade through. Therefore, we propose some changes to the mapping page.

Talking with @smit1678 and @geohacker, one good driving philosophy is to make the default interface as easy as possible for new users. Essentially, to strip away everything that doesn't help new users to quickly answer the question "Where task should I map next?" At the same time, we'd like to retain other information for project managers and experienced mappers.

## One solution
We propose adding creating two visualization modes: a default (or zen) mode and an experienced user mode. 

### Default mode
* Task squares that have the "Ready" state will be visible and selectable
* Task squares that should not be selected by new users (locked, mapped, validated, bad imagery, invalidated?) will not show up in this mode
* If ML analytics are available, they will show up as a color gradient (likely 3-tiered as in our [initial demo](https://tasks.developmentseed.org/project/26)). We can also explore some other indicator like hashing, or some sort of simple icon.
* Picking a random task could be influenced by ML analytics or some other TM-determined prioritization.
### Experienced mode
* All task states will be visible as they are now
* We can explore adding ML information, but the interface may be too crowded at this point.

## Open questions
1. What's the best way to display ML information? Color gradient, hashing, icon, or some other visual modifier to the task square?
2. How will we simultaneously visualize multiple types of ML information (e.g., buildings + roads)?
3. Is it easy to update the visualization so that locked/mapped tasks are quickly hidden in the default mode?

**Comment by geohacker** [comment]
Thank you for laying this out so well @wronk. 

@smit1678 - as we're closing in on the backend, we're thinking of using the visualisation approach in our fork of TM as a starting point. It looks like this:

![tm-ml](https://user-images.githubusercontent.com/371666/48761575-f608f380-ecce-11e8-97fd-83de34a80695.gif)

Did you get any specific feedback on any of the points we discussed last week?

**Comment by smit1678** [comment]
> Did you get any specific feedback on any of the points we discussed last week?

Unfortunately I didn't get the chance to do some testing during a mapathon. 

> as we're closing in on the backend, we're thinking of using the visualisation approach in our fork of TM as a starting point.

Thinking just as a starting point and then evolve the ideas @wronk laid out?

**Comment by geohacker** [comment]
> Thinking just as a starting point and then evolve the ideas @wronk laid out?

@smit1678 yeah of course - I think this is only a starting point and without touching too many parts we can get something out. And then go from there. We also have limited time for the current sprint.

**Comment by xamanu** [comment]
A quick update on some conversations that have been going on around this:

* Different providers for ML: There are many ML efforts and endpoints, an extendable architecture is needed in order to allow flexible integration of different ML providers and models. One idea is to abstract a ML-Service that handles the different providers and models, but provides one general API to the TM and other applications, that might want to rely on certain elements of ML for any kind of use case.
* For triggering the ML-Service, the TM will use webhooks with user events. For getting data back from the ML-Service the data will be passed on via the Annotation API.
* There is a general agreement to go towards the complexity measure as the first real show case of ML in the TM. This can be used to either support the project manager to create better tasks, or to give mappers adequate tasks in terms of complexity depending on their skill level. @hotosm/major will support us to create a good and working user flow around this.

**Comment by wronk** [comment]
I realized I never dropped the ML-relevant notes from the February working group meeting. They are on google drive [here](https://docs.google.com/document/d/1qf8GLCIzvvTzdTIeVAt-yvGNzC5Ic43AVLzngMDMdEU/edit#heading=h.bejc5d11p3rf). 

The contours of these discussions were primarily driven by HOT, Facebook, Microsoft, and DevSeed, but others from the meeting were involved as well.

**Comment by xamanu** [comment]
Passing this on to @fitoria to get familiar with the past work and check the PR about Task Annotations #1289. I suggest we split them into two PRs, one that is introducing the Task Annotations and another one that includes the work to bring it to the UI. In a next step we would like to include the ML Layer into the project creation process, instead of presenting it to the user.

With the support of @geohacker and @wronk a general connection piece the `ml-enabler` will be created, which will also support changing measures based on task splits.

**Comment by xamanu** [comment]
We are planning on bringing in the Tasks Annotations backend into the Tasking Manager soon. @fitoria started wrapping up the work @geohacker to separate the backend into one single PR #1577.

In a next step we seek to:

* build a generic piece for integrating such data sources with the [*ml-enabler*](https://github.com/hotosm/ml-enabler)
* (semi-) automatize the feed-in of data from looking glass
* use the complexity layer during the project creation flow #1578 
* use the complexity information on tasks to facilitate adequate tasks to the right users #1579

**Comment by xamanu** [comment]
I think that can be closed in favour of all the follow up issues mentioned before. Thanks.
