### ISSUE TITLE
Import GeoJSON polygons for Priority Areas

### ISSUE THREAD

**Issue by Vaomatua** [hotosm/tasking-manager#1275]
I would like to be able to use a GeoJSON polygon file to show the Priority Areas in addition to drawing a polygon/rectangle/circle.
![image](https://user-images.githubusercontent.com/12214434/48580406-fb7fcb80-e8d3-11e8-8ceb-47d92ebddc57.png)

**Comment by canunen** [comment]
I support that suggestion. Project managers may already have identified the priority areas and a JSON import would help a lot.
