### ISSUE TITLE
Task oriented project creation

### ISSUE THREAD

**Issue by smit1678** [hotosm/tasking-manager#1279]
Proposal based on work presented in TM Working Group: 

Some projects can have targeted purposes based on GIS processing, ML Extractions, or other sources of data. Utilizing that as an input to project creation can insure mapper time is maximized. This also allows project creators to bring external data into the project and individual tasks (similar to the import process features we've used in the past via per task instructions). 

Feature improvement focuses on:

* Clip project to where input task geometry exists
* Maintain task data for passing on to the mapper into either ID (Future) or JOSM (currently just via JOSM plugin)

PRs to test this idea coming soon via @lesserj

**Comment by willemarcel** [comment]
I think this issue is solved with arbitrary tasks & clip to aoi.
