### ISSUE TITLE
Split moving tasks to another location in the world

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1282]
The project https://tasks.hotosm.org/project/5537 is acting strangely: when you split a task, it disappears from the main grid in Timor-Leste and instead moves to the middle of the Indian Ocean. The tasks were originally around https://tasks.hotosm.org/project/5537?task=40 but when split move to around https://tasks.hotosm.org/project/5537?task=70

Looking at commit history for the most recent version push to master, this _seems_ to be a bug that was already present in the code as we did not touch the geometry calculations when ensuring task split history is preserved (https://github.com/hotosm/tasking-manager/blame/master/server/services/grid/split_service.py). No issues like this came up when testing on the staging instance, and projects that are at the top of the list on live do not display this problem when splitting either--so it does not appear to be widespread at this time. Nevertheless, still a problem.

Thanks to Andrew for finding this!

**Comment by ethan-nelson** [comment]
https://tasks-stage.hotosm.org/project/5535 is an example of this occurring on staging

I've been looking at the raw tasks geojson from https://tasks-stage.hotosm.org/api/v1/project/5535/tasks?as_file=false and picked one of the tasks of the original zoom level and one at the next zoom level that was split. 

```
19 |  
-- | --
type | "Feature"
geometry |  
type | "MultiPolygon"
coordinates |  
0 |  
0 |  
0 |  
0 | -42.1874999924431
1 | 72.3957057007426
1 |  
0 | -41.8359374925061
1 | 72.3957057007426
2 |  
0 | -41.8359374925061
1 | 72.5017223456187
3 |  
0 | -42.1874999924431
1 | 72.5017223456187
4 |  
0 | -42.1874999924431
1 | 72.3957057007426
properties |  
taskId | 41
taskX | 392
taskY | 816
taskZoom | 10
taskIsSquare | true
taskStatus | "READY"
20 |  
type | "Feature"
geometry |  
type | "MultiPolygon"
coordinates |  
0 |  
0 |  
0 |  
0 | -68.6434492452437
1 | 42.1845617326509
1 |  
0 | -68.6434492452437
1 | 42.5957829683862
2 |  
0 | -68.0866664916311
1 | 42.5957829683862
3 |  
0 | -68.0866664916311
1 | 42.1845617326509
4 |  
0 | -68.6434492452437
1 | 42.1845617326509
properties |  
taskId | 39
taskX | 200
taskY | 407
taskZoom | 9
taskIsSquare | true
taskStatus | "READY"
```

Taking formulas from https://github.com/hotosm/tasking-manager/blame/master/server/services/grid/split_service.py#L61-L72

For the first (which is a task that has already been split)
```
-42.1875 lon, 72.3957 lat -> -4696291.02, 11897270.63 in ESPG 3857
max = 156543.0339 * 256 / 2 = 20037508.3392
step = max / (2 ** (10 - 1)) = 39135.758475
(-4696291.02 + max) / step = 392
(11897270.63 + max) / step = 816
```
That matches the x and y properties.

For the second (which is an original task)
```
-68.6435 lon, 42.1846 lat -> -7641359.47, 5188671.85 in ESPG 3857
max = 156543.0339 * 256 / 2 = 20037508.3392
step = max / (2 ** (9 - 1)) = 78271.51695
(-7641359.47 + max) / step = 158
(5188671.85 + max) / step = 322
```
That does not match the x and y properties. Calculating the lat and lon from the x and y properties instead
```
max = 156543.0339 * 256 / 2 = 20037508.3392
step = max / (2 ** (9 - 1)) = 78271.51695
200 * step - max = -4383204.949200001
407 * step - max = 11818999.05945
Converting those from ESPG 3857 to 4326 -> -39.375 lon, 72.182 lat
```
Which is in the same general vicinity as the split tile.

So it seems in some cases a project may be created with incorrect x and y properties?

**Comment by ethan-nelson** [comment]
Playing around with things a bit, it seems I can get a slightly strange gridding if I go from step 2 to 3 in project creation, alter the size of the grid, zoom out, pan the map, then go back to step 2 and pan the map and zoom a bit, then go forward to step 3. So there is perhaps a variable about lat, lon, and/or zoom that is not being reset or updated?

**Comment by lesserj** [comment]
@ethan-nelson I had this problem a lot. It only happened to me on high-resolution screens.  I even have a computer with two screens, one, which is high resolution.  I would get the error when creating a task on the high-resolution screen, but if I moved to the standard resolution screen, it would work fine.  It was only impacted when drawing the project boundaries.  When I imported the project area, it'd work fine.  I didn't track it down exactly, but I think the math for calculating dimensions, does not factor in the 2x (or 3x) factor on those screens.

**Comment by jarmokivekas** [comment]
Just for one more data point, I think this same thing is happening in project #6060 (https://tasks.hotosm.org/project/6062)

This gist has [two different geojson files from the same project](https://gist.github.com/jarmokivekas/bd797f9e179baf42ab8573c65eee7628) a few days apart. In the first file there is one, and in the second there are two tasks that have been moved from Yurimaguas, Peru to the Pacific Ocean, west of Santiago, Chile.

Two missing tasks (white squares):
![Screenshot from 2019-06-01 15-36-20](https://user-images.githubusercontent.com/3074453/58748803-4cc56600-8486-11e9-93fa-0ebcb28aae76.png)

Moved into the Pacific Ocean. Still correctly positioned relative to eachother, though.
![Screenshot from 2019-06-01 15-45-35](https://user-images.githubusercontent.com/3074453/58748804-4fc05680-8486-11e9-8c69-8cc8a40bd83e.png)

**Comment by ethan-nelson** [comment]
The before/after here is really useful for debugging, thanks!

**Comment by ethan-nelson** [comment]
The above gist has the before and after states of a task that was split weirdly, namely task 416. The original attributes are:

x  |  y  |  z
---|-----|---
60880 | 102015 | 18

Stepping through the split function, the northwestmost task is assigned the following attributes:

x | y | z | 
---|---|---
121760 | 204031 | 19 

Running the coordinate numbers:

xmin (espg 3857) | ymin (espg 3857) | xmin (espg 4326) | ymin (espg 4326)
---|---|---|---
-10730535.776864063 | -4442061.460969044 | -96.39° | -37.02°

which is where the split tasks stand.

So it does seem to be that the x/y/z of the tasks _at project creation_ are generated incorrectly and therefore stored that way.

**Comment by ethan-nelson** [comment]
Now, let's investigate what the x/y/z of the original tile is working backwards. The northwestmost corner of the task is:

xmin (espg 4326) | ymin (espg 4326) | xmin (espg 3857) | ymin (espg 3857)
---|---|---|---
-76.1059885597261° | -5.89542588825815° | -8472079.89 | -657436.91

Now we have a set of linear equations that we can solve for the tile x and y (https://github.com/hotosm/tasking-manager/blob/develop/server/services/grid/split_service.py#L87-L96):

```
x = (2 ** (zoom - 1)) * [(-8472079.89 / 20037508.3392) + 1]
y = (2 ** (zoom - 1)) * [(-657436.91 / 20037508.3392) + 1]
```

Using various zoom levels, 

zoom | x | y
---|---|---
14 | 4728.33189896 | 7923.21792014
15 | 9456.66379791 | 15846.4358403
16 | 18913.3275958 | 31692.8716805
17 | 37826.6551917 | 63385.7433611
18 | 75653.3103833 | 126771.486722
19 | 151306.620767 | 253542.973444

Because of the size of the numbers, there are some rounding errors and these are not exact. But it seems (assuming my math is right) that the tile indices stored are off by about 25%. So searching front end code now based on mine and Jacob's experience during project creation.

**Comment by xamanu** [comment]
This might be fixed with the recently merged #1863. It can be tested locally and on staging.

**Comment by russdeffner** [comment]
This project got it really bad: https://tasks.hotosm.org/project/6981

**Comment by dakotabenjamin** [comment]
Another one: https://tasks.hotosm.org/project/7014

**Comment by tobylyte** [comment]
Yes, https://tasks.hotosm.org/project/7014 is suffering with this. 

![image](https://user-images.githubusercontent.com/3061722/66984995-c36ca400-f0b3-11e9-9fb3-fd607c5a4335.png)

Some of the split tasks are moved to West Chad
e.g. https://tasks.hotosm.org/project/7014?task=505#bottom 
![image](https://user-images.githubusercontent.com/3061722/66984603-ea76a600-f0b2-11e9-9903-b45d9677a346.png)

**Comment by xamanu** [comment]
As per converations with @russdeffner, moving priority up here.

**Comment by xamanu** [comment]
We have another case: https://tasks.hotosm.org/project/7377

![image](https://user-images.githubusercontent.com/97706/69799085-7f98ae80-11ca-11ea-8cab-8b440ad73286.png)

**Comment by russdeffner** [comment]
Another case: https://tasks.hotosm.org/project/7446

**Comment by relet** [comment]
I seem to be able to reliably reproduce the bug (splitting tasks in the latter project on Firefox/Linux). If there is anything I can help to check, I'm happy to help.

**Comment by zlavergne** [comment]
@xamanu @ramyaragupathy can you get me a copy of the logs for the most recent cases please. I've noticed something on our TM instance when we get experience this bug and if it's the same issue, I may have an idea towards the fix.

**Comment by xamanu** [comment]
We got a related PR: https://github.com/hotosm/tasking-manager/pull/2081 (thanks to @nrotstan)

**Comment by xamanu** [comment]
Fix has been merged and is being released soon.
We have to bring this into TM4. As the branches are diverging.

**Comment by willemarcel** [comment]
I noticed that problem happened on TM4 instance too: https://tm4.hotosm.org/api/v2/projects/3/tasks/?as_file=true

Have we applied the change on #2081 to develop?

cc @xamanu @JorgeMartinezG

**Comment by xamanu** [comment]
Added a PR for porting this fix to TM4: https://github.com/hotosm/tasking-manager/pull/2192

**Comment by dakotabenjamin** [comment]
@xamanu can we close this now?

**Comment by xamanu** [comment]
Yes, we have deployed this for TM3 and it is in TM3.
