### ISSUE TITLE
"Undo"ing invalidation of a validated square breaks the task

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1283]
The task at https://tasks.hotosm.org/project/5503?task=67 was previously in a validated state. Another user later invalidated the square, then checked out the task again and did an "undo" to revert the task to validated. That user now cannot invalidate the task again with the error `There was a problem unlocking the task. Validator Lock API - unhandled error: object of type 'NoneType' has no len0`. I haven't investigated yet, but I imagine this is a corner case of the undo action for invalidated->validated is not properly accounted for.

**Comment by willemarcel** [comment]
It doesn't apply to TM4.
