### ISSUE TITLE
ML prediction storage in TM

### ISSUE THREAD

**Issue by geohacker** [hotosm/tasking-manager#1284]
Related to #1264. 

@smit1678 @ethan-nelson - @wronk @batpad and I are thinking a bit more about integrating the ML results to the front-end. Currently, we aren't storing the predictions to the ML db and we think we should store this per task. So this would involve:

1. Changes to the Tasks model or a new model
Tasks already have an `extra_properties (varchar)` column which @batpad and I suspect is carried over from some previous work Sanjay did but is unused. We could turn this column into a jsonb type and store ml results as key value pairs for look up and updates. The other idea and may be slightly cleaner is to create a new model altogether and call it MLPredictions and store `task (id), ml_prediction (json)` and then use this for lookup.  This would allow us to keep Tasks model independent, and also expand later. @ethan-nelson do you have a suggestion or preference?

2. API endpoint to POST project/tasks geojson 
Depending on 1, we can figure out where this endpoint should go.

3. Front-end visualisation
We'll use the [current structure](https://github.com/hotosm/tasking-manager/issues/1264#issuecomment-440191005), and add another button to visualise ML results and pull the attributes to the front-end.

**Comment by wronk** [comment]
## Updated plan
After getting some community feedback, our updated plan is to create a separate "Task Properties" table within the TM database. We'll also build API endpoints to interface with that new table.

The advantage of this strategy (pointed out by a number of people) is that this approach is useful for any generic task annotation (where ML-derived information is only one example). We could also use this for task prioritization (e.g., based on humanitarian needs or search engine hits) or other task-relevant info that can be stored in JSON format.

## Task properties table
**Columns**
* Project ID
* Task ID
* Annotation type (enum) to help front-end parsing of task properties
* Annotation source (str? Optional)
* Timestamp of last update
* Properties (jsonb) with key/value pairs containing information about a task

**API endpoints**
* POST requests to add/update task properties
    * Eventually (or immediately? cc @ethan-nelson), this should make use of an API key to limit access
* GET requests to fetch task properties
    * Will be called from TM's front-end
    * Once fetched, properties can be added to a project's geojson file for visualization

**Comment by lesserj** [comment]
Take a look at #1302.  It allows projects to be created by geojson data.  Geojson data is split by task boundaries and stored per task.  Tasks without data are discarded.  There is no visualization component in Tasking Manager, but it does include a plugin for JOSM that allows the data to be passed to JOSM when clicking the start mapping button.

**Comment by xamanu** [comment]
An update here, concrete work has been started on a separate piece, the [ml-enabler](https://github.com/hotosm/ml-enabler), which might be interesting for other applications to use, too.

**Comment by xamanu** [comment]
Most discussions went into the ml-enabler. Closing here in order to avoid parallel conversations.
