### ISSUE TITLE
Add message or action to bring users back to Contribute page with correct filter

### ISSUE THREAD

**Issue by smit1678** [hotosm/tasking-manager#1285]
When clicking on an advanced project, we give users a message: `You cannot select tasks for mapping on this project because you do not have the required mapper experience level.`

This raises the question of what do I do next? This might be off-putting and we don't give a user an option to understand what projects they can participate in. 

<img width="1059" alt="hot tasking manager 2018-11-26 12-09-32" src="https://user-images.githubusercontent.com/796838/49013345-56d37880-f174-11e8-8e60-72fd243c072a.png">

### Potential solution

It might be helpful to add an action for a user to click to take them back to a filtered view of the Contribute page or off a suggested high priority project that is in line with their user level.

**Comment by willemarcel** [comment]
It doesn't apply to TM4.
