### ISSUE TITLE
Allow users to apply for a validator role

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#1286]
There should be a way to request validator role from a project. Maybe when the mapper tries to hit Validate on a restricted validation project they get a way to 'message the project manager' for validator role. This doesn't cover how we ensure PM's verify their level of experience or any onboarding that should happen.

**Comment by xamanu** [comment]
This functionality is proposed to live in the [users' profiles](https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652190). And we probably have to define who is going to be notified to take the decision.

**Comment by willemarcel** [comment]
**Description:**

Provide a functionality in the user profile to request to become a validator. A good mechanism to select the recipient needs to be defined. This might be admins of an organization the user is affiliated or general community admins.
Then implement a notification and message to the admins and a user flow to approve or deny a request, adding a small message to explain one or another decision.

Depends on: #1608 and #1609

**Comment by russdeffner** [comment]
Here is the current form: http://bit.ly/HOTValidators

**Comment by xamanu** [comment]
This has been implemented in a simple way on Tasking Manager 4. For becoming a validator users have to apply to specific groups. HOT could communicate what is its validator group and there is the functionality to apply for membership. @russdeffner it would be good to verify whether the current implementation works for HOT's process.

**Comment by russdeffner** [comment]
Yes, it works very well. One question I would have is if there is anything we need to change for teams? In other words, will validators need a 'global' role to validate on a team or do we need a more coarse method for various teams/organizations to recruit and train their own validators. That said, the form still works very well for HOT purposes.

**Comment by xamanu** [comment]
> will validators need a 'global' role to validate on a team

No, there is not going to be any global role for validators anymore. They join teams, that can be used flexibly to give permissions out to groups.

> or do we need a more coarse method for various teams/organizations to recruit and train their own validators. That said, the form still works very well for HOT purposes.

Yes, exactly.
