### ISSUE TITLE
Loading message on user profile

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1290]
We have improved the queries that retrieve mapped and validated projects on the user profile page so that it is not timing out any more, but there is still a lot of number crunching going on and thus it still takes ~30 seconds for some of the more advanced users. It would be great to have a 'loading' message on the user profile page while waiting for that information.

In a similar light as #1188, #1189, and #1191.

**Comment by xamanu** [comment]
On user profile, I always see the error message because of missing email address, but when the user loads it disappears.

**Comment by willemarcel** [comment]
It doesn't apply to TM4
