### ISSUE TITLE
Display auto unlock time remaining neater

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1291]
Right now, the task auto unlock timer is displayed in minutes left. Let's look at changing this such that it is dynamic and based on the time remaining. I know in TM2 we used a time-ago sort of parser to handle that. The server already supplies the auto unlock time in seconds to the front end.

**Comment by ethan-nelson** [comment]
From https://github.com/hotosm/tasking-manager/pull/1274#issuecomment-445161128 @ramyaragupathy 

In all the cases time left is displayed in minutes like  ![image](https://user-images.githubusercontent.com/12103383/49636699-59ae5300-fa29-11e8-8182-fc0d27603c75.png)

Just thinking if we could get to display units in hours & days if the auto unlock duration exceeds an hour. Like:

- 2hrs and 10 minutes left instead of 130 mins left
- 1 day and 15 hrs left instead of 2340 minutes left

**Comment by ramyaragupathy** [comment]
Addressed through https://github.com/hotosm/tasking-manager/pull/1311
