### ISSUE TITLE
minor bug: (long) list of tasks for validation are not readable

### ISSUE THREAD

**Issue by govvin** [hotosm/tasking-manager#1294]
![image](https://user-images.githubusercontent.com/5821688/49682531-ae68d100-faf0-11e8-8e6f-1ada4d10f52f.png)

When you are given (a long list) of multiple tasks to validate (e.g. validating by user, or by area) you get this long string where some of the numbers are unreadable

**Comment by willemarcel** [comment]
it doesn't apply to TM4
