### ISSUE TITLE
Ability to working on multiple tasks that are next to each other

### ISSUE THREAD

**Issue by govvin** [hotosm/tasking-manager#1295]
![image](https://user-images.githubusercontent.com/5821688/49790632-aff0fe00-fd69-11e8-9917-0a7720adbab8.png)

We work on tasks with linear features (roads) - checking geometry and alignment. Often, it's best to work on multiple tasks at the same time - either mapping them, or validating them together but we can only select on one task at a time.

Would that be possible?

Someone might wonder,  why not create larger tasks areas instead? If you're working on roads, you'll be creating a lot of empty spaces you're not actually working on, so visualizing the task is more accurate with smaller tasks.

**Comment by xamanu** [comment]
I fear a bit that this will lead to people blocking too many tasks and we are loosing data quality because of this. Ideally the project creator should create suitable task sizes.
