### ISSUE TITLE
Add Type(s) of Mapping to Contribute page project display

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#1298]
In the project summaries shown on the Contribute page - it would be nice to also show what type(s) of mapping are checked in the project metadata. i.e. If mappers are shown Roads vs. Buildings, etc. from the 'front' page it might do several things:

- Seeing the type of mapping may help mappers decide if the project is right for them
- It might also encourage mappers to read the instructions if it's a mapping type they have not done before
- May also help manage projects if project managers can more quickly see the type(s) of mapping (i.e. if I have a road and a building project and want to quickly visually find one vs. the other)

This will take up a bit more space on the project summaries, but it seems the majority of current projects have plenty of space for one more metadata item.

**Comment by xamanu** [comment]
The new redesign addresses this with filters:

![image](https://user-images.githubusercontent.com/97706/58164676-cafb5e80-7c75-11e9-982d-1eb781545321.png)

@russdeffner, do you think this is a good solution for your need?

**Comment by russdeffner** [comment]
I was more talking about the small 'cards' when viewing contribute/front page
![Capture](https://user-images.githubusercontent.com/6763645/58182823-8965b600-7c6b-11e9-9441-c259077c19df.PNG)

**Comment by xamanu** [comment]
Yes, I think they were on the project cards at some stage in the redesign process and then they were taking off to not overload the cards.

The question is whether we still want the symbols on the card or we think it is fair enough to have them as filters, so people can use them explicitly for exploration.

**Comment by russdeffner** [comment]
Having the project type next to/in the opposite corner of difficulty on new project cards would suffice for what this issue was about (i.e. a quick visual to know what type(s) of features are being mapped). If it's limited to 3-4 icons (which we also need to ensure 'other' is still there, power infrastructure is a 'new' type I came across recently), I think it would fill that space nicely.

**Comment by xamanu** [comment]
I see this being a design decision for TM4, not to have the mapping types on the cards. If people are interested in mapping certain features, the filters are going to help to narrow down by mapping type. I close this issue for now. If you are very strong about it @russdeffner feel free to open it again. Thanks.
