### ISSUE TITLE
Re-add ability to assign tasks to someone

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1309]
TM2 allowed you to assign a task to someone for them to complete. That's not in TM3.

**Comment by ethan-nelson** [comment]
Per Slack, it seems there was not much interest in this feature, but always open to expanded functionality :)

**Comment by xamanu** [comment]
I suggest marking this as a `won't fix`. We might want to reopen it. In case it becomes important to anybody.
