### ISSUE TITLE
add 'mark as read' to inbox

### ISSUE THREAD

**Issue by FrisoDB** [hotosm/tasking-manager#1312]
Every time I login I find myself having received about ten new standard messages, usually about a task being verified. I have to open and close every message, which gets a bit annoying.

**Comment by xamanu** [comment]
This is a bit related to #1361, which introduces actions on several messages.

**Comment by uwaiszaki** [comment]
@xamanu I would like to work on this issue.

**Comment by xamanu** [comment]
There is a PR by @uwaiszaki on this #1401

**Comment by willemarcel** [comment]
It's done already
