### ISSUE TITLE
Select a task by the number to map or validate

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1325]
From @FransS1945

Make it possible to fill in the number of a task you want to map or validate.

This option is useful when you want to continue mapping or validating on the same task for instance when you had to stop or the timeslot ends.

**Comment by xamanu** [comment]
@FransS1945 I'm not sure I'm understanding well the requirement. Can you explain a bit better what you think should change and what impact it shall have? Thanks!

**Comment by FransS1945** [comment]
Hi Xamanu.  
When a mapper or validator want to continue on a specific task in a project there are no tools to do so. After a time out or when you reach the limit of the time slot on that task. 
Now you have ( by absence of other options) to change the task number in the address field of your Internet browser by selecting a random task and change that. When there should be a field where you can fill in the task number, it makes it easier. I am also asked regularly to (double) check a task on specific points.  I hope this will bring more clarity in my request.
Thanks

**Comment by xamanu** [comment]
Thank you @FransS1945 for your explanation. it makes indeed a lot of sense. We are thinking about addressing this in the ongoing redesign of the Tasking Manager with a "My tasks" view:

![image](https://user-images.githubusercontent.com/97706/58164940-4d841e00-7c76-11e9-951b-ab40d847005a.png)

Does this address your need?

> I am also asked regularly to (double) check a task on specific points

In this case, is the url working for you?

**Comment by xamanu** [comment]
The new TM4 is able to show/filter on task numbers. This should help solve this issue here.
