### ISSUE TITLE
Add lastUpdated and created in /search API

### ISSUE THREAD

**Issue by kamicut** [hotosm/tasking-manager#1338]
I have an application that reads the TM API and would like to sort by lastUpdated to see what are the "freshest" tasks. Unfortunately right now I would have to hit every project API endpoint to get the lastUpdated metadata. Would it be useful to float the lastUpdated and created fields to the search API models? I can work on this.

**Comment by mrsaicharan1** [comment]
Would like to work on this issue. Could you assign this to me?

**Comment by ethan-nelson** [comment]
Hi @mrsaicharan1 I can't assign it to you for some reason, but I will mark it as in progress. Let me know if you run into problems! Thanks for your interest!

**Comment by ethan-nelson** [comment]
Hi @mrsaicharan1 I wanted to check in on your progress. I'm not trying to rush you--just wanted to see if you were running into any problems I could help with along the way. Cheers!

**Comment by kamicut** [comment]
@xamanu I'm waiting to see if @mrsaicharan1 wants to work on this since they expressed interest.

**Comment by willemarcel** [comment]
It's implemented in TM4
