### ISSUE TITLE
Split tile becomes unselectable

### ISSUE THREAD

**Issue by wookey** [hotosm/tasking-manager#1339]
I suspect a bug in the tasking manager: Colin_Jones split 3 tiles into 4 (due to cloud obscuring only part of the tile, so that part could be 'marked as bad imagery'. However now those subtiles are no longer selectable for editing.

The example is on https://tasks.hotosm.org/project/5381 three tiles in a row NW 'corner' of task area, which before splitting were:
https://tasks.hotosm.org/project/5381?task=66
https://tasks.hotosm.org/project/5381?task=93
https://tasks.hotosm.org/project/5381?task=112

If you click on any subtile there, it is not highlighted, but the history for https://tasks.hotosm.org/project/5381?task=10 appears (tile/task 10 is not highlighted either).
So these tile are now uneditable. Any idea what went wrong?

**Comment by ethan-nelson** [comment]
Hi @wookey thanks for filing this. I was able to select the square that is missing by messing with the url (https://tasks.hotosm.org/project/5381?task=505), but you're definitely right that the large circle shouldn't be selectable--especially when you select that one particular task. I'll touch base with the project manager to see if we can figure out how this occurred. Thanks!

**Comment by willemarcel** [comment]
It doesn't apply to TM4.
