### ISSUE TITLE
Update postgis in Client Install Script for Ubuntu 16.04

### ISSUE THREAD

**Issue by abalosc1** [hotosm/tasking-manager#1340]
404 on `http://postgis.net/stuff/postgis-2.2.4dev.tar.gz` listed in the Client Install Script for Ubuntu 16.04
https://github.com/hotosm/tasking-manager/wiki/Client-Install-Script-for-Ubuntu-16.04

**Comment by ramyaragupathy** [comment]
@arunasank - did this get through for you in the cfn?

**Comment by ethan-nelson** [comment]
I don't want to jump a version number without looking at the changelog, so I updated the script to point to just the postgis-2.2.4 release instead of dev. Let me know if that doesn't work for you.

**Comment by arunasank** [comment]
Hi folks, I am using `postgis-2.5.2dev`!

**Comment by dakotabenjamin** [comment]
Thanks @ethan-nelson! I'll close this, please reopen if issues aren't resolved.
