### ISSUE TITLE
Transfer project to new owner

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1341]
Provide the ability to transfer ownership of a project from one user to another.

**Comment by xamanu** [comment]
I would put a button under `Actions` when editing a project. And then provide a small form with autocomplete to select the user. What do you think?

**Comment by ethan-nelson** [comment]
That sounds like a good plan :+1:

**Comment by uwaiszaki** [comment]
@xamanu @ethan-nelson Currently we are not using project_dto to update author and author_id of the Project Model. Can i use them to update the author and the author_id of the project?

**Comment by fitoria** [comment]
PR here https://github.com/hotosm/tasking-manager/pull/1663
