### ISSUE TITLE
tiles/project aoi increase in size

### ISSUE THREAD

**Issue by edircksen** [hotosm/tasking-manager#1342]
HOT TM project 5475 appeared to become corrupt while still in draft. The task squares expand and the apparent AOI covers most of the hemisphere. Upon zooming in, the task squares are selectable and things look normal. I created the project by importing a GeoJSON file and using the square grid option to define task squares. This has happened a few times before. I've checked validity of the polygon in QGIS. It seems unfixable, so I recreate the project using the same GeoJSON and delete the bad one project. The new projects seem stable. 5475 is Archived, please take a look. My first ticket, please bear with me.

**Comment by ethan-nelson** [comment]
Hi @edircksen thank you for filing the ticket--you're in the right place. Would you mind sending the geojson to ethan.nelson@hotosm.org? I'd like to take a look at the behavior in my local environment to try and figure this out. Thanks!

**Comment by edircksen** [comment]
Hi, Ethan,

Attached are 2 geojson files. BornoNganzai.geojson is the file I used to create the HOT TM project (5475, archived). BornoHganzaiGrid.geojson is the project AOI polygon downloaded from TM. There is a slight difference, I don't know if it's meaningful. Thanks for your help. I look forward to learning from this.Thanks


Eric Dircksen, Volunteer

________________________________

**Comment by willemarcel** [comment]
It doesn't apply to TM4.
