### ISSUE TITLE
Italian language translation 

### ISSUE THREAD

**Issue by AleZena** [hotosm/tasking-manager#1351]
Hello,
it seems Italian language is ready to be used.

Alessandro a.k.a. Ale_Zena_IT

**Comment by ethan-nelson** [comment]
Thanks for the notice @AleZena . We weren't able to grab the updated translations prior to the last release, but I will make sure to pull them down this week.
Cheers,
Ethan

**Comment by xamanu** [comment]
The update of the italian language has been part of the 3.3.2 release. Thanks!
