### ISSUE TITLE
Conditional RDS creation in the CloudFormation template

### ISSUE THREAD

**Issue by arunasank** [hotosm/tasking-manager#1352]
Ref: https://github.com/hotosm/tasking-manager/issues/1327

A CloudFormation template has several parts: `Parameters`, `Resources` and `Conditions` are important for the tasking-manager template. 

A `Condition` enables you to create resources conditionally. 

```
"Conditions" : {

  "<Key>" : {Intrinsic function}
}
```

* The `<Key>` is user defined.
* The `{Intrinsic function}` is a CloudFormation way to write JSON functions: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html.

## Steps
1. Craft a condition, that checks if the `Snapshot` parameter is not empty and the `RDSUrl` is empty, and add it to the conditions section of the template.
2. Add the `"Condition" : "<Key>"` key value pair to the `TaskingManagerRDS` object under `Resources`.
3. Deploy and test the stack to make sure that the RDS resource is getting created only when the condition you have created is true. You'd also have to ensure that the `TM_DB` environment variable is set, based on this condition.

Happy to answer any questions as you're working through it!

cc/ @hotosm/tech

**Comment by dakotabenjamin** [comment]
@arunasank with the commits I pushed to #1327 can we close?

**Comment by arunasank** [comment]
@dakotabenjamin yep for sure. I haven't deployed it myself, but I think you did and things looked good? Please feel free to close.

**Comment by dakotabenjamin** [comment]
If we run into issues later we can address them in the PR
