### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by kleper** [hotosm/tasking-manager#1357]
Hello,

I'm trying to update the OSMColombia Tasks server to the last release of version 3 of the task server, but at the end of the process I'm having the following error:
Feb 27 12:43:11 TM3 gunicorn [1959018]: [2019-02-27 12: 43: 11,829] CRITICAL in mapping_apis: Task GET API - unhandled error: 'TASK_AUTOUNLOCK_AFTER'

Can you help me solve this problem? Is there documentation on how to update?

Thank you.

**Comment by xamanu** [comment]
Hi @kleper. Which version are you upgrading from?
There is a wiki page on TM2-TM3 migration: https://github.com/hotosm/tasking-manager/wiki/Migrating-from-TM2-to-TM3

**Comment by kleper** [comment]
Hi, i have TM3.
i was testing the update on my "sandbox" installation https://talleres.openstreetmap.co/ but it failing.
Thanks

**Comment by ethan-nelson** [comment]
@kleper have you made many customizations to the TM after installing? It sounds like there could be a missing variable in the python server configuration script (https://github.com/hotosm/tasking-manager/blob/master/server/config.py) or it's not getting defined when Flask boots up.

**Comment by kleper** [comment]
Thanks Ethan, change my config.py for the new one and solve the problem.
