### ISSUE TITLE
ready2go: copyable ISO8601 timestamps in expert mode

### ISSUE THREAD

**Issue by nrotstan** [hotosm/tasking-manager#1359]
> Note: this feature has been implemented, but not yet submitted as a PR

* Users in expert mode can hover over a timestamp to view it in IS08601 format
* Clicking the ISO8601 timestamp copies it to the user's clipboard
* Users who are not in expert mode continue to experience existing behavior

![copyable_timestamp](https://user-images.githubusercontent.com/445970/53646961-52927d80-3bf1-11e9-85d0-9493c91805aa.gif)

**Comment by xamanu** [comment]
I like this small but comfortable improvement. What do you think @russdeffner?

**Comment by russdeffner** [comment]
Yes, this is a great subtle feature that will also help us flush out what expert mode will be useful for.
