### ISSUE TITLE
ready2go: project activity sorting and filtering, with task links

### ISSUE THREAD

**Issue by nrotstan** [hotosm/tasking-manager#1360]
> Note: this feature has been implemented, but not yet submitted as a PR

* Allow sorting of project activity by date
* Allow filtering of project activity by action and username
* Allow filtering by latest action per task
* Include link to task

<img width="1267" alt="activity_all" src="https://user-images.githubusercontent.com/445970/53649236-91770200-3bf6-11e9-8f8a-1be89dc25820.png">

<img width="1215" alt="activity_invalidated_latest" src="https://user-images.githubusercontent.com/445970/53649246-96d44c80-3bf6-11e9-81d3-1d9c5efafe84.png">

**Comment by xamanu** [comment]
This will help the project managers a lot! What do you think, @russdeffner?

**Comment by russdeffner** [comment]
Oh yes, this is a big win for PMs, Mapping Team Leads, Validators, Donors and anyone that wants to dig into the mapping/QA dynamics happening in a particular project. Especially love the quick check-box for 'only last action' so you're not swamped by a flood of lock/unlock.
