### ISSUE TITLE
ready2go: inbox sorting, filtering, message types, and delete multiple/all

### ISSUE THREAD

**Issue by nrotstan** [hotosm/tasking-manager#1361]
> Note: this feature has been implemented, but not yet submitted as a PR

* Classify inbox messages by type, such as "system", "validated", "invalidated", "mention", etc.
* Show project and task associated with messages, when appropriate
* Allow filtering of messages by type, sent-from user, project, and task
* Allow sorting of messages by date/time sent
* Support selection of multiple (or all) messages and offer Delete All Selected action (fixes #916)

<img width="1263" alt="inbox_all" src="https://user-images.githubusercontent.com/445970/53660685-4a4b3a00-3c13-11e9-92b4-876aee72280c.png">

**Comment by xamanu** [comment]
This is a great enhancement. I'm looking forward to the PR.

**Comment by russdeffner** [comment]
Going hand in hand with the subtle nudging for email - important improvements to how messaging works, and is displayed in the inbox!

**Comment by xamanu** [comment]
This has been achieved in #1423. This issue can be closed.
