### ISSUE TITLE
ready2go: OSMCha option in task Advanced area

### ISSUE THREAD

**Issue by nrotstan** [hotosm/tasking-manager#1362]
> Note: this feature has been implemented, but not yet submitted as a PR

* Add an OSMCha option to the task Advanced area
* Clicking it opens OSMCha and applies a bounding box filter and a starting date set to the timestamp of the earliest history entry for the task

<img width="571" alt="advanced_osmcha" src="https://user-images.githubusercontent.com/445970/53661320-eaee2980-3c14-11e9-8fec-784fe0ab973f.png">

**Comment by zlavergne** [comment]
@nrotstan would this feature be easily implemented at a project level?
