### ISSUE TITLE
ready2go: Aways show task Advanced options to expert users

### ISSUE THREAD

**Issue by nrotstan** [hotosm/tasking-manager#1363]
> Note: this feature has been implemented, but not yet submitted as a PR

* Always show task Advanced options to expert users -- no need to click to expand
* Do not offer task Advanced options at all to non-expert users

**Comment by xamanu** [comment]
@nrotstan Is this related to "mapper level" or "expert mode"?

**Comment by nrotstan** [comment]
It's based on expert mode

**Comment by xamanu** [comment]
This is a very strong assumption. I could imagine about advanced users that don't want to use the expert mode (extended display) and beginner users (with experienced people behind it) that may want to use the expert mode.

I would suggest to have a bit less intrusive behaviour. Maybe a message after a user became an advanced mapper that there is an expert mode and allow them to activate it with one click.

**Comment by willemarcel** [comment]
It doesn't apply to TM4.
