### ISSUE TITLE
ready2go: split tasks with arbitrary geometry

### ISSUE THREAD

**Issue by nrotstan** [hotosm/tasking-manager#1364]
> Note: this feature has been implemented, but not yet submitted as a PR

* Support splitting of tasks that did not have a square grid applied to them

![spit_arbitrary](https://user-images.githubusercontent.com/445970/53661903-669ca600-3c16-11e9-9786-3972e7fbf310.gif)

**Comment by xamanu** [comment]
This is awesome!
