### ISSUE TITLE
ready2go: Encourage users to add email address

### ISSUE THREAD

**Issue by nrotstan** [hotosm/tasking-manager#1365]
> Note: this feature has been implemented, but not yet submitted as a PR

* Show a navbar badge (red exclamation point) next to username if user has not set an email address
* Show same badge next to "Your profile" menu option on nav dropdown
* Show message on profile page encouraging users to add an email address if needed

<img width="274" alt="email_badge" src="https://user-images.githubusercontent.com/445970/53662697-6b625980-3c18-11e9-963a-6113d04a7c85.png">

<img width="457" alt="email_notice" src="https://user-images.githubusercontent.com/445970/53662778-9c428e80-3c18-11e9-8cb7-22ea02ae072f.png">

**Comment by xamanu** [comment]
This seems to be a duplicate and aligned to #1243.
For us this is very important! Thanks @nrotstan for bringing this in.

Here is my comment on this topic (taken from the other issue):

> This is probably a big bottleneck for all kind of communication that can happen on the Tasking Manager, like getting feedback from validators, success of projects the mapper participated, etc.
>
> Said this, I would go even further and suggest to just require every user that maps to have a verified email address in their profile.

@nrotstan @smit1678 @russdeffner

**Comment by xamanu** [comment]
Yes, indeed this is less intrusive. However, I think, at least `validators` and `project managers` must have an email address! And, it seems to be one of our biggest bottleneck on mappers retention, that we don't have a way to communicate with most of people who sign-up (not even to give feedback on their mapping, e.g. validated/invalidated a task).

Wouldn't it be more complex to introduce a logic and corresponding dialogs that check email addresses for validators and project managers and isn't it easier to just enforce all users to put some point of contact (the email address in a first step) to do any activity on the system.

**Comment by russdeffner** [comment]
I think this is a decision to be made on this point @xamanu - if we just require email, then this particular change would no longer be necessary. I do think implementing a program-wide requirement would be easier, just not sure if that requirement would result in people deciding not to map (via the TM). Probably very little, but maybe not necessary to find out?

**Comment by xamanu** [comment]
Giving an email address is most common on all platforms, people with concerns on privacy can just use any email address they signed-up anywhere, and we have clear numbers that we have a low retention rate and conclusions from research that this is most likely connected to a missing communication flow.

I clearly incline towards just enforcing everybody to set their email address. This is a requirement to give and get feedback and therefore part of any mapping activity.

**Comment by zlavergne** [comment]
I agree with @xamanu almost any other system out there requires a form of contact if it's not supplied by OAuth. I don't think it would be discouraging or intrusive if we implemented another step after the current login/OAuth step that requires adding an email address.

**Comment by uwaiszaki** [comment]
@xamanu @ethan-nelson I would like to work on this.

**Comment by uwaiszaki** [comment]
@xamanu @ethan-nelson  I would like to work on this issue. 
<img width="457" alt="tmissue1365" src="https://user-images.githubusercontent.com/32809190/54838195-05846180-4cee-11e9-9c5e-103c3e86dd5e.png">
Do i need to add this message box on home screen like the cookie message?

**Comment by xamanu** [comment]
I still think we should make it obligatory to fill in the email address.

**Comment by uwaiszaki** [comment]
@xamanu Should I include a message box like cookie message or redirect the user to profile page with a message to add email after login?

**Comment by xamanu** [comment]
Recapping a bit the options on the table:

1. Design as proposed by @nrotstan (using his code, he can put into a PR) and implement rather a block for people who haven't added their email to do any actions, like *Start mapping*, *Start validating* or *Add message* together with a small notice that they need to add an email address in their profile.
2. Prominent message, similar to the cookie message. I think this shall come with a similar functionality to block on all actions, as for 1. Comparing the two ideas, I incline a bit more towards 1, but I guess this is very subjective, and everybody will have its own preference.
3. Redirect to profile with message to add email. This is probably the easiest option to implement. But also a bit rough to the user. It shall redirect on any action a user wants to do, not just after login.
4. Redirect to a special page to only add the email. This is probably the most to code. It gives the user a clear flow and it separates the logic of having an email or not from the actions (as proposed in 1. and 2.). I think the argument against this is more on the validation of the email address. We would block the user from exploring the Tasking Manager until the user has validated their email address. This can become annoying, especially in case the email server uses greylisting and emails lasts several minutes to come through.

Looking at the different options, I tend to go for 1. What do others think? Did I miss any other suitable way to do this?

**Comment by uwaiszaki** [comment]
@xamanu @ethan-nelson I have blocked the start validating button and also added a warning box similar to the cookie message to add email as a start, Please give ur reviews.
![tmissue1365(1) gif](https://user-images.githubusercontent.com/32809190/55103783-259d9180-50ef-11e9-961c-083068047656.gif)
