### ISSUE TITLE
New fields for user profiles to encourage interaction

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/tasking-manager#1370]
Add additional optional attributes to user profiles including:

- email address
- photo
- location
- social media handles
- user profile on Missing Maps http://www.missingmaps.org/users/#/
- Skype/IRC/Slack handles
- other items mentioned in #613

Motivate and prompt users to fill out their profiles with a % completion and occasional prompts a la LinkedIn.

**Comment by 75pollet** [comment]
Hi,  @xamanu @TylerRadford, i would like to work on this issue

**Comment by xamanu** [comment]
This is heavily related to the design improvements @hotosm/major is currently doing.

**Comment by willemarcel** [comment]
On the redesign context, I saw the necessity of the following new fields on User model: first_name, last_name, city and country.

**Comment by willemarcel** [comment]
@fitoria are you currently working on this? When possible, please add the fields `name`, `city` and `country`. I prefer just a `name` field, instead first and last names. Some opinions, @xamanu ?

**Comment by fitoria** [comment]
Fields updated on PR
