### ISSUE TITLE
Consider a 'Share my contributions' link

### ISSUE THREAD

**Issue by CloCkWeRX** [hotosm/tasking-manager#1371]
Similar to #356, but for user pages.

http://tasks.hotosm.org/user/CloCkWeRX for example is great, but there's no rss feeds or ways to embed this in a site, or to easily share on social media.

Unlike sharing a project page, this potentially attracts a steady stream of eyeballs to a variety of tasks as a medium-heavy contributor repeatedly works on various projects.

**Comment by willemarcel** [comment]
That area in TM4 needs authentication, so this idea doesn't apply
