### ISSUE TITLE
Gamification

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1374]
The Tasking Manager should reward people for doing good mapping and data validation. For example, give people points or badges for mapping, validating squares, fixing invalidated squares, and also some for making good quality data.

**Comment by uwaiszaki** [comment]
@xamanu Giving people badges for contributing is also a good option. For example, the first contributor of the month, max contributions.

**Comment by theprover97** [comment]
Hi, I'm a GSoC 2019 applicant and i look forward to work on the project idea of Tasking Manager: Gamification. I have worked on an issue of tasking-manager(#1372) and am currently working on some other issues. I request you to  guide me through this project's ideas and tell me about its relative place in the whole tasking-manager project.

**Comment by ethan-nelson** [comment]
One other consideration is the Missing Maps badges that currently exist (e.g. http://www.missingmaps.org/users/#/FTA). For now, we've just linked to the user profile page on Missing Maps from the TM profile page.

**Comment by theprover97** [comment]
Hi @xamanu . Can we still work on this idea?

**Comment by xamanu** [comment]
For now let's go with https://github.com/hotosm/tasking-manager/issues/1381 and close here.

**Comment by shloak17107** [comment]
Hi @xamanu. Can this issue be reopened since it is a project for GSoC 2020?

**Comment by pydevsg** [comment]
Yes, @xamanu , please reopen this issue and help me in guiding through this project, thanks.
