### ISSUE TITLE
Improve UX of project creation wizard

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1375]
The wizard to create projects in the TM, is a step-by-step guide to select the region of interest and splits up the area into smaller tasks that mappers can reserve for them, mark them as mapped, when they are done, and then let validators check the data. The project creation wizard shows some inconsistencies and there are good ideas for improvement.

This issue consists in conducting initial interviews with well experienced project managers of the TM, and an analysis on the wizard and potential changes for improvement. After this analysis, the agreed changes and solutions with the HOT team shall be implemented and a new version of the TM will be released.

**Comment by xamanu** [comment]
Some notes when interviewing project creators for detecting pain points:

- Is it possible to suggest the best imagery for a region? (currently in JOSM you check and then you integrate)
- Maybe support description creation (best practices)
- Overlapping projects are not completely solved
- Turn off split would be nice
- Feature request: Task size to be adjustable by km2
- Feature request: Carry over task number to step 4 or merge step 3 and 4.
- Default Mapper Level should be difficulty
- Private project needs manual user name adding; import csv? maybe transform into "Unlisted" type GDoc sharing link
- Organizations tags are not unique...
- Creation menu is not very consistent
- Is is possible to delete a project after resetting the tasks. Is this wanted?

**Comment by xamanu** [comment]
First design input on this to better structure the project creation flow:

![image](https://user-images.githubusercontent.com/97706/77058568-88a5c980-69cd-11ea-8a8b-beb297835e9c.png)

**Comment by xamanu** [comment]
And some [wireframes](https://projects.invisionapp.com/share/CBV5H8O79J5#/screens/396624665_TM-1-Create_Project_General_Info) on how this could look like.

**Comment by willemarcel** [comment]
We improved greatly the project creation page on #4089

**Comment by bopercival-hot** [comment]
imrpovements done - closed
