### ISSUE TITLE
Better wording for "invalidated" tasks

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1376]
In a nutshell: Change “invalidated” to “help needed”, and squares aren't red but another color

People often don't fix invalidated squares. One idea is to change the name or color of invalidated squares to something that sounds more positive, or to encourage people to want to come back and help. Maybe “help needed” and gray or yellow? Some other pattern perhaps?

**Comment by xamanu** [comment]
cc: @hotosm/major, @nrotstan

**Comment by xamanu** [comment]
This is part of the ongoing work with @hotosm/major  and the related redesign.

**Comment by theprover97** [comment]
But mapped areas are already marked yellow, and bad imagery is opaque black. We can use light blue for Invalidated (i.e. "Help Needed") Tasks.

**Comment by xamanu** [comment]
@russdeffner, @hotosm/major, what do you suggest as a good wording, instead of "Invalidated"?

**Comment by russdeffner** [comment]
If it isn’t restricted to one word, I think “needs additional mapping” would be good

**Comment by theprover97** [comment]
And what color scheme should we choose for the same.

**Comment by russdeffner** [comment]
I liked the light grey similar to TM2 but even just swapping the current invalidated and bad imagery state colors would be improvement in my opinion.

**Comment by theprover97** [comment]
So these are the changes for the time being? Then can I work them out?

**Comment by xamanu** [comment]
The designers suggested "More work needed":

![image](https://user-images.githubusercontent.com/97706/58172792-0fdcc080-7c89-11e9-8281-77f6ee6d2886.png)

Does this work for you, @russdeffner?

**Comment by russdeffner** [comment]
Wording wise, yes - "more work needed" I think is better than "invalidated" - I don't like the colors though. One of the problems we were trying to address is mappers not going for the 'red' invalidated squares, so a softer, more inviting color should be used. Also Bad Imagery is no longer there, is that because we are removing the functionality or just didn't get onto this mock-up?

**Comment by xamanu** [comment]
Cool. Then we know that we go with "More work needed".

The colour discussion I would like to centralize in #1257 and will do there a small write-up today.

**Comment by xamanu** [comment]
![](https://user-images.githubusercontent.com/26889634/68822765-bea80980-06cc-11ea-8691-6b3c5bcf5d41.png)

We came up with these colours and naming. "Invalidated" became "More work needed". Closing here. Thank you.
