### ISSUE TITLE
Give mappers feedback to their contribution and remind them to come back via email

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1378]
Often mappers don't return to map after the first time. After a mapathon or event, send an automated thank you for mapping and a reminder to keep going.

**Comment by xamanu** [comment]
cc: @hotosm/major, @nrotstan

**Comment by theprover97** [comment]
@xamanu, I would like to work on this issue. Can you please tell me how to get started on this?

**Comment by xamanu** [comment]
@theprover97 Apologies, this is already assigned to @fitoria and I think he has already started with a good amount of code.

**Comment by xamanu** [comment]
Thanks for the PR, @fitoria. I checked it and realized you are introducing weekly summary mails for mappers. I'm not sure this is going for the purpose we had here. This might be a bit too much for mappers to receive.

What about encouraging depending on progress in the project (50%, 75%, 90%):

```
Hi [USERNAME]

you recently participated in the mapping project - [PROJECT_NAME] -  on the [TM_INSTANCE_NAME].

We want to inform you the project has reached [PERCENTAGE_COMPLETENESS]% of completeness. 

Please login and help us to finish the project!

Thank you!
```

For the redesign we wanted to recommend projects, but this requires a logic to be in place for recommended projects (#1612):

![image](https://user-images.githubusercontent.com/97706/58959316-560b4700-8794-11e9-879b-5bda7f5a5a21.png)

We could use this kind of list also for a project that reaches 100% completeness:

```
Hi [USERNAME]

you recently participated in the mapping project - [PROJECT_NAME] -  on the [TM_INSTANCE_NAME].

We want to inform you the project has been completed. It is time to celebrate! 

Do you want to continue? How about exploring this list of projects we selected for you?

[RECOMMENDED_PROJECT_LIST]
```
