### ISSUE TITLE
ready2go: cross-project All Activity page

### ISSUE THREAD

**Issue by nrotstan** [hotosm/tasking-manager#1384]
> Note: this feature has been implemented, but not yet submitted as a PR

* Add new All Activity page showing activity across projects (like #1360 offers for a single project)
* Allow filtering of activity by project name
* Restricted to validators, project managers, and admins
* New page is accessible via top-nav dropdown menu

<img width="1238" alt="all_activity" src="https://user-images.githubusercontent.com/445970/54144677-6efc9a00-43e9-11e9-9433-e0428f51ddf2.png">

**Comment by zlavergne** [comment]
> * Allow filtering of activity by project name
@nrotstan there is also a box under `User`. Can you also filter based on user?

**Comment by nrotstan** [comment]
@zlavergne Yes, username filtering and everything else from PR #1360 (single project activity) is supported.

**Comment by ramyaragupathy** [comment]
Closing this for now.
