### ISSUE TITLE
Message page: Able to access message page with non existing message id.

### ISSUE THREAD

**Issue by uwaiszaki** [hotosm/tasking-manager#1389]
We can access the message page with a fake message id.
There should be a 404 error status to show that the message does not exist.
![hotosmtaskmanagernewissue2](https://user-images.githubusercontent.com/32809190/54474081-55eb5300-4806-11e9-9e7a-3eb47209ad96.png)
@smit1678 @xamanu @ramyaragupathy I would like to work on this issue.

**Comment by xamanu** [comment]
Thanks for noticing, @uwaiszaki and feel free to take this task.

**Comment by uwaiszaki** [comment]
@xamanu I have created a pr #1400. Kindly give ur reviews

**Comment by xamanu** [comment]
This has been done by @uwaiszaki and has been merged into `develop`. It will be part of release 3.3.
