### ISSUE TITLE
Cloudformation TM Way Ahead

### ISSUE THREAD

**Issue by arunasank** [hotosm/tasking-manager#1395]
👋 @hotosm/tech 

Last week, we saw a [pretty significant performance improvement in the tasking manager](https://github.com/hotosm/tasking-manager/issues/1354#issuecomment-472934872). By changing `gunicorn` to use threads instead of synchronous workers, the tasking manager is able to:

* Take on more requests, and complete them asynchronously in a shorter period of time.
* Use smaller and cheaper AWS instances
* Use a smaller and cheaper RDS instance

This also means that we'll have more detailed metrics, and ways to monitor our stacks.

## Next steps to wrap up the CloudFormation work

We have a few key decisions to make as we wrap up this migration. 

Please weigh in with your thoughts on the following, @xamanu, @smit1678, @dakotabenjamin and the rest of @hotosm/tech-staff, so we can wrap up the CloudFormation migration in a way that makes the most sense.

* **Upgrade to an ALB (Application load balancer)**: Currently, we are using an elastic load balancer. We can migrate to a more advanced "Application Load Balancer" to take advantage of better metrics and load balancer performance and customisation.
* **Take a call on our deployment strategy**: Moving to CloudFormation from ElasticBeanstalk would require us to change our deployment methods. Currently, our deploys are tied together tightly with CircleCI. This means, a code merge with the `develop` branch creates an automated deploy to our staging stack, and a code merge with `master` creates an automated deploy to the production stack. After the switch, we have one of two options:
  * **Easy**: We would have to manually deploy to a staging stack using `cfn-config` and after testing the changes, manually deploy to a production stack using `cfn-config`. This would mean that we no longer do code merges. We always 
    * Use `cfn-config` to deploy to the `staging` stack from the development branch, or the branch used to create a PR. (before the merge)
    * If things look good on `staging`, we merge the branch with `master`, and deploy to `production`. Anything merged with `master` is always final, and in line with production. So, a merge with `master` is always accompanied with a deploy to `production`
  * **Hard** If we want to retain the automated deployment model we currently follow, we would have to build this with AWS Code Deploy, using AWS Code Config.
I would prefer us going ahead with the easy deployment strategy for our first iteration, but document the process really well, so that anybody on the team is able to deploy.
* **Spring cleaning** Decide on maintaining EBS files and data. Should we dump, or keep?
* **Cleanup old RDS snapshots and databases** We have a ton of old snapshots, and databases that are stale. We can dump several of these.
* **Spot instances** We have a call with our AWS manager tomorrow, when we can make a decision about this. This will be a org-wide push, and will not be implemented for the first iteration of the tasking manager.

There are a few more items listed on https://github.com/hotosm/tasking-manager/issues/1353.

**Comment by xamanu** [comment]
Thanks for the update, @arunasank! It is know about these performance improvements!

* Upgrade to an ALB: Great that we are ready for the future.
* Take a call on our deployment strategy: This is a bit more difficult, not having the automatic deployment of staging. But it makes sense to have one workflow for all kind of stacks in HOT. Currently all others don't have auto deployment. So, probably we can work with a well-documented easy but manual work flow for now, and at a later point we might want to improve the overall infrastructure with auto deployments.
* Spring cleaning: Not sure whether we want to actively want to maintain them. Maybe we can move them into the `devops` directory.
* Cleanup: Cool!

**Comment by dakotabenjamin** [comment]
See https://github.com/hotosm/tasking-manager/pull/1396 for nearly finished ALB work

**Comment by dakotabenjamin** [comment]
- **Add alarms for status page to template** Currently TM3 has 2 alarms that should be tracked, then we can update the triggers in Lambda to follow those instead of the EB alarms (below). 

![image](https://user-images.githubusercontent.com/1847818/54534101-1174ca00-4962-11e9-8f60-7737d18d2f10.png)

**Comment by arunasank** [comment]
Copying over some tasks from https://github.com/hotosm/tasking-manager/issues/1353, so we can close there:
* **Set up all our TM stacks using CloudFormation**: Make a detailed plan for deleting existing EBS environments, and setting up TM stacks on CloudFormation, to ensure that the process is seamless and secure, and we don't accidentally lose data.

**Comment by ramyaragupathy** [comment]
:+1: [Awesome](url) @arunasank 

|tool|time taken|
----|-----|
**_help_**

- 1
- 2

**Comment by arunasank** [comment]
## Tasks

@dakotabenjamin feel free to edit this comment once you finish a task.

Task | Owner | Status
-------|----------|----------
Migrate to the ALB | @arunasank | ✅ 
Update our deployment strategy. Use cfn-config based commands in our circle ci: https://github.com/hotosm/tasking-manager/issues/1444 | @dakotabenjamin  | 
Reduce bootstrap time | @arunasank |
RDS Audit | @arunasank |
Cleanup EBS deps | @dakotabenjamin |
Plan out Cloudformation deploy dates and process etc | @dakotabenjamin @arunasank

**Comment by dakotabenjamin** [comment]
I updated the comment about and added a note about documentation

**Comment by arunasank** [comment]
@dakotabenjamin @xamanu  and I wrote up the docs two weeks ago, but forgot to share it here: https://paper.dropbox.com/doc/Tasking-Manager-CloudFormation-Deployment--AdAaQ3qMag2hWzmYFsfxpqXOAg-OANrQbPkejRThZj8f19wL

**Comment by arunasank** [comment]
Tracking this separately from the CFN deployment: https://github.com/hotosm/tasking-manager/issues/1467

**Comment by dakotabenjamin** [comment]
OK- I think this one is good to close but please reopen if there's anything else
