### ISSUE TITLE
Drop down menu in mobile view is not closing when clicking outside the menu.

### ISSUE THREAD

**Issue by uwaiszaki** [hotosm/tasking-manager#1404]

**Comment by ethan-nelson** [comment]
Just to add some clarifying info, it's specifically the hamburger menu that does not close automatically on mobile. Thanks to #1397, the menu for the user menu does indeed close after being clicked. 

![tmmenu](https://user-images.githubusercontent.com/8998918/54968714-df063680-4f38-11e9-8cf1-bbe82ae741bb.png)

**Comment by xamanu** [comment]
Thanks for the fix!
