### ISSUE TITLE
Clicking Contribute is taking it to /contribute?difficulty=ALL

### ISSUE THREAD

**Issue by uwaiszaki** [hotosm/tasking-manager#1405]
Clicking contribute on homepage takes us to /contribute?difficulty=ALL but when we click back, instead of going to the home page it redirects us to /contribute.
![tmnewissue4](https://user-images.githubusercontent.com/32809190/54841968-a1b26680-4cf6-11e9-8013-e6113ee1745d.gif)
@xamanu I would like to work on this.

**Comment by willemarcel** [comment]
It doesn't apply to TM4
