### ISSUE TITLE
Broken navigation menu when resizing window

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1409]
Steps to reproduce:

1. Resize browser to be very skinny, such that the hamburger menu activates.
2. Click on the hamburger menu to open/activate it.
3. Resize the browser to be bigger, such that the hamburger menu icon disappears. You will be left with the activated hamburger menu window and no way to close it. Additionally, because of the behavior mentioned in #1404, you cannot close the menu just by clicking elsewhere.

![tmstuck](https://user-images.githubusercontent.com/8998918/54969230-9f404e80-4f3a-11e9-8adb-4d91340e1821.png)

**Comment by uwaiszaki** [comment]
@ethan-nelson I would like to work on this.
