### ISSUE TITLE
gateway timeouts very often

### ISSUE THREAD

**Issue by dkocich** [hotosm/tasking-manager#1412]
Many errors appear in the tasking manager and UI acts weird (I was unassigned from validation task with "The task expired and was automatically unlocked." / "Invalid project. Please select another project.", UI won't load or respond correctly, etc.).
Similar issues appear also for other marathon participants and last for almost an hour...

![image](https://user-images.githubusercontent.com/6165660/55028106-31ae2400-5007-11e9-9068-0c60bf66450c.png)

**Comment by xamanu** [comment]
Thanks for reporting @dkocich! We faced some problems in our building pipeline, yesterday. This result in an performance issue with our server infrastructure. This should have been fixed by now.

Can you please confirm that all is back to normal? Thanks.

**Comment by dkocich** [comment]
everything looks ok now - closing if you say that it is fixed...
