### ISSUE TITLE
CircleCI builds failing for develop branch on deployment step

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#1425]
It fails in the deployment while running `circleci_deploy.sh`. 
```
 pip install -r requirements.aws.txt
.
.
.
Building wheel for PyYAML (setup.py) ... - \ | / error
  Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-62syfglp/PyYAML/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-_endpok3 --python-tag cp37:
<traceback emitted>
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for PyYAML
```

Perhaps this can be fixed simultaneously in #1424 ? cc @xamanu

**Comment by xamanu** [comment]
This PR runs through: #1427 (but I had a different error)

**Comment by hunt3ri** [comment]
@dakotabenjamin the issue may well be related to adding the python-dev to the docker container as discussed here

https://github.com/aws/aws-cli/issues/2290
https://github.com/aws/aws-cli/issues/2290#issuecomment-402815593

I suspect you're getting Python 3.7 which may not be compatible with PyYAML as outlined in the linked comment.  It may be better to specify python3.6 as the base image??  Good luck!!

**Comment by xamanu** [comment]
The pipeline apparently shows some inconsistencies, too. Sometimes the tests just [fail](https://circleci.com/gh/hotosm/tasking-manager/1535), while almost identical code bases seem to [work](https://circleci.com/gh/hotosm/tasking-manager/1536).

**Comment by xamanu** [comment]
@JorgeMartinezG spotted the weak point in the `.ebignore` file where `client` was explicitly excluded. This PR addresses the problem: #1433.

**Comment by ethan-nelson** [comment]
This should be fixed now
