### ISSUE TITLE
Starting docker container is giving error

### ISSUE THREAD

**Issue by uwaiszaki** [hotosm/tasking-manager#1430]
docker-compose up is giving this error
![tmnewissue5](https://user-images.githubusercontent.com/32809190/55286765-b4473280-53bd-11e9-87d4-6c95033b0ee5.png)
@xamanu I tried installing python-dotenv by "pip3 install python-dotenv", but it didn't solve my problem.

**Comment by xamanu** [comment]
@uwaiszaki Please try `docker-compose build && docker-compose up`

**Comment by uwaiszaki** [comment]
@xamanu This Solved the issue
