### ISSUE TITLE
Conflict when uploading while working on assigned tile

### ISSUE THREAD

**Issue by beataj-telenav** [hotosm/tasking-manager#1432]
I have encountered today several situations when I got a conflict error while mapping with JOSM. 
It is possible that the tile lock does not work properly?

**Comment by ethan-nelson** [comment]
Can you provide some information on the project and task?

**Comment by ethan-nelson** [comment]
Also note that locking/checking out a task for mapping is strictly in the tasking manager environment. It does not prevent anyone else from mapping in OSM for that area--they just can't access it through the TM interface easily.

**Comment by beataj-telenav** [comment]
I was mapping: https://tasks.hotosm.org/project/5852?task=495#bottom while I got the conflict.

**Comment by xamanu** [comment]
There are definitively several people mapping on the same time. The status of the task is well set however. Probably there was a very ambitious mapper, extending the area of his/her task.

**Comment by beataj-telenav** [comment]
Ok, for the next time when I'm mapping using the tasking manager, I will download again the data from OSM to double check it. 
Thank you.
