### ISSUE TITLE
Blocked User Can Comment

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#1435]
Currently a user that is blocked (i.e. Read_Only) can still comment on projects. This should be changed to ensure that a blocked user can not perform any activity on a project.

**Comment by uwaiszaki** [comment]
@russdeffner I would like to work on this.

**Comment by xamanu** [comment]
This has been addressed within release 3.2.1 for the backend. But the front end should hide the possibility to add comments. This is work in progress in #1438.

**Comment by xamanu** [comment]
#1438 and https://github.com/hotosm/tasking-manager/pull/1431 went into `develop` for the 3.4 release.
