### ISSUE TITLE
Change difficulty category names

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#1441]
I suggest we change the categories of difficulty from: "Beginner, Intermediate, Advanced" to "Easy, Moderate, and Hard (or Difficult)"

The reason is - often we have projects (i.e. all road projects that ask for classification) that are really not very beginner friendly/easy but more moderate in difficulty yet we allow beginner mappers to participate. Having difficulty categories match the level of mapper made sense when we developed TM3 but is now showing to be confusing in these cases where we don't want difficulty restriction to match mapper level.

**Comment by RebeccaFirthy** [comment]
Hiya, just chiming in on this - I agree more can be done surrounding easy>difficult scale. Another real challenge is that mappers can't tell which projects are restricted according to mapping level and which aren't, and they don't get particularly good error message if they don't have the right permissions (e.g. 'You have 12 changesets until you're intermediate'. We recently had this issue a lot with Cyclone Idai mapping where beginners wanted to contribute and couldn't figure out which to contribute to. Even after providing explanation this was the sort of message I received (from multiple people!)
<img width="782" alt="github1" src="https://user-images.githubusercontent.com/25038632/55828702-a044b480-5ad2-11e9-95df-234cef5777b0.PNG">
<img width="556" alt="github2" src="https://user-images.githubusercontent.com/25038632/55828708-a3d83b80-5ad2-11e9-8ad1-fc345a239f20.PNG">

**Comment by xamanu** [comment]
Thanks for your input @russdeffner and @RebeccaFirthy. Let's focus here on renaming of the names.
The topic on finding the right tasks and projects will be addressed with the redesign, based on the great input of @hotosm/major.

**Comment by willemarcel** [comment]
We are going to handle that issue on https://github.com/hotosm/tasking-manager/issues/2908
On TM4 we already have better and clear error messages.
