### ISSUE TITLE
Test the CloudFormation based tasking manager

### ISSUE THREAD

**Issue by arunasank** [hotosm/tasking-manager#1445]
👋 @hotosm/tech The staged version of the tasking manager is set up at http://tasks-cfn-stage.hotosm.org/. Currently, it's only been tested by me (😅), so I would love it if more people can test it, and see if something feels weird/better. 

esp. cc/ @russdeffner @xamanu @ramyaragupathy @mataharimhairi @dakotabenjamin @smit1678 @cgiovando @willemarcel

**Comment by arunasank** [comment]
Ref: https://github.com/hotosm/tasking-manager/issues/1395

**Comment by willemarcel** [comment]
Tested creating and editing project, mapping, validating, deleting message, posting comments, set bad imagery, updating user details. Everything worked great :+1:

**Comment by arunasank** [comment]
Also noting that @willemarcel noticed some lag on specific projects, where the production instance was performing better than the cloudformation instance. He has updated our load test files to hit these end points and I'll be using this new load test file to test our stacks and posting results soon. Want to note that we do run the CloudFormation TM on an instance with half the CPU and memory power as what we have on production - so if we do notice an issue in the load tests, the solution will be a simple change of the instance type we are using.

**Comment by arunasank** [comment]
We fixed this. More on https://github.com/hotosm/tasking-manager/issues/1354. The issue was with the difference in the number of instances we had on `production` and `staging`.
