### ISSUE TITLE
Audit TM stacks

### ISSUE THREAD

**Issue by arunasank** [hotosm/tasking-manager#1446]
Ref: https://github.com/hotosm/tasking-manager/issues/1395

As a way of spring cleaning the tasking manager resources and environments before we move to CloudFormation, let's look closely at our stacks and our RDS instances and snapshots and figure out which ones need to be retained/thrown away.

# Stacks
We currently have the following tasking Manager stacks hosted by HOT:
* `production`: The main TM at tasks.hotosm.org
* `stage`: The staging TM instance at tasks-stage.hotosm.org
* `teachosm`: This is the TM instance used by **TeachOSM** hosted currently on HOT resources.

Besides the above, we have the following stacks. Per chat with @xamanu and @ramyaragupathy, we aren't fully sure of why some of these stacks exist.

@dakotabenjamin @ethan-nelson can you comment if you're aware of the purpose of the stacks with a ❓ 

Stack | Purpose | Can the stack be 🗑 ? | Deleted Stack
---------|-----------|---------------|-------------
`stretch` | set up for debugging the recent deploy issue. | ✅ | yes
`demo` | ~~❓way to deploy a certain PR ❓~~ stale stack  | ✅ | yes
`test` | ❓ | ❓|

**Comment by dakotabenjamin** [comment]
@xamanu if it's ok with you i think we can destroy the `stretch` environment and it's associated database. This was setup specifically to fix some deployment problems with CircleCI and that has been completed. There shouldnt be any important or sensitive information on there.

**Comment by xamanu** [comment]
Agreed!

**Comment by dakotabenjamin** [comment]
`demo` is an old stack that we couldn't fully delete because of an odd resource dependency. I'm haven't taken a look at it in a while but iirc it was a security group. I think we could force delete the stack without removing the dependency (leaving it floating out there in the wild) by deleting it via cloudformation. 

`test` replaced `demo` in function and has been used in the past to test specific branches. This is done by changing a variable in the CircleCI app by hand, then pushing changes to the branch. Currently it's deploying the `tm4ml` branch for devseed development. I think having a stack like this is generally useful, especially for testing deployments without having to push to the protected `development` branch on GH.

**Comment by arunasank** [comment]
👍 Thanks @dakotabenjamin and @xamanu !

> `test` replaced `demo` in function and has been used in the past to test specific branches. This is done by changing a variable in the CircleCI app by hand, then pushing changes to the branch. Currently it's deploying the `tm4ml` branch for devseed development. I think having a stack like this is generally useful, especially for testing deployments without having to push to the protected `development` branch on GH. 

Does this mean that this stack is not being actively developed or tested? Can we
1.  Delete this stack
2. Recommend the _manual_ creation and deletion of stacks for use cases independent of the `stage` and `prod` stacks. That way, we know _why_ someone is creating a stack, and it's very clear if the stack can be deleted or not once it's finished being used.

**Comment by dakotabenjamin** [comment]
@smit1678 do we know the status of testing for the `tm4ml` branch? At least we should coordinate with DevSeed or other ML developers before we delete, and then determine how to run this type of coordinated deployment under the new system.

**Comment by arunasank** [comment]
Reffing the PR, so we know we can 🗑 this stack, once the PR is merged with `develop`: https://github.com/hotosm/tasking-manager/pull/1349

**Comment by arunasank** [comment]
Per chat with @xamanu , the `taskingmanager-test` stack can be binned! Going to wait another day to see if anyone else wants it around. cc @ethan-nelson and @dakotabenjamin

**Comment by arunasank** [comment]
Binned this stack today. Closing here!
