### ISSUE TITLE
Audit TM deployment strategy

### ISSUE THREAD

**Issue by arunasank** [hotosm/tasking-manager#1449]
# Deployment strategies

As a means of maintaining and paying for only the necessary stacks, let's think about revising our deployment strategies, as we move to CloudFormation.

### Existing
Currently our deployment strategy involves:
* Merge with `develop` => Circle CI pushes to `stage` so that changes can be tested at https://tasks-stage.hotosm.org.
* If things look good on `develop`, merge with `master` =>  Circle CI pushes to `prod` so that changes can be tested at https://tasks.hotosm.org.

From time to time, we have a need to test a feature outside of our CI pipeline, to reproduce a crash or a specific issue, for example, that is not tied with our release pipeline. For these cases, we set up a separate CI pipeline that deploys to a fresh TM stack - `demo` or `test` or something new like `stretch`. 

### Proposal
* Have only two deployment environments - `prod` and `stage`, that mimic our existing deployment strategies. This will mean that on any normal day, there are three TM environments that HOT is running:
  * `prod`: HOT production stack
  * `stage`: HOT staging stack
  * `teachosm`: TeachOSM stack that HOT is maintaining the infrastructure for
* Any other environment that we set up is set up manually, as and when required, using `cfn-config`, so that we can minimise the number of environments we run. Such stacks are also binned after they serve their purpose.

cc/ @hotosm/tech let me know your thoughts!

**Comment by dakotabenjamin** [comment]
something nice with the `tm4ml` branch is that the developer can push changes without our input. Would the be possible with a manual deployment without having to give them aws credentials (i.e. through github/circleci flow?) Perhaps we can have an environment variable on CircleCI that is normally blank but when filled could run an update, but would require a manually deployed stack already in existence? Is that too rickety...

**Comment by dakotabenjamin** [comment]
Update:

CircleCI handles the `master` branch => `production` stack and `develop` branch => `staging` stack (see https://github.com/hotosm/tasking-manager/pull/1332) 

What's left to do is the `teachosm` stack which we can also build into Circle by generalizing the `deploy-staging` job to allow for multiple branches. I propose we put that into a second phase of work so we can get these current updates into the next release.

**Comment by dakotabenjamin** [comment]
This is complete with the 3.3 release
