### ISSUE TITLE
iD Editor keyboard shortcut "s" will change to "q"

### ISSUE THREAD

**Issue by tordans** [hotosm/tasking-manager#1450]
Hi, this is a heads up that in the next release of iD, the keyboard shortcut to square a buildings will change from <kbd>s</kbd> to <kbd>q</kbd>. 

<img width="1003" alt="Bildschirmfoto 2019-04-08 um 20 34 12" src="https://user-images.githubusercontent.com/111561/55748043-ed2a7b80-5a3d-11e9-90ab-5704998923dc.png">

([Source](http://preview.ideditor.com/master/#background=DigitalGlobe-Premium&disable_features=boundaries&locale=en&map=16.00/-4.4419/37.1617))

For the background, see https://github.com/openstreetmap/iD/pull/5999.

What is the best way to coordinate an update on the various instruction texts of tasking manager?

**Comment by ethan-nelson** [comment]
Hi @tordans I think @aawiseman is one of the folks involved in the training materials, specifically https://www.youtube.com/watch?v=VPJz-AucqF4&list=PLb9506_-6FMHZ3nwn9heri3xjQKrSq1hN&index=7. Andrew, any chance you may have the original video files handy that we can swap out at 2:06 the right shortcut?

**Comment by tordans** [comment]
Hi @ethan-nelson, I suggest we collect a list of places that need updating.

- [ ] The training video (https://github.com/hotosm/tasking-manager/issues/1450#issuecomment-481076013)

- [ ] The default-wording (I assume there is something like a copy-paste-text somewhere?) that is provided to campaign owners, like
  > Please square your buildings ('S' key in the iD web editor) and keep them unattached from roads, landuse and other buildings unless they are physically attached.
  ([Source](https://tasks.hotosm.org/project/5885#bottom))

- [ ] The current wording on each campaign that says something like "Please square your buildings ('S' key in the iD web editor)" (I assume those texts are hard coded inside the campaign description, so that needs changing.)

- [ ] Are there training docs for campaign owners, that need updating?

- and so on …

**Comment by xamanu** [comment]
This has been fixed with #2444
