### ISSUE TITLE
Need for a data audit

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1460]
Documenting known issues from our database:

- While discussing the area mismatch issue for summary stats endpoint, problem of older projects with invalid coordinate system in DB surfaced. This makes it hard to compute aggregate geometry of all projects. 

- There is also empty values for `action_text` field in `task_history` table which stores the time spent on a task. If we want to integrate models to predict average project/task completion time, empty values might skew the results.

We need to come up with an action plan to address these issues.

cc @ethan-nelson @felix @arunasank @smit1678

**Comment by smit1678** [comment]
Thanks @ramyaragupathy for getting this convo started. As we go through and audit, let's separate out into individual tasks that can be run out. I separated out https://github.com/hotosm/tasking-manager/issues/1470 to tackle that first and it seems that we can run that out as we look at #1462. 

Here's a couple other potential areas where we need to audit based on an initial ticket search and conversations with @russdeffner: 

* Issue with project admin display: https://github.com/hotosm/tasking-manager/issues/1063
* From https://github.com/hotosm/tasking-manager/issues/576 there was a call to either archive or delete old projects that have very low mapping rates. I think we go with the archive option since that is a good practice to garden and archive projects that are clearly not active. 
* is there data from deleted projects that still exist in the database? i.e. if a project was mapped to 50% but then deleted, what happened to the data? (this is just a question and haven't looked at the code)

**Comment by ramyaragupathy** [comment]
> is there data from deleted projects that still exist in the database? i.e. if a project was mapped to 50% but then deleted, what happened to the data? (this is just a question and haven't looked at the code)

A project can be deleted only if it is [0% mapped and 0% validated](https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/project.py#L270). So for project with contributions delete process throws with an error message.

![](https://paper-attachments.dropbox.com/s_ADEAF5925A0B83DFC114F9D014DAA9B1B17E16FF1DB0511DDA3D71B400839F3D_1555307784226_image.png)

@arunasank & I are looking at the rest of the criteria for project clean up today. We will post the database filtering and our action plan shortly.

**Comment by russdeffner** [comment]
@ramyaragupathy this is true; however you can ‘trick’ the TM into thinking no mapping was done by using the unmark/reset tasks to ready state buttons in edit mode and then delete the project

**Comment by ramyaragupathy** [comment]
Here’ the list of existing [projects with invalid geometry](https://docs.google.com/spreadsheets/d/1zlQCRC_hFiGLBEDf9g5QQfJxkNUFDjMAIxGTqJXaFMo/edit#gid=0). Some have coordinates beyond the projection specific bounds.


    "geometry": {
            "type": "MultiPolygon",
            "coordinates": [
              [
                [
                  [
                    -234.607543945312,
                    11.6939279489023
                  ],
                  [
                    -234.607543945312,
                    11.5594166628307
                  ],

 A few others have coordinates in a different projection:
 

     "geometry": {
            "type": "MultiPolygon",
            "coordinates": [
              [
                [
                  [
                    301577.861786219,
                    677553.623917146
                  ],
                  [
                    301577.861786219,
                    677553.623758481
                  ]

Projects with a different projection from the existing ones throws a `Polygons and MultiPolygons should follow the right-hand rule` while validating with [geojsonhint](https://github.com/mapbox/geojsonhint).

For now I feel all those projects that don’t display well on the TM and with nil contributions should be deleted. With a Jan snapshot I could spot 7 such projects.

Rest of the invalid geometry projects with nil contributions can be removed after messaging the authors.

Here’s also the list of projects with low mapping rates (mapping< 10%) and no updates in the last 2 years:


  | total | archived | published | draft
-- | -- | -- | -- | --
low mapping rates (mapping< 10%) and updates < 2017 | 540 | 324 | 100 | 116


We should delete the 116 projects that are in draft after letting the authors know about the cleanup. Rest 100 projects we could archive

@xamanu @ethan-nelson @smit1678 - thoughts?

**Comment by xamanu** [comment]
> We should delete the 116 projects that are in draft after letting the authors know about the cleanup. Rest 100 projects we could archive

Yes, I agree.

> For now I feel all those projects that don’t display well on the TM and with nil contributions should be deleted. With a Jan snapshot I could spot 7 such projects.

Sounds reasonable. :+1: 

>  you can ‘trick’ the TM into thinking no mapping was done by using the unmark/reset tasks to ready state buttons in edit mode and then delete the project

I think we should make this impossible for project managers. Only admins should be able to delete projects that have had any activity (even if reset). On the other side, I'd be curious what happens through resetting, when mappers have spent time on it, etc. Will this be deleted or still hang around in the database?

> Here’ the list of existing projects with invalid geometry

What do we do with the others? The ones with invalid geometry but already happening has going on. Can we try to fix the AOI?

**Comment by ramyaragupathy** [comment]
Got to dig the project deletion behaviour further. Recording my observations:
1. Any project manager can delete a project irrespective of who the author is
2. If a project has contributions (tasks mapped or validated) then the deletion throws an error message.
3. Projects could be deleted by reseting task status to ready. Like @russdeffner mentioned this tricks the app by creating new entries in task history. Old entries in the table are preserved though.
Once reset is done, deletion gets through.
4. However even if all the tasks are reset to `READY` status, if there has been a chat discussion for the project then the deletion fails with the same `Contributions present` message.
5. When tasks are reset, number of tasks mapped and validated are updated in the projects table But the counter is not reset for bad imagery tasks.

I feel items 1,4 and 5 behaviour should be fine tuned:
>1. Any project manager can delete a project irrespective of who the author is

Either the deletion should be restricted to only admins or the project author. I'd recommend allowing just project authors to delete, so that there is no additional layer of communication with the admin to delete a project

> 4. However even if all the tasks are reset to `READY` status, if there has been a chat discussion for the project then the deletion fails with the same `Contributions present` message.

This fails due to a foreign key constraint:

```
CRITICAL in project_admin_api [/Users/ramyaragupathy/Github/tasking-manager/server/api/project_admin_api.py:312]:
Project GET - unhandled error: (psycopg2.IntegrityError) update or delete on table "projects" violates foreign key constraint "project_chat_project_id_fkey" on table "project_chat"
DETAIL:  Key (id)=(8) is still referenced from table "project_chat".
 [SQL: 'DELETE FROM projects WHERE projects.id = %(id)s'] [parameters: {'id': 8}]
```

Should `reset` be extended to cover all actions associated with a project rather than just task histories? This means we lose all conversations/knowledge sharing that happened within the TM platform

> 5. When tasks are reset, number of tasks mapped and validated are updated in the projects table But the counter is not reset for bad imagery tasks.

If tasks mapped & validated counts are set to zero on hard reset,  then the bad imagery counter should be set to nil as well. Because per current task status after the reset all images are in `READY` state and there is no point maintaining the counters at old value. Suppose after the reset, a task is marked for bad imagery, then the previous count get added as well leading to escalation in numbers.


On the previous question of fixing invalid geometries,
> What do we do with the others? The ones with invalid geometry but already happening has going on. Can we try to fix the AOI?

Agree that we should fix the AOI, but let's try that manually on a case by case basis to ensure none of the project history is affected.

_If you'd like to understand the entire DB level update, you can go through [this doc](https://paper.dropbox.com/doc/Project-creation-Deletion--AbgErOtvCJoEE3lkX4pJ9m84Ag-hwJUBDX0qFEqRMhancQQ5) where I have logged the table level changes for project creation/deletion and task splitting._

cc @xamanu @ethan-nelson @smit1678
