### ISSUE TITLE
Database (RDS) backups

### ISSUE THREAD

**Issue by arunasank** [hotosm/tasking-manager#1461]
We want to exercise more control over how we snapshot our RDS instances and store them. Per chat with several folks on @hotosm/tech we have decided the following regarding the snapshotting and backing up of our RDS databases:
• For every DB instance, we will configure AWS to store 10 nightly historical builds
• As part of the Circle CI CloudFormation deploy, a database snapshot will be made of the current DB state, before the deploy, and the snapshot from the previous deploy will be deleted.

cc/ @dakotabenjamin

**Comment by arunasank** [comment]
Assigning this to you @dakotabenjamin !

**Comment by xamanu** [comment]
As the headline talks about backups, I just wanted to comment here, that I think it would be good to have not only snapshots but indeed backups. As a good practice backups are stored at a different place (provider) and shall allow us to recover in case our main provider's infrastructure goes down (we never know).

**Comment by dakotabenjamin** [comment]
The CFN PR has changes that include 10 days of backups and pre-deployment backups.

@xamanu that is a good idea, we can keep this issue open to continue that convo

**Comment by xamanu** [comment]
The snapshot part has been resolved. So, let's make this issue about the backup (lowered priority and adjusted title).
