### ISSUE TITLE
Non-dev testing environment

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1476]
It would be good non-developers can test Pull Requests of the Tasking Manager. This requires to setup a test setup much easier.

First step has been done with the Docker Compose setup (#797 and related improvements on configuration #1419). Recent testing on Windows and Mac showed problems with the legacy Docker versions. But also the workflow has been extremely rough. That we ended up deploying on a VPS.

Let's use this issue to find a suitable solution for non-devs.

**Comment by JorgeMartinezG** [comment]
**Update:** Testing environment is set using docker via https://github.com/hotosm/tasking-manager/pull/1480. However, the project database migrations fail at the beginnning. It is necessary to re-create the container related to migrations. 

**TODO:** - One important thing to do is to improve testing execution via docker. A Makefile could be useful.
- Update documentation. What is docker, how to setup, override.
- Fix tests. Right now, 4 server tests are failing using docker setup. I consider that this should be moved to another issue

**Comment by xamanu** [comment]
Thanks @JorgeMartinezG.

Yes, a wrapper script, so Makefile, is a good way forward. Can you outline the proposed logics you want to include into it?

Please open another issue with the four failing tests. Most likely we have some experience in the team with some of the errors :-)

**Comment by JorgeMartinezG** [comment]
- make up: To start docker containers
- make down: to destroy all containers.
- make build: to recompile TM dockerfile. It is useful when a new module has been included.
- make test-client: to execute karma tests within TM docker container.
- make test-server: To execute python tests within TM docker instance.
- make tests: To run both client and server tests

**Comment by xamanu** [comment]
They seem to be strait forward :) what about doing some magic and include a `make` to test a specific PR?

Would it make sense to have a separation between building the frontend and the backend dependencies?

**Comment by JorgeMartinezG** [comment]
to test specific PR it will involve recompiling dockerfile using an specific branch read from cli. But yes, it is possible to include it.

Related to the separation between frontend and backend, IMO it would be necessary to split server and client in two Dockerfiles, which would correspond to two separate services which will communicaty each other using a docker-compose.

**Comment by xamanu** [comment]
I see most of the proposed Makefiles commands can be easily documented for developers and don't necessary need to live in a script. However if we want to make it easy for non-devs they make a lot of sense, but then I think the rebuild on a certain PR is bringing the real benefit.

What will be the direct benefit for separating frondend and backend into two Dockerfiles? (besides following the microservice approach).

**Comment by JorgeMartinezG** [comment]
The benefit will be avoiding re-installation of modules and libraries. For instance, if I include a library in the requirements.txt file, I do not need to rebuild the client.

**Comment by xamanu** [comment]
For your information, some [documentation for non-devs has been started here](https://docs.google.com/document/d/12Yjj9cpGAyYIQuJedULogVipcRWjelI_ynrqvqZtnaA/edit).

**Comment by xamanu** [comment]
The splitting of the two services we probably should address in another place, to not extend here too much :)

What about these commands? 

* `make up`: To start docker containers
* `make down`: to destroy all containers.
* `make build`: to recompile TM Dockerfile. It is useful when a new module has been included.
* `make build frontend`: to install node dependencies and build the frontend again
* `make build backend`: to install python dependencies again
* `make test-client`: to execute karma tests within TM docker container.
* `make test-server`: To execute python tests within TM docker instance.
* `make tests`: To run both client and server tests
* `make checkout PRNUMBER`: to checkout a certain pull request from the main repo and build everything again.

And we probably want to include the `gulp run` ideally in one command like `make up --dev` or `make watch` (?).
