### ISSUE TITLE
Failed to generate request token

### ISSUE THREAD

**Issue by uwaiszaki** [hotosm/tasking-manager#1479]
tasking manager is giving this error while trying to login.
![tmlocalsetup1](https://user-images.githubusercontent.com/32809190/55972811-d7b58b80-5ca1-11e9-957b-b53a9827ae72.png)

**Comment by uwaiszaki** [comment]
This error is coming before redirecting it to the osm authorization page with url http://localhost:5000/api/v1/auth/login?redirect_to=/

**Comment by xamanu** [comment]
It looks like your OAuth settings are not correct. Please check the [installation instructions](https://github.com/hotosm/tasking-manager#installation) and make sure followed these instructions:

> In order to configure the connection for logging into your local Tasking Manager go to `https://www.openstreetmap.org/user/<Your_OSM_UserName>/oauth_clients/new` and fill in the form:
>
><img width="300" alt="screen shot 2019-01-08 at 10 58 26 pm" src="https://user-images.githubusercontent.com/3166852/50847977-f81b3480-1398-11e9-9cfd-771f58efefb0.png">
>
> Afterwards copy the consumer key and secret from OpenStreetMap into your configuration file `tasking-manager.env`, and set the two variables: `TM_CONSUMER_KEY` and `TM_CONSUMER_SECRET`.

**Comment by uwaiszaki** [comment]
@xamanu I tried the instruction for local setup but it's not solving the issue. Using docker it's showing null after osm authorization page.

**Comment by xamanu** [comment]
@uwaiszaki I think your local setup is now working after supporting you in the chat. is this correct? Can you report what made the change? and eventually close the issue. Thanks.

**Comment by uwaiszaki** [comment]
@xamanu setting POSTGRES_ENDPOINT= localhost in config.py solved the issue.
I also assigned privileges to the TM user for all the tables in tasking-managar db.
