### ISSUE TITLE
Set up machine learning playground instance

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1488]
We want to have a playground instance for the user testing of machine learning implementations.

* [x] Define the name for the url `?.hotosm.org` (@smit1678 volunteered already :smiley:) 
* [ ] Start off with an empty database.
* [ ] Disable the `tm4ml` branch automatic deployment and use the branch `machine-learning` instead.

**Comment by xamanu** [comment]
Some brainstroming: tasks-assisted.hotosm.org

**Comment by gaoxm** [comment]
tasks-assisted.hotosm.org sounds good!

**Comment by smit1678** [comment]
> tasks-assisted.hotosm.org

Dig it. 👍

**Comment by xamanu** [comment]
@dakotabenjamin can you help us with the next steps, please?

**Comment by arunasank** [comment]
Set this up at https://tasks-assisted.hotosm.org. However, once you try to use OSM auth to grant access, there's an internal server error.

The environment variables are set. However, the `load_dotenv` command doesn't seem to work:

```
load_dotenv(os.path.join(os.path.dirname(__file__), os.path.pardir, 'tasking-manager.env'))
```

I tried adding some try and except statements around it to no avail.

Further, there's https://github.com/hotosm/tasking-manager/issues/1510 when I try to create this using an empty database.

Further there's also this issue:

**Comment by arunasank** [comment]
This has been set up at https://tasks-assisted.hotosm.org.

Please test there, and close this issue if all looks good! The code for this is the ML branch + the CFN branch and is at `machine-learning-cfn`

**Comment by arunasank** [comment]
@felix can we close this issue?

**Comment by xamanu** [comment]
Let's use this as a reminder to make sure the deployment is working, too.

**Comment by xamanu** [comment]
@arunasank and @dakotabenjamin can you confirm this to be working?

**Comment by arunasank** [comment]
Hey @dakotabenjamin can you replicate the CI on `develop`/`master` for tasks-assisted? This can be closed once we have that!

**Comment by arunasank** [comment]
We did this!
