### ISSUE TITLE
Write script wrapper for multiple commands execution

### ISSUE THREAD

**Issue by JorgeMartinezG** [hotosm/tasking-manager#1492]
To improve setup, shutdown,  Pull request review and test executions, docker comands should be wrapped into a Makefile.

**Comment by JorgeMartinezG** [comment]
Initial implementation of Makefile included in branch docker/1492-makefile using commit https://github.com/hotosm/tasking-manager/commit/5e7bb59264e1564080353a483bf65b89d0b313d2

**Comment by xamanu** [comment]
This has been tackled with #1498
