### ISSUE TITLE
Restrict project edit function to project author

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1504]
From https://github.com/hotosm/tasking-manager/issues/1470#issuecomment-485311160, at present we allow a project to be deleted by anyone who has a project manager role. Even if someone has not authored a project, they could edit/delete it, provided they have a project manager status. 

I feel this should be restricted to just one project manager who is the project author.

**Comment by russdeffner** [comment]
I would agree, as long as Admins could still edit/delete any project and that more than one project manager can be assigned. We often have a need in disaster response for a team to edit projects while original creator is sleeping/away

**Comment by xamanu** [comment]
Yes, in #1591 there is planned to have admins of the same organization that can edit the projects and special teams can be created that can be assigned with the project management role. 

In this issue here we will immediately fix that all project managers can edit and restrict it to the author.

**Comment by xamanu** [comment]
This has been part of release 3.3.2. Closing here. Thanks.
