### ISSUE TITLE
Node v6 end-of-life soon

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1511]
Per https://nodejs.org/en/about/releases/ Node v6 goes end-of-life on 4/30. We should look at the effect of upgrading to v8 or 10.

**Comment by xamanu** [comment]
In the [Dockerfile](https://github.com/hotosm/tasking-manager/blob/develop/devops/docker/tasking-manager/Dockerfile#L27) we are successfully using Node version 9 already. I remember that there were some minor issues with Node version 10, that is why I stepped back to use version 9.  Upgrading the version however needed an additional `	npm install closure-util --save` to work properly.

@arunasank On which Node version is the new Cloudformation stack running?

**Comment by ethan-nelson** [comment]
Since 9 is working fine with Docker, I'd say we just update the [README](https://github.com/hotosm/tasking-manager/blame/develop/README.md#L69) and call it solved!
