### ISSUE TITLE
Cannot Comment on Projects

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#1516]
Hello, this is a somewhat urgent problem. Currently no one can comment on the discussion / Q/C tab of projects. From @willemarcel - seems the frontend is not making the call to the API. Does not seem to affect the per-Task comments and maybe related to the read_only user fix recently deployed.

**Comment by xamanu** [comment]
We should probably escalate this related correction to become a hotfix and a minor release, so this can be fixed rapidly. What do you think @dakotabenjamin?

**Comment by dakotabenjamin** [comment]
Hotfix has been deployed.
