### ISSUE TITLE
Show user token on the user profile page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1521]
In order to use the API, a user needs to know his/her authorization token, it would be helpful to add it on the user profile page (only for the current logged in user).

**Comment by uwaiszaki** [comment]
@willemarcel Can we use local storage for session token?

**Comment by willemarcel** [comment]
@uwaiszaki I think it's ok, although I'm currently not the best person to answer this question.

It seems we have a `SessionToken`, which is already saved on the local storage and an `Authorization Token`, that can be seen when inspecting the network requests on the browser.

**Comment by xamanu** [comment]
Just connecting some things: This might be related to https://github.com/hotosm/tasking-manager/pull/1407 and https://github.com/hotosm/tasking-manager/pull/1037

**Comment by uwaiszaki** [comment]
@xamanu #1407 is using auth token to verify, generate and return new token.

**Comment by uwaiszaki** [comment]
@ethan-nelson can u please guide me.

**Comment by xamanu** [comment]
@willemarcel is this related to #202?

**Comment by willemarcel** [comment]
I couldn't understand what #202 is about...

I saw some related issues like #1197, but I didn't get why it was included on task annotation and which solution was implemented.

**Comment by willemarcel** [comment]
Besides exposing the token to the user, in the new React frontend implementation I didn't succeed to use the current Authentication view. One of the problems I noticed is that the authentication API uses flask sessions, that way the frontend needs to be served by the backend.

In my opinion, the backend and the frontend should be totally independent. The redirection of the user to the OSM website should be done by the frontend, not by the backend view.

My proposal is to rewrite the authentication view with https://requests-oauthlib.readthedocs.io/, so we can have an authentication API totally independent of the frontend.

**Comment by fitoria** [comment]
WIP: https://github.com/hotosm/tasking-manager/commits/feature/redesign-login

**Comment by willemarcel** [comment]
I created PR with @fitoria work + improvements: https://github.com/hotosm/tasking-manager/pull/1769

**Comment by willemarcel** [comment]
Fixed with #1913
