### ISSUE TITLE
Increase time interval of has-new-messages requests

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1524]
Currently the frontend makes a new request to `/api/v1/messages/has-new-messages` each 10 seconds.

Although it's a request that returns a tiny amount of data as response, I believe we don't need to fetch it so frequently and it would help reduce the load on the server. I suggest to increase the interval to 1 or 2 minutes.

Interval function is at https://github.com/hotosm/tasking-manager/blob/ab03f5092ac38bb323d7a3021fc816ca4c08ecf1/client/app/components/account-nav/account-nav.directive.js#L57

**Comment by uwaiszaki** [comment]
@willemarcel @xamanu I have created a pr. Please review it

**Comment by xamanu** [comment]
Thanks @uwaiszaki and @willemarcel. The PR went in. Closing here.
