### ISSUE TITLE
Notification Tab should reopen after new message is received

### ISSUE THREAD

**Issue by uwaiszaki** [hotosm/tasking-manager#1526]
Currently, notification tab for new messages is closed after 10 secs. It should reopen after the new message is received.

**Comment by uwaiszaki** [comment]
@xamanu I would like to work on this.

**Comment by xamanu** [comment]
I'm not so sure about this. Of course it could be nice. But as these are notifications, I would rather leave them to not distract the user too much.

**Comment by xamanu** [comment]
Closing here because of inactivity. Feel free to reopen.
