### ISSUE TITLE
Empty activity in dashboard

### ISSUE THREAD

**Issue by NicolasGrosjean** [hotosm/tasking-manager#1528]
Hello,

In a project I am currently working [the activity in the dashboard project](https://tasks.hotosm.org/project/5847/dashboard) is empty whereas I'm validating a lot of tasks.

![image](https://user-images.githubusercontent.com/13560473/56847694-aa422200-68de-11e9-91a1-543639d6d184.png)

**Comment by ramyaragupathy** [comment]
Related to https://github.com/hotosm/tasking-manager/issues/1522

**Comment by NicolasGrosjean** [comment]
Sorry I have not seen it has been already reported.

I closed this duplicate.
