### ISSUE TITLE
Include tasks counts in project API

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1530]
Right now we include the percent mapped and validated in the [get project API endpoint](https://github.com/hotosm/tasking-manager/blob/develop/server/api/project_apis.py#L13-L75) (the function ultimately called is here https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/project.py#L457-L504). It would be good to include not only the percentages but also the # of tasks marked mapped, invalidated, validated, bad imagery. Note this will require updated the [project DTO](https://github.com/hotosm/tasking-manager/blob/develop/server/models/dtos/project_dto.py#L74) to hold the data to be transmitted.

**Comment by theprover97** [comment]
@ethan-nelson can i work on this?

**Comment by ethan-nelson** [comment]
Sure! This could be added to both the project and the project summary APIs. The fields that would be useful are https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/project.py#L78-L80 specifically: `tasks_mapped`, `tasks_validated`, `tasks_bad_imagery`.

**Comment by ethan-nelson** [comment]
And also perhaps `total_tasks`--I didn't check whether that is in the summary or not.

**Comment by theprover97** [comment]
I have updated the tasks-count for total_tasks, tasks_mapped, tasks_validated, and tasks_bad_imagery in both the project and project summary, along with Project DTO and Project Summary. Could you please tell me how to test these changes in the respective API endpoint ?

**Comment by Nikitag0329IITkgp** [comment]
Hello, @ethan-nelson does this still require work or is it done?
