### ISSUE TITLE
Task Invalidation History breaks splitting

### ISSUE THREAD

**Issue by zlavergne** [hotosm/tasking-manager#1533]
Bug related to #1272 . I'm experiencing a bug caused by the foreign key between `task_invalidation_history` and `task_history`.

To reproduce:
1. invalidate a square
2. reselect square to `map`
3. attempt to split the square

I get the following error:
```
Task Split API - unhandled error: (psycopg2.IntegrityError) update or delete on table "task_history" violates foreign key constraint "fk_invalidation_history" on table "task_invalidation_history"
DETAIL:  Key (id)=(250) is still referenced from table "task_invalidation_history".
 [SQL: 'DELETE FROM task_history WHERE task_history.id = %(id)s'] [parameters: ({'id': 149}, {'id': 154}, {'id': 159}, {'id': 249}, {'id': 250}, {'id': 508})]
```

This could be fixed by adding something like:
`invalidation_history = db.relationship(TaskInvalidationHistory, lazy='dynamic', cascade='all')`
to TaskHistory. It's a very similar problem as #1506 which is fixed by #1508.

@nrotstan That solution will force deletion of "historical" validation data when splitting. Would that be alright?

**Comment by nrotstan** [comment]
Thanks for catching this, @zlavergne , I'll look into it.
