### ISSUE TITLE
Move to React for the frontend framework

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1541]
The Tasking Manager's frontend runs currently on the framework [AngularJS in version 1.7.8](https://angularjs.org/). Last year active development stopped for this framework and 2021 all support will be dropped. for the integration of maps, OpenLayers is used, which is limiting us in [several occasions](https://github.com/hotosm/tasking-manager/issues/577), and we probably want to switch to another library, too.

The [recent redesign work](https://github.com/hotosm/projects/issues?q=is%3Aissue+is%3Aopen+label%3A%22ML4TM+Design%22) will introduce fundamental changes to the interface and it is a good moment to evaluate, whether we want to move on an rely on a different frontend framework, while implementing these changes.

So far I heard in various conversations a tendency towards the [React](https://reactjs.org/) framework. But also a [newer version of Angular](https://angular.io/) or [Vue.JS](https://vuejs.org/) might be good candidates.

This issue is to start a conversation and collect people's opinions, investigate on the feasibility and organize ourselves to tackle this.

**Comment by willemarcel** [comment]
I believe the redesign work is the ideal opportunity to change the framework. My preference is using React.

**Comment by zlavergne** [comment]
I would love to switch away from OpenLayers!

@xamanu when do you think a framework switch would start happening? I'm curious how it might affect future feature porting

**Comment by xamanu** [comment]
@zlavergne I think we just want to start a conversation about this and I want to bring this up in our stakeholder meeting the day after tomorrow. We are considering such a move while implementing the redesign, we are currently going through it on detail, so we can estimate better. Of course we want to make sure such a step fits into everybody's need to maintain the TM.

**Comment by xamanu** [comment]
Over the last two weeks we have been planning the redesign work and talked with people involved. We are eager to push for a framework change to React with the work of the redesign. As for the timeline, are estimating to be get this done this summer.

With this change we are also moving on from OpenLayers to a new library, which is discussed in #577.

**Comment by willemarcel** [comment]
@xamanu I think the base of the React implementation is done, so we can close this issue
