### ISSUE TITLE
Issues in building Tasking-Manager on Ubuntu>18.04

### ISSUE THREAD

**Issue by theprover97** [hotosm/tasking-manager#1545]
The Tasking-Manager is still showing following errors when building it on Ubuntu > 18.04, even on the latest Ubuntu 19.04.

_Step 4/13 : RUN apt-get update   && apt-get upgrade -y   && apt-get install -y libgeos-dev   && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ---> Running in 6ad6ded9fbd3
Err:1 http://deb.debian.org/debian stretch InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://security.debian.org/debian-security stretch/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:3 http://deb.debian.org/debian stretch-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libgeos-dev
ERROR: Service 'migration' failed to build: The command '/bin/sh -c apt-get update   && apt-get upgrade -y   && apt-get install -y libgeos-dev   && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100

**Comment by xamanu** [comment]
This shall be solved and documented in #1345.

**Comment by xamanu** [comment]
@theprover97 Does it help to follow the steps of this [script for Ubuntu 18.04](https://github.com/hotosm/tasking-manager/blob/install-scripts/devops/scripts/install_on_ubuntu_18_04.sh)?

**Comment by theprover97** [comment]
Yes @xamanu , the steps of the script for Ubuntu 18.04 works fine in building Tasking-Manager on this setup. However, it still shows error on versions >18.04. But we may take into consideration that Ubuntu 18.04 is only the stable version currently, and higher versions are themselves under development.

**Comment by xamanu** [comment]
Yes, there also seems to be a problem with connecting to the internet. Looks more like a support request. Closing here. In case you need more help, please contact us in the chat. Thank you.
