### ISSUE TITLE
Tiles marked with "Bad Imagery" cannot be invalidated

### ISSUE THREAD

**Issue by Vaomatua** [hotosm/tasking-manager#1552]
Newbie editors often click the Bad Imagery button because it is the most obvious. When I try to invalidate the task I get an error and the tile cannot be unlocked. 
![image](https://user-images.githubusercontent.com/12214434/57327807-a5425700-70c4-11e9-93a8-5ae879f000fb.png)

**Comment by xamanu** [comment]
Thank you very much @Vaomatua for reporting!

@JorgeMartinezG created a fix and it will be installed on the main instance with the next release. We will report here, once it is live and let you confirm.

**Comment by Vaomatua** [comment]
@xamanu Thanks for the update, I couldn't find the error when searching or would have added the comment to #1556 
Thanks @JorgeMartinezG  for the work.

**Comment by Vaomatua** [comment]
Thanks to all who helped on this, I have confirmed this is resolved.
