### ISSUE TITLE
Improve API error messages

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1554]
We are exposing too much information about the database on some API error messages. For example, on the project creation endpoint:

`{"error": "Project PUT - unhandled error: (psycopg2.IntegrityError) null value in column \"id\" violates not-null constraint\nDETAIL:  Failing row contains (null, 2, 2019-05-08 10:31:29.690642, 2, en, 2477516, 1, f, f, f, null, null, null, null, null, 2019-05-08 10:31:29.674684, null, null, null, 56, 0, 0, 0, null, 0101000020E6100000DF264200250053404D4926DD9C053140, 0106000020E610000001000000010300000001000000050000004A2D4FDC87FF..., 0, {0,1,2,3}, {0,1,2,3}).\n [SQL: 'INSERT INTO projects (status, created, priority, default_locale, author_id, mapper_level, enforce_mapper_level, enforce_validator_role, private, entities_to_map, changeset_comment, due_date, imagery, josm_preset, last_updated, license_id, geometry, centroid, task_creation_mode, mapping_types, organisation_tag, campaign_tag, mapping_editors, validation_editors, total_tasks, tasks_mapped, tasks_validated, tasks_bad_imagery) VALUES (%(status)s, %(created)s, %(priority)s, %(default_locale)s, %(author_id)s, %(mapper_level)s, %(enforce_mapper_level)s, %(enforce_validator_role)s, %(private)s, %(entities_to_map)s, %(changeset_comment)s, %(due_date)s, %(imagery)s, %(josm_preset)s, %(last_updated)s, %(license_id)s, ST_SetSRID(ST_GeomFromGeoJSON(%(ST_GeomFromGeoJSON_1)s), %(ST_SetSRID_1)s), ST_Centroid(ST_SetSRID(ST_GeomFromGeoJSON(%(ST_GeomFromGeoJSON_1)s), %(ST_SetSRID_1)s)), %(task_creation_mode)s, %(mapping_types)s, %(organisation_tag)s, %(campaign_tag)s, %(mapping_editors)s, %(validation_editors)s, %(total_tasks)s, %(tasks_mapped)s, %(tasks_validated)s, %(tasks_bad_imagery)s) RETURNING projects.id'] [parameters: {'status': 2, 'created': datetime.datetime(2019, 5, 8, 10, 31, 29, 690642), 'priority': 2, 'default_locale': 'en', 'author_id': 2477516, 'mapper_level': 1, 'enforce_mapper_level': False, 'enforce_validator_role': False, 'private': False, 'entities_to_map': None, 'changeset_comment': None, 'due_date': None, 'imagery': None, 'josm_preset': None, 'last_updated': datetime.datetime(2019, 5, 8, 10, 31, 29, 674684), 'license_id': None, 'ST_GeomFromGeoJSON_1': '{\"type\": \"MultiPolygon\", \"coordinates\": [[[[75.9926672719204, 17.02263067831737], [76.00485522968407, 17.01335649592026], [76.01270873767967, 17.02501070412649], [75.9942551396572, 17.02800621082241], [75.9926672719204, 17.02263067831737]]]]}', 'ST_SetSRID_1': 4326, 'task_creation_mode': 0, 'mapping_types': None, 'organisation_tag': None, 'campaign_tag': None, 'mapping_editors': [0, 1, 2, 3], 'validation_editors': [0, 1, 2, 3], 'total_tasks': 56, 'tasks_mapped': 0, 'tasks_validated': 0, 'tasks_bad_imagery': 0}]"}`

We should return only: `null value in column "id" violates not-null constraint` or some other message informing that the request data had inconsistencies.

**Comment by ramyaragupathy** [comment]
From `/user/update-details`
```

{"error": "User GET - unhandled error: (psycopg2.IntegrityError) null value in column \"default_editor\" violates not-null constraint\nDETAIL:  Failing row contains (360183, wille, 1, 3, 6, 2, 0, {1,2}, wille.yyz@gmail.com, willemarcel, f, null, _willee, 2019-04-08 10:51:26.758678, 2019-07-23 13:47:19.31777, t, f, null, Salvador, Brazil, Wille, null, null, null, null, null, null, null).\n\n[SQL: UPDATE users SET facebook_id=%(facebook_id)s, default_editor=%(default_editor)s, mentions_notifications=%(mentions_notifications)s, comments_notifications=%(comments_notifications)s, projects_notifications=%(projects_notifications)s, expert_mode=%(expert_mode)s WHERE users.id = %(users_id)s]\n[parameters: {'facebook_id': 'willemarcel', 'default_editor': None, 'mentions_notifications': None, 'comments_notifications': None, 'projects_notifications': None, 'expert_mode': None, 'users_id': 360183}]\n(Background on this error at: http://sqlalche.me/e/gkpj)"} ```
