### ISSUE TITLE
Create a test dump file with postgres engine 9.5.15

### ISSUE THREAD

**Issue by arunasank** [hotosm/tasking-manager#1555]
Ref: https://github.com/hotosm/tasking-manager/issues/1549

* Regenerate https://github.com/hotosm/tasking-manager/blob/machine-learning/tests/database/tasking-manager.sql using postgres 9.5.15
* Update `tasking-manager-assisted` using the regenerated dump.

cc/ @xamanu @willemarcel @fitoria @JorgeMartinezG @dakotabenjamin @ramyaragupathy

**Comment by xamanu** [comment]
Can our deployment already create an instance with a fresh database? Or is it just easier to give it a dump to eat?

**Comment by arunasank** [comment]
> Can our deployment already create an instance with a fresh database? Or is it just easier to give it a dump to eat?

The `python manage.py db upgrade` has never worked for me when the database is empty, because the command does not install the postgis extension by default, which causes a lot of things to fail. 

Ref: https://github.com/hotosm/tasking-manager/issues/1510#issuecomment-490159542

**Comment by xamanu** [comment]
@arunasank, Is this still necessary? In #1549 it seems you reported the original issue to be fixed by upgrading to an updated postgres database.

**Comment by xamanu** [comment]
Here is a 9.6 based dump: [tm-psql-9-6.zip](https://github.com/hotosm/tasking-manager/files/3177016/tm-psql-9-6.zip)

**Comment by arunasank** [comment]
We can close here - since upgrading the overall database to postgres 11.x will fix this. Thanks for the dumps!
