### ISSUE TITLE
Discrepancy in time spent mapping value on user profile page

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1562]
Per chat w/ users on slack, `Time Spent Mapping` stats displayed on user profile page seems to be off from the actual value.

![image](https://user-images.githubusercontent.com/12103383/57466668-ba72dd80-729e-11e9-8dca-820c1a31b1fc.png)
 
**Issues reported:**

> Someone had said that when they reached 24 hours of mapping time, it switched to saying just "a day."  But after mapping a little longer, it now only says "an hour"

 > The "time spent mapping" always flips back to 1 hour. I've spent probably around 50 hours mapping Cyclone Idai tasks alone, yet my profile says "Time Spent Mapping: 2 hours"

Looking into this deeper

**Comment by xamanu** [comment]
Thanks, @ramyaragupathy.
