### ISSUE TITLE
Enforce Random Task Selection

### ISSUE THREAD

**Issue by zlavergne** [hotosm/tasking-manager#1583]
Internally, we have implemented a feature called **Enforce Random Task Selection**. 

Implementation:

* Optional setting to Enforce Random Task Selection
![image](https://user-images.githubusercontent.com/9849118/57863378-35fcef00-77b7-11e9-9b6f-5dce52c5797c.png)

* If Enforce Random Task Selection is enabled, users will not be able to manually select tasks. They will be required to use the "Select A Random Task" button (does not apply to pm/admins)
![image](https://user-images.githubusercontent.com/9849118/57863458-617fd980-77b7-11e9-8a96-e83023db0fd2.png)

* Errors appear if they try to select a task from the map
![image](https://user-images.githubusercontent.com/9849118/57863485-6c3a6e80-77b7-11e9-9c47-7231ea680c0f.png)

From a separate discussion, it sounds like for this to be valuable for HOT, the functionality of random selection needs to change to choose tasks in priority areas first. 

@xamanu @russdeffner That shouldn't be difficult to add but should I change the global functionality of "Select A Random Task" to  _always_ select tasks in priority areas or only when "Enforce Random Task Selection" is enabled?

**Comment by zlavergne** [comment]
@xamanu @russdeffner I mentioned during the last TMWG call that the current "Select A Random Task" feature is a regression from TM2 and since there isn't a need for the more robust feature internally, I'd like to port this over as is. I should have the PR ready next week

**Comment by xamanu** [comment]
> From a separate discussion, it sounds like for this to be valuable for HOT, the functionality of random selection needs to change to choose tasks in priority areas first.

This has been also mentioned in #955.
