### ISSUE TITLE
Hyperlink to contribute to translation in the README is broken

### ISSUE THREAD

**Issue by JohnoverBoard** [hotosm/tasking-manager#1587]
It seems the link to translate is landing on a 404 error page not found message. If someone can confirm if

https://github.com/hotosm/tasking-manager/blob/develop/docs/contributing-translation.md

is supposed to be the actual page, I can rectify the same. Thanks.

**Comment by JohnoverBoard** [comment]
I have submitted a PR for the same #1588

**Comment by xamanu** [comment]
Thanks @JohnoverBoard. I just merged it in.
