### ISSUE TITLE
Frontend for teams and organizations 

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1591]
Based on the models and related database changes, which #1531 is introducing, we want to implement one way of using teams and organizations that works for the main Tasking Manager (and HOT), while other organizations may alter this in their fork of TM, to adjust it to their internal work flows.

The following features and behaviours are envisioned to be developed:

* [ ] Allow users to apply for public teams, that are open to join. Admins of the associated organization must be notified and have the option to confirm or reject the inquiry.
* [ ] Allow users to leave a team. In addition project managers and admins of the associated organization should be able to remove users from teams.
* [x] General admins and admins of the associated organization should be able to edit teams and organizations. Including adding and removing users as admins to an organization. Only general admins can change the organization of an existing team.
* [ ] Allow to select teams for mapping, validation and project management on the side of projects.
* [ ] Develop migration path for existing tags into organizations (should also partially fix #943)

What do you think?

**Comment by xamanu** [comment]
In a chat with @uwaiszaki we were thinking to target this with the new framework #1541 within the redesign. What do you think @JorgeMartinezG and @willemarcel?

**Comment by willemarcel** [comment]
@xamanu I think it's the better decision

**Comment by xamanu** [comment]
We developed a [click-dummy for teams and organizations](https://projects.invisionapp.com/share/7PUM47HQ3H9#/screens).
