### ISSUE TITLE
Implement redesign style

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1596]
This is a top-level issue for the whole redesign work.

White-labeled: https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/351144626
Branded: https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/350140387

**Comment by xamanu** [comment]
We track things here: https://github.com/hotosm/tasking-manager/projects/3

**Comment by xamanu** [comment]
Marking this as solved. As the issues are in the project.
