### ISSUE TITLE
Create “My tasks” frontend page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1599]
Implement frontend view that show the tasks a user has touched as a mapper or as a validator.

Reference: https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/359643157 

Depends on https://github.com/hotosm/tasking-manager/issues/1597

**Comment by thadk** [comment]
We might want pagination on this API similar to messages, projects, etc.

**Comment by thadk** [comment]
Remember hover doesn't work on iPads and phones, but this only appears on hover: <img width="976" alt="image" src="https://user-images.githubusercontent.com/283343/71355709-e0a76e00-254d-11ea-8bbf-edd168f204f4.png">
