### ISSUE TITLE
Improve mapping statistics endpoint

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1600]
- [x] Extend the backend API to provide information as needed by the new homepage.
- [ ] Extend the backend API to provide information as needed by the new user profile page.

References:
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652190
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652191
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357890354

**Comment by willemarcel** [comment]
To the homepage we need the number of buildings and the length of roads (in km) mapped. 

That data is available at https://osm-stats-production-api.azurewebsites.net/stats/hotosm and it's used by Missing Maps website, but I don't know who maintains that service.

cc @smit1678 @xamanu

**Comment by ramyaragupathy** [comment]
We started with addressing performance issues on stats endpoint

**Comment by ramyaragupathy** [comment]
> but I don't know who maintains that service.

We're supporting the application now 😀

**Comment by ramyaragupathy** [comment]
@JorgeMartinezG  - Please refer to [osm-stats documentation](https://github.com/AmericanRedCross/osm-stats/blob/master/documentation/API.md) for user related stats.

**Comment by willemarcel** [comment]
@ramyaragupathy we are using https://osm-stats-production-api.azurewebsites.net/stats/hotosm right now to get the number of buildings and roads length. Let me know if you include that information in some endpoint, so I can change the frontend.

**Comment by ramyaragupathy** [comment]
> https://osm-stats-production-api.azurewebsites.net/stats/hotosm
This returns details for just one hashtag #hotosm. We should be looking at https://osm-stats-production-api.azurewebsites.net/reports/hot*

If the above link times out then, let's look at modifying existing endpoints

**Comment by xamanu** [comment]
Using a separate service makes it difficult for others to install their Tasking Manager, as they would not get good homepage statistics? How should we deal with that? Creating a new follow up issue?

**Comment by xamanu** [comment]
@willemarcel What is the status here? Thanks.

**Comment by willemarcel** [comment]
@xamanu It's missing the number of elements mapped by user (buildings, roads km, landuse, waterway). It's needed on that screen: https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652191

**Comment by xamanu** [comment]
ok, let's mark this as approved, and i created a new follow up issue: https://github.com/hotosm/tasking-manager/issues/2246
