### ISSUE TITLE
Filterable tables - server api

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1601]
There are a lot of new filterable tables for tasks, projects and notifications. Probably it makes sense to think about a generic way on how to produce filterable (and searchable?) tables.

This issue is about the implementation on how tables are generated on the TM server side and the way they are exposed to the frontend client through the internal API.

Coordinate with @nrotstan around their work and how this fits together.

References:
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/358164913
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357087237
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/358973357
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652194
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357651168

**Comment by xamanu** [comment]
@willemarcel @fitoria what is the status? Can this be considered as done?

**Comment by willemarcel** [comment]
It didn't go as we planned. We are using the common endpoints for each listing item view.
