### ISSUE TITLE
Add Favorites model

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1602]
Add database model to make possible to register a user favorite projects

Reference: https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652194

**Comment by JorgeMartinezG** [comment]
As initial model design, the following table should be created


Column | Type
-- | --
id | int
project_id (FK) | int
user_id (FK) | int

With this table model, is possible to apply the API view requirements, defined in https://github.com/hotosm/tasking-manager/issues/1603

I would like to know your feedback @xamanu @willemarcel

**Comment by willemarcel** [comment]
@JorgeMartinezG it seems good to me! I'd also set a `unique_for` rule in order to avoid a user to create multiples favorite entries for the same project
