### ISSUE TITLE
Add list of organizations endpoint

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1605]
We need a server API endpoint to provide a list of organizations that has projects on Tasking Manager. Probably we want being able to apply filters on it.

Related to https://github.com/hotosm/tasking-manager/issues/1531

**Comment by JorgeMartinezG** [comment]
@willemarcel @xamanu there is already and endpoint which lists the organizations from tags table. It was included here: https://github.com/hotosm/tasking-manager/commit/a6ba2153ffd48d540732235b9fbc454dcc4ffc49

`https://tasks.hotosm.org/api/v1/tags/campaigns`

**Comment by willemarcel** [comment]
Nice, @JorgeMartinezG ! The organisations endpoint is that https://tasks.hotosm.org/api/v1/tags/organisations

On #1531, there is already a proposal to migrate organisations to a new model, so I think we need to update that endpoint after the database change.

Filters could be by name (and maybe by `projects.campaigns`). It would be nice to have the number of projects of that organization as well, so we can ordering by number of projects on the frontend.

**Comment by xamanu** [comment]
This is part of PR https://github.com/hotosm/tasking-manager/pull/1858

**Comment by xamanu** [comment]
This has been merged. Closing here.
