### ISSUE TITLE
Add Campaign ManyToMany field to User model

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1606]
Add a ManyToMany relation to allow associate a user to campaigns.

**Comment by willemarcel** [comment]
@JorgeMartinezG There is a related issue: https://github.com/hotosm/tasking-manager/issues/1590

**Comment by xamanu** [comment]
Campaigns and users shouldn't have a direct connection. Campaigns are connected to projects, and users might take tasks of projects that are associated under some campaigns. I'm going to close here.
