### ISSUE TITLE
Add API views to associate / unassociate Campaigns with Users

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1607]
Add API view or modify user update details view (/api/v1/user/update-details) to make it possible to create relationship between users and campaign tags.

Depends on #1606.

**Comment by xamanu** [comment]
Campaigns and users shouldn't have a direct connection. Campaigns are connected to projects, and users might take tasks of projects that are associated under some campaigns. I'm going to close here.
