### ISSUE TITLE
Add more filter options to project search API view

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1616]
Allow to search projects created by or contributed by a user and by country.

**Comment by abalosc1** [comment]
It would also be nice to be able to filter on Percentage Mapped and Validated

**Comment by JorgeMartinezG** [comment]
To update this issue, search projects by username is here https://github.com/hotosm/tasking-manager/tree/feature/1616-project-search-filters. Missing countries implementation to complete this issue
