### ISSUE TITLE
Apply general frontend redesign

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1619]
The redesign changes a the look and feel of the website. Apply it to the whole TM interface.

Reference: https://projects.invisionapp.com/share/WTRWOQ6Y6RQ#/screens/362186631

**Comment by willemarcel** [comment]
Header, Footer and first section of the new frontpage are ready.

**Comment by willemarcel** [comment]
Some changes requested by @hexiaok :

- [ ] Add link to change user profile picture on osm website when hovering the profile picture on the welcome and settings views.
- [ ] Add border to editor dropdown on settings page
- [ ] Highlight the important fields that are missing to fill on settings/welcome views
- [ ] Use `react-select` on the explore projects filter section

Other changes I noticed:

- [ ] Add text about how we use the user data and email. Get text on https://github.com/hotosm/tasking-manager/pull/1855/files

**Comment by xamanu** [comment]
@willemarcel what is the status? Shall I open up follow up issues for one or another task?
