### ISSUE TITLE
Filterable tables - elements

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1629]
There are a lot of new filterable tables for tasks, projects and notifications. Probably it makes sense to think about a generic way on how to produce filterable (and searchable?) tables.

This issue is about the implementation of the frontend features such as the rendering of the table, and the filter elements.

Coordinate with @nrotstan around their work and how this fits together.

Design references:
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/358164913
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357087237
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/358973357
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652194
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357651168

Depends on https://github.com/hotosm/tasking-manager/issues/1601 and https://github.com/hotosm/tasking-manager/issues/1616

**Comment by xamanu** [comment]
@willemarcel what is the status here? is this solved and can be closed?

**Comment by thadk** [comment]
I think this work was in the end incorporated by other PR's as backend work.
