### ISSUE TITLE
Redesign the project page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1630]
Redesign the project page according to the design reference: https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/355947347

**Comment by thadk** [comment]
We will need `percentMapped` and `percentValidated` as part of the `/project/:id` endpoint. Like most of the project details, I think it could be available on both `abbreviated=true` and `abbreviated=false`

**Comment by thadk** [comment]
Favorites will need to be implemented with these not-yet-merged issues/PR https://github.com/hotosm/tasking-manager/issues/1603 #1602  https://github.com/hotosm/tasking-manager/pull/1660

**Comment by thadk** [comment]
Special needs for task map on project detail page:
[ ] Need to be able to turn off scrolling using mouse wheel
[ ] Need to be able to hide the task layer by a prop

**Comment by willemarcel** [comment]
@thadk I agree with the first 3 topics.

About the MapboxGL issue, I like the idea of componentizing it.

About the lazy loading, I don't like the idea. @xamanu asked us to depend as less as possible on external requests. As the bundle is loaded just one time, I don't see it as a problem.

**Comment by thadk** [comment]
@willemarcel Lazy loading is still using local bundles of the npm module on our server. The difference is the Mapbox code would only be loaded when people get to a page that has a map.
