### ISSUE TITLE
Improve static and informative pages

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1637]
Improve the FAQ and About pages. No content work, but allowing the proposed structure and behaviour of these pages.

Design reference: https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/358974980

Related to https://github.com/hotosm/tasking-manager/issues/1636

**Comment by xamanu** [comment]
In the new redesign some static pages need to be rewritten:

* Learn to map and learn to validate: https://projects.invisionapp.com/share/WTRWOQ6Y6RQ#/screens/362222475
* About: https://projects.invisionapp.com/share/WTRWOQ6Y6RQ#/screens/362688202
* Help: https://projects.invisionapp.com/share/WTRWOQ6Y6RQ#/screens/362688368
  * I am a new mapper
  * I am a new validator
  * I am a project manager
  * Other ways to get help

**Comment by xamanu** [comment]
We are having some first docs here:

* [About page](https://docs.google.com/document/d/1raUGj_BNw0UjsQexlie0LKduTaWfHM1U6sRqCsXLyNI/edit)
* [Learn page](https://docs.google.com/document/d/1FCN69EUvMDSbeXsSgZf3ky3gnobU2vXHL8vR-c3yHc8/edit)

**Comment by xamanu** [comment]
The docs reached the final state. Closing here.
