### ISSUE TITLE
Create "Explore projects" frontend page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1639]
List projects created, contributed or favorited by a user. Needs: filtering, ordering, pagination and map visualization.

Design references:
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652193
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652194

**Comment by thadk** [comment]
@willemarcel @xamanu Just noticed that `/api/v1/project/search` API does not yet support "Order By" field.

I also wondered if it was intentional to leave the Organisations field off of the "more Filters" page design for filtering projects? Was it intended to be a dropdown from the Organisations button at the top– a bit ambiguous? https://projects.invisionapp.com/share/WTRWOQ6Y6RQ#/screens/362686814

**Comment by thadk** [comment]
I noticed some organisation do not have any projects. Maybe we could distinguish these in the tags/organisations and hide these.
e.g. https://tasks-stage.hotosm.org/api/v1/project/search?mapperLevel=ALL&organisationTag=Abt+Associates
`{"Error": "No projects found"}`

**Comment by thadk** [comment]
After today's PR, these features are known to be still needed:
- [ ] Autocomplete and throttle on search box
- [ ] Remove "generic project" button, replace with "organization"
- [ ] Trial organisation and campaign main screen button as autocomplete <select>
- [ ] Fix `...` button on the paginator to do something useful.
- [ ] Mobile responsive – all buttons should move to more filters screen, "more filters" -> "filters".
- [ ] Show the API's GeoJSON for active projects with MapboxGL JS on a humanitarian basemap #577

**Comment by thadk** [comment]
The basic page uses 400kb compressed and it seems like the server really has to work for it.

If I was to make another API suggestion besides `order-by`, I'd say we could add a parameter to `/api/v1/project/search` to ask for `mapData=[no-map-data, GeoJSON, TopoJSON]` and use https://postgis.net/docs/AsTopoJSON.html

**Comment by xamanu** [comment]
This is part of TM4 and the issue can be closed.
