### ISSUE TITLE
Create contributions timeline component

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1642]
Create a github like user's timeline contributions.

Design reference:
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/356487950
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/356528406

Depends on https://github.com/hotosm/tasking-manager/issues/1615 and #1604

**Comment by thadk** [comment]
See https://github.com/hotosm/tasking-manager/issues/1641

**Comment by willemarcel** [comment]
Solved with https://github.com/hotosm/tasking-manager/pull/2263/
