### ISSUE TITLE
Create new notifications page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1644]
Create the new notifications page, according to the redesign specifications:

https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357890356
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357890354

**Comment by thadk** [comment]
#1928

**Comment by xamanu** [comment]
I just observed some issues on TM4 with this:

![image](https://user-images.githubusercontent.com/97706/72440716-4380d380-37a1-11ea-9754-69ad67e95588.png)


* One message was duplicated
* Instead of showing the username it shows some id
* Highlighting of names doesn't seem to work well, still.

**Comment by xamanu** [comment]
The page has been created. There are some bugs, created a follow up issue for that: https://github.com/hotosm/tasking-manager/issues/2247
