### ISSUE TITLE
Create the Welcome page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1645]
After a user has been logged in, the person shall be redirected to a welcome page, which includes invitation to fill out the parts of the profile that are missing and propose recommended projects to the user, based on the information we have been gathering.

Design references:

https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652189
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652195
https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652191

**Comment by willemarcel** [comment]
Finished with https://github.com/hotosm/tasking-manager/pull/1764

**Comment by willemarcel** [comment]
Defining what should happen when the user do the login on TM, in evaluation order:

1. If the user profile completion is under 50%, redirect it to a Welcome Page where they can fill it. 
2. If the user has not mapped a task yet, show the page with a "Map your first task" banner and recommended projects section
3. If the user has already mapped a task, I see two possibilities: show the my projects page or the stats and badges page.

Opinions, @xamanu @russdeffner ?

**Comment by ramyaragupathy** [comment]
> 1. If the user profile completion is under 50%, redirect it to a Welcome Page where they can fill it.

What parameters do you consider for completeness ? - email, fb id, twitter id, interest areas, anything else?

> 2\. If the user has not mapped a task yet, show the page with a "Map your first task" banner and recommended projects section

Sounds good

> 3\. If the user has already mapped a task, I see two possibilities: show the my projects page or the stats and badges page.

My projects page with recommendations for further mapping

**Comment by willemarcel** [comment]
@ramyaragupathy

**Comment by xamanu** [comment]
Sounds like a good plan. In addition it would be nice to check here if email has not been set and encourage users to do so.

If a user has already a mapped task, i think showing my projects and project recommendations would be good.

**Comment by russdeffner** [comment]
I agree, my projects - this will quicken the time from log-in to map that many experienced mappers want.

**Comment by willemarcel** [comment]
I added the routing logic after login. It's missing only to add the interests selection component to finish this issue.

**Comment by willemarcel** [comment]
Closing this. The missing details are registered on https://github.com/hotosm/tasking-manager/issues/1936
