### ISSUE TITLE
Tooltip in Messages - Inbox show extra text '| translate'

### ISSUE THREAD

**Issue by wireguy** [hotosm/tasking-manager#1654]
Hover mouse over an item in the inbox to get the tooltip popup and notice the text has the extra words  | translate.   Also, should the tooltip text be  'quoted'

![image](https://user-images.githubusercontent.com/47227325/58632772-a5dda000-82b4-11e9-88a9-48c0cba6f3bd.png)

**Comment by xamanu** [comment]
The information used in the `title` attribute of the `td` element is used to generate the title, but a tooltip should probably not be appearing. Other tables in the tm usually do headers through the `tr` explicitly. @nrotstan, what do you suggest to address this?

**Comment by xamanu** [comment]
Not an issue anymore with the new frontend of TM4.
