### ISSUE TITLE
Offset when selecting task by clicking on map

### ISSUE THREAD

**Issue by sidneygijzen** [hotosm/tasking-manager#1662]
Hello,

Since about 2 weeks there seems to be a random offset in play when selecting a task by clicking on the map. The screenshot below shows that I clicked where the mouse pointer is visible, but it selected the task north of my pointer.

The offset on selecting a task seems random: sometimes it selects a task to the north, sometimes to the east, etc. I tried to deduce a pattern in this behaviour, but wasn't to do so so far. I noticed though that the offset seems to decrease when zooming in. By zooming in I mean: only 3-4 tasks visible in the viewport.

The used browser is Firefox 67.0 on Kubuntu 18.04. I also did a quick test on Google Chrome (v74), and that appears to work correctly.

![hotosm-tm-task-selection-map](https://user-images.githubusercontent.com/6213045/58759181-5e098380-8515-11e9-9c41-a6b7164ea0d8.png)

**Comment by xamanu** [comment]
Hi, thanks for reporting! I just checked with my local computer FF 60.6.3esr (64-bit) on Debian Buster and it works fine, too. I'd recommend you to use Chrome for now and hopefully with the next release of the Firefox it will be fixed again.

I'm giving this a low priority for now. In case there are more people having similar problems, we can escalate this up to a higher priority.

**Comment by sidneygijzen** [comment]
Thanks for your reply. I understand.

Fingers crossed that the problem disappears with Firefox 68 :-)
