### ISSUE TITLE
Review oauth permissions

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1671]
Currently the Tasking Manager encourages to use the permission `modify their user preferences` for connecting with OpenStreetMap.org it needs to be reviewed whether `read their user preferences` should be enough.

**Comment by qeef** [comment]
It was definitely enough in the last releases.

**Comment by xamanu** [comment]
There hasn't been any changes to this version. Let's check and change the readme file and the setup accordingly.

**Comment by qeef** [comment]
Well, when checking my OAuth settings on osm.org, I am sure the change came when name of application changed from *Tasking Manager 3 - Prod* to *Tasking Manager CFN Prod*.

**Comment by xamanu** [comment]
Thanks @qeef for noticing. With the last release we changed our server setup and with this we moved the oauth application. While doing this we followed the documentation (readme.md).

Just checked and all works well with less permissions. We will change this as soon as possible (latest tomorrow).

**Comment by xamanu** [comment]
@qeef We fixed this on the live [HOT Tasking Manager](https://tasks.hotosm.org) and adjusted the documentation accordingly in this PR #1674.

A quick confirmation from your side would be nice. Thanks!

**Comment by qeef** [comment]
I can confirm, only *read your user preferences* are needed now.
