### ISSUE TITLE
Check translations

### ISSUE THREAD

**Issue by wireguy** [hotosm/tasking-manager#1678]
These strings are in the code (inbox.html), but not in any json file:

Task
Type
Sent
State
Project
No messages
Delete selected messages
Are you sure you want to delete these messages? This cannot be undone
Delete Selected
Delete All Selected Messages

**Comment by xamanu** [comment]
I would like to use this issue to generally document a bit our translation, making sure everything is up-to-date (including #1351) - i changed title to make it more general. hope this is ok.

**Comment by wireguy** [comment]
@xamanu 
You may want to investigate strings that are message fragments, example: "and help improve it." .
Fragments can cause incorrect translations.

another example:
{{ 'A new project will be created with' | translate }} {{ createProjectCtrl.numberOfTasks }} {{ 'tasks.' | translate }}

maybe make %1% be a replaceable parameter in the string
{{ 'A new project will be created with %1% tasks.' | translate }} {{ createProjectCtrl.numberOfTasks }}

**Comment by xamanu** [comment]
Checked translations and pipeline and improved the workflow and the documentation within #1706, which will close this issue here.

As a follow up we should check on @wireguy's suggestions during the redesign work. For this i created another issue: #1714.
