### ISSUE TITLE
dead link - license/6

### ISSUE THREAD

**Issue by don-vip** [hotosm/tasking-manager#1683]
The following link is dead:
https://tasks.hotosm.org/license/6
It is used in imagery entries used by JOSM.

**Comment by xamanu** [comment]
Do you remember which project you had this problem? Thanks.

**Comment by don-vip** [comment]
Sure, it's https://josm.openstreetmap.de/wiki/Maps/Palestine
https://wiki.openstreetmap.org/wiki/2014_Gaza_Strip

**Comment by don-vip** [comment]
OK I found out the new link: https://tasks.hotosm.org/api/v1/license/6
