### ISSUE TITLE
Favorites API: List projects favorited for the signed in user

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1686]
From #1602 #1603 - we should include an endpoint to retrieve all projects favorited by a user

**Comment by xamanu** [comment]
@JorgeMartinezG Can you point to the PR that needs review on that?

**Comment by xamanu** [comment]
I think it is this one: https://github.com/hotosm/tasking-manager/pull/1660
Is there anything more to do here. Or can this issue be closed?

**Comment by JorgeMartinezG** [comment]
@xamanu No. It is ready to be closed
