### ISSUE TITLE
Improve logging of instances

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1693]
The recent problems on the HOT Tasking Manager's live instance (#1687) required debugging on the main server. Switching on the database logging led to follow up problems of the instance running full in a short time.

Lets tackle this properly and make sure we have a reasonable and documented way of accessing the most important logs on our deployments.

* tasking manager logs
* database transactions logs
* http (web server) logs 

Probably we have to find a suitable time span for each of them to collect and throw away. And lets make sure we document this properly for the team.

**Comment by dakotabenjamin** [comment]
DB Logs: 
- reenable cloudwatch logging for the RDS resource (i.e. #1688)

TM3/server Logs: 
- in the AMI work (https://github.com/hotosm/tasking-manager/pull/1546) we can install and  configure the CloudWatch Agent to pull logs into CloudWatch Logs

**Comment by dakotabenjamin** [comment]
Aside about RDS Disk space with transaction logs. It appears that the massive disk storage is a temporary offloading of transaction logs before being uploaded to s3. Having sufficient space to handle that action will prevent disk full errors, but we don't really have a way of knowing beforehand.

**Comment by dakotabenjamin** [comment]
Once the packer/AMI work is done we can tackle this
