### ISSUE TITLE
HOT's Tasking Manager deployment branches

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1694]
Currently we are deploying the main [HOT Tasking Manager](https://tasks.hotosm.org) from the `master` branch. However this complicates the processes when finding urgent solutions for errors occurring on the main instance (like #1687), it is relatively slow to test out some quick fixes and also it doesn't look nice in our commit history of the product Tasking Manager.

Therefore we should change our deployment to be based on the branch: `deployment/hot-tasking-manager`

And in addition I suggest to apply also consistent naming for the other deployment branches:

* `deployment/teachosm-tasking-manager` instead of `teachosm`
* `deployment/assisted-tasking-manager` instead of `machine-learning`

**Comment by xamanu** [comment]
I prepared the branches:

* `deployment/hot-tasking-manager`
* `deployment/teachosm-tasking-manager`. 
* `deployment/assisted-tasking-manager`.

**Comment by dakotabenjamin** [comment]
When ready to implement, we need to change the branch filter values in the circleci config: 
https://github.com/hotosm/tasking-manager/blob/develop/.circleci/config.yml#L221
https://github.com/hotosm/tasking-manager/blob/develop/.circleci/config.yml#L248
https://github.com/hotosm/tasking-manager/blob/develop/.circleci/config.yml#L275
https://github.com/hotosm/tasking-manager/blob/develop/.circleci/config.yml#L302

**Comment by xamanu** [comment]
Ready to take off.

**Comment by xamanu** [comment]
This has been deployed on `deployment/hot-tasking-manager. Reoping this for the other branches. Just to now forget.
