### ISSUE TITLE
Add publiccode.yml

### ISSUE THREAD

**Issue by nemobis** [hotosm/tasking-manager#1702]
Would you be interested in a patch to add a metadata file like https://github.com/globaleaks/GlobaLeaks/blob/master/publiccode.yml ? It's necessary to be included in https://developers.italia.it/en/software/ , the list of free software which the Italian state will heavily advertise to the public sector in Italy.

**Comment by ethan-nelson** [comment]
Presto!

**Comment by xamanu** [comment]
This is a nice way of promoting Free Software. Thanks @nemobis for bringing this up! I had a look at it, and unfortunately it seems not to be any standard, but a very particular national regulation of Italy. So far I'm missing a bit the perspective on how this could help the Tasking Manager, as I'm not aware of any collaboration with public institutions in Italy that would require or ease up the use of this extra file.

As soon as this is getting used more widely and hopefully promoted to an international standard we should bring this in.
