### ISSUE TITLE
Validation locking issues

### ISSUE THREAD

**Issue by Vaomatua** [hotosm/tasking-manager#1712]
![image](https://user-images.githubusercontent.com/12214434/59854252-693b1c80-9327-11e9-810d-90182ffb5817.png)

I have validated several tiles this morning, but am not able to lock a tile for validation now.

**Comment by xamanu** [comment]
Hi @Vaomatua, we were facing some resources scarcity on the database connection on Friday and increased them the same day. Just checked and was able to lock for validation. May you please test, whether it work now for you, too? Thanks.

**Comment by Vaomatua** [comment]
@xamanu Thank you for the reply, I did check later on Friday and was able to work as expected. Thank you for all the backend work, I know it is a thankless task, and I appreciate all the work this team does.  Thanks
