### ISSUE TITLE
Project ownership

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1715]
In some rare cases it can be observed that the owner of a project is not the one that created this. 

For example:

* https://tasks.hotosm.org/project/6167
* https://tasks.hotosm.org/project/6176
* https://tasks.hotosm.org/project/6202
* https://tasks.hotosm.org/project/6290
* https://tasks.hotosm.org/project/6381
* https://tasks.hotosm.org/project/6480
* https://tasks.hotosm.org/project/6497
* https://tasks.hotosm.org/project/6498
* https://tasks.hotosm.org/project/6539
* https://tasks.hotosm.org/project/6680
* https://tasks.hotosm.org/project/7027
* https://tasks.hotosm.org/project/7030
* https://tasks.hotosm.org/project/7143
* https://tasks.hotosm.org/project/7147
* https://tasks.hotosm.org/project/7183

**Comment by xamanu** [comment]
We investigated in the database logs that the wrongly used owner is the subject of the query before creating the project:

* Some task activity: `2019-06-19 04:09:48 UTC:172.31.71.2(56460):taskingmanager@tm:[3615]:LOG: statement: INSERT INTO task_history (project_id, task_id, action, action_text, action_date, user_id) VALUES (6128, 6, 'STATE_CHANGE', 'VALIDATED', '2019-06-19T04:09:48.649496'::timestamp, 1004928) RETURNING task_history.id` 
* Right afterwards the project creation `2019-06-19 04:09:50 UTC:172.31.71.2(55114):taskingmanager@tm:[11189]:LOG: statement: INSERT INTO projects (status, created, priority, default_locale, author_id, mapper_level, enforce_mapper_level, enforce_validator_role, allow_non_beginners, private, entities_to_map, changeset_comment, due_date, imagery, josm_preset, last_updated, license_id, geometry, centroid, task_creation_mode, mapping_types, organisation_tag, campaign_tag, mapping_editors, validation_editors, total_tasks, tasks_mapped, tasks_validated, tasks_bad_imagery) VALUES (2, '2019-06-19T04:09:50.689893'::timestamp, 2, 'en', 1004928, 1, false, false, false, false, NULL, NULL, NULL, NULL, NULL, '2019-06-19T04:09:50.598505'::timestamp, NULL, ST_SetSRID(...`

**Comment by clairedelune** [comment]
I'm facing the same issue with this project that I had created and cannot edit anymore: https://tasks-assisted.hotosm.org/project/56

**Comment by russdeffner** [comment]
I would not call this rare anymore, seems like every couple days we get a report of this happening and potentially a lot more are happening but the project creator (and random person receiving the project) do not notice as there's no indication as was witnessed during the live demo at the HOT Summit.

Fixing 6758 - is assigned to https://tasks.hotosm.org/user/Isaim but originally created by https://tasks.hotosm.org/user/koos%20krijnders 

Sorry @clairedelune - I'm not an Admin on Tasks-Assisted, so can't transfer for you there.

**Comment by xamanu** [comment]
Raised priority here.

**Comment by xamanu** [comment]
Happened again: https://github.com/hotosm/tasking-manager/issues/1715
I reverted the ownership.

**Comment by xamanu** [comment]
After the latest commit this hasn't happened anymore. Closing the issue here, in case this appears again, feel free to reopen. Thank yoU!
