### ISSUE TITLE
Project search by number is not consistent

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1723]
While searching for projects by a specific number, there are certaincases where the results are not returned. This behavior seems random though

> entering '6179' into the search box delivers no match - searching for 'chad' delivers project 6179 as the second match

![project_search](https://user-images.githubusercontent.com/12103383/60172095-973dc680-9829-11e9-9940-996c253ddc78.gif)

**Comment by JorgeMartinezG** [comment]
**Update:** Looking at the problem, `project_info` table has a text_searchable column which is a tsvector, that indexes short_description and description columns. Some projects have empty values for this column. I will continue in this issue
