### ISSUE TITLE
Transfer to non Project Manager user

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#1725]
Currently you can Transfer a project to a user who does not have the Project Manager role. However, it only gives them the Edit Project button, but when clicked, kicks out to homepage. Ideally it would warn or not allow the project manager attempting to send a project to a non-pm user. There is also no indication to the user receiving the project, so they would have to know or see the Edit Project button to know and needs an admin to 'send it back'.

**Comment by xamanu** [comment]
@fitoria provided a PR for this issue: https://github.com/hotosm/tasking-manager/pull/1733
