### ISSUE TITLE
Access from Hong-Kong is blocked by Amazon

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/tasking-manager#1740]
email message on HOT mailing list with screenshot - planning to do a mapathon in less than 2 hours and getting a screen message

![image001](https://user-images.githubusercontent.com/6763965/60590092-0029bf00-9d93-11e9-846e-19d1819c54fc.png)

**Comment by Nick-Tallguy** [comment]
Problem seems to be because location is Hong Kong

**Comment by eternaltyro** [comment]
@Nick-Tallguy Can you verify if problem persists?

**Comment by dakotabenjamin** [comment]
Thanks for posting this- The email was sent 21 June during which we were undergoing maintenance. This has since been resolved, and the user has been notified on slack. If issues still persist, please feel free to reopen.

**Comment by Nick-Tallguy** [comment]
Thanks for that. Strange that the email appeared today!

Nick
my phone is responsible for any spelling mistakes!
