### ISSUE TITLE
Add due date field to Project model

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1767]
Add a date field to register the date when the organization or project manager needs the project mapping to be finished.

Required by #1628

**Comment by ramyaragupathy** [comment]
@willemarcel - Due date is [already available](https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/project.py#L68) in our existing model. Think this should suffice for `countdown` in project card

**Comment by willemarcel** [comment]
@ramyaragupathy thanks for the information. Closing it!
