### ISSUE TITLE
Project save fails with new release

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1772]
<img width="600" alt="Capture" src="https://user-images.githubusercontent.com/12103383/61576049-389afe00-aaf2-11e9-8872-d5292cc9a6eb.PNG">

Project save function fails with `{'enforceRandomTaskSelection': ConversionError(\"This field is required.\")}` error message.

**How to reproduce?**
- Choose any of the existing project created prior to this release
- Click edit project
- Now just try saving, you should get the error message

**What's the cause?**
- There's a new field `enforce_random_task_selection` in the projects table
- By default during migration all these values are populated to null on DB 
- Project DTO has the field requirement set to True, which means the application expects a non-null value during data transfer.
- However, all the existing projects have this field value set to null. So while saving this  throws an error

**Solution**
- Add a server default value in migration file
- And set the project DTO requirment to false

**Comment by xamanu** [comment]
Thanks for the fast fix, @ramyaragupathy! Created a hotfix release for it [v3.4.1.](https://github.com/hotosm/tasking-manager/releases/tag/v3.4.1).
