### ISSUE TITLE
Problems about V3 of HOT's Tasking manager-Invalid project

### ISSUE THREAD

**Issue by saliousoft** [hotosm/tasking-manager#1775]
Hi dev team,
I have some issues about the V3 of HOT Tasking manager.
In fact, It's Impossible to load some projects like project 813. Since yesterday and today, i have tried unsuccessfully. Please take a look. Thanks you very much.
Kindest regards.
Saliou

**Comment by xamanu** [comment]
This seems to have incredibly complex project boundaries. Maybe this is why it isn't loading. I can see it on my side, but I have to wait longer until it appears. @saliousoft can you let us know about other projects (and their id number) which you aren't able to open?

Many thanks
