### ISSUE TITLE
Map zoom too high when accessing a specific project task by URL

### ISSUE THREAD

**Issue by augustindo** [hotosm/tasking-manager#1776]
For few weeks, the way to display a task on the map (when accessing directly from URL) changed.

When you try to access a task by URL, it seems that the task is correctly selected and the map correctly centered but the zoom level seems setted to max value. One can expect that the map extent would correspond to the selected task extent.

**Example**
If you access this URL (project 813, task 716): https://tasks.hotosm.org/project/813?task=716#bottom , you get

![image](https://user-images.githubusercontent.com/20402274/61589680-db648280-abad-11e9-96b2-09836aa2ac52.png)

and the user could think that something goes wrong (blank map)...

but if you zoom out enough you get

![image](https://user-images.githubusercontent.com/20402274/61589718-82e1b500-abae-11e9-8da2-96697e6fa668.png)

Another example here: https://tasks.hotosm.org/project/5968?task=1247#bottom

In [#BaseRoadsVsOpenData](https://wiki.openstreetmap.org/wiki/Consolidated_mapping_projects_-_base_roads_check_vs_open_data_references) spectific projects, this behaviour change is very troublesome because we use these TM tasks URL to load tasks from a prioritization uMap like this one: http://u.osmfr.org/m/232379/

**Comment by xamanu** [comment]
Thanks for reporting @augustindo. We are going to work on a fix for that.

**Comment by xamanu** [comment]
This has been addressed by @zlavergne - many thanks - and will be part of the next hotfix release.
