### ISSUE TITLE
Update backend dependencies

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1779]
The backend dependencies are getting old. Lets try to update as much as we can. I started a [branch](https://github.com/hotosm/tasking-manager/tree/feature/update-backend-dependencies) with an updated `requirements.txt` but with some errors. And lets make sure we don't include any packages we actually don't use anymore.

**Comment by eternaltyro** [comment]
Flask-Oauthlib is no longer maintained. https://github.com/lepture/flask-oauthlib/issues/391

**Comment by JorgeMartinezG** [comment]
I have updated the branch. However when updating some modules got the following warnings:

**SQLAlchemy==1.3.6**
 SAWarning: The GenericFunction 'st_geomfromgeojson' is already registered and is going to 

The `SQLALCHEMY_POOL_SIZE` config option is deprecated and will be removed in v3.0.  Use `SQLALCHEMY_ENGINE_OPTIONS['pool_size']` instead.

The `SQLALCHEMY_MAX_OVERFLOW` config option is deprecated and will be removed in v3.0.  Use `SQLALCHEMY_ENGINE_OPTIONS['max_overflow']` instead.

**schematics==2.1.0**
SchematicsDeprecationWarning: Call to deprecated function _validator_functions.
  atom.name in schema._validator_functions

**Comment by willemarcel** [comment]
https://pyup.io/ is a good tool to keep dependencies updated
