### ISSUE TITLE
Review backend API

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1780]
Lets go over the existing API and consolidate and clean up things for version 4 of the TM.

**Comment by ramyaragupathy** [comment]
Per chat listing a few items for me to work on:

- [ ] Improve performance:  Profiling space & time complexity 
- [ ] Verify Data units (metrics -area, count): Make sure the data from different endpoints return numbers in the right units. Example, [area measurement](https://github.com/hotosm/tasking-manager/issues/1766 ) is expected in sq.kms, but the endpoint returns data in a different unit
- [ ] Review backend API endpoints
    - [Check error messages](https://github.com/hotosm/tasking-manager/issues/1554): Review the existing log messages to ensure that we  provide human-readable message and don't reveal too much information from the underlying data
    - Audit access and restrictions to API endpoints: Review and confirm the accessibility and availability of information with the right level of authorization
    - Testing API endpoints (integration and unit tests): Understand the most used and the problematic endpoints to improve our tests coverage in CI

**Comment by xamanu** [comment]
We have a [working document of the envisioned API v2](https://docs.google.com/spreadsheets/d/1aiR07_Irdf_cLaSEf3iO84iVkAdYaSxDR9J2FeWvGBA/edit#gid=0), please check and give feedback here or directly commenting in the doc. Thanks.

**Comment by hunt3ri** [comment]
Hi @xamanu @ramyaragupathy as part of the API refresh have you though about upgrading to Flask 1.1 and throwing away FlaskRestful.  Flask 1.1 has a few nice improvements and I don't think FlaskRestful is really maintained any more.  I think it would be possible to do gradually.  Let me know what you think?

**Comment by xamanu** [comment]
I put all open points of this into the follow up issue #1930 and close here as the relevant first important step has been successfully realized.
