### ISSUE TITLE
Allow trailing backslashes in routes

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1797]
Taking this comment from @eternaltyro in https://github.com/hotosm/tasking-manager/pull/1742#issuecomment-515911059

> This is a flask idiosyncrasy. Quoting flask documentation:
> 
>>  An important detail to keep in mind is how Flask deals with trailing slashes. The idea is to keep each URL unique so the following rules apply:
>>  
>> If a rule ends with a slash and is requested without a slash by the user, the user is automatically redirected to the same page with a trailing slash attached.
>> 
>> If a rule does not end with a trailing slash and the user requests the page with a trailing slash, a 404 not found is raised.
>>
> I think we should make trailing slashes to be seamlessly redirected to path without trailing slashes. It is general convention to do so.

**Comment by willemarcel** [comment]
Issue solved, thanks, @ramyaragupathy !
