### ISSUE TITLE
Create API endpoint to register new users by email

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1801]
In the new frontend we need to provide the possibility to the user to register an account on Tasking Manager before creating an account on OSM.

The information we want to register about the user is the email and name, so let's add an endpoint to receive that information. 

I don't know how to deal with the user_id as we use the OSM uid on the User model. If it's complicated to deal with it, we could create another model to those temporary users.

The user will not have a password or permissions to execute actions, we only collect his email to give a follow up if they didn't return after redirected to the OSM website.

**Comment by JorgeMartinezG** [comment]
@willemarcel I'm agree with using a separate model. Also, we would need to check if the username is already registered in OSM. A possible solution is to include a checker within the new endpoint that validates from osm api

**Comment by JorgeMartinezG** [comment]
To update my previous comment, looks like OSM cannot expose users email addresses through the API due to privacy policies https://wiki.osmfoundation.org/wiki/Privacy_Policy#Email_Addresses. I still consider important to use a separate model.

**Comment by JorgeMartinezG** [comment]
@willemarcel do you think that we would need the whole CRUD? Or just insert rows in the table?

**Comment by willemarcel** [comment]
@JorgeMartinezG I think the API needs only a POST method to insert the row in the table. Once the user creates his/her OSM account and the user model is effectively created, the backend should update the entry on that other database with the information that an account is already associated with this email. Do you think it's ok?

**Comment by JorgeMartinezG** [comment]
Yes, I agree. I think the following steps should be:
1. Users registers in TM without OSM account. (Table insertion in the not_osm_users table)
2. User registers in OSM.
3. User goes to TM and signs in. There will be an insertion in _users_ table. Then, we would check if that e-mail is in _not_osm_users_ table. If yes, then, we delete the row..

**Comment by xamanu** [comment]
This is related to #1186
