### ISSUE TITLE
Zone with a weird shape shows in the map

### ISSUE THREAD

**Issue by dkocich** [hotosm/tasking-manager#1806]
I used "random validation" button to select a zone to validate (https://tasks.hotosm.org/project/6300?task=493#bottom  appeared). It shows to me as a line (not square) in map copying borders of other area. Is it a datagrid issue or frontend problem?

![image](https://user-images.githubusercontent.com/6165660/62153134-39a70900-b304-11e9-82cf-5a212372be41.png)

**Comment by ramyaragupathy** [comment]
Maybe this is related to area trim function while creating a project

**Comment by willemarcel** [comment]
It doesn't apply to TM4
