### ISSUE TITLE
Sorting Contributors by Level Error

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#1809]
Hi all, it's very handy to be able to sort the contributors by level on the validation tab. At some point recently, this broke a little bit. It used to sort Beginner, Intermediate, Advanced then click again and it would sort Advanced, Intermediate, Beginner. Now it seems to 'group' rather than sort as I click sort by level and get Advanced, Beginner, Intermediate; click again and get Intermediate, Beginner, Advanced. But the reason we discovered this was because it's often nice to 'surface' all the beginner mappers to the top, which is no longer possible. However, instead of going back to just regular sort function - it might actually be nice to be able to 'cycle' the 3 levels - i.e. click 'sort' once it gives: beginner, intermediate, advanced; twice: intermediate, advanced, beginner and thrice: advanced, beginner, intermediate; so we could 'surface' any of the 3 levels. 

Bug found by Ralph Aytoun, verified and reported by me.

**Comment by russdeffner** [comment]
@ramyaragupathy - I think this screen capture will help clarify where this is I am talking about
![LevelSort](https://user-images.githubusercontent.com/6763645/62256069-299f3000-b3bd-11e9-9f19-bba4f61f0874.PNG)

If you click the word `Level` it will sort, but as you can see in the example it is sorting Intermediate to the top. I am guessing that at some point it changed from sorting by experience level (i.e. the 'value' of Beginner, Intermediate and Advanced) to alphabetical.

**Comment by willemarcel** [comment]
Solved with TM4
