### ISSUE TITLE
Installation fails due to conflicting urllib3 version

### ISSUE THREAD

**Issue by NeolithEra** [hotosm/tasking-manager#1813]
Hi, users are unable to run **_tasking-manager_** due to dependency conflict with _**urllib3**_ package. As shown in the following full dependency graph of **_tasking-manager_**, **_tasking-manager_** requires _**urllib3==1.24.2**_，while **_transifex-client==0.13.6_** requires _**urllib3<1.24**_.

According to pip’s “first found wins” installation strategy, _**urllib3==1.24.2**_ is the actually installed version.
However, _**urllib3==1.24.2**_ does not satisfy _**urllib3<1.24**_.

### Dependency tree------
```
tasking-manager(version range:)
| +-alembic(version range:==0.9.2)
| | +-SQLAlchemy(version range:>=0.7.6)
| | +-Mako(version range:)
| | +-python-editor(version range:>=0.3)
| | +-python-dateutil(version range:)
| +-aniso8601(version range:==1.2.1)
| +-bleach(version range:==2.0.0)
| +-cachetools(version range:==2.0.0)
| +-certifi(version range:==2019.3.9)
| +-chardet(version range:==3.0.4)
| +-click(version range:==6.7)
| +-coverage(version range:==4.3.4)
| +-flake8(version range:==3.7.7)
| +-flask(version range:==0.12.4)
| +-flask-cors(version range:==3.0.2)
| +-flask-httpauth(version range:==3.2.3)
| +-flask-migrate(version range:==2.0.4)
| | +-Flask(version range:>=0.9)
| | | +-Werkzeug(version range:>=0.15)
| | | +-Jinja2(version range:>=2.10.1)
| | | +-itsdangerous(version range:>=0.24)
| | | +-click(version range:>=5.1)
| | +-Flask-SQLAlchemy(version range:>=1.0)
| | +-alembic(version range:>=0.6)
| | | +-SQLAlchemy(version range:>=0.9.0)
| | | +-Mako(version range:)
| | | +-python-editor(version range:>=0.3)
| | | +-python-dateutil(version range:)
| | | +-SQLAlchemy(version range:>=0.6.0)
| | | +-SQLAlchemy(version range:>=0.7.3)
| | | +-SQLAlchemy(version range:>=0.7.6)
| | +-Flask-Script(version range:>=0.6)
| | | +-Flask(version range:)
| | | | +-Werkzeug(version range:>=0.15)
| | | | +-Jinja2(version range:>=2.10.1)
| | | | +-itsdangerous(version range:>=0.24)
| | | | +-click(version range:>=5.1)
| +-flask-oauthlib(version range:==0.9.3)
| +-flask-restful(version range:==0.3.6)
| +-flask-script(version range:==2.0.5)
| | +-Flask(version range:)
| | | +-Werkzeug(version range:>=0.15)
| | | +-Jinja2(version range:>=2.10.1)
| | | +-itsdangerous(version range:>=0.24)
| | | +-click(version range:>=5.1)
| +-flask-sqlalchemy(version range:==2.2)
| +-flask-swagger(version range:==0.2.14)
| +-geoalchemy2(version range:==0.4.0)
| +-geojson(version range:==1.3.4)
| +-gevent(version range:==1.4.0)
| +-glob2(version range:==0.7)
| +-greenlet(version range:==0.4.15)
| +-gunicorn(version range:==19.7.1)
| +-html5lib(version range:==0.999999999)
| +-idna(version range:==2.8)
| +-itsdangerous(version range:==0.24)
| +-jinja2(version range:==2.10.1)
| +-mako(version range:==1.0.6)
| | +-MarkupSafe(version range:>=0.9.2)
| +-markupsafe(version range:==1.0)
| +-mccabe(version range:==0.6.1)
| +-newrelic(version range:==3.2.0.91)
| +-nose(version range:==1.3.7)
| +-oauthlib(version range:==2.0.2)
| +-psycopg2(version range:==2.7.3.2)
| +-pycodestyle(version range:==2.5.0)
| +-pyflakes(version range:==2.1.1)
| +-pyproj(version range:==1.9.6)
| +-python-dateutil(version range:==2.6.0)
| +-python-dotenv(version range:==0.10.1)
| +-python-editor(version range:==1.0.3)
| +-python-slugify(version range:==1.2.6)
| | +-Unidecode(version range:>=0.04.16)
| +-pytz(version range:==2018.9)
| +-pyyaml(version range:==5.1)
| +-requests(version range:==2.21.0)
| +-requests-oauthlib(version range:==0.8.0)
| +-schematics(version range:==2.0.0a1)
| +-shapely(version range:==1.6.4.post2)
| +-six(version range:==1.11.0)
| +-sqlalchemy(version range:==1.3.0)
| +-transifex-client(version range:==0.13.6)
| | +-urllib3(version range:<1.24)
| | +-six(version range:==1.11.0)
| | +-requests(version range:>=2.19.1,<3.0.0)
| | | +-chardet(version range:>=3.0.2,<3.1.0)
| | | +-idna(version range:>=2.5,<2.9)
| | | +-urllib3(version range:>=1.21.1,<1.26)
| | | +-certifi(version range:>=2017.4.17)
| | +-python-slugify(version range:==1.2.6)
| | | +-Unidecode(version range:>=0.04.16)
| +-unidecode(version range:==1.0.23)
| +-urllib3(version range:==1.24.2)
| +-webencodings(version range:==0.5.1)
| +-werkzeug(version range:==0.12.2)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

1.	Fix your direct dependency to be urllib3==1.23. 
I have checked this revision will not affect your downstream projects now. 
2.	Ask your upstream project **_transifex-client_** to loose the version range of urllib3 to be urllib3>=1.21.1,<1.26.
Which solution do you prefer, 1 or 2?

@hunt3ri  Please let me know your choice. I can submit a PR to solve this issue.

**Comment by xamanu** [comment]
Thanks @NeolithEra! I'd say let's go with (1) for now. A PR is highly appreciated.
There is already some communication ([issue](https://github.com/camptocamp/c2cgeoportal/pull/4982)) in the transifex-client project to update their dependency, once this is done, we can update both the transifex-client and the urllib3.

**Comment by JorgeMartinezG** [comment]
To update this issue, @NeolithEra is right. the **urllib3** version currently within the requirements.txt file creates a conflict with current transifex module which needs an urllib3 version lower than 1.24. Right now I have the updated dependencies in this branch: https://github.com/hotosm/tasking-manager/tree/feature/1779-update-deps However some modules are not updated in order of not breaking tests.

**Note:** To test and verify I'm using two additional libraries:
- **pipdeptree:**  which creates the dependency tree. This lets me know which libraries are isolated and do not require other ones.
- **pip-review:** which shows me which library has an update available.
- **pip_check_reqs**:  It lists all modules which are not "used" by the project.

In this way, I can check which libraries i can remove from the requirements file and update the required ones.

**Comment by xamanu** [comment]
This has been fixed. Many thanks.
