### ISSUE TITLE
Administrator Account

### ISSUE THREAD

**Issue by inge4neuromedia** [hotosm/tasking-manager#1824]
I have an instance of tasking manager on a server. But when i logged in the application i only have standard user role but i don't administrator capabilities.

How i get the admin account for create project or make other things?

**Comment by JorgeMartinezG** [comment]
Hi @inge4neuromedia. One possible option is to execute a database query to update your user role as admin. Like:

```
UPDATE users set role = 1, email_address = 'your_email@gmail.com', is_email_verified=true where username = 'your_username'
```

Where 1 corresponds to admin role.

**Comment by inge4neuromedia** [comment]
@JorgeMartinezG  thank so much!.
