### ISSUE TITLE
Change redirect_to param on backend api

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1826]
Allow the `redirect_to` parameter to receive not only the end of the url but the complete url (for example: http://localhost:3000/login/), that way we would avoid problems when people are accessing from localhost or even allow us to authenticate in a remote server (staging, for example).

**Comment by fitoria** [comment]
Checked this one and the backend currenlty does not have any restrictions on what it does receive, right now the issue is on the react router [Redirect](http://knowbody.github.io/react-router-docs/api/Redirect.html) component that does not allows external domains and just paths within the same app.

**Comment by willemarcel** [comment]
Closing this, as @JorgeMartinezG is solving it in https://github.com/hotosm/tasking-manager/issues/1914
