### ISSUE TITLE
API Token

### ISSUE THREAD

**Issue by inge4neuromedia** [hotosm/tasking-manager#1831]
Have an instance of TM3 in another server . I tried to create a project through api rest but the backend returns 401 http status. this means that i dont have authorization for make that.

How do i get properly the token in order to use  API' protected resources?

**Comment by willemarcel** [comment]
@inge4neuromedia are you able to access the frontend of that instance? After the login, inspect some of the network requests and search for the `Authorization` header.

**Comment by inge4neuromedia** [comment]
> @inge4neuromedia are you able to access the frontend of that instance? After the login, inspect some of the network requests and search for the `Authorization` header.

 I tried it. it worked. thank so much.
