### ISSUE TITLE
Featured projects

### ISSUE THREAD

**Issue by JorgeMartinezG** [hotosm/tasking-manager#1836]
Enable a project to be featured by Project Managers. The following tasks are:
- Update database model to set a project as featured.
- Create API endpoints to list, set and unset projects as featured. Returning response must have the same structure as project search Endpoint
- Create services.
- Create tests for these services.

**Comment by thadk** [comment]
Thanks @JorgeMartinezG – ideally the list of projects set will have the same results as a `/search` query so the project cards https://github.com/hotosm/tasking-manager/issues/1628 have all the details.
