### ISSUE TITLE
Creator name change randomly when creating new project

### ISSUE THREAD

**Issue by adisadit** [hotosm/tasking-manager#1838]
Hi all,

Currently I have issue with my two newly created task. Yesterday I created this task:

https://tasks.hotosm.org/project/6497

When I want to edit the task, the creator changed from me to other user.

Today I created the task again:

https://tasks.hotosm.org/project/6498

But again the creator of this task is not me again.

Could you help me to solve this problem?

Thank you

**Comment by adisadit** [comment]
I can edit the project, for the first time. but after I closed the tab, I cannot edit again the project because I'm not the owner of the project:
![image](https://user-images.githubusercontent.com/2520159/63505155-3404a380-c4fd-11e9-9d93-bf5bf1bb578d.png)

**Comment by ramyaragupathy** [comment]
Transferred to your username @adisadit. Related issue tracker here https://github.com/hotosm/tasking-manager/issues/1715

**Comment by willemarcel** [comment]
It's been solved already
