### ISSUE TITLE
Add time details to Activity and Stats page

### ISSUE THREAD

**Issue by wireguy** [hotosm/tasking-manager#1846]
On the Activity and Stats page, the When column shows time in a relative way.
example: 5 minutes ago, an hour ago,  12 days ago, etc.

This is good, but after a few minutes there isn't a way to tell how long a user spent doing the task.

Provide a way to see how long was spent doing an activity.

Possible ideas:
- show timestamp (probably in UTC) for each activity (lock, unlock, split, marked ready, mapped) 

- show the time spent doing an activity. 
 examples: 
marked ready after 22 minutes
mapped after 83 minutes
unlocked after 120 minutes of inactivity

- change the When column to have the timestamp,   and add a new Duration column showing the time spent.   Every activity would have an entry in the When column, but not all activities need entry in the Duration column.  Time spent doesn't really make sense for split, locked.

note;
'When' changing to 'Updated' in #1631

**Comment by bopercival-hot** [comment]
closed as per comment above
