### ISSUE TITLE
Project Search API is slow for large resultsets

### ISSUE THREAD

**Issue by thadk** [hotosm/tasking-manager#1849]
When using the new front-end, the `project/search` API is fairly slow on the staging server, taking up to 15 seconds to return the default results (~2500 projects) for no specific filters.  If multiple people are using the API it seems to get even slower and can time out and show bad gateway. If you filter to a smaller set, such as the Intermediate (~200)  or Advanced (~30 projects), the API returns much more quickly.

It could be related to the query JOIN of all projects with their task history to get the number of distinct`total_contributor`'s to each project. This is hard to do efficiently in one query because we cannot look at *only* the one requested page of results: The map needs to show all the projects returned for browsing.  @JorgeMartinezG pointed to this line: https://github.com/hotosm/tasking-manager/blob/develop/server/services/project_search_service.py#L70

If possible in the API, maybe we can do two queries in one API endpoint: 

* one for `mapResults` that only gets the ID and centroid with no `LIMIT` covering every project, 
* and another query for `results` that does the join with the task history but is only covering the requested page of results. 

This change would allow the front-end to use the existing implementation. As a relatively straightforward optimization, it could ask the API to turn off the first `mapResults` SQL query and output if the front-end already has downloaded the `mapResults[]` GeoJSON for those search parameters on future `project/search` API requests for later pages. Doing this in one API also saves bandwidth without adding new requests for the client to make.

Overall, maybe we can research where the bottleneck is on this API for large results.

**Comment by JorgeMartinezG** [comment]
@xamanu this issue should be closed since it is included within #1854
