### ISSUE TITLE
Private projects invisible to authorized users

### ISSUE THREAD

**Issue by clairedelune** [hotosm/tasking-manager#1873]
So far, private projects have only been accessible typing their URL. For logged-in users whose usernames are listed in the properties of a private project, the project should be searchable: it should appear in the project list while searching for the project's name or number.

**Comment by xamanu** [comment]
Thanks for the input, yes I very much agree. Let's tackle this together with the teams frontend work for the version 4.

**Comment by xamanu** [comment]
This has been already addressed with the org manager check that we introduced through https://github.com/hotosm/tasking-manager/pull/2492
