### ISSUE TITLE
Use HTTP/2 or GZIP on Nginx for Tasking Manager

### ISSUE THREAD

**Issue by thadk** [hotosm/tasking-manager#1875]
Many of the APIs and resources associated with the TM 4.0 are not currently optimally compressed to conserve bandwidth, reduce load time and reduce latency anywhere in the world. 

As a best solution, HOT should look into using HTTP/2 on Nginx to serve the Flask web pages to the clients. As a fallback solution, we could add a GZIP compression module. Either solution will at least halve the download size of many resources.

The HTTP/2 protocol (previously called SPDY) compresses and reduces the number of round-trips necessary for the same transaction. It is supported by AWS Elastic Bean Stalk in a fresh configuration.

More details on the benefits and setup are [available in this article](https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-with-http-2-support-on-ubuntu-16-04):
   * All requests are downloaded in parallel, not in a queue
   * HTTP headers are compressed
   * Pages transfer as a binary, not as a text file, which is more efficient
   * Servers can “push” data even without the user’s request, which improves speed for users with high latency

**Comment by xamanu** [comment]
@eternaltyro is looking into this. Please report here. Thanks.

**Comment by eternaltyro** [comment]
I think it's a good idea to have HTTP/2 support and GZIP compression. Doing these will definitely improve page load speeds. Google Pagespeed Insights seems to agree: https://developers.google.com/speed/pagespeed/insights/?url=tasks.hotosm.org

**Comment by verdy-p** [comment]
Also with browser "Accept" MIME headers, we could serve better image formats than the default GIF/PNG/JPEG. There are newer more compact formats supported (notably WebP, except Apple's browsers but its support is about to be added by Apple and already exists in beta versions of their browsers for MacOS or iOS). This is already used by social networks, and photo sharing sites.
Note that even JPEG, GIF, PNG images can be statically compressed without loss on the server, even if they are served in JPEG/GIF/PNG to browsers that still don't have the support for newer image formats (and https://developers.google.com/speed/pagespeed/insights/?url=tasks.hotosm.org already makes that suggestion too)

**Comment by xamanu** [comment]
@eternaltyro what are the direct measures you recommend we implement to improve performance?

**Comment by thadk** [comment]
Thanks for setting this up @eternaltyro. For some reason the resources served by Flask seem not to be compressed by GZIP e.g.:
![image](https://user-images.githubusercontent.com/283343/67223132-b5dd5400-f3fc-11e9-80c3-9db53f1564a6.png)

**Comment by eternaltyro** [comment]
@verdy-p The image format suggestion is good. I think there are services that offer image optimization to reduce the size of images without losing (perceived) quality for site assets.

@thadk @xamanu I read up a bit about this and it seems gunicorn / flask can't do static compression efficiently. The recommended approach is to have nginx reverse proxy the requests from gunicorn bound to localhost (or using wsgi). 

Another approach we can explore is to use a CDN. We can host our static files on a CDN like Amazon CloudFront with an appropriate expiry / maxage. CloudFront can do compression.

**Comment by verdy-p** [comment]
Image size reduction is already used by Wikimedia with their thumbnail
server for Mediawiki (for now it creates only JPEG and PNG, but may use
WebP as its support is already very wide, except for now the default Apple
browsers for iOS and MacOS (but they are coming).

The thumbnail server can support the "Accept:" MIME headers to return the
cached thumbnails, built dynamically (if a thumbnail is not immediately
available, the server may return a default image in an alternate format,
and there's support in HTML5 to support multiple image references for
various browsers with different capabilities or rendering conditions, like
HiDPI devices).

As well, Mediawiki has now a builtin server to create stripped versions for
CSS, JOSN, HTML, XML, which will then compress even better with lower CPU,
memory and network resources in front caching proxy servers. This also
helps for mobile users whose ISPs do not provide such proxy themselves and
notably in developing countries where the available bandwidth is much lower
and much more expensive for end users, and frequently shared by many
concurrent users.

Using HTTP2 in front caching servers also helps a lot to speed up page
loads, reduce the bandwidth needed, and improve the interactivity.

But the main problem for HOTOSM is for imagery tile servers: not all
imagery sources have good compressors, and may be we would need to create
out own caching proxy: most bandwidth needed in HOTOSM is for the imagery,
and many users cannot use it without lengthy response times, and huge costs
in their limited dataplans

(notably in developing countries or shared internet accesses only via a
surcharged set of a few local Wifi channels: 3 channels at most within the
2GHz band, and many devices still don't have support for 5GHz with
additional channels... let's not even talk about MIMO, which most often
only works in single-user mode and does not allow aggregation of shared
channels, except in the next coming standard requiring a few specific
mobile devices and hotspot routers which are also the most expensive).

Even if HOTOSM is difficult to use on a smartphone, it should work on
mobile tablets and should avoid using features that are too much battery
intensive or CPU/memory intensive: even if gzip-like compression is used in
the networking layer, the decompression should not require lot of memory
and all unnecessary bytes in decompressed formats will have cost.
Precomputing and filtering the data they will experiment with should be
done on servers or front proxies to allow serving more people and with
lower computing and networking requirements.

If this is still not possible in out existing softwares, may be we could
have a solution with remote desktop services offering the web browsing
experience for them over a cloud service.

**Comment by xamanu** [comment]
What are your suggestions here, @eternaltyro? Is this relevant for our infrastructure and it's performance or costs? Is this in relation to the effort?

**Comment by xamanu** [comment]
Closing here.
