### ISSUE TITLE
New notifications endpoint

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1881]
From https://github.com/hotosm/tasking-manager/issues/1644

**Comment by thadk** [comment]
To support #1655 we would need to index the text in subject, body, and ID of the task/project so it can have full text search like we have in "Explore Projects" with the PostgreSQL GIN index.
https://www.postgresql.org/docs/11/textsearch-controls.html
There are a few migrations in the codebase for the `projects` table we could probably copy to create the needed columns for metadata storage.

**Comment by ramyaragupathy** [comment]
Basic functionality implemented through #1928
