### ISSUE TITLE
Add events section to homepage

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1882]
It's not a priority, but one of the actions we need on a second stage of the redesign is a component listing the events. We need to decide where we get the data from and some other aspects.

Design reference: https://projects.invisionapp.com/share/WTRWOQ6Y6RQ#/screens/362186631

**Comment by xamanu** [comment]
Yes, events is a challenge. Especially we don't want to open up yet another space for events. For now I would close this and see whether this was a good design idea or is really requested by the users.
