### ISSUE TITLE
Review infrastructure needs for redesign release

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#1883]
Before the testing release of the redesign, we should try to prepare for changes to infrastructure arising from the redesign and implement infra improvements that would help maintain smooth operation of TM going forward. From the discussion at today's meeting, here are some thoughts to start and we can flesh out priorities and details:

- releasing the test app on a separate stack
   - consider costs involved
- further speed up deployment times
- Tracking via matomo
- Instance logging to CloudWatch

**Comment by xamanu** [comment]
The proposed url for the testing instance is: `tm4.hotosm.org`

**Comment by willemarcel** [comment]
@dakotabenjamin @eternaltyro do you think it would be possible to serve the frontend in a static server instead of serving it as a flask view? I think it would reduce the load on the backend server and solve some issues we are having with the serviceWorker intercepting the API requests.

**Comment by dakotabenjamin** [comment]
Do you know if that can be served on s3 @willemarcel ?

**Comment by willemarcel** [comment]
@dakotabenjamin yes, it can! Some tutorials:
https://medium.com/@wolovim/deploying-create-react-app-to-s3-or-cloudfront-48dae4ce0af
https://www.fullstackreact.com/articles/deploying-a-react-app-to-s3/
