### ISSUE TITLE
How to modify text on TeachOSM tasking mgr?

### ISSUE THREAD

**Issue by geomantic** [hotosm/tasking-manager#1887]
Because it's a fork of the HOT tasking manager, the language on the TeachOSM tasking manager talks about HOT, rather than educational applications of OpenStreetMap. For example, on the language on the splash screen is pretty specific to HOT, but we (TeachOSM project) would like to update to reflect project priorities/mission.

How best to accomplish?

**Comment by xamanu** [comment]
Thanks for reaching out @geomantic!

The TM3 doesn't have perfect support for that. Most people achieved it by editing the [design template for the specific page](https://github.com/hotosm/tasking-manager/blob/master/client/app/home/home.html) and then run the frontend generation. This is not perfect and we are trying to improve that for TM4. So you might want to hold on for the next version to do your changes. Or already now. If you need assistance with the steps, please feel welcome to contact us on hotosm.slack.com in the #tasking-manager channel.

**Comment by geomantic** [comment]
@xamanu thanks for that. We'll get started on content and evaluate level of effort for editing the template. I'll make a point of checking in over on the #tskg-mgr channel, too.
