### ISSUE TITLE
Teams, orgs and campaigns frontend

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1890]
On top of the backend #1858 for teams orgs and campaigns a suitable user interface must be created. @hexiaok is currently looking into this and will provide design input.

**Comment by hexiaok** [comment]
@xamanu Here provide 3 entry-point options for users to explore teams:
**Option 1** 
Use tabs & `explore projects` and `explore teams` in one screen
Pros: users can see the content of `projects` and `teams` at the same time
Cons: the list of projects is already a long one and people want to use this long list. And it is also one of the heaviest queries to the database. So adding up another one might be a bit a problem in performance and comfort for the user. 
UI Ref: 
![Explore1](https://user-images.githubusercontent.com/26889634/67069546-08760080-f1b0-11e9-9ccc-fe047bc4139b.jpg)

**Option2**
Use tabs & `explore projects` and `explore teams` are in separate screens, by default users will see the `explore projects` first
Pro: solve the concern of Option1
Con: `explore teams` is a bit hidden for users 
UI Ref:
![Explore2](https://user-images.githubusercontent.com/26889634/67069786-d2854c00-f1b0-11e9-97a2-5fed9e3c8919.jpg)

**Option3**
Use dropdown
Pro: List `explore projects` and `explore teams` at the same time, easy for users to see both
Con: Users need to click twice to go to the project page or team page 
UI Ref:
![Explore 3](https://user-images.githubusercontent.com/26889634/67069925-3f98e180-f1b1-11e9-9605-98d452bb928a.jpg)

**Comment by verdy-p** [comment]
Option 2 seems better:
- most users will first see the projects, and that's where we need the most people: that's where we can promote the most active projects (other projects from the same team can be found in each project)
- adding one more click will be fine for project teams, that have more limited goals, and generally already have their own tracking page that could point directly to their own projects without having to browse to find themselves.
- other users that started projects will generally know for which team they are working, directly from the project description. They will join these teams directly without searching for them. So browsing teams will be used very infrequently, and only by users that have already gained some experience and want to extend their support. Generally this will be to see if there are other teams with similar goals or interests, or working in some specific regions.

Option 3 would be much less attractive, in fact boring: it would not be immediate for new comers what HOT is working on and active, unless there's additional home content added such as a calendar of events, and a newsfeed, and a small excerpt from the "About" details.

But there's an alternative: display just one row of blocks for each section, allowing that row to scroll horizontally, or making it scroll every few seconds. Allow users to click on one of them. Allow user to click a "See all" to get an extensive list. You could even have a single row of projects or teams mixed in the auto-scrolling content, chosen randomly within some lists of "most active", "most recent", "most urgent", "most complete projects". Each tile would then have a bottom button "browse other teams" in a team tile, or "browse other projects" in a project tile. Then you could keep the menu of option 3 just above it for a complete browse.

This way no need to scroll down for long, each section has some content to show, each one has at least one summary.

Final note: please reduce the height of all top banners to the minimum. For now this layout occupies nearly all the height on a typical smartphone, users need to scroll down always, and even then the  horizontal margins are excessive when the actual content is in tiles that already have their own delimitation in internal margins (it's still very accessible for readers). You can place as many tiles as can fit without these extra margins (not even aligned to the margins of your proposed top banners and menus. Wasting space jsut to display large blank margins, and then to force users to scroll, would not help.

Also avoid extreme font sizes in the banner (e.g. the "EXPLORE" word at top just distracts too much users from reading all the rest, when there are so small items like the "show map" button, or the language selector (not evident to see), or the "sign in"/logon button.

**Comment by verdy-p** [comment]
note also: if the user are signed in, then he may have preferences to the content of this page, where they would like to pin some of their interesting feeds, just above the default randomly selected content still displayed below: users will then focus rapidely to what interest them and can change their mind later. Some "pinnable" feeds could be project tags or the result of their prefered search string (prefilled in the search form, possibly with a combo to add a search in their list of favorites).

**Comment by xamanu** [comment]
@hexiaok developed a [click-dummy for teams and organizations](https://projects.invisionapp.com/share/7PUM47HQ3H9#/screens).

**Comment by xamanu** [comment]
I suggest to close this issue as a duplicate of #1591
