### ISSUE TITLE
Translate country names on the frontend

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1893]
The projects now include information about the country. We need a solution to translate the names of the countries that are coming from the database.

Related to https://github.com/hotosm/tasking-manager/issues/1495

**Comment by willemarcel** [comment]
Possible source of country names data:

- https://github.com/nvkelso/natural-earth-vector/blob/master/CHANGELOG
- https://github.com/Tommytrg/country-names-list/blob/master/countries.json

We need to check which of them matches better with the languages we currently support

**Comment by verdy-p** [comment]
Why not country names that are in Wikidata (just need their QID, easy to
collect, and already implemented in data modules or list of countries on
Commons, including for nav templates).
At least they are reviewed constantly for most active languages, and thye
have a wider range of supported languages than those vetted in CLDR (which
also uses Wikidata as a source, and Wikidata also synchronizes the vetted
translated named approved in CLDR, though they are very long to be updated
in CLDR which is a very slow process)

Le jeu. 31 oct. 2019 à 02:46, Wille Marcel <notifications@github.com> a
écrit :

**Comment by willemarcel** [comment]
@verdy-p We would like to use a solution that can work in a environment without internet access, so we need to have that data on our system. It seems the natural-earth-vector already has a sync with wikidata implemented.
