### ISSUE TITLE
Fix percentMapped and percentValidated counts

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1908]
[That project](https://tasks.hotosm.org/project/6163) is completely mapped, but it's returning 91% mapped and 96% validated (`percentValidated` could not be bigger than `percentMapped`)

Another improvement I propose is to consider the `BADIMAGERY` tasks as mapped and validated on that count. So the user can know when some work is missing on a project or not.

Do you agree, @xamanu ?

**Comment by willemarcel** [comment]
I just noticed that we have the `percentBadImagery` information, so I think we don't need to count badimagery on the other fields. It would be good verify if the rounding is working well and can not cause uncertainty about if a project is complete

**Comment by willemarcel** [comment]
@xamanu @russdeffner I checked that TM3 allows me to validate a task that was set as `BADIMAGERY`, it even allows me to validate a task that was set as BADIMAGERY by me.

Should we consider that all `BADIMAGERY` tasks needs validation? Do you think we should change something on this flow?

**Comment by russdeffner** [comment]
@willemarcel - thinking about this a bit more... yes, it's probably ok to be able to 'invalidate' your own bad imagery task; but with restrictions to validator status projects - this maybe isn't necessary and bad imagery tasks should be treated as a 'mapped' task only reviewable by someone else.

Also, I'm not sure my initial thought was 'fully correct'. I don't think we want a bad imagery to go to validated status. Project Managers may find it useful to be able to quickly see spots in their projects with 'bad imagery'/clouds, etc. So we could still allow 'invalidate', or maybe when you review a bad imagery task you are only provided the options to "un-mark" (i.e. reset to 'ready for mapping' state) or 'leave as bad imagery'.

**Comment by willemarcel** [comment]
Thank you, @russdeffner ! I agree with you. So we have to work on this actions:

- [ ] Fix `percentMapped`
- [ ] Fix `percentValidated` and consider `BADIMAGERY` tasks as non mapped in the validation count
- [ ] Disallow a user to validate a task that him/herself set as `BADIMAGERY`

Users will continue to be able to invalidate/reset status of BADIMAGERY tasks even if this status was set by them.

**Comment by xamanu** [comment]
That must be fixed by now. Please reopen if problem still exists.
