### ISSUE TITLE
Basic embedding of iD in TM

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1909]
We want iD to become part of the Tasking Manager: #1358

In order to work on the integration two possible ways of embedding (possibly via an iframe) should be possible:

* Embed main iD as an iFrame.
* Create a packaged (maybe containerized) setup for a self-hosted iD.

**Comment by JorgeMartinezG** [comment]
To update on this issue. I implemented a basic approach and would like some feedback:
1. Cloned id repository locally and installed required modules and dependencies.
2. Compiled id editor.
3. Copied _dist_ folder_.
4. Served folder with python and an _index.html_ file. 

The main idea is to use id editor as static folder, just like swagger. Then, within TM, we can create a new route passing the project task as gpx

**Comment by willemarcel** [comment]
We could evaluate it together with https://github.com/hotosm/tasking-manager/issues/1883

**Comment by JorgeMartinezG** [comment]
**Update**

The current work done has been pushed to: https://github.com/hotosm/tasking-manager/tree/feature/1909-id-embed

**Notes**
- Id editor library is served with Flask. A new endpoint has been included which reads oauth parameters and renders a html template.
- I included a quick fix to service-worker.js which enables to bypass server endpoints. Needs further review.
- If an user is not logged in Tasking Manager, cannot access id editor endpoint

**Comment by xamanu** [comment]
I know @willemarcel has started working on it. Assigning to him.

**Comment by xamanu** [comment]
The counterpart on the iD side has been implemented (https://github.com/openstreetmap/iD/pull/7333), we are good to continue here.

**Comment by xamanu** [comment]
Wohooo, this is in.
