### ISSUE TITLE
Transform the /api/v2/system/authentication/login/ view in an API view

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1914]
Currently the`/api/v2/system/authentication/login/` is not an API view, as it's redirecting the user to OSM. Ideally that view should be an authentic API view handling GET and POST requests and returning the token to the users.

Reference of how the OSM authentication works on OSMCha: https://github.com/willemarcel/osmcha-django#how-to-login-using-the-oauth-api

cc @xamanu @JorgeMartinezG 

Related to https://github.com/hotosm/tasking-manager/issues/1521

**Comment by JorgeMartinezG** [comment]
@xamanu this issue could be closed. The fix was sent within #1937
