### ISSUE TITLE
User warning for large project extent

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1915]
Our average project size stands at 5500 sq.km, but there are 400+ projects exceeding the average extent. Per chat w/ @willemarcel @dakotabenjamin and @eternaltyro a user warning
should be provided during project creation

**Comment by xamanu** [comment]
Yes, good step. Is this a duplicate of https://github.com/hotosm/tasking-manager/issues/1080?

**Comment by xamanu** [comment]
@JorgeMartinezG Can this be included in the TM4 project creation (https://github.com/hotosm/tasking-manager/issues/1888) you are currently working on?

**Comment by xamanu** [comment]
This has been included. Closing the issue here.
