### ISSUE TITLE
Custom Editor Options

### ISSUE THREAD

**Issue by zlavergne** [hotosm/tasking-manager#1916]
I'd like to discuss a new feature that will allow Project Managers to add a custom editor endpoint to a project that will be added as an additional option in the dropdown list:
![image](https://user-images.githubusercontent.com/9849118/66603330-2d8fc100-eb69-11e9-8489-8a6ca096bb34.png)

The plan is to add it as a "Custom" option to the editor options in the "Settings" section of the `edit-project` page. 

cc @xamanu

**Comment by xamanu** [comment]
Yes, I think that makes the TM much more flexible. Maybe we just want to show the possibility to add those custom endpoints only for project managers, that have the "Expert mode" switched on.

**Comment by russdeffner** [comment]
I think this is good as long as it still allows the PM the ability to only allow specific editors. In project creation there is already the check-boxes to display/not-display editors in the drop-down. So this custom would also need populated there.

**Comment by russdeffner** [comment]
@zlavergne - that, but more along the lines of... if I only want mappers using the custom editor or JOSM, that I can still do that in Settings.

**Comment by zlavergne** [comment]
> if I only want mappers using the custom editor or JOSM, that I can still do that in Settings.

@russdeffner I'll try to have a screen capture of how this will look in a few hours but that's the plan 😄

**Comment by xamanu** [comment]
This is in by now. Many thanks!
