### ISSUE TITLE
Cannot deploy deployment/hot-tasking-manager

### ISSUE THREAD

**Issue by adrienandrem** [hotosm/tasking-manager#1917]
I have trouble trying to set up an instance from the [deployment/hot-tasking-manager branch](https://github.com/hotosm/tasking-manager/tree/deployment/hot-tasking-manager).
First I set the consistent branch name in [devops/docker/tasking-manager](https://github.com/hotosm/tasking-manager/blob/deployment/hot-tasking-manager/devops/docker/tasking-manager/Dockerfile#L15)
Then launching `docker-compose up`, i see in the logs:
* `migration_1` fails to connect to postgresql several times
* `postgresql` prints an error `relation "projects" does not exist`

Finally, http://127.0.0.1:5000 returns a 404 error.

**Comment by xamanu** [comment]
Hi @adrienandrem, I suggest you to take the `master` branch. For both the checkout and the branch name in the `devops/docker/tasking-manager`.

**Comment by adrienandrem** [comment]
Hi @xamanu, thank you for your help. Trying with `master`, I get the same first two errors, but it might be OK: migration processing attempts while postgresql boots up, I guess.

I still get the 404 error though.

One clue might be the  
`WARNING: Connection pool is full, discarding connection: localhost`
printed just before `docker-compose up` ends.

**Comment by AmarOk1412** [comment]
@xamanu 

I just tried on a fresh device:

```
git clone git@github.com:hotosm/tasking-manager.git
cd tasking-manager
git checkout master
```

In `devops/docker/tasking-manager/Dockerfile` I changed the branch to `master`

In my `tasking-manager.env` I only changed the following lines (infos from https://www.openstreetmap.org/user/YYYYY/oauth_clients/XXXX)
```
TM_SECRET
TM_CONSUMER_KEY
TM_CONSUMER_SECRET
```

Then `docker-compose up -d`. `docker-compose logs` show migrations errors (but I think it's because there is nothing to migrate), the rest is ok.

However http://127.0.0.1:5000/ return a 404 error.

```
app           | manage.py:28: UserWarning: TM_DEFAULT_CHANGESET_COMMENT environmental variable not set.
app           |   warnings.warn("%s environmental variable not set." % (key,))
app           | manage.py:35: UserWarning: Homepage counters not initialized.
app           |   warnings.warn('Homepage counters not initialized.')
app           |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
app           | 172.18.0.1 - - [22/Oct/2019 23:06:46] "GET / HTTP/1.1" 404 -
app           | 172.18.0.1 - - [22/Oct/2019 23:06:46] "GET /favicon.ico HTTP/1.1" 404 -
app           | manage.py:28: UserWarning: TM_DEFAULT_CHANGESET_COMMENT environmental variable not set.
app           |   warnings.warn("%s environmental variable not set." % (key,))
app           |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
app           | 172.18.0.1 - - [22/Oct/2019 23:08:45] "GET / HTTP/1.1" 404 -
```

**Comment by xamanu** [comment]
Hey, please set `TM_DEFAULT_CHANGESET_COMMENT` to something unique and it shall work.

**Comment by AmarOk1412** [comment]
yeah I set it in my tasking env after my comments, this doesn't change anything, was just a warning (and @adrienandrem did it too)

**Comment by adrienandrem** [comment]
`TM_DEFAULT_CHANGESET_COMMENT` is set in `tasking-manager.env`.

@xamanu do you confirm on your side you do not get a 404 error with fresh configuration and install from `master`, following [README instructions](https://github.com/hotosm/tasking-manager/blob/master/README.md)?

Is there specific info I could report here?

Thanks

**Comment by GnanaShekhar** [comment]
@adrienandrem I did the same today. Faces

- Cloned package
- `git checkout master`
- `cp example.env tasking-manager.env`
- Add `TM_CONSUMER_KEY ` and `TM_CONSUMER_SECRET` in tasking-manager.env
- Uncomment `POSTGRES_ENDPOINT=localhost` & `POSTGRES_PORT=5432`
- and then `docker-compose up -d`

Tried to access it from http://0.0.0.0:5000/ got the following error on webpage

> Not Found
> The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Logs had 
```

Attaching to app, taskingmanager_migration_1, postgresql
postgresql    | LOG:  database system was shut down at 2019-11-11 10:51:56 UTC
migration_1   | [2019-11-11 10:52:00,146] INFO in __init__: Tasking Manager App Starting Up, Environment = None
postgresql    | LOG:  MultiXact member wraparound protections are now enabled
migration_1   | [2019-11-11 10:52:00,146] DEBUG in __init__: Initialising Blueprints
postgresql    | LOG:  autovacuum launcher started
migration_1   | [2019-11-11 10:52:00,152] DEBUG in __init__: Initialising API Routes
postgresql    | LOG:  database system is ready to accept connections
migration_1   | [2019-11-11 10:52:00,244] DEBUG in __init__: Initialising Homepage Counters
migration_1   | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
app           | [2019-11-11 10:52:11,308] INFO in __init__: Tasking Manager App Starting Up, Environment = None
migration_1   | INFO  [alembic.runtime.migration] Will assume transactional DDL.
app           | [2019-11-11 10:52:11,309] DEBUG in __init__: Initialising Blueprints
app           | [2019-11-11 10:52:11,315] DEBUG in __init__: Initialising API Routes
app           | [2019-11-11 10:52:11,406] DEBUG in __init__: Initialising Homepage Counters
app           |  * Serving Flask app "server" (lazy loading)
app           |  * Environment: production
app           |    WARNING: This is a development server. Do not use it in a production deployment.
app           |    Use a production WSGI server instead.
taskingmanager_migration_1 exited with code 0
app           |  * Debug mode: off
app           |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
app           | 10.XXX.XXX.17 - - [11/Nov/2019 10:52:29] "GET / HTTP/1.1" 404 -
```

**Comment by GnanaShekhar** [comment]
I think I found the issue, `GET /` is unable to fetch the index.html. Reason being `_init_.py` in `/server` is handling the get request and trying to render index.html from `/frontend/build`. So when you run docker-compose up -d it should be build the frontend but it failed for some reason.

Solution: Go to /frontend and execute the commands `npm install` and `npm run build` then you will get /frontend/build folder and then if you re-run the command docker-compose up -d in the `/` folder. You should see the website running at http://127.0.0.1:5000/

Even after doing this there is some functionality of the package that is still throwing 404 issues, like http://127.0.0.1:5000/contribute. So please verify and test before using it just after that.

**Comment by adrienandrem** [comment]
Thank you for the clue @GnanaShekhar!
It is still `/client` on `master` actually.

I'd think this would be already handled in the [Dockerfile client configuration](https://github.com/hotosm/tasking-manager/blob/master/devops/docker/tasking-manager/Dockerfile#L34),
no error is returned at execution:

    Step 11/13 : RUN cd client && npm link gulp && 	npm install closure-util --save && 	npm install && gulp build
     ---> Using cache
     ---> 0eef7f049637
    Step 12/13 : EXPOSE 5000

Logging into `app` container and running the commands return errors  
and `/frontend/build` is not generated:

    root@81ca2d20abe1:/usr/src/app/client# npm install
    npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN hot-tasking-manager@3.0.0 No repository field.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    
    up to date in 15.47s
    root@81ca2d20abe1:/usr/src/app/client# npm run build
    npm ERR! missing script: build
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2019-11-19T20_50_03_227Z-debug.log

Please note that I'm not familiar with JavaScript.

**Comment by adrienandrem** [comment]
@xamanu I don't know why but pulling once more from `master` seems to have solved the problem.  
UI is displayed and I'm able to log in.

If this can be of any use, here is my local diff:

    diff --git a/devops/docker/tasking-manager/Dockerfile b/devops/docker/tasking-manager/Dockerfile
    index bf5d734..cda0fdf 100644
    --- a/devops/docker/tasking-manager/Dockerfile
    +++ b/devops/docker/tasking-manager/Dockerfile
    @@ -12,7 +12,7 @@ RUN apt-get update \
     # Upgrade pip
     RUN pip install --upgrade pip
     
    -ARG branch=develop
    +ARG branch=master
     RUN git clone --depth=1 git://github.com/hotosm/tasking-manager.git \
            --branch $branch /usr/src/app
     
    diff --git a/docker-compose.yml b/docker-compose.yml
    index 518a2ab..5cf2a30 100644
    --- a/docker-compose.yml
    +++ b/docker-compose.yml
    @@ -4,7 +4,7 @@ version: '3'
     services:
       # Main application
       app:
    -    image: hotosm/tasking-manager
    +    build: ./devops/docker/tasking-manager
         container_name: app
         env_file: tasking-manager.env
         environment:
    @@ -22,7 +22,7 @@ services:
     
       # Migration service
       migration:
    -    image: hotosm/tasking-manager
    +    build: ./devops/docker/tasking-manager
         env_file: tasking-manager.env
         restart: on-failure
         environment:

**Comment by adrienandrem** [comment]
Short-lived joy, rerunning the whole process from a new

    git clone -b master https://github.com/hotosm/tasking-manager

gives the same 404 problem.

**Comment by timwaters** [comment]
I was seeing the same error with the develop branch and the hotosm/tasking-manager image. So I tried building from master following the above comments. If helps any I was able to (on master), connect to the docker container e.g `docker exec -it abcdefg bash`

```
>root@abcdefg:/usr/src/app#

cd client/
npm install
npm rebuild node-sass
gulp build
```
Then going to http://127.0.0.1:5000/  worked :)

-----

p.s. the reason why I did the `npm rebuild node-sass` was that I saw:

```
gulp build
/usr/src/app/client/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /usr/src/app/client/node_modules/node-sass/vendor/linux-x64-59/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 9.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
```
