### ISSUE TITLE
TM architecture

### ISSUE THREAD

**Issue by qeef** [hotosm/tasking-manager#1920]
I think that the architecture of TM is wrong. I think that the proper design is:
- Separate backend and frontend repositories.
- Make backend REST API only.
- Make backend asynchronous.

Is anyone considering the architecture review?

**Comment by qeef** [comment]
> > Separate backend and frontend repositories.
> 
> Can you elaborate on this a bit, please? I think there are several valid design patterns. And we are improving on the separation between frontend and packend with the current redesign. Splitting up the repository would have a lot of implications and I would like to know your arguments in favour of splitting.

I am interested in this one. Which valid design patterns do you (as HOT TM dev team) consider?

There are few reason, from my point of view, for splitting:
- Different dev teams for Python and JavaScript.
- Different performance measurements.
- Different designs needs -- UI vs. API.
- There must be standardized communication between backend and frontend.
- Multiple client applications for different purposes (aka just mapping, manager app, statistics app).

**Comment by xamanu** [comment]
By the way, we have a pretty clear separation of frontend and backend in different directories. And: it works well.

> Different dev teams for Python and JavaScript
Yes, this is true for a huge project. But in our case, we have only one team and we want people that contribute to the Tasking Manager to understand the application as a whole. Once we have two teams working side-by-side, I agree, it might become interesting to consider a split of the repository. Right now, i fear, it would cause an overhead and make things more complicated for people joining the project.

> Different performance measurements.

We have the possibility to run frontend and backend together as one service, but also to run it as separate services. This seems to be more an infrastructural question than a matter of having it in two repositories.

> Different designs needs -- UI vs. API.
> There must be standardized communication between backend and frontent.

Yes, this is correct. I think with the current review of the API we have made good progress in the standardization of the API. However we usually develop user oriented and feature driven, which means that we extend and adapt the API to the needs of the UI. They are not two side projects for frontend and backend.

> Multiple client applications for different purposes (aka just mapping, manager app, statistics app).

Great idea and very good argument. As soon as there is established and actively maintained Software available that consumes the API in this way, it would make a lot of sense and we are very open to split the repos!

**Comment by qeef** [comment]
Thanks, @xamanu for the information. I think that I have no more questions regarding project architecture.

I do not agree with all the decisions but I understand those had to be made.

Anyway, I am closing the issue as it is a question and I have my answers. Thanks!
