### ISSUE TITLE
Interface for interests

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1926]
After introducing type of action and interests to users #1640 and #1781 we need a way to manage those categories. I would suggest to build a small "Manage interests" page on the UI, that is available to admins only. There admins can add and remove interests one by one.

* A new interest should always increase the <interest_id> to avoid clashes.
* Existing interests should show how many projects and users have selected them.
* When trying to delete an interest that is being used by at least one project or user, ask the admin for confirmation when deleting.

**Comment by willemarcel** [comment]
@xamanu currently the Interests creation is open to any logged user, should we restrict it to only project managers and admins?

**Comment by xamanu** [comment]
Yes, interests shouldn't change a lot. Restrict to admins please.
