### ISSUE TITLE
Highlight tasks locked by user

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1938]
On the task selection page, if the current user has one task locked for mapping or validation, highlight that information on the map and on the task list. We don't need to restrict any user action (the backend will do), just show that information on the map.

Suggestions, @hexiaok , @xamanu ?

**Comment by russdeffner** [comment]
Wille, just wondering what it might look like/what we need to do for a mapper/validator that selects a task on one project but then navigates to another project all together? They obviously should not be able to select another task there, but how will that be visualized to them - an 'error' message? if so, it should specify what project they have a task locked on so they can easily navigate back to unlock it.

**Comment by willemarcel** [comment]
@russdeffner I see some different cases:

If the user is on the project where they have some task locked, highlight the task on the map and task list so the user can notice it.

If the user is not on the project page, we can always show it on the user menu, something like:
![image](https://user-images.githubusercontent.com/666291/68024876-1b95cf80-fc8a-11e9-900f-037ea0e12027.png)

but replacing the top part of this tooltip by the information of the task locked and linking to that task.

Finally, if the user try to lock a task on another project, show a modal notification and give him the option to go to the task he locked previously.
