### ISSUE TITLE
Switch task list to the page of the selected task

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1940]
When a user clicks on a task on the map, make the list switch to the page where that task is present, except when we have some filter and the task is not included in the filter results.

**Comment by xamanu** [comment]
In latest testings the suggestion came up to change the information on the left hand side to information on the task, and maybe list also the tasks around it.

**Comment by willemarcel** [comment]
Solved by https://github.com/hotosm/tasking-manager/pull/2430
