### ISSUE TITLE
List contributors on the project detail page 

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1942]
![image](https://user-images.githubusercontent.com/666291/67859331-202b7e00-fafa-11e9-83c8-5904dbaf2089.png)

If the user has not the profile picture on the database entry, show the initials of his name or his username if the user has not filled the name field yet.

**Comment by willemarcel** [comment]
I pushed a first version on #2213 

The endpoint `/api/v2/projects/{project_id}/contributions/` is not returning the `pictureUrl`. Could you take a look on it, @ramyaragupathy or @JorgeMartinezG?

**Comment by ramyaragupathy** [comment]
@willemarcel - working on this

**Comment by willemarcel** [comment]
this issue is finished by https://github.com/hotosm/tasking-manager/pull/2319
