### ISSUE TITLE
Add section to list comments and questions of the project

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1943]
![image](https://user-images.githubusercontent.com/666291/67859573-bcee1b80-fafa-11e9-96bf-a366bfc0597e.png)

It's located on the project detail page and needs also to allow the user to post a new comment/question.

**Comment by JorgeMartinezG** [comment]
**Update:** On the backend side. There are some changs that need to be implemented but I would like to know your opinions @willemarcel @xamanu:
1. We would need to create a new endpoint to search comments in a project.
2. We would need to create the comments **SortBy** endpoint.
3. Currently, there are no comment replies model within **ProjectChat**. The endpoint just queries for the comments of a project. To accomplish this. I propose two options:

a. Create a new column within ProjectChat called **children** which is an array of integers and stores the ids of the comments which are replies to the parent one.
b. Create a many-to-many relationship table which references the ids of the **ProjectChat** model. We would need two columns only. Child and Parent.

Both options would require a new migrations file. Option b will not have fixed depth IMO I prefer option b

**Comment by willemarcel** [comment]
@JorgeMartinezG I think we could go without the search and without organizing the replies on threads. I think there is not a large amount of questions & comments on a project that raises the need for search & sorting. The threads would be useful, but we could let it for the future.
