### ISSUE TITLE
Create "My projects" page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1945]
![09_User Profile_my projects_03](https://user-images.githubusercontent.com/666291/67866914-65ef4300-fb08-11e9-956f-6039e0703c45.png)

**Comment by thadk** [comment]
@willemarcel @xamanu By the way, how should Archived Projects appear?

<img width="379" alt="image" src="https://user-images.githubusercontent.com/283343/69792107-e8b0ff80-1193-11ea-8e0d-68bae29f74c6.png">

**Comment by xamanu** [comment]
I would go with an additional button on the filters for "archived" besides "created", "contributed", "favorite". What do you think?

**Comment by willemarcel** [comment]
Yes, a filter button would be an excellent solution.

**Comment by xamanu** [comment]
Is this in by now? Does it work good?

**Comment by willemarcel** [comment]
It's missing to add some filters yet.

**Comment by thadk** [comment]
Hypothetically everything is wired up so if these GET parameters are implemented on the backend, the filters will all work: `CreatedByMe` (done), `CreatedByMeArchived`, `CreatedByMeDraft` (?), `FavoritedByMe`, and `ContributedToByMe`

**Comment by willemarcel** [comment]
Finished this issue with https://github.com/hotosm/tasking-manager/pull/2248
It's missing to solve https://github.com/hotosm/tasking-manager/issues/2132 for complete functionality.
