### ISSUE TITLE
Allow multiple tasks selection to validation

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1946]
![image](https://user-images.githubusercontent.com/666291/67867876-d6e32a80-fb09-11e9-81e1-1e1f0645edb6.png)

If the multiple selection toggle is active, when the user select a second (or subsequent) task it will keep the first selected tasks.

This feature should be accessible only to `expertMode` users that can validate a project.

**Comment by xamanu** [comment]
@willemarcel I think this has been implemented and you showed it today, but with a slightly different implementation. Can this issue be closed?

**Comment by willemarcel** [comment]
@xamanu we don't have yet the switch that allows the user to select multiple tasks, but we can select all the tasks a user mapped and go to validate them.

I don't think that multiple selection switch is important now, but we need to update the validate page to allow the user to set a status to each task they're validating.

**Comment by xamanu** [comment]
This is going to happen in #2017
