### ISSUE TITLE
custom imagery offset 

### ISSUE THREAD

**Issue by Geocruizer** [hotosm/tasking-manager#1948]
Is it possible to create a custom imagery offset and build that into a project as default?  I'm running into issues with mappers using different imagery offsets and am hoping this could be an easy solution.  Maybe it should be built into iD rather than TM?

**Comment by xamanu** [comment]
Thanks @Geocruizer. This is a good feature request. Currently iD is not offering to pass variables for defining an offset, but it would be a good feature to add - I created an issue on the side of iD (https://github.com/openstreetmap/iD/issues/6999). Once iD supports it we can create the counterpart on the Tasking Manager.

**Comment by xamanu** [comment]
Just got feedback that iD does support an `offset=east,north` url parameter.
https://github.com/openstreetmap/iD/blob/master/API.md#url-parameters

**Comment by RAytoun** [comment]
Ouch! Would be a great idea but unfortunately due to the different orthocorrections across any one imagery tile the offsets will vary across the area so a single one-size-fits-all may be a problem in itself.

**Comment by xamanu** [comment]
Maybe this setting can only make sense when restricting the imagery layers available, as suggested in https://github.com/hotosm/tasking-manager/issues/1956 ?

**Comment by bopercival-hot** [comment]
stale and for previous tm version. Closed through gardening
