### ISSUE TITLE
isExpert vs expert_mode in user model

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1950]
Spotted 2 related fields in user model while reviewing #1913. This is misleading and looks like duplicate fields. 

cc @willemarcel @xamanu

**Comment by willemarcel** [comment]
`expert_mode` user field was added some months ago on https://github.com/hotosm/tasking-manager/blob/27c83b5f02eafab5150688dbd51dbbed8f55e7ec/migrations/versions/6612e4d6524c_.py
I don't remember why I asked for it on https://github.com/hotosm/tasking-manager/issues/1834

Should we delete it and update the code to use `is_expert`?

**Comment by ramyaragupathy** [comment]
Per chat w/ @willemarcel  we're going ahead `is_expert`. I will make a PR to remove the `expert_mode`
