### ISSUE TITLE
Deprecate tasks-assisted

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1954]
After launching TM4 the tasks-asissted instance shall be moved into the main HOT Tasking Manager:

* [ ] Export and import projects and tasks from Tasks-Assisted into HOT TM. Probably under a certain campaign and pointing to the RapiD editor.
* [ ] Redirect from tasks-assisted.hotosm.org to tasks.hotosm.org

**Comment by xamanu** [comment]
@ramyaragupathy, would it be feasible to import the projects first into TM3?

**Comment by ramyaragupathy** [comment]
Not relevant anymore
