### ISSUE TITLE
Review site structure

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1955]
The current structure and the one proposed for the redesign are not entirely consistent. Let's look again into this and come up with a good site structure for the Tasking Manager.

**Comment by xamanu** [comment]
@hexiaok has been creating some flow charts with a proposal for a new structure

![Tasking Manager IA -1-Non-logged-in-users](https://user-images.githubusercontent.com/97706/68197238-ccb1a800-ffb1-11e9-93c7-a27122621df0.jpg)
![Tasking Manager IA -2-Mappers](https://user-images.githubusercontent.com/97706/68197248-cfac9880-ffb1-11e9-90e4-1d439bea7226.jpg)
![Tasking Manager IA-3-Org-Admins](https://user-images.githubusercontent.com/97706/68197257-d509e300-ffb1-11e9-9508-28da00aa49bd.jpg)
![Tasking Manager IA -4-Hot-Admins](https://user-images.githubusercontent.com/97706/68197253-d2a78900-ffb1-11e9-8316-2b31945aae7b.jpg)

**Comment by xamanu** [comment]
Adding @willemarcel, to change the site structure when convenient. Thanks.

**Comment by willemarcel** [comment]
Looks perfect for me! Another entry point for teams will be on the `My teams` page. We are planning to add a section on that page that lists other teams.

**Comment by xamanu** [comment]
This looks like you completed it, @willemarcel. Can we mark is at `Done`?
