### ISSUE TITLE
Migrate organisations and campaigns

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1965]
We removed the migrations of content for organisations and campaigns from #1858 in #1961. Let's bring this back in a new migration, which includes a logic for consolidating several organisations with different names, such as HOT, HOTOSM, and Humanitarian OpenStreetMap Team.

This code snipped might be a good starting point:

```

    conn = op.get_bind()

    # Content migration: Migrate the campaigns tag in campaigns table
    campaigns = conn.execute(
        "select campaigns from tags where campaigns is not null"
    ).fetchall()

    # This will be used to consolidate the data in tags table
    dictionaries = {"HOTOSM": {"HOTOSM", "HOT-OSM"}, "ABC": {"abc", "ABc"}}

    for campaign in campaigns:
        result = campaign[0]
        for campaign_key, campaign_values in dictionaries.items():
            if campaign[0] in campaign_values:
                result = campaign_key

        query = "insert into campaigns(name) values('" + result + "')"
        op.execute(query)

    # Migrate the organisations tag in organisations table
    organisations = conn.execute(
        "select organisations from tags where organisations is not null"
    ).fetchall()

    # This will be used to consolidate the data in the tags table
    org_dictionaries = {"HOTOSM": {"HOTOSM", "HOT-OSM"}, "ABC": {"abc", "ABc"}}

    for org in organisations:
        result = org[0]
        if result.startswith("'") or result.startswith('"'):
            print(result)
            result = result[2:]
        for org_key, org_values in org_dictionaries.items():
            if result in org_values:
                result = org_key

        query = "insert into organisations(name) values ('" + result + "')"
        op.execute(query)
```

**Comment by willemarcel** [comment]
@xamanu Is there any block to push a solution to this issue?

**Comment by xamanu** [comment]
No blocker, but also not highest priority. This can be addressed while TM4 is in the testing phase.

**Comment by xamanu** [comment]
Quick update here:

* @ramyaragupathy has implemented a first logic for the migration https://github.com/hotosm/tasking-manager/pull/2260
* Currently, we are actively going through all the organizations and finding duplicates, grouping some of them, reaching out to contact persons, etc. This will take another week approx. Then we can continue here to bring this data in.

**Comment by xamanu** [comment]
@ramyaragupathy, please use the current state of editing for testing and completing the migration of organizations.

**Comment by ramyaragupathy** [comment]
Organisation migration 🚢  through https://github.com/hotosm/tasking-manager/pull/2260
Campaign migration is tracked here: https://github.com/hotosm/tasking-manager/issues/2612
