### ISSUE TITLE
Improve Sign Up process

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1975]
This issue is a second step of sign up process (see https://github.com/hotosm/tasking-manager/issues/1244 for previous reference)

* Split the sign up process in two parts. On the fist screen, the user will enter their email address, on the second, we will explain about why we use OSM authentication and ask them to create an account on OpenStreetMap.

<img width="765" alt="Screen Shot 2019-11-08 at 10 20 22 PM" src="https://user-images.githubusercontent.com/666291/68508877-57aece80-024e-11ea-97c1-def11a89ceaf.png">

* As on the OSM account registration, there isn't the possibility to redirect the user back to TM, I think a good solution would be to open the OSM website on another window or in a popup. That way TM can stay open on the user browser with the sign up modal showing a message like "click on the button when you finished the registration on OSM". That way, the user can give the permission to TM and finish the sign up process.

**Comment by willemarcel** [comment]
We could add some gifs giving more information on how to complete the sign up process. I took this idea from: https://www.holstee.com/pages/reflections-one-last-step

**Comment by xamanu** [comment]
We also need to include a sentence about why we are saving the email address and give a link to our privacy policy.

Further we should make sure the modal is being closed when redirecting to OSM. Thus the user finds the overall page, but not the open modal that want to lead to OSM again.

The error messages should become more visible - currently it is hard to see when you enter a already used email address, for example.

**Comment by xamanu** [comment]
This has been implemented and just checked. Will be merged and deployed in a little while. Thank you @JorgeMartinezG.
