### ISSUE TITLE
Update organisations list API

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1984]
Update `/api/v2/organisations/` endpoint https://github.com/hotosm/tasking-manager/blob/49861fe3ef64afa0c8b23d49dc99344c8ac25139/server/api/organisations/resources.py#L258

- [x] `managers` field is returning a null value, should return the usernames of the administrators/managers of the org. Actually the ideal would be having the pictureUrl too, like: `[{username: 'Admin_1', pictureUrl: null }, {username: 'B', pictureUrl: null }]`
- [x] restrict organisation creation to users with `admin` role

**Comment by willemarcel** [comment]
- [ ] allow admins to filter by managers `/api/v2/organisations/?managers=<uid>`
- [ ] allow logged in users to filter only with their own uid, with the same url param `/api/v2/organisations/?managers=<uid>`

**Comment by xamanu** [comment]
Assigning @fitoria, as he has been continuing on this issue. What is the current status here?

**Comment by fitoria** [comment]
Work in #2029
