### ISSUE TITLE
Validate all tasks of a specific user

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2017]
From the Tasking Manager User Group I would like to report back the feature request of being able to select all tasks mapped by one mapper for validation.

When validating a mapper's work, often times a certain mistake is made consistently by the same person in various tasks they might have mapped. As a validator it is useful being able to select all tasks of one person for validation.

**Comment by willemarcel** [comment]
It's missing only to change the validation page to allow the validator to set a status to each validated task
