### ISSUE TITLE
Add filters to team list endpoints

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2023]
We need to filter teams using some conditions:

- teams that a user is member
- teams that a user is manager
- teams that a user requested to join, but approval is pending
- by team name
- by team function

The two first filters are the most urgent.

**Comment by fitoria** [comment]
@willemarcel what do you mean by "by team function"?

**Comment by willemarcel** [comment]
The role field on the ProjectTeam model, @fitoria
