### ISSUE TITLE
API: User

### ISSUE THREAD

**Issue by d3netxer** [hotosm/tasking-manager#203]
There is a user api call. What does it return?

confirm if it includes at least:

- completed projects
- completed squares, invalidated squares, validated squares, along with timestamps
- user role: validator, etc.
- message history? (API auth)

**Comment by hunt3ri** [comment]
Hi @d3netxer 

The existing user API is in an early alpha state, it will be enhanced before launch to return the majority of the above :)

**Comment by hunt3ri** [comment]
Above info now available to users.
