### ISSUE TITLE
unable to validate

### ISSUE THREAD

**Issue by zorglubu** [hotosm/tasking-manager#2038]
Hello,

Despite the message "Keep up the validation! We need experts like you to help!", the validation task is denied every time I am trying a validation : "You do not have the required Validator role for validation on this project."
Is it a bug or is it just that I don't understand ? Thanks.
User https://tasks.hotosm.org/user/zorglubu

**Comment by RAytoun** [comment]
Hello zorglubu,
Thank you for your time and all the mapping you have done over the years. And thank you for your attempts at validating. Unfortunately not all mappers have your experience and we have had many beginners starting to validate on complex or urgent projects resulting in a lot of clean-up work at the end. This has resulted in some Project Managers restricting their projects to verified validators only to keep the standard up and reduce the amount of extra work at the end. We would very much like you to validate if you so wish and to that end please request a validator status at [http://bit.ly/HOTValidators ](http://bit.ly/HOTValidators) and there is an online validator training at 3:30 pm UTC on Thursday 12th December at [http://bit.ly/JOSMValidation](http://bit.ly/JOSMValidation) . I apologise about the validation note on the Tasking Manager, it seems this appears for all advanced mappers.
Look forward to adding you to the list of validators.

**Comment by zorglubu** [comment]
Thank you for your answer. 

I will apply ;-) 

Le 2019-12-09 00:00, Ralph Aytoun a écrit :

> Hello zorglubu,
> Thank you for your time and all the mapping you have done over the years. And thank you for your attempts at validating. Unfortunately not all mappers have your experience and we have had many beginners starting to validate on complex or urgent projects resulting in a lot of clean-up work at the end. This has resulted in some Project Managers restricting their projects to verified validators only to keep the standard up and reduce the amount of extra work at the end. We would very much like you to validate if you so wish and to that end please request a validator status at http://bit.ly/HOTValidators [1] and there is an online validator training at 3:30 pm UTC on Thursday 12th December at http://bit.ly/JOSMValidation . I apologise about the validation note on the Tasking Manager, it seems this appears for all advanced mappers.
> Look forward to adding you to the list of validators. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

 

Links:
------
[1] http://bit.ly/HOTValidators
[2]
https://github.com/hotosm/tasking-manager/issues/2038?email_source=notifications&amp;email_token=AHROM6BRQDKAZP4WUPAJSTTQXV4BZA5CNFSM4JYAWOX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGHMWAY#issuecomment-563006211
[3]
