### ISSUE TITLE
Problems running the task manager with docker

### ISSUE THREAD

**Issue by TAQ2** [hotosm/tasking-manager#2039]
Hello, I would like to start contributing to the front end of the tasking manager. When I loaded up the project following the docker instructions I get the following error:

```
[2019-12-09 13:20:51,205] ERROR in app: Exception on / [GET]
app           | Traceback (most recent call last):
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
app           |     response = self.full_dispatch_request()
```

macOS Mojave 10.14.5 (18F203)

Is this something that someone could help me with please?

**Comment by xamanu** [comment]
We checked on the docker install and also had a lot of people coming in for the GSoC programme. They were able to run the setup. Please join our chat hotosm.slack.org and ask in the #tasking-manager channel.
