### ISSUE TITLE
API: Project

### ISSUE THREAD

**Issue by d3netxer** [hotosm/tasking-manager#204]
In TM3 API there is a Search call (http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/api-docs/swagger-ui/index.html?url=http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/api/docs#/)

parameters for querying include:

- language
- mapper level
- mapping types (roads, buildings, etc)
- organization tag
- campaign tag

What is returned includes:

- project id
- locale (language, ex: en)
- name
- shortDescription
- mapper level
- priority
- aoi centroid
- organization tag
- campaign tag

** can we add author (or author_id) , date published, last modified, and who last modified it!? **

What else do we want? should metrics like show below be part of a separate stats API?

- % complete and validated 
- same data used to build the Activity and Stats tabs in TM2
- per square return square ID, state of square (not started, locked, started, validated, rejected)
- geojson of extents (options to just return project extent boundaries, grid along with Ids of each square, or center points; priority AOIs as well)

**Comment by harry-wood** [comment]
I guess that link was to a preview version of the API docs? These are [here now](https://tasks.hotosm.org/api-docs/swagger-ui/index.html?url=https://tasks.hotosm.org/api/docs#!/search/get_api_v1_project_search)

To update your notes here, currently it returns these fields in the response fields for a project:

* projectId
* locale
* name
* shortDescription
* mapperLevel
* priority
* organisationTag
* campaignTag
* percentMapped
* percentValidated
* status
* activeMappers

So this issues seems a bit out of date and maybe could be closed in favour of some more specific ideas.

I think "geojson of extents" is a idea worth expanding in another issue.

Also I would suggest a `mapResults=true/false` param, but again, I should describe that in another issue

**Comment by xamanu** [comment]
The requirements for changes on the backend for the redesign work will touch on this one.

**Comment by xamanu** [comment]
Related to #1856
