### ISSUE TITLE
CodeDeploy: Simplify Instance provisioning (AMI/Userdata)

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#2050]
The following changes need to be made on the `redesign/add-codedeploy` branch:

- [ ] Generalize AMI packer script for simplified infrastructure (i.e. we only need one AMI per application stack and it doesn't need to be generated often)
- [ ] Install CodeDeploy Agent along with all dependencies
- [ ] Remove unnecessary code from CloudFormation Template LaunchConfiguration UserData property. 
- [ ] Parameterize ImageId, 

When working with autoscaling groups, we should follow this guide: https://docs.aws.amazon.com/codedeploy/latest/userguide/integrations-aws-auto-scaling.html especially for installing the CodeDeploy Agent.

I am still a little unsure of how the initial revision is deployed- I don't think it's something we can back into Cloudformation. We use CircleCI to deploy further application revisions however. Thoughts?

**Comment by xamanu** [comment]
Increasing priority here.

**Comment by eternaltyro** [comment]
Steps to cover for full CodeDeploy setup: 

- [ ] Instances need to have IAM roles attached to be able to connect to CodeDeploy
- [ ] Build steps for frontend

I will keep updating this comment to enumerate more steps needed for CodeDeploy

**Comment by eternaltyro** [comment]
Database migrations need to be run from just one instance per deployment. There are some approaches to handling this:

- Use an external cache and store the state of migration there
- Use an external queue that will hold the job
- Update a custom db in PostgreSQL DB to update timestamp or CodeDeploy Deployment ID
- Read from mutable parameter that is updated once migration is run 


**Ref:**
https://serverfault.com/questions/894992/running-a-codedeploy-hook-on-just-one-instance-in-a-group

**Comment by eternaltyro** [comment]
Hitting this bug pretty often: https://github.com/aws/aws-codedeploy-agent/issues/185

**Comment by eternaltyro** [comment]
@dakotabenjamin can we obsolete this since we are going to be using Terraform?
