### ISSUE TITLE
Permissions and bugfix to some tasks endpoints

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2056]
- [ ] require authentication on `/api/v2/projects/{project_id}/tasks/queries/own/mapped/`
- [ ] fix swagger docs and verify if `/api/v2/projects/{project_id}/tasks/queries/aoi/` is working properly - (I tried to pass the project_id, but it failed for me)

**Comment by ramyaragupathy** [comment]
`/api/v2/projects/{project_id}/tasks/queries/own/mapped/`

* This API is used in the project activity and stats section which can be accessed even without login. 
* Returns an array of users who have mapped a task for the project along with details and counts of tasks mapped.
```
{
		"username": "randomuser",
		"mappedTaskCount": 1,
		"tasksMapped": [239],
		"lastSeen": "2019-12-11T14:48:45.793941",
		"mappingLevel": "ADVANCED",
		"dateRegistered": "2017-08-21T09:08:17.945201",
		"lastValidationDate": "2019-10-03T07:30:48.445137"
	}
```
* /tasks/queries/own/mapped/ is misleading instead updating this to /tasks/queries/mapped/ to reflect the purpose

`/api/v2/projects/{project_id}/tasks/queries/aoi/`
* I've verified that the function in develop branch is the same as the working piece in master. So this should work as usual without any issues.
