### ISSUE TITLE
Check for locked tasks across all Projects

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2063]
`/api/v2/projects/{project_id}/tasks/queries/own/locked` checks for tasks locked by user for a particular projects. So if I lock a task for mapping/validation in one project and try locking another task in a different project, then the tool lets me do it which is a bug.

Ideally endpoints should check for locked tasks across the entire TM instance than just one project.

cc @willemarcel @xamanu

**Comment by ramyaragupathy** [comment]
Also observed that:
* validation task lock follows the same behaviour
* a mapper can lock random tasks for mapping and validation within the same project and across projects 
eg: Lock task 1 for mapping under project 1. Now switch to validate tab and choose task 2 for validation in the same project 1. Task 2 is locked for validation - ideally, I feel this should not be allowed. 
Switch to project 2 and choose different tasks for mapping/validation. Now you've more than two tasks locked for mapping and validation simultaenously in different projects.

Suggest validation and map lock check should be such that a mapper can lock task(s) (multiple tasks allowed for validation) at a time for just one action - either mapping/validation. If I have already locked tasks for validation, TM should not let me lock other tasks for mapping and vice versa.

cc @willemarcel @xamanu

**Comment by willemarcel** [comment]
@ramyaragupathy I agree that we should implement that restriction to validation too.
