### ISSUE TITLE
Improve integration with AI-assisted mapping

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2065]
So far:

* We have piloted AI-assisted mapping with RapiD (https://github.com/hotosm/tasking-manager/pull/1550)
* and we are currently integrating iD into the Tasking Manager (https://github.com/hotosm/tasking-manager/issues/1358)
* people started using the custom editor field to point to RapiD on the main instance (https://github.com/hotosm/tasking-manager/pull/1924)

Let's think about making AI-assisted mapping a standard feature of Tasking Manager.

**Comment by jayenashar** [comment]
Is there documentation on how I can setup a tasking manager with RapiD?  Or migrate an existing tasking-manager?

**Comment by willemarcel** [comment]
@jayenashar Do you want to make RapiD your main editor or just give users the option to use it?

**Comment by jayenashar** [comment]
if there's no licensing issues, the main editor.

**Comment by willemarcel** [comment]
@jayenashar we are going to integrate RapiD inside TM on the next few months, for now I think you could:

replace `'?editor=ID'` by `'https://mapwith.ai/rapid'` on https://github.com/hotosm/tasking-manager/blob/fix/env-var-instructions/frontend/src/utils/openEditor.js#L18
and replace iD by RapiD on that line https://github.com/hotosm/tasking-manager/blob/develop/frontend/src/utils/openEditor.js#L18

Let me know if that solution works.

**Comment by jayenashar** [comment]
did you mean to paste a link to the same line in two separate branches?

**Comment by willemarcel** [comment]
@jayenashar sorry, the second link I pasted was wrong. I fixed it on my previous comment.

**Comment by willemarcel** [comment]
Actually, replace that line: https://github.com/hotosm/tasking-manager/blob/fix/env-var-instructions/frontend/src/utils/openEditor.js#L18

by:

```
const customUrl = https://mapwith.ai/rapid;
windowObjectReference.location.href = getIdUrl(project, center, zoom, selectedTasks, customUrl);
return '?editor=CUSTOM';
```

**Comment by willemarcel** [comment]
@jayenashar you'll also need to move that if statement to after the following one.

**Comment by jayenashar** [comment]
here's my diff:

```diff
diff --git a/frontend/src/utils/openEditor.js b/frontend/src/utils/openEditor.js
index 761ff3b2..6844b8e6 100644
--- a/frontend/src/utils/openEditor.js
+++ b/frontend/src/utils/openEditor.js
@@ -15,7 +15,12 @@ export function openEditor(
   }
   const { center, zoom } = getCentroidAndZoomFromSelectedTasks(tasks, selectedTasks, windowSize);
   if (editor === 'ID') {
-    return getIdUrl(project, center, zoom, selectedTasks, '?editor=ID');
+    if (windowObjectReference == null || windowObjectReference.closed) {
+      windowObjectReference = window.open('', `iD-${project}-${selectedTasks}`);
+    }
+    const rapidUrl = 'https://mapwith.ai/rapid';
+    windowObjectReference.location.href = getIdUrl(project, center, zoom, selectedTasks, rapidUrl);
+    return '?editor=CUSTOM';
   }
   if (windowObjectReference == null || windowObjectReference.closed) {
     windowObjectReference = window.open('', `iD-${project}-${selectedTasks}`);
```

it opens rapid but doesn't zoom to the task.  i was also a little confused by `windowObjectReference == null` since `windowObjectReference` is `undefined` not `null`

**Comment by willemarcel** [comment]
What's the URL it's generating?

If you want your users to use only Rapid, another solution would be to set a custom editor on all projects and activate only the custom editor on all projects.

**Comment by jayenashar** [comment]
looks like it opened this:

https://mapwith.ai/rapid?#map=NaN/NaN/-Infinity&comment=%23oceania-tm-project-1%20%23buildings&gpx=https%3A%2F%2Ftasks.smartcitiestransport.com%2Fapi%2Fv2%2Fprojects%2F1%2Ftasks%2Fqueries%2Fgpx%2F%3Ftasks%3D&presets=building

which redirected to:

https://mapwith.ai/rapid?#comment=%23oceania-tm-project-1%20%23buildings&disable_features=boundaries&gpx=https://tasks.smartcitiestransport.com/api/v2/projects/1/tasks/queries/gpx/%3Ftasks%3D&map=NaN/NaN/-Infinity&presets=building

and then:

https://mapwith.ai/rapid?#background=Maxar-Premium&comment=%23oceania-tm-project-1%20%23buildings&disable_features=boundaries&gpx=https://tasks.smartcitiestransport.com/api/v2/projects/1/tasks/queries/gpx/%3Ftasks%3D&map=NaN/NaN/-Infinity&presets=building

and i think finally stopped redirected on:

https://mapwith.ai/rapid?#background=Maxar-Premium&disable_features=boundaries&gpx=https://tasks.smartcitiestransport.com/api/v2/projects/1/tasks/queries/gpx/%3Ftasks%3D&map=2.00/-84.1/267.2&presets=building

**Comment by Aadesh-Baral** [comment]
Hello everyone, integration of RapiD inside TM is complete now. Integrated Rapid can be enabled while creating/editing a project on the settings tab.


![enabling_integrated_rapid](https://user-images.githubusercontent.com/67958673/167290174-8a34d8ba-bf54-4538-abc1-e16d16be9108.png)
