### ISSUE TITLE
Cannot archive project (table `project_priority_areas` has far more rows than expected)

### ISSUE THREAD

**Issue by taylorsmock** [hotosm/tasking-manager#2068]
The response from the request is `{"error": "Project GET - unhandled error: DELETE statement on table 'project_priority_areas' expected to delete 1 row(s); Only 132 were matched."}`.

https://tasks.hotosm.org/project/5354 -- I wanted to archive this project, which I did by logging in to the account that owns that project (KaartOSM), then going to the the edit-project page, changing the status to archived, and saving.

What I tried:
* Removing the priority area. It complains about a missing organizational tag, which I add, but it then brings up the same problem.

**Comment by ramyaragupathy** [comment]
Thanks for flagging the issue here @taylorsmock. This issue is related to #1789 - project archive is failing because of a duplicate priority area entry in Database for this project. This has been fixed through #1880 - fix will go live in V4 release

cc @xamanu

**Comment by ramyaragupathy** [comment]
Fixed through https://app.circleci.com/jobs/github/hotosm/tasking-manager/4819
