### ISSUE TITLE
CodeDeploy: CI/CD Workflow overhaul

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#2072]
Once an application stack is setup with CodeDeploy, new revisions can be pushed via CircleCI. We need to replace the `cfn-config update` commands with codedeploy revision push commands, and prepare for failures, etc. 

- [ ] replace cfn-config update with new flow 
    - upload files to s3
    - run codedeploy revision
- [ ] Implement deployment failure measures and fallbacks

**Comment by eternaltyro** [comment]
Basic Checklist:

- [ ] Instance profiles for backend VMs with permissions for CodeDeploy
- [ ] CodeDeploy agent installed on the backend VMs
- [ ] CodeDeploy AppSpec (fresh install) deployment
- [ ] CodeDeploy AppSpec update (repeat) deployment

**Comment by eternaltyro** [comment]
@dakotabenjamin can we obsolete this since we no longer plan on using CodeDeploy?
