### ISSUE TITLE
Check auto unlock function

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2108]
Per chat w / @willemarcel - figured out that the auto-unlock task functions waits for client-side command, ideally server should  handle the auto unlocks independently.

_Will add examples, just creating a ticket to capture consversation_

**Comment by willemarcel** [comment]
Some details:

The auto unlock tasks function is triggered by the GET requests on the project detail endpoint -> `/api/v2/projects/<id>/` (code: https://github.com/hotosm/tasking-manager/blob/develop/server/api/projects/resources.py#L112). I think that approach has some problems:

- The main problem is that executing that function on each GET project request can cause some performance issues, as if there are too many people accessing the same project, a query and some database operations are executed repeatedly at the same time.
- On the other hand, if nobody accesses the project, the tasks will continue locked.

I think the ideal solution would be to have that function running on the background at a fixed time interval.

Other possible solution would be to trigger that operation from different parts of the system, like after each task status change on the project, after each user login, when a user tries to lock a new task. That way, we avoid executing it so frequently, but run in a wide range of situations when it's really needed.
