### ISSUE TITLE
Test function is not running due to duplication

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2151]
[This test](https://github.com/hotosm/tasking-manager/blob/develop/tests/server/unit/services/test_project_service.py#L50) is not running because a test with the same name is on the line [111](https://github.com/hotosm/tasking-manager/blob/develop/tests/server/unit/services/test_project_service.py#L111).

**Comment by DeboDevelop** [comment]
Can I work on this issue?

**Comment by willemarcel** [comment]
@DeboDevelop yes, sure

**Comment by DeboDevelop** [comment]
@willemarcel Thanks a lot.

**Comment by DeboDevelop** [comment]
Please check the pull request  #2381 .

**Comment by DeboDevelop** [comment]
@willemarcel Sir, any tips on how to solve this?

I changed the name of the method but that wasn't enough.

I think these 2 lines summarise it,

`    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgresql" to address: Name or service not known`

`    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgresql" to address: Name or service not known`

[https://docs.sqlalchemy.org/en/13/errors.html#error-e3q8](https://docs.sqlalchemy.org/en/13/errors.html#error-e3q8)

It failed to connect to the database.

**Comment by accakks** [comment]
Hi @willemarcel , I am an Outreachy Applicant. Is this issue unassigned as of now?

**Comment by willemarcel** [comment]
@accakks yes, we don't have anyone working on it now

**Comment by xamanu** [comment]
https://github.com/hotosm/tasking-manager/pull/2504

**Comment by Aadesh-Baral** [comment]
Closed by #5129
