### ISSUE TITLE
TM4 console errors on home page

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2157]
Noted the following console errors while loading https://tm4.hotosm.org:

`Mixed Content: The page at 'https://tm4.hotosm.org/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://tm4.hotosm.org/api/v2/projects/queries/featured/'. This request has been blocked; the content must be served over HTTPS.`

`SyntaxError: Unexpected token < in JSON at position 0` at `stats.js: 69`

cc @willemarcel

**Comment by ramyaragupathy** [comment]
`Mixed Content: The page at 'https://tm4.hotosm.org/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://tm4.hotosm.org/api/v2/projects/queries/featured/'. This request has been blocked; the content must be served over HTTPS.` -  fixed through #2186

**Comment by ramyaragupathy** [comment]
Still seeing `SyntaxError: Unexpected token < in JSON at position 0` at `stats.js: 69`

**Comment by willemarcel** [comment]
@ramyaragupathy could you paste here the response you're getting on `/api/v2/system/statistics/`?
It's failing to respond on staging server and returning that error, but it works on my machine.

**Comment by ramyaragupathy** [comment]
Here you go @willemarcel 

```
{
    "mappersOnline": 77,
    "totalArea": 35201389.11327167,
    "tasksMapped": 2219998,
    "tasksValidated": 1140807,
    "totalMappers": 204760,
    "totalValidators": 9968,
    "totalProjects": 7233,
    "totalMappedArea": 8370361.934781266,
    "totalValidatedArea": 4211516.536374155,
    "totalOrganizations": null,
    "totalCampaigns": 0,
    "organisations": null,
    "campaigns": [
        {
            "campaign": "Unassociated",
            "projectsCreated": 7233
        }
    ]
}
```

**Comment by willemarcel** [comment]
It's not happening on production neither in staging.
