### ISSUE TITLE
Map centroid loading inconsistent

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2158]
Sometimes see the following message in the project load page within Chrome browser and the map centroid does not show up. I was able to see the centroid on the map once but after reload, there was no centroid and there was this console error.

``Error {message: "Input data given to 'tasks-centroid' is not a valid GeoJSON object."}
message: "Input data given to 'tasks-centroid' is not a valid GeoJSON object."
__proto__: Object``

**Comment by xamanu** [comment]
This has been merged. Let's see whether it is fixed. In the contrary case, please reopen.
