### ISSUE TITLE
Read more button visibility check

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2160]
For some projects `Read More` option is way below the text. Would like the alignment and the text height to be re-evaluated
![read-more](https://user-images.githubusercontent.com/12103383/72181339-1d5cdb80-340f-11ea-95ff-afb305e771ea.gif)
.

**Comment by xamanu** [comment]
Initially the design was meant to show the bottom bar as a fixed element. Now we are kind of squeezing  all the description text into this one little square. It would be good to have a more expandable space for the description and instructions. Let's think about it a bit.

**Comment by willemarcel** [comment]
Tested again in Safari, Chrome and Firefox and it works well if the window height is not lower than 630px. I'm very satisfied with its behaviour. Let me know if there is something we can do to improve.
