### ISSUE TITLE
Style learn and about page

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2162]
Text content looks cluttered in the about and learn page. Improvement and consistent styling needed for readability.

![image](https://user-images.githubusercontent.com/12103383/72181950-72e5b800-3410-11ea-8623-be1e3743b7b1.png)
![image](https://user-images.githubusercontent.com/12103383/72181990-88f37880-3410-11ea-802b-a06560a73064.png)

**Comment by JanviMahajan14** [comment]
Hi @ramyaragupathy . I am new to this project and looking forward to contribute in this project.
Can I take this issue?

**Comment by xamanu** [comment]
We have final drafts that are ready to be put into the suitable design:

* **About**:
  - [Content](https://docs.google.com/document/d/1raUGj_BNw0UjsQexlie0LKduTaWfHM1U6sRqCsXLyNI/edit#)
  - [Design](https://projects.invisionapp.com/share/WTRWOQ6Y6RQ#/screens/362688202)
* **Learn**:
  - [Content](https://docs.google.com/document/d/1FCN69EUvMDSbeXsSgZf3ky3gnobU2vXHL8vR-c3yHc8/edit#)
  - [Design](https://projects.invisionapp.com/share/WTRWOQ6Y6RQ#/screens/362222475)

**Comment by xamanu** [comment]
First PR for the about page #2519
