### ISSUE TITLE
Project card and map alignment on Explore Projects section

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2164]
Under `Explore Projects` we need to evaluate the spacing between the project cards and map section. 

![image](https://user-images.githubusercontent.com/12103383/72182614-d9b7a100-3411-11ea-92ed-ac80d062372a.png)

**Comment by ramyaragupathy** [comment]
Also there is a huge empty space beneath the map alongside project cards. Would be nice to have this behaviour redesigned - either have cards aligned here or adjust content to suit window size

![image](https://user-images.githubusercontent.com/12103383/72182973-afb2ae80-3412-11ea-9f95-2062cbacf5dc.png)

**Comment by thadk** [comment]
Hi @ramyaragupathy – the cards are pretty intricate but if someone can figure out a good way to solve this, more power to them. At smaller resolutions below the max-width of the cards, it does shrink them. That has its own issues though as "URGENT" gets off center. Remember to account for the organization logo which will appear soon on the top left.

**Comment by willemarcel** [comment]
I would prefer to make the map fill the space until the bottom of the page and then scroll only the section where the cards are located.

About the horizontal space, it will be a bit complicated, as @thadk mentioned, but we can try something soon.

**Comment by bopercival-hot** [comment]
closed - resolved.
