### ISSUE TITLE
Create Project: Define area page styling

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2169]
Noticed a gap between map and the next button, but this as adjusted after window resize. Also the checkbox for arbitrary tasks and the text looks a bit off.

![image](https://user-images.githubusercontent.com/12103383/72184860-6749bf80-3417-11ea-8fbe-b79e6db9213f.png)

**Comment by willemarcel** [comment]
@ramyaragupathy could you confirm if it's happening yet?

**Comment by NoemiNahomy** [comment]
@willemarcel This is no longer happening.
