### ISSUE TITLE
Notification Page: Search by Project 

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2171]
While doing project search in the notification page, it behaves like a normal text search, doing an API fetch for each character typed. It should take in `project` as query parameter instead of `text` and maybe pre-populate project IDs from the message object already sent to the client.

![notification-search](https://user-images.githubusercontent.com/12103383/72186034-46369e00-341a-11ea-96bf-08bfd158429d.gif)

**Comment by ritvikjain99** [comment]
@ramyaragupathy I think we should ignore the 'non-number' inputs. Shall I proceed like this ?
