### ISSUE TITLE
Notification Page: sort query parameter mixed up 

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2172]
Notification search by project and sorting works fine on the backend. But the frontend seems to be pick wrong parameters.

eg :`/api/v2/notifications/?sortDirection=asc` becomes `/api/v2/notifications/?sortDirection=projects&sortBy=ASC` from the client, so effectively the sorting doesn't happen

**Comment by ritvikjain99** [comment]
@ramyaragupathy Can I pick this up ?
