### ISSUE TITLE
Distinguish between actions and comments on My Tasks page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2177]
On My contributions page, if a user has only posted a comment to a task, it shows the text: "You worked on this task...". We should distinguish between task status changes and comments on this text.

**Comment by willemarcel** [comment]
@JorgeMartinezG @ramyaragupathy Currently on `/api/v2/users/{user_id}/tasks/` we don't have enough information to separate the tasks that received a status change action and a comment.

`{"tasks":[{"taskId":23,"projectId":1,"taskStatus":"READY","taskHistory":[],"taskAnnotation":null,"isUndoable":false,"autoUnlockSeconds":7200,"lastUpdated":"2020-02-27T09:42:53.240978Z"},{"taskId":38,"projectId":1,"taskStatus":"MAPPED","taskHistory":[],"taskAnnotation":null,"isUndoable":false,"autoUnlockSeconds":7200,"lastUpdated":"2020-03-27T11:27:02.709115Z"},]}`

On that case, for example, the first task received a comment and the second one was mapped by me.

**Comment by xamanu** [comment]
@JorgeMartinezG is going to do the backend change to expose through the dto the missing information.

**Comment by xamanu** [comment]
Closing as discussed in the dev meeting today.
