### ISSUE TITLE
Scroll task activity modal content div

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2180]
Assure that the last task activity is visible on the screen:

![image](https://user-images.githubusercontent.com/666291/72221169-a6bafd80-3536-11ea-9abb-fe493511804d.png)

Ps: On MacOS the scroll bar is not visible by default...

**Comment by ritvikjain99** [comment]
@willemarcel I wanna do this, it would be really good of you if you elaborate the desired behaviour!

**Comment by willemarcel** [comment]
the ordering of the actions was reversed on #2392, so it solves that issue
