### ISSUE TITLE
Imagery not handled the same in Tasking Manager as Editors

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#2209]
Scenario: If you put the TMS for ESRI World into a project (i.e. so it is loaded by default) then you cannot zoom in and get higher resolution tiles. If you then switch (in iD or JOSM) to the ESRI World imagery available in the editor, you can get the higher resolution tiles.

Question/Challenge: Is there something/what is, going on different between how the imagery is served to the editor from the Tasking Manager vs. straight from the editor.

This behavior makes it difficult for new mappers, and even more experienced, to know that they have to switch from the ESRI World they are given to that available in the editor. It also makes it difficult for project managers to decide whether to use the TMS 'auto-load' feature or just make note in the instructions.

Last, this only seems to be a problem with the ESRI imagery, but may exist with others.

**Comment by willemarcel** [comment]
@russdeffner could you paste a project link with that case?

**Comment by russdeffner** [comment]
@willemarcel https://tasks.hotosm.org/project/7446 - it is done, but if you do a 'second validation' on a task you should see the behavior.

**Comment by willemarcel** [comment]
@russdeffner The problem is that it's missing the `blankTile=false` on the imagery url. With it, it works well:

tms[22]:https://{switch:services,server}.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/{zoom}/{y}/{x}?blankTile=false

**Comment by russdeffner** [comment]
Ah, thanks @willemarcel but how are our project managers to know that? Is there some way the TM can 'recognize and fix' and/or warn if it's not there?  Or is this something we need to handle with training? My workflow is to copy the TMS from JOSM, and in at least the case of ESRI, the blankTile=false is not there. This is the first time I've heard of the fix and from the sounds of it, lots of people don't even realize what is happening, they just assume there's no higher resolution imagery.

**Comment by willemarcel** [comment]
That is a very specific problem with ESRI imagery and the blankTile param is not needed on JOSM (https://github.com/openstreetmap/iD/issues/4327). Although JOSM loads correctly if the url has the param.

A good possibility for the future would be to improve that imagery field on the projects in order to use the https://github.com/osmlab/editor-layer-index data.

@xamanu do you think we could do something immediately to handle this problem, like modify the code or update the urls on the database?
