### ISSUE TITLE
PATCH method on projects is not properly working

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2218]
The PATCH method should allow us to update any individual field on a project.

When I tried to update just these two fields: `{"restrictMappingLevelToProject": true, "restrictValidationRole": true}`, it failed with:

```
[2020-01-17 11:27:44,798] ERROR in resources: Error validating request: {"status": ["This field is required."], "projectPriority": ["This field is required."], "defaultLocale": ["This field is required."], "mapperLevel": ["This field is required."], "private": ["This field is required."], "taskCreationMode": ["This field is required."], "mappingEditors": ["This field is required."], "validationEditors": ["This field is required."]}
127.0.0.1 - - [17/Jan/2020 11:27:44] "PATCH /api/v2/projects/6/?projectStatuses=0 HTTP/1.1" 400 -
```

It's not blocking the project editing with the frontend because we are sending all the projects fields in the request, but we should make it work properly in the future.

**Comment by joaovitor3** [comment]
Can I work on this issue?

I looked at the `ProjectDto` and some fields are required, which causes failure after instantiating a `ProjectDTO` object as a result of its validations in the patch method.

I thought to create a new DTO with optional fields for the `patch` method, although I guess it's not the best for the architecture.

I believe the best solution would be to subclass the `ProjectDTO` class with its fields being optional, with some searches I wasn't able to know it's possible using `schematics`, do you guys could help me out with some suggestions?

**Comment by willemarcel** [comment]
@joaovitor3 yes, you can work on it. I don't have much knowledge about DTO's, probably @ramyaragupathy or @JorgeMartinezG can give you best instructions.

**Comment by JorgeMartinezG** [comment]
Yes. @joaovitor3 thank you for contributing to TM. My opinion to solve this taks involves two steps:
1. Modify the ProjectDTO to make fields not required: https://github.com/hotosm/tasking-manager/blob/develop/server/models/dtos/project_dto.py#L164
2. Then, we would include missing checkers within the project.py  update method: There is an example made for the org field: https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/project.py#L415
There should be a conditional per field

**Note.** One solution which reduces lines of code would be to get all fields that the dto has, an then iterate over each one and set the attribute in the project model. Such as:
```
# Need to parse de dto object to get an array of strings.
dto_keys = ['private', 'status'] 
[setattr(proj_obj, key, value) for key in dto_keys]

# Commit to the database.
db.session.commit()
```
This works for fields that do not need further process, i.e. private, status, etc.

Please, let me know your opinion, so we can iterate through this issue to get a good solution.

**Comment by joaovitor3** [comment]
Thanks @willemarcel  and @JorgeMartinezG for the quick answer!

I will try to apply all the changes pointed out by @JorgeMartinezG.
Any advance or questions I'll comment here

**Comment by joaovitor3** [comment]
I made some progress. I got stuck for some days, but I guess now it's ok for you guys to review my solution.

Following the @JorgeMartinezG suggestions, I updated the `ProjectDTO` fields to be optional, set the `ProjectDTO` attributes in the `update` method and add in `if` statement for each field. As seen in the sniped below.

```project_dto.py```
```py
# before
default_locale = StringType(
        required=True, serialized_name="defaultLocale", serialize_when_none=False
)

# after
default_locale = StringType(
        serialized_name="defaultLocale", serialize_when_none=False
)
```

```project.py```
```py
project_dto_data = self._get_project_and_base_dto()[1]
updated_fields = [key for key, value in project_dto.items() if value is not None and value]
[setattr(project_dto, key, value) for key, value in project_dto_data.items() if key not in updated_fields]

if project_dto.project_status:
            self.status = ProjectStatus[project_dto.project_status].value
```

All validations in the `updated_fields` line are necessary, due to some fields have the `False` and empty list values, which wasn't caught by the `if value` condition.

**Comment by joaovitor3** [comment]
Just opened the [Pull Request](https://github.com/hotosm/tasking-manager/pull/2418).

**Comment by bopercival-hot** [comment]
resolved
