### ISSUE TITLE
Bring back activity and stats page

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2244]
For TM4 we need the [activity and stats page](https://tasks.hotosm.org/project/7444/dashboard) back.

It shall large be the same as in TM3, but with a few review and enhancements:

* Add the stats page as a tab: https://github.com/hotosm/tasking-manager/issues/683
* Add provided enhancements for TM3: https://github.com/hotosm/tasking-manager/pull/1631
* Add task links to most stats: https://github.com/hotosm/tasking-manager/issues/630
* Add time details to stats page: https://github.com/hotosm/tasking-manager/issues/1846
* Consider adding some more improvements: https://github.com/hotosm/tasking-manager/issues/1382

**Comment by willemarcel** [comment]
so I just checked the current TM3 stats page... It's made of 

- last activities
- contributors list (with number of tasks mapped/validated
- completeness stats
- task comments

My proposals:

- The last activities are present on the task selection page (the list shows basically it)
- The contributors list could be a tab on the project selection page, allowing the user to easily filter the tasks mapped by user
- The completeness stats are available on the project detail page, but I think we could include it somewhere on the task selection page (probably close to the project name)
- About the task comments, I'm not sure how useful it is... does the project manager receives notification for each task comment? Maybe a view similar to the current My contributions page, listing the comments of all tasks (I don't even know if we have this available on our TM4 API).

**Comment by xamanu** [comment]
Yes, I think this is a good approach, we don't have to duplicate too much information.

So, besides a section for the contributors, I'm seeing the activity list a bit more powerful than what we have in the task list, that allows only looking at one status, but not inspect all status changes. Especially thinking about how power users are using this (compare with https://github.com/hotosm/tasking-manager/issues/1360).

I also have my doubts about the requirement of the comments table. Let's look at the other parts with a higher priority.

![image](https://user-images.githubusercontent.com/97706/73011772-d60e1c00-3e0c-11ea-9cc1-3c1c2c7c0c9b.png)

I also think the video of Ralph will give us a bit more insight.

**Comment by willemarcel** [comment]
Almost everything was done by @JorgeMartinezG . It's missing only to add the progress bar to the task selection page.

**Comment by willemarcel** [comment]
Added the progress bar with https://github.com/hotosm/tasking-manager/pull/2312
