### ISSUE TITLE
Show task info when selecting on the map

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2245]
When selecting a task on the map in the project view. The left side shows the list of tasks. Please make the TM switch to task details when clicking on the through the map. The overall list shall still be available through the tabs.

**Comment by willemarcel** [comment]
@xamanu I think that PR https://github.com/hotosm/tasking-manager/pull/2430 helps a lot on this issue. Let's get some feedback from users to define if we really need to add a task info tab.
