### ISSUE TITLE
Fix notifications page

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2247]
I just observed some issues on TM4 with the notifications:

![image](https://user-images.githubusercontent.com/97706/72440716-4380d380-37a1-11ea-9754-69ad67e95588.png)

* [ ] Instead of showing the username it shows some id, when the notification reaches the same user who made the comments
* [ ] Avoid sending a notification if you comment on your project
* [ ] Redirect to notifications page after delete a notification

**Comment by thadk** [comment]
@xamanu I suspect those are back-end bugs but I don't have relevant notification data in my own backend to test. Can you share the JSON response from the notification API from your dev tools?

**Comment by willemarcel** [comment]
> Instead of showing the username it shows some id

I'm noticing that problem as well.

- The backend is creating a message to notify the same user that posted the comment (what is not useful...)
- The problem with the id instead of the user name is on the backend as well

On the frontend we need to replace the username (`@[username]`) on the message body by the user page link and format it as `@username`.

**Comment by ritvikjain99** [comment]
@willemarcel I can do this !

**Comment by xamanu** [comment]
Some more good input from the testers:

> I noticed that when deleting notifications I get redirected to the home page instead of staying 8n the notification page. Also, when new notifications come in there is no indicator showing that there are new notifications. An orange bubble or new notification count would be useful.

**Comment by xplora1a** [comment]
Also having this. This might be sensible in the event of the last notification is deleted, but it also happens if I have remaining messages.

**Comment by xamanu** [comment]
Fixed with #2623
