### ISSUE TITLE
Change count logic on /api/v2/projects/{id}/contributions/queries/day/

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2251]
I was testing the map all, invalidate all, validate all and reset all functions on this project. So I mapped all one time, invalidate them, then mapped all, validated all and then reset the status of all tasks to ready to map. This endpoint `/api/v2/projects/{id}/contributions/queries/day/` is returning that result:

` {"stats": [{"date": "2020-01-24", "mapped": 224, "validated": 224, "cumulative_mapped": 224, "cumulative_validated": 224, "total_tasks": 112}]}`

We should count the number of tasks that were mapped/validated, not the number of state changes on the tasks.

**Comment by joaovitor3** [comment]
Hi
I'm trying to start contributing to the project, could I pick this issue or this is too hard for a new contributor?

**Comment by willemarcel** [comment]
@joaovitor3 welcome to tasking manager!

Maybe it's a bit complex to understand the tasks history... I think those two issues would be better for a new contributor:

- https://github.com/hotosm/tasking-manager/issues/2132
- https://github.com/hotosm/tasking-manager/issues/2047

**Comment by joaovitor3** [comment]
Thanks for the quick response @willemarcel, I will look at these two issues.

About being a new contributor, I would like to enter the HOT slack chat as mentioned in the [working groups section](https://github.com/hotosm/tasking-manager/blob/develop/docs/working-groups.md), but after answering the form and receiving the link to access the channel, the [invitation link](https://hotosm.slack.com/join/shared_invite/enQtNDkyMDA4MjQ1MDEyLWNmMjU4ZmEyNzI5MTc2MmJkODU5ZTA0ZmFhYWMwZmYyZjdhYThkMTI2OWJjNDZmMTlhMjBlYzYwMjdmYjNjZDg) does not seem to be active.

Am I doing something wrong? If not, should I open an issue about it?
Thanks for the feedback

**Comment by willemarcel** [comment]
@joaovitor3 could you try to register again at http://slack.hotosm.org/? The invitation link has been updated.

**Comment by joaovitor3** [comment]
I tested the new link and it's properly working.

I am already in the hot slack chat, thanks!

**Comment by willemarcel** [comment]
Another problem I noticed on tm4 instance:

On that project: https://tm4.hotosm.org/projects/18, the contributions chart shows almost 50% of mapping completion, but we only have 17 tasks mapped and 1 validated.

This is the return of the `/api/v2/projects/{id}/contributions/queries/day/` endpoint

`{"stats": [{"date": "2020-03-03", "mapped": 144, "validated": 6, "cumulative_mapped": 144, "cumulative_validated": 6, "total_tasks": 295}, {"date": "2020-03-04", "mapped": 4, "validated": 0, "cumulative_mapped": 148, "cumulative_validated": 6, "total_tasks": 295}]}
`

**Comment by NoemiNahomy** [comment]
Another problem: 
in the result of the api `/api/v2/projects/`  of the `percentMapped` field for its calculation discounts the `task_bad_imager` from `total_task` 
However, for contributions timeline (`/api/v2/projects/{id}/contributions/queries/day/`) this field `task_bad_imager` it's not discounted from `mapped`, so the mapped percentage are different.
