### ISSUE TITLE
Update project mapping/validation permissions

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2254]
With the introduction of teams and organisations, we need to change the logic that defines if a user can map or validate a project. My proposal is:

- For **private projects**:
  - Furthermore the list of users, consider also the project's team members.
- For **public projects**:
  - Consider all the current permissions (level, validator role, etc)
  - Add permissions to map to the users that are part of a mapper team
  - Add permissions to validate to the users that are part of a validator team

**Comment by xamanu** [comment]
Thanks for setting this up, @willemarcel and @ramyaragupathy for starting to work on the backend.

Three comments:

1. I would not do different permission systems between private and public teams. This increases complexity and the direct benefit is not clear to me.
2. I would add permissions to project manage a group by team as well. It has been quite e comment request for people to be able to share the project mangement with a group of people, for review by them, or for latest changes in a mapathon by the instructors present, e.g.
3. And we can consider dropping the current permission roles. But I would not make this part of this issue and we could also deprecate them in a version to come.

**Comment by willemarcel** [comment]
@xamanu yes, private teams should work the same way. I was referring to private projects.

The project editing permissions changes are in another issue: https://github.com/hotosm/tasking-manager/issues/2099

About dropping the current permission roles, I think we need a transition time and that transition would be natural as users would be joining teams and we won't give `validator` roles to anyone else. I think it would cause too much trouble if we do a hard transition.

**Comment by qeef** [comment]
> Add permissions to map to the users that are part of a mapper team
> Add permissions to validate to the users that are part of a validator team

This means that only one team of mappers/validators is possible for a project?

**Comment by willemarcel** [comment]
@qeef no, we allow unlimited teams for each role
