### ISSUE TITLE
Include project status in project/search API

### ISSUE THREAD

**Issue by Sanych** [hotosm/tasking-manager#2256]
Is it possible to include project status(active, archived, etc) in `mapResults` returned by v1/project/search api?

We use this api to obtain projects for disaster.ninja app. And we would like draw archived projects in different color.

**Comment by ramyaragupathy** [comment]
`https://tasks.hotosm.org/api/v1/project/search?mapperLevel=BEGINNER&page=1` returns an object with 2 k-v pairs. First one `mapResults` has all the project centroids for the search results from the query and then the `results` key holds the first 14 projects in an array, with each array holding metadata on projects including `status`:

```
{
		"projectId": 6149,
		"locale": "en",
		"name": "Espinar, Peru - Women Connect Challenge",
		"shortDescription": "Peru has a very unequal society, and whilst parts of Peru are well mapped, these tend to be urban, wealthy areas that reflect the inter-sectional power relations at play in the country. GAL School Peru is working with schools and universities to identify under-represented social issues, and then investigate, map and share them with state organisations and promote change.",
		"mapperLevel": "BEGINNER",
		"priority": "HIGH",
		"organisationTag": "Gal School Peru",
		"campaignTag": "Women Connect Challenge",
		"percentMapped": 98,
		"percentValidated": 99,
		"status": "PUBLISHED",
		"activeMappers": 1
	}
```

Please let me know if this is what you're looking for, else we can discuss more.

**Comment by Komzpa** [comment]
Hi @ramyaragupathy, is there a way to bypass pagination to get everything in single query?

**Comment by ramyaragupathy** [comment]
If it is just the project centroids and ID then `mapResults` should help - else if you're looking for more data for each project then I don't see a way to bypass pagination

**Comment by Sanych** [comment]
Hello @ramyaragupathy.

In order to reduce amount of requests to TM API we collect and store in cache all project ids and centroids few times per hour to show it on a map. And we want to separate archived projects from others. I've found a workaround by making two requests to the API, one with projectStatuses=ARCHIVED and one without. Thus I can define archived projects. But I don't know whether you have other statuses for the projects and I'm not able to define them.

**Comment by ramyaragupathy** [comment]
@Sanych - good to know your use case. Available project statuses - PUBLISHED, ARCHIVED, DRAFT
* By default search endpoint returns PUBLISHED projects
* when `status=ARCHIVED`, PUBLISHED + ARCHIVED projects are returned. I assume you do a diff between the two results to find out ARCHIVED projects
* You could do `status=ARCHIVED,DRAFT` to fetch PUBLISHED, ARCHIVED & DRAFT projects all  together

**Comment by Komzpa** [comment]
Here's example how it works live: https://disaster.ninja/live/#overlays=hotActivations,alert-shape,bivariate-custom_kontur_openstreetmap_quantity,osm-users;id=GDACS_TC_1000651_6;position=49.25255234926976,-19.228501138463386;zoom=8.500630348669958

**Comment by bopercival-hot** [comment]
stale issue, closed
