### ISSUE TITLE
for JSOM remote control settings, make type 'tms'

### ISSUE THREAD

**Issue by d3netxer** [hotosm/tasking-manager#2268]
I am having trouble getting my TMS links to work in JOSM through the HOT TM.

I am trying to debug, and I see that the HOT TM is using this url to communicate to JOSM's remote control:
```
http://127.0.0.1:8111/imagery?title=Tasking%20Manager%20Imagery%20-%20%237846&type=htt&url=https%3A%2F%2Fcog.ittc.state.gov%2Ftiles%2F%7Bz%7D%2F%7Bx%7D%2F%7By%7D.png%3Furl%3Dhttps%3A%2F%2Flib.ittc.state.gov%2Fuliastai_29jan20_ge1_cog.tif
```
It is not working, but I was debugging and found out it works if I change the type from 'type=htt' to 'type=tms'. I'm sure why type is htt. Can you please take a look? @willemarcel ?

I see the code that does this here: https://github.com/hotosm/tasking-manager/blob/923c76bb64c00bd54439b5beabedc4b3512c822d/frontend/src/utils/openEditor.js#L110

This is the draft project I created to test the TMS: https://tasks.hotosm.org/project/7846?task=125

**Comment by willemarcel** [comment]
@d3netxer Could you try to edit your project and set the imagery as `tms[1,22]:https://cog.ittc.state.gov/tiles/{z}/{x}/{y}.png?url=https://lib.ittc.state.gov/uliastai_29jan20_ge1_cog.tif`? I think it will work after that change.

JOSM supports only tms and wms types and we get that value from the imagery URL.

**Comment by d3netxer** [comment]
I just wanted to let you know @willemarcel that using the tms prefix as you suggested worked for me. Thanks for you help.
