### ISSUE TITLE
Restructure 'My contributions' section

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2275]
- My contributions nav bar link should open the current user detail page (the url could be `/contributions/` or `/users/:username/`)
- In the case the current user is seeing the details of themselves, we show a submenu like this above the `HeaderProfile`: 
![image](https://user-images.githubusercontent.com/666291/73682984-32d8c480-46a0-11ea-8615-707889b4dedc.png)
with the links My projects, My tasks, My stats
  - when we click on My project, load the content of `/manage/projects/` with that `HeaderProfile`
  - when we click on My tasks, load the current content of `/contributions/` with that `HeaderProfile`

**Comment by JorgeMartinezG** [comment]
@willemarcel Where would the **my stats** link redirect?

**Comment by willemarcel** [comment]
My stats would be the user detail page, we can make it the default of this section so changing the order to: My stats, My projects, My tasks
