### ISSUE TITLE
Add custom editor fields to project edit page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2301]
Allow the users to set a custom editor name, description and url in the settings project editing page.

**Comment by xamanu** [comment]
@willemarcel has this already been resolved with https://github.com/hotosm/tasking-manager/pull/2238?

**Comment by willemarcel** [comment]
@xamanu no, I enabled to select custom editor if the project has already one set on the database, but it's missing to update the project edit form to add the custom editor fields
