### ISSUE TITLE
API Profiling

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2303]
From our backend:

* Identify bottlenecks 
* Slowest endpoints 
* Most frequently called endpoints?
* What causes slow endpoints? 
* How much time does a specific request take?

**Comment by dakotabenjamin** [comment]
We enabled Performance Insights on the TM3 database and found two queries that played a significant role a recent incident where the database instance was running at 100% CPU. 

![Screenshot_2020-03-25 RDS · AWS Console](https://user-images.githubusercontent.com/1847818/77592585-d9835980-6ec8-11ea-9d87-75d2d41fa807.png)
```
SELECT task_history.id AS task_history_id, task_history.task_id AS task_history_task_id, task_history.action AS task_history_action, task_history.action_date AS task_history_action_date, task_history.action_text AS task_history_action_text, users.username AS users_username FROM task_history JOIN users ON users.id = task_history.user_id WHERE task_history.project_id = ? AND task_history.action != ? ORDER BY task_history.action_date DESC LIMIT ? OFFSET ?

SELECT count(*) AS count_1 FROM (SELECT task_history.id AS task_history_id, task_history.task_id AS task_history_task_id, task_history.action AS task_history_action, task_history.action_date AS task_history_action_date, task_history.action_text AS task_history_action_text, users.username AS users_username FROM task_history JOIN users ON users.id = task_history.user_id WHERE task_history.project_id = ? AND task_history.action != ?) AS anon_1
```

My current theory is that as http requests to the server increased, the number of backend servers also increased, up to 12. This led to a non-linear increase in requests to the database and a positive feedback loop occurred. It would be good to determine which endpoints these SQL queries are connected to, and whether they are still present in the TM4 backend.

**Comment by ramyaragupathy** [comment]
@NoemiNahomy -  is working on setup a profiler using jupyter notebook.

**Comment by NoemiNahomy** [comment]
- I updated the ERD model until la version 4.0

- Add notebook profiler to jupyter to measure api response times https://github.com/hotosm/tasking-manager/pull/3054

**Comment by NoemiNahomy** [comment]
The API response time [report](https://github.com/hotosm/tasking-manager/blob/feature/add-notebook-profiler/scripts/profiler/projects.ipynb) answers the following questions:

- Identify bottlenecks

- Slowest endpoints

- How much time does a specific request take?
