### ISSUE TITLE
Task history doesn't register unlock actions

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2308]
Lock a task for mapping, then use the `/actions/stop-mapping/` endpoint (or the frontend) to unlock the task. When we check the `/api/v2/projects/<id>/tasks/<id>/` endpoint, there is only a `LOCKED_FOR_MAPPING` entry on the `taskHistory`, but there is no information that the user has unlocked it.

Reported by @zlavergne

**Comment by ramyaragupathy** [comment]
When a task is unlocked - that task's LOCKED_FOR_MAPPING history entry is updated with the duration for which the task was locked(`action_text` field). `action_date` stores the timestamp when the task lock was initiated. Maybe we could use these two fields - duration locked and action initiated timestamp - to arrive at the unlock timestamp for history summary on the frontend.

**Comment by xamanu** [comment]
This is related to #2781
