### ISSUE TITLE
[BUG]: Project search.

### ISSUE THREAD

**Issue by ritvikjain99** [hotosm/tasking-manager#2332]
__BUG__:
When you search projects, wireframes are mounted and then unmounted with splash.
__IDEAL BEHAVIOUR__:
There shouldn't be any activity if there aren't any results.
![hot1](https://user-images.githubusercontent.com/34532173/74671655-abc43a00-51d1-11ea-9d5b-f24086ce9997.gif)

**Comment by bopercival-hot** [comment]
Issue no longer exists.
