### ISSUE TITLE
 Edit buttons on project page

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2336]
Add an edit buttons for people with the permission to go to the edit form of a project from the main project page and tasks view.

**Comment by willemarcel** [comment]
Together with this, let's check if the user has permission to edit a project and only allow access to the project editing page to allowed users.

**Comment by xamanu** [comment]
Needs to check, if a user is:

* Super admin
* Organisation admin (of the org related to one project)
* Is part of a project manager team

These checks are a bit more complex, right @willemarcel? Because we either do them on login (when we already do a lot of requests or when loading the project, which is already hitting the db quite hard, too)

**Comment by xamanu** [comment]
Rising priority, as this is an essential component of the teams functionality.
