### ISSUE TITLE
[BUG]: Loss of options on screen resize.

### ISSUE THREAD

**Issue by ritvikjain99** [hotosm/tasking-manager#2346]
__BUG__:
When we resize screen, some links like 'language', 'Explore Projects', 'filter' vanish completely, which means if user opens these pages with this screen width he would be deprived of navigations to the related pages.
__ADDITIONAL CONTEXT__:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34532173/74740938-e4bbe780-5281-11ea-8913-284705e7c919.gif)

**Comment by willemarcel** [comment]
@ritvikjain99 The burger menu has all the links, except the language selector. The filters go inside the sidebar. If you have some improvement proposal, let us know.

**Comment by ritvikjain99** [comment]
@willemarcel the burger menu in my case only has two options 'signup' and 'login' on both the pages. 
It doesn't have the disappeared links.
Please correct me if I am wrong !

**Comment by willemarcel** [comment]
@rightway1 I can see the explore projects button inside the burger menu. If I'm logged in, the other links show up there too.

**Comment by ritvikjain99** [comment]
@willemarcel might be due to incomplete setup. Sorry for inconvenience!
