### ISSUE TITLE
Review some details on project creation

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2349]
Some feedback from testing for improving the project creation:

* [x]  Allow to modify the polygon of an AoI in the project creation step, after drawing the points. (As is behaves in TM3).
* [ ] Add indication that you need to or how to "close" the polygon. It would be nice if each node was rendered and the start/end node was colored distinctly.
* [x] Rename "interests" in projects into "categories".
* [x] Check on teams dropdown list, whether it appears behind toggle on project edit page in "Permissions" tab

**Comment by willemarcel** [comment]
- The third item is fixed with https://github.com/hotosm/tasking-manager/pull/2369
- The last item I fixed some days ago

**Comment by xamanu** [comment]
* The first item is fixed with #2438
