### ISSUE TITLE
[BUG]: Search task by project id.

### ISSUE THREAD

**Issue by ritvikjain99** [hotosm/tasking-manager#2358]
__BUG__:
As we are supposed to enter an integer value in 'project id' placeholder on '/contributions/tasks', if I enter any non-integer value the error thrown is unhandled and the component explodes.
@willemarcel please correct me if I am wrong !
I wanna work on this issue and it would be really helpful if someone guides me how to startoff !

**Comment by willemarcel** [comment]
@ritvikjain99 yes, this kind of error happens in most API endpoints and it would be really good if we could fix it. I can not guide you because I don't have knowledge about that part of the backend.

**Comment by ritvikjain99** [comment]
@willemarcel sure I would try my best !
