### ISSUE TITLE
experimental feature idea: machine learning estimated completeness

### ISSUE THREAD

**Issue by d3netxer** [hotosm/tasking-manager#236]
What if a machine learning algorithm could estimate missed buildings/roads/square on a per project and a per square basis; and these estimates could be displayed? It could help in the validation stage look for missed areas.

**Comment by ethan-nelson** [comment]
This idea is being actively pursued and the issue now is how it will be handled in the TM internally. Because of the awareness of this process, I am going to go ahead and close this broad ticket--but see #1284 for further information about implementation. Thank you for your input @d3netxer !
