### ISSUE TITLE
Organisation endpoint related

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2366]
* Summarising results from fetch all org endpoint. One that has a red circle has to be corrected

endpoint|authentication|user ID|current behaviour|expected behaviour
---------|--------------|-------|--------------|--------------
GET all organisations|no|no| all orgs DTO (manager list,picture url, org - name, log, url) 🔴 |return  all orgs w/o manager list
GET all organisations|no|yes|unauthorised access|unauthorised access
GET all organisations|admin|yes|org DTO (manager list,picture url, org - name, log, url) matching manager user ID|returns an org DTO (manager list,picture url, org - name, log, url) matching manager user ID
GET all organisations|admin|no|all orgs DTO (manager list,picture url, org - name, log, url) |all orgs DTO (manager list,picture url, org - name, log, url) 
GET all organisations|non-admin|yes|org DTO (manager list,picture url, org - name, log, url) matching manager user ID|returns an org DTO (manager list,picture url, org - name, log, url) matching manager user ID
GET all organisations|non-admin|no|all orgs DTO (manager list,picture url, org - name, log, url) |all orgs DTO (manager list,picture url, org - name, log, url)

~* When an organization is created, automatically the author becomes a manager. However, there is no entry made for this in `organisation_managers` table~

cc @JorgeMartinezG @willemarcel @xamanu

**Comment by NoemiNahomy** [comment]
Hi. Can i help with this task? This url  http://127.0.0.1:5000/api/v2/organisations/ should not leave the manager, right?

**Comment by xamanu** [comment]
This has been solved with #2547.
