### ISSUE TITLE
feature: share url for private project

### ISSUE THREAD

**Issue by d3netxer** [hotosm/tasking-manager#237]
Instead of having to input individual usernames to let them have access to a private project. Have an option to share a private link instead (ex. like sharing a link for a Google Doc).

**Comment by bgirardot** [comment]
Hi @d3netxer I am putting the 3.2 milestone on several of your suggestions because we will not be able to get them into the 3.0/3.1 release cycle, but I do not want to lose them.

**Comment by willemarcel** [comment]
TM4 sets project access based on teams.
