### ISSUE TITLE
Website shows projects with 100% completion of mapping/validation

### ISSUE THREAD

**Issue by DavidMetcalfe** [hotosm/tasking-manager#2372]
It appears that projects at 100% Mapped and 100% Validated still continue to show up. You can see an example with project #232 Monrovia Roads in the attached screenshot.

![image](https://user-images.githubusercontent.com/80915/75082883-a6fdcf80-54ca-11ea-818d-9f6c2c3b0d9f.png)

**Comment by xamanu** [comment]
This is actually the desired behaviour I think. Project managers can "archive" projects. We can consider to add a functionality that completed projects are marked as archived automatically.

**Comment by DavidMetcalfe** [comment]
@xamanu I spoke with Jessica Bergmann about this as well and she seems to be aligned on the general resolution to this one: "Currently, the functionality of the Tasking Manager requires project managers of the task to be the one to set the task as 'archived' once it's achieved 100% mapping and validation, which is why this task may still appear displayed. We're working to see if we can automate some of these processes in the new release of the Tasking Manager 4 to make it simpler for volunteers to find available mapping tasks."

Definitely looking forward to UI improvements to more easily surface available mapping tasks!

**Comment by bopercival-hot** [comment]
Issue is resolved in TM4
