### ISSUE TITLE
Instagram link in footer

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2377]

**Comment by ritvikjain99** [comment]
It would be really helpful if you elaborate !
PS: I suggest that the link should open in new tab.

**Comment by willemarcel** [comment]
@xamanu we already have the instagram link on footer

**Comment by xamanu** [comment]
Yes, unfortunately it links to YouTube.

**Comment by willemarcel** [comment]
So it should be an error on the environment variables. @dakotabenjamin, could you check it?

**Comment by eternaltyro** [comment]
There is an error in the environment variable. We need to rebuild the stack with the right variable.

**Comment by xamanu** [comment]
Just checked. This is done. Thanks.
