### ISSUE TITLE
Investigate TM4 login delay

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2382]
Currently, TM4 login takes a while - more than a minute- because there is a check to gather recent activities on the user's favorited and contributed projects. Instead of  having this coupled with login, should think of a better placement for this function

cc @willemarcel @JorgeMartinezG @xamanu

**Comment by willemarcel** [comment]
On tasks-stage server, it took 3 seconds to load `/api/v2/users/wille/openstreetmap/` and 2.5s to load 
`/api/v2/users/queries/wille/` . 

we are not using that information that comes with `/api/v2/users/queries/wille/`:
```
projectsMapped: 21,
tasksMapped: 62,
tasksValidated: 6,
tasksInvalidated: 0,
```

and that same information is available on `/api/v2/users/wille/statistics/` (it took 18 seconds to load).

**Comment by willemarcel** [comment]
I checked if we are using the data I highlighted on my previous comment when we fetch `/api/v2/users/queries/<username>/`... On the Welcome page, we are using the `tasksMapped` data, but we can get that information from other endpoint, so I think it's ok to remove those fields from that endpoint.

**Comment by willemarcel** [comment]
We removed only the projectsMapped. We could continue the work on https://github.com/hotosm/tasking-manager/issues/2003#issuecomment-591517060
