### ISSUE TITLE
101% completion reported

### ISSUE THREAD

**Issue by dstansby** [hotosm/tasking-manager#2385]
The project here: https://tasks.hotosm.org/project/7882 is showing up as 101% completed in in cards on https://tasks.hotosm.org/contribute?difficulty=ALL . I presume this is a bug, as it can't be possible to have > 100% completion.

**Comment by xamanu** [comment]
Hi, yes, thank you. We are close to get out TM4. Lets check when it is getting launched on the percentage numbers again.

**Comment by xamanu** [comment]
Hi, yes, thank you. We are close to get out TM4. Lets check when it is getting launched on the percentage numbers again.

**Comment by comradekingu** [comment]
Happened for a "mapathon" of https://tasks.hotosm.org/project/7032#bottom yesterday too.

**Comment by xamanu** [comment]
Still a case in TM4 after migrating the database. It might need a recalculation of the percentages on the backend and we need to observe if this occurs also with new projects in TM4.

**Comment by ramyaragupathy** [comment]
Modified the code for stats update on undo action - which resulted in percentage overshoot. Also DB updated through a special migration to correct task counts.

Current status on TM4:

![image](https://user-images.githubusercontent.com/12103383/81271715-19ae2e00-906a-11ea-8032-5ec0fc5d5116.png)

![image](https://user-images.githubusercontent.com/12103383/81271914-5a0dac00-906a-11ea-99b3-5a4ad5040a56.png)
