### ISSUE TITLE
Separate API Endpoint for `/projects` for editing/managing the project

### ISSUE THREAD

**Issue by zlavergne** [hotosm/tasking-manager#2393]
Currently there is a single `/projects/#` endpoint that's used any time we need project info. I'm thinking there should be a separate endpoint for the admin side that doesn't send the `tasks` object. In some cases it can be a hefty geojson and isn't used anywhere for project management. It also means we don't need to send the `tasks` when we save a project.

Mainly just an observation and not very critical 😃

**Comment by willemarcel** [comment]
@zlavergne have you tried to use the `/api/v2/projects/{project_id}/queries/summary/` endpoint? Maybe there are some fields missing there that we could add...

There are some problems with the PATCH method on projects (https://github.com/hotosm/tasking-manager/issues/2218), but it already possible to update the project without sending all the information.

**Comment by bopercival-hot** [comment]
stale, tm3 related, closed.
