### ISSUE TITLE
TM4 - https://tm4.hotosm.org/manage is broken

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/tasking-manager#2394]
Unable to view the 'manage' screen - getting a blank screen. Also having the same problem is @michael63-osm & raytoun. - all part of training team. Michael commented that it was working a couple of hours ago.

**Comment by Nick-Tallguy** [comment]
Have found that the menu items below https://tm4.hotosm.org/manage/ are accessible - for instance https://tm4.hotosm.org/manage/projects?mappedByMe=1 is a working link

**Comment by willemarcel** [comment]
@Nick-Tallguy thanks for reporting. We fixed it with https://github.com/hotosm/tasking-manager/pull/2369
