### ISSUE TITLE
Optimize cloud infrastructure for TM4

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#2431]
We can tackle this from two angles: locust.io, and [flask-profiler](https://github.com/muatik/flask-profiler)

Primarily I am looking to optimize the EC2 instance size and the RDS instance size. 

### Locust.io Load Testing
Following #1354 we should conduct a series of tests on an independent cloudformation stack using different EC2 instance sizes: `c5d.large` (current, compute-optimized), `m5n.large`, `t3.medium`, `t3.small` (general purpose) 

After EC2 optimization, we can look into how much we are able to scale down the RDS instance, which for `production` is currently `db.t3.2xlarge`. We can use a combination of locust.io and Cloudwatch monitoring for this step. 

### flask-profiler
The profiler tool will tell us
- Where are the bottlenecks in my application?
- Which endpoints are the slowest in my application?
-   Which are the most frequently called endpoints?
-   What causes my slow endpoints? In which context, with what args and kwargs are they slow?
-   How much time did a specific request take?
While this won't tell us much directly about the infrastructure needs, it will tell us where to look when we notice issues infrastructure-wise

**Comment by xamanu** [comment]
To be addressed after the public launch.

**Comment by qeef** [comment]
I am interested in the results of the load testing of TM4. I just created an issue in `tasking-manager-locustio-test` repository, see https://github.com/hotosm/tasking-manager-locustio-test/issues/1. Do you still use that repository for load testing?

**Comment by willemarcel** [comment]
@qeef probably the hotosm/tasking-manager-locustio-test is outdated as it was made to TM3. @NoemiNahomy built some profilers recently https://github.com/hotosm/tasking-manager/tree/develop/scripts/profiler

Some information about performance: we've had mapathons with up to 170 mappers recently.

**Comment by qeef** [comment]
Thanks, @willemarcel. I briefly checked https://github.com/hotosm/tasking-manager/tree/develop/scripts/profiler but didn't find any *mapping* endpoint there. So, in fact, mapping is not profiled? Also, it looks like it is for one user only.

About the performance -- 170 mappers is nice. Unfortunately, it says nothing. I would like to know the maximum and the average response time, the number of requests per second, and the number of errors for these 170 mappers. And also to the hardware/VPS configuration of the tested server and if it was a localhost test or testing over the Internet.

I think it would be interesting to know these numbers and it is inevitable to boost TM4 performance. Each time we organize mapathons, we have performance issues.

**Comment by eternaltyro** [comment]
Can this be closed as no longer needed @dakotabenjamin ?  Now that we have a clear containerisation roadmap, we can approach this issue again later.

**Comment by ramyaragupathy** [comment]
Closing this for now as it is part of containerisation workplan
