### ISSUE TITLE
Allow to drop import files on project creation

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2437]
When setting an AOI for a new project, allow the user to upload a file by just dragging and dropping it over the map.

**Comment by vvijayalakshmi21** [comment]
Hi, I am an Outreachy applicant and interested to contribute to this project. 
Kindly let me know how to get started.

**Comment by ritvikjain99** [comment]
Hey @vvijayalakshmi21, please join HOTOSM's slack channel #interns as the first thing to do :)
