### ISSUE TITLE
add anchors to each project create and edit sections

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2441]
Allow the users to navigate throw the project create and edit sections throw hash anchors. For example: `/manage/projects/2#description`, `/manage/projects/2#instructions`.

Assure that if the user press the back button after going to a second section the form data will not be lost and it will just enable the previous section.

**Comment by ritvikjain99** [comment]
@willemarcel I have solved this issue, just wanted to know that:
For the case when user enters an invalid anchor should I make a check function of something else ?

**Comment by willemarcel** [comment]
@ritvikjain99 no, if the anchor is unexisting, just load the first section

**Comment by ritvikjain99** [comment]
@willemarcel need your help here !
I want the code to trigger just on change in `props.location` but this __warning__ (which failed the tests) is ruining things and please suggest solution !
