### ISSUE TITLE
Replace old buildings video on Learn page with new one

### ISSUE THREAD

**Issue by aawiseman** [hotosm/tasking-manager#2444]
The buildings video at https://tasks.hotosm.org/learn is from the previous version of iD, this video is the more recent one https://www.youtube.com/watch?v=E1YJV6I_rhY

**Comment by xamanu** [comment]
Thanks, @aawiseman! I just opened a PR for TM3 on this. We are going to schedule a deployment next week to get it online.

**Comment by xamanu** [comment]
This is going to be deployed tomorrow.
