### ISSUE TITLE
User data moved over to another profile

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2447]
During the initial mapathon testing one bug was discovered, that looks similar to #1715:

> For a single user, when logged in, the name, gender, email address showed on his profile was the one of a different user. But the image was correct. No other users reported this issue.  After logging out and in again, the user still had the same problem.

**Comment by xamanu** [comment]
Wondering if this would be a solution: https://github.com/hotosm/tasking-manager/pull/1037

**Comment by xamanu** [comment]
This has happened only once so far. Lets continue testing and see another occurrence before addressing this with a bit more information about it.

**Comment by willemarcel** [comment]
@ramyaragupathy @JorgeMartinezG closing this as it seems to be solved with the improvements of the last weeks
