### ISSUE TITLE
colors on the project page

### ISSUE THREAD

**Issue by giblet22** [hotosm/tasking-manager#246]
Just watching through the walkthrough today. I think adding a fourth color  (the blue for locked) can be a bit confusing and so there is just a lot going on and a new mapper will keep having to go back and forth to the legend. 

What if `Locked` was a yellow border (as it currently is) and `Locked by Me` is a different border color like the blue that used in the version that was shown in the video.

**Comment by russdeffner** [comment]
Related: the legend does not have the 'selected' yellow boundary; typically a user is going to be selecting a single task and what they'll see is like so: 
![lockedbyyou](https://user-images.githubusercontent.com/6763645/32181042-18ddc1b6-bd59-11e7-8cb7-11983a43f610.PNG)
Would think we either need to add the yellow selected box to the legend or 'turn it off' once it goes from selected to locked. i.e. I have only briefly seen the dark blue border as it's usually hidden under the yellow one.

**Comment by xamanu** [comment]
Although this was the first issue on this, there are some ongoing conversations in #1257. I would like to close here as a duplicate and continue the discussion over there.
