### ISSUE TITLE
Come back easier to an open task

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2464]
Some feedback on coming back to a task when using an external editor:

> If you have closed a task in JOSM and returned to the Task update page, it’s not intuitive how to re-open the task (looks as if you have to use the ‘Start another editor’ link but this is not clear). Ideally would like ‘Reload task’ button.

and

> Under ‘MY CONTRIBUTIONS’ in the ‘My Tasks’ tab, the ‘Resume task’ link is visible only when you hover over a task. User suggested this should be permanently visible.

**Comment by willemarcel** [comment]
> Under ‘MY CONTRIBUTIONS’ in the ‘My Tasks’ tab, the ‘Resume task’ link is visible only when you hover over a task. User suggested this should be permanently visible.

We show the "Resume task" button to all task the user interacted, but stopped working. I think it will be very confusing having too many call to action on a page, but I think the suggestion makes sense if the task is yet locked by the user.
