### ISSUE TITLE
Consider allowing users to adjust the transparency of layer over map

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2468]
On the Contribute map, the transparency through the grid overlay is not great (i.e. it is not easy to see the underlying imagery; this could be useful for example if you are time-limited and looking for a task that has a small number of elements that you can complete or conversely if you are looking for tasks that have a lot of elements to map.

Consider allowing users to adjust the transparency.

**Comment by willemarcel** [comment]
@xamanu I have thought already about that, but I think it depends on having a more frequently updated basemap layer, otherwise it wouldn't be useful.

**Comment by xamanu** [comment]
Agreed. Closing here for now.
