### ISSUE TITLE
Show the task locked by a user on map

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2469]
Map in ‘Contribute’ page does not show ‘locked by you’ task, shows all locked tasks. If you are working on tasks in a particular area, seeing the one locked to you helps to manage your workload (e.g. if there are 3 unmapped tasks adjacent to the task locked by you, it would encourage you to map those).

**Comment by xamanu** [comment]
@willemarcel can you confirm this has already been done?

**Comment by willemarcel** [comment]
@xamanu no... we are not handling those details yet.
