### ISSUE TITLE
Email sending on TM4

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2472]
Currently the TM testing site is not sending emails.

**Comment by xamanu** [comment]
@dakotabenjamin @JorgeMartinezG can you have a look and check what is failing? Thanks.

**Comment by dakotabenjamin** [comment]
We use AWS Simple Email Service for sending mail to users. The credentials are set in Cloudformation, and they are the same across environments. In addition, I have noticed in the tm4 logs on CloudWatch that emails appear to be sent. It would be a good place to check there.

**Comment by JorgeMartinezG** [comment]
I tested in both tm4 and staging instances and got no errors related to messages. However, staging logs show jinja-related error for / endpoint. It is not related to email services

```jinja2.exceptions.TemplateNotFound: index.html```

**Comment by xamanu** [comment]
This has been checked. I sent out an email today, wasn't able to receive it. Will wait if anybody else got it.

**Comment by xamanu** [comment]
This has been addressed by #2584 and #2587. However it currently seems to open the email client. Which is not an expected behaviour. Can't we just send out the email?
