### ISSUE TITLE
Migrate validator role

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2474]
This is to deprecate the validator and project manager roles. Existing users shall be moved into a former validator and project manager team respectively.

* Move users from validators into standard group
* Move role of all users to mappers
* Remove validators role
----

* Move users from project managers into standard group
* Move role of all users to mappers
* Remove project manager role

**Comment by ramyaragupathy** [comment]
🚢 https://github.com/hotosm/tasking-manager/pull/2518
