### ISSUE TITLE
Redirect to project page after sign-up

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2505]
When a user starts from a specific project page and clicks sign-up, the project should be saved in the database (together with the other pre-saved data such as name and email) and after the first login the user should be redirected to this specific project.

The standard behaviour of the welcome page should persist, if a user comes from any other page, e.g. the explore project page. Then no redirect shall happen.

**Comment by ritvikjain99** [comment]
Can I take this?
