### ISSUE TITLE
TeachOSM TM: Change links and text from HOT to TeachOSM

### ISSUE THREAD

**Issue by geomantic** [hotosm/tasking-manager#2513]
What's the best way for me to edit the text on https://tasks.teachosm.org/about so that it points to TeachOSM rather than HOT? The TeachOSM instance is a direct fork of the HOT TM, but the text was never changed. Because of that, some community members are not aware that there are multiple working instances of the TM and send requests to HOT, rather than to TeachOSM. 

Please @ me w/ any response. TIA

**Comment by xamanu** [comment]
Hi, thanks for the inquiry. You can change the text directly in code and adapt it to your needs. For the new version of Tasking Manager (v4) we are looking into making this even more easier #1383. I hope this answered your questions. For direct assistance please join our #tasking-manager channel on hotosm.slack.com
