### ISSUE TITLE
Highlight better the fields that are required in the user profile

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2531]
People reported that they felt they are obliged to fill out social media fields on the Tasking Manager user profile in order to continue. Please add stars or a highlighting colour on the field that are required to fill in (currently name and email, i think).

**Comment by pydevsg** [comment]
Hi, @xamanu is this issue still open, I am willing to work on it.
Please assign me the same.

**Comment by xamanu** [comment]
Sure, thanks! Looking forward to the contribution.
