### ISSUE TITLE
Unfork iD

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2535]
For the iD integration in Tasking Manager we've slightly [forked iD](https://github.com/hotosm/iD). Let's get things upstream, so we can ideally rely directly on the main iD version.

* [ ] Scope iD's CSS to its container (https://github.com/openstreetmap/iD/issues/7437) and respective changes in the Tasking Manager CSS.

**Comment by xamanu** [comment]
@willemarcel is there anything else we would need to get upstream in order to rely on the standard iD directly?

**Comment by willemarcel** [comment]
@xamanu currently the https://github.com/openstreetmap/iD/ is not published as a package on npm, so we should suggest them to do it.

I'll do a PR with a small change to define the minimized file as the main file on the package.json.

**Comment by quincylvania** [comment]
Hello TM folks 👋

I've done the CSS scoping and was able to fix minor styling issues that your implementation may have run into, such as incorrect mouse cursors in the map. I'm also working on https://github.com/openstreetmap/iD/issues/7445, which will help avoid unexpected selector collisions.

> https://github.com/openstreetmap/iD/ is not published as a package on npm, so we should suggest them to do it.

I'm not sure why iD has never been published this way, but I don't see an immediate reason why it shouldn't be.

Let me know what else would improve the embedding experience!
