### ISSUE TITLE
Organisations not displayed for non-admin users

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2550]
For a non-admin user on TM4 - while selecting `organisations` from `manage` section, all the orgs which are managed by the user should be listed. Backend `https://tasking-manager-tm4-api.hotosm.org/api/v2/organisations/?manager_user_id=2823295` returns the right data, but frontend still says ` not permitted to manage organisations`. 

![image](https://user-images.githubusercontent.com/12103383/77322831-559b6700-6d3a-11ea-9873-6fabc294739c.png)

Expected behaviour: showcase organisations managed by user

**Comment by ritvikjain99** [comment]
@ramyaragupathy the org creation form doesn't give you an option to add non-admin users as project manager, so apparently non-admin user can't be made org manager !

**Comment by willemarcel** [comment]
Confirmed that it's solved.
