### ISSUE TITLE
Styling issue on the project overview page

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2563]
There are some minor styling issues on the project overview page:

------

![image](https://user-images.githubusercontent.com/97706/77432516-13276800-6dd6-11ea-91a1-d159cd95b8b6.png)

------

* It seems text is cut off above "TYPES OF MAPPING" icons, if the short description is too long.
* The scrollbar doesn't make much sense/looks good.
* The line spacing /styling is also different in the description at the top vs. below under "Description"

See [testing project #18](https://tm4.hotosm.org/projects/18) for an edge case example.

**Comment by xamanu** [comment]
Another small issue about a strange distortion of profile pic on the project page:

![image](https://user-images.githubusercontent.com/97706/77447780-f7c55880-6de7-11ea-8a28-feb0ad5c9b71.png)

**Comment by LeenasPingveenas** [comment]
> 
> 
> Another small issue about a strange distortion of profile pic on the project page:
> 
> ![image](https://user-images.githubusercontent.com/97706/77447780-f7c55880-6de7-11ea-8a28-feb0ad5c9b71.png)

It also allows me to drag text box over other content:
![Capture](https://user-images.githubusercontent.com/58010959/77448832-2c85df80-6de9-11ea-87ac-bd56c5bb2455.PNG)

**Comment by LeenasPingveenas** [comment]
Bug that allows text box to be dragged over other UI items.

![Capture](https://user-images.githubusercontent.com/58010959/77449008-622ac880-6de9-11ea-984b-cfb67ad4ac93.PNG)

**Comment by ritvikjain99** [comment]
@xamanu comment box has been amended in #2585 .

**Comment by willemarcel** [comment]
Most issues were solved. What's missing:

- Detect when the short description is too long for the screen space and assure the "Read more" button will be always visible.
- The organization information is mostly not visible. We could add it on the end of the page or next to the teams information.

**Comment by xamanu** [comment]
Fixed the distortion of profile pic problem in #2739

**Comment by willemarcel** [comment]
This issue has been solved.
