### ISSUE TITLE
Check on map attribution

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2565]
On the Mapbox map tiles the "improve the map" statement is sort of counter-intuitive as users are indeed actively improving the map through the Tasking Manager instead. Lets take that away.

And according to [OSM copyright rules](https://www.openstreetmap.org/copyright/en) the OSM part should be “© OpenStreetMap contributors” with a link to the copyright page. 

![image](https://user-images.githubusercontent.com/97706/77433212-03f4ea00-6dd7-11ea-9d85-22e76360b767.png)

So for Mapbox tiles we can perfectly use:

> © [OpenStreetMap contributors](https://www.openstreetmap.org/copyright) © Mapbox

**Comment by willemarcel** [comment]
I hid the Improve this map" part with CSS. As we are using a Mapbox style, it's not possible to modify the attribution easily. We can solve it when we have our own vector tiles.

**Comment by xamanu** [comment]
ok, closing here. Lets reopen this, once/if we have our own tile server.

**Comment by willemarcel** [comment]
> And according to OSM copyright rules the OSM part should be “© OpenStreetMap contributors” with a link to the copyright page.

The [legal FAQ](https://wiki.openstreetmap.org/wiki/Legal_FAQ#3a._I_would_like_to_use_OpenStreetMap_maps._How_should_I_credit_you.3F) allows us to remove the "contributors" part of the OSM credits
