### ISSUE TITLE
Slim top bar while editing in ID

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2566]
Might be nice to slim down the top bar while in iD mode to increase the amount of mapping area.

**Comment by JorgeMartinezG** [comment]
@willemarcel we could make a chevron-up down option to the header and make a state of it, what do you think?

**Comment by willemarcel** [comment]
@JorgeMartinezG we have a chevron icon at the side of the username, I don't have a good idea of icon that could fit that need... Initially I thought about hiding the top section of the header (where we have the hotosm.org link) on the map/validation page, but we would need to add some animation to avoid a page flicking.

**Comment by ritvikjain99** [comment]
@willemarcel I can add transition which would reduce its height to zero when id mapping tab is opened, if I am allowed to !
