### ISSUE TITLE
Organisation admin flow

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2567]
Testing the functionality of the organization admin there are a few improvements and bugs we have to look at:

* [x] Allow users without the project manager role to be selected as an organisation admin.
* [x] Show all projects a user can edit on the "My projects" page. Not only the ones users have created themselves.
* [x] Allow organization admins to create a project under their organization(s)
* [x] Allow organization admins to create a team under their organization(s)

**Comment by ramyaragupathy** [comment]
**Allow users without the project manager role to be selected as an organisation admin**
* `manage/organisations/new` page sends a request to `users/username=&role=ADMIN,PROJECT_MANAGER`
* Backend raises an exception when user role  not in ADMIN or PROJECT_MANAGER - fixed

**Show all projects a user can edit on the "My projects" page. Not only the ones users have created themselves**
* `manage/projects/` is invoked from `My projects` page with the following query parameters
     * `projects/?mappedByMe=1`  ->  My contirbuted projects
     * `projects/?favoritedByMe=true` -> My favortied projects

     Folowing enabled only for admin users
     * `projects/?createdByMe=true` ->  Projects created by me
     * `projects/?projectStatuses=DRAFT` -> show all draft proejcts
     * `projects/?projectStatuses=ARCHIVED` -> show all archived projects

Under `My Organisations` user can still edit projects related to organisations they can manage:

![image](https://user-images.githubusercontent.com/12103383/77521869-569ed680-6ea9-11ea-93d7-4e2cbeec21e9.png)

But this is specific to just organisation and user cannot filter projects from multiple organisations that they manage. So it will be useful to filter on `My projects` page.

@xamanu @willemarcel - how do you like the idea of providing an additional filter button on `My projects` page to filter `Managed` projects.
* `Managed` -> filter projects that I can manage. We can introduce a `projects/managedByMe=true` query parameter

**Comment by ramyaragupathy** [comment]
**Allow organization admins to create a project under their organization(s)**
* Backend was letting project manager, admin and org managers create projects, updated to let admins and project managers create projects
* Logged in as non-admin. Frontend `organisations/` calls
   * `organisations/?manager_user_id=2823295`  - returns two organisations that the user can manage, but there is none that's displayed for the user
  *  No option to create projects under `My projects` page

**Comment by ramyaragupathy** [comment]
** Allow organization admins to create a team under their organization(s)**
Backend does not have any restriction on who creates a team as long as they log in

**Comment by willemarcel** [comment]
> @xamanu @willemarcel - how do you like the idea of providing an additional filter button on My projects page to filter Managed projects.
> 
>     Managed -> filter projects that I can manage. We can introduce a projects/managedByMe=true query parameter

I like this idea and I think we really need it

> Backend does not have any restriction on who creates a team as long as they log in

We need to restrict it to ADMIN and org managers

**Comment by willemarcel** [comment]
@ramyaragupathy about the Managed projects, we should include also the projects associated with a project manager team whose user is member of

**Comment by ramyaragupathy** [comment]
Changes implemented through https://github.com/hotosm/tasking-manager/pull/2599
