### ISSUE TITLE
Maintenance site

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2568]
When deploying changes for the TM now with the frontend being separated from the backend. The frontend usually persists, while the backend is not reachable. For the user it looks like the tool is working well, but it doesn't behave well. Lets find a solution to put the frontend in maintenance mode during deployments and also if there are any unexpected errors.

**Comment by dakotabenjamin** [comment]
I found a fairly simple solution from this: https://stackoverflow.com/questions/46904990/maintenance-mode-using-s3-cloudfront

In effect, we can have a single lambda function that can be triggered when a viewer requests the site *before the cloudfront cache is checked* and returns the maintenance page content in the lambda function. I need to design a simple maintenance page for the lambda function and then the lambda function can simply exist by itself. When we need to put any TM site up (or any cloudfront served site for that matter) for maintenance we just create a Lambda@Edge deployment as a trigger for the function.

**Comment by xamanu** [comment]
This looked already good today. Needs probably documentation and a language review about the wording of the site.

**Comment by dakotabenjamin** [comment]
yes, I also will add the lambda functions to the scripts/ folder somewhere.
