### ISSUE TITLE
Mention people in mapping comments

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2573]
This is not working nicely. With an @ people should be able to choose from a drop-down search possible users. The usernames can also include white spaces.

**Comment by JorgeMartinezG** [comment]
@xamanu I could successfully mention myself within the comments section of a project in tm4 instance. Which section is having this issue?
![image](https://user-images.githubusercontent.com/3285923/77448099-6db4ca00-6dbe-11ea-9fff-18d39f07dd53.png)

**Comment by ritvikjain99** [comment]
@JorgeMartinezG the only problem I see here is if you write anything @[<here>], frontend will show that it just as if user is tagged without any check, even if it is senseless. I have worked upon this in #2529 , would be grateful if you suggest edits !

**Comment by xamanu** [comment]
@JorgeMartinezG and @ritvikjain99 I think this is not working for comments on tasks for mapping and validation. And yes, also the PRs by @ritvikjain99 are part of this here (many thanks for them)!
