### ISSUE TITLE
Improve provision of the suitable imagery for projects

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2578]
On the project tasks page, on the bottom bar, there is the "Imagery" part:

![image](https://user-images.githubusercontent.com/97706/77445409-f8a8bb00-6de4-11ea-9324-0951d02b6be0.png)

This currently (as in TM3) is becoming populated with the custom imagery if specified. However this doesn't make that much sense in projects where the description recommends some specific "standard" layer (like Maxar or Bing).

Let extend this to how a user would like to have this:

* Allow Project Managers to also select one of the standard layers and they should be shown there.
* Auto load this layer in the (iD and JOSM) editor.

**Comment by Aadesh-Baral** [comment]
The standard imagery layer is shown on the project detail and tasks page as in the screenshot below:
![imagery_2](https://user-images.githubusercontent.com/67958673/175923194-d1702ba9-5c59-456f-ae25-43037ae1f6ee.png)
![imagery](https://user-images.githubusercontent.com/67958673/175923208-680e2baa-9c60-4f32-a69e-1c982b4c8bf7.png)

Also, iD and JOSM are autoloaded with this predefined standard imagery
![maxar_id](https://user-images.githubusercontent.com/67958673/175923445-b104d3cb-8c41-4fd5-b732-5b4cc41b0b0d.png)

So I think this issue has been resolved. If I misunderstood this issue please feel free to reopen it with a comment.
