### ISSUE TITLE
Link to OSM Analytics and Export Tool

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/tasking-manager#258]
Link through from the Tasking Manger to the Export Tool and OSM Analytics. Something like: 'if you want to extract data from this region use the Export Tool, or would you like to see how the area you’ve been mapping has changed over time, use OSM Analytics'.

We've done this for the OSM data pushed through to the HDX platform via the Export Tool, so that the user can look at the same region on OSM Analytics. So I'm thinking the GeoJSON, KML, or zipped SHP file that was used to create the project in the Tasking Manager can define the region in both the Export Tool and OSM Analytics.

Talk to Seth and Brandon about how to incorporate both of them! Think it would be a great feature to offer users, so that they can easily see the impact of their contributions over time and use the data :) 

<img width="1279" alt="screen shot 2017-04-28 at 19 53 12" src="https://cloud.githubusercontent.com/assets/8972913/25540770/84ca4550-2c4c-11e7-8d72-d492a3cf34a4.png">

<img width="1280" alt="screen shot 2017-04-28 at 19 53 28" src="https://cloud.githubusercontent.com/assets/8972913/25540778/8998ea5a-2c4c-11e7-86e8-270119886a03.png">

**Comment by ramyaragupathy** [comment]
Download OSM data is available through [v4.7.0](https://github.com/hotosm/tasking-manager/releases/tag/v4.7.0). We do have a plan to bring in OSM analytics tool within Tasking Manager.
