### ISSUE TITLE
Duplicate projects of same region

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/tasking-manager#259]
Is there a way to provide a warning when a project that is 'Active' is similar to the one you are creating? I think this might be a good way of trying to reduce the amount of duplicate projects out there and focus on finishing existing ones.

**Comment by bgirardot** [comment]
Hi Mhari, we added the option to see existing projects during project creation, hopefully that helps with this issue. On the first screen of project creation, there is a toggle to show existing project footprints.

Let us know if that does not address this issue and we can re-open it.
