### ISSUE TITLE
Upgrade Tasks-Assisted to latest version

### ISSUE THREAD

**Issue by DavidMetcalfe** [hotosm/tasking-manager#2590]
[Project 16](https://tasks-assisted.hotosm.org/project/16) cannot be completed, despite the Contribute page showing the project as available to be worked on.

![image](https://user-images.githubusercontent.com/80915/77630074-bb891980-6f07-11ea-9516-e5b324058d96.png)

Yet the map within the project shows no available tasks, and the page states "There are no tasks currently available for mapping."

![image](https://user-images.githubusercontent.com/80915/77630190-dcea0580-6f07-11ea-9d59-587776e20e15.png)

**Comment by DavidMetcalfe** [comment]
Project 12 confirmed with the same behaviour, yet this one shows 100% completion for both mapping and validation.

![image](https://user-images.githubusercontent.com/80915/77840573-eceb2a80-713d-11ea-96f5-1aa1f4c92a6e.png)

![image](https://user-images.githubusercontent.com/80915/77840583-f70d2900-713d-11ea-810e-21569254c79a.png)
![image](https://user-images.githubusercontent.com/80915/77840588-fecccd80-713d-11ea-98a3-9f164ad81547.png)

**Comment by xamanu** [comment]
Thanks for reporting. This is on [Tasks-Assisted] an experimental platform (see [blog post](https://www.hotosm.org/updates/hands-on-assisted-tasks/)), which we support on the side.

This problem has been repaired released, but we are lacking behind on upgrade on this instance. Our main [HOT Tasking Manager](http://tasks.hotosm.org/) should not have this issue anymore.
