### ISSUE TITLE
General search function

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#260]
A general text search function seems to be missing

**Comment by tastrax** [comment]
I notice a search function has been implemented but it does not appear to work for description (try a search for cyclone)

**Comment by hunt3ri** [comment]
Hi @tastrax we've set up the search to only search active projects not archived, to make this faster for the bulk of users.  So as far as I can see there are no active projects with the word cyclone in their description.  If you search for monsoon or Serbia or Nyamira you'll see some projects

Thanks

**Comment by tastrax** [comment]
2648 and 2651 both show on the main page and have the word cyclone in the text. Are these projects active?

**Comment by tastrax** [comment]
![maincontributepage](https://cloud.githubusercontent.com/assets/8775395/26298463/bdaf5546-3f1a-11e7-816e-c962e43f84fe.JPG)

**Comment by hunt3ri** [comment]
Yeah I see it, will investigate.

**Comment by hunt3ri** [comment]
Released a patch for this bug, text search now returning results for Cyclone etc 💨
