### ISSUE TITLE
Task actions are not woking properly.

### ISSUE THREAD

**Issue by ritvikjain99** [hotosm/tasking-manager#2601]
If you mark any of the three options in task and submit it, the action shows 'Resume mapping' even if the task is marked as unavailable or mapped. But after refresh the they work fine.

**Comment by willemarcel** [comment]
@ritvikjain99 It probably means the tasks api request on the task selection page is being cached. I have noticed that problem sometime ago, but it's not happening to me on my local instance and on TM4

**Comment by ritvikjain99** [comment]
@willemarcel Actually what I found was that variable `lockedTasks` was not updated after updating status of task. So I invoked the function responsible. And it solves the problem. You can have a look at it in PR. Else we are good to drop this issue !
