### ISSUE TITLE
All tab fails

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#261]
If you have used the filters to get only beginner, advanced etc and then try a search on All you are returned no projects

**Comment by tastrax** [comment]
It also appears as though no filters work if the All tab is selected

**Comment by popelnuh** [comment]
Hi there,

Thank you for reporting this. This hasn't been set up yet, we will be working on this in the current sprint.

Thank you,

Zlata

**Comment by LindaAlblas** [comment]
@tastrax the 'all' filter should now work

**Comment by tastrax** [comment]
Thanks Linda - I will check it out and get back to u with any issues

**Comment by tastrax** [comment]
all good now
