### ISSUE TITLE
Filters - Priority required

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#262]
I think its essential that there is a filter for priority

**Comment by hunt3ri** [comment]
We made a change to the project filter so that we now order by priority which hopefully mitigates this issue.

**Comment by tastrax** [comment]
All depends on how many projects are at each priority level. For instance I might want to search for low priority road projects (to give those projects a bit of a boost). I understand that the preference is to complete urgent, then high, then medium etc tasks first but not everyone uses the task manager in that way. I suspect there are many worthwhile lower priority projects that seldom hit the 'front page' and therefore languish for months or years.

**Comment by xamanu** [comment]
Within TM4 we filter now by priority (or urgency).
