### ISSUE TITLE
Organisation not appearing

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#263]
Organisation does not appear on grid or list view

**Comment by tastrax** [comment]
Now seems to appears on grid but not list view

**Comment by LindaAlblas** [comment]
@tastrax this should be fixed too now

**Comment by tastrax** [comment]
well done folks

**Comment by tastrax** [comment]
This appears to have been lost again - no organisation on grid or list view

**Comment by hunt3ri** [comment]
Hi @tastrax we ported in the majority of TM2 data last week.  The existing dataset doesn't have organisation specified as it's a new field.  So all Project Managers will have to update their projects to specify an organisation.  However, we'll make a change to the UI to make it clearer that organisation has not been set cc @LindaAlblas
