### ISSUE TITLE
Error unlocking task

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#264]
Not sure if this is some sort of permissions issue or how operational the whole TM3 site is....
![tm3_unlock _error](https://cloud.githubusercontent.com/assets/8775395/25555011/8fafb95e-2d1f-11e7-8aaf-ed9a8913ef78.PNG)

- locked a square
- Didnt map anything in ID editor
- stopped mapping and got the following error

**Comment by popelnuh** [comment]
Hi there,

Thank you  for reporting this. We are aware of this issue and are currently looking into this.

**Comment by popelnuh** [comment]
@tastrax, we have implemented a fix for this.

Can you confirm whether this issue is still occurring on your side?

**Comment by tastrax** [comment]
@popelnuh Thanks Zlata - looks like its working as expected.
