### ISSUE TITLE
Changeset hash-info for all iD starts

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2650]
In the first time we open iD the project's changeset comment is loaded correctly. But...

- If I modify (or erase the comment), but don't save the changeset, it loads the modified (or empty) comment next time.
- If I modify and save the changeset, it loads the project's comment correctly

**Comment by willemarcel** [comment]
Reported to iD https://github.com/openstreetmap/iD/issues/7504

**Comment by xamanu** [comment]
It is reported that changeset comments don't show up after several saves in iD.

**Comment by jflasher** [comment]
Sorry for the duplicate issue! In my case, it only seemed to happen the first time I came into iD. After I pasted manually once, behavior seemed normal even after going in and out of iD.

**Comment by xamanu** [comment]
No worries, @jflasher. Thanks for the additional information. We are looking into this tricky one.
