### ISSUE TITLE
Provide better message when trying to validate a task on an archived project

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2652]
When trying to validate a task on an archived project a user gets the following error: ![image](https://user-images.githubusercontent.com/97706/78581792-de7ace00-7823-11ea-987b-9e5d71b241ed.png)

Can we give a better message here?  Something like `Project has been archived, no mapping or change of tasks is possible`.

**Comment by Aadesh-Baral** [comment]
With #5306 merged in i think this can be closed now.
