### ISSUE TITLE
Improve contributions tab in project

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2654]
This issue is to reevaluate the contributions table in TM3 and TM4.

![image](https://user-images.githubusercontent.com/97706/78590210-01f84580-7831-11ea-9ab3-ca43488ba1a0.png)

![image](https://user-images.githubusercontent.com/97706/78590250-0e7c9e00-7831-11ea-8094-b1fa5ce67049.png)

Changes to the view may need to add the additional information on the endpoint `/api/v2/projects/2/contributions/`

* Validators find it extremely useful to have the `registered` and `last validation` columns in TM3. Because it allows them to spot new mappers quickly and easily. Especially during a mapathon scenario. They can see who are very new and no validation on their tasks has happened so far.
* The sorting options of this table is quite extensively used to inspect contributions
* Improve repeated terms for task achievements in table view

**Comment by xamanu** [comment]
One idea for the `recent` is to add a filter `Newbie` to the drop down list for the list, that shows users that registered in the last 7 days:

![image](https://user-images.githubusercontent.com/97706/78609161-a9857000-7851-11ea-9c36-80b62c426f95.png)

**Comment by xamanu** [comment]
What about a table like this?

User | Mapped | Reviewed
---------------------- | --------------------- | ---------------
username (experience level)  | x(mapped) (y/z) | x(validated) 

This ideas here:

* Omit the `total`, as it seems to be not that useful
* Disclose the amount of mapped tasks that are pending validation (y) and the number of tasks validated (z) 
* Together with the `Newbie` filter we would allow validators to check quickly on new mappers that need to be checked with much care.

**Comment by xamanu** [comment]
Additionally it would be nice to be able to sort on the columns. That would give us a user ranking for every project \o/

**Comment by RAytoun** [comment]
The option 5 on the TM3 also gave us the link to highlight on the map the tasks that the mapper had completed and we could select those tasks to check. A much quicker process for us to get to where we need to be.

**Comment by xamanu** [comment]
This functionality, to select the tasks, is also available in TM4, and even with all tasks of the user, which is very nice.

**Comment by willemarcel** [comment]
My proposals to this issue:

- Use icons to replace beginners, intermediate and advanced words
- Show date when the user registered on TM when the mouse is over the username and level icon
- Use icons to replace mapped / validated / total text
- Add "New mappers" filter to filter users registered in the last month.
