### ISSUE TITLE
html title when editing with iD

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2658]
When editing with iD in the Tasking Manager the html title gets overridden.

![image](https://user-images.githubusercontent.com/97706/78648574-adde7700-78ab-11ea-904f-93c1a4149a76.png)

**Comment by xamanu** [comment]
We need to fix this on iD, first. @quincylvania can you help us here?

**Comment by willemarcel** [comment]
Thanks @quincylvania ! I solved that issue with #3362
