### ISSUE TITLE
Show error message when trying to save a project with empty required fields

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2664]
A user can not change their [test project](https://tm4.hotosm.org/manage/projects/35) from draft to published, and get a message error "Project update failed:" with no more info.

It looks like the descriptions and instructions fields are empty but required. The frontend shall provide an error message to the user, asking to fill these fields.

**Comment by ramyaragupathy** [comment]
Server message:

```
ERROR in project_admin_service: short_description not provided for Default Locale
CRITICAL in resources: ProjectsRestAPI PATCH - unhandled error: short_description not provided for Default Locale
```

**Comment by joaovitor3** [comment]
This issue could be related to [this one](https://github.com/hotosm/tasking-manager/issues/2218)?
