### ISSUE TITLE
Improve display of project urgency

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2673]
User feedback:

> Can we suggest a different way to present the urgency other than this note in the top right? Took me a couple minutes of looking around to realize it wasn’t talking about difficulty. I’ll know now what it means but instinctively it’s not that clear. Maybe some sort of visual cue? I’ve seen on other apps colored clocks visualizing the urgency of an item, for example.

**Comment by willemarcel** [comment]
I think the problem are the "high", "medium" and "low" urgency labels, which are not clear what it is about.
