### ISSUE TITLE
Some frontend details

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2686]
- [x]  Review the task state dialog (see comments https://github.com/hotosm/tasking-manager/issues/2686#issuecomment-612009579 and https://github.com/hotosm/tasking-manager/issues/2686#issuecomment-612847049)
- [x] Add organization info to project page
- [x] Add campaign selection on project edit page
- [x] Add icons for learn pages links to tutorials
- [x] Link the the privacy policy on the cookies consent popup
- [x] Remove not working share button on projects
- [x] On "More Filters", could the lists be alphabetized A-Z?
- [x] In the "search" area, hitting "Enter" after the search seems to clear the search rather than return results. May not be intuitive for all
- [x] LinkedIn on the TM4 profile page has a lowercase 'i', but it should be uppercase
- [x] Add link to privacy policy in footer
- [x] Remove `Featured projects` element from frontpage

**Comment by willemarcel** [comment]
> "Can't finish this task, set back to ready for mapping" -- the wording is a bit confusing, how about something short like "Unfinished"?
> Can we add a (?) icon after the action "It was impossible to map this task" and with a mouse over we say Due to bad imagery or nothing is there to map.

I think the best way of making it more comprehensive is to replace "task status" text by a question like:

**Could you map everything on this task?**
- Yes
- No
- The imagery is bad or nothing is there to map

**Comment by xamanu** [comment]
I like this idea, @willemarcel It makes it much clearer.

**Comment by willemarcel** [comment]
@xamanu I'm not sure about "nothing is there to map"... I don't know the opinion of the PMs, but I think the unavailable status should be applied only if we can not assure the data is complete due to imagery limitations.

Maybe "Is this task completely mapped?" could be better for the question. If a project is interested only in one type of features (like buildings) "everything" may be understood as every feature on the imagery is mapped.

**Comment by xamanu** [comment]
> I'm not sure about "nothing is there to map"... I don't know the opinion of the PMs, but I think the unavailable status should be applied only if we can not assure the data is complete due to imagery limitations.

Yes,indeed, better to move a bit more careful and in coordination with the validators.. Lets stick to the bad imagery for now.

> Maybe "Is this task completely mapped?" could be better for the question. If a project is interested only in one type of features (like buildings) "everything" may be understood as every feature on the imagery is mapped.

Agreed, makes sense!

**Comment by xamanu** [comment]
Email notifications might have a bad link:

> Hi XXX
>
> You have a new message on the HOT Tasking Manager.
>
> [Click here to view it..](https://tm4.hotosm.org/inbox)
>
> Many thanks,
> Humanitarian OpenStreetMap Team
>
> Please note: You can now opt-out of all automated validation
> messages by visiting your User Profile and clicking "Edit-Add Contact Details."
