### ISSUE TITLE
Explicit URLs for tasks

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2691]
User feedback:

> On the map on the project page when i click on a task the URL does not reflect the clicked task. Eg when i enter the url https://tm4.hotosm.org/projects/31/tasks, i click a task in the map, the url stays the same. And also (as a consequence?) i cannot select a specific task via the url, as i could in TM3. I do not see any search function to compensate for this

**Comment by ritvikjain99** [comment]
@willemarcel  We can give a thought to the inclusion of hash navigation here ! 
like /project/{id}/tasks#{task-number}

**Comment by willemarcel** [comment]
@ritvikjain99 It's bit more complicated. Right now we have the `?search=` param  than can do it. I tried to add a `?task=` to enable just the selection of the task, but it was affecting other components. I'll try to work on it again after solving some problems on the task list.

**Comment by tawirth** [comment]
I would like to vote this one up. For the Crowd2Map project we used to ask for a url to the project task square so we could validate or provide new mapper feedback. Now we are asking that they provide the task number but we still have to go and search for the osm username to find the task square. From my point of view this is a step backward in the new tasking manager. Thanks.
