### ISSUE TITLE
Check on provided social media links in user profile

### ISSUE THREAD

**Issue by wireguy** [hotosm/tasking-manager#2710]
Would be nice if the LinkedIn field:

- could parse the input and strip everything up to the last '/' 
users seem to grab the url of their linkedin id and paste it as input causing tm to make the link:
https://www.linkedin.com/https://www.linkedin.com/gg
instead of 
https://www.linkedin.com/gg

- would be nice if the url could be validated (pinged?) and inform the user if the link is bad (gets a 404)

**Comment by xamanu** [comment]
Lets check here on other social media links, too.

**Comment by eternaltyro** [comment]
Twitter link does not show `https://` explicitly. The rest of the social media links do.

**Comment by willemarcel** [comment]
I added a validation on the user settings form that avoid users from inserting urls https://github.com/hotosm/tasking-manager/pull/3684
