### ISSUE TITLE
LinkedIn in TM4 spelled with lowercase 'i' but should be uppercase

### ISSUE THREAD

**Issue by wireguy** [hotosm/tasking-manager#2711]
LinkedIn on the tm4 profile page has a lowercase 'i', but it should be uppercase as it is in the existing tm.

see https://brand.linkedin.com/policies
for more info.   

tasking-manager\frontend\src\components\user\forms.js
line 271

**Comment by xamanu** [comment]
Added to this issue. Closing here.

**Comment by wireguy** [comment]
'Added to this issue'  
which??  #2714 ?  saw text, but not code.
