### ISSUE TITLE
Show error message on Organisation creation

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2717]
If for some reason the organisation creation fails, it's breaking the app. Instead, it should show a message on the footer with the reason the request failed.

**Comment by ritvikjain99** [comment]
Will get this done !

**Comment by ritvikjain99** [comment]
@willemarcel just wanna have suggestion on how should the message be placed ?
I was thinking to give an alert if any error occurs!
Or should I place a box somewhere for the error ?

**Comment by willemarcel** [comment]
@ritvikjain99 Initially I thought about adding it on the footer at the left side of the "Cancel" button. Or below the field with problem if we know what is causing the error (generally it fails because there is already an org with the same name). I wouldn't like to use modal or alert on it

**Comment by HelNershingThapa** [comment]
Closed by #5252
