### ISSUE TITLE
Create Project: Style issue in project section imagery

### ISSUE THREAD

**Issue by NoemiNahomy** [hotosm/tasking-manager#2721]
In firefox and chrome the buttons are outside the project form area.

![imagen](https://user-images.githubusercontent.com/1789542/79132144-c81ac800-7d77-11ea-98f4-5952e8efe104.png)

**Comment by xamanu** [comment]
Unfortunately it doesn't solve the problem on my end:

![image](https://user-images.githubusercontent.com/97706/79201993-72522880-7e28-11ea-899e-b4eaf84b82c6.png)
