### ISSUE TITLE
There can be multiple campaigns with same name

### ISSUE THREAD

**Issue by ritvikjain99** [hotosm/tasking-manager#2728]
I can create multiple campaigns with same name, not really sure about whether this is feature or not.
If this is intended then we should have an distinction between two with same name.

![Screenshot_2020-04-14 Tasking Manager](https://user-images.githubusercontent.com/34532173/79219458-f2e84780-7e6f-11ea-9ea3-4277d92e3634.png)
 @xamanu please confirm this so that I can solve if this is really an issue!

**Comment by xamanu** [comment]
Yes, this doesn't make sense. I think it is good that campaigns are handled by id. But we should check on creation and change of name, that a campaign with the same doesn't exist.

**Comment by ritvikjain99** [comment]
I'll get that done !

**Comment by ramyaragupathy** [comment]
Handled through #3119 - thanks for spending time on this @ritvikjain99
