### ISSUE TITLE
Preserve status when switching task in mapping/validation views

### ISSUE THREAD

**Issue by joaovitor3** [hotosm/tasking-manager#2729]
Based on [this issue](https://github.com/hotosm/tasking-manager/issues/2688).

If you switch tabs to view the history while mapping or validating, everything you had selected in the status buttons is lost.

**Comment by xamanu** [comment]
Hey, hasn't this been solved on recent `develop`? We just merged a fix today. Can you verify?

**Comment by joaovitor3** [comment]
You are talking about [this one](https://github.com/hotosm/tasking-manager/pull/2723), right?

If so, it's different because in the tab we have some buttons to declare the task status and the PR merged before was fixing the comment (the one that I just opened is about the buttons that had the same misbehavior of missing when changing between tabs).

**Comment by xamanu** [comment]
Ah, right! Thanks for highlighting that.
