### ISSUE TITLE
Project search can't handle special chars

### ISSUE THREAD

**Issue by ritvikjain99** [hotosm/tasking-manager#2737]
If your search text has chars like `< ) ! &` server throws 500 which is unhandled at frontend.
You can see it here:
![Screenshot_2020-04-15 Tasking Manager](https://user-images.githubusercontent.com/34532173/79370524-77ba8a80-7f70-11ea-80fe-ba8b20364f09.png)

**Comment by ritvikjain99** [comment]
I think in all searches if there is any error then irrespective of its type the result should be 0 not error !

**Comment by Aadesh-Baral** [comment]
Fixed by #5134 and #5155
