### ISSUE TITLE
Update notification results after a notification is read

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2741]
On the notification page, click on a notification and a modal opens. Then click on close icon. On that moment, the list should be updated to have the notification marked as read.

**Comment by ritvikjain99** [comment]
I would like to do this !

**Comment by ritvikjain99** [comment]
I noticed one more thing if you open any notification on second page you are thrown to first page automatically, will try to fix this !

**Comment by ritvikjain99** [comment]
@willemarcel do we really need a separate route(/message/{id}) for notification popup ?
Current to open a notification there is separate link and a manually created modal, when we are already using a third party package for it !

**Comment by willemarcel** [comment]
> I noticed one more thing if you open any notification on second page you are thrown to first page automatically, will try to fix this !

It's not a problem.

> @willemarcel do we really need a separate route(/message/{id}) for notification popup ?

We need to provide a direct link to a message, because we send notifications by email with a link.

**Comment by ritvikjain99** [comment]
>It's not a problem.

So if I wanna see 6 messages on Xth page. Then I open it once get redirected to 1st page then again go to Xth page, open 2nd notif then get redirected to 1st, open 3rd notif then get redirected to 1st and so on, is it intended ?, sorry if I asking too much but just couldn't digest it !

**Comment by willemarcel** [comment]
@ritvikjain99 Sorry I didn't understand well what you said about the page... yes, the current pagination doesn't handle to be initialized with a value different from 1. It'd be good to have a fix for it.

**Comment by Ichchhie** [comment]
Closed by #5136
