### ISSUE TITLE
Make learn page sections linkable

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2760]
Currently it is not possible to directly link to `How to validate` and `How to manage`  pages. Can we make this possible?

**Comment by xamanu** [comment]
This button currently links to the mapping section because we can not actually link to the learn to validate page:

![image](https://user-images.githubusercontent.com/97706/81169273-1d698400-8f88-11ea-9737-9e20a7591b91.png)

**Comment by Patrik-Br** [comment]
Tested. Not sure if I understand this correctly, when I got to https://tasks-stage.hotosm.org/learn and I click on "Learn to validated" or "Learn to manage" there is still showen the same URL in my browser (ttps://tasks-stage.hotosm.org/learn), so I guess this isn't fixed?

**Comment by martien-176** [comment]
Does the button "Learn how" in the above image stil exists? I cannot find it.

Could someone please explain more what exactly is the problem? Thanks.

**Comment by Patrik-Br** [comment]
It works perfect in live version 👍 good job.

@martien-176 when you got to LEARN page, there is now different URL when you click on each of learn to map/validate/manage

**Comment by martien-176** [comment]
Thanks @Patrik-Br, i already saw that, but did not realize that was the issue to be tested. 

I was looking for the  button "Learn how". I found that, and it links to https://tasks-stage.hotosm.org/learn/validate. I suppose that is also a thing to be tested.

So in both cases: works as expected. Many thanks for the tech team.
