### ISSUE TITLE
Identify asynchronous tasks 

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2786]
In order to reduce latency and improve user experience certain tasks like sending mails, auto unlock operations can be moved to a separate thread without blocking the API calls and reduce redundant API calls. First step is to identify all such tasks from the backend. Later we could use a library like [Celery](http://www.celeryproject.org/) and update the backend to have these tasks run seamlessly behind the scenes

**Comment by ramyaragupathy** [comment]
Listing out functions in message service that could be handled asynchronously without blocking other activities
* send_message_after_validation
* send_welcome_message
* send_message_after_comment
* send_message_after_chat
* send_favorite_project_activities

**Comment by NoemiNahomy** [comment]
We could also add the list:

- send_invite_to_join_team

- accept_reject_request_to_join_team

**Comment by ramyaragupathy** [comment]
sounds good @NoemiNahomy - let's add it to our PR https://github.com/hotosm/tasking-manager/pull/3332  and merge the changes

**Comment by bopercival-hot** [comment]
PR merged
