### ISSUE TITLE
Give access to private projects for all users in an assigned team

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2817]
Expecting an input option for allowed user list on private projects.
![image](https://user-images.githubusercontent.com/12103383/80571486-53ec4f80-8a1a-11ea-9be1-8e8c9224c9ad.png)

![image](https://user-images.githubusercontent.com/12103383/80571520-61093e80-8a1a-11ea-966c-42890f0ec590.png)

**Comment by russdeffner** [comment]
Shouldn't this be handled with Teams in TM4? Or at least, add individually or by team?

**Comment by xamanu** [comment]
Yes, i think i remember we said this should be handled by teams, and we support the list of users but only in the backend. Still we need a way to add teams to a private project.

**Comment by willemarcel** [comment]
> Shouldn't` this be handled with Teams in TM4? Or at least, add individually or by team?

Yes, we made the decision to remove the allowed users field from the project edit form.

> Still we need a way to add teams to a private project.

@xamanu we can add teams the same way we do to public projects, can't we?

**Comment by xamanu** [comment]
As far as I see, if a user is part of a team that is assigned to the project, s/he can still not access the project, but this is what I would assume as the behaviour in TM4.

**Comment by willemarcel** [comment]
Resolved by https://github.com/hotosm/tasking-manager/pull/2949
