### ISSUE TITLE
I can't create a private project

### ISSUE THREAD

**Issue by NoemiNahomy** [hotosm/tasking-manager#2833]
When I activate this option, I cannot save the project because of a server error.

In the console: Must have at least one allowed user on a private project

I can't assign at least one user to a project

![Screenshot(5)](https://user-images.githubusercontent.com/1789542/80722637-9753c600-8acd-11ea-9a64-aaba40c5f62b.png)

**Comment by ramyaragupathy** [comment]
Related https://github.com/hotosm/tasking-manager/issues/2817
