### ISSUE TITLE
Select another project button not working for advanced projects

### ISSUE THREAD

**Issue by joaovitor3** [hotosm/tasking-manager#2852]
As a beginner mapper when trying to contribute for a project allowed for advanced mappers only, when selecting the `select another project` button nothing happens.

![image](https://user-images.githubusercontent.com/18130942/81016641-37e01800-8e37-11ea-8f69-ba9eab31722e.png)

**Comment by HelNershingThapa** [comment]
Fixed in https://github.com/hotosm/tasking-manager/pull/2912
