### ISSUE TITLE
Capitalization Issue With Turkish Characters

### ISSUE THREAD

**Issue by canunen** [hotosm/tasking-manager#2864]
There are two versions of the letter "i" in Turkish: "i" and "ı"

For the Turkish interface, the letter "i" should be capitalized as "İ", and the letter "ı" should be capitalized as "I"

**Comment by willemarcel** [comment]
@canunen Thanks for noticing it! Is that capitalization of the main TM header correct?

![image](https://user-images.githubusercontent.com/666291/81119666-9ffb3080-8f01-11ea-8acd-c92ba7ee1578.png)

**Comment by canunen** [comment]
> @canunen Thanks for noticing it! Is that capitalization of the main TM header correct?
> 
> ![image](https://user-images.githubusercontent.com/666291/81119666-9ffb3080-8f01-11ea-8acd-c92ba7ee1578.png)

Hey Felix, capitalization on the header is correct, thanks.

**Comment by canunen** [comment]
@xamanu @willemarcel 
Sorry for revisiting a closed issue. Everything is fine with Turkish text, but this time I realized this causes capitalization error on non-translated English text like project names, organization names etc.
 
![Screenshot_2020-05-16_12-41-28](https://user-images.githubusercontent.com/13434280/82116466-bb243680-9772-11ea-9937-6830b0f44f27.png)

Is selective capitalization by language possible?

**Comment by verdy-p** [comment]
No it is not correct if dotted and undotted i are confused.

The basic ASCII capitalization rules do not apply to the Turkic (aka Latin
Altaic) alphabets. (for Turkish and a few other Turkic languages romanized
with the same system). this can be an issue for the dot over the two Latin
letters i and j (except the Dutch digram "ij", possibly ligatured, which is
not used in Turkic languages, but this also applies to some other ligatured
digrams like "ti" or "li": the ligature which may exist in Turkish for the
dotless "Ti" will become a non-ligatured dotless "TI", where as the dotted
"Ti" is normally never ligatured, but will become an undotted non-ligatured
"TI" if capitalized in english but an undotted non-ligatured dotted "TI" in
Turkish).
Such tricks is specified in Unicode by a languages-sensitive capitalization
file (replacing the default simple casing pairs of the main UCD file).
Locale-sensitive capitalization is also needed for German and Hungarian
(for the sharp S: it applies in Germany and Austria for traditional
typography, but not Switzerland which uses the simpler model; there are
also special rules for the German umlaut) and a few other languages. There
are a few rules as well for some letters in other Nordic languages, and
also for Greek (for the final sigma letter form).
