### ISSUE TITLE
Custom OSM server configuration for Dockerized version

### ISSUE THREAD

**Issue by majdal** [hotosm/tasking-manager#2865]
Hello TM team - congrats on the 4.0 release!

I have my own instance of the OSM infrastructure on my own server, which I use to run mapathons to vectorize the content of historical maps. I've run 22 mapathons so far, but I'd like the vectorization process to become more systematic, so I plan on deploying TM4 for the project. I looked through the [feature/docker pull request](https://github.com/hotosm/tasking-manager/pull/2816), and I can't see anywhere in  where I would specify the OSM server to be used. [Asking](https://hotosm.slack.com/archives/C319P09PB/p1588712727186100
) around on on Slack seems to confirm that. 

I'd like my mappers to be able to use the integrated iD editor, to simplify their experience. 

## Feature request
Ability to specify OSM server in `.env`, including authentication using the specified OSM server.

**Comment by majdal** [comment]
Possibly useful: osm-seed worked on dockerizing the iD editor, [here](https://github.com/developmentseed/osm-seed/tree/develop/id-editor).

**Comment by willemarcel** [comment]
@majdal do you think we can close this issue?

**Comment by majdal** [comment]
Yes we can :) Thanks everyone for the work!
