### ISSUE TITLE
Fix sorting of the manage projects page

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2869]
The sorting of the projects in the manage projects page is not having an effect, when choosing the different options.

![image](https://user-images.githubusercontent.com/97706/81149465-c951a600-8f6d-11ea-90b3-ba89fe06031a.png)

**Comment by JorgeMartinezG** [comment]
Fix is currently in production instance

**Comment by willemarcel** [comment]
Reopenning it as the sorting is only working well for ADMIN users
