### ISSUE TITLE
Same height boxes

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2871]
I know this is hard. But let's collect here a bit the issue around the cards/boxes and try to find a good solution for making them on the same height but respecting variable length:

![image](https://user-images.githubusercontent.com/97706/81160435-944b5080-8f79-11ea-8043-9e17459e5eb6.png)

------

![image](https://user-images.githubusercontent.com/97706/81160459-9c0af500-8f79-11ea-97b1-45ba5bba6a42.png)

------

![image](https://user-images.githubusercontent.com/97706/81160585-c78ddf80-8f79-11ea-9e85-e57fe8baa12e.png)

**Comment by xamanu** [comment]
Another constraint. They still need to work in the responsive design. o_0

**Comment by xamanu** [comment]
Another place with same height boxes

![image](https://user-images.githubusercontent.com/97706/81164138-636e1a00-8f7f-11ea-8859-df11fe84f5fd.png)

**Comment by Manasa2850** [comment]
@xamanu can I work on this?
