### ISSUE TITLE
Wrong Name in HOT Tasking Manager - Email Verification 

### ISSUE THREAD

**Issue by Fanevanjanahary** [hotosm/tasking-manager#2880]
I got this email:

 

> Hi Athena Santiago 
> Thank you for supplying your email address, please click the link below to verify you own this address
> Click here to verify your email address
>  Please ignore this email if you have received it by mistake.
>  Many thanks
>  HOT Mapping Team

But the name is not right

**Comment by xamanu** [comment]
Thanks @Fanevanjanahary this was very helpful. We had a problem of some very few times users got their email address flipped over to another one, and I guess, this caused your confusion here. We addressed this in the latest release (https://github.com/hotosm/tasking-manager/releases/tag/v4.0.3) and monitor that this is not happening again.
