### ISSUE TITLE
Request to Join Team Notifications

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#2884]
Currently if you manage a team that allows public requests, the message you get in your notification inbox is not very helpful. Mostly it's just the message, so a few things could make it much more useful...

1. Currently it highlights when you hover over the message "Request to Join Team" - this should maybe be a link to the team that has the pending request(s).
2. It appears there is an attempt to have a link when you click the username that made the request, but like other notifications, it has no functionality and in one case when I right-clicked and opened in a new window, it did not successfully take me to that user. The URL is off by one letter, https://tasks.hotosm.org/user/hebolz is the link it is trying to take me to; https://tasks.hotosm.org/users/hebolz is the link it should be taking me to.
3. Ideally there would be an accept and reject option directly from the message, but this is probably tied to a larger request to be able to reply directly from the inbox to all appropriate types of notifications.

**Comment by russdeffner** [comment]
Also, there was no alarm or email with these notifications, just noticed them when I went to check another message.

**Comment by willemarcel** [comment]
The PR https://github.com/hotosm/tasking-manager/pull/3290 solves most of those issues

![image](https://user-images.githubusercontent.com/666291/87301880-b7006500-c4e6-11ea-981d-272cd84dec13.png)
"testing" is the team name, both user and team names are linked.
