### ISSUE TITLE
Map data disappearing

### ISSUE THREAD

**Issue by bkastner** [hotosm/tasking-manager#2885]
When using the new tasking manager I've had problems with map data disappearing.  The first time the task boundary (pink square) disappeared and I had to save edits, submit the task, and re-select the task to get it back.  The second time it was buildings and roads missing. 

I'm using Chrome 81.0.4044.138 on MacOS 10.15.4.

**Comment by willemarcel** [comment]
The iD integration is better now. We fixed several bugs on the last weeks.
