### ISSUE TITLE
User stats cakes 

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2901]
It has been reported that the user profile stats are sometime not loading correctly. So far it seems only to happen on Firefox.

![image](https://user-images.githubusercontent.com/97706/81411354-c7d0db00-9131-11ea-82d6-c2a00a6c9508.png)

**Comment by NoemiNahomy** [comment]
I think the problem is caused by the url returns a value of 404 for new mappers.
This new user is a new mapper.
https://osm-stats-production-api.azurewebsites.net/users/SamHot20
https://osm-stats-production-api.azurewebsites.net/users/noe_mi

**Comment by willemarcel** [comment]
It was solved with https://github.com/hotosm/tasking-manager/pull/3286
