### ISSUE TITLE
Map feature options in iD

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2902]
As a user, when mapping a building i am only seeing 'Area' but then i cannot select building unless i manually type it in.

![image](https://user-images.githubusercontent.com/97706/81412112-e4b9de00-9132-11ea-9c4b-27ed7284a6cb.png)

> Do you know why I am not able to select the generic type:building for areas, or any line types at all in any of the projects that are currently active? This is what it looks like for areas:

![image](https://user-images.githubusercontent.com/97706/81411738-53e30280-9132-11ea-8bf8-838f24e270b0.png)

**Comment by willemarcel** [comment]
It's defined by iD, based on the last presets the user has selected.
