### ISSUE TITLE
Check on notification options

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2904]
Users reported that the options on their profile aren't having effects on the messages they receive:

![image](https://user-images.githubusercontent.com/97706/81413723-6dd21480-9135-11ea-9101-cd3d216ad43a.png)

**Comment by willemarcel** [comment]
We need to make it more clear the difference between "Project updates" and "Comments". When a task I mapped is validated, will I receive a project update?

Maybe we need to improve the messaging system to avoid the user from receiving two messages by the same action (for example a comment of a validator and a message saying that the task was validated).
