### ISSUE TITLE
Private projects hidden from Admins and Managers

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#2906]
If I put a project as Private, even as the owner and creator - it does not show up in Explore or Manage sections of the TM, the only way it seems possible to return to it is if you know the project URL. We need to allow admins, project managers and owners to search for private projects.

**Comment by russdeffner** [comment]
This may have just been a caching or slow connection/responsiveness of database issue.

**Comment by ramyaragupathy** [comment]
Yeah - looks like it. As an admin I can confirm access to private projects
