### ISSUE TITLE
Difficulty vs. Mapper Level

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#2908]
Related to #2907 - let's just cut difficulty away from mapper level for good. In metadata it should just be "Difficulty: Easy, Moderate, Challenging" - wording can change a bit, but especially now that this isn't tied to permissions anymore there's no reason to continue the confusion between mapper level and difficulty of projects.

**Comment by willemarcel** [comment]
I like this idea!

**Comment by russdeffner** [comment]
I would suggest to re-open this as it still is not fully addressed. The following screen capture highlights why... The "Beginner Mapper" vs. "Intermediate Mapper" does not give the mapper a picture of access or necessarily difficulty. Some of the "Intermediate Mapper" projects are open to beginners and the way permissions work, a "Beginner Mapper" project could be restricted to intermediate and advanced, or to a particular team assigned to mapping. This needs to change where there is a "Difficulty" rating (i.e. easy, moderate, challenging) and a permission (i.e. not restricted or restricted to 'mapper level').

![whyreopen](https://user-images.githubusercontent.com/6763645/132953197-515b0be0-1c2d-40f3-95c2-9c9a94bba968.PNG)

**Comment by bopercival-hot** [comment]
Happy with that @russdeffner will reopen and bring it back to the table.
