### ISSUE TITLE
Draft projects not showing in search

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#2910]
Error in Web Consule: Res failure Object { Error: "Unable to fetch projects" }  500 Object { "content-type": "application/json" } Object { mapResults: {…}, results: [], pagination: {…}, error: {…} }

Error on screen: 
![DraftNoShow](https://user-images.githubusercontent.com/6763645/81518031-58482f00-936f-11ea-8fb3-a22ecb687b0a.PNG)

**Comment by ramyaragupathy** [comment]
This one is related to empty project info that's mentioned in 2916. After updating locale info, this filter is working
