### ISSUE TITLE
Project update: Changing default language should include empty field check

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2916]
We have come across around 9 projects with  `default_locale` data  missing from project_info.
eg: project 8151 has default_locale set to `fr` but there is no matching details for the project in `project_info` table. This breaks down any project search activity because of null value.

This has to be handled in the codebase in the following way:
* Better error handling on empty locale values
* Prompt user to fill in default information details whenever default_locale in updated.

For a project, I updated the default_locale to point to a non-English language and then hit on save. This did not prompt me to fill in information for any of the description/instruction/title in the default_locale. Ideally it should and when the default_locale is `en` this check is present. It should be present for all languages in the frontend.

**Comment by Aadesh-Baral** [comment]
I think this is no longer an issue as frontend prompts user to fill in default information details whenever default_locale is updated. I think it is also related to #5161 which has been addressed in #5162.
![change_language](https://user-images.githubusercontent.com/67958673/174563910-9808514a-00ee-4d84-952e-d9e47d1d5afd.png)
