### ISSUE TITLE
Link to project in mentioned message isn’t clickable

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2921]

**Comment by willemarcel** [comment]
Also use the same colour on the notification title:

![image](https://user-images.githubusercontent.com/666291/81573387-ca724100-937a-11ea-8d14-2f7d78cd5090.png)

**Comment by cgiovando** [comment]
Not sure if it's the same issue, but also links to tasks don't open automatically when clicked. The URL is correct, but in Chrome I need to manually right click and choose "Open Link in New Tab".

![Screen Shot 2020-05-18 at 07 00 55](https://user-images.githubusercontent.com/10201533/82175947-a0b69e00-98d5-11ea-9e58-d6f60430b247.jpg)
