### ISSUE TITLE
Show projects a non-admin user can manage

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2923]
Consider adding a “Created/managed by me” also to the “My contributions”→”My projects” section, for people who are having PM permission (through teams or as an author) and want to find the projects they can edit.

**Comment by willemarcel** [comment]
@ramyaragupathy as while I was working on #3083, I touched that part of TM, I solved that issue too.

**Comment by willemarcel** [comment]
Solved by https://github.com/hotosm/tasking-manager/pull/3297
