### ISSUE TITLE
docker build - no index.html template - throw 500 server error

### ISSUE THREAD

**Issue by chas678** [hotosm/tasking-manager#2955]
vanilla docker local run, following docs.  on successful startup, navigating to http://127.0.0.1:500 gives 500 

app           | jinja2.exceptions.TemplateNotFound: index.html
app           | 172.18.0.1 - - [14/May/2020 21:24:05] "GET / HTTP/1.1" 500 -

**Comment by chas678** [comment]
`app           | 172.18.0.1 - - [14/May/2020 21:28:04] "GET / HTTP/1.1" 500 -
app           | [2020-05-14 21:28:26,692] ERROR in app: Exception on / [GET]
app           | Traceback (most recent call last):
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
app           |     response = self.full_dispatch_request()
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
app           |     rv = self.handle_user_exception(e)
app           |   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
app           |     return cors_after_request(app.make_response(f(*args, **kwargs)))
app           |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
app           |     return original_handler(e)
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
app           |     reraise(exc_type, exc_value, tb)
app           |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
app           |     raise value
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
app           |     rv = self.dispatch_request()
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
app           |     return self.view_functions[rule.endpoint](**req.view_args)
app           |   File "/usr/src/app/backend/__init__.py", line 60, in index
app           |     return render_template("index.html")
app           |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
app           |     ctx.app.jinja_env.get_or_select_template(template_name_or_list),
app           |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
app           |     return self.get_template(template_name_or_list, parent, globals)
app           |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
app           |     return self._load_template(name, self.make_globals(globals))
app           |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
app           |     template = self.loader.load(self, name, globals)
app           |   File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
app           |     source, filename, uptodate = self.get_source(environment, name)
app           |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
app           |     return self._get_source_fast(environment, template)
app           |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
app           |     raise TemplateNotFound(template)
app           | jinja2.exceptions.TemplateNotFound: index.html`

**Comment by chas678** [comment]
```
app           | 172.18.0.1 - - [14/May/2020 21:28:04] "GET / HTTP/1.1" 500 -
app           | [2020-05-14 21:28:26,692] ERROR in app: Exception on / [GET]
app           | Traceback (most recent call last):
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
app           |     response = self.full_dispatch_request()
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
app           |     rv = self.handle_user_exception(e)
app           |   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
app           |     return cors_after_request(app.make_response(f(*args, **kwargs)))
app           |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
app           |     return original_handler(e)
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
app           |     reraise(exc_type, exc_value, tb)
app           |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
app           |     raise value
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
app           |     rv = self.dispatch_request()
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
app           |     return self.view_functions[rule.endpoint](**req.view_args)
app           |   File "/usr/src/app/backend/__init__.py", line 60, in index
app           |     return render_template("index.html")
app           |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
app           |     ctx.app.jinja_env.get_or_select_template(template_name_or_list),
app           |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
app           |     return self.get_template(template_name_or_list, parent, globals)
app           |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
app           |     return self._load_template(name, self.make_globals(globals))
app           |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
app           |     template = self.loader.load(self, name, globals)
app           |   File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
app           |     source, filename, uptodate = self.get_source(environment, name)
app           |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
app           |     return self._get_source_fast(environment, template)
app           |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
app           |     raise TemplateNotFound(template)
app           | jinja2.exceptions.TemplateNotFound: index.html
```

**Comment by JorgeMartinezG** [comment]
@chas678 thank you for raising this issue. Right now, since frontend and backend are separated in master branch, docker is outdated. This issue is not fully related to docker. Also, docker changes are managed within a different branch: https://github.com/hotosm/tasking-manager/tree/feature/docker. We need to merge the branch after successfull tests and review

**Comment by maxgrossman** [comment]
@JorgeMartinezG - first thanks for all your work on this project everyone loves. I was fiddling with the 4.0.5 tagged branch and think that this error is due to the build folder made in npm build not being preserved after the `app` container is built. 

To test this theory I added a volume in the docker compose to preserve that folder. I seem to be able to get docker running. Is this worth a pr or even of interest? I'm also ok with letting the docker branch come along and replace current set up.

To be more specific I just added `- /usr/src/app/frontend/build` under [this line](https://github.com/hotosm/tasking-manager/blob/develop/docker-compose.yml#L21)

**Comment by JorgeMartinezG** [comment]
Thank you for commenting @maxgrossman . The team is currently making releases that include bugs and design fixes. I have not brought back the docker support yet, but it is in our plans. I will notify once I rebase the branch with latest changes and retake this.

**Comment by maxgrossman** [comment]
thank you @JorgeMartinezG!

**Comment by willemarcel** [comment]
@maxgrossman a lot of changes happened since May. Is this issue solved for you?

**Comment by bopercival-hot** [comment]
stale, closed.
