### ISSUE TITLE
Number of users to be added to teams at a time

### ISSUE THREAD

**Issue by canunen** [hotosm/tasking-manager#2960]
I have started setting up our local teams on TM4 and realized that I could add 10 OSM users at a time, the user names after 10th were not added to the team. I selected edit again, and was able to add the omitted users then. 

If removing the limitation is not possible, I'd suggest adding an info text to the managers above or below the box where they add team members manually.

**Comment by willemarcel** [comment]
@canunen I tried to reproduce it, but I couldn't. I was able to add more than 10 users at a time

**Comment by willemarcel** [comment]
@canunen would you be able to record your screen or look on the terminal for some errors?

**Comment by canunen** [comment]
Thanks for reaching out @willemarcel. I didn't get any errors but realized that the people after the 10th user were not added to the team. I'll try againand let you know.

**Comment by canunen** [comment]
Hi @willemarcel, I added 10+ users to a mock team.
![Screenshot from 2020-05-27 19-24-45](https://user-images.githubusercontent.com/13434280/83046683-07635680-a050-11ea-9fed-5eb026d18738.png)

Some of them were not visible at the panel after the confirmation. 
![Screenshot from 2020-05-27 19-25-03](https://user-images.githubusercontent.com/13434280/83046687-07fbed00-a050-11ea-9450-29bca561557f.png)

However when I returned back to the team page, I saw that althoug not visible at the initial dialog, the users were added. 
![Screenshot from 2020-05-27 19-25-38](https://user-images.githubusercontent.com/13434280/83046691-08948380-a050-11ea-8173-0a97404934b0.png)

**Comment by canunen** [comment]
I've added 10+ accounts to a mock team:
![screen1](https://user-images.githubusercontent.com/13434280/83050064-a5f1b680-a054-11ea-9463-018b944e4e20.png)

Not all of the mwere visible at the panel after submission:
![screen2](https://user-images.githubusercontent.com/13434280/83050068-a722e380-a054-11ea-8bb3-6440f9375e97.png)

After navigation to other pages and re-opening the team page, all added users were visible. This is why I thought there was a 10 user limit at the first place. 
![screen3](https://user-images.githubusercontent.com/13434280/83050072-a8eca700-a054-11ea-97b5-13dbb104bb1d.png)

**Comment by bopercival-hot** [comment]
user resolved. Closed.
