### ISSUE TITLE
Missing user on project contributions endpoint

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2983]
![image](https://user-images.githubusercontent.com/666291/82474698-d27c6000-9aa1-11ea-811b-78276bfc1e1a.png)

@wireguy worked on this project, but the `/api/v2/projects/8470/contributions/` endpoint doesn't return his name

**Comment by wireguy** [comment]
not just me, also  DEO NISHIMWE and Awania Moris,  if that helps with debugging.
