### ISSUE TITLE
Imagery offset saved across sessions

### ISSUE THREAD

**Issue by jflasher** [hotosm/tasking-manager#2992]
I could see how this may actually be a feature, but the Imagery Offset I set for one task was carried over when I opened up a new task. Flagging in case it's not the intended behavior.

**Comment by willemarcel** [comment]
@jflasher It's a behaviour defined by iD.

I think it would be a good idea to allow the project managers to set the offset for a defined imagery source, and we could pass it to iD and JOSM. However neither JOSM and iD APIs supports it right now.
