### ISSUE TITLE
Add feenster to Thinkwhere team

### ISSUE THREAD

**Issue by hunt3ri** [hotosm/tasking-manager#3]
Hi @smit1678 

We can't add our colleague Ian Feeney to the thinkwhere team because he's not part of the Github HOT organisation.  

Could you add @feenster to project

Thanks
Iain

**Comment by smit1678** [comment]
Done! Ah I thought that by having you as a Team Maintainer this would prevent any blocking of adding new folks, but I guess that's not the case. Just open tickets up, or ping on Slack, and I'll get them adding quickly.

**Comment by hunt3ri** [comment]
Thanks @smit1678 👍
