### ISSUE TITLE
Adjusting a users role results in an error message

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#306]
When I visit this url logged in:

http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/user/michael63

and try to set michael as an admin, I get the error message:

"An error occurred when setting the role."

**Comment by popelnuh** [comment]
Hi Blake,

Can you press Ctrl+F5 and try again please?

Thank you,

Zlata

**Comment by bgirardot-np** [comment]
Works now.
