### ISSUE TITLE
Improve Message Center (no refresh on delete)

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#3070]
Hello,

When deleting a message from the inbox/message center, the filters & page number resets. This can be really annoying when you've received about a dozen task messages and at least a handful of team requests in a day and now you're looking at page x of 30; hit delete and your back to page 1 with filters cleared. It would be much better if the message just deletes and leaves you where you were.

**Comment by russdeffner** [comment]
This is still occuring

**Comment by Aadesh-Baral** [comment]
I believe this can be closed since it has been resolved in #5136.
