### ISSUE TITLE
Unable to opt-out of notifications (instructions in notification email are wrong)

### ISSUE THREAD

**Issue by danstowell** [hotosm/tasking-manager#3075]
I've got all these notifications in TM4, and they say:

> Please note: You can opt-out of these automated validation messages by visiting your User Profile and clicking "Edit-Add Contact Details."

But I can't find a way to do that. There's no "Edit-Add Contact Details". I've hunted around for it! Is the text old, from TM3?

The immediate fix is to update the text, I presume. But we could also link directly to that target page, rather than users having to hunt for it?

![Screenshot from 2020-06-02 21-14-41](https://user-images.githubusercontent.com/202965/83565907-1433ee80-a517-11ea-8a47-2b4c81691297.png)

**Comment by Nick-Tallguy** [comment]
I'm also receiving these as emails with the text reading:

Hi Tallguy

You have a new message on the HOT Tasking Manager.

Click here to view it..

Many thanks,
Humanitarian OpenStreetMap Team

Please note: You can now opt-out of all automated validation
messages by visiting your User Profile and clicking "Edit-Add Contact Details."

**Comment by danstowell** [comment]
Thanks for working on this. Can we make the text clearer though? The new text says we opt out by going to "User Profile Settings and choosing which notifications you want to receive". But it doesn't tell us **which** box to un-tick - I still don't know how to opt out!

A great approach would be to have an "Unsubscribe" link directly in the email, which carries out the desired action.

**Comment by danstowell** [comment]
(I'd like to re-open this issue but I guess I don't have that privilege myself)

**Comment by willemarcel** [comment]
I opened a new issue with updated details: https://github.com/hotosm/tasking-manager/issues/3766
