### ISSUE TITLE
Support markdown on task comments

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#3134]
Using images to give feedback to mappers is a very good idea, so we should support markdown on task comments.

**Comment by Janabau** [comment]
Hi, I sent a few thank you messages on our MSF tasks and the entire text is still in one chunk, no lines, and hyperlinks are not visible. Adding images would be nice, but we have found a workaround, we upload them on Missing Maps twitter and share a link. Therefore, what is needed more is a quick fix to allow basic formatting, to at least distinguish lines and hyperlinks to other onlines content.

**Comment by willemarcel** [comment]
@Janabau Now it's solved (the deploy to production will be tonight). You can drag and drop images to automatically upload it to our CDN and TM will add the markdown comment. You can also use any markdown tag. To break lines, let one line space between paragraphs.
