### ISSUE TITLE
Remove duplicated tasks from backend

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#3141]
Per discussion w/ @JorgeMartinezG and @willemarcel - we have identified [duplicated task geometries](https://docs.google.com/spreadsheets/d/1xodq-8qavryA5Z3HQagxUmK28ASzxDI_aqbs9Z3LK0o/edit#gid=0) in our backend. This could have come from the frontend libraries that were doubling up the task split based on the polygons that it was intersecting. For now, we gave switched the function to be handled by backend libraries. However, we need to clean up the existing duplicated data on tasks. Maybe a one-off sql script can help us.

**Comment by willemarcel** [comment]
Related to https://github.com/hotosm/tasking-manager/issues/3067
