### ISSUE TITLE
Improve backend dependencies file

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#3147]
We have all the development and application dependencies listed under a single `requirements.txt` Separating the dependencies will be useful for clean installation and uninstallation in different environments.

**Comment by ramyaragupathy** [comment]
After careful investigation, it is better to keep it all one file - however cleaned up to include only direct dependencies - #3203

**Comment by willemarcel** [comment]
@ramyaragupathy can we close it then?

**Comment by ramyaragupathy** [comment]
good to close
