### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Mashin6** [hotosm/tasking-manager#3151]
When I leave Tasking manger (https://tasks.openstreetmap.us/) open in background tab in Chrome (Version 83.0.4103.97 (Official Build) (64-bit)) for some time, after a while the Google Chrome Helper (renderer) process uses 60% of my CPU.

macOS 10.15.5

**Comment by willemarcel** [comment]
@Mashin6 that TM instance runs on the version 3. We're not maintaining that version any more. Let us know if you have the same issue on https://tasks.hotosm.org
