### ISSUE TITLE
Task stats in User DTO 

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#3175]
`/users/queries/username` endpoint is missing details on task stats - mapped/validated/invalidated

**Comment by willemarcel** [comment]
@ramyaragupathy those stats are available on `/api/v2/users/<username>/statistics/` and I prefer to concentrate the stats on that endpoint. We already get too much data on the login.

**Comment by ramyaragupathy** [comment]
Agree with you @willemarcel - as long is this data point is not used on the frontend for any other page, I am ok to remove it
