### ISSUE TITLE
improve the loading of the project relationship

### ISSUE THREAD

**Issue by NoemiNahomy** [hotosm/tasking-manager#3213]
The `/api/v2/projects/{project_id}/ `  uses this [line](https://github.com/hotosm/tasking-manager/blob/1f6be9c94cbde044a62dc2bd949d0a5f69ed2146/backend/models/postgis/project.py#L364), internally the orm makes the cartesian product. Project is a main table and it has a lot of relationships.

I suggest disabling these relationships for this query.
for example: 
```
Project.query.options(
            orm.noload('tasks'), orm.noload('messages'), orm.noload('project_chat')
        ).get(project_id)
```
or 
```
project_chat = db.relationship(ProjectChat, lazy="noload", cascade="all")
tasks = db.relationship(
        Task, backref="projects", cascade="all, delete, delete-orphan", lazy="noload"
    )
```

**Comment by willemarcel** [comment]
@NoemiNahomy is it solved already?

**Comment by NoemiNahomy** [comment]
Yes
