### ISSUE TITLE
existing project validation

### ISSUE THREAD

**Issue by NoemiNahomy** [hotosm/tasking-manager#3265]
I suggest optimizing the validation of projects that are used in many endpoints.
fox example: 
In api contributions:
https://github.com/hotosm/tasking-manager/blob/1d28a65bbbcc5a4a9c2def223d8e24d074620dcb/backend/api/projects/contributions.py#L32
In api comments:
https://github.com/hotosm/tasking-manager/blob/1d28a65bbbcc5a4a9c2def223d8e24d074620dcb/backend/api/comments/resources.py#L115

**Comment by willemarcel** [comment]
@NoemiNahomy Is this this issue already resolved?

**Comment by NoemiNahomy** [comment]
Yes, this the corresponding PR https://github.com/hotosm/tasking-manager/pull/3266
