### ISSUE TITLE
[project-stats] Add contributors statistics to the project stats page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#3271]
Show statistics about contributors on projects stats, like
- [x] Contributors by mapping level
- [x] Contributors registration day

Some other interesting possibilities:
- Average tasks by users
- Gender
- Location

**Comment by khyati18** [comment]
@willemarcel I would like to work on this issue.

**Comment by willemarcel** [comment]
@khyati18 We have solved the first two items with #3314. I think it's better to wait for user feedback before start working on the remaining topics, but if you want to propose an improvement or something new, feel free to do it.

**Comment by willemarcel** [comment]
Closing it. If we feel the need of more statistics, we'll open new issues
