### ISSUE TITLE
Include in the project stats dashboard the number of features added

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#3339]
Add a section similar to the one that we have on the user detail page based on the leaderboard API data.

**Comment by SColchester** [comment]
This would be really valuable! Is there any chance of adding the project size in km2?

**Comment by yunjuc** [comment]
So we are looking at adding a section with **buildings, roads, points, and waterways** data points, any other data should be included? And what about the order, should it be at the top/bottom, else?

I'm also thinking about adjusting the project stats layout a bit. Right now it's a mix of banner and card patterns, I want to make it all cards. I think it will look cleaner and also be consistent with the user stats page.

**Comment by willemarcel** [comment]
> So we are looking at adding a section with buildings, roads, points, and waterways data points, any other data should be included?

I think it's only that

> And what about the order, should it be at the top/bottom, else?

I believe the best place is after 'tasks by status" section

> I'm also thinking about adjusting the project stats layout a bit. Right now it's a mix of banner and card patterns, I want to make it all cards. I think it will look cleaner and also be consistent with the user stats page.

It makes sense! 👏🏾

**Comment by willemarcel** [comment]
Solved with #3690 #3681
