### ISSUE TITLE
Improve sign up error message

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#3344]
![image](https://user-images.githubusercontent.com/666291/87780517-44082e80-c805-11ea-95f2-78ee5fb51b91.png)

This error is probably occurring because that email address is already registered, So we need to show a better message to the users.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@willemarcel can you provide more information on this issue? I have a hard time reproducing it. Is it possible you have two accounts with the same e-mail address?
See,
https://github.com/hotosm/tasking-manager/blob/3d86c0dc967705cbbe9a26bffcc2a923e5698903/backend/services/users/user_service.py#L777-L779
where `one_or_none()` can raise `MultipleResultsFound` if multiple e-mails are found. It is handled in,
https://github.com/hotosm/tasking-manager/blob/3d86c0dc967705cbbe9a26bffcc2a923e5698903/backend/api/users/actions.py#L343-L349

Other than by having two identical e-mail addresses, I have a hard time not getting the correct error message, `f"Email address {user_dto.email} already exists"` shown.

**Comment by willemarcel** [comment]
Sorry for the delay on answering you, @k3KAW8Pnf7mkmdSMPHz27. I confirmed it is working correctly. I just improved the frontend validation and error display with https://github.com/hotosm/tasking-manager/pull/3660

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Ok, no worries and great that it is working that it should!
I added some suggestions in #3662 for back-end changes related to detection of multiple e-mail addresses, feel free to add/change/discard the PR as it only indirectly relates to this issue.
