### ISSUE TITLE
Change "Project updates" settings text

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#3357]
![image](https://user-images.githubusercontent.com/666291/87967473-3d8fe600-ca95-11ea-8b19-ad605d4c69ec.png)

Rewrite to "Receive a notification every time a task you mapped is marked as Finished or More mapping needed.", as these are the only actions that are triggering that type of notifications.

**Comment by russdeffner** [comment]
Would also say this isn't "Project updates" but "Task Updates" or maybe "Task Status (Updates)"

**Comment by ramyaragupathy** [comment]
Capturing the current behaviour on Project updates - this is for the overall progress of projects that a user has contributed to or favorited. This is different from Task-related notifications. I would suggest adding it as a different category - as Task updates notifications.

**Comment by willemarcel** [comment]
![image](https://user-images.githubusercontent.com/666291/89298252-6ee2e700-d63b-11ea-9d57-2d7b851c2f63.png)
We added the tasks type and let the project updates type as it was previously
