### ISSUE TITLE
osmstats-api wildcard endpoint

### ISSUE THREAD

**Issue by aaj013** [hotosm/tasking-manager#3359]
I have seen you using a new endpoint ([https://osmstats-api.hotosm.org/wildcard?key=hotosm-project-*](https://osmstats-api.hotosm.org/wildcard?key=hotosm-project-*)) for getting more stats to tasking manager home page recently. But I could not find a documentation for the corresponding route anywhere in github. Are you using any fork of osm-stats project for [this](https://osmstats-api.hotosm.org) or any other api? Please help, I am also looking for deploying a similar api.

**Comment by willemarcel** [comment]
@aaj013 The documentation is available at https://github.com/hotosm/osmstats-wildcard-api/

**Comment by aaj013** [comment]
> @aaj013 The documentation is available at https://github.com/hotosm/osmstats-wildcard-api/

Thank you.
