### ISSUE TITLE
project search api country field has mixed languages

### ISSUE THREAD

**Issue by jarmokivekas** [hotosm/tasking-manager#3374]
The `api/v2/projects/` endpoint includes a `country` field in the returned data. The value of he field is sometimes inconsistent with the other projects in the same country. For example, sometimes there is both `Brasil` and `Brazil`, or `Democratic Republic of the Congo` and `République Démocratique du Congo`

I ran across this writing some report automation for a current activation. Project split into tables by country:
![image](https://user-images.githubusercontent.com/3074453/88275843-b934a180-cce6-11ea-875a-133c349a7f1f.png)

I'm guessing this is based on the locale set for the TM project?

As a data user I would like to have either:
1. always use the English name (which it usually is currently)
1. always use an ISO country code
1. always use the local name

**Comment by willemarcel** [comment]
Solved with #3669. It'll be deployed to production in some hours.

**Comment by jarmokivekas** [comment]
I have returned to work with this type of data, and I'm grateful this change has been made :)
