### ISSUE TITLE
Got email notification but there is no new message on the tasking manager

### ISSUE THREAD

**Issue by Fanevanjanahary** [hotosm/tasking-manager#3385]
Hi,
I got 30 emails notification in 9 hours saying that I have new message but actually there is no message on the HOT tasking manager.

Thank you

![image](https://user-images.githubusercontent.com/12623986/88374260-21948900-cda2-11ea-9184-377ce8acc2a2.png)

**Comment by ramyaragupathy** [comment]
Hi @Fanevanjanahary - can you please confirm if this is your OpenStreetMap user ID -https://www.openstreetmap.org/user/Athena%20Santiago

**Comment by ramyaragupathy** [comment]
I see this comes from an email mix up issue, reported a few months ago - correcting the other user profile for the mail information

**Comment by Fanevanjanahary** [comment]
Hi @ramyaragupathy, it's not my osm ID. 

Yes I have opened that issue you told about,  this #2880

Thank you

**Comment by willemarcel** [comment]
@Fanevanjanahary I believe the issue is solved now. Let us know if you face some other problem
