### ISSUE TITLE
Cannot redact location information from Profile > Settings page

### ISSUE THREAD

**Issue by SColchester** [hotosm/tasking-manager#3435]
In the Profile > Settings page if you add a city and press Save it keeps that city. However if you return to Settings to delete that field and press save nothing happens. After deleting the text, pressing save and refreshing the page the old city name continues to populate. 
![Annotation 2020-08-06 171534](https://user-images.githubusercontent.com/43822967/89556387-385ac700-d809-11ea-9c5d-309a3c3f5342.png)

**Comment by willemarcel** [comment]
@ramyaragupathy @JorgeMartinezG that is a problem in users update endpoint in general.

**Comment by Aadesh-Baral** [comment]
With #5265 merged in i think this issue can be closed now.
