### ISSUE TITLE
Improve mention email content

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#3461]
- Include the username that mentioned you
- Include a link to the project page

![image](https://user-images.githubusercontent.com/666291/90032990-56a34580-dc95-11ea-9e64-d3cceda8afda.png)

**Comment by max-keviv** [comment]
@willemarcel  
Is this fine or there needs some changes
![image](https://user-images.githubusercontent.com/59287619/90519438-a5654980-e185-11ea-899d-1aede5f0473c.png)

**Comment by willemarcel** [comment]
@max-keviv I would only rephrase to "{user} mentioned you in a comment on Project #1" and  "{user} mentioned you in a comment on Task 123 of project #1"

**Comment by max-keviv** [comment]
@willemarcel should   'Task 123'  be linked

**Comment by willemarcel** [comment]
@max-keviv yes, it can be linked

**Comment by max-keviv** [comment]
@willemarcel  can you review my  PR #3497

**Comment by willemarcel** [comment]
Replaced by #3614
