### ISSUE TITLE
Filter and map interface

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#347]
When I ran a filter I expected the map interface to show all project locations for that filter and the list/grid to show the priority tasks. Instead the map only shows the first 4 (from the grid/list view). This means I need to scroll through screens rather than being able to choose from the map interface. This seems counter intuitive to me. Surely all results of the filter should show on the map interface?

**Comment by ethan-nelson** [comment]
Can you check whether this is still a bug or works as expected now? It looks like a related issue was solved with a few pull requests. Thanks!

**Comment by tastrax** [comment]
Yep - looks to be working correctly now
