### ISSUE TITLE
Archived projects appearing in list and Grid view

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#348]
Inactive projects appearing in list and Grid view - refer also to #260

**Comment by hunt3ri** [comment]
Thanks @tastrax can you give me the project IDs that you are seeing.

**Comment by tastrax** [comment]
on the main page for TM3

http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/contribute

2646, 2648, 2651, 2666

**Comment by tastrax** [comment]
If archived projects are to remain in the lists then they need to be identified in some way (and also be available to search). Maybe the public interface has archived projects completely removed.

**Comment by hunt3ri** [comment]
Hi @tastrax it looks like this is because the TM2 dataset we used was from @bgirardot and is now over a month old, so I guess these projects were active at the time and have now been archived.  We'll use a fresh dataset when we go to the official switch on.

 I'll close this issue for now.
