### ISSUE TITLE
Mapped calculation error

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#349]
Appears its possible to map more than 100 percent of a project
![capture](https://cloud.githubusercontent.com/assets/8775395/26299106/f7c0b156-3f1c-11e7-856f-65db1b1a35fd.JPG)

**Comment by hunt3ri** [comment]
Thanks @tastrax yeah we saw this one, hopefully have a fix soon 😄

**Comment by hunt3ri** [comment]
Hi @tastrax we've made some changes to fix this.  If it looks close, please fix

**Comment by tastrax** [comment]
Looks correct
