### ISSUE TITLE
Check if email is verified before sending messages

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#3498]
Per chat w/ @willemarcel and user requests, it is necessary to check if email is verified before sending any message notifications to the user

**Comment by teymour-aldridge** [comment]
Has this been completed?
I'd be happy to do it if not (and nobody else is working on it 🙃).

**Comment by willemarcel** [comment]
@teymour-aldridge Your help on this issue would be much welcomed. Feel free to work on it and open a PR. Let us know if you need some help.

**Comment by teymour-aldridge** [comment]
Thanks!
