### ISSUE TITLE
New docker installation can't create projects

### ISSUE THREAD

**Issue by EdLoach** [hotosm/tasking-manager#3503]
Browser is blank after brief red whirling animation and flash of text at top of page too brief to read. Browser inspect element/console shows 
```
Uncaught TypeError: ee is not a constructor
    at a.default (index.js:127)
```
Same in Opera, Chrome, Firefox and Edge. I've successfully added an Organization, Team, Campaign and Category using the other options on the Manage page, but 
http://localhost/manage/projects/new/
always ends up looking blank. (I've verified my email address and used psql to set me as admin to get as far as the Manage menu).

**Comment by GeoMechain** [comment]
Problem also encountered, was it followed? I specify that this is also a local installation as indicated in the documentation (installation with docker). The access is done by http:/localhost/ and not by http:/127.0.0.1:5000/ or even http:/127.0.0.1:80/

**Comment by jayenashar** [comment]
i'm also having the same issue.  using commit 575c92fcb450fb2c5795f90835c277a3e524f61f .  i think the issue is that MapboxDraw is capitalized and react thinks it's a component.  i'm about to try lowercasing it to see if it does the trick.

**Comment by jayenashar** [comment]
ah no.  looks like an es6/webpack thing where you need require().default.  will submit a patch soon

**Comment by willemarcel** [comment]
@jayenashar actually I think the problem on that dockerfile is that npm installs an incorrect version of mapbox-gl-draw. We should be using `yarn` instead of `npm`.
cc @frafra

**Comment by jayenashar** [comment]
oh god yes, please use yarn

**Comment by jayenashar** [comment]
this patch worked for me:

```
diff --git a/frontend/src/components/projectCreate/index.js b/frontend/src/components/projectCreate/index.js
index 60d6ca7b..98791d18 100644
--- a/frontend/src/components/projectCreate/index.js
+++ b/frontend/src/components/projectCreate/index.js
@@ -1,4 +1,5 @@
 import React, { useState, useLayoutEffect, useCallback } from 'react';
+import MapboxDraw from '@mapbox/mapbox-gl-draw';
 import { useSelector } from 'react-redux';
 import { Redirect } from '@reach/router';
 import { useQueryParam, NumberParam } from 'use-query-params';
@@ -16,8 +17,6 @@ import { MAX_AOI_AREA } from '../../config';
 import { AlertIcon } from '../svgIcons';
 import '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw.css';
 
-const MapboxDraw = require('@mapbox/mapbox-gl-draw');
-
 const aoiPaintOptions = {
   'fill-color': '#00004d',
   'fill-opacity': 0.3,
diff --git a/frontend/src/components/projectEdit/priorityAreasForm.js b/frontend/src/components/projectEdit/priorityAreasForm.js
index 41365bfc..8ff9bd75 100644
--- a/frontend/src/components/projectEdit/priorityAreasForm.js
+++ b/frontend/src/components/projectEdit/priorityAreasForm.js
@@ -2,6 +2,7 @@ import React, { useState, useContext, useLayoutEffect } from 'react';
 import { useSelector } from 'react-redux';
 import mapboxgl from 'mapbox-gl';
 import 'mapbox-gl/dist/mapbox-gl.css';
+import MapboxDraw from '@mapbox/mapbox-gl-draw';
 import MapboxLanguage from '@mapbox/mapbox-gl-language';
 import DrawRectangle from 'mapbox-gl-draw-rectangle-mode';
 import { FormattedMessage } from 'react-intl';
@@ -11,8 +12,6 @@ import { StateContext, styleClasses } from '../../views/projectEdit';
 import { Button } from '../button';
 import { MAPBOX_TOKEN, MAP_STYLE, MAPBOX_RTL_PLUGIN_URL } from '../../config';
 
-const MapboxDraw = require('@mapbox/mapbox-gl-draw');
-
 mapboxgl.accessToken = MAPBOX_TOKEN;
 try {
   mapboxgl.setRTLTextPlugin(MAPBOX_RTL_PLUGIN_URL);
```

**Comment by frafra** [comment]
We should avoid using different installation methods between Docker and non-Docker setups. If yarn is the preferred way to install dependencies, we should discontinue npm support and use yarn everywhere.

Nonetheless, the patch makes sense independently of the package manager.

**Comment by jayenashar** [comment]
what i usually do is have scripts like `setup-db.sh`, `setup-frontend.sh`, `setup-backend.sh`, etc. and then call those scripts from the Dockerfile and also from a `setup-all.sh` script.  then i don't have to maintain two installers separately.  (just an idea, not saying i have time to make a PR.)

**Comment by frafra** [comment]
@jayenashar I totally agree with that kind of approach. Dockerfiles and CI definitions should be as slim as possible in my opinion, thus reusing code from the non-containerized setup. A separate issue for that should be created.
