### ISSUE TITLE
Small JOSM overview map

### ISSUE THREAD

**Issue by SColchester** [hotosm/tasking-manager#3512]
Seen in Chrome. Launching a task with JOSM editor selected - occasionally the overview map is crushed into the upper-left hand corner of the Tasking Manager at ~1/3 of normal size.

![Annotation 2020-08-21 114115](https://user-images.githubusercontent.com/43822967/90883391-a07ee080-e3a5-11ea-8e95-640358b62a33.png)

**Comment by wireguy** [comment]
@SColchester:
Work around for this is to click on the webpage (not on the map), and press Ctrl +, then Ctrl - (or Ctrl scrollwheel back and forth).
This forces the browser to resize the webpage and then resize it back the way you had it.   It's a no-op, but it forces the map control to repaint correctly.
