### ISSUE TITLE
Overuse of 'The imagery is bad'

### ISSUE THREAD

**Issue by SColchester** [hotosm/tasking-manager#3514]
Seen in lots of projects (for example - see Questions and comments section: https://tasks.hotosm.org/projects/9144)

'The imagery is bad' seems to be overused because often it is difficult mapping, not because the imagery is actually missing, cloudy or too bad to map with. This might be improved with a terminology change or possibly having the option less prominent.

Releasing these tasks back to available for mapping is time consuming - it has to be done one at a time. Would it be possible to add a bulk action to the edit page of a project to revert bad imagery tasks?

**Comment by willemarcel** [comment]
Resolved by #4105
