### ISSUE TITLE
Option to open iD editor in it's own tab?

### ISSUE THREAD

**Issue by bmckinlay** [hotosm/tasking-manager#3538]
The previous version of HOT tasking manager would open the iD editor in a separate tab. This would allow me to run a full-screen iD editor session, switching back to the tasking manager in a separate tab to manage the task.

The new version of tasking manager opens an embedded iD editor. I can see how this is more user-friendly for some, but on my small 13" laptop screen, it leaves far less screen real-estate for iD - a poor user experience that makes editing much more difficult.

Is there an option to open iD editor separately (ie: not embedded in the tasking manager interface)? Could this option be added?

Thanks

**Comment by willemarcel** [comment]
@bmckinlay you can press F11 to use iD on full screen mode

**Comment by bmckinlay** [comment]
Huh? Pressing F11 does nothing for me. The tasking manager interface is still taking up a lot of screen space.

I guess a better way to phrase this is: How do I open a stand-alone instance of the iD editor, outside of the tasking manager?

**Comment by bmckinlay** [comment]
@willemarcel OK, I figured it out - it's ctrl-command-F on mac.

But weirdly, only the actual keyboard command works, if you select "View/Enter full screen" from the menu it just gives you a full screen window with the task manager interface still wrapped around it.

It would be good if there as a more obvious way to do this!

**Comment by willemarcel** [comment]
@bmckinlay What we will implement soon is to hide part of the header when iD is loaded, so it will make the screen space quite similar to what you have on osm.org.

It's not on the plan to support opening iD in another window, because we use a different API to load it integrated, and it would cost more to maintain both ways.
