### ISSUE TITLE
Improve task lock error handling on frontend

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#3540]
If the user tries to lock a task, but someone else has already locked it (we refresh tasks states each 60s), it will return those errors:

`ERROR: Task 733 is not MAPPED, BADIMAGERY or VALIDATED [in /tasking-manager/backend/services/validator_service.py:35]`

`ERROR: Task in invalid state for mapping [in /tasking-manager/backend/services/mapping_service.py:28]`

We need to handle it better on the frontend and show a more informative message.

**Comment by HelNershingThapa** [comment]
Closed in 5376cc2a76c9d16bf5f94a6ff9037d3024098b15
