### ISSUE TITLE
Frontend initialization error (nginx docker)

### ISSUE THREAD

**Issue by l-longour** [hotosm/tasking-manager#3589]
Hello I'm installing the tasking manager and so far so good. However once the tasking manager is installed, if I go on **IPv4**:80 (frontend) the server returns a 404 error. I checked the frontend logs:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf differs from the packages version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```

Searching how to patch this error I found the following stackoverflow ticket: [Error trying to run nginx using docker-compose with custom conf.d](https://stackoverflow.com/questions/62214607/error-trying-to-run-nginx-using-docker-compose-with-custom-conf-d) 

So it seems that the frontend initialization script is set for a local installation and not a classical installation as for the official TM. Is there an adaptation ? Is it documented (I didn't find anything on the github doc).

**Comment by GeoMechain** [comment]
It seems to come from the development setup **localhost**:80 works. What do I need to change to be able to access the TM remotely? (like an installation on a VPS).

**Comment by bopercival-hot** [comment]
@l-longour is this still an issue for you? Or has it been resolved?
