### ISSUE TITLE
JOSM remote control doesn't add data layer in second download

### ISSUE THREAD

**Issue by neogeomat** [hotosm/tasking-manager#3613]
On first load of a task to JOSM, osm data boundary and image is added. on loading another task to josm (1st one is completed) only boundary layer is added, data layer is neither added nor the old data layer is updated.

**Comment by willemarcel** [comment]
@neogeomat I could not reproduce that problem. Could you try again and check the browser console for some error?

**Comment by neogeomat** [comment]
It is not happening now
