### ISSUE TITLE
Problems encountered when switching from a local to a remote installation

### ISSUE THREAD

**Issue by GeoMechain** [hotosm/tasking-manager#3618]
Hi - I need to set up a tasking manager. I've followed the numerous indications on the repository and on slack but I'm stuck since a few days on two specific issues (for which the documentation hasn't been of much help).

The first problem concerns the oauth connection. Indeed I set up the remote access as follows: 

```
TM_APP_BASE_URL=http://tasks.gromatici.fr/
TM_APP_API_URL=$TM_APP_BASE_URL
TM_APP_API_VERSION=v2
```

And I also changed all **localhost** values by **tasks.gromatici.fr** in the files docker-compose.yml and docker-compose.override.yml .

At this point if I try to connect (after the make up launch of course) the osm authentication window is empty (about:blank).

If I do the same test in local configuration (VM) and by going to http://localhost instead of http://127.0.0.1:5000 or http://127.0.0.1:80 the authentication window works well and allows me to log in on the TM. Once I'm an administrator (like #1824), I have access to the creation of organization, campaign, but no project (the most important!) the project creation page also sends me an empty (like #3503 ).

**Comment by willemarcel** [comment]
Hi @GeoMechain !

Sorry for the delay on answering you. I've made a change on the example.env file explaining better what to use on those variables: https://github.com/hotosm/tasking-manager/blob/develop/example.env#L6
Let me know if it helps you.

Abou the problem when creating a page, it can be some problem when loading the maps. Were you able to access the explore projects page?

**Comment by jayenashar** [comment]
it might be worth updating the docker instructions to include instructions on how to make it a public server.  it took me a while to figure it out.

**Comment by willemarcel** [comment]
@jayenashar would you like to make a PR with the instructions? We don't use the dockerfiles on HOT...
