### ISSUE TITLE
feature request: add a preset for imagery layer

### ISSUE THREAD

**Issue by d3netxer** [hotosm/tasking-manager#3621]
I have an idea for a new feature. Can project editors add an imagery preset for iD editor (and probably JOSM too)? 

For example a project editor can select "Maxar Standard (Beta)" as the option for their particular project. Then for that project when a mapper selects a square in the project to map, the "Maxar Standard (Beta)" will automatically be loaded instead of Bing imagery?

This new feature request may also require some coordination with the iD developers.

**Comment by willemarcel** [comment]
@d3netxer We already have an issue to that: #3051
We couldn't work on it yet, but it's possible.
