### ISSUE TITLE
PostgreSQL data are not persistent

### ISSUE THREAD

**Issue by frafra** [hotosm/tasking-manager#3647]
It would be nice suggesting how to make PostgreSQL data persistent in Docker. For example:

```
    volumes:
      - postgresql-tm:/var/lib/postgresql/data
```

Or by mounting a local directory:

```
    volumes:
      - /srv/postgresql:/var/lib/postgresql/data
```

**Comment by ramyaragupathy** [comment]
This is already available as part of the docker compose file
