### ISSUE TITLE
Add DueDateBox to Project cards

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#3707]
Option 1:

![image](https://user-images.githubusercontent.com/666291/95640784-d91d6b00-0a74-11eb-89a1-e0bda9825f34.png)

Option 2:
![image](https://user-images.githubusercontent.com/666291/95640812-f94d2a00-0a74-11eb-8007-a792ffd57be1.png)

@russdeffner let me know your thoughts

**Comment by russdeffner** [comment]
I think I like option 1 better, maybe option 2 within one week or something - maybe even more dramatic like red stopwatch and text?
