### ISSUE TITLE
Project team selections cleared when cloned

### ISSUE THREAD

**Issue by SColchester** [hotosm/tasking-manager#3710]
I've been cloning projects which have their validation permissions set to 'Only team members' and the teams specified as 'HOT Global Validators' and 'Validator trainees'. As soon as the project is cloned the original project loses all of the teams specified. The toggle remains on 'Only team members' but the listed teams are cleared below. The new created project retains the specified teams but the original does not.

**Comment by russdeffner** [comment]
Related to #3700

**Comment by willemarcel** [comment]
Resolved by #3811
