### ISSUE TITLE
Auth settings?

### ISSUE THREAD

**Issue by jayenashar** [hotosm/tasking-manager#3719]
[The osm auth settings image](https://github.com/hotosm/tasking-manager/blob/develop/docs/assets/osm-oauth-settings.jpg) does not suggest to check "modify the map" but I've got a user saying it's needed

![osm auth settings](https://github.com/hotosm/tasking-manager/raw/develop/docs/assets/osm-oauth-settings.jpg)

![user report](https://user-images.githubusercontent.com/1137152/95923331-ff3e6480-0e00-11eb-935d-9fc4133fd957.png)

**Comment by willemarcel** [comment]
@jayenashar We forgot to update that image on the transition from TM3 to TM4. That permission is needed by the integrated iD editor.

**Comment by jayenashar** [comment]
thanks for confirming.  i'll make a PR
