### ISSUE TITLE
can't save in iD (with docker setup)

### ISSUE THREAD

**Issue by jayenashar** [hotosm/tasking-manager#3721]
https://www.openstreetmap.org/oauth/request_token is giving me an HTTP 500 error.  it looks like the only parameter is the `Autorization` header, which had an empty string for the `oauth_consumer_key` value.

i discovered that env vars from tasking-manager.env aren't passed to the frontend during the docker build phase (specifically `TM_CONSUMER_KEY`).  and i couldn't figure out how to tell docker compose to use a environment file during the build phase.  i added all of the environment variables separately except the secrets, so now `oauth_consumer_key` has a value but i'm still getting an HTTP 500 error.

i also noticed the frontend uses `REACT_APP_OSM_CONSUMER_SECRET` (which i didn't set during the build) but i'm wondering if that is correct/safe?  it could also be why i'm still getting the 500 error.

also i'm pretty sure `TM_APP_API_URL` should have `/api` in `example env`, but it's overridden in `docker-compose.override.yml` so i guess it makes no difference.

**Comment by willemarcel** [comment]
On the frontend, we copy the `tasking-manager.env` to a `.env.expand` in order to rename some env vars with the prefix REACT_APP_, as it is needed to be accessed by React.

Probably the problem is the `WORKDIR` command in the frontend docker file. I believe the `tasking-manager.env` file on the root dir is not accessible after `WORKDIR` on the frontend folder.

**Comment by jayenashar** [comment]
thanks wille.  still not sure about exposing secrets in the frontend but copying tasking-manager.env into the container works

**Comment by willemarcel** [comment]
iD itself exposes it: https://github.com/openstreetmap/iD/blob/03ca12741f6d1d8c47485abcfc413d0341bbb284/test/spec/services/osm.js#L8
