### ISSUE TITLE
Allow to see comments of multiple tasks

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#3730]
When multiple tasks are selected to validation, allow users to see the comments of tasks.

**Comment by wireguy** [comment]
@willemarcel 
I was thinking about this, and mocked up a presentation idea. 
Each task is in a div.
The black bars are collapsed tasks text.  The red bars are expanded tasks text.


![image](https://user-images.githubusercontent.com/47227325/102112329-89a54380-3e05-11eb-90fe-aaed33ec37de.png)

**Comment by willemarcel** [comment]
@wireguy Thanks for the suggestion, I believe a dropdown would be better to save screen space. I'm including that issue on the next sprint.

**Comment by wireguy** [comment]
@willemarcel A dropdown may save space, but it may not be the best option for validators.   Ask validators about their use cases.  I think the most common would be that they pick a block of 10 to 20 tasks and then want to be able to read all the information from those tasks.   With a dropdown, that means click choose one, then scroll through read the text, then go back and click the second one (or was I already on the third one).   Back and forth.    Okay, maybe Tab back and forth so you can use the keyboard keys.

The other use case I see is that I want to know the comments of one of the tasks in the middle of that block of 20.   Need a way to know which item in the dropdown that task is.

**Comment by wireguy** [comment]
Maybe it should be more like "code folding" in your code dev environment.   I mocked up the same info as above.  Ignore the html tags (just doing it quickly).  
This would save space.   You could have a shortcut key or button to expand all/collapse all, so a validator can scan though all the text.

Maybe when a line with the task's name "Task 97" in this picture, you could highlight where in the map this task is located.

![image](https://user-images.githubusercontent.com/47227325/102349868-035a4000-3f72-11eb-9406-4eaca05623c3.png)

**Comment by wireguy** [comment]
@willemarcel usecase to consider for future iterations...?

The multiple tasks case for a validator that selects many tasks, say 40.
With 40 tasks, you want to minimize  the clicking that the user has to do read the information in the tasks.

- Open all of the accordions with one click or keystroke (ctrl+O for open? E for expand?)
- Link comments/activity checkboxes, to show all comments with 1 checkbox click.  Or, just display 1 set of checkboxes at the top of the accordions (or move the checkboxes above into the 'title' part of the dialog.

**Comment by willemarcel** [comment]
@wireguy I like the idea of having a main comment/activity checkbox. I'll open an issue to it.

I have some concerns about loading all tasks histories in one action, as each task history requires one API request. If we trigger multiple requests at the same time, the user will need to wait more to get the results, the server will need to handle a lot of requests at the same time (impacting the performance for other users), and maybe the user will not even read the history of some tasks.
