### ISSUE TITLE
map canvas changes zoom and centre when Start Editor is activated.

### ISSUE THREAD

**Issue by mfrasca** [hotosm/tasking-manager#3735]
the situation is: I'm mapping within an easy project, using JOSM remote controlled, I am browsing the tasks from the map, and I'm doing adjacent areas, as to reduce network traffic with aerial imagery.
I select a tile/task, and I go to this part of the interface:
![image](https://user-images.githubusercontent.com/122869/96352394-6caff680-1088-11eb-9a48-1eff1241c9f6.png)
I click on `Start Mapping`, and the interface updates itself:
![image](https://user-images.githubusercontent.com/122869/96352410-8a7d5b80-1088-11eb-9593-7adfe7fcc584.png)

at this time, the map looks like this:
![image](https://user-images.githubusercontent.com/122869/96352425-a7199380-1088-11eb-96d6-75767f52f5e7.png)

as soon as I click on `Start Editor`, the map recentres and rezooms, which I find surprising, confusing, and is not what I wish:
![image](https://user-images.githubusercontent.com/122869/96352457-da5c2280-1088-11eb-9a6b-a80510d885a3.png)

**Comment by willemarcel** [comment]
@mfrasca HOT is not maintaining the version 3 of Tasking Manager any more.

**Comment by mfrasca** [comment]
good day @willemarcel, thanks for your reply. I'm using the software as running at the server tareas.openstreetmap.co; should I give them any specific feedback, suggestions?
