### ISSUE TITLE
Request for Priority to the History tab in the TM

### ISSUE THREAD

**Issue by Kraan46** [hotosm/tasking-manager#3740]
Hi TM developers. It would be a good idea for us mappers and validators to have the History tab open first when a task is selected. This would avoid that, as experienced far too often, the user does not read the previous comment(s) and does not take that in consideration when completing the task. Selecting afterwards the Completion tab could than load the task to the default editor of the user.

**Comment by willemarcel** [comment]
@Kraan46 We already have that issue: https://github.com/hotosm/tasking-manager/issues/3507

We have discussed your request previously on the user group meetings, and we consider that we need to show the completion tab by default, if not, users will not have the context of what they need to do after mapping.

**Comment by Kraan46** [comment]
I am surprised to read users would prefer the present set-up. New on HOT but facing daily the disadvantage of mappers not reading the comments. Would it be possible to organize a poll among experienced mappers and experienced validators?

**Comment by willemarcel** [comment]
The Completion tab gives the context and teaches new users what they need to do. We have the editor on the left side and after mapping you answer the question and submit the task.
![image](https://user-images.githubusercontent.com/666291/97165400-64c81480-1762-11eb-9452-0252481b8e57.png)

----

Now imagine you are a new user, and after locking a task you see that:

![image](https://user-images.githubusercontent.com/666291/97165469-7f01f280-1762-11eb-9b50-978ac7c66187.png)

It doesn't provide the information of what you should do after mapping.

The history usually has a lot of state changes, sometimes the comments are not very clear... Exposing a lot of text to the user doesn't give us any warranty they will read and understand it.

The solution I proposed on #3507 is to always show the completion tab and, if the task was invalidated previously and has a comment, add a popup asking the user to read the comments, or just show the last comment on a popup over the map.
