### ISSUE TITLE
Due date does not allow weekends

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#3828]
This should be obvious, but I may want to have a project due on say Sunday, so that the data is ready to deliver Monday morning. I don't actually see any reason to restrict the due date at all but probably was just overlooked in the settings as I was unable to select November 15, 2020 from either the calendar or manually entering the date in project 9765.

**Comment by willemarcel** [comment]
@russdeffner I didn't notice that restriction was set. Fixing it now and I'll deploy it to production until tomorrow.

**Comment by willemarcel** [comment]
@russdeffner production is updated with a fix to that issue.

**Comment by russdeffner** [comment]
Great, thanks for the quick fix @willemarcel
