### ISSUE TITLE
User Profile - Previous (imported) projects on map seem wrong place

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#388]
I noticed on a user that the projects shown on their user profile map seem to be in the wrong place. 

It actually looks like this might be a larger issue as clicking on the project on the map or in the list of previous projects shows mostly missing data.

![2017-05-25_06h40_27](https://cloud.githubusercontent.com/assets/265831/26436268/90a0d9f6-4115-11e7-90d6-29341c7c4f8d.png)

![2017-05-25_06h44_24](https://cloud.githubusercontent.com/assets/265831/26436334/0339e78c-4116-11e7-8c7b-46dab57785a1.png)

**Comment by hunt3ri** [comment]
This is really the same problem as #387 so I'll close as a dupe

**Comment by hunt3ri** [comment]
Re-open to stop other people reporting the same bug

**Comment by hunt3ri** [comment]
@bgirardot I've hopefully resolved this issue, can you confirm.

**Comment by bgirardot** [comment]
Yes, map part working for me now.

Clicking on some projects is still turning up "blank" projects. For example #1410

![2017-05-29_16h36_21](https://cloud.githubusercontent.com/assets/265831/26553710/23425cec-448d-11e7-9b43-7226c275431a.png)

**Comment by bgirardot** [comment]
I am going to close this and open a new issue for the "blank" or "missing" projects
