### ISSUE TITLE
Notification when there is a comment in the general project section

### ISSUE THREAD

**Issue by vdgwebsites** [hotosm/tasking-manager#3912]
The general projectpage comments often contain information that is important to contributors.

There is a TM setting ¨Comments - Receive a notification every time someone posts a comment on projects or tasks you have contributed to.¨

I am not shure, but even when this is enabled contributors won´t get notifications when there is a comment in the general project section.

Could projectpage comments be included when this setting is enabled?

Regards @martien (Slack)

**Comment by vdgwebsites** [comment]
I noticed this is already implemented, so i will close the issue.

**Comment by Martien** [comment]
je bedoelt naw een andere Martien.

**Comment by willemarcel** [comment]
Solved by #4036

**Comment by vdgwebsites** [comment]
Thanks
