### ISSUE TITLE
Need to add angular-translate support for additional languages

### ISSUE THREAD

**Issue by bgirardot-np** [hotosm/tasking-manager#394]
@LindaAlblas I am not sure how difficult this is, I can look at it later today, but on the off chance it is quick for you to do knowing the implementation details of angular-translate, we need to add support for these languages, which are in transifex and as of now, shows how much of the ui is translated into each so far. 

It will be good to get a look at the UI in different languages to see how it adapts, especially non Latin characters.

I do not think any of the languages so far is a right to left language.

Italian (it) 422 strings translated
Japanese (ja) 369 strings translated
Spanish (es) 203 strings translated
German (de) 171 strings translated
French (fr) 142 strings translated
Indonesian (id) 79 strings translated
Chinese (Taiwan) (zh_TW) 59 strings translated
Czech (cs) 59 strings translated
Hungarian (hu) 59 strings translated
Norwegian Bokmål (nb) 59 strings translated
Portuguese (pt) 58 strings translated
Portuguese (Brazil) (pt_BR) 59 strings translated
Russian (ru) 59 strings translated
Slovenian (sl) 59 strings translated
Ukrainian (uk) 57 strings translated
Bengali (bn) 0 strings translated

**Comment by LindaAlblas** [comment]
@bgirardot , I have written some instructions here: https://github.com/hotosm/tasking-manager/wiki/Localisation (see 'adding a new language').

Once local mapping is configured (which gets saved in here: https://github.com/hotosm/tasking-manager/blob/develop/.tx/config), then a 'tx pull' should do the magic.

If a language was added that was not in TM2, then it will have to get added to the config file too.

**Comment by bgirardot** [comment]
I think this is completed.
