### ISSUE TITLE
Facilitate users to continue work on the project

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#3964]
After a task is mapped of validated, we should make it easier to users to continue work on the project.

A good alternative would be after the user press the submit button, don't redirect them to the tasks page and instead show a popup offering a random neighbour task or giving the opportunity to the users to select a task on the map (with the map zoomed in the last task they mapped/validated).

**Comment by Aadesh-Baral** [comment]
Fixed by #5141
