### ISSUE TITLE
"Privacy Policy" link in GDPR popup is broken

### ISSUE THREAD

**Issue by zlavergne** [hotosm/tasking-manager#3976]
When trying to go to the privacy policy, it opens a broken link at `about:blank#blocked`.

**Comment by willemarcel** [comment]
Thanks for reporting, @zlavergne ! It's missing the env var on our circleci context.

**Comment by zlavergne** [comment]
I thought it was something like that :)

**Comment by willemarcel** [comment]
Solved on production.
