### ISSUE TITLE
Docker build does not support TM_IMPORT_MAX_FILESIZE and TM_MAX_AOI_AREA 

### ISSUE THREAD

**Issue by frafra** [hotosm/tasking-manager#4009]
`TM_IMPORT_MAX_FILESIZE` and `TM_MAX_AOI_AREA` are two variables which should be set at build time. They are not set in the frontend Dockerfile, nor they are mentioned in `docker-compose.override.yml` (only `TM_APP_API_URL` is mentioned).

**Comment by andodet** [comment]
@frafra In order to use `docker-compose.yml` and keep all configs living inside `tasking-manager.env` one could rewrite the `make up` command to create a `.env` file at build time:
```makefile
up:
    cp tasking-manager.env .env
    docker network inspect tm-web >/dev/null 2>&1 || \
        docker network create tm-web
    docker-compose -f docker-compose.dev.yml up -d
```
Then it would be just a matter of using the `environment` parameter the same old way in `docker-compose.yml`
