### ISSUE TITLE
Change checkbox to radio button on Task History

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#4038]
A user reported that it would be better to have radio buttons (comments / activities / all) instead of checkboxes on the task history component:

"Also, would radio buttons be better than checkboxes?
With checkbox, you can have the unchecked/unchecked state which shows all items (same as checked/checked).
It's also strange when both are checked, and I want to just see comments that I have to click the activities box.
With radios, you could have   comments, activities, comments and activities (or All).   You only get 1 of them.   If I want comments, I click comments.   So, I'm clicking the thing I want (not what I don't want)."

![image](https://user-images.githubusercontent.com/666291/103532093-60f2f580-4e69-11eb-9dfd-fb7c1b555f24.png)

**Comment by LittleStar21** [comment]
Hi, can I work on this issue?
Thank You

**Comment by willemarcel** [comment]
@LittleStar21 yes, feel free to work on it
