### ISSUE TITLE
./venv/bin/python3.6 manage.py db upgrade error

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#404]
Any idea what the issue is that causes these errors?

I ran this on a brand new, freshly created db with the postgis extension.

https://gist.github.com/bgirardot/3cad9a02ff813a6d66c47e81023957fb

**Comment by bgirardot** [comment]
I did just recently see an error about psycopg2 I had not seen before, in some other context that mentioned I needed to compile it with some additional lib to use some function. Unfortunately I do not remember where I saw that error but is it possible I need to reinstall psycopg2 due to some recently added functionality?

**Comment by bgirardot** [comment]
When I try to login, I get the following error in my browser:

`sqlalchemy.exc.ProgrammingError

sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "users" does not exist
LINE 2: FROM users 
             ^
 [SQL: 'SELECT users.id AS users_id, users.username AS users_username, users.role AS users_role, users.mapping_level AS users_mapping_level, users.tasks_mapped AS users_tasks_mapped, users.tasks_validated AS users_tasks_validated, users.tasks_invalidated AS users_tasks_invalidated, users.projects_mapped AS users_projects_mapped, users.email_address AS users_email_address, users.is_email_verified AS users_is_email_verified, users.twitter_id AS users_twitter_id, users.facebook_id AS users_facebook_id, users.linkedin_id AS users_linkedin_id \nFROM users \nWHERE users.id = %(param_1)s'] [parameters: {'param_1': 359133}]
`

**Comment by bgirardot-np** [comment]
Ethan also had the issue, he gave this feedback:
>In  the file `migrations/versions/9f5b73af01db_.py` and i just deleted/commented out line 24

And he reports that allowed him to carry on with rc1 and things seem to work out ok.

**Comment by hunt3ri** [comment]
Hi @bgirardot that's a bug.  Looks like a column I was using for testing got into the migrations.  I've commited a fix.  Apologies about that
