### ISSUE TITLE
Add horizontal scrolling buttons to ActionTabsNav

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#4047]
![image](https://user-images.githubusercontent.com/666291/103633295-4c276800-4f24-11eb-86d5-2ebfd4845e50.png)

Instead of a scroll bar, we could use some arrows buttons to scroll.

Possible solution: https://stackoverflow.com/questions/56392199/make-a-button-to-scroll-horizontally-in-div

**Comment by wireguy** [comment]
github adds an ellipsis and then a menu.  Chrome adds a sideways chevron >> and a menu.
![image](https://user-images.githubusercontent.com/47227325/103649454-7b41d780-4f2c-11eb-8cd6-a18b80430cea.png)

**Comment by LittleStar21** [comment]
I'd like to work on this.

**Comment by willemarcel** [comment]
@LittleStar21 yes, feel free to work on it
