### ISSUE TITLE
A few observations

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#407]
- Typo in advanced search types of mapping - Land usee
- On an iPad the search box where you enter text is non existent - not a big issue but some shadow/box might be useful (shadow appears on Samsung tablet)
- Nice touch with the Mapswipe reference footer when on tablets (iPad Air 2 and Samsung tablet (portrait only)
- I am hoping I can bookmark the tasking manager with the advanced search already open
- Android tablet shows some sort of code {{'Contribute | translate }} etc etc rather than actual correct text
- I am assuming that grid/list sort order is by Priority and then something else.... last updated (which doesn't show)?

**Comment by bgirardot-np** [comment]
Thank you very much @tastrax !!
Let me follow up after looking at these more.

Thank you so much for looking and putting in you comments, here and slack.

**Comment by bgirardot-np** [comment]
I see Linda already fixed my typo on Land usee :)

**Comment by bgirardot** [comment]
@tastrax I think all of these are now fixed. If not could you please see if the issue already exists and/or re-open this issue?

Thank you very much for helping by testing and leaving issues among the many other things you do :)

So I am closing this, but as I said, if it need re-open or there is actually a follow on issue (can't close the mapswipe dialog for example) please let me/us know.

cheers!
