### ISSUE TITLE
Map project bubbles

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#408]
When clicking/hovering on a project in the map interface just about anything in the northern hemisphere
 gets the project title obscured - Maybe drop the font sizes in the bubbles?

![tm3_map_hover](https://cloud.githubusercontent.com/assets/8775395/26491723/17d4506c-4254-11e7-9f0f-b81b4057bdfb.jpg)

**Comment by bgirardot** [comment]
This behaves correctly if the bubble is outside to area to the left or the right, it moves the map to fit the whole popup into view. It should do the same for top or bottom (granted it will basically never happen on the bottom, but happens pretty often on the top)

**Comment by tastrax** [comment]
Alas, not for me on the top (Chrome or Edge). Edge also gives a few spurious results on the edges as well
![tm3_map_bubble_right_edge_browser](https://cloud.githubusercontent.com/assets/8775395/26827045/c0b841fe-4afe-11e7-83f9-2322d6df6c81.JPG)

**Comment by bgirardot** [comment]
@tastrax Sorry, I was not clear: It does work as it should for left/right, but it does not work as it should for top. It should work the same way for all edges.

**Comment by tastrax** [comment]
No worries

**Comment by LindaAlblas** [comment]
@tastrax @bgirardot this should now be fixed
