### ISSUE TITLE
During project creation 'Create new project' menu item does not work

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#409]
When creating a project if I want to start over, I used to just go to "Create new project" menu item and it would take me back to the beginning to start over. That no longer works and "create new project" seems to do nothing.

The only way to start over is to "back button" until I get to the beginning again.

"Create new project" should always do the same thing, take you to the start of the project creation process.

**Comment by feenster** [comment]
fixed with above PR
