### ISSUE TITLE
Add number of comments information on "My tasks" list

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#4098]
It would be helpful for users if they could see the number of comments each task received on "My tasks" list

![image](https://user-images.githubusercontent.com/666291/104442313-a1dac080-5573-11eb-89ae-c1fb8db6787f.png)

**Comment by Abhirup-99** [comment]
@willemarcel can I work on this?

**Comment by willemarcel** [comment]
@Abhirup-99 yes, you can, although I think maybe it's a bit complex issue

**Comment by Abhirup-99** [comment]
Let me take a stab at it, if I find it difficult I would notify you :). Thanks.
