### ISSUE TITLE
Discard tiny tasks when generating task grid

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#4118]
On the project creation process, it's common to have some super tiny tasks, due to the grid generation process. We should discard tasks that are smaller than a threshold. I believe something around 1000 m² would be good, but we can do a small research to find the better number.

**Comment by willemarcel** [comment]
With **4000m²** threshold:
![image](https://user-images.githubusercontent.com/666291/108427653-48258000-721c-11eb-94ba-ab8e1469855c.png)

With **2000m²** threshold, which seems the ideal to me:
![image](https://user-images.githubusercontent.com/666291/108428393-3e504c80-721d-11eb-8260-2a253cd4bfec.png)

Would it be interesting / necessary to let the Project Manager define the threshold or is it more important to avoid tiny tasks in order to provide a better experience for mappers?

**Comment by SColchester** [comment]
Hi @willemarcel - I like this a lot, I imagine that it will save mappers and validators some grief (pushing a project to from 99% -> 100% often involves jumping around plenty of these tiny tasks and marking them as complete). Having a fixed threshold seems sensible and 2,000 appears to be a good limit. 

However, would it be possible to allow project creators to choose this sort of trim OR the original trim? I worry that where multiple projects in the same campaign are created adjacent to each other the trimming shown above would leave sections that 'fall between' projects and would be left unmapped.

**Comment by willemarcel** [comment]
Thanks, @SColchester! I consider allowing the creators to set the threshold, so if they don't want it, they could set it as zero.

I believe the case of multiple projects around the same region would be better solved with another solution, like for example creating multiple projects from one AoI.

**Comment by willemarcel** [comment]
Proposed a new solution, giving the option to the project manager to discard or not the tiny tasks:
![image](https://user-images.githubusercontent.com/666291/112459627-cd7ce280-8d3c-11eb-9759-78c100ed291e.png)
