### ISSUE TITLE
Check if browser has WebGL support

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#4119]
If a browser doesn't have permissions to use WebGL, the pages with maps will fail to load. We could check it and show a message to the users in case WebGL is not active.

**Comment by Abhirup-99** [comment]
can I work on this?

**Comment by willemarcel** [comment]
@Abhirup-99 yes, feel free to contribute

**Comment by Abhirup-99** [comment]
Thanks, would push a pr shortly.

**Comment by Abhirup-99** [comment]
Can you suggest should I show a custom modal window with the error or an alert box?

**Comment by willemarcel** [comment]
@Abhirup-99 a modal like the ones we use would be good.

**Comment by Abhirup-99** [comment]
![Screenshot from 2021-02-04 05-33-41](https://user-images.githubusercontent.com/48902681/106825300-9b3ef500-66aa-11eb-9bd4-3a11d1c8d6ab.png)
@willemarcel this is what I came up with, does the design look fine? Should I push a pr?

**Comment by willemarcel** [comment]
I was thinking about to show that message only on the pages with maps, but we can consider that option as well. You can start a PR and then I evaluate better
