### ISSUE TITLE
Backend is allowing to lock a task for validation multiple times

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#4127]
When doing multiple task selection, the backend is not checking if some of the tasks are validated. On that case, it should discard those tasks and not lock them for validation again.

Example:
https://tasks-stage.hotosm.org/projects/8579/tasks?search=1
https://tasks.hotosm.org/projects/9973/tasks/?search=4701

**Comment by max-keviv** [comment]
@willemarcel can give steps to produce the error or image of bug
