### ISSUE TITLE
Allow to filter projects by last_updated date

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#4159]
Modify the `/projects` endpoint to include a `last_updated` query param.

**Comment by max-keviv** [comment]
@willemarcel  do you want to include it into api/v2/projects/

**Comment by Sanych** [comment]
Hi @max-keviv. I initially requested for this feature.
You are right. api/v2/projects/ is the right place.

**Comment by max-keviv** [comment]
@willemarcel doesn't /projects endpoint has orderBy query param which has last_updated option

**Comment by Sanych** [comment]
@max-keviv. It is not about sorting. The idea here is to search for projects that were updated after some date-time.

**Comment by max-keviv** [comment]
@Sanych thanks for clearing it
