### ISSUE TITLE
Config files - hard coded host names

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#416]
There are 3 config files I see with hard coded host names:

tasking-manager/client/app/taskingmanager.config.js
tasking-manager/client/taskingmanager.config.json
tasking-manager/server/config.py

Can we eliminate one of the client config files?

Can we adjust the hard coded host names?

I am pretty sure we can eliminate the host name for the client config files and just use the relative paths

not sure about the server config files

are there other config files I am missing that we should document?

cheers
blake

**Comment by LindaAlblas** [comment]
tasking-manager/client/app/taskingmanager.config.js is automatically generated from the tasking-manager/client/app/taskingmanager.config.json. It takes the human readable .json and converts it into a file that Angular can deal with. So we need to keep both but you only need to change the .json.
