### ISSUE TITLE
Improve frontend code splitting

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#4185]
Research about better ways to split the frontend build in order to make it load faster.

**Comment by teymour-aldridge** [comment]
From what I understand, `react-scripts` uses WebPack under the hood, so one way to do this would be to use dynamic imports in places (which WebPack will handle automatically).

One thing I have seen people do to increase perceived page load time is to render React components on the server, by using a Javascript runtime (e.g. V8, Spidermonkey) as a Python extension module.
