### ISSUE TITLE
TypeError: api/v2/projects/{project_id}/comments/tasks/{task_id}/ endpoint

### ISSUE THREAD

**Issue by max-keviv** [hotosm/tasking-manager#4203]
Server response Get comments for a task:
TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
![Screenshot from 2021-02-05 14-15-19](https://user-images.githubusercontent.com/59287619/107011300-77b89f00-67bd-11eb-8a21-38a069d2a8b7.png)

**Comment by willemarcel** [comment]
@max-keviv The body part should be removed from the docstrings.

**Comment by max-keviv** [comment]
@willemarcel  can you please give the Request URL

**Comment by willemarcel** [comment]
https://github.com/hotosm/tasking-manager/blob/develop/backend/api/comments/resources.py#L238

**Comment by bopercival-hot** [comment]
@max-keviv do you consider this issue resolved?
