### ISSUE TITLE
Imported projects - "blank" or "missing"

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#422]
I see some projects listed in my user profile that when I click on them they turn up with "blank" information. They are also not locatable by the 'search' function.

For example #1410

![2017-05-29_16h36_21](https://cloud.githubusercontent.com/assets/265831/26554073/ca0c1738-448e-11e7-9e3f-ce2e17a79311.png)

![2017-05-29_16h37_40](https://cloud.githubusercontent.com/assets/265831/26554082/d1203590-448e-11e7-8609-72f12f792837.png)

**Comment by bgirardot** [comment]
Maybe related:

When I create a new project and do not fill in the required fields, but hit 'save' and then 'go to project' the dsiplay looks exactly same, kind of blank.

Maybe these imported projects either did not have or did not import one of the required fields?

Here is 3807 I just "half" created, did not fill in the required infos.

![2017-05-29_18h40_45](https://cloud.githubusercontent.com/assets/265831/26557020/9e2cbfea-449e-11e7-86b8-55b0455039b1.png)

**Comment by hunt3ri** [comment]
Hi @bgirardot replicated this locally, some weird issue to do with serialising the priority areas as GeoJSON I'll look at this today.

**Comment by hunt3ri** [comment]
Hi @bgirardot I deployed a fix this morning, please retest.  There were a couple of reasons for this problem:

1.  Project not rendering - BUG with priority areas, that I fixed.
2.  Project not appearing in search.  Project is flagged as PRIVATE, so will not appear in search results.

Thanks
Iain

**Comment by bgirardot** [comment]
Hi Iain,

1410 works for me now.

These still seem to be "blank" for me, but are all from my user profile list of projects I have contributed to.

http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/project/838
http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/project/865
http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/project/1431
http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/project/1554
http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/project/2205

**Comment by bgirardot** [comment]
@hunt3ri Dealing with the dynamic xyz urls reminded me, there is a data problem in the existing TM2 database with priority areas.

I can't explain exactly what it is, but there are duplicate entries in the project_priority_areas table. 

This causes us internal server errors if we try and edit those projects, they work totally fine otherwise, but if we try to edit and save they throw an error.

I am about to double check if the above listed projects coincide with the bad data.

I use these sql commands to find them in the TM2 database:

> SELECT priority_area_id FROM project_priority_areas GROUP BY priority_area_id HAVING COUNT(priority_area_id) > 1;
> SELECT project_id,priority_area_id FROM project_priority_areas GROUP BY project_id,priority_area_id HAVING COUNT(priority_area_id) > 1 order by project_id;

You can hopefully tease out the issue from those?

And then I fix the problem like this:

> delete from project_priority_areas where project_id = nnnn;

nnnn being the project id number.

Feel free to just delete the priority areas that are duplicated en mass to "resolve" the issue.

I would be fine doing that to the current TM2 database so we do not have to think about it again.

**Comment by bgirardot** [comment]
The project do not seem to coincide between blank ones and ones with the double priority area issue. Some overlap, but not the ones listed above.

**Comment by hunt3ri** [comment]
Was an error in importing data, now resolved.

**Comment by bgirardot** [comment]
@hunt3ri Are you going to or did you re-import the data? The above examples still show as blank.

**Comment by hunt3ri** [comment]
Should now be fixed @bgirardot
