### ISSUE TITLE
Documentation link for postgres docker image is broken

### ISSUE THREAD

**Issue by Abhirup-99** [hotosm/tasking-manager#4223]
I was setting up backend but found the documentation link for postgres docker image is broken. 
What would be the way forward?

**Comment by Abhirup-99** [comment]
@willemarcel can you help with this one.

**Comment by eternaltyro** [comment]
@Abhirup-99 can you elaborate ? Where did you see the link to the documentation?

**Comment by tsmock** [comment]
I have also seen this link. After a bit of investigation, the `Dockerfile` was essentially
```Dockerfile
# This was `FROM mdillon/postgis` -- see removal commit for original
FROM postgis/postgis:latest

ENV POSTGRES_USER hottm
ENV POSTGRES_PASSWORD hottm
ENV POSTGRES_DB tasking-manager
```

It was removed in 91ba9d405e3443199343a147e227cafea33d256e.

As for where references to the missing Dockerfile are located, see https://github.com/hotosm/tasking-manager/blob/develop/docs-old/setup-development.md#build--run-the-postgis-dockerfile and https://github.com/hotosm/tasking-manager/blob/develop/docs/developers/development-setup.md#build--run-the-postgis-dockerfile .

We could probably replace it with `docker run --env POSTGRES_USER=hottm --env POSTGRES_PASSWORD=hottm --env POSTGRES_DB=tasking-manager --publish 5432:5432 postgis/postgis:latest`. Someone should double check that -- I tested with `podman`, but it _should_ work with `docker`.

**Comment by ramyaragupathy** [comment]
@spwoodcock - does your PR on separating swagger in docker fixes this? Can you please verify?

**Comment by spwoodcock** [comment]
No it's unrelated, but this issue can be solved with a small docs update.

I personally don't think we need such comprehensive documentation for how to set up a standalone postgres container.
That's outside the scope of TM.

We do this by default in the development docker compose config.
If the user wants to change the default config to their spec with TM inside containers, but also linking to a separate database in containers too, I think they will know how to do this anyway.
