### ISSUE TITLE
Main project listing - pagination behaves strangely - shows same projects

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#423]
When paging through projects on the main contribute listing, at some point in paging back through the projects it starts showing the same projects for part of the listing.

You can see in the attached screen shots, around page 15, it starts keeping the same two projects at the bottom and only changes the first two projects.

![2017-05-29_16h51_06](https://cloud.githubusercontent.com/assets/265831/26554326/d2cd7d52-448f-11e7-8600-1d1922b3be8d.png)

![2017-05-29_16h51_31](https://cloud.githubusercontent.com/assets/265831/26554331/d7275a30-448f-11e7-8ba1-0f73a77ca489.png)

**Comment by hunt3ri** [comment]
Hi @bgirardot this should now be resolved, by ordering by ProjectID.  Please retest.

**Comment by bgirardot** [comment]
It looks like the default, non filtered listing is by priority, then by project id, which I think is what it should be. Is that right, that is how it behaves?

the main issue is fixed though, I see different projects all the way through.

**Comment by hunt3ri** [comment]
@bgirardot yes it's now ordered by priority then project id.  Will close the issue 👍
