### ISSUE TITLE
Possibly incorrect code

### ISSUE THREAD

**Issue by teymour-aldridge** [hotosm/tasking-manager#4232]
Sorry – I accidentally clicked enter before adding the description.

In `organisation_service.py` there is something a bit strange going on:

https://github.com/hotosm/tasking-manager/blob/16bf8a69103ddb94cf9419b0729cc6a9ac6cd5c6/backend/services/organisation_service.py#L234-L249

First, an exception is raised (which returns from the function). However, there is some code which should never run (because an exception is raised).

This seems like it might be an indentation error?

**Comment by willemarcel** [comment]
Thanks, @teymour-aldridge ! I fixed it

**Comment by teymour-aldridge** [comment]
Cool :D
