### ISSUE TITLE
Project Dashboard - Sort descending on project number

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#427]
Currently the project listings on the project dash board seem to be ascending based on project number, could we reverse that so the most recent project are at the top?

I think that would just be descending instead.

Newer projects should be at the top of the lists.

**Comment by bgirardot** [comment]
I see the columns are sortable. It should default to descending by project number.

**Comment by hunt3ri** [comment]
Hi @bgirardot this should now be resolved.  Please retest.

**Comment by LindaAlblas** [comment]
I think Blake meant the order of projects on the project dashboard http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/admin/dashboard. I have made them descending by project ID by default.
