### ISSUE TITLE
Build frontend with env var parameters

### ISSUE THREAD

**Issue by DearRude** [hotosm/tasking-manager#4297]
Is it currently possible for frontend to read parameters (logo, name, social links, ...) from env vars or they need to be hardcoded?

**Comment by willemarcel** [comment]
@DearRude you can follow the instructions on https://github.com/hotosm/tasking-manager/blob/develop/docs/setup-development.md#configuration

It's mentioning mostly variables needed by the backend, but the frontend variables can be configured on the same way.

**Comment by DearRude** [comment]
I already tried to set vars in frontend dockerfile before build but it does not seem to have any effect.

**Comment by bopercival-hot** [comment]
@DearRude have you resolved this or would you like further support?
