### ISSUE TITLE
Project Task Map UI does not seem to update

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#434]
If I have a project up and someone else checksout a task, my map UI does not seem to update. Refreshing the page does update it, but it should update on some tighter interval.

**Comment by bgirardot** [comment]
I do see that it does update, but seemingly not very often. At least minutes between updates.

**Comment by bgirardot** [comment]
Further testing shows that it does not seem to update on its own at all.

**Comment by feenster** [comment]
Hi Blake,

Project auto refresh works for me, although I have noticed that sometimes it seems to stop at times.  I had put it down to the fact that I am developing and doing out of the ordinary things with my browser and sessions.  Never noticed it during normal use.  I may need to try and get a look at your screen to try and get a bit more information and see it happening.

**Comment by feenster** [comment]
Fixed with PR #516
