### ISSUE TITLE
Remove fields from User DTO

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#4378]
The fields `missingMapsProfile` and `osmProfile` can be calculated on the frontend and doesn't need to be served by the backend.

**Comment by NatashaKSS** [comment]
Hi @willemarcel may I assist in this issue? 

This looks like a good way for me to get an introduction to working with the python backend :) I'll follow the backend development setup instructions here: https://github.com/hotosm/tasking-manager/blob/develop/docs/setup-development.md#backend.

Also, **may I ask if the frontend is still using these fields?** (just wanted to make sure!) I've done a quick search in the frontend codebase and found no such reference to these fields, so I assume that it's safe to deprecate them.

**Comment by willemarcel** [comment]
@NatashaKSS yes, sure! We set the links to the OSM user page and to the Missing Maps on: https://github.com/hotosm/tasking-manager/blob/develop/frontend/src/components/userDetail/headerProfile.js#L43-L44 and it's already set based on the username
