### ISSUE TITLE
Improve time filter on statistics pages

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#4393]
Feedback from user: "The time filter menu is not super intuitive, i.e. it takes a lot of clicks to filter on the previous year. Some shortcut e.g. "this year" / "last year", or buttons to move to the previous similar period (i.e. if filtered on the year click on "previous" to automatically filter on previous years) would be very useful"

**Comment by NatashaKSS** [comment]
Hi @willemarcel, maybe I can help take a look at this issue? 

Just wondering, is the Statistics page this one in the screenshot below?
* If so, I'm not able to find the "time filter menu" mentioned in this issue 😅 am I looking in the right place?

URL to the page: https://tasks-stage.hotosm.org/projects/8579/stats

![image](https://user-images.githubusercontent.com/12412031/124492564-3c131700-dde7-11eb-8929-25ec045cbc19.png)

**Comment by willemarcel** [comment]
Hi @NatashaKSS ! It's on `/manage/stats` or in `/manage/organisations/{id}/stats`. I'm not working at HOT and on Tasking Manager any more. So I won't be able to review your Pull Requests.
