### ISSUE TITLE
Dynamic URL in per task instructions

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#441]
Dynamic URL in per task instructions

**Comment by hunt3ri** [comment]
Hi @bgirardot I'm looking at this now.  Looking at the existing data from HOT2 it looks like the majority of instructions don't reference the X,Y,Z of the task, and I can't find one example of people using dynamic urls on arbitrary grids.

So wondering what the best way to proceed here is.  Do we want to go for continuing to allow people to add text instructions like "Use MapBox Imagery", and add X,Y,Z urls?   TBH I'm not sure how useful the URL is now that u can see the imagery in the tasking manager??

Let me know.

**Comment by bgirardot** [comment]
This project is archived and due to a bug... hey that reminds me, we do have a bug in some of data, will follow up after this.... I can't update it to make it published, it is currently archived, I am sure you can see it since you are an admin.

http://tasks.hotosm.org/project/617

that uses the xyz urls and is how we use that functionality.

**Comment by bgirardot** [comment]
http://tasks.hotosm.org/project/617

If you "review" a task square, notice the instructions on the left, with the dynamic urls will download specific files just for that task square.

if you edit the project, you can see how those per task instructions are written.

**Comment by hunt3ri** [comment]
Thanks @bgirardot OK will go with allowing PMs to specify dynamic URLS with X, Y, Z

**Comment by pgiraud** [comment]
As far as I know this has been addressed in #468, #482 and #578.
We can close this issue in my opinion.

**Comment by bgirardot** [comment]
Thank you @pgiraud My testing shows it works as intended now as well.
