### ISSUE TITLE
Validation - autofill OSM usernames in comment box based on users in Task history

### ISSUE THREAD

**Issue by SColchester** [hotosm/tasking-manager#4429]
In TM3 as a validator commenting to users was faster because after selecting '@' it recommended to autofill with the OSM username of the user who marked the task as mapped. As it stands, in TM4 the list that appears after selecting '@' is a full list of all OSM users - this takes some time to locate the correct user - often only after several characters are input. For example:
![2021-03-25 14_27_07-#10104_ Zambia Local Impact Governance Activity - Mumbwa District-03 - HOT Taski](https://user-images.githubusercontent.com/43822967/112493048-ba3c3800-8d79-11eb-90a3-483365163c02.png)

**Comment by wireguy** [comment]
@SColchester see #3453

**Comment by aawiseman** [comment]
Yes, this would be great. It's similar to one I just posted, https://github.com/hotosm/tasking-manager/issues/4596
