### ISSUE TITLE
iD editor broken in firefox

### ISSUE THREAD

**Issue by lovelyfurball88** [hotosm/tasking-manager#4450]
In firefox, if you use the iD editor built into the tasking manager, it will ask you to log in when you try to save even when you are already logged in. If you do log in, the login window 404s and any edits you make are lost. Very annoying for firefox users.

**Comment by willemarcel** [comment]
@lovelyfurball88 are you experiencing this problem using the HOT Tasking Manager or another instance?

**Comment by lovelyfurball88** [comment]
The tasking manager. I don't know if its firefox itself or something I have, but it worked for me on other browsers.

**Comment by willemarcel** [comment]
@lovelyfurball88 could you check the Firefox console for some error message?
