### ISSUE TITLE
Add loading indicator to buttons on project edit page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#4462]
Similar to #4447, add the loading indicators on the project Save button and on the buttons of the actions section of project edit page.

**Comment by NatashaKSS** [comment]
Hi there, I might be able to help with this issue! (and hopefully other similar ones 🙏)

---
However, I'm new to this project and just got my TM development environment set up for the frontend. **How do I access the project edit page in my development environment? I can't seem to access it as it seems like I don't have the right permissions.** 😅 (is this the right avenue to ask?)

I've logged in with my OSM account on `localhost:5000` and set `TM_APP_API_URL='https://tasking-manager-staging-api.hotosm.org'`, but I don't see the project CRUD UI anywhere on the HOTS website. I've consulted all the README docs but still couldn't quite figure out this last bit. Is there a piece of instruction that I've missed?

**Comment by willemarcel** [comment]
Hi @NatashaKSS ! What is your OSM username? I can give you permission to edit a project on staging.

**Comment by NatashaKSS** [comment]
Thanks for the quick reply 😄 My OSM username should be: "Natasha Koh"

I hope this is correct! I got this from my openstreetmap user URL: "https://www.openstreetmap.org/user/Natasha%20Koh"

**Comment by willemarcel** [comment]
@NatashaKSS I added you to an organization. Please run your tests on this project only https://tasks-stage.hotosm.org/projects/8579, as the staging sends notification email to the users.

**Comment by NatashaKSS** [comment]
Just checking on the details of this issue ~

What's left is just to add the loading indicator & disabled feel to the red buttons on each one of the buttons in the ACTIONS section right? Namely:
* Message all contributors
* * Message all contributors
* * Message all contributors

I need to add the loading indicator to that red "Validate all tasks" button, am I right? Similarly, for each and 

![image](https://user-images.githubusercontent.com/12412031/119657418-75f31400-be5e-11eb-946a-02cd5acaba99.png)

**Comment by willemarcel** [comment]
Yes, you need to use the useAsync hook to trigger the API request and then show the loading indicator while the request is executing. This is a good PR to have an idea on how to do it https://github.com/hotosm/tasking-manager/pull/4447/files
