### ISSUE TITLE
Project filtering - Advanced Search page - UI improvements

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#447]
Project filtering UI/UX needs refinement. The main issue is the need to click the search button. Could be a performance hit to "live update" the list of projects. Might need some additional refinements based on user feedback.

**Comment by LindaAlblas** [comment]
The search button only needs to be used when doing a free text search. The advanced options automatically search. This will have to be monitored and if it turns out to be a problem for performance, then we'll have to look at it again and potentially reintroduce the search button.

**Comment by bgirardot** [comment]
Oh, I think I saw that happen just now and it did not register with me it was behaving that way :) . Super cool. Thank you very much!
