### ISSUE TITLE
Not all tasks submitted when validating multiple tasks

### ISSUE THREAD

**Issue by wireguy** [hotosm/tasking-manager#4551]
I can't reproduce consistently.
steps:

select multiple tasks to validate (in this test I selected project 10116, 4 tasks #2941·#2939·#2942·#2940
did map corrections using josm, submitted
selected 'yes' 
added a 'thanks' comment to the first task, and copied to all other tasks
submitted

It looks like nothing happened:
![image](https://user-images.githubusercontent.com/47227325/116001617-4cc33780-a5c3-11eb-845b-7d1996ab75f3.png)

So...  I hit refresh on the web page, and the first task was correctly submitted, but not the others:

![image](https://user-images.githubusercontent.com/47227325/116001679-990e7780-a5c3-11eb-82c4-75d981be4289.png)

now when I submit for the others, it works fine.

I copied this out of the chrome console:

```
RTLTextPlugin is loaded
matomo.hotosm.org/piwik.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tasking-manager-tm4-production-api.hotosm.org/api/v2/users/queries/filter/[pmalletappa]/:1 Failed to load resource: the server responded with a status of 404 ()
tasking-manager-tm4-production-api.hotosm.org/api/v2/users/queries/filter/[pmalletappa]/:1 Failed to load resource: the server responded with a status of 404 ()
11.22abab7a.chunk.js:2 WARNING: Too many active WebGL contexts. Oldest context will be lost.
i._setupPainter @ 11.22abab7a.chunk.js:2
11.22abab7a.chunk.js:2 WARNING: Too many active WebGL contexts. Oldest context will be lost.
i._setupPainter @ 11.22abab7a.chunk.js:2
11.22abab7a.chunk.js:2 WARNING: Too many active WebGL contexts. Oldest context will be lost.
i._setupPainter @ 11.22abab7a.chunk.js:2
tasking-manager-tm4-production-api.hotosm.org/api/v2/projects/10116/tasks/actions/unlock-after-validation/:1 Failed to load resource: the server responded with a status of 500 ()
```

**Comment by wireguy** [comment]
I tried on a different set of tasks and received a different line in the console log:

```
tasking-manager-tm4-production-api.hotosm.org/api/v2/projects/10116/tasks/actions/unlock-after-validation/:1 Failed to load resource: the server responded with a status of 500 ()
```

same steps, 4 tasks, submit, 1 submits 3 don't.  worked after refresh.

**Comment by willemarcel** [comment]
Thanks for the report, @wireguy! We discovered an issue on the email sending that is affecting some actions. We will push an update tonight that is going to solve it.

**Comment by willemarcel** [comment]
@wireguy it should be fixed now. Let me know if you notice something wrong

**Comment by wireguy** [comment]
Haven't been able to reproduce since getting the update.   Going to close.    Good work 🎉
