### ISSUE TITLE
Mapper experience level - when does this get updated?

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#458]
I notice on the imported data that all of the mappers come in as beginner, which make sense.

When will those mapper experience levels get updated? 

I would guess during the first time the login, and on each following login or visit to the mapper's user profile.

**Comment by hunt3ri** [comment]
Hi @bgirardot yes the intention is to refresh their mapper level when they visit their profile page.  This functionality will be implemented us part of the work on #448

**Comment by bgirardot** [comment]
Could we also update it when they login or some other passive trigger (mark a task complete/validated, once a day, once a week, etc) to update the xp level?

**Comment by bgirardot** [comment]
@hunt3ri This is answered and on the radar so I am going to close it.
