### ISSUE TITLE
Add way to mention each person who mapped in a square at the same time

### ISSUE THREAD

**Issue by aawiseman** [hotosm/tasking-manager#4596]
I think it would be useful to add a quick way to mention everybody who mapped in a square, rather than using @ for each user. Maybe similar to #managers, #author -- like #taskcontributors or something? I think that would make folks more likely to see comments. Or even have that automatically turned on for each comment on the square?

**Comment by wireguy** [comment]
#3453 is request for quicker way to add the '@'

**Comment by aawiseman** [comment]
Ah great @wireguy . That's similar, in this case it would just do them all at once. I think both would be useful

**Comment by aawiseman** [comment]
Any progress on this one? I think it would help.

**Comment by Aadesh-Baral** [comment]
@aawiseman What do you think about adding  #contributors to task comment section which will mention everybody who locked task for mapping or validation.

**Comment by aawiseman** [comment]
@Aadesh-Baral  I think that would work!
