### ISSUE TITLE
Change focus to editbox when adding a validation comment

### ISSUE THREAD

**Issue by wireguy** [hotosm/tasking-manager#4601]
![image](https://user-images.githubusercontent.com/47227325/116822376-7e507b80-ab4c-11eb-8dc5-60222421d69e.png)
When you click on the +Comment button, the focus stays on button. 
It would be nice to have the focus change to the editbox, so the validator can just start typing.
This saves one mouse click.

**Comment by willemarcel** [comment]
Good idea, @wireguy ! I'll implement it soon
