### ISSUE TITLE
Fails to save project - error on saving

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#463]
If I make any changes to this project and hit "save changes" it just returns an error:

http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/admin/edit-project/2608

I do not see anything obviously wrong with it. I have also tried clearing it out to the most bare bones project, just all saves result in an error. 

Not a major issue, but might be informative to look at to see what is going on.

**Comment by LindaAlblas** [comment]
@bgirardot this issue should now be fixed
