### ISSUE TITLE
Order the tasks by id on multiple tasks validation

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#4689]
![image](https://user-images.githubusercontent.com/666291/119913689-e9ffeb80-bf34-11eb-929f-b8ff13fbffc2.png)

Sometimes the tasks don't show ordered by id on the multiple tasks validation.

**Comment by NatashaKSS** [comment]
This looks manageable, may I take up this issue? :)

Btw, how do you navigate to this specific page in the website?

**Comment by willemarcel** [comment]
Yes, @NatashaKSS ! I think it's a good issue for you. On `/projects/:id/tasks/` select multiple tasks for validation, by clicking on some blue tasks on the map, then click on `Validate selected tasks`.
