### ISSUE TITLE
Task boundary should be downloaded before OSM data is downloaded.

### ISSUE THREAD

**Issue by AndrewBuck** [hotosm/tasking-manager#470]
On the TM3 preview instance, if you click the button to load the selected task in JOSM it will use the JOSM remote to download the OSM data for the bounding box covering the area selected and then secondly it will download the boundary polygon for the selected area.  However because the boundary is downloaded second, that is the most recently loaded layer in JOSM and you then have to switch back to the OSM data layer.

What should be done is that the order should be reversed so that the bounding polygon is downloaded first, and then the OSM data after that.  This has two additional benefits as well besides the layer ordering issue.  First, the bounding polygon will download very quickly and then josm will zoom to the area so you can start looking at it while it downloads the data from OSM which can take quite a while for areas with lots mapped in them.  Secondly, if the OSM download fails due to too much downloaded data in the area, the user will at least get the bounding polygon so that they can manually download smaller chunks themselves.

**Comment by AndrewBuck** [comment]
It looks like the changes were made as I suggested.  From what I can tell it is now behaving exactly as described.

I am leaving the issue open for now as I am not a developer so I don't know if they completed it to their satisfaction, but from my point of view this issue can be marked closed as long as the devs agree.

**Comment by feenster** [comment]
Thanks for feedback Andrew, closing issue.  Discussion in #471 is also relevent.
