### ISSUE TITLE
Need to set upload=never on the Bounding polygon for tasks downloaded in JOSM.

### ISSUE THREAD

**Issue by AndrewBuck** [hotosm/tasking-manager#471]
Clicking the button to load the selected task in JOSM will download a layer with a bounding polygon for the task to be worked on.  On older versions of the TM when we had this enabled would set upload=false on the bounding layer to avoid people accidentally adding them into the OSM database if they merge layers.  The TM3 instance doesn't seem to do this, however.

Also, as long as we will need to add this I think we should actually use the new upload=never option that newer versions of JOSM support.

https://josm.openstreetmap.de/ticket/12731

That addition was in a fairly new version of JOSM, however so we may want to stick with upload=false for now with a plan to switch to upload=never at some point in the future, or we may want to try adding both tags (although I am not sure what JOSM would do if a file had bot tags).

Either way, this is a critical issue.  TM3 should not go live before this is resolved with at least upload=false.  When we had this before without the upload=false flag it caused huge problems.

**Comment by feenster** [comment]
Thanks for this feedback, very helpful.  The advice I got from the the JOSM developer mailing list was as follows:

> Mark the XML data as upload=no or upload=never (since JOSM 11709) to prevent accidential uploads.

We have implemented with upload=no.  Do you know if 'no' is a valid value?  This fix here may be to change no to false.

**Comment by althio** [comment]
I think upload=no is invalid.

upload=false will emit a warning.
upload=never (since JOSM 11709) will forbid any upload if the layer.

I recommend upload=never for the polygon of the task.

**Comment by feenster** [comment]
if using upload never, what risk is there that someone is using an older version of josm which doesn't support upload = never, and they do not even see a warning?

**Comment by althio** [comment]
I do not have stats of people with older versions of JOSM vs people ignoring yet another somewhat daunting warning of JOSM.
This is a concern, risk either side, no perfect solution.

For reference we choose faith in upgrading and the future at https://github.com/hotosm/learnosm/issues/335#issuecomment-285949451

**Comment by bgirardot** [comment]
@althio @AndrewBuck Ian pushed updates to help address this issue, testing would be most welcome, you should see significantly different behavior in how the task polygons are loaded into josm.

at the moment, I think the main issue is the one Ian raised, what happens if we use upload=never and people have older josm software that does not support that tag.

but as I said, ian has made changes that should help address this no matter what based on layers in josm, i have yet to test myself as they were added literally just 30 mins ago.

**Comment by bgirardot** [comment]
@feenster Do you know if we can create an empty data layer?

In testing the latest, the single task validation works fine, two layers, the task outline layer is discourage upload and not the active layer. The data layer with the downloaded data is just a standard data layer and the active layer.

For the multi task validation, can we create a second, active data layer just like you do now with the single task validate, but just not download the data for that second data layer? 

Also can we name those data layers? "Task Boundaries - Do not edit or upload" and "OSM Data layer for validation"

Also my testing, with a 6 month old version of JOSM that does not support upload=never, seems to indicate that you will get the warning to discourage uploads even when upload=never and even when upload=madeupvalue. It seems to not matter what the value of upload= is for my version, once that is key is there, it discourages uploading that layer, regardless of value.

**Comment by bgirardot** [comment]
It does look like we can add layer_name= when using load_layer to name a layer.

Feedback so far from the JOSM-Dev list is that we should create an empty.osm file, put it in our static resources directory and then have jsom download that to create an empty data layer. the RemoteControl api does not seem to support making an empty data layer directly.

**Comment by feenster** [comment]
Ok @bgirardot , we've merged another commit #496 

It now works like this:
- Create a new empty layer 'Task Boundaries #<projectId> - Do not edit or upload' layer in JOSM'
- Import task square(s) as OSMXML marked with upload=never to above layer
- Load Imagery if available to layer 'Tasking Manager Imagery - #<projectId>'
- Create a new empty layer 'OSM Data layer for validation'
- If single task, load OSM data to above layer
- Zoom to bbox of task(s)

**Comment by bgirardot** [comment]
I do not see the upload=never functionality working. I do not see even the discourage upload working, the layer with the task polygon just looks like any other osm data layer in JOSM

**Comment by feenster** [comment]
Hi @bgirardot 
The upload=never flag is defintely being passed to JOSM.

As far as I can tell, I am using the JOSM commands as documented.  I have detailed the commands and data being used below.

It would be useful to have someone with a deeper understanding of the JOSM api and it's inner workings take a look at this, as I am not sure where to take it from here.

</hr>

To get the tasks loaded on to a layer with a custom name I use two JOSM remote commands in the following sequence. The osmxml being passed to JOSM in both commands contains upload="never"

### Command Sequence and data
**1. load_data** 

- [https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands#load_data](https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands#load_data)
- This is used to create an empty layer with a custom name.
- Actual encoded URL used to invoke command: http://127.0.0.1:8111/load_data?new_layer=true&mime_type=application/x-osm+xml&layer_name=Task%20Boundaries%20%232651-%20Do%20not%20edit%20or%20upload&data=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf8%22%3F%3E%3Cosm%20generator%3D%22JOSM%22%20upload%3D%22never%22%20version%3D%220.6%22%3E%3C%2Fosm%3E

**2. import**

- https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands#import
- This is used to create load tasks from TM3 to JOSM into the layer created in step 2
- Actual encoded URL: http://127.0.0.1:8111/import?url=http%3A%2F%2Ftasking-manager-staging.eu-west-1.elasticbeanstalk.com%2Fapi%2Fv1%2Fproject%2F2651%2Ftasks-as-osm-xml%3Ftasks%3D40&new_layer=false

**Comment by feenster** [comment]
@bgirardot!  I think it's fixed now.  I needed to uriencode the  mime_type param on the load_data request.

**Comment by feenster** [comment]
@bgirardot have you been able to verify that this is working as you expect?

**Comment by bgirardot** [comment]
@feenster I actually had this confused. the original issue was about mapping, but my comments were about validation, as was #437 

The good news is that either way, both mapping and validating, single task or multiple tasks, it all works well.

My preference is that we do not need two layers for single task, mapping or validating in josm, but if we need two layers, it is working exactly right.
