### ISSUE TITLE
Project "Custom Editor" fields cleared on cloned project

### ISSUE THREAD

**Issue by SColchester** [hotosm/tasking-manager#4819]
All of the info below is cleared for a project when it is cloned. The new project will retain this information, but the original project that was used to create a clone from will have these details removed. This effectively removes the RapiD editor for any project that has been cloned from. Have to go back and manually add these details to get editor working again.

![2021-07-28 11_33_48-Edit project #11119 - HOT Tasking Manager — Mozilla Firefox](https://user-images.githubusercontent.com/43822967/127308489-5db62d42-5622-48a5-bb49-f9e4a8c86c04.png)

**Comment by jeffdefacto** [comment]
I can confirm this is happening for me as well. Definitely an annoyance as it will break projects if you don't fix it.
