### ISSUE TITLE
TM3 does not save the preffered editor  to use when working on a task.

### ISSUE THREAD

**Issue by AndrewBuck** [hotosm/tasking-manager#484]
On the existing TM2 instance if you select an editor like josm when you work on a task, if you come back to the site later it defaults to the one you chose.  The new version of the TM3 no longer does this.  Not sure if it was a cookie or server side for the prefernece on TM2 but either way it is nice to have it remembered.

My recommendation would be to save the users preference server side as this way it is consistent across computers, but would also be useful for Knowing which users are skilled in josm, etc.

**Comment by bgirardot** [comment]
I think this is something that comes from OSM API as well if you have it set there. But TM2 might keep track of it as well once you select something.

**Comment by pgiraud** [comment]
On TM2, we were using à cookie.

**Comment by feenster** [comment]
Fixed using cookies to track last used editor
#538
