### ISSUE TITLE
Download Tasks Grid & Download AOI buttons restricted to project creator

### ISSUE THREAD

**Issue by zlavergne** [hotosm/tasking-manager#4841]
As of now, the **Download AOI** and **Download Tasks Grid** buttons are only available for the creator of a project. It would make sense to open this up more on the front end (the API doesn't have any restrictions on who should be able to download these).  At the very least, PM's for a project and org admins should be able to download both.

I'm curious if there needs to be a front end restriction at all for this feature. I've seen cases where validators will use the AOI or tasks grid during validation. Let's discuss 😄 

![228002204_362031678631851_4083175941543958662_n](https://user-images.githubusercontent.com/9849118/128249702-5fdfea74-1a34-4806-8519-ee143d315ab4.png)

**Comment by Roro-first-ro-is-silent** [comment]
Thank you for making the Tasks Grid available for validators. It is very helpfull for some projects where we are mapping also buildings over the task borders (usually in Mozambique projects). It would be great if one day it would be available for mappers aswell :) Thank you

**Comment by lehnerpat** [comment]
I've been mapping in some of the Mozambique projects. I can confirm that having the task grid available as a mapper would be helpful sometimes. Especially in projects like the Mozambique missing maps, where the task areas aren't a fully contiguous grid but have gaps instead, this would make it easier to judge whether buildings outside my current task area are in another task (in which case I shouldn't map them right away), or not part of any task (in which case I can including them)

**Comment by Patrik-Br** [comment]
On projects where the tasks are not instantly next to each other, shaped like grid, I am always using the taskgrid even when I am mapping (I am using a workaround in JOSM using the URL) because there are often some buildings outside the tasks. So having the opportunity to make it available for download for mappers as well would be benefit in my opinion.
