### ISSUE TITLE
Maxar premium imagery doesn't work for me

### ISSUE THREAD

**Issue by aadit66** [hotosm/tasking-manager#4846]
I've been trying to work a task which requires the use of Maxar Premium, but I can't see anything apart from a grey-ish screen and the outlines of other people's work. I left the thing to load for around 10 minutes in case it was a network issue, but nothing changed. Am I doing something wrong?

![Screenshot 2021-08-13 at 2 38 16 PM](https://user-images.githubusercontent.com/88875595/129315508-cceedd74-c2f6-44c0-9196-6c3ffede3a68.png)

**Comment by bopercival-hot** [comment]
@aadit66 can you please submit this to support.hotosm.org

**Comment by dakotabenjamin** [comment]
Fixed in #4931
