### ISSUE TITLE
Will hotosm add Simplified Chinese?

### ISSUE THREAD

**Issue by LaoshuBaby** [hotosm/tasking-manager#4849]
I noticed translation files in ```/frontend/src/locales```

So what should I notice if I want to translation? Should all strings be translated before final pull request?

**Comment by d-rita** [comment]
@LaoshuBaby translations happen via this [Transifex](https://www.transifex.com/hotosm/tasking-manager/dashboard/) repository. These [contributing guidelines](https://github.com/hotosm/tasking-manager/blob/develop/docs/contributing-translation.md) are a good starting place. As for adding a new language to TM, we would need a good percentage of the strings to be translated (at least 60/70%).
