### ISSUE TITLE
TypeError: Only timezones from the pytz library are supported

### ISSUE THREAD

**Issue by jimmyrocks** [hotosm/tasking-manager#4850]
I've been trying to run the tm_backend in Docker / docker-compose on a Digital Ocean machine, and I kept getting this error:
`TypeError: Only timezones from the pytz library are supported`

I don't really understand the specifics of what was going on, but I was eventually able to _solve_ it by updating the version of the apscheduler in the requirements.txt:

From
`apscheduler==3.6.3`
To
`apscheduler==3.7.0`

Is this going to cause other problems for me? Has anyone else run into this issue with tm_backend and Docker?

more of the error message:
```
tm_backend_1      |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
tm_backend_1      |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
tm_backend_1      |   File "/usr/src/app/manage.py", line 79, in <module>
tm_backend_1      |     cron.add_job(auto_unlock_tasks, "interval", hours=2)
tm_backend_1      |   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 420, in add_job
tm_backend_1      |     'trigger': self._create_trigger(trigger, trigger_args),
tm_backend_1      |   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 921, in create_trigger
tm_backend_1      |     return self._create_plugin_instance('trigger', trigger, trigger_args)
tm_backend_1      |   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 906, in _create_plugin_instance
tm_backend_1      |     return plugin_cls(**constructor_kwargs)
tm_backend_1      |   File "/usr/local/lib/python3.7/site-packages/apscheduler/triggers/interval.py", line 38, in __init__
tm_backend_1      |     self.timezone = astimezone(timezone)
tm_backend_1      |   File "/usr/local/lib/python3.7/site-packages/apscheduler/util.py", line 93, in astimezone
tm_backend_1      |     raise TypeError('Only timezones from the pytz library are supported')
tm_backend_1      | TypeError: Only timezones from the pytz library are supported
tm_backend_1      | [2021-08-20 14:27:00 +0000] [11] [INFO] Worker exiting (pid: 11)
tm_backend_1      | [2021-08-20 14:27:00 +0000] [1] [INFO] Shutting down: Master
tm_backend_1      | [2021-08-20 14:27:00 +0000] [1] [INFO] Reason: Worker failed to boot.
hotosm_tm_backend_1 exited with code 3
```

**Comment by ethan-nelson** [comment]
For trying to debug this issue in the repo's initial state (i.e. without forcing the apscheduler upgrade), could you provide the output of the `timedatectl` or similar type command from the machine?

**Comment by datendelphin** [comment]
I just stumbled across the same issue. Looks like https://stackoverflow.com/questions/68832550/python-apscheduler-fails-only-timezones-from-the-pytz-library-are-supported-e
altering requirements, upgrading to apscheduler==3.7.0 resolves the issue

**Comment by datendelphin** [comment]
Seems resolved with https://github.com/hotosm/tasking-manager/commit/b6872ce7f207ea9e0fcfda4e04c2ccee797b7eea
