### ISSUE TITLE
Parameterize AMI in Cloudformation template

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#4854]
The AMI [hard-coded into the template]() is only valid for us-east-1. We should parameterize this so it can be configured for multiple regions.

**Comment by zlavergne** [comment]
Hey @dakotabenjamin , I'd be interested in helping with this issue. Having just gone through this process, I found a few things that would be useful to be parameterized. Happy to chat more about my findings if you want.
