### ISSUE TITLE
 Divergent Contributor Counts

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#4899]
Here is a screen capture of the Explore page on the Tasking Manager:

![Explore](https://user-images.githubusercontent.com/6763645/136704726-c924c117-bcfc-4f06-ac1f-ef91d73378e5.PNG)

Looking at project 6665, you see "total contributors" with a value of 3573

Here is a screen capture of the very same project, in the project view, just moments later:

![Project](https://user-images.githubusercontent.com/6763645/136704811-546469e5-ef4d-41a2-bdee-f6d02e1d9f4f.PNG)

Towards the bottom you see "contributors" preceded by the value of 1069

It is my assumption that on the Explore page, the value is actual "total contributions", i.e. each time the project is 'worked on', i.e. if I map a few tasks, then come back and validation a few task - that is 2 contributions, by 1 contributor. The value on the project page is I think actually showing "Unique Contributors". However we go about it, we need to clarify (and make sure we use correct terminology) so these either both show "Unique Contributors" or "Total Contribution Sessions" or whatever stat makes the most sense here.

**Comment by Aadesh-Baral** [comment]
Nice catch @russdeffner. On the project list view all of the user actions other than a comment are identified as a contribution while on the project detail view, user actions i.e. `Mapped`, `Validated`, and `Bad imagery` are counted as a contribution.
Users are considered contributors if they:
| User actions | Projects list view      | Project detail view |
| ----------------- | -------------------------- |--------------------------|
| Mapped | :heavy_check_mark: | :heavy_check_mark: |
| Validated | :heavy_check_mark: | :heavy_check_mark: |
| Marked as bad imagery | :heavy_check_mark: | :heavy_check_mark: | 
| Locked for mapping    | :heavy_check_mark: | :x: |
| Locked for validation   | :heavy_check_mark: | :x: |
| Invalidated | :heavy_check_mark: | :x: |
| Commented | :x: | :x: |

@petya-kangalova any thought on how we should take this forward for consistent contributors count throughout the project?

**Comment by Aadesh-Baral** [comment]
Contributors calculation for projects list view: https://github.com/hotosm/tasking-manager/blob/e15c917b093fd1adadf5bfccc579cf969823fe90/backend/models/postgis/project.py#L938-L950
Contributors calculation for project detail view: https://github.com/hotosm/tasking-manager/blob/e15c917b093fd1adadf5bfccc579cf969823fe90/backend/services/stats_service.py#L247

**Comment by petya-kangalova** [comment]
@russdeffner is that something we can post in tasking-manager organization channel to get input from people?

**Comment by russdeffner** [comment]
Sure, I don't see why not @petya-kangalova but I think it could be just simply a 'rewording' from contributors to contributions but I'm fine if there is a larger consensus that wants it to be more explicitly 'solved' (i.e. if people wanted to make sure the numbers match on the explore page and project description, stats, etc.)
