### ISSUE TITLE
Improved sorting for ‘My Tasks’ list

### ISSUE THREAD

**Issue by bopercival-hot** [hotosm/tasking-manager#4924]
User submitted through Help Desk:
The "My tasks" list is a helpful tool to revisit my previous tasks and maybe recapitulate how problems that occurred during mapping were solved. The tasks are sorted by their ID (see screenshot). However, the sorting is not very helpful: Rarely do I remember the task ID. More often, I know what I did yesterday or the day before.

There certainly are people for whom a numerical sorting works well, but optional sorting according to other criteria (date edited, project ID) would be welcome.

**Comment by Aadesh-Baral** [comment]
While going through the current code implementation I found out that tasks are sorted by the last action date by default and it's working as it should be locally but on staging and production it's being sorted by task_id for some reason.
