### ISSUE TITLE
Users are unable to "Submit" validation tasks

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#4948]
Users on the tasks-indonesia.hotosm.org seem to be unable to click the submit button when validating tasks. The error was reported on https://tasks-indonesia.hotosm.org/projects/176/tasks/?page=1 but has been seen before on other projects. It was reported that this applies to project created after migrating to TM4 (so previous projects don't seem to have this issue). 

The logs are showing Authentication errors: 
```
2021-12-10 14:14:54,525 CRITICAL: Validator Lock API - unhandled error: (535, b'Authentication Credentials Invalid') [in /tasking-manager/backend/api/tasks/actions.py:571]
```

We suspect it may have to do with the OAuth implementation. We currently use OAuth V1 with OSM login, but OSM has recently implemented OAuth V2. Perhaps upgrading our login process will resolve these errors. 

The following are user reports from Slack:

### 4 August 02:30 EST
> we did test today. Only 23% did not have any validation issue. For the rest of the team have encountered this issue.
> I tried to validate other task (task number 111 - https://tasks-indonesia.hotosm.org/projects/111/). I managed to validate two tasks before the issue comes again.

### 10 December 08:43 EST
> Project 176 Semery Vulcanic eruption.
> Problems with changing status of tasks after validation.
> When I submit a of multiple tasks The submit task button  reacts, but don't finish.
> I have to stop validation to continu . So the task is not marked as validated.

### 10 December 12:30 EST
> I encountered this also, I was allowed to validate, but nothing happened when I submitted a task as well mapped.

### 16 December 19:10 EST
> Hi, we seem to have a problem on the Indonesia Tasking Manager. Who do we contact for that? I can select a task and it loads into JOSM. I can work on that task and save the work to OSM. When I select the button for complete=yes and try to submit that it will not go through. If I select the complete=no and submit it does go through and reverts the task back to ready for validation. If I select stop validation it accepts that as well. It refuses to accept that a task is validated.

**Comment by dakotabenjamin** [comment]
I was thinking perhaps this issue is related to login timeout. Maybe users are being logged out without realizing?

**Comment by vdgwebsites** [comment]
@dakotabenjamin i validated several tasks in this project and tried your suggestion. Logging out and in before validation.

Unfortunately with no result.

Sometimes i succeeded in saving a validated task. This seems to happen randomly. Even when i succeeded to save, the next task i couldn't. And the other way round.

Regards, Martien
OSM: martien-vdg

**Comment by adiatmad** [comment]
Got the same issue after validating several tasks. I validated without logging out and only takes a couple of minutes each task.

![TM Indonesia 176](https://user-images.githubusercontent.com/38268616/153343506-45717108-00a3-4e28-8dad-92234d0cd45b.png)

Cheers, Dinar
