### ISSUE TITLE
Set Default Permission for Validation to 'Intermediate and Advanced'

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#4954]
As with #1753 this isn't asking for any change outside of setting the default value to 'not beginner'. It has come up in the Quality Assurance and Control Working Group that possibly we would not allow beginner mappers to ever validate; but I think that's going too far. There may be a situation where you are training people or otherwise have identified new OSM profiles to be able to validate. 

So, a compromise might be that project creators would be 'forced' to consciously change the permission value of validators to any mapper by making the default restricted to intermediate and advanced. Thank you for considering, this should be a relatively easy change for a big increase in data quality.

![defaultvalidation](https://user-images.githubusercontent.com/6763645/147188688-cc78024d-3a87-48f5-adef-40fe7366b61b.PNG)

**Comment by SColchester** [comment]
This would be great!

**Comment by aawiseman** [comment]
@russdeffner I think this is a great idea, it’s been a problem lately such as https://lists.openstreetmap.org/pipermail/hot/2022-January/015748.html

**Comment by opk12** [comment]
Hello. Is this change only effective on newly created projects, or it applies retroactively to existing projects?

**Comment by opk12** [comment]
Hello. Is this change only effective on newly created projects, or it applies retroactively to existing projects?

**Comment by HelNershingThapa** [comment]
@opk12 only on newly created projects
