### ISSUE TITLE
Easy mapathon-specific hashtag adds during mapathons

### ISSUE THREAD

**Issue by maGIScian** [hotosm/tasking-manager#4976]
We (MSF) want to make it possible for mapathon organisers to add a specific hashtag to a project during a mapathon.  They would for example enter the project number and the hashtag they want in a dialog box or something and click 'activate' and then the hashtag is automatically added to the changesets for that project, until they click 'deactivate' and the mapathon-hashtag isn't added anymore.  many mappers forget to add hashtags during mapathons that have their own hashtags - this approach would make it easier to track mapathon-specific contributions.

**Comment by SColchester** [comment]
I like this but do worry that Orgs might forget to de-activate after a session and projects end up having tags forever. Might include a time-out function to remove automatically after several hours.

**Comment by HelNershingThapa** [comment]
Under the changeset comments section, project managers can include hashtags.
![hashtag](https://user-images.githubusercontent.com/51614993/192732784-9a97ba99-5673-4bc3-ae71-01c1ca86e6a0.png)

A default changeset comment, #hot-tm-stage-project-8580, a unique identifier for a TM project, can be seen. I believe similar hashtags could be added for hackathons.

**Comment by maGIScian** [comment]
not easy for mapathon organisers, who don't have project editing rights, and often work in timezones other than the project managers, so switching it on and off at the right time and communicating this could be troublesome.  like, seriously, just a little box where the mapathon organiser says okay activate the hashtag for the project now, and then deactivates it afterwards.  if this is too much to ask and takes months to get a reply, pretty glad I'm not missing maps coordinator anymore!

**Comment by HelNershingThapa** [comment]
Sorry for the delay; we were preoccupied with other matters.
