### ISSUE TITLE
Enable shippable access on organisation

### ISSUE THREAD

**Issue by hunt3ri** [hotosm/tasking-manager#5]
Hi @smit1678, @bgirardot 

I've just sent a request thru to the github HOT organization owners from shippable to allow it to pull from the repos in order that we can get our CI system running.

Would you be able to approve it, or assign this tic to appropriate person

Many thanks
Iain

**Comment by smit1678** [comment]
Done. ✔️

**Comment by hunt3ri** [comment]
Awesome thanks @smit1678 and FYI for peace of mind, github/shippable is smart enough to only allow me to pull from the tasking-manager repo.  All other repos are invisible

Cheers
Iain
