### ISSUE TITLE
API 'reset-all-badimagery' resets status for every project on Tasking Manager

### ISSUE THREAD

**Issue by SColchester** [hotosm/tasking-manager#5011]
From API Docs: https://tasks.hotosm.org/api-docs/

POST: /api/v2/projects/{project_id}/tasks/actions/reset-all-badimagery/ 

API 'reset-all-badimagery' is designed to reset bad imagery for one project defined by Project ID - however it seems to reset bad imagery **for every project on Tasking Manager.** Here is the entry that was made, including the responses:

![2022-02-22 07_49_34-API Docs - HOT Tasking Manager — Mozilla Firefox](https://user-images.githubusercontent.com/43822967/155169477-94e27636-301b-4fbd-b966-b5af0464a6c5.png)

![2022-02-22 07_50_31-API Docs - HOT Tasking Manager — Mozilla Firefox](https://user-images.githubusercontent.com/43822967/155170247-6b914feb-b0e5-4c1f-8dc9-dd5f56acffc8.png)

This correctly worked for the defined project:

![2022-02-22 07_50_05-](https://user-images.githubusercontent.com/43822967/155169659-f153c48b-716a-4dd5-aa32-89c79095ff78.png)

But then also caused task resets for all other projects that I checked (adding some exmaples to show extent) - I can only assume this was the case for **ALL** Tasking Manager projects:

![2022-02-22 07_49_03-#10218_ Tripoli Digital Base Map Project 2021 - HOT Tasking Manager — Mozilla Fi](https://user-images.githubusercontent.com/43822967/155171063-2627b995-eb03-43d1-9c7d-05f68b2b1f51.png)

![2022-02-22 07_49_47-](https://user-images.githubusercontent.com/43822967/155171111-5136e19a-89c4-4121-9239-e587fad72d30.png)

![2022-02-22 07_50_55-#12147_ Open Cities - Guatemala_ Chiquimula Este 2 - HOT Tasking Manager — Mozil](https://user-images.githubusercontent.com/43822967/155171142-af58309d-c835-4bdc-9a48-25b6cb18f585.png)

![2022-02-22 07_52_25-](https://user-images.githubusercontent.com/43822967/155171181-6f6f06eb-9208-4025-857f-3549348e8785.png)

**Comment by zlavergne** [comment]
Oof. Good catch. I checked the code and this is definitely what the code is doing:
https://github.com/hotosm/tasking-manager/blob/3c12892ac1e506e2170bff7e5e1094c416f6603e/backend/services/mapping_service.py#L369-L382

As you can see (if you speak Python), we aren't filtering by `project_id` when fetching tasks. It literally gets **all** tasks in the entire instance marked as `BadImagery`.

I can submit a PR to fix this but question for @d-rita @ramyaragupathy @eternaltyro, if this action was taken at all in the TM, then it likely messed up tasks and stats for multiple projects. Do you folks think any remediation is needed right now or can I make a PR to fix the issue, then there can be an investigation into affected projects?

**Comment by ramyaragupathy** [comment]
cc @petya-kangalova

**Comment by zlavergne** [comment]
PR is out 😄

**Comment by ramyaragupathy** [comment]
@Aadesh-Baral - there is an option to reset task status using the `Edit Project` option. `Reset All Unavailable Tasks` refers to resetting bad imagery tasks.

![image](https://user-images.githubusercontent.com/12103383/156323763-0f366a08-b6e9-4da5-8d7b-ea86c9141a9e.png)

cc @dakotabenjamin

**Comment by Aadesh-Baral** [comment]
Ok @ramyaragupathy thanks

**Comment by SColchester** [comment]
@ramyaragupathy thanks for pointing that out - I did not know it also existed there, great it is!
