### ISSUE TITLE
Translatable strings visible for about a second after logging in

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/tasking-manager#502]
After logging in, I see the placeholders for translatable strings in brackets, this lasts for about a second before the strings are replaced with the menu items in English below

![image](https://cloud.githubusercontent.com/assets/9853903/26806631/ed358686-4a1f-11e7-8b0a-9ed618e1b473.png)

**Comment by tastrax** [comment]
strings also seem to show permanently on Samsung Tablet  GT_P5100 Android 4.2.2
