### ISSUE TITLE
Implement OAuth 2.0 for OSM Login

### ISSUE THREAD

**Issue by Aadesh-Baral** [hotosm/tasking-manager#5027]
OSM now supporting OAuth 2.0 for login and OAuth 1.0 will go away at some point, according to TomH: "we will hopefully be retiring OAuth 1 in the relatively near future" ([openstreetmap/openstreetmap-website#3299](https://github.com/openstreetmap/openstreetmap-website/issues/3299)). Now its time to upgrade TM to use OAuth 2.0.

**Comment by Aadesh-Baral** [comment]
The idea here would be to not only upgrade TM to use OAuth 2.0 but also make changes to the TM embedded iD editor and its underlying OAuth library to support OAuth 2.0.

**Comment by zlavergne** [comment]
@Aadesh-Baral regarding updating the iD editor; it may be best to make that PR to the iD repo instead so that the changes will more easily propagate. I'm curious on your thoughts on this.

**Comment by Aadesh-Baral** [comment]
@zlavergne we are planning a PR to osm-auth library. If approved it would be easy to propagate changes to other projects as well.
