### ISSUE TITLE
Map view doesnt seem to represent project list

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/tasking-manager#503]
Eg. there are projects in DRC, but only point represented in Africa is in Madagascar.

![image](https://cloud.githubusercontent.com/assets/9853903/26806710/5d001706-4a20-11e7-9b37-ed56e60c4e5b.png)

**Comment by tastrax** [comment]
Correct - it only shows the projects listed above (currently 6 projects). I have also made comments on the map display in #347

**Comment by tastrax** [comment]
Now doesn't seem to show any points at all

**Comment by bgirardot** [comment]
Same behavior here, no points show on the map.

**Comment by feenster** [comment]
@TylerRadford @bgirardot 
Issue address with #547 
- Map moved to it's own tab to allow display of all projects without confusion and difficulties arising from the paging of results in the grid and list veiw
- Clustering of projects at smaller scales on the map
- NB, the project click popup will contain % mapped and % validated once new API in place.  Missing for now.

**Comment by feenster** [comment]
re-opining pending implementation of  the project details api mentioned

**Comment by feenster** [comment]
#further fixes in #566
