### ISSUE TITLE
Change map display to Humanitarian OSM style and add OSM contributors attribution

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/tasking-manager#504]
Change map display to Humanitarian OSM style and add OSM contributors attribution

All places OSM web/slippy map is displayed

**Comment by LindaAlblas** [comment]
I have switched the background mapping to the Humanitarian OSM style. I have also set the attribution property collapsible to false so it now always shows. 

The attribution for any additional configured layers (such as MapBox aerial) can be changed in client/taskingmanager.config.json
