### ISSUE TITLE
Sometimes Choose a Task options don't appear without explanation

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/tasking-manager#505]
See below screenshot. Using Chrome. Clicked into the project but no options to take a task appear.

![image](https://cloud.githubusercontent.com/assets/9853903/26806931/64bfa30c-4a21-11e7-9507-7683b532f950.png)

Only if I click on a map tile do I get the below. We could probably improve usability by having this display immediately.
![image](https://cloud.githubusercontent.com/assets/9853903/26806969/84c463e0-4a21-11e7-8a27-f90b9ff7aa8c.png)

**Comment by feenster** [comment]
fixed with #517 and #523
