### ISSUE TITLE
Add TM Cheatsheet to TM Learn page

### ISSUE THREAD

**Issue by petya-kangalova** [hotosm/tasking-manager#5050]
**Is your feature request related to a problem? Please describe.**
Incorporate the new Tasking Manager  Cheatsheet created by  Can from the Asia Pacific Hub so that others can use. From Slack conversation: https://hotosm.slack.com/archives/C319P09PB/p1647608283723759

**Describe the solution you'd like**
A suggestion will be to add  the cheatsheet under Manuals as a separate page called Tasking Manager 
![image](https://user-images.githubusercontent.com/98902727/159246551-88655e41-d38f-42f5-8583-997e7d092cbf.png)

Link to cheatsheet: https://drive.google.com/file/d/19pckU4Cru-cSz_aclsLsBk-45SQ1Qyy_/view

Other suggestions also welcome!

**Comment by Aadesh-Baral** [comment]
@petya-kangalova PR is already out

**Comment by petya-kangalova** [comment]
@Aadesh-Baral  apologies, just saw! Thank you! Linking to PR https://github.com/hotosm/tasking-manager/pull/5049
