### ISSUE TITLE
Update About page with correct organizations/logos

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/tasking-manager#506]
@bgirardot and myself to determine

http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/about

Do we want to recognize TM2 donors or only TM3?
Donors or other supporters?

**Comment by bgirardot** [comment]
@TylerRadford There is an issue with ublock origin and maybe other adblocking software blocking the logos (about to get fixed), but if you disable your adblocker you should see the correct full list of logos.

Please let me know if that current list needs changing.

**Comment by cgiovando** [comment]
See https://github.com/hotosm/tasking-manager/issues/702 about that issue - we should remove any js/script around those logos that trigger the ad blockers.
