### ISSUE TITLE
Multiple roles for 1 team within the same project

### ISSUE THREAD

**Issue by Jorieke** [hotosm/tasking-manager#5073]
We have 1 team on the HOT TM that is set up to work on private projects. At the moment it is only possible to assign one role to the team on the same task. It is not possible to assign the team to the role of mapper and the role of validator. 

It would be great if I could assign the same team as mapper and as validator on a task.  

I have now set the one team as validator, and it seems that they can now also map the tasks, not only validate. If this would be the actual solution, it would be great to make that clearer on the HOT TM. The difficulty is that as project admin you cannot test these things out yourself to see if it is working because you are allowed to do much more than just mappers. 

Another solution could as well be to create a second team, but that seems to be an extra step for the mappers to become member of a new team again, and we will probably lose mappers in that process. 

I hope you can help out! 
Thanks, Jorieke

**Comment by zlavergne** [comment]
Thanks for the issue @Jorieke. You're right that the **validator** role assumes the permissions of the **mapper** role. This is the intended design as these roles are hierarchical (a **PM** role allows the team to validate and map as well as PM only permissions). 

But you bring up a good point that we could add more useful verbiage to clarify this to admins and managers. I definitely don't suggest creating another team as that's too much overhead for admins.

**Comment by Jorieke** [comment]
Thanks @zlavergne ! 

I have to say that it has worked pretty well with the set up of assigning the team the role of validator, and than playing a bit with the permissions so beginner mappers who are part of the team are not able to validate.

For mapping permission I set: Only team members. 
For validation permissions I set: Only intermediate and advanced team members.

**Comment by Aadesh-Baral** [comment]
Fixed by #5318
