### ISSUE TITLE
Improve error message when trying to validate self-mapped tasks

### ISSUE THREAD

**Issue by hiddewie** [hotosm/tasking-manager#5086]
**Is your feature request related to a problem? Please describe.**

Situation: I worked on many tasks for a project, mapping some and validating the work of other mappers.

However, I often forget that I mapped some of the tasks myself, and click the validation button for tasks that are ready for validation.

Validating the tasks I mapped myself is not allowed by the system. This is a good thing :+1:.

However the error message does not indicate this problem clearly.

**Describe the solution you'd like**

The error message should clearly describe that the task cannot be validated because I mapped it myself.

**Describe alternatives you've considered**

An even better solution would be to show in the UI if a task was mapped by myself so wouldn't even consider clicking the validation button.

**Additional context**

Screenshot of current error message

![image](https://user-images.githubusercontent.com/1073881/162585891-efb34b56-783c-421d-8dc3-d4fe0181f8cb.png)

**Comment by Aadesh-Baral** [comment]
This has been addressed in #5039. You can only check It on [staging](https://tasks-stage.hotosm.org) currently but will be in production soon. 
Actually, I liked the alternative approach that you mentioned. Can you create a separate issue for the alternative approach?

**Comment by hiddewie** [comment]
Thanks, great! I did search for issues but didn't find #5039, maybe because it's a PR.

I will make a new issue for the UI improvement
