### ISSUE TITLE
Organization and Campaign tags converted all lower case - Can we keep mixed case?

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#509]
Can we keep the case for these as they are created? At the moment, they get switched to all lower case.

**Comment by hunt3ri** [comment]
Hi @bgirardot I'm afraid not, if you allow mixed case you end up with multiple tags like

malariaAfrica
MalariaAfrica
malariaafrica

which means you lose all the grouping.  Tags are always lowercased, check Stackoverflow etc.

**Comment by bgirardot** [comment]
@hunt3ri  Are you sure we can't support mixed case? I think the auto suggestions should help keep the above issue minimized. It sure looks a lot better with mixed case.

Alternatively, maybe we should default to all upper case since a lot of the organization tags at least are all uppercase. MSF, ARC, WFP, etc.

**Comment by bgirardot** [comment]
Feedback shows overwhelming preference for mixed case. We will have to figure how to deal with the possibility of "duplicate" tags that are not really duplicates, probably by manually pre-loading the organization tags and by re-assigning them if accidentally done incorrectly.

**Comment by hunt3ri** [comment]
@popelnuh can you confirm that you can create mixed-case tags on projects now.  If so please close this issue, thanks.

**Comment by popelnuh** [comment]
Tested and working as expected. The mixed case for organisations and campaigns can now be saved and retrieved with filtering from the contribute page.
