### ISSUE TITLE
[BUG] JOSM doesn't load OSM data when attempting to map a task

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#5097]
**Describe the bug**
A user on the [HOTOSM Slack](https://hotosm.slack.com/archives/C319P09PB/p1650003569584219) reported that only the task boundary loads in JOSM, but not the OSM data. I was also able to replicate this on the latest version of JOSM. 

**To Reproduce**
1. Open JOSM (Make sure remote control is enabled)
2. Select a task for mapping in JOSM
3. Check the Information of the created layer

**Expected behavior**
When selecting JOSM as the editor, it should load both the boundary and the osm data layer. 

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Browser N/A
 - Version JOSM v18427

**Comment by jluebbe** [comment]
I can reproduce this on Chromium and Firefox (Debian Bullseye). The first time I tried it with Firefox, it worked correctly. On further tries of the same task, I now only get the bounding box.

When looking at the HTTP requests on the loopback interface with Wireshark, I saw `/load_data?…`, `/load_and_zoom?...` and `import?...` when it worked( all completed with 200 OK. Now I only see requests for `/import?…` (the bounding box).

**Comment by rohieb** [comment]
I can reproduce this with Debian stable, JOSM v17428, Firefox 88.0.1. When I click on the "select task" button, I only see a request to http://127.0.0.1:8111/version?jsonp=checkJOSM in the Firefox inspector, and nothing else… JOSM asks the usual remote control questions, I click on "Allow", and then I have a new way with four nodes and no tags (apparently the size of the bounding box?) in JOSM.

**Comment by SmithChart** [comment]
Can confirm this behavior on Debian Bullseye with Firefox 91.8-esr and JOSM 18427.

**Comment by Aadesh-Baral** [comment]
Found really inconsistent. For me, the OSM data layer and boundary loads while mapping a task on the project [11896](https://tasks.hotosm.org/projects/11896/tasks/) but only boundary and imagery loads on the project [12084](https://tasks.hotosm.org/projects/12084/tasks/).

**Comment by rohieb** [comment]
> Edit: ah, after allowing the import in JOSM, I now also get requests to `http://127.0.0.1:8111/load_data?new_layer=true&layer_name=Boundary%20for%20task%3A%20223%20of%20TM%20Project%20%2312010%20-%20Do%20not%20edit%20or%20upload&data=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf8%22%3F%3E%3Cosm%20generator%3D%22JOSM%22%20upload%3D%22never%22%20version%3D%220.6%22%3E%3C%2Fosm%3E` and `http://127.0.0.1:8111/import?new_layer=false&url=https%3A%2F%2Ftasking-manager-tm4-production-api.hotosm.org%2Fapi%2Fv2%2Fprojects%2F12010%2Ftasks%2Fqueries%2Fxml%2F%3Ftasks%3D223`, but still no OSM data.

Looking at the second URL, it apparenly tries to redirect JOSM to load data from `https://tasking-manager-tm4-production-api.hotosm.org/api/v2/projects/12010/tasks/queries/xml/?tasks=223`. When I do this in the console, I only get the bounding box in the OSM data:
```
$ curl https://tasking-manager-tm4-production-api.hotosm.org/api/v2/projects/12010/tasks/queries/xml/?tasks=223
<?xml version='1.0' encoding='utf8'?>
<osm version="0.6" upload="never" creator="HOT Tasking Manager">
<way id="-223" action="modify" visible="true">
<nd ref="-1" /><nd ref="-2" /><nd ref="-3" /><nd ref="-4" /><nd ref="-5" />
</way>
<node action="modify" visible="true" id="-1" lon="35.631409" lat="33.643206" />
<node action="modify" visible="true" id="-2" lon="35.631409" lat="33.647779" />
<node action="modify" visible="true" id="-3" lon="35.636902" lat="33.647779" />
<node action="modify" visible="true" id="-4" lon="35.636902" lat="33.643206" />
<node action="modify" visible="true" id="-5" lon="35.631409" lat="33.643206" />
</osm>
```
(newlines inserted by me for readability)

I don't know if should look like this…?

**Comment by Kraan46** [comment]
Validation works flawless (all loads properly). Mapping not. Sometimes task boundary loads, sometimes not. Sometimes OSM data layer loads. Sometimes not. Imagery never loads as usual (but can be added manually).

**Comment by petya-kangalova** [comment]
A few other users reported the same issue via the Tech support helpdesk. Adding notes here from them if helpful with debugging:

 **15 April:  Guatemala:**  since HOT tasking manager wanted to update itself is only downloads the border of task and not the data into JOSM

![image](https://user-images.githubusercontent.com/98902727/163979902-e390df6b-80f9-49e8-a3d9-606f3fd2907c.png)

 **17 April:  Belgium**
In the window 'layers' (screen.jpg : upper right corner) the OSM data layer is missing in JOSM.
The existing features (roads, wterways, buildings ...) are not mapped.
This problem suddenly occured after I closed task 38 of the project 12087.
My country : Belgium
![image](https://user-images.githubusercontent.com/98902727/163980200-6e898949-4df7-43b1-9fc4-c81aa743cc34.png)

 **18 April: Spain**
Clicking on a tile does not pass the url to the remote control and therefore JOSM does not load the already mapped objects. This has been going on for a few days. I use Ubuntu. I've tried multiple browsers and the same thing happens in all of them. I have tried with another computer and the same thing happens.

![image](https://user-images.githubusercontent.com/98902727/163980541-4e666fed-5d3c-408b-8503-090b33b4c792.png)

**Comment by zlavergne** [comment]
Hey all. I think we've already got a solution to this issue in `develop` and it just needs to be deployed. Taylor Smock, one of the main JOSM contributors, determined this wasn't an issue with JOSM as they haven't changed the remote control code any time recently. We determined that the issue came down to the `window.location.reload()` in the `Reload editor` action which terminates the calls to JOSM early. The changes I made in #5096 actually solves this issue because we no longer reload the page. So this shouldn't be an issue after the next release.

**Comment by jpuxan** [comment]
It works fine now. Thank you so much

**Comment by Kraan46** [comment]
No, it doesn't. Here still the same issue.

**Comment by Aadesh-Baral** [comment]
I think #5096  solves the issue in the case of reloading the editor. i.e. when the user has already locked a task.  This needs to be handled while starting an editor also. i.e. while locking a task for mapping. Will verify it and send a PR asap.

**Comment by Aadesh-Baral** [comment]
Here is PR #5106 to fix the latter case I mentioned above. Keeping this issue open until it is completely verified as solved.

**Comment by jluebbe** [comment]
It is still broken for me. Does the fix still need to be deployed on https://tasks.hotosm.org/?

**Comment by SmithChart** [comment]
I can still reproduce the problem. But on the way to reproduce it I found the following behavior:

* JOSM-latest: 18433
* Firefox 91.8.0esr (64-bit) on Debian Bullseye
* Tested on this project: https://tasks.hotosm.org/projects/12010/map/?editor=JOSM

When using my everyday Firefox Profile I only get an empty bounding box in JOSM:
![Bildschirmfoto_2022-04-21_22-28-09](https://user-images.githubusercontent.com/6676035/164547025-f16c3a0a-380b-4fc0-943f-6a4a962bb731.png)
While remote-controlling JOSM Firefox does the following requests to localhost:
```
http://127.0.0.1:8111/load_data?new_layer=true&layer_name=Boundary%20for%20task%3A%20456%20of%20TM%20Project%20%2312010%20-%20Do%20not%20edit%20or%20upload&data=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf8%22%3F%3E%3Cosm%20generator%3D%22JOSM%22%20upload%3D%22never%22%20version%3D%220.6%22%3E%3C%2Fosm%3E
http://127.0.0.1:8111/import?new_layer=false&url=https%3A%2F%2Ftasking-manager-tm4-production-api.hotosm.org%2Fapi%2Fv2%2Fprojects%2F12010%2Ftasks%2Fqueries%2Fxml%2F%3Ftasks%3D456
```
Both get a HTTP 200.

Extensions like ad- or cookie-banner blockers are disabled for tasks.hotosm.org
After these requests the whole page reloads.


When using an empty Firefox profile it works as expected.
But I see a lot more requests:
```
http://127.0.0.1:8111/load_data?new_layer=true&layer_name=Boundary%20for%20task%3A%20456%20of%20TM%20Project%20%2312010%20-%20Do%20not%20edit%20or%20upload&data=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf8%22%3F%3E%3Cosm%20generator%3D%22JOSM%22%20upload%3D%22never%22%20version%3D%220.6%22%3E%3C%2Fosm%3E
http://127.0.0.1:8111/version?jsonp=checkJOSM
http://127.0.0.1:8111/import?new_layer=false&url=https%3A%2F%2Ftasking-manager-tm4-production-api.hotosm.org%2Fapi%2Fv2%2Fprojects%2F12010%2Ftasks%2Fqueries%2Fxml%2F%3Ftasks%3D456
http://127.0.0.1:8111/imagery?id=Bing
http://127.0.0.1:8111/load_data?new_layer=true&layer_name=OSM%20Data&data=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf8%22%3F%3E%3Cosm%20generator%3D%22JOSM%22%20version%3D%220.6%22%3E%3C%2Fosm%3E
http://127.0.0.1:8111/load_and_zoom?left=35.636902&bottom=33.643206&right=35.645142&top=33.647779&changeset_comment=%23hotosm-project-12010%20%23MissingMaps_DRK%20%23redcross%20%23missingmaps&changeset_source=Bing&new_layer=false
```
All getting a HTTP 200.

But in this case the page does not reload.

**Comment by drklrd** [comment]
@SmithChart yes indeed! The webpage reloaded too early before sending all requests to JOSM. But this is already fixed in the recent release of TM. Could you please try hard reloading the TM page (with CTRL+SHIFT+R)  and see if that fixes it?

**Comment by SmithChart** [comment]
@drklrd I was quite sure that I did a reload with "Cache disabled" during debugging yesterday. But it seems that's not the case.
I reloaded the TM page with CTRL+SHIFT+R and now it works as expected. Thanks for the support!

**Comment by jluebbe** [comment]
After using CTRL+SHIFT+R, it now works correctly for me.
