### ISSUE TITLE
Negative mapped and validated on a test project

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#510]
Maybe an artifact of the test project, But I do see negative numbers for %mapped and validated.

![2017-06-06_13h25_43](https://cloud.githubusercontent.com/assets/265831/26827146/34090046-4abc-11e7-91c8-13230ae7e52e.png)

![2017-06-06_13h26_06](https://cloud.githubusercontent.com/assets/265831/26827149/37d07006-4abc-11e7-8652-c1a98376e261.png)

**Comment by LindaAlblas** [comment]
@bgirardot this was an issue before but shouldn't be any more. Please ignore this test project.
