### ISSUE TITLE
Add upload image option to comments box

### ISSUE THREAD

**Issue by aawiseman** [hotosm/tasking-manager#5131]
**Is your feature request related to a problem? Please describe.**
Right now it is difficult if not impossible to add an image in the comments box to show somebody something.

**Describe the solution you'd like**
An upload button in the comments box, or some other way to add images.

**Additional context**
This was Martien's suggestion

**Comment by HelNershingThapa** [comment]
A textual hint was added recently and is currently on the staging instance. Will be available on the live instance soon. 

![comment-section](https://user-images.githubusercontent.com/51614993/168966544-1b943823-ddb3-4a99-aac4-6d5492169fc5.png)

**Comment by martien-176** [comment]
My comment on #5130 covers this too.

**Comment by petya-kangalova** [comment]
Now already on live so closing the issue.
