### ISSUE TITLE
Make 'private project' status clear to Org Manager

### ISSUE THREAD

**Issue by SColchester** [hotosm/tasking-manager#5137]
**Problem**
It is hard for an Organization Manager to tell that their project is private. They will need to go into the Edit Menu of the project and at the bottom of the permissions page there is a toggle. Due to its obscurity, I have attended events where the event organizer and project creator did not know their project was set to private and therefore did not know why all the attendees could not find or see the project. 

**Describe the solution you'd like**
For the organization managers that the project is associated with show a tag on the project page that indicates it is set to private. E.g.

![2022-05-19 18_06_50-#10218_ Tripoli Digital Base Map Project 2021 - HOT Tasking Manager — Mozilla Fi](https://user-images.githubusercontent.com/43822967/169347167-541a9388-0aeb-46a6-8a69-63aa9c242d22.png)

**Describe alternatives you've considered**
For anyone that visits the project and is blocked access to the project they could be notified that they have visited a private project and will need to contact the Organization Manager to seek access.

**Comment by HelNershingThapa** [comment]
Hi @SColchester, I added an indicator beside the project title. Will this do?

![private](https://user-images.githubusercontent.com/51614993/169961404-b45e9785-f772-48aa-8b15-0fca3aec8645.png)

**Comment by SColchester** [comment]
That looks great! Many thanks 😄

**Comment by martien-176** [comment]
https://tasks-stage.hotosm.org/projects/8656

This is what i see when visiting a private project.


![Image](https://user-images.githubusercontent.com/17877665/170832010-443df35c-6b54-471b-9a36-b3b68a118abf.jpg)

Would it be possible to show the indicator for regular mappers/validators too?

**Comment by SColchester** [comment]
@martien-176 agree that would be even better!
