### ISSUE TITLE
Return refresh task page to task that was just completed/validated.

### ISSUE THREAD

**Issue by RAytoun** [hotosm/tasking-manager#5140]
After I have marked a task as validated I will want to do the ntask next to it to check continuity of features but the refresh task page does not take me back to the task last worked on. Instead it takes me back to the zoomed out view of all the task squares and I have to zoom back in and try and find the task I last worked on to select the task alongside it.
This is costing everyone a lot of time and unnecessary extra steps.
Please change the settings so that the refresh page returns to the zoomed in task last worked on and help save us all a lot of time
![Task refresh](https://user-images.githubusercontent.com/10500102/169617203-3ddcdba7-150d-41a4-bebf-8e7f87e1089f.jpg)
![Task zoom in](https://user-images.githubusercontent.com/10500102/169617225-e4d99803-9e8c-4ff1-abdf-be46ace98318.jpg)
.

**Comment by Patrik-Br** [comment]
Tested after mapping. Works perfectly 👍
