### ISSUE TITLE
[BUG] User gets logged out on browser refresh without internet connection

### ISSUE THREAD

**Issue by HelNershingThapa** [hotosm/tasking-manager#5150]
**To Reproduce**
1. If you are not logged in, log in to TM.
2. Disconnect your internet.
3. Refresh the browser.
4. You will find yourself logged out.

**Expected behavior**
Users should not be logged out when refreshing the browser without an internet connection.

**Screenshots**
![refresh-log-out](https://user-images.githubusercontent.com/51614993/170182317-be3f747d-c388-4763-9c83-063359910fa6.gif)

**Desktop**
 - OS [ Ubuntu v20.04.4 LTS ]
 - Browser [ Chrome v101.0.4951.64 (Official Build) (64-bit) ]
 - Version [ TM v4.4.15 ]

**Comment by Patrik-Br** [comment]
Works 👍 Tested with Vivaldi browser
