### ISSUE TITLE
[BUG] Search filter cannot display accents

### ISSUE THREAD

**Issue by Crashillo** [hotosm/tasking-manager#5151]
**Describe the bug**
There's no way to type accents (therefore, to find projects) in the search bar. It doesn't matter the keyboard distribution, it will display them aside. Instead of _Málaga_, it displays _M´alaga_, then, no result is found.

Very important issue for a non-english projects.

**To Reproduce**
1. Go to project explorer
2. Type any accent in the search bar. `Alt Gr+´ + a`, for instance 

**Expected behavior**
Be able to type accents as usual

**Screenshots**
![image](https://user-images.githubusercontent.com/817526/170213780-9f1b3d1a-dccc-43f4-8441-2543bf2a959b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04, macOS BigSur (Windows & Debian 10, works as expected)
 - Browser: any
 - Version: any

**Comment by martien-176** [comment]
Thanks,  although i never had to use this, it works fine.

- OS: windows 10, works as expected
- Browser: Edge 
- Version: 103.0.1264.49 (Official build) (64-bit)
