### ISSUE TITLE
[BUG] error navigating to tasks page using the url

### ISSUE THREAD

**Issue by petya-kangalova** [hotosm/tasking-manager#5167]
**Describe the bug**
Unable to navigate to tasks page of a project by changing project number in URL

**To Reproduce**
Message from Ralph via Tech Support. I also tried and I am getting an error too.

I am tabulating statistical data from the TM so am going to lots of different projects.
To do this all I need is to change the project number in the URL and click enter to go to the next project task selection page. https://tasks.hotosm.org/projects/12489/tasks 
Since yesterday using this method returns a white page with An Error occurred - something did not work well and I have to use an extra step now to go to the projects page and then to the task page https://tasks.hotosm.org/projects/12489 which does work.
**Expected behavior**
Changing the URL should direct to relevant task of the specified project in the URL

**Screenshots**

**Desktop (please complete the following information):**
 - Browser 
![error](https://user-images.githubusercontent.com/98902727/171901433-28d55280-e312-4869-8cbc-cbc57d32df29.jpg)

**Additional context**
In my understanding this is likely a bug- do let me know if other have faced similar issues.

**Comment by HelNershingThapa** [comment]
Closed by 096f825d56a09474c85c89325d9374cac6a264cb
