### ISSUE TITLE
Private project indication missing for users having no access to a project

### ISSUE THREAD

**Issue by HelNershingThapa** [hotosm/tasking-manager#5168]
https://tasks-stage.hotosm.org/projects/8656

This is what i see when visiting a private project.

![Image](https://user-images.githubusercontent.com/17877665/170832010-443df35c-6b54-471b-9a36-b3b68a118abf.jpg)

Would it be possible to show the indicator for regular mappers/validators too?

_Originally posted by @martien-176 in https://github.com/hotosm/tasking-manager/issues/5137#issuecomment-1140284132_

**Comment by martien-176** [comment]
It works as far as there is a text indicating that the user has no permission to access.

However, the advise to "Please contact the project manager" is of not much use. Since you do not know who that is .
