### ISSUE TITLE
[BUG] Duplicate text in the welcome page

### ISSUE THREAD

**Issue by HelNershingThapa** [hotosm/tasking-manager#5178]
**Describe the bug**
_"Select causes of interest to help us recommend the right projects for you."_ text appears twice on the welcome page.

**To Reproduce**
1. Go to the [home page](https://tasks.hotosm.org/).
2. Log out if you are logged in.
3. Login with your account. You'll be redirected to the welcome page once successfully logged in.
4. You will find the "Select causes of interest to help us recommend the right projects for you." text appearing twice.

**Expected behaviour**
Only a single text block to select interest should be present.

**Screenshots**
![redundant-text](https://user-images.githubusercontent.com/51614993/173230398-e6f78912-d8fe-4416-9489-3f2a64604205.png)

**Desktop (please complete the following information):**
 - OS:  [ Ubuntu v20.04.4 LTS ]
 - Browser [ Chrome v101.0.4951.64 (Official Build) (64-bit) ]
 - Version [ TM v4.4.15 ]

**Comment by LittleStar21** [comment]
Hi, is this issue still open? I'd like to work on it please.

**Comment by LittleStar21** [comment]
Also, where should the "Select causes of interest to help us recommend the right projects for you." text appear? Below the "Welcome to Tasking Manager!" text or below the "Interest" text?

**Comment by HelNershingThapa** [comment]
sure @LittleStar21 , feel free to work on it.

**Comment by HelNershingThapa** [comment]
Not showing the top _"Select causes of interest to help us recommend the right projects for you."_ text would be good.
