### ISSUE TITLE
Editor changes to default after selecting a task

### ISSUE THREAD

**Issue by Aadesh-Baral** [hotosm/tasking-manager#5194]
**Describe the bug**
Editor is changed to default after selecting a task
**To Reproduce**
1. Go to any projects on TM
2. Click on contribute
3. Change the editor 
4. Click on any task to map/validate

**Expected behavior**
Editor shouldn't be changed back to default.

**Screenshots**
![reset_editor_bug](https://user-images.githubusercontent.com/67958673/175801460-27b31901-fc09-4058-95eb-e511fbc8c87a.gif)

**Comment by martien-176** [comment]
Browsers used for testing: Edge and Firefox

It works as expected, thanks.

**Comment by Patrik-Br** [comment]
Tested, works great 👍
