### ISSUE TITLE
[BUG] When default changeset comment is removed, project stats will not show. 

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#5212]
**Describe the bug**
User reported an issue with project stats not showing in their tasking manager app: https://tareas.nomadas.org.pe/projects/10/stats

On this instance, the default project comment is "#osmpe-project-[x]" where x is the number of the project. On project 10 the default changeset comment was removed and replaced with "#osmpe-unmsm-comaru". The logic for fetching the stats rely on the default comment, so removing it means the stats won't show. This is not ideal behavior. 

**Expected behavior**
Stats should appear as long as there is a changeset comment for the project. 

**Screenshots**
Project where changeset comment was unchanged:
![image](https://user-images.githubusercontent.com/1847818/176928417-317afcc1-94a3-4b61-aee1-b7b9e02e9182.png)

Project in question:
![image](https://user-images.githubusercontent.com/1847818/176928460-329a366f-ed14-4857-b039-5e9608e7de68.png)

**Proposed Solution**
There are two possible solutions:

1. Make it so that the default changeset comment cannot be removed in the project editing settings. 
2. Change the logic for project edit stats fetching to use a primary changeset comment, which can be the default or something else.

**Comment by SColchester** [comment]
@dakotabenjamin great that you've outlined this. I'd argue for solution 1. The risk with solution 2 is that project creators frequently add a custom tag for their project which **intentionally not unique** in order to collect the stats across several projects from a campaign e.g.` #COVID-19`.
