### ISSUE TITLE
[BUG] Grid service tests rely on floating points

### ISSUE THREAD

**Issue by RaymondDashWu** [hotosm/tasking-manager#5219]
**Describe the bug**
test_grid_service.py tests on a JSON consisting of many floating point numbers as outputs. It compares a string of expected vs a string of results. This could lead to small differences and failed tests due to floating point rounding.

For example. My output of ```test_feature_collection_multi_polygon_with_zcoord_dissolve```

- {"coordinates": [[[[-4.65996216497632, 55.95041925350509], [-4.95173413390339, 56.2627945145455], [-4.67367146099783, 56.2434516969104], [-4.66709656284914, 56.2435936767028], [-4.0046243330544, 56.03981437664169], [-4.35742797997559, 55.48727395069889], [-4.65996216497632, 55.95041925350509]]]], "type": "MultiPolygon"}
+ {"coordinates": [[[[-4.65996216497632, 55.95041925350509], [-4.95173413390339, 56.262794514545504], [-4.67367146099783, 56.2434516969104], [-4.66709656284914, 56.2435936767028], [-4.0046243330544, 56.03981437664169], [-4.35742797997559, 55.48727395069889], [-4.65996216497632, 55.95041925350509]]]], "type": "MultiPolygon"}

**To Reproduce**
1. Run tests

**Expected behavior**
Instead of asserting string, assertAlmostEqual

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS 12.2.1 
 - Browser N/A
 - Version N/A

**Comment by RaymondDashWu** [comment]
FYI I think there's more wrong with this than the floating point values. I was in the process of fixing these tests [here](https://github.com/MLH-Fellowship/OSM-HOT-Tasking-Manager/blob/7f9bf41e1688c3d578a4c351f91dd2debdaa5b9f/tests/backend/unit/services/grid/test_grid_service.py#L14) and it looks like the JSON is incorrect as well. Please advise.

`AssertionError: 1275886.875907619 != 1275932.9954440442 within 7 places (46.11953642521985 difference)`

**Comment by Aadesh-Baral** [comment]
@RaymondDashWu All of the tests in test_grid_service are passing in my case. Are you using the latest code or how can I reproduce this error?

**Comment by RaymondDashWu** [comment]
> @RaymondDashWu All of the tests in test_grid_service are passing in my case. Are you using the latest code? or how can I reproduce this error?

That's possibly the reason. My codebase is an old fork. I just saw that the tests were the same. Closing for now
