### ISSUE TITLE
Include types of mapping on task action page

### ISSUE THREAD

**Issue by HelNershingThapa** [hotosm/tasking-manager#5222]
**Is your feature request related to a problem? Please describe.**
When mapping, I've found myself multiple times being confused about what types of mapping(roads, buildings, waterways, etc.) a project has after getting to the task action page (the page where you provide a status for the task). 

**Describe the solution you'd like**
Include types of mapping on the task action page so that users don't have to go back to the project detail page to confirm what types of mapping a project has.

**Comment by SColchester** [comment]
Well idenitified, have had this issue myself! Having the feature icons (buildings, waterways, highways etc.) display at the top of the instructions might solve this. The icons would then show both at the Task selection phase and during mapping on the 'Instructions' tab
