### ISSUE TITLE
Red cross mark appear on top right corner while filtering tasks by username/id

### ISSUE THREAD

**Issue by Aadesh-Baral** [hotosm/tasking-manager#5239]
**Describe the bug**
Users in slack reported a red cross button appears on the top right corner while filtering tasks by username/id. 
Quotes from slack:
> Found by coincidence what I think is a new option on the TM: this red cross appears once you select something in the tasks list (like for instance a mapper or tasks to validate). Clicking on it undo this selection. Don't see the necessity of this ad, but never mind.

> Originally I think there was a black cross in the selection field itself that is no longer there...now it moved to the upper right corner of the screen and became red. Guess why? Useful? My reply is: no.

**To Reproduce**
1. Go to any project on TM
2. Click on contribute.
3. Click on tasks tab in the left corner.
4. Click on filter tasks by id or username and enter any keyword.
5. You can see the red cross mark on the top right corner.

**Expected behavior**
As per the user in slack originally there was a black cross in the selection field itself that is no longer there...now it moved to the upper right corner of the screen and became red, so it might be good to reset it to original position and color

**Screenshots**
![2022-07-08 09_49_52-#12867_  Disaster Response  - Afghanistan Earthquake 2022 - HOT Tasking Manager](https://user-images.githubusercontent.com/67958673/178454225-2e686ada-f613-4e6a-b17a-3c51cc3a02b6.png)

**Comment by Patrik-Br** [comment]
This bug is back since last new version of TM. 

![image](https://user-images.githubusercontent.com/83399473/205448642-527cbab9-eb8f-4a62-86f6-ece44e5c03ec.png)

![image](https://user-images.githubusercontent.com/83399473/205448610-8a55e030-e65f-4bff-8dc0-7a91b8f4b760.png)

**Comment by HelNershingThapa** [comment]
Resolved with https://github.com/hotosm/tasking-manager/commit/e5eb2a10e965c3413cf0a3de6bad273fcd9c5b2d being merged in
