### ISSUE TITLE
[BUG] Backend build on Quay always shows 'building'

### ISSUE THREAD

**Issue by HelNershingThapa** [hotosm/tasking-manager#5244]
**To Reproduce**
1. Go to [repository page](https://github.com/hotosm/tasking-manager)
2. Scroll down to the section where README.md is being rendered.
3. See the 'container building' badge.

**Expected behavior**
The status of the badge must be updated.

**Screenshots**
![quay-building](https://user-images.githubusercontent.com/51614993/178667563-5b5524b5-cf37-4c64-9348-095f35be0e29.png)

**Additional context**
Recent repo builds are not being triggered on Quay.

**Comment by dakotabenjamin** [comment]
Quay.io builds were disabled automatically since 3 months due to build failures. I have re-enabled them to see if they continue to fail. Will monitor and report once we get more information.

**Comment by dakotabenjamin** [comment]
Fixed :D
