### ISSUE TITLE
[BUG] - Unable to Transfer Project Ownership

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#5247]
**Describe the bug**
As discussed in Slack: https://hotosm.slack.com/archives/C319P09PB/p1657643299390869 - Project Owners are unable to transfer ownership of their projects to other Administrators in their own organization. It appears that only System Administrators are able to 'receive' transferred projects (i.e. the only users that appear in the auto-fill/drop-down appear to be Sys/Super Admins).

**To Reproduce**
1. Go to edit any project
2. Click on Actions
3. Scroll down to Transfer Project and try to enter a valid OSM username that is an Admin of the same Organization
4. The "Transfer Project" button will not 'activate'/no ability to interact with the button.

**Expected behavior**
Once a valid OSM username is entered, the Transfer Project button should initiate and transfer the project to new owner.

**Comment by Aadesh-Baral** [comment]
Conversation from the tasking-manager channel on slack regarding this issue:
@Ichchhie says:

> Yeah Russell is right. But, it's quite unclear functionality wise, we have few questions raised:
> Who is the project owner; is it organization associated with the project or project creator? which helps in getting clarity on if the transfer should be between users or organization?
> What is the goal of this transfer ownership function?
> What is the expected output of this transfer ownership function?
> Is it correct that the functionality should only be to sys admins?
> If yes, how can we meet the goal of a ownership transfer beyond sys admin?
> If no, should we restrict this or make clear on the roles, functionality of particular user?
> This also revolves around https://github.com/hotosm/tasking-manager/issues/5023 this issue. So, let's have a good discussion here. (edited) 

@SColchester replies:

> Great, thanks for outlining this clearly @Ichchhie 
>   my stance:
> It's the person (OSM username) publicly listed as the project creator
> The person listed as the project creator is seen by the public as 'responsible' for the project, they are the person to contact if something is wrong or if something needs to be clarified. If someone creates a project on behalf of someone else, transferring ownership is often suitable because it leaves the person who is more familiar with the wider goals of the project as the main contact for the public
> On the project overview page 'Coordination' section the username here: "and was created by USERNAME" changes
> I think all Organization managers should be able to change project ownership - this is particularly useful when there are staffing changes within an organization, the original project creator leaves an organization and dis-engages with Tasking Manager/OSM -> their replacement would ideally transfer ownership of the active projects to become the new main contact for those projects
> Leave permissions as they are currently, I think that anyone that has the right to Edit a project can change the project owner
> The current terminology is not clear because the project page lists it as 'project creator' but the project edit menu lists this as 'project owner' - recommend either re-wording or adding clarification text to edit menu

@russdeffner says:
> In the specific case, the current Project Owner/Creator is leaving (their role), and wants to transfer ownership to someone taking over the managing of the organization's TM usage. (edited) 


@russdeffner says:
> Issue #5023 is more just about the terminology and how it's used across the TM. I started a new issue specifically to this bug: https://github.com/hotosm/tasking-manager/issues/5247


@Aadesh-Baral says:

> @SColchester
>  thanks for clarification, I have some concerns regarding 5th point leaving the permissions as it is allows a member of team with Project Manager permission within a particular project can change the ownership of project. In my opinion, teams can contain members of different organizations or individual contributors so allowing member of team to change project permissions might be a problem.


> Yeah agree that project manager team members should not be granted permission to change owners - should be restricted to Organization Managers (edited) 


@russdeffner says:

> I do see a need to transfer projects across organizations though - this happened recently where an organization basically started a handful of projects and then for whatever reason could not see them through, so the local community (existing org on the TM) 'took them over'. So in that case maybe we could only allow a system admin to do the transfer; but that person would need to be able to pick any/all organization admins to transfer to.


@russdeffner says:

> @Aadesh-Baral  - agree, I think how it is pretty straightforward and works well - that is, the Team with Project Manager permissions can do anything to a project except they can't create (or clone) new projects and they can't delete the project. I think that is ok, noting that we've had several organizations mention that they would like a way to give someone project creation permission without making them organization admins.

**Comment by Aadesh-Baral** [comment]
@russdeffner @SColchester This issue has been completed. Can you please review its implementation on [staging](https://tasks-stage.hotosm.org) server once? Please hard refresh after loading the staging site.

**Comment by russdeffner** [comment]
@Aadesh-Baral - It does not work for me; I tried transferring one of my HOT projects to the only other admin for HOT and their name isn't showing up. Project 8588 on staging site, created by me, trying to transfer to https://tasks-stage.hotosm.org/users/Mapperson 

I also tried to transfer a project from the German Red Cross to myself (which I would think should/needs to be possible for System Admin accounts - but I'm not sure I'm a Sys/Super Admin on the staging site, maybe just the main) - and it fails. In both cases I get this...

![transferfail](https://user-images.githubusercontent.com/6763645/180677703-22619d64-a403-4c67-8489-9073fa25d69c.PNG)

**Comment by Aadesh-Baral** [comment]
Hi @russdeffner, Did you hard refresh TM with ctrl+shift+R before trying it? In case of transferring it to sys admins, i made a patch update recently, so it should also work now.

**Comment by russdeffner** [comment]
@Aadesh-Baral - the transfer between same organization admins is working now; thanks! However, now I don't show up in the list of users unless I am part of the organization - that's ok, I can join an org and make the transfer and leave; but it would be nice if I could just make the transfer without having to join/leave. Either way - it's working as expected (in the few cases I tested).

**Comment by Aadesh-Baral** [comment]
Project ownership transfer to Sys admins should be possible even if they aren't org managers. Something might have gone wrong on implementation. Will check and update accordingly. Thanks for reviewing @russdeffner
