### ISSUE TITLE
Project Creation - Block project 'Save' unless team permissions are correctly defined

### ISSUE THREAD

**Issue by SColchester** [hotosm/tasking-manager#5248]
**Problem**

Under a project 'Edit' > 'Permissions' menu, project creators often limit mapping or validation permissions to 'Only team members' - however, they often fail to define which particular teams under the 'Teams' section below. This leads to a situation where projects are frequently created which **do not allow anyone** to map or validate them. 

My assumption is that projects creators might think that choosing 'Only team members' and then leaving the 'Teams' section blank allows **all** teams to map/validate - this is not the case, each team and its role need to be individually defined. 

**Solution**

During project creation/editing in the 'Edit' > 'Permissions' menu if either Mapping or Validation permissions have been limited to "Only team members" or "Only intermediate and advanced team members" if no teams have been defined, on pressing 'Save' the save process should be blocked and a message should be displayed stating: "It was not possible to save the project. Permissions are restricted to teams, and teams are not defined". Example edited from existing warning:

 ![2022-07-13 16_42_12-Edit project #12966 - HOT Tasking Manager — Mozilla Firefox](https://user-images.githubusercontent.com/43822967/178777397-26d636dd-da07-4274-a9f3-3e6d63f60df8.png)

**Alternative considered**

If mapping or validation is restricted to teams, but no teams are defined an alternative is to allow **all** teams to map or validate. A limitation of this is that teams have varied purposes and qualities and this may allow very inexperienced mappers to validate projects where the intention of the project creator was to limit validation to more experienced users.

**Comment by Aadesh-Baral** [comment]
Hello, @SColchester. I think this has already been addressed in #5181, and it has been implemented in both staging and production. Could you please confirm this once and let me know if it's working on your end?

 ![no_team_set_error](https://user-images.githubusercontent.com/67958673/178896406-07c25da8-79a8-4def-8d00-85c8c8d7905a.png)

**Comment by SColchester** [comment]
Perfect, it works - many thanks, this is great to see!
