### ISSUE TITLE
Notify user if geojson is not Polygon or MultiPolygon

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#527]
When importing to define the project area, it successfully imports Linestring based geojsons and lets you move to the next step. But they do not work in the aoi trimming process.

We should notify a user on import if the geojson they are trying to use is not the correct type.

@feenster My testing shows that either Polygon or MultiPolygon seems to work fine.

**Comment by feenster** [comment]
@bgirardot can you send the file you are trying to import please

**Comment by bgirardot** [comment]
Maybe I needed to ctl-f5, which i just did for another issue, but it works as expected now!

**Comment by feenster** [comment]
Phew!
