### ISSUE TITLE
Removing my email address results in error

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#529]
I had previously set my email address, but if I try and remove it and hit save it says "An error occurred when setting your contact details."

I can change it another email address, but I do not seem to be able to remove my email address.

I can remove facebook, twitter, linked in just fine.

![2017-06-08_00h53_36](https://user-images.githubusercontent.com/265831/26905043-4598d3b6-4be5-11e7-9871-1dad0d326dc6.png)

**Comment by bgirardot** [comment]
Just an update, now it errors when adding my email address.

I takes about 5 or 7 seconds after clicking "Save" but then it does give the error message.

**Comment by hunt3ri** [comment]
@bgirardot should now be resolved.

**Comment by bgirardot** [comment]
No more errors :), but one small thing, the validated checkmark does not get removed if I remove my email address.

![2017-06-14_17h23_33](https://user-images.githubusercontent.com/265831/27140685-77108920-5126-11e7-85ae-e3958b4bd8d0.png)

**Comment by bgirardot** [comment]
Fixed!
