### ISSUE TITLE
[BUG] Latest Docker Build Fails

### ISSUE THREAD

**Issue by extinctPencil** [hotosm/tasking-manager#5300]
**Describe the bug**
Projects no longer build in docker 
 Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef load_traceback
      cdef Waiter
      cdef wait
      cdef iwait
      cdef reraise
      cpdef GEVENT_CONFIG
            ^
      ------------------------------------------------------------
      
      src/gevent/_gevent_cgreenlet.pxd:181:6: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

**To Reproduce**
Steps to reproduce the behaviour:
1. Docker compose up -d

**Expected behaviour**
The project should build new docker containers

**Desktop :**
 - OS: Windows
 - Browser Chrome or edge

**Additional context**
The issue occurs with the version of gevent package
I resolved by taking a later  gevent package which also meant I had to update the version of greenlet  I updated requirements.txt 
gevent==21.8.0
greenlet==1.1.0

The chosen version numbers  were guess work !

I had successfully built the code in docker on 15th July and failed with the  indicated error on  1st August  
I re-ran the exact same build and source code absolutely no modifications .. so its an enviroment not source code issue
A detailed look at build logs suggests that an update to a later version of Python ? on teh base image before code compilation

 comparing the ApkUpdate that is run on the ubuntu container 
Working build : 
(59/60) Installing python3 (3.10.4-r0)
(60/60) Installing python3-dev (3.10.4-r0)

failed build 
(57/58) Installing python3 (3.10.5-r0)
(58/58) Installing python3-dev (3.10.5-r0)

I am not a python dev , I have solved for myself by updating gevent package versions but am not confident that these are the correct versions or there are no unfortunate consequences of doing so

**Comment by faebebin** [comment]
Same problem using `docker-compose build` on Ubuntu 20.04.4 LTS ; 

➜  tasking-manager git:(develop) docker-compose --version
docker-compose version 1.29.2, build 5becea4c
➜  tasking-manager git:(develop) docker --version
Docker version 20.10.17, build 100c701
➜  tasking-manager git:(develop) python3 --version
Python 3.8.10
➜  tasking-manager git:(develop) lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
![image](https://user-images.githubusercontent.com/21113500/185126336-7283454e-1f03-4c6d-8f49-b548dab6d614.png)

**Comment by Aadesh-Baral** [comment]
@extinctPencil  thanks for the issue. I can verify this issue on docker build.
