### ISSUE TITLE
Add TM Version to database

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#5314]
**Is your feature request related to a problem? Please describe.**
When the database schema updates, it can break some third party queries. If the version is in the database then those users can check easily if the schema changes. 

**Describe the solution you'd like**
Add a table with the current version of TM to the DB and update it when new versions come out. 

**Additional context**
Bene from Heigit requested this feature. We provide weekly database dumps (scrubbed user data) for their analyses. When we update the DB schema their processing software needs updating, so it would be helpful to have that information available on the database. 

It could also be used on the frontend to inform users of the current TM version.

**Comment by Aadesh-Baral** [comment]
@dakotabenjaminI believe there is a table in the database called 'alembic version' that is updated when the schema changes. Can this be helpful for  this case?

**Comment by dakotabenjamin** [comment]
We are referring to the Tasking Manager version here.
