### ISSUE TITLE
Allow completed and validate Tasks to be checked out for mapping

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#532]
Can we allow mappers to checkout completed and validated tasks?

We the restrictions on validation available, the requirement that only through the validation process can people look at completed or validated task squares is causing issues.

**Comment by hunt3ri** [comment]
@bgirardot  What issues specifically?

**Comment by bgirardot** [comment]
Ideally anyone can look at a validate task as an example of what a properly mapped task looks like. That is something project managers are doing (completing a task square perfectly and marking it validate) and recommending more.

Less frequently, regular mappers will double check completed task squares just make sure it is fully mapped. (most validation consists of finishing mapping.)

Hopefully it is easy to allow as I do not think anything else depends on enforcing that restriction currently.

**Comment by bgirardot** [comment]
Yes, so not causing functionally issues, but process / workflow related.

**Comment by bgirardot** [comment]
Gah, reading the title it is wrong, I mean Tasks, not Project, changing it now.

**Comment by feenster** [comment]
@bgirardot  Allowing tasks with status mapped or validated to be locked for mapping doesn't fit easily with the task state model, or the mapper level and validator role restrictions implemented in TM3.  With PR #649 I have implemented a preview button that allows users to open the task square in ideditor without doing any task locking.  This will allow any user to look at any task square in ideditor regardless of their role, or the current state of the task.  This way people take can look at the mapping in a square without having to check it out for any number of reasons (see a well mapped example, see a validated example, see an invalidated example, see a bad imagery example, quick double check of status, decide whether the task is worth working on)

**Comment by bgirardot** [comment]
I ended up commenting this option out of the UI. It was confusing and took people to an editor for the area without locking the task so was going to lead to issues.

We still need to find a way to allow folks to checkout out a validated task so they can see what a well mapped task looks like.

**Comment by willemarcel** [comment]
We changed that behaviour on TM4.
