### ISSUE TITLE
Add button for adding new teammembers to teams admin page

### ISSUE THREAD

**Issue by martien-176** [hotosm/tasking-manager#5335]
**Is your feature request related to a problem? Please describe.**

- https://tasks.hotosm.org/manage/teams/1
- https://tasks.hotosm.org/manage/teams/1

When you want to add a new teammember you have to enter their username in a textbox with text "Search for TM users". Then you have to hit the Enter key and the new teammember is added to the team. The problem: the textbox looks like a searchfield. So an admin could think they are searching a username, but is in fact adding it.

**Describe the solution you'd like**
My preferred solution would be a button to click for adding, and a button to click for search.

**Describe alternatives you've considered**
A notification inside the textbox that clearly indicates what the box is meant for and how to use it.

**Additional context**
N/A

**Comment by Ichchhie** [comment]
For me, the message looks ok, if we add somethings like "Add" button beside name as in the screenshot below:

Option 1:
![1](https://user-images.githubusercontent.com/33247422/190947863-8c4153f9-62db-425e-ab16-2d792c1caff6.png)
Option 2:
![2](https://user-images.githubusercontent.com/33247422/190947868-396f7937-625c-42b3-a9d8-ebd8eb955cf0.png)

**Comment by martien-176** [comment]
I like option 1 the most.
