### ISSUE TITLE
By default do not allow beginner mappers to be able to validate

### ISSUE THREAD

**Issue by aawiseman** [hotosm/tasking-manager#5361]
**Is your feature request related to a problem? Please describe.**
Right now, beginner mappers can validate, which leads to poor validation and the need to re-map or re-validate. PMs can change that, but often "All mappers" is selected. For example Ralph noted one project had 130 squares "validated" by beginners, missing a ton of issues.

**Describe the solution you'd like**
I think by default "All mappers" should either not be an option and it should be "intermediate and advanced mappers" by default, or "All mappers" should not include beginner mappers. 

PMs can add them later manually, but I think it should be an explicit opt-in rather than require the PM to take an additional step to prevent them.

**Comment by HelNershingThapa** [comment]
Hi @aawiseman, with https://github.com/hotosm/tasking-manager/issues/4954 being closed, the default validation permissions have been set to "Only users with intermediate or advanced level". Does this resolve your issue as well?

Default mapping and validation permissions screenshot:
![default-permissions](https://user-images.githubusercontent.com/51614993/192131143-9eab7231-9304-411c-b598-d80737b1bc74.png)

**Comment by aawiseman** [comment]
Thank you, yes this is great!
