### ISSUE TITLE
[BUG] Search for Tasking Manager users displays limited user list

### ISSUE THREAD

**Issue by canunen** [hotosm/tasking-manager#5363]
When searching for users to add to teams or assign as managers to organizations, the generated dropdown list displays only a limited number of users and the user in question might not be listed. 

**To Reproduce**
1. Go to an organization's management page.
2. Click on  'Edit' on the Managers section
3. Click on the 'Search for Tasking Manager users' search box and write the username
4. The desired username might not appear on the resulting dropdown list, making it impossible to add a certain user sometimes. 

**Expected behavior**
If there is an exact match, it should be listed at the top, followed by partial matches.

**Screenshots**
![image](https://user-images.githubusercontent.com/13434280/192013538-500fa1fb-57d0-4542-99c1-1907d4a13cee.png)

**Desktop (please complete the following information):**
 - OS: Windows 11, PopOS! Linux
 - Browser: Chrome
 - Version 105.0.5195.127 (Official Build) (64-bit)

**Comment by aaj013** [comment]
@canunen Is this fine? https://github.com/hotosm/tasking-manager/pull/5367#issuecomment-1261701861
