### ISSUE TITLE
Cannot use the Log in function in the frontend page.

### ISSUE THREAD

**Issue by jrip-geo** [hotosm/tasking-manager#5368]
**Log in fails**
I'm seeing errors such as "Oauth2 requires https/secure connection" or "Blocked loading mixed active content" when trying to use Nginx to serve out the frontend as https. I'm not sure if there is a better way to serve out the application as https.

**To Reproduce**
1. Git pull the develop branch.
2. Navigate to the main tasking-manager directory.
3. Added external DNS URL to the tasking-manager.env file.
4. Pointing to external SQL instance.
5. Run the "make up" command.

**Expected behavior**
I expected the frontend and backend to serve out in http and be able to log in and coordinate tasks with an OSM server.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.x
 - Browser [e.g. chrome, Firefox, Edge]

**Additional context**
Does the production stack require https? if so, are there any instructions or feasible ways to serve out the containers as https? Where should I look?

**Comment by Aadesh-Baral** [comment]
Additionally, we must include this note in the instructions for development setup.

**Comment by jrip-geo** [comment]
Thank you Aadesh! How do we set it to https for production? do we have to modify Traefik or do you guys use other tools?

**Comment by jrip-geo** [comment]
UPDATE: so I've gotten traefik to route as https, but for some reason it seems that the tasking-manager.env is not being read or the configs I'm applying in tasking-manager.env are not being accepted or implemented. I have tasking-manager.env under the main /tasking-manager/ dir. I'm pointing to https in the TM_APP_URL but in the browser it's showing that it's requesting http in that link instead of the https link that I'm trying to refence to in the .env file. My docker-compose.yml is referencing the tasking-manager.env like this: 
![image](https://user-images.githubusercontent.com/107219961/193379135-a23e9f9c-5fe3-4870-8ec8-70a7148af6ce.png)

**Comment by Aadesh-Baral** [comment]
OSM OAuth2 application accepts http://127.0.0.1 but not http://localhost. So you can add http://127.0.0.1:3000/authorized as redirect uri on OAuth2 application. Also you need to run frontend on 127.0.0.1 instead of localhost.

**Comment by jrip-geo** [comment]
Do you have a discord I can jump into with you Aadesh?

**Comment by Aadesh-Baral** [comment]
Sorry I am not on discord. But there is [hotosm slack](https://hotosm.slack.com/) where we can have a chat. There is #tasking-manager channel dedicated to TM related discussions which might be helpful for you too.

**Comment by jrip-geo** [comment]
It says I need a hotosm.org email to log in, but I just jumped into the https://meet.jit.si/TaskingManagerCollectiveMeetUp channel for the project if you have 2 minutes @Aadesh-Baral

**Comment by jrip-geo** [comment]
For now to close the original purpose with this issue: in production, in order to communicate with a built production OSM server you have to do it over https, with the backend serving on https, with Oauth2. Otherwise it will error out requesting Oauth2 over https. I achieved this with the "make up" command process for the docker container deployment by modifying the docker-compose.yml to serve out the frontend and backend via https through Traefik the service. It did not like the NGinx approach for reverse_proxy to the localhost, this resulted in the sign in failure issue where the connection gets blocked for mixed content redirection.
