### ISSUE TITLE
[BUG] OSM Galaxy mapathon detailed report does not work on Safari

### ISSUE THREAD

**Issue by aawiseman** [hotosm/tasking-manager#5373]
**Describe the bug**
https://galaxy.hotosm.org/mapathon-report/detailed does not work on Safari, nothing happens when you click "Submit"

**To Reproduce**
1. Go to https://galaxy.hotosm.org/mapathon-report/detailed
2. Enter something
3. Click Submit your query
4. Nothing happens

**Expected behavior**
It should be working.

The summary report works fine on Safari.

**Desktop (please complete the following information):**

 - OS: MacOS 12.6
 - Browser Safari 15.6.1 (17613.3.9.1.16)

**Screenshots**
<img width="1792" alt="Screen Shot 2022-10-06 at 11 41 44 AM" src="https://user-images.githubusercontent.com/5025092/194394601-da41670f-04ea-4ba6-bd86-3842509d774d.png">

**Comment by Aadesh-Baral** [comment]
This issue is not related to Tasking Manager. Perhaps the [Galaxy API](https://github.com/hotosm/galaxy-api/issues) is the appropriate location for this issue.

**Comment by aawiseman** [comment]
Thanks, will do
