### ISSUE TITLE
Map Tile Not Loading Regardless of imagery chosen

### ISSUE THREAD

**Issue by jamattey** [hotosm/tasking-manager#5379]
Hello, 

Here is a screenshot from a user during a recent mapathon. Please let me know what the diagnosis and possible fixes are. 

![image](https://user-images.githubusercontent.com/69109175/195334073-d19cf73d-a53f-4eaf-8524-cf07ae23e2d5.png)

**Comment by jamattey** [comment]
@HelNershingThapa  All the above suggestions have been tried but without success.

**Comment by HelNershingThapa** [comment]
@jamattey Could you also try clearing your cache for the site's data? Click on the lock icon beside your URL address bar and clear site data. I sincerely apologize for this inconvenience.

**Comment by ramyaragupathy** [comment]
stale
