### ISSUE TITLE
 [BUG] need of hard refresh acknowledged while testing OAuth 2.0

### ISSUE THREAD

**Issue by Ichchhie** [hotosm/tasking-manager#5388]
**Describe the bug**
Need of hard refresh after a new release has been a issue in Tasking Manager. And it has been more prominent with the implementation of OAuth 2.0. 
**To Reproduce**
1. Go to 'https://tasks-stage.hotosm.org/'
2. Log out of the existing account
3. Log in again
3. You will see the message as shown in the screenshot
![Staging site test 1 (1)](https://user-images.githubusercontent.com/33247422/196933890-1b966f85-58f9-4e94-936c-b3707a64660b.jpg)
4. Ctrl+Shift+R will fix the issue
5. Click Login, it won't do anything and throws Internal Server Error on backend
6. Need to hard refresh, but sometimes it takes multiple iteration

**Expected behavior**
Login without any issue on second login after first one

**Comment by Aadesh-Baral** [comment]
@Ichchhie can we close this issue now?

**Comment by Ichchhie** [comment]
Yes, we can do that as this is no longer an issue and OAuth2.0 was not the culprit.
