### ISSUE TITLE
Mapper contribution page - aka "Front Page" for project selection

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#54]
This page is very much like the "Front Page" in the Tasking Manager 2, but allows for more easily tailoring the listed projects for what a mapper would like to work on.

http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/contribute

This issue was created early in the development process, so the functionality is not fully available yet, we are looking for general feedback on the features presented via the UI, but know that some of the UI is non functional.

**Comment by bgirardot** [comment]
Can we change "tags" to be both tags or project number?

**Comment by giblet22** [comment]
I like being able to filter by difficulty level. Could we also filter by priority?

**Comment by Kazeem12** [comment]
Great work, I am not able to go beyond step 2: define tasks. Am I missing anything?

**Comment by Vaomatua** [comment]
I think this is a positive remodel.
I think it would be great to also search by country.

**Comment by dekstop** [comment]
Minor issue (potentially to do with the test deployment approach): I had to disable Ghostery, otherwise it wouldn't style the page. It filters Elastic Beanstalk as a tracker/ad network.

More important: I think it would be good to have a basic search form on every page, especially the landing page, as we have now in TM2. That way, people who know where they need to go don't need that extra click. This will also help reduce complexity during mapathon briefings, which often start with "go to project #X".

**Comment by RAytoun** [comment]
I like and 100% agree that a front page was necessary.
The early versions had the entry straight onto the tasks which was great for volunteers that were new to the Tasking Manager, they could just click on any project and get started.
The new front page is a bit more daunting for a new person. Could we have a panel near the top that clearly says something like ... "Welcome to the Tasking Manager. If you are new to the Tasking Manager please read the following quick guide before starting". Then link this to some very basic bullet points.

**Comment by bgirardot** [comment]
@RAytoun Hi Ralph, the links I posted were directly to functionality. The actual front page of the Tasking Manager, which is what people will see when they are not logged in is this:

http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/

Which I think addresses your comment. You will also notice there is a learn navigation button on the top of that main page.

**Comment by michael63-osm** [comment]
Looks great!

What I like particularly: 
 - good navigation within a project using clearly visible buttons
 - a clear differentiation between mapping and validation
 - more colour codes for the tiles letting invalidated tiles stand out clearly and an option to mark bad imagery (what does locked indicate?)

But I experience a navigation error: When I move on to page 2, select one of those two projects there using the contribute button and go back with my browser's back button then I end up on page 1. Not quite what I expect. Imagine this flow: I browse through some pages, find an interesting project, choose it, find out that it is too difficult for me and want to continue browsing the list.

**Comment by mataharimhairi** [comment]
Perhaps to try and make it less confusing for newbies, the 'Contribute' page for 'Beginners' is defaulted to projects focused on mapping building and roads. This means there are no filter options and the easiest type of mapping tasks are automatically presented to beginners. 

The filtering options are then only available to 'Intermediate' and 'Advanced'. Still, not opposed to even further variations on filtering based on level, between 'Intermediate' and 'Advanced'.
