### ISSUE TITLE
[BUG] Frontend breaks after deleting a team

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#5414]
**Describe the bug**
On staging instance, the frontend breaks after deleting a team.

**To Reproduce**
1. Go to a team you manage
2. Click on delete team
3. Confirm the deletion

**Expected behavior**
Redirect to Manage teams page

**Screenshots**

**Additional context**
Happening on staging instance

**Comment by HelNershingThapa** [comment]
Closed with https://github.com/hotosm/tasking-manager/commit/89b4bdfc19890990284f47c2d0e527fcbb2d3b0e being merged in--success messages were missing. Thank for reporting @willemarcel
