### ISSUE TITLE
[BUG] Can not create team in staging instance

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#5415]
**Describe the bug**
in stage instance, it's not possible to create team with "Anyone can join" or "By request" methods.

**To Reproduce**
1. Go to Create team page
2. Fill all the input fields
3. Select "Anyone can join" or "By request"
4. The create team button is yet disabled

**Expected behavior**
Create team button should be enabled

**Screenshots**
![image](https://user-images.githubusercontent.com/666291/203135738-fe9cf0c5-b917-485c-aa3e-77266c5b5c65.png)

**Comment by HelNershingThapa** [comment]
Thanks for catching this, @willemarcel. The submit button depends on the value of the visibility option to be enabled. Nonetheless, the value is only initialized once you select the 'by invite' option from the radio buttons. We should have tested this functionality extensively when we introduced the team join methods in #5375. Thank you for catching that.
