### ISSUE TITLE
[BUG] When validating multiple tasks at once after clicking on comment button it goes to Error page

### ISSUE THREAD

**Issue by Patrik-Br** [hotosm/tasking-manager#5428]
**Describe the bug**
When user lock multiple tasks for validation at once and click on [+Comment button](https://prnt.sc/Lr5IGhQpK7vZ) to give feedback it will redirect him to [Error page](https://prnt.sc/_Pf5WynqfXCh) and the Return button doesn't work. 

**To Reproduce**
1. Lock at least 2 tasks for validation
2. Click on [+Comment button](https://prnt.sc/Lr5IGhQpK7vZ)

**Expected behavior**
Be able to write a comment to give feedback. 

**Screenshots**
![image](https://user-images.githubusercontent.com/83399473/204757619-8912f39d-b161-4881-b2dd-80d26b5cf452.png)
![image](https://user-images.githubusercontent.com/83399473/204757663-da50e49c-ca04-4f32-a405-6a9ecd86c78f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 22H2 (Build 22621.819)
 - Browser: Vivaldi
 - Version: TM v4.5.0

**Comment by HelNershingThapa** [comment]
Resolved with https://github.com/hotosm/tasking-manager/commit/1f37fa2018fd614bc466f07c212545dc6956b05f. We apologize for the inconvenience and appreciate your reporting; we will work to get this into production as soon as possible.

**Comment by martien-176** [comment]
I had exactly the same issue, i am glad it is solved now.

Hopefully it will be published quickly, this is a bit of a pain.

**Comment by dakotabenjamin** [comment]
This change has been deployed- thanks for bringing the issue to our attention!
