### ISSUE TITLE
OSM Authentication Not Working 

### ISSUE THREAD

**Issue by jamattey** [hotosm/tasking-manager#5433]
<img width="506" alt="Screenshot 2022-12-01 at 1 47 53 PM" src="https://user-images.githubusercontent.com/69109175/205069210-5418b577-a673-4de5-864e-16093d4ac3b6.png">
Here is feedback for my auth attempt with OSM. 

Kindly check if there is an issue with the authentication service

**Comment by Aadesh-Baral** [comment]
Hi @jamattey, Thanks for the issue.  Please try again after hard refreshing Tasking Manager in your browser with ctrl+shift+R (cmd+shift+R on Mac). Please let me know if this resolves your problem.

**Comment by jamattey** [comment]
Hi @Aadesh-Baral it is working now
