### ISSUE TITLE
Support ability to view info about task you mapped by clicking on the map

### ISSUE THREAD

**Issue by HelNershingThapa** [hotosm/tasking-manager#5435]
**Is your feature request related to a problem? Please describe.**
[from Slack](https://hotosm.slack.com/archives/C319P09PB/p1669911707915239) `The new tasking manager has a popup for tasks you've mapped: "You cannot validate tasks that you mapped". The note is fair enough, but it also prevents the task being selected. There's lots of other reasons to want to select a task you've mapped, e.g., review its history.` Tracking the issue here.

**Comment by ramyaragupathy** [comment]
As a first step, we will start enabling task selection via the map for those tasks that were mapped by the user.
