### ISSUE TITLE
[BUG] Members removed from team while enabling/disabling team join notification

### ISSUE THREAD

**Issue by Aadesh-Baral** [hotosm/tasking-manager#5441]
**Describe the bug**
User in slack reported that if team join notification switch is turned on/off every members of a team except the one who clicks the switch are removed from the team.  

**To Reproduce**
1. Go to team edit page.
2. Set your team join method to by request.
3. Click on team join method switch
5. You can see all members except you getting removed from a team.

**Expected behavior**
None of the members should be removed from the team.

**Additional context**
When the team join notification is enabled/disabled a PATCH request is made to /team/<team_id>. While inspecting this request i found out that all the members except the user that is performing the action removed from the payload itself. So i think this issue is more on frontend side. 

Conversation on slack: [here](https://hotosm.slack.com/archives/C319P09PB/p1670014170691819)

**Comment by aawiseman** [comment]
Another team manager (LemonEarlMapper) was adding people to the team and she, myself and another colleague all just got removed from it somehow @Aadesh-Baral @dakotabenjamin
