### ISSUE TITLE
Complete endpoint level testing 

### ISSUE THREAD

**Issue by Aadesh-Baral** [hotosm/tasking-manager#5442]
The Tasking Manager API endpoints aren't being tested. As a result, any dependency updates or major changes to the existing code are extremely challenging. To avoid problems in these instances, we need to have at least complete tests at endpoint level.

- [x] Projects #5489 
- [x] Users #5597 
- [x] Tasks #5572 
- [x] Organisations #5570 
- [x] Comments #5641 
- [x] Notifications #5715 
- [x] Teams #5598 
- [x] System #5776
- [x] Interests #5616 
- [x] Campaigns #5592 
- [x] Licences #5638
- [x] ~Grid~
- [x] ~Annotations~
- [x] Countries #5637 
- [x] ~Favourites~
- [x] Issues #5665
- [x] ~Mapping~

**Comment by ramyaragupathy** [comment]
@Aadesh-Baral - in order to prioritise the endpoints, let's take data on query insights from the RDS. Working w/ @dakotabenjamin to see if this could be retrieved as a sql dump for us to map to specific endpoints.

Otherwise as discussed let's moved the `api` folder to `integration tests` section.

**Comment by Aadesh-Baral** [comment]
@ramyaragupathy yes sure query insights will help. I've moved `api` folder to `integration` tests section on #5489.

**Comment by Aadesh-Baral** [comment]
closing this as all of the tasks in this issue are complete.
