### ISSUE TITLE
TM 3 comments and suggestion

### ISSUE THREAD

**Issue by kombe1207** [hotosm/tasking-manager#545]
The TM 3 new demo was doing great as i tried to use it, i was just suggest the followings..

1. Layes when you edit by using JOSM appears 4 layers so i was ask to reduce  those layers if possible,by joining some of them to be one layer.
2. TM 3 window has got many features,.. so i suggest chart icon to be placed at the right side part of the footer.
 Generally TM 3 demo was looks cool.

**Comment by bgirardot** [comment]
@kombe1207 Hi kombe, the 4 layers does not sound right. That sounds like something is not working correctly.

It should be only two layers, one with the task square outline and one to edit osm data on.

**Comment by PaulUithol** [comment]
Which project was this @kombe1207 , the one Russ posted for the RH team?

**Comment by PaulUithol** [comment]
http://tasks-demo.hotosm.org/project/1
