### ISSUE TITLE
Login problems - Keep getting redirected to login

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#546]
(this needs more testing on my part, submitting it triggered a few ideas that I need to explore to see if I can find out exactly the steps or situation that causes it. So I am submitting it and then closing it and will re-open it if needed or I get better steps to recreate.)

This has been happening for a while to me, but I thought it was because of the staging and using different servers etc... but now I am getting reports of it from several other folks who do not access different versions of the software.

Upon visiting the staging site I see this page, which I can not figure out how to get to on purpose, but find it when returning to the site:

![2017-06-10_13h32_07](https://user-images.githubusercontent.com/265831/27002394-617360a8-4de1-11e7-834e-e161db3645d2.png)

I click on either of the two Login buttons, am taken to OSM to grant access, and then am returned to exact the same page.

I stopped loading the page mid process to capture this URL box in case that helps:

![2017-06-10_13h33_52](https://user-images.githubusercontent.com/265831/27002406-aada2d80-4de1-11e7-8eb7-07fa5e56493d.png)

But still just ended up back here:

![2017-06-10_13h34_52](https://user-images.githubusercontent.com/265831/27002410-bfe35e4a-4de1-11e7-9f1f-977ff3563ea0.png)

Opening an Incognito window allows me to login normally.

**Comment by bgirardot** [comment]
We go more reports of this from the larger scale user testing.

**Comment by feenster** [comment]
We haven't been able to recreate this, however, one theory is that there may be a rogue network request to one of the authenticated API's that is returning a 401 and causing the client application to redirect to the login page.  We will investigate further, but if this issue is seen again by anyone, it would be helpful if you could take a look at what network requests were made by the browser and identify if any of them are getting 401.  In chrome, press f-12 to get developer tools, then click on the network tab to see the requests.

**Comment by smit1678** [comment]
I've been seeing this and it looks like the endpoint `http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/api/v1/user/nsmith` is getting a 401. 

![hot tasking manager 2017-06-23 13-01-22](https://user-images.githubusercontent.com/796838/27481350-107768ba-5814-11e7-9dc4-9b39eb64be87.png)

**Comment by bgirardot** [comment]
One of the things I just noticed trying to get reproduce this on demand is that, when i log in, just after leaving the OSM site granting access, i actually see that short login screen for about 1 or 2 seconds, and then it reloads the landing page properly logged in.

So that page seems to even be part of the "path" of logging in successfully. It just seems to get stuck on that page sometimes.

**Comment by bgirardot** [comment]
Added details:

User report: Asking me to login when I already am, this is using Firefox on a Windows 10

Happens to me on Win 7 using Chrome

**Comment by feenster** [comment]
@bgirardot @smit1678 OK, we think we have this fixed with the above PR  I will close the issue for now, as it can be reopened if it reoccurs.
