### ISSUE TITLE
[BUG] Unexpected Error Upon Resuming Task

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#5472]
**Describe the bug**
While having a Task locked for validating, if I navigate to another project and try to lock a Task for mapping - I get an error when I click the "Return to Project #X" button.  **Note** - this error I believe is related to first locking a task for Validation, then trying to lock one for mapping/validation; it does not happen when you have a Task locked for mapping and then try to lock one for mapping or validation. In other words - as long as the first action is to lock for Mapping, then it works as expected.

**To Reproduce**
1. Go to any Project with Tasks to validate
2. Select a Task to validate
3. Navigate to a different Project with Tasks available to map
4. Select a Task to map (this should give you the pop-up that you already have a Task selected in another Project)
5. Click the "Go to project #X" (project in step 1) button (see first image)
6. See error page (see second image)

**Expected behavior**
The expected behavior should be that no matter what the second step (i.e. attempting to lock a Task for mapping/validation) is, you should be directed back to your previously locked Task (whether that be for mapping or validation).

**Screenshots**
![ErrorCause](https://user-images.githubusercontent.com/6763645/206952298-b7744776-7bbb-45bd-9b2d-25502cc0956f.JPG)
![errorpage](https://user-images.githubusercontent.com/6763645/206952308-0838bd89-ce2c-4991-92b2-b5a5f965e5df.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - TM Version latest (4.5?)

**Additional context**
Potentially related/tangent to #2466

**Comment by HelNershingThapa** [comment]
Resolved with c6bfa756b780fc5b94fb2352a3b7855b3a03256d being merged in--we had a typo that caused the error :sweat_smile:
