### ISSUE TITLE
Revert All Tasks State by Specific Username

### ISSUE THREAD

**Issue by adiatmad** [hotosm/tasking-manager#5484]
**Is your feature request related to a problem? Please describe.**
Franz [noticed](https://hotosm.slack.com/archives/C4GLC45PY/p1671119145917509) that a new mapper is more focusing on validation an ignores warnings of the issue triangle and hardly corrected issues. That new mapper already validated many tasks in  different project.

**Describe the solution you'd like**
Project manager can revert all tasks state by specific username

**Describe alternatives you've considered**
Provide option `Advanced level` only as validator, not including `intermediate level`. The current option available is 
`Who can validate? Users with intermediate or advanced level`. 

**Additional context**
Follow up discussion [is here](https://hotosm.slack.com/archives/C03800TQKK2/p1671199835706839)

**Comment by ramyaragupathy** [comment]
@adiatmad - per discussion with the team today, we will go ahead include this as an option under `Edit project` -> `Actions` section. For now it is better to not club this feature with the permissions and the user mapping levels as we are discussing to revamp the idea of mapping levels.

cc @HelNershingThapa @Aadesh-Baral @Ichchhie
