### ISSUE TITLE
[BUG] When I tag an user who contributed into task in the task window it close itself instantly

### ISSUE THREAD

**Issue by Patrik-Br** [hotosm/tasking-manager#5486]
**Describe the bug**
As Frans reported on Slack, when I try to tag a user who contributed into task after I click on their @username the window close so I am not able to finish/send my message. 

**To Reproduce**
1. Go to https://tasks.hotosm.org/projects/XXXXX/tasks/
2. Click on "See task history" of any task
3. Click on "All" to see contributors of the task
4. Start typing message and try tag any of the users with @
5. The window will close on it's own

**Expected behavior**
The task window will not close on it's own so I am able to tag user and send a message.

**Screenshots**
[Video recording of reproducing the issue.](https://sendspark.com/share/pv1wcdtx158ogtsm)

![image](https://user-images.githubusercontent.com/83399473/208449325-d8c66f46-2c14-4dcf-8769-5b17dbbc711f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 22H2 (Build 22621.819)
 - Browser: Vivaldi
 - Version: v4.5.1

**Comment by SColchester** [comment]
Was about to report this, +1 would be great to fix, issue is new with WYSIWYG

**Comment by ramyaragupathy** [comment]
@HelNershingThapa is already working on a fix for this and we will push it to production as early as possible . cc @dakotabenjamin
