### ISSUE TITLE
Project Creation Process

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#55]
This is the initial project creation process. The most enjoyable feature is the "pre-splitting" task squares.

Again, this is not fully wired up yet, and the editing of the meta-data on the project is currently not connected or was not connected when this feedback request was made.

http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/admin/create-project

**Comment by giblet22** [comment]
I love that I can split tasks ahead of the project creation but I don't necessarily like that I have to draw another area. Might be more intuitive to just be able to select a task or select all the ones you want then press `split` or something similar. If I only want to split one task and keep the ones around it the regular size, I still have to draw a shape and clicking a bunch of times to split one task is kind of difficult.

**Comment by giblet22** [comment]
I like having "the size of each task is xx.x sq km" but it's not easy to fix that without re-drawing the AOI. If possible to add a slider or box to input the size of grid you want, even if you end up losing a little bit of your AOI, if that value will be on there, it should be easier to adjust it.

**Comment by michael63-osm** [comment]
@giblet22 Not sure if that was fixed during the past two weeks but I see that in step 3 you can split individual tasks either in point mode by selecting them with the mouse or in polygon mode by drawing a polygon across the tasks you would like to see split.

**Comment by d3netxer** [comment]
what are campaign tags? will they probably match what we also usually put in the changeset comments for projects?
