### ISSUE TITLE
[BUG] The scroll bar on project page doesn't go all the way down

### ISSUE THREAD

**Issue by Patrik-Br** [hotosm/tasking-manager#5517]
**Describe the bug**
The scroll bar on project page doesn't go all the way down so I am not able to see all the text there.

**To Reproduce**
1. Go to any project page that has long description, for example https://tasks.hotosm.org/projects/13594
2. Try scroll down

**Expected behavior**
Be able to scroll down and see all the text without having to zoom out my browser.

**Screenshots**
[Video how I replicated this issue.](https://sendspark.com/share/12jvyk4jtz6p55hc)

![image](https://user-images.githubusercontent.com/83399473/211900761-785b234a-74f3-4dff-8c9e-45f2f47b6a5a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 22H2 (Build 22621.819)
 - Browser: Vivaldi
 - Version: TM v4.5.1

**Comment by HelNershingThapa** [comment]
I believe this issue has been resolved with the inclusion of https://github.com/hotosm/tasking-manager/pull/5516. @Patrik-Br - Could you please confirm that this works for you on the staging instance?

**Comment by Patrik-Br** [comment]
I can't find there a project with instructions that are long enough to be able to test it myself but on your GIF it looks fixed. So I take it as solved. Thank you

**Comment by HelNershingThapa** [comment]
Cool, if you'd still be interested in checking the fix, try it out with this [one](https://tasks-stage.hotosm.org/projects/8626).
