### ISSUE TITLE
Multiple messages for bulk validation/invalidation

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#552]
We should limit validation and comments during bulk validation to just one message.

At the moment, if 20 of my tasks get validated and the validator leaves a comment, I get 40 messages.

**Comment by bgirardot** [comment]
I have been looking at how we might mitigate this issue.

It looks to me like if we could wrap these lines in an if block:

https://github.com/hotosm/tasking-manager/blob/develop/server/services/validator_service.py#L95-L105

That might do the job mostly.

The if would test a variable to determine if the block has been entered or not and after it has been entered once it would just be skipped after that one time.

<pre>
message_sent = false
...
if messsage_sent is false do
      lines 95-105
      set message_sent to true
</pre>

setting the initial message_sent variable needs to happen between 91 and 92 or before.

It does not look to me like that should affect anything else and still should work in the case where there is only 1 task being validated, but the message that gets sent will be imperfect as it will not reflect that more than just one task has been validated.

Does that seem like it would work to you? I think it is imperfect, but would mainly address the issue.

@feenster @hunt3ri

**Comment by hunt3ri** [comment]
Hi @bgirardot it's slightly more complicated than that, as if there's multiple users in the bulk update, only the first user would get the message.  So we'd want to use an array, something like:

<pre>
message_sent_to = []

if task.mapped_by not in message_sent_to:
    send_message()
    message_sent_to.append(task.mapped_by)
</pre>

**Comment by hunt3ri** [comment]
@popelnuh this should be ready to test.  If you validate multiple tasks you should only receive one message rather than a message for every task validated.

**Comment by popelnuh** [comment]
Working as expected. When multiple tasks are validated, there is one message sent to the mapper's inbox.
