### ISSUE TITLE
Improve circle-ci build and deploy pipeline

### ISSUE THREAD

**Issue by Aadesh-Baral** [hotosm/tasking-manager#5539]
I believe there are several improvements that might be done to the CircleCI build.
1. Separate frontend and backend build jobs so that they may be easily restarted if one of them fails. Currently, if one step fails, the entire build process must be restarted.
2. Only trigger the frontend build and deployment (staging) if a change in the frontend directory is detected. (A similar case should be made for backend build and deployment).

What are your thoughts on this? @dakotabenjamin @ramyaragupathy @eternaltyro

**Comment by eternaltyro** [comment]
I am currently working on this.

**Comment by eternaltyro** [comment]
> 1. Separate frontend and backend build jobs so that they may be easily restarted if one of them fails. Currently, if one step fails, the entire build process must be restarted.

This piece is done.
