### ISSUE TITLE
2 separate layers in JOSM sometimes make user confuse

### ISSUE THREAD

**Issue by harrymahar** [hotosm/tasking-manager#556]
When we start to edit/mapping or validate in JOSM there are 2 layers that will be added in our JOSM. Some cases, they could make user confused about it. One layer is OSM Data layer for validation and the other is task boundaries.

It might be better if the layer only layer for edit/map and the layer for tasking boundaries does not need to add into JOSM because there is a possibility user can edit the layer boundary and if user already add a lot of tasks then it would be very confusing as name of the layer is same in JOSM.

**Comment by bgirardot** [comment]
@feenster We are getting a fair amount of feedback about this.

I think the best solution is that if people are just mapping or validating 1 task square, they do not get the task polygon and the task polygon layer. Keep that just for multiple task squares during validation. 

hopefully you can add a switch someplace that tells the api to either create or not create the task polygon layer. if it is just one task, activate the switch that disables that functionality.
