### ISSUE TITLE
[BUG] Rapid is not behaving correctly after sidepanel collapse

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#5564]
**Describe the bug**
After hiding the TM sidebar, RapiD doesn't load tiles for the entire screen

**To Reproduce**
1. Open a task in embedded Rapid editor
2. Hide the right TM sidebar
3. Check that some tiles and OSM data are not rendered by Rapid on the right side of the screen. When tracing a line, the mouse cursor is in one place, but the tip of the line is on another position of the screen.

**Expected behavior**
Map tiles and OSM data should be loaded correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/666291/216973179-793081cd-5642-4357-be35-5cdf6f5d0dfe.png)

![image](https://user-images.githubusercontent.com/666291/216976294-074d7c25-e8f7-4886-9866-53297762be38.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 109

**Comment by danieldegroot2** [comment]
cc: @bhousel

**Comment by HelNershingThapa** [comment]
The RapiD editor context was not restarted when the side panel was toggled. Thank you for reporting @willemarcel
