### ISSUE TITLE
Request the preview for the HOT TM Messages to contributors

### ISSUE THREAD

**Issue by Janabau** [hotosm/tasking-manager#5566]
**I only notice when something appears not right in a thank you message after it is sent and I was a contributor to the project**
We use this feature practically for all MSF projects as a tool for community engagement. I have messaged on the HOT slack Tasking-Manager channel before about the issues of adding pictures in Messages, when they appeared as links. I would like to be able to check they appear as a picture and the text appears correctly, before I hit send.

**Add a button Preview next to Message all contributors**
what I want to happen is for the message to appear as it will appear in receivers' email.

You can label this **Enhancement**, I don't know how to change the Label (this one appeared authomatically).

**Comment by Aadesh-Baral** [comment]
Do you mean when you send message to all contributors of a project as a project manager?

**Comment by Janabau** [comment]
> Do you mean when you send message to all contributors of a project as a project manager?

Yes, exactly @Aadesh-Baral .

**Comment by Janabau** [comment]
Is this going to be implemented @Aadesh-Baral ?

**Comment by Aadesh-Baral** [comment]
Yes, this is on our plan. Since it requires some design changes it may take some time.
