### ISSUE TITLE
Add support to mark all notifications as read

### ISSUE THREAD

**Issue by HelNershingThapa** [hotosm/tasking-manager#5593]
**Is your feature request related to a problem? Please describe.**
I have a ton of unread notifications on my account. It's tedious to either open each notification or click on that eye-like icon to mark a notification as read. 

**Describe the solution you'd like**
I want to mark all of my notifications as read simultaneously. That would make it easier for me to keep track of newer unread notifications. Something similar to how mail platforms let you select all of your messages at once and mark them as read with the click of a button.
![Mark all notifications as read](https://user-images.githubusercontent.com/51614993/219587063-4dfefd60-9d9b-485d-8793-57369dd9f200.png)

**Describe alternatives you've considered**
Mark all notifications as read when users leave the page that lists all notifications automatically, something similar to LinkedIn.

**Comment by ramyaragupathy** [comment]
End point and unit test cases are pending
