### ISSUE TITLE
[BUG] OSI Approved icon broken on about page

### ISSUE THREAD

**Issue by watmildon** [hotosm/tasking-manager#5594]
**Describe the bug**
The about page has an img link to an external page that is broken. https://github.com/hotosm/tasking-manager/blob/ae44dc10697b5ebd03f1a12b04e7fa037b415388/frontend/src/views/about.js#L64 

**To Reproduce**
1. Go to the HOT homepage
2. Click about

**Expected behavior**
all images to load successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/118567155/219830701-fdd6a9ad-ad0f-4758-ae99-8447976af329.png)

**Desktop (please complete the following information):**

**Comment by HelNershingThapa** [comment]
Thank you for catching that, @watmildon. The link we used as the image's source had broken and needed to be replaced. It has been fixed and will be included in the next release.
