### ISSUE TITLE
[BUG] Feedback comment when validating is sent even if user click stop validation

### ISSUE THREAD

**Issue by Patrik-Br** [hotosm/tasking-manager#5625]
**Describe the bug**
When I lock a task (or multiple, doesn't matter) for validation, write a comment and click on Stop validation it will send the comment anyway.

**To Reproduce**
1. Lock any task for validation
2. Write comment
3. Click on Stop validation
4. See the comment has been added to the task

**Expected behavior**
The comment won't be added.

**Screenshots**
![image (4)](https://user-images.githubusercontent.com/83399473/223977025-4fb5edec-adfc-4791-80d5-304cfbfa69e9.png)
![image (5)](https://user-images.githubusercontent.com/83399473/223977043-6448a32b-b6fd-4cda-ac92-031276463333.png)

**Desktop (please complete the following information):**
- OS: Windows 11 Version 22H2 (Build 22621.819)
- Browser: Vivaldi
- Version: TM v4.5.1

**Comment by ramyaragupathy** [comment]
@Patrik-Br - this seems like the expected beahviour. Were you having different expectations on how this workflow has to go?
