### ISSUE TITLE
[BUG] iD fails to login and upload changes, authorization request redirects to a missing page

### ISSUE THREAD

**Issue by HellMapGoesCoding** [hotosm/tasking-manager#5630]
Embedded iD saving fails to login and upload changes, authorization request redirects to a missing page

1. Open some projects (I was doing `http://tasks.osm.ch/projects/37`)
2. Click contribute, select square, start mapping
3. Make some edits in embedded iD
4. Save
5. See error (screenshot 1), click OK
6. Save again
7. Site offers to (re)authorize logic (screenshot 2)
8. Site redirects to a 404 page (screenshot 3) (for me `http://tasks.osm.ch/projects/37/map/land.html?oauth_token=blahblah`)

Reloading page doesn't help - same sequence of events happens, except screenshot 1 doesn't show and goes straight to screenshot 2. 
Tried relogging on main site. Tried a different browser. Tried clearing all auth token on OSM site.

1. ![1](https://user-images.githubusercontent.com/111684839/224710191-f89171aa-ad23-45d9-a3b9-4da008091be6.png)
2. ![2](https://user-images.githubusercontent.com/111684839/224710201-d6761e01-9b30-4560-a612-1bb25fcc1e4c.png)
3. ![3](https://user-images.githubusercontent.com/111684839/224710199-1ead1e42-3f28-478f-9afc-b3927a1e5f5e.png)

 - OS: Windows 7
 - Browser: Opera 96, Firefox 110, Chrome 110

**Comment by HelNershingThapa** [comment]
Hi @HellMapGoesCoding, thank you for raising this issue. However, this issue belongs to another repository, which could be a fork of this current repository and maintained by the Swiss OpenStreetMap Association. I recommend posting this issue in the appropriate repository where it can receive the appropriate attention from the pertinent developers and community.

**Comment by HelNershingThapa** [comment]
I am closing this issue. If you still require support or have any further questions, please feel free to reach out to us, and we'll be happy to assist you in any way we can.

**Comment by ramyaragupathy** [comment]
@HellMapGoesCoding - Like @HelNershingThapa pointed out this issue is not relevant for this repository. Closing it here. However if you need any development assistance you can reach out to us at tech@hotosm.org
