### ISSUE TITLE
[BUG] App crashes while trying to copy comment

### ISSUE THREAD

**Issue by HelNershingThapa** [hotosm/tasking-manager#5643]
**To Reproduce**
1. Select at least two tasks for validation.
2. Click on the _Comment_ button for a task.
3. Type something, and a _Copy Comment_ button will appear.
4. Click on the Copy Comment button.
5. Find that the app has crashed.

**Expected behavior**
The app shouldn't crash, and the comment should be copied to the clipboard.

**Screen Recording**
![yesyes](https://user-images.githubusercontent.com/51614993/227141926-a8a61d16-83c3-467a-b395-2da09dd10e65.gif)

**Additional proposal/thought**
Although this button has been there for about two years, users should have been experiencing problems when they click on it ever since. I have been here for a while, but I don't think we've ever had a report on the matter. The in question functionality relates to copying, which is a fundamental computer function that, in my opinion, any user may perform without the usage of a specific button. I suggest removing the app's button functionality.

**Comment by Freedisch** [comment]
Hello @HelNershingThapa, I will look into it

**Comment by HelNershingThapa** [comment]
Sure @Freedisch. It seems like there is a problem with the corresponding message(s) that should appear after clicking the Copy Comment button. Let me know if you have any further questions or concerns.

**Comment by HelNershingThapa** [comment]
Hi @Freedisch, I was wondering if you had any updates or progress to share. Please let us know if you need any further information or assistance. Looking forward to hearing from you.
