### ISSUE TITLE
GPX name attribute cannot be translated

### ISSUE THREAD

**Issue by matheusgomesms** [hotosm/tasking-manager#5650]
**Describe the bug**
When opening a task to edit, the box surrounding the AOI displays: "Task for project xxxx. Do not edit outside of this area!".

I would like to translate that string, and could not find here on Github neither on Transifex. Do you have more info where I can translate that?

This happens both on iD and RapiD (did not test on JOSM), but I suspect this string comes from the .gpx (attribute _name_).

Thanks!

**Comment by Aadesh-Baral** [comment]
@matheusgomesms Yes this string comes from task gpx (name attribute) which is generated on backend. Until now we don't have any translations set for text generated in backend.

**Comment by matheusgomesms** [comment]
Thank you for the fix! @d-rita, where can I find this string to translate? I finished my language on Transifex and could not find it.

**Comment by d-rita** [comment]
The string should be available if the transifex repository has been updated with any new strings added to TM. Tagging @ramyaragupathy for this.
