### ISSUE TITLE
[BUG] The text of notification is going over the window. 

### ISSUE THREAD

**Issue by Patrik-Br** [hotosm/tasking-manager#5658]
**Describe the bug**
If text of the notification is longer then the notification window the text doesn't divide into multiple lines. It is just one long line.

**To Reproduce**
1. Receive any longer notification

**Expected behavior**
Text of notification dividing into multiple lines.

**Screenshots**
![image](https://user-images.githubusercontent.com/83399473/229109130-00572a0a-bd49-4b77-a258-8b9cd9d68585.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Vivaldi
 - Version: TM v4.5.2

**Additional context**
Probably related to [5556](https://github.com/hotosm/tasking-manager/pull/5556)

**Comment by Aadesh-Baral** [comment]
Should be fixed by https://github.com/hotosm/tasking-manager/pull/5605.
Keeping this open until #5605 is deployed to production.

**Comment by HelNershingThapa** [comment]
Closing this issue; expected styles have been reflected in the production instance.
