### ISSUE TITLE
[BUG] frontend build fails

### ISSUE THREAD

**Issue by nicokant** [hotosm/tasking-manager#5659]
**Describe the bug**
frontend build fails, this happens also using docker-compose build

**To Reproduce**
1. clone the repository
2. cd frontend && npm install
3. npm run build

Build fails with error:

```
> TaskingManager-frontend@0.1.0 build /home/nicokant/Work/gisdevio/tasking-manager/frontend
> npm run preparation && npm run update-static && react-scripts build


> TaskingManager-frontend@0.1.0 preparation /home/nicokant/Work/gisdevio/tasking-manager/frontend
> bash -c "if (test -a ../tasking-manager.env); then grep -hs ^ ../tasking-manager.env .env.expand > .env; else cp .env.expand .env; fi"


> TaskingManager-frontend@0.1.0 update-static /home/nicokant/Work/gisdevio/tasking-manager/frontend
> bash -c "mkdir -p public/static/id; mkdir -p public/static/rapid; cp -R node_modules/@hotosm/id/dist/* public/static/id; if ! (test -a node_modules/RapiD/dist/RapiD.css) then mv node_modules/RapiD/dist/iD.css node_modules/RapiD/dist/RapiD.css; fi; cp -R node_modules/RapiD/dist/* public/static/rapid;"

Creating an optimized production build...
Failed to compile.

./src/components/horizontalScroll/styles.scss
globalThis is not defined

```

**Expected behavior**
Build successfully

**Desktop (please complete the following information):**
 - OS: Linux Fedora
 - TM Version 4.5.2
 - Node 10.24.1

**Comment by Aadesh-Baral** [comment]
@nicokant Can you try it on node 16?

**Comment by Aadesh-Baral** [comment]
@nicokant  They are not maintained currently. However, it's on our plan to use and maintain docker scripts, and this will probably start soon.

**Comment by nicokant** [comment]
@Aadesh-Baral I created a PR with node js v16 support, let me know if there's something else I could do to fix this issue.

**Comment by ramyaragupathy** [comment]
With https://github.com/hotosm/tasking-manager/pull/5721 - node version moved to 16
