### ISSUE TITLE
Upgrade PostgreSQL version

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#5668]
Currently, Tasking Manager uses PostgreSQL 11.x. Explore moving to a later version - preferably 15.x.

 - [ ] Functional issues with Tasking Manager
 - [ ] Performance monitoring

**Comment by eternaltyro** [comment]
Staging PostgreSQL version has been upgraded to v13.10. No issues in staging. The Deployment scheduled for the week of 05 June 2023 will introduce PostgreSQL to v13.10 in production.

**Comment by ramyaragupathy** [comment]
We now use Postgres 13.13 engine
