### ISSUE TITLE
[BUG] Circle-CI fails to upload Coverage test results

### ISSUE THREAD

**Issue by eternaltyro** [hotosm/tasking-manager#5673]
**Description**
Circle-CI runs throw an error that mentions that upload of coverage tests has failed

```
Archiving the following test results
  * /home/circleci/app/tests/backend/results/coverage.xml
  * /home/circleci/app/tests/backend/results/unitresults.xml


failed uploading test results: File: home/circleci/app/tests/backend/results/coverage.xml had the following problems:
  * invalid top level element: coverage
  ```

**To Reproduce**
1. Initiate a workflow such as `build-deploy`
2. Inspect results
3. Example here: https://app.circleci.com/pipelines/github/hotosm/tasking-manager/9727/workflows/fe8551c0-23cb-4de8-8fd8-16f69a3ca839/jobs/15116

**Expected behavior**
Coverage test results are uploaded(?)

**Comment by dakotabenjamin** [comment]
I think we need to save the coverage to another directory and upload them via store_artifacts instead. The store_test_results directive only covers test results. https://circleci.com/docs/collect-test-data/. Should be a quick fix!
