### ISSUE TITLE
Exiting projects during project creation - popup too big

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#568]
given the small area of the map shown the pop up including the short description seems to be just too much text most of time.

I think we should just show the meta data about the project:
number, title, any tags, mapping type, status, %mapped, % validated, project creator, create data, last updated date.

![2017-06-14_17h05_45](https://user-images.githubusercontent.com/265831/27139756-22a567fe-5124-11e7-9979-ddd96dc2aef6.png)

**Comment by hunt3ri** [comment]
Hi @bgirardot can you Ctrl+F5 your browser, as we made a couple of tweaks to allow scrolling on popup

**Comment by bgirardot** [comment]
Yes, that is much improved for sure.

Just not sure we really need the short description and would be better off with all the meta data on the project.

**Comment by xamanu** [comment]
This has been addressed in TM4.
