### ISSUE TITLE
Project Clone does not copy allowed user list if private

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#571]
Cloning a project keeps the private setting, but does not keep the user list.

**Comment by hunt3ri** [comment]
@bgirardot what would you want to happen.  I assume keep project private and copy across the user list?

**Comment by bgirardot** [comment]
Yes, the user list should be cloned over to the new project as well.

**Comment by ethan-nelson** [comment]
Based on the code at https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/project.py#L152-L154 and a test I just ran on staging, this is fixed.
