### ISSUE TITLE
AWS SMTP setup for TM3

### ISSUE THREAD

**Issue by hunt3ri** [hotosm/tasking-manager#572]
Hi @david-hotosm @bgirardot 

During our testing here, we've discovered AWS have restrictions in place to stop spamming that you have to request AWS to lift.  So you can only send 50 emails per day at the rate of about 1 every 20 seconds.

You will want to raise those to something like 10,000 per day with 100 per minute.  Further details can be found here

http://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-issues.html

Thanks
Iain

**Comment by bgirardot** [comment]
@david-hotosm Can you update this issue? Is this something we have done?

There is a link to the form to request the lifting of the limits in the link iain provided above, it is in the 2nd major bullet point.

**Comment by bgirardot** [comment]
This is working now.
