### ISSUE TITLE
Update test cases for the notifications page

### ISSUE THREAD

**Issue by HelNershingThapa** [hotosm/tasking-manager#5722]
This issue is a follow-up to #5713 and is related to adding code coverage for the remaining files not covered in the previous pull request (PR). The files that need code coverage are located in the frontend/src/components/notifications directory and include the following files:
- deleteNotificationsButton.js
- notificationOrderBy.js
- notificationCard.js
- notificationBodyCard.js

**Comment by ramyaragupathy** [comment]
It is related to https://github.com/hotosm/tasking-manager/pull/5676?

**Comment by HelNershingThapa** [comment]
@ramyaragupathy yes, it is partially related to #5676. However, before proceeding with the test cases for this issue, reviewing and incorporating any changes made in PR #5676 that may impact the test cases would be prudent. This will help us ensure accurate test coverage and align our testing efforts with the latest changes.
