### ISSUE TITLE
[BUG] Copy link buttons not copying correct link since latest update

### ISSUE THREAD

**Issue by SColchester** [hotosm/tasking-manager#5746]
**Describe the bug**
The 'copy link' button now copies an incomplete URL along the lines of: `undefined/projects/14391/tasks?search=288`

This means that if this URL is put into an address bar and searched it returns an error. 

**To Reproduce**
1. Go to any task list in a project or any organization edit page 
2. Click on the copy link icon
3. Paste the text somewhere
4. See error in link text

**Expected behavior**
It should copy the full link which will work in a browser, i.e. not contain the 'undefined' text. 

**Screenshots**
![2023-05-01 18_33_23-Window](https://user-images.githubusercontent.com/43822967/235490609-8ed7d826-8a3d-47b3-9a7d-7f6a73ee4f9a.png)

![2023-05-01 18_47_51-Window](https://user-images.githubusercontent.com/43822967/235491226-78c851db-398a-4d47-bf4d-667a9248cbaf.png)

**Desktop**
 - OS: Windows 11 
 - Browser: Firefox

**Comment by HelNershingThapa** [comment]
Hi @SColchester thank you for reporting the issue. I want to inform you that one of our recent pull requests, https://github.com/hotosm/tasking-manager/pull/5720 should fix the issue. However, the fix is only available on our staging instance and not yet on the live instance.

Could you please test the fix on the [staging instance](https://tasks-stage.hotosm.org/) to confirm that it resolves the issue for you?

**Comment by SColchester** [comment]
@HelNershingThapa for some reason I get an issue signing into Staging instance

**Comment by HelNershingThapa** [comment]
@SColchester could you tell me more about the issue, please?

**Comment by SColchester** [comment]
@HelNershingThapa -> Infininte loop of failed logins: 
![staging-login](https://user-images.githubusercontent.com/43822967/236761730-54956d45-51dd-4ac7-8aa8-270acde5fd31.gif)

**Comment by HelNershingThapa** [comment]
Could you try it in incognito mode and see it it helps @SColchester ?

**Comment by SColchester** [comment]
@HelNershingThapa yes that works and the link copy also works 😄 👏

**Comment by HelNershingThapa** [comment]
@SColchester If it worked on the incognito, could you try hard refreshing the site? And if that doesn't work, try clearing the site's data, and that should hopefully work for you. 

I am closing this as resolved by https://github.com/hotosm/tasking-manager/pull/5720.
