### ISSUE TITLE
[BUG] Return button on error page not working

### ISSUE THREAD

**Issue by Ichchhie** [hotosm/tasking-manager#5750]
**Describe the bug**
I randomly got into the error page while trying to lock the task of a certain project. But while clicking the **_Return_** button on the error page, the web URL changed but the screen remained on the same page.

**Expected behavior**
The return button should redirect to the previous page

**Screenshots**
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/33247422/235617214-ff051f94-7269-4848-b4d1-72c078e318fa.gif)

**Comment by HelNershingThapa** [comment]
Since we were unable to reproduce the problem you reported, it has become difficult to pinpoint the exact cause or offer a specific solution. 
Keeping the issue open, and if any new information or insights arise in the future, please feel free to update.

**Comment by Patrik-Br** [comment]
Yes this behaviour happened to me as well but I don't have a way to reproduce it either.

**Comment by ramyaragupathy** [comment]
Could be related to https://github.com/hotosm/tasking-manager/pull/5954 - we can reopen if needed
