### ISSUE TITLE
Cleaning of the TM2 database - Request for comment

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#576]
In looking at some of the new features in TM3, the large number of existing projects of varying degrees of quality (never published, test projects, huge aois, very low % mapped but still open) is having an impact both on performance and on usability.

I am proposing that we trim the TM2 database of projects that are older than 60 days and have a mapped percentage of 10% or less.

If a project is only 10% or less mapped, then the value of keeping that historical data is much reduced.

Is this something we can easily do?

Is 60 days too short?

I can detail the impacts I think it would have from a project manager and user perspective shortly.

@pgiraud @smit1678 @ethan-nelson @hunt3ri

**Comment by giblet22** [comment]
Thanks @bgirardot. This would include projects that are in a draft status as well? I'll often create a handful of tasks at once (yes, sometimes of a large area) and save them when they're needed. This would likely impact several projects of ours that fit those criteria.

**Comment by giblet22** [comment]
That's not to say I haven't had my fair share of poorly made tasks that I've discarded. If I could identify which projects I'd like kept, would you be able to exclude those?

**Comment by ViolaineCartONG** [comment]
Hi ! It would also make sense for me to share with you the projects that are ok to delete so that you can delete them, as i also have a few projects in archive mode that I have never published, but plan to...

**Comment by bgirardot** [comment]
Right, draft projects, yes, should exclude those as a whole.

I think the list of projects you need to keep should be shorter. 

Maybe we can generate a list of the project that would be deleted for review before the delete process.

**Comment by NateHeard** [comment]
Sixty days might be too short but the proposal seems reasonable, especially if the candidate list were circulated before deletion. As a side note, I sometimes receive an internal service error when attempting to archive dead ends.

![image](https://user-images.githubusercontent.com/13320367/27184431-27265c8e-51b0-11e7-982b-afc84d970733.png)

**Comment by giblet22** [comment]
@bgirardot a list of projects to be deleted would be great. Thank you!

**Comment by ViolaineCartONG** [comment]
what about projects that are more than 60 days old and where people are still mapping/there is still activity on these? i would not delete them...

**Comment by mikelmaron** [comment]
I think that's a reasonable cut off to clean up and archive projects periodically -- I know @dalekunce was doing this periodically.

However @bgirardot this is concerning

> an impact both on performance and on usability.

Considering that we have just a few thousand projects, I wouldn't expect there to be any performance issues. Is there a ticket on this? Maybe the performance issues need to be profiled and optimized, on the first order, rather than looking to delete projects.

**Comment by bgirardot** [comment]
I think we will run some queries and see how many projects there are that are archived with 0, 1, 2 ... 10 percent mapped.

Maybe we need to drop the cap down to 5% and up the days to 120 or 240 but I personally do not see any value in projects that are more than 6 or 12 months old or older and have only 10% mapped. They essentially, from a project planning perspective did not have enough of an impact to adjust future project planning based on. Which is why we keep the projects around, to inform future project creation.

Any map data is valuable map data, that is not what I am saying. 

I am saying that the project itself is of little value when so old and so little progress, it would still need to be re-examined and re-mapped under any future projects.

**Comment by mikelmaron** [comment]
@bgirardot I agree, there may be little value in keeping these projects open, and glad we are gardening. They should be archived.

BUT I'm troubled that a driver for this is performance. We should not be seeing issues in performance with this number of projects.

**Comment by dalekunce** [comment]
I second @mikelmaron. Cleaning the projects is a good idea. It's something I've been doing on tm2 for a couple years now. It's very concerning that performance of tm3 is the driver for this. I would consider this a blocker and work hard to figure out why this is an issue before moving forward.

**Comment by hunt3ri** [comment]
@bgirardot we've not seen any significant perf problem locally, and certainly no-one has reported any problems on github?

**Comment by smit1678** [comment]
@bgirardot Correct me if I'm wrong but the reason was based on the performance that was raised here: https://github.com/hotosm/tasking-manager/issues/530#issuecomment-308714453.

**Comment by pgiraud** [comment]
I'd be interested to know which performance issues are expected. Because, if we solve issue by doing some clean up after importing projets from TM2 in order to decrease the number of projects, this means that we will have to do the same in 6 months.

**Comment by bgirardot** [comment]
Ya, it is just that in some of the areas that are covered with several really large project, like the road import projects, it is difficult to really appreciate the existing project footprints unless you really zoom out.

Which means a fair amount of data has to be loaded. If we have projects that are not really serving any purpose, especially what were essentially test projects, then getting rid of them will have a positive impact on the view of existing project footprints.

As I said, I think we should do some db queries to see what the real numbers are.

Maybe we just go with very conservative, archived projects, less than 5% and see how many that actually is. It might not be worth it.

**Comment by bgirardot** [comment]
@pgiraud We can delete projects now, so things that got created and turnout to be mistakes or tests, etc can be deleted, that will help keep the build up of those projects at least down.

We also have more experience creating projects and what works best so some of the less optimal projects of the past probably would not be created today.

**Comment by hunt3ri** [comment]
Ah thanks @smit1678 yes the concern we're flagging there is to do with response size rather than overall performance of the application.  So yes if we have lots of low value projects kicking around it's just increasing the payload size.  So on a slow connection you'll have a few MB of data to download, which can be mitigated by removing old data.

We currently have 2500 projects in our test system running on 1 small AWS instance, and it seems pretty snappy.  All feedback welcome

http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/

**Comment by mikelmaron** [comment]
Ok so archiving projects will address this issue, rather than delete?

One idea to improve map performance -- use vector tiles rather than load GeoJSON

**Comment by feenster** [comment]
Perhaps also worth noting that the specific issue discussed in #530 affects the map on the project creation page used by project managers to create new projects.

The main contribute page where mappers and validators do their mapping and validating is not affected.

**Comment by bgirardot** [comment]
No, archiving it will not help, we show the archived projects on the project creation map.

I am not hearing any case for why keeping old archived projects that have a few % of mapped tiles or 0% should be kept.

**Comment by Geocruizer** [comment]
All of my archived projects can be removed.  Thanks

**Comment by rbanick** [comment]
I think that 5% and a 6 month cutoff are fair. @bgirardot We should signpost this somewhere on the website so it's well understood by users.

**Comment by xamanu** [comment]
Closed in favour of the follow up #1460
