### ISSUE TITLE
[BUG] NodeJS v16 used for frontend is EOL in September 2023

### ISSUE THREAD

**Issue by eternaltyro** [hotosm/tasking-manager#5767]
Tasking Manager frontend runs on NodeJS v16.x which is set to be EOL on 11 September 2023. We need to reprioritise our tasks to focus on making the frontend compatible with v18 - the current LTS version of NodeJS. This will give us one year before we need to upgrade again.

https://endoflife.date/nodejs

**Comment by ramyaragupathy** [comment]
Per discussion w/ @HelNershingThapa this will be addressed through https://github.com/hotosm/tasking-manager/pull/5721

**Comment by ramyaragupathy** [comment]
with https://github.com/hotosm/tasking-manager/pull/5721 - moved to node 18 cc @varun2948 @royallsilwallz @manjitapandey
