### ISSUE TITLE
switch to leaflet or mapbox-gl-js

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/tasking-manager#577]
All respect to the history of OpenLayers -- but Leaflet or mapbox-gl-js is a better choice in 2017 for the type of application we're building. OpenLayers has more comprehensive features -- like OGC standards support, projections -- but that comes at the cost of complexity and maintainability. Leaflet is simpler, cleaner, and smaller. mapbox-gl-js is also open source, and being very actively developed.

**Comment by hunt3ri** [comment]
Fairly major surgery to extract OpenLayers at this stage.  Shame no-one raised this at the start of the project, when we agreed architecture.  OpenLayers was stated as the map framework back in January.

One short-term quick win would be to upgrade to the latest version of OpenLayers, we're currently running v4.0,1 and latest is v4.3.1.  So there may be some perf improvements and bugfixes that would be a win for users.

Thanks

**Comment by IknowJoseph** [comment]
@hunt3ri Is upgrading OpenLayers a simple procedure? I've been looking to define my own OpenLayers location so that I could use a local copy, or my own CDN, or SRI hashing, for example, but didn't find this obvious.

**Comment by hunt3ri** [comment]
@IknowJoseph to perform the upgrade it should be just a matter of tweaking the version number in the package.json here

https://github.com/hotosm/tasking-manager/blob/develop/client/package.json

However, we'd want to conduct some local testing to ensure there was no regressions etc

**Comment by mikelmaron** [comment]
> Shame no-one raised this at the start of the project, when we agreed architecture. 

Indeed, I had no idea this was agreed.

Anyway, we can look at this as a top priority after launch.

**Comment by dalekunce** [comment]
Apologies if this was discussed and decided towards the beginning of the project. I do think that leaflet backed by GL-JS is the way forward. Realizing that we are too close to launch to make this change can we still spec out what the switch would entail. What is the biggest hurdle to switching over to GL-JS? I assume the map is still going to make similar type queries to the API for data. Or are you saying the things are hardwired in the API for openlayers. This doesn't look like it from the current API docs. In this case it doesn't matter what the requesting piece is as long as the map can support it.

**Comment by xamanu** [comment]
The inclusion of vector tiles in the TM is becoming more and more interesting as it is a prerequisite to include preprocessed information, such as layers coming from [OSM Analytics](https://osm-analytics.org/), which could be very useful at the moment of project creation.

**Comment by willemarcel** [comment]
With the TM redesign, we have a good opportunity to change the map framework, so it's time to make a decision

**Mapbox-GL-JS**
* It will allow us to use vector tiles layers
* We can yet load geojson data as we currently do on the tasks visualization maps
* We will need a new base layer, as the current Humanitarian OSM tile layer is not available as vector tiles

**Leaflet**
* There is a plugin to support vector tiles, but it doesn't provide a good user experience when loading layers with large amounts of data
* Allow us to load current geojson and TMS layers

**Comment by mikelmaron** [comment]
@willemarcel raster tile layers are supported by mapbox-gl-js -- so it's not a dependency to switch.

**Comment by xamanu** [comment]
There was a question on the chat:

> Are you planning to use https://github.com/uber/react-map-gl or the vanilla library?

(ping @zlavergne and @willemarcel)

**Comment by thadk** [comment]
Hi @mikelmaron – if you have any maintained humanitarian map style suggestions for us to use or start from, welcome! I don't know if we even have a team Mapbox account yet. Excited to be working on this.

**Comment by thadk** [comment]
I think we got it sorted actually.
