### ISSUE TITLE
[BUG] Dockerfiles use outdated container images

### ISSUE THREAD

**Issue by eternaltyro** [hotosm/tasking-manager#5788]
Comments from @spwoodcock :

> Currently I use quay.io/hotosm/base-python-image to track original Dockerfile.
> It was last updated 2 years ago & has critical vulnerabilities.
> 
> Do you know exactly what goes into this image build & if it's still maintained?
> 
> I would suggest we use an official Python stock image. 3.10-alpine3.17 if we want to stick to Alpine.
> 

> If I may, I will update the Dockerfile a bit to be closer to the one for FMTM https://github.com/hotosm/fmtm/blob/main/src/backend/Dockerfile

**Comment by spwoodcock** [comment]
This was solved by #5184, but as mentioned in the thread, we may want to refactor to use a `python-bullseye-slim` image.

Alpine based images aren't optimal for Python https://pythonspeed.com/articles/alpine-docker-python/
