### ISSUE TITLE
[BUG] The Maxar imagery in TM version of ID Editor is outdated 

### ISSUE THREAD

**Issue by Patrik-Br** [hotosm/tasking-manager#5792]
**Describe the bug**
As [anthaas mentioned on Slack](https://hotosm.slack.com/archives/C35UWSB6Z/p1684173924401789), the HOT Tasking Manager's version of ID Editor is showing older version of Maxar Imagery.

**To Reproduce**
1. Lock a task for mapping, select Maxar Imagery
2. Compare the Maxar Imagery of the same area in JOSM or OSM version of ID Editor

**Expected behavior**
Having the most current available version of the Maxar Imagery in Tasking Manager's version of ID Editor.

**Screenshots**
Here is the imagery compared between HOT TM ID editor and JOSM
![TM ID](https://github.com/hotosm/tasking-manager/assets/83399473/6e5b56fd-6ad3-4e40-88c1-1a14705c4078)

Comparison of OSM ID editor and JOSM
![OSM ID](https://github.com/hotosm/tasking-manager/assets/83399473/f5f76264-ddee-4387-87a1-0c7e67c64d69)

Comparison of HOT TM ID editor and OSM ID editor
![TM vs OSM](https://github.com/hotosm/tasking-manager/assets/83399473/79031c37-a689-41e3-bd0c-dd9cacee9e8a)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Vivaldi
 - Version: v4.5.4-hotfix2

**Additional context**
This issue will probably be fixed with updating the version of ID Editor. Issue #5780

**Comment by emi420** [comment]
Update: This is not related to the iD Editor version, it's an issue with the connectID string that was provided by Maxar, they're working on this issue.
