### ISSUE TITLE
Mapping - OSM editing layer says "For Validation"

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#580]
When I check out a task square for mapping in JOSM, it creates just the OSM data layer, which is perfect, but it is still named OSM Data Layer for Validation.

Should be OSM Data Layer for Mapping :)

![2017-06-16_16h40_14](https://user-images.githubusercontent.com/265831/27231414-d5092c8e-52b2-11e7-8d35-08fd55449ac8.png)

**Comment by feenster** [comment]
@bgirardot Could we make the name generic?  "OSM Data Layer"

**Comment by bgirardot** [comment]
yes
