### ISSUE TITLE
Broken Instagram link on the footer

### ISSUE THREAD

**Issue by HelNershingThapa** [hotosm/tasking-manager#5850]
The Instagram link on the footer of our website appears to be broken. Clicking on the link does not redirect users to the Instagram profile as intended.               
              
              Just noticed the Instagram link of the main instance is also broken.

_Originally posted by @HelNershingThapa in https://github.com/hotosm/tasking-manager/pull/5849#discussion_r1210089850_

**Comment by lalitkumawat1m** [comment]
hey @HelNershingThapa, I am willing to work on this issue, please assign me this issue.

**Comment by HelNershingThapa** [comment]
hi @lalitkumawat1m  thank you for showing your willingness; I appreciate your initiative and interest in contributing. I reached out to some individuals who use Instagram, and they confirmed that the link is broken unless logged in. The Instagram profile is only visible if browsing from a logged-in account. Otherwise, an exception is thrown, and the link appears broken.

I apologize for the confusion caused and for not closing the issue earlier. Thank you again for your offer to help.
