### ISSUE TITLE
Validation - JOSM no longer zooms to task polygon areas

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#587]
JOSM used to zoom to the polygon areas we load for validation. Looks like it does not do that anymore when they added a feature to option not zoom to downloaded data.

We need to send a zoom and bbox command.

**Comment by feenster** [comment]
Addressed by #596
 
@bgirardot I have added a step to use josm zoom remote command when there is more than one task square.  However in testing JOSM zooms sometimes but not others and I have not been able to understand this behaviour.

The zoom command is issued by TM3 correctly, but for some reason, although JOSM responds with a success message, JOSM does not actually zoom.

It works for this project (validate the 2 tasks by daisygrubber):
http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/project/3997

But not this (validate the 5 tasks by bgirardot):
http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/project/2763

For anyone wanting to investigate this, this is the code where the JOSM commands are sent.
https://github.com/hotosm/tasking-manager/blob/develop/client/app/project/project.controller.js#L1079

**Comment by bgirardot** [comment]
This works for me, both of your examples and my own testing. Thank you Ian.
