### ISSUE TITLE
Add confirmation dialog while deleting project chat.

### ISSUE THREAD

**Issue by Aadesh-Baral** [hotosm/tasking-manager#5880]
This feature was requested by @russdeffner on tasking-manager slack channel. 
russell.deffner

> Also, we may want to add a confirmation - single click delete is a bit dangerous as I could see myself accidently clicking the icon.

More info: [here](https://hotosm.slack.com/archives/C319P09PB/p1685938911622229?thread_ts=1685711797.770239&cid=C319P09PB)

We can implement similar confirmation dialog box to that of manage section.
![delete_confirmation](https://github.com/hotosm/tasking-manager/assets/67958673/71b13d6b-3e72-4ba4-b5aa-cb5557aa975f)

**Comment by mtalhabaig3** [comment]
@Aadesh-Baral can i try?

**Comment by Aadesh-Baral** [comment]
Yeah sure go ahead. @mtalhabaig3

**Comment by mtalhabaig3** [comment]
Alright!
