### ISSUE TITLE
[BUG] More filters menu height should extend to the bottom of the page or container should not overflow

### ISSUE THREAD

**Issue by HelNershingThapa** [hotosm/tasking-manager#5884]
**Describe the bug**
The current implementation of the more filters menu in our web application is causing visual inconsistencies and usability issues. The menu's height does not extend to the bottom of the page, resulting in an awkward appearance and an overall poor user experience.

**To Reproduce**
1. Navigate to the Explore Projects page with the More Filters functionality.
2. Expand the filters menu.
3. Observe that the menu's height does not extend to the bottom of the page or that the container overflows, causing scrolling on the main page.

**Expected behavior**
The height of the filters menu should be adjusted to fill the entire vertical space from the top of the page to the bottom. Alternatively, we can modify the container to prevent overflowing the page, enabling scrolling within the filters menu while keeping the rest of the page static.

**Screenshots**
![image](https://github.com/hotosm/tasking-manager/assets/51614993/d9def7f6-d76b-4137-a07f-1037033db499)
![screencapture-tasks-stage-hotosm-org-explore-filters-2023-06-06-13_52_51](https://github.com/hotosm/tasking-manager/assets/51614993/dd4dbab5-2d4f-4d11-9b59-0c5ac75f9b5e)

**Additional context**
This issue was brought up by @kshitijrajsharma on our [Slack channe](https://hotosm.slack.com/archives/C319P09PB)l

**Comment by mtalhabaig3** [comment]
@HelNershingThapa can I go ahead with this?

**Comment by HelNershingThapa** [comment]
@mtalhabaig3 Yeah, sure, you can. Feel free to ask if you need anything.

**Comment by mtalhabaig3** [comment]
Alright!

**Comment by HelNershingThapa** [comment]
@mtalhabaig3 It has been a while. If there have been any updates on the development, please let me know.

**Comment by mtalhabaig3** [comment]
@HelNershingThapa I started working on it but got busy with some things, Sorry about that. I am resuming the work on it and will let you know with the updates! 😊
