### ISSUE TITLE
Create container image to fetch from AWS S3 and restore to PostgreSQL server

### ISSUE THREAD

**Issue by eternaltyro** [hotosm/tasking-manager#5887]

**Comment by AfiMaameDufie** [comment]
Trying to resolve this now when trying to build container to connect to postgres server
` 9 |     RUN apt-get update && apt-get install -y postgresql-client
  10 |
  11 | >>> RUN psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -W $POSTGRES_DB -c "SELECT * FROM users;"
  12 |
  13 |
--------------------
ERROR: failed to solve: process "/bin/sh -c psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -W $POSTGRES_DB -c \"SELECT * FROM users;\"" did not complete successfully: exit code: 2`

Same line works from my CMD:

`$ psql -h localhost -p 5432 -U user -W orange -c "SELECT * FROM users;"`
Password:
 user_id |      email      |           first_name
---------+-----------------+--------------------------------
       1 | rick@gmail.com  | Rick
       2 | morty@gmail.com | Morty
(2 rows)

@eternaltyro

**Comment by eternaltyro** [comment]
@AfiMaameDufie Can you please add more info / context for how you ran the container, the contents of Dockerfile, etc.?

**Comment by AfiMaameDufie** [comment]
At the moment, I am restoring the db_dump file using 

`CMD ["bash", "-c", "psql -U $PGUSER -h $PGHOST -p $PGPORT -d $PGDATABASE -f /tmp/db_dump.sql"]`

This is currently working

**Comment by ramyaragupathy** [comment]
not relevant anymore
