### ISSUE TITLE
Two minutes tutorials inside Learn section should be updated 

### ISSUE THREAD

**Issue by fredychandra** [hotosm/tasking-manager#589]
Hi @bgirardot @TylerRadford

The video inside Learn Section on New Tasking Manager should be updated. It is still using old tasking manager page as a reference (she the pic below). This should use the new TM page as well, so it will more sensible. I realize the video can be updated once the new TM is relased.
![tm_learn](https://user-images.githubusercontent.com/6345285/27369972-86991da4-5684-11e7-9c0d-20e75b1784cc.JPG)

**Comment by ethan-nelson** [comment]
@bgirardot do we want to drop in your ''new in TM3'' videos? Or alternatively @aawiseman do you have updated videos for TM3?

**Comment by ethan-nelson** [comment]
This has been fixed in #1070 and others
