### ISSUE TITLE
[BUG] Hidden Menus due to Overlapping Horizontal Scrollbar on Project Detail Page

### ISSUE THREAD

**Issue by Ichchhie** [hotosm/tasking-manager#5893]
**Describe the bug**
On the project detail page, a convenient shortcut menu is provided at the bottom. However, an issue arises when the number of menu items exceeds the available space, prompting the appearance of a right arrow button to access additional menus. Unfortunately, clicking this arrow button triggers the appearance of a horizontal scrollbar, which covers the menus that should be visible.

**To Reproduce**
1. Navigate to the project detail page.
2. Scroll down to the bottom of the page where the shortcut menus are located.
3. Observe that the available space may be insufficient to display all menu items.
4. Notice the appearance of a right arrow button to access hidden menus.
5. Click on the right arrow button.

**Expected behavior**
Upon clicking the right arrow button, the menus should not be hidden by the scrollbar.

**Screenshots**
![ezgif com-video-to-gif(3)](https://github.com/hotosm/tasking-manager/assets/33247422/e75ac0a4-c479-4798-bf57-b3f24fa8a1e0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox

**Comment by martinyis** [comment]
If this issue is not done yet, I would like to work on that. Just assign me if possible!
