### ISSUE TITLE
New windows dialog to reaffirmed the completely task

### ISSUE THREAD

**Issue by samnawi** [hotosm/tasking-manager#590]
In the new tasking manager (http://tasks-demo.hotosm.org/), Should we need a new Windows dialog (after the user click "Mark as Completely Mapped") to affirm that task is really done? I think it important to prevent the new mapper or who still not familiar with the tasking manager tool, to click this button carelessly or some user accidentally click this button.
![tasking manager](https://user-images.githubusercontent.com/8871958/27369210-2534cdb8-5681-11e7-9b9a-6f614d5f7ac2.gif)

cc : @bgirardot @TylerRadford @fredychandra

**Comment by ethan-nelson** [comment]
There have been some ideas about this mentioned in the Tech WG meetings lately that may relate to this. We could add features for only specific mapper levels, so mappers on the beginner level may be appropriate to show this to as opposed to advanced mappers. That way, new users do not accidentally mark it while at the same time we do not disrupt the flow of advanced mappers.

**Comment by willemarcel** [comment]
It doesn't apply to TM4.
