### ISSUE TITLE
Add text to lead users share their project through social media

### ISSUE THREAD

**Issue by fredychandra** [hotosm/tasking-manager#591]
HI @bgirardot @TylerRadford

I have seen project sharing on media social platform exist, It is working. However, I think some text needs to be added to lead the contributors to realize and to understand how they can share their project through the media social button. E.g: _Share this / Share to your networks... etc.

See image below on the yellow mark. Last, I think the button can be put at the top next to HOT image (in the red circle area).
![share tm](https://user-images.githubusercontent.com/6345285/27370036-d4e03696-5684-11e7-9fdc-868c9090da89.JPG)

**Comment by bgirardot** [comment]
Hi Fredy, we moved this up higher and gave it a label "Share". Hopefully that makes it more clear.
