### ISSUE TITLE
[BUG] Pointer to projects page from organisation page is not working on some organisations

### ISSUE THREAD

**Issue by Patrik-Br** [hotosm/tasking-manager#5923]
**Describe the bug**
When I click on the "View all" button under projects section on the [organisation page of Médecins Sans Frontières (MSF) ](https://tasks.hotosm.org/organisations/medecins-sans-frontieres-msf) it sends me to Explore Projects page but the URL "https://tasks.hotosm.org/explore/?organisation=M%C3%A9decins%20Sans%20Fronti%C3%A8res%20(MSF)"  is uncorrect because it doesn't show me any available projects. When I use the filter and filter by the organisation it works correctly.

I tried to find a pattern but wasn't sucesfull. I have found that there is the same issue for organisation [Spatial Ecology & Analysis Lab (SEAL)](https://tasks.hotosm.org/organisations/spatial-ecology-analysis-lab-seal) but other organisations with ( ) in name, like [Enugu State Water Corporation (ENSWC)](https://tasks.hotosm.org/organisations/enugu-state-water-corporation-enswc) for example works as intended. 

**To Reproduce**
1. Go to https://tasks.hotosm.org/organisations/medecins-sans-frontieres-msf
2. Click on "View all" under projects section
3. See that it is not showing any available projects

**Expected behavior**
See list of available projects, same as when I use the filter.

**Screenshots**

![BUG-organisations-to-projects](https://github.com/hotosm/tasking-manager/assets/83399473/c04881d3-0057-4c90-ab51-3700bf756c68)

![image](https://github.com/hotosm/tasking-manager/assets/83399473/39ab2a8f-1e18-409b-8ffb-8795a7297558)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Vivaldi, Mozilla Firefox
 - Version: TM v4.6.0

**Comment by HelNershingThapa** [comment]
Thank you for reporting this issue. There appears to be an encoding problem with the organization name when navigating to the Explore Projects page. The URL for Médecins Sans Frontières (MSF) is not correctly encoded, resulting in the page not displaying any available projects.
