### ISSUE TITLE
[BUG] Broken website link of HOT

### ISSUE THREAD

**Issue by Ichchhie** [hotosm/tasking-manager#5925]
**Describe the bug**
The website link provided on the landing page appears to be broken.

**To Reproduce**
1. Go to 'https://tasks.hotosm.org/'
2. Click on '[hotosm.org](http://hotosm.org/)' link in top right

**Screenshots**
![ezgif com-video-to-gif(4)](https://github.com/hotosm/tasking-manager/assets/33247422/96e8a8bf-40d3-476c-acd2-f79c3a9972f0)

**Comment by HelNershingThapa** [comment]
The code snippet uses the `ORG_URL` environment variable to dynamically generate the href attribute with the `http://` prefix being static.

https://github.com/hotosm/tasking-manager/blob/377fce9eaa25de81dfa3841cd8eed1b8650eb511/frontend/src/components/header/index.js#L103

By explicitly specifying the HTTPS protocol, we can ensure that the link always directs to the secure version of the website.

The hotosm.org website might have stopped redirecting from HTTP to HTTPS, causing the link to break. Previously, this redirection worked fine for us. 

If you try accessing hotosm.org directly by typing it into the address bar, you may encounter a "This site can't be reached" error. This further suggests that the website no longer supports HTTP connections and requires HTTPS.

**Comment by dakotabenjamin** [comment]
we are working on the redirect from the DNS side but you can also change it to "www.hotosm.org" and it will work.
