### ISSUE TITLE
[BUG] Interest/category with empty name can be created

### ISSUE THREAD

**Issue by Aadesh-Baral** [hotosm/tasking-manager#5946]
By using the API, it is possible to create an interest or category without giving it a name, although doing so would break the manage categories page on front end.

**Expected behavior**
Creating a interest/category with empty name should not be possible. And also on the manage categories page this scenario should be handled.

**Comment by lalitkumawat1m** [comment]
hey @ramyaragupathy , I am willing to work on this issue, please assign me this issue.

**Comment by Aadesh-Baral** [comment]
@lalitkumawat1m Go ahead

**Comment by ramyaragupathy** [comment]
Since this is a high priority issue, @Aadesh-Baral will be working on it this week. @lalitkumawat1m - please watch out for other good first issues. Thanks for your interest 🙏
