### ISSUE TITLE
Add Before Start Mapping Guidance at Learn Section

### ISSUE THREAD

**Issue by fredychandra** [hotosm/tasking-manager#597]
Hi @bgirardot @TylerRadford 

I propose to add  Before Start Mapping Guidance as sub-section inside Learn section. I think it should consist of: 
- How to get the required software, such as JOSM, JAVA, etc
- Provide the download link of the software, so users can directly go to the page and download what they need. e.g. https://josm.openstreetmap.de/wiki/Download
- ... etc, that important to lead users ready before starting to learn OSM mapping. 

I find it will be useful for the users who are the first time with OSM mapping project and have no any OSM software to use. 
Please see the pic on the yellow mark. There might be suitable to put the Guidance.

![tm_learn_befor start](https://user-images.githubusercontent.com/6345285/27412670-55bd7ddc-5720-11e7-96a3-1223305dc6bd.JPG)

**Comment by xamanu** [comment]
We've redone the whole learn section #1637
