### ISSUE TITLE
Grid creation trim by default

### ISSUE THREAD

**Issue by pgiraud** [hotosm/tasking-manager#599]
Currently in TM3, when a project manager creates a project and decides to use the "gridded" mode, the grid squares are created so that the bounding box of the polygon(s) is filled. In some cases, this may mean a lot of tasks outside the area(s) of interest. The only way to be sure that the tasks really fit inside the area of interest to use the trim feature then.

In my opinion in most cases (if not all) the project managers will not want to keep squares outside the area of interest and they will use the "trim". Is there a reason why the grid is not trimmed by default? Performance?

Also, I wouldn't set the "clip tasks" checkbox checked by default.

**Comment by pgiraud** [comment]
I'd like to add that in some cases you're not allowed to get smaller tasks because the maximum number is reached. But this is before the "trim" effect! This may not happen if the grid fits the polygons at first.
This usually happens when you have several polygons.
http://bl.ocks.org/d/f5b7f0fb61f95192c829dff2dbbdc119

**Comment by bgirardot** [comment]
Hi @pgiraud I think this question might be answered in #579 

Not really a solution, but what is happening.

There are workarounds at the moment: You can still use the splitting tasks squares by polygon to get smaller grids over your actual AoI

and we can increase the 1 meg limit on sending to the server so we can up the number of task squares.

**Comment by feenster** [comment]
https://github.com/hotosm/tasking-manager/issues/594#issuecomment-310401307

**Comment by bgirardot** [comment]
@pgiraud I am going to close this as I think #579 covers it and has more details.
