### ISSUE TITLE
[BUG] Date pickers incorrectly aligned on Org Stats page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#5993]
**Describe the bug**
The date pickers are not correctly aligned on Organizations Stats page

**To Reproduce**
1. Go to an organization stats page
2. See that the datepickers are wrongly aligned

**Expected behavior**
Be in the same line as the calendar icon.

**Screenshots**
![image](https://github.com/hotosm/tasking-manager/assets/666291/1aebbbd8-f854-46b8-86b0-1ddc71993502)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 115.0.2 (64-bit)

**Additional context**
The error can be seen in all screen sizes.

**Comment by HelNershingThapa** [comment]
Thank you for reporting. I'm happy to let you know that this issue has been taken care of with https://github.com/hotosm/tasking-manager/pull/5886 and is also available on the live instance.
