### ISSUE TITLE
With boundary layer locked, users can no longer add task boundaries to the JOSM todo plugin

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#5996]
related: https://github.com/hotosm/tasking-manager/pull/5837/

Some validators reported a break in their workflows for validating multiple tasks on JOSM. They use the "todo" plugin to add task boundaries and iterate through them as a visual aid for validation. 

With the PR ref'd above, the boundary layer is now locked, preventing it from being added as a todo item. 

Can we drop https://github.com/hotosm/tasking-manager/pull/5837/files#diff-36df05d0c18d02c7b3a941100028ab3a1cdcf3c726e954f6443c3180f342a5f3R141 while keeping the `upload_policy` and maintain intended functionality? Should we maintain the locked layer but make it and Expert Mode toggle? 

Or does this user behavior fall outside the scope of TM and should the users affected pursue changes to JOSM and the todo plugin? I don't really see why data from a locked layer couldn't be added to the todo list.

**Comment by dakotabenjamin** [comment]
User Anthaas has opened a ticket in JOSM todo: https://josm.openstreetmap.de/ticket/23072

**Comment by tsmock** [comment]
I've modified the TODO plugin to allow TODO items from more sources. I _think_ that fixes this issue.

**Comment by dakotabenjamin** [comment]
This has been fixed since https://github.com/JOSM/todo/releases/tag/v128 as confirmed by the reporting user.

**Comment by dakotabenjamin** [comment]
Thanks @tsmock !
