### ISSUE TITLE
User Interface: a few comments

### ISSUE THREAD

**Issue by Charlotte-Morgan** [hotosm/tasking-manager#600]
Hi @bgirardot and @TylerRadford - thanks for asking us to review the TM3
Congratulations to the team on TM 3 so far. Its great to see it taking shape and incorporating many features users have requested.  Here are few observations  on the user interface.

0. While there are heaps of new features and functionality the interface is not as pleasing. It looks a bit clumsy with so many different fonts

1. It all looks a bit pale and bland, especially the list view. When I compare to TM2 there is less colour and I find the text much harder to read even though it is larger (maybe there is not enough space between the lines). The headings appear to be smaller than the column contents
eg TM2 
![image](https://user-images.githubusercontent.com/5743135/27463563-aa9d8572-57f2-11e7-97ab-e6c66f6e7cc6.png)
is more readable than 
![image](https://user-images.githubusercontent.com/5743135/27463597-e2dfd32c-57f2-11e7-824f-fac4871ad818.png)

Grid view is easier to read and I really like map view. Do you have some way to stop the world wrapping?

In a task window -the interface is not as pleasing as TM2. It looks a bit clumsy with so many different fonts and styles. I prefer simple and consistent look and feel so that users are not distracted when trying to find information.
![image](https://user-images.githubusercontent.com/5743135/27464159-0c40513a-57f6-11e7-9f3a-9c71e403bbbd.png)

2. Search function.
Hmm - In my first search attempt I was not sure  if it was thinking, failed to find something or did nothing. Maybe it all happened so fast
In the advanced search the drop down for 'types of mapping' obscures the result; again its not really easy to see if the search is responding. It runs on the 'search' click but also on a return?
![image](https://user-images.githubusercontent.com/5743135/27463850-58482032-57f4-11e7-8dcf-1254ed4073ef.png)

3. I think it would look a little more professional if organisations and campaigns used some capitalisation. Maybe this could be managed from an admin generated pick list rather than from free text - this way you will hopefully only get each organisation once.

4. About page.  It would be nice if this acknowledged the history of the project with some info about versions and how the project has evolved / grown.

5. While TM1 and TM2 were supported by AIFDR; TM3 is supported by The Australian Government through DMInnovation as the implementing partner. This needs to be updated on TM3 but do you have a way to recognise legacy partners?

I encourage you to get an expert on presentation to review the look and feel.
Thank you again for the opportunity to comment and good luck with the polishing.

**Comment by bgirardot** [comment]
@Charlotte-Morgan thank you very much for the comments and feedback!

I have divided them up into individual issues here in GitHub so they are easier to track and added your name to them. One of them was already an issue (capitalization of tags) so I added a comment to that issue.

I am only closing this one because each one is now all covered by a specific issue.

Thank you again for taking the time to review and give us this feedback!
