### ISSUE TITLE
Project Creation - Metadata fields mandatory

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#602]
Based on stakeholder feedback, all of the fields in the meta data panel, with the exception of campaign, should be mandatory. We need those fields to be used so we get the maximum benefit from them.

**Comment by smit1678** [comment]
Coming back to this ticket to further this conversation. @bgirardot @ethan-nelson @dakotabenjamin @willemarcel @ramyaragupathy and anyone else watching any reason we should not make all of the fields mandatory? 

I think for the image field, related to #1122, we should provide a dropdown of the primary image later to be used to preconfigure the iD link. 

Is there a case for not making them all mandatory?
