### ISSUE TITLE
Improve UI Text - font mix, sizes, coloration, spacing

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#605]
It all looks a bit pale and bland, especially the list view. When I compare to TM2 there is less colour and I find the text much harder to read even though it is larger (maybe there is not enough space between the lines). The headings appear to be smaller than the column contents
eg TM2
 - Charlotte

**Comment by xamanu** [comment]
This is to be considered in the ongoing redesign with @hotosm/major.

**Comment by xamanu** [comment]
The new redesign for TM4 has addressed this.
