### ISSUE TITLE
Improve the About page to be more informative

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#606]
About page. It would be nice if this acknowledged the history of the project with some info about versions and how the project has evolved / grown.

While TM1 and TM2 were supported by AIFDR; TM3 is supported by The Australian Government through DMInnovation as the implementing partner. This needs to be updated on TM3 but do you have a way to recognise legacy partners?

-- Charlotte

**Comment by xamanu** [comment]
The ongoing [design work](https://github.com/hotosm/projects/issues/17) gives a vision for the about page focused on the users. Closing here.
