### ISSUE TITLE
problem with project statistics

### ISSUE THREAD

**Issue by JuanMeloColombia** [hotosm/tasking-manager#6064]
since a few weeks ago, there have been problems in the display of project statistics since it does not show the number of buildings created and kilometers of roads mapped.

![image](https://github.com/hotosm/tasking-manager/assets/118753175/11dd0a08-0187-48f2-bf65-93f6b6f79b3e)

**Comment by ramyaragupathy** [comment]
@JuanMeloColombia - thanks for flagging this issue. Leaderboard service, which has been providing us this data, is not functional any more starting mid-September. We are [aware](https://github.com/hotosm/tasking-manager/issues/5999) of it, and we are transitioning the data source to [ohsome now stats](https://heigit.org/introducing-ohsomenow-stats-real-time-monitoring-for-openstreetmap-contributions/). Your OSM and TM contributions are intact and this should be available on Tasking Manager from mid-October. Thanks for your patience while we get this done!

cc @konishon @kaditya97 @HelNershingThapa
