### ISSUE TITLE
Review for color blindness compatibility

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#608]
Review for color blindness compatibility

**Comment by althio** [comment]
for reference: https://github.com/hotosm/osm-tasking-manager2/issues/500#issuecomment-67775776

**Comment by bgirardot** [comment]
We received a notice from a user that the color coding on the map grid is hard for red/green folks to see. He suggested a roll over task status would help with the issue if we can't also find another way to address it.

**Comment by xamanu** [comment]
This is probably important input for the ongoing design work with @hotosm/major.

**Comment by xamanu** [comment]
Closing this in favour of the follow up issue #1257. I brought the initial request into the follow up conversation.
