### ISSUE TITLE
Frontend compile error

### ISSUE THREAD

**Issue by dongpo** [hotosm/tasking-manager#6091]
Follow the [Development setup](https://github.com/hotosm/tasking-manager/blob/develop/docs/developers/development-setup.md). Try to build the frontend of TM. As doing "yarn start" and "yarn build", the error message "Cannot read properties of undefined (reading 'indexOf')" is shown. 

**Screenshots**
<img width="888" alt="Screenshot 2023-10-23 at 6 08 32 PM" src="https://github.com/hotosm/tasking-manager/assets/1594678/d2979f53-4e69-4c5f-82f0-42a9be0a0771">

**Comment by ramyaragupathy** [comment]
@royallsilwallz - can you please help here?

@dongpo - for quicker resolution, you can also flag this is in HOTOSM slack - specifically in #tasking-manager channel.

**Comment by royallsilwallz** [comment]
Hey @dongpo, mine's working fine.
Which node version are you using? 
Try it with node v16. It should work fine.

**Comment by dongpo** [comment]
Thank for the replies from @ramyaragupathy and @royallsilwallz. It's worked since the node was switched to v16.
