### ISSUE TITLE
Contribute - Links in views should open in new window

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#610]
For example, when viewing history, clicking on a user’s profile opens in the same window.

Appears on Map tab, Validate tab, Chat tab, Activity and stats page

This leads to people being taken away from the task they are working on or project they are looking to contribute to.

**Comment by xamanu** [comment]
This is to be considered in the ongoing redesign with @hotosm/major https://github.com/hotosm/projects/issues/24

**Comment by xamanu** [comment]
This has been implemented in a new flow and with modals that popup and can be closed in order to not loose the page/task people were looking at.
