### ISSUE TITLE
Contribute - "Map" tab not clear means "Mapping" 

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#611]
Not clear this is a verb, maybe needs to be "Mapping" or "Map a Task" or something.

**Comment by ethan-nelson** [comment]
We unfortunately don't have a ton of space to work with, so we can't add too much text.I do like the gerunds for the two "do" tabs:

`Instructions` `Mapping` `Validating` `Questions and Comments` (perhaps we can trim that last one down too)

**Comment by xamanu** [comment]
This shall be included in the rethinking of the UI with @hotosm/major.

**Comment by xamanu** [comment]
Fixed with the improvements on the mapping flow in TM4.
