### ISSUE TITLE
[BUG] Incomplete contributors list in task comments

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#6115]
After the [new deployment](https://github.com/hotosm/tasking-manager/releases/tag/v4.6.2), there are issues reported about incomplete contributor list for tagging in task comments section.

_Another different issue I recognized recently: the wrong users seem to be listed when you put the "@" in the comment field in the tasking manager.
My most recent example is task 1109 of project https://tasks.hotosm.org/projects/15602  - the same was observed in task 1235 and 897 (here I indeed directed my comment to the wrong person...).
Back to task 1109: This task was marked as completely mapped by user Cameon (screenshot 1). While typing the @ sign users "Dlankler", "Miss Pooler", and "laurenko" are shown (see screenshot 2), but not e.g. user Cameon and PeterMN to whom I wanted to direct my thanks. It seems that the suggestions have nothing to do with the persons participating in the task ...
Did someone else recognize this behaviour in another project?_

![image](https://github.com/hotosm/tasking-manager/assets/12103383/a9ef083f-e994-4c0f-823a-faecb0ff6230)
![image](https://github.com/hotosm/tasking-manager/assets/12103383/96cc676e-65b5-48d3-8dc4-ab52a7ddcd12)

<img width="562" alt="image" src="https://github.com/hotosm/tasking-manager/assets/12103383/5ab079ec-a561-4e51-bdb4-8713f1bf585b">

cc @kaditya97 @royallsilwallz @konishon

**Comment by manjitapandey** [comment]
@ramyaragupathy, i am little confused about this part where kathyaus has stated " if you select multiple tasks, it doesn't bring up list of mappers for each tasks". How is it possible to select multiple tasks at the same time? Can you guide me through this part?
![](https://user-images.githubusercontent.com/12103383/278941313-5ab079ec-a561-4e51-bdb4-8713f1bf585b.png)
