### ISSUE TITLE
[BUG] Privacy Policy link is misdirected

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#6120]
**Describe the bug**
Our privacy policy is located at https://www.hotosm.org/privacy but on both the footer and the consent tracking banner it links to https://tasks.hotosm.org/hotosm.org/privacy. This is likely an issue with an envvar setting. Maybe related to the refactor?

**To Reproduce**
1. Go to tasks.hotosm.org
2. Click on "privacy policy" on the footer
3. See error

**Expected behavior**
Privacy policy should link to hotosm.org/privacy page

**Screenshots**
![image](https://github.com/hotosm/tasking-manager/assets/1847818/88e60c79-d128-43a0-9d9b-bd3d302555fc)

**Desktop (please complete the following information):**
 - Edge, Firefox

**Additional context**
Reported here: https://hotosm.atlassian.net/jira/servicedesk/projects/HTR/queues/custom/13/HTR-875

**Comment by royallsilwallz** [comment]
It is [this](https://github.com/hotosm/tasking-manager/blob/7d26e0cf3e6f2e0ed188336aa6f8d05d523c0bd1/example.env#L29C1-L29C57) env variable. 
CC - @dakotabenjamin @ramyaragupathy

**Comment by dakotabenjamin** [comment]
Possibly introduced by this fix I made: https://github.com/hotosm/tasking-manager/commit/74d130d42f755e99c7792c7847c57fdc6f5651d6

And then I forgot to update the envvar in the CI

**Comment by ramyaragupathy** [comment]
Both the footer and the consent tracking banner points to the privacy policy on HOT website.
