### ISSUE TITLE
Removing missingmaps link from user profile page

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#6128]
Since the Missing Maps Leaderboard page is down and we have[ switched our statistics source to ohsomeNow Stats](https://github.com/hotosm/tasking-manager/issues/5999), we should also remove the link to Missing Maps from user profile page.

<img width="1186" alt="image" src="https://github.com/hotosm/tasking-manager/assets/12103383/21fba8a0-e885-4842-a306-3a0dce0d8a06">

**Comment by balex654** [comment]
Hi @ramyaragupathy. I'm new to this repo (and new to making open source contributions) and I'd like to fix this issue. I have a local branch with changes that I'd like to push but I get a 403 error. Do I have to be given permission to push changes?
