### ISSUE TITLE
[BUG] While validating multiple tasks at once the autocomplete after @ in comment section always recommend user from first task

### ISSUE THREAD

**Issue by Patrik-Br** [hotosm/tasking-manager#6137]
**Describe the bug**
When I am validating multiple tasks at once and I am about to write a feedback message the autocomplete after @ always shows the users from the first task, doesn't matter for which task I am writing feedback it always shows the contributors from first task. 

**To Reproduce**
1. Lock multiple tasks for validation
2. Click on +Comment
3. Click on @ to tag a user and see the list of users
4. See that is recomends for autocomplete always the same list of the same users in every task comment window.

**Expected behavior**
Recommend the correct contributors in the specific task according to task history after I click on the @, just like it was a few weeks ago.

**Screenshots**
![autocomplete](https://github.com/hotosm/tasking-manager/assets/83399473/4026b88e-a8fb-4af5-a213-6c5e1f757336)
In the comment window for task number 4 it should recommend user 'timi and not bbb9.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Vivaldi
 - Version v4.6.2 hotfix

**Additional context**
I am kinda sure that it was reported before but I can't find the ticket so I created this one.

**Comment by manjitapandey** [comment]
This issue is part of issue #6115 and is on progress. Will be solved on next release.
