### ISSUE TITLE
Let users download OSM data generated for each project

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#6143]
Related to [Export Tool integration](https://github.com/hotosm/tasking-manager/issues/6094) - there should be a download option available for all signed-in users to access data exports for each project.

Per the sketch here, seeing this fit in the contribution section.

@manjitapandey @varun2948 to add the mock-ups for reference.

![image](https://github.com/hotosm/tasking-manager/assets/12103383/df8c8aa6-1ea8-49f4-a1c1-02986709e8db)

Download option swill be available on all projects(published and archived, draft need not have this option). During the initial launch we will have files generated for archived projects as well and it will be a one time task. Later, on a daily basis, we will have new exports available only for active projects that are in published status. Suppose export is not available for a project then a pop-up with the message that no data available for download should be indicated for the user.

**Comment by varun2948** [comment]
Finished working on the UI for downloading OSM data. We just need the actual S3 file URL to test the download and notify the user of its availability.
