### ISSUE TITLE
  Export tool integration: Setting up a lambda function to track active projects and schedule export jobs

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#6145]
Related to [Export Tool integration](https://github.com/hotosm/tasking-manager/issues/6094):
![image](https://github.com/hotosm/tasking-manager/assets/12103383/33ba73b9-d220-447e-ab70-ad5cac3ece80)

![image](https://github.com/hotosm/tasking-manager/assets/12103383/244f6d3e-4a76-4360-90cc-6bdf9b1b5fb8)

There will be a [new TM endpoint](https://github.com/hotosm/tasking-manager/issues/6144) to track active projects which will be used by a lambda function. Objective of this lambda function:
1. run everyday on 12 UTC cc @mahesh-naxa @eternaltyro 
2. hit the TM API to generate a list of published, active projects
3. using the list of active projects, send export jobs to [raw-data-api](https://github.com/hotosm/raw-data-api)

**Comment by ramyaragupathy** [comment]
For now, we have the TM related lambda functions existing in the same repo: https://github.com/hotosm/tasking-manager/tree/develop/scripts/aws/lambda. If required, we should consider moving this to separate repos.

cc @dakotabenjamin @eternaltyro @mahesh-naxa @kaditya97

**Comment by dakotabenjamin** [comment]
I say keep it in the repository. My major concern is cloud independence- we can default for now to using lambda but should also consider being able to run it as a tiny container/microservice should we need to.

**Comment by ramyaragupathy** [comment]
Complete
