### ISSUE TITLE
[BUG] Unable to submit tasks after validation

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#6154]
**Describe the bug**

Several [users are reporting](https://hotosm.slack.com/archives/C319P09PB/p1700940729985989) delay in validation submission action. It is a huge blocker to the validation workflow. After hitting the, submit button there is a delay in submission and finally there is an error message indicated to the user.

<img width="831" alt="image" src="https://github.com/hotosm/tasking-manager/assets/12103383/d1f7d91f-587b-4989-9fbd-cef6e1163e4d">

![image](https://github.com/hotosm/tasking-manager/assets/12103383/4f48824f-10f6-4a2f-8804-dad2719810be)

<img width="676" alt="image" src="https://github.com/hotosm/tasking-manager/assets/12103383/5c78b87b-fcf0-4629-ae49-b02b71696ab5">

<img width="828" alt="image" src="https://github.com/hotosm/tasking-manager/assets/12103383/5f2d3dae-5c46-42b5-8668-1b441feaa1c1">

![image](https://github.com/hotosm/tasking-manager/assets/12103383/b75b8209-494f-4b59-ad1f-a315a791572f)

![image](https://github.com/hotosm/tasking-manager/assets/12103383/4dd653f7-aaf0-4aef-953f-5ad54703cc59)

**Comment by manjitapandey** [comment]
I was able to reproduce the issue again today. 
The unlock after validation API fails showing 504 error and timeout.
![image](https://github.com/hotosm/tasking-manager/assets/97273021/e82d5d21-689b-43b0-847a-ff8a2efa6c0b)
