### ISSUE TITLE
Contribute - Map/Validate - Provide link to download gpx file for task

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#616]

**Comment by bgirardot** [comment]
This should be available for any task square and any editor as it is now in the TM2.

**Comment by ethan-nelson** [comment]
It looks like this is available from the API endpoint http://tasks.hotosm.org/api/v1/project/XX/tasks_as_gpx?tasks=YY&as_file=true.

But I believe it is the case that this endpoint should be available on the task window.
