### ISSUE TITLE
Contribute - Validate tab - contributor list too crowded, start buttons touch each other

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#619]
![2017-06-26_16h37_51](https://user-images.githubusercontent.com/265831/27544654-1aaa56a4-5a8e-11e7-89bf-7fcd6173ccc0.png)

**Comment by ethan-nelson** [comment]
Closing as this has been refined with the UI overhaul. Please reopen if it's still unacceptable! 

![validation](https://user-images.githubusercontent.com/8998918/32139090-f907118e-bc05-11e7-858a-03272f2a2cd0.PNG)
