### ISSUE TITLE
UI Update of live monitoring feature

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/tasking-manager#6200]
**Is your feature request related to a problem? Please describe.**
The existing UI has some usability constraints specially with the scrolls. 
Some buttons are attached which aren't so visually appealing.
![Screenshot 2024-01-11 at 11 51 36](https://github.com/hotosm/tasking-manager/assets/97273021/17d33b74-ad04-47f2-aa9a-e895efedba0a)

**Describe the solution you'd like**
@emi420's Idea: UI update as below.
![Screenshot 2024-01-11 at 11 53 54](https://github.com/hotosm/tasking-manager/assets/97273021/b63d4a98-2558-4bbc-846d-22bb9c23df4c)

**Additional context**
UI focusing more on Map and data list.

cc: @ramyaragupathy

**Comment by manjitapandey** [comment]
Related to #6151

**Comment by emi420** [comment]
This is done! view's UI has been updated.
