### ISSUE TITLE
Improve UX on live feature monitoring page 

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/tasking-manager#6219]
**Describe the solution you'd like**
We can improve UX by making the live feature monitoring page more similar to the edit screen, where there’s no footer, the map is fixed to the available screen space and the right sidebar is the only space where scroll is enabled.

**Additional context**
Something similar to id editor page.
![image](https://github.com/hotosm/tasking-manager/assets/97273021/ed220938-7c46-4bc4-8284-36c1d222426c)

- Related to #6151

**Comment by emi420** [comment]
Hey @royallsilwallz , it's improving! just a couple of fixes:

#### Tag filter and dropdown for selecting background has to be moved close to the top

It's using an absolute position, maybe something like `top: 100px` for the `.top` class will solve the issue. I'm open to other solutions also. Also, as you'll be working with the styling of this form, please check the alignment between the dropdown and the other elements and the value for the rounded corner of the "Search" button (to keep design consistent).

<img width="360" alt="Screenshot 2024-01-25 at 08 52 22" src="https://github.com/hotosm/tasking-manager/assets/1226194/7801444b-1df5-419f-a518-01544b83c4e8">

#### There's a scroll so the user can move the screen

An `overflow: hidden` could be used for disabling scroll on the container.

<img width="1078" alt="Screenshot 2024-01-25 at 08 55 43" src="https://github.com/hotosm/tasking-manager/assets/1226194/94be8ad7-d0ba-4505-ac29-a8e4dc4c26ee">


Also you have to take into a account the height of of the project's title and then the feature list at the bottom. Currently, the list's seems to be exceeding the available space. This is visible if you add a `border: 1px solid red` for testing:

<img width="385" alt="Screenshot 2024-01-25 at 09 03 57" src="https://github.com/hotosm/tasking-manager/assets/1226194/352957d9-f171-4417-aa2a-fc7c83251aae">

**Comment by royallsilwallz** [comment]
Yeah sure @emi420. I'll be working on these changes.

**Comment by royallsilwallz** [comment]
Hey @emi420, I've fixed the design changes and pushed the code. Can you review it and let me know ?

**Comment by emi420** [comment]
Hey @royallsilwallz , everything looks nice!
