### ISSUE TITLE
Project lists do not show number of people actively mapping

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#627]
The TM2 showed how many people were currently mapping or validating a project (how many people had a task square locked)

**Comment by russdeffner** [comment]
For project managers and mapathon organizers, this is valuable information. i.e. if I have a team employed, I'd like to be able to quickly see that the number of mappers is relatively equal to my team, i.e. they are all working the project assigned.  For mapathons it's also nice to show/tell 'hey, we have X number of mappers working on this right now' versus totals at the end.

**Comment by hunt3ri** [comment]
@pgiraud how did you calculate the counts last time??  I'm thinking the only practical way to do it is to track usage in the DB - an in-memory approach isn't really practical with the amounts of projects and need to decrement counter if user hasn't been seen for a while?

**Comment by pgiraud** [comment]
Actually, as far as I remember, the count of active users for a project was just the number of currently locked tasks. With the auto-unlock mechanism, inactive users eventually disapear as soon as tasks are unlocked.

That may not be easy to do in TM3 for several reasons including the project list request caching. Also the new data model (with only one table for both locks and states) may make things more difficult.

How difficult do you think it is to know how much tasks are locked?

**Comment by hunt3ri** [comment]
@pgiraud that's a genius solution 💯 It should be pretty easy to get the counts using that apporach.  The tasks table has a task_status column.  So 1 = LOCKED_FOR_MAPPING and 3 = LOCKED_FOR_VALIDATION

So the following SQL would get the project level activty

select count(1) from tasks where task_status in (1, 3) and project_id = n

and if we wanted app wide project activity on the homepage a little cached API that dropped the project_id eg

select count(1) from tasks where task_status in (1, 3)

Could see if I could pull something together over an evening

**Comment by hunt3ri** [comment]
@pgiraud @bgirardot can you remember if you could see the number of active mappers on the contribute page, or did you have to open the project to see them, or were they visible in both places?

**Comment by bgirardot** [comment]
Both places. Thank you for thinking about this item iain

**Comment by hunt3ri** [comment]
PR submitted, let me know what you think :)

**Comment by ethan-nelson** [comment]
My understanding is this was solved with #879. Please reopen if that is not the case.
