### ISSUE TITLE
Add pyinstrument for performance benchmarking

### ISSUE THREAD

**Issue by robsavoye** [hotosm/tasking-manager#6292]
To enable performance testing, support for pyinstrument should be added to the backend. This can be then run optionally via an additional parameter to the REST API call. This also needs  way to export the results outside of docker.

**Comment by spwoodcock** [comment]
This should only be available during local development & not in any of the public facing instances 👍

**Comment by spwoodcock** [comment]
But could go to the staging server temporarily if necessary for performance issue investigations

**Comment by robsavoye** [comment]
My plan was to have this in a "perf" branch, not develop or main.

**Comment by spwoodcock** [comment]
I won't be deployed anywhere in that case 👍
Just for local testing.

However, if you merge the branch then we want to make sure pyinstrument is not included in production by using Python dependency groups  and having a multistage dockerfile that uses different groups for each build target

**Comment by robsavoye** [comment]
I don't plan to make any code changes other than whatever it takes to get some performance statistics. It shouldn't effect the docker image at all, I used pdm to install the module manually.

**Comment by ramyaragupathy** [comment]
We need to have the pyinstrument integration in two places:
* one in Fast API migration and 
* also in the current codebase

so that we do the performance comparison between both the setups

cc @kaditya97 @robsavoye @spwoodcock

**Comment by kaditya97** [comment]
Here are the references what I prefer for setting up pyinstrument in flask and fastapi
- [https://pyinstrument.readthedocs.io/en/latest/guide.html#profile-a-web-request-in-flask](https://pyinstrument.readthedocs.io/en/latest/guide.html#profile-a-web-request-in-flask)
- [https://pyinstrument.readthedocs.io/en/latest/guide.html#profile-a-web-request-in-fastapi](https://pyinstrument.readthedocs.io/en/latest/guide.html#profile-a-web-request-in-fastapi)

**Comment by ramyaragupathy** [comment]
@kaditya97 - here is some previous work on profiling https://github.com/hotosm/tasking-manager/tree/develop/scripts/profiler
