### ISSUE TITLE
Activity and Stats page - activity list does not indicate which task the activity took place

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#630]
The list of activity on the project only says "Task locked,mapped,validated by .... " but it does not indicate which task.

It should indicate which task and provide a link to that task.

**Comment by belaeifert** [comment]
Hello! I would like to contribute with this issue. Which page can I see the bug?

**Comment by ethan-nelson** [comment]
An example is available here: https://tasks.hotosm.org/project/5543/dashboard

**Comment by xamanu** [comment]
This is to be considered in the ongoing redesign with @hotosm/major hotosm/projects#21

**Comment by xamanu** [comment]
This has been addressed in TM4. The last user is shown on the regular task list.
