### ISSUE TITLE
Viewing task instructions without HOT TM account 

### ISSUE THREAD

**Issue by Jorieke** [hotosm/tasking-manager#6302]
Hello, 

We are trying to comply with the OSMF Organised Editing guidelines. See here: https://osmfoundation.org/wiki/Organised_Editing_Guidelines#:~:text=Organised%20Editing%20Guidelines%201%20Preamble%20OpenStreetMap%20is%20powered,problematic%20edits%20Problematic%20edits%20may%20be%20reverted.%20
For reference as well the wiki page we are working on to comply: https://wiki.openstreetmap.org/wiki/M%C3%A9decins_Sans_Fronti%C3%A8res

In the guidelines it is suggests to add "training material or written instructions" onto the wiki page that we create for our activity. It would however be great to just be able to link through to the instructions that we give in our projects on the HOT Tasking Manager, and not to copy-paste those instructions on the wiki page. 
At the moment a user without account on the HOT TM is able to see the main page of a project, but not the page with instructions. Eg. https://tasks.hotosm.org/projects/15739
It would thus be great as well if a person without account could see the HOT TM with instructions as well. This will allow anyone who wants to control our activities to have access to the instructions given in the project.  

Thanks for your consideration! 
Jorieke

**Comment by ramyaragupathy** [comment]
@Jorieke - thanks for the suggestion. Will prioritise for the coming release

**Comment by ramyaragupathy** [comment]
We're getting this rolling @royallsilwallz @manjitapandey @emi420 

When a user accesses a project with/without login, there should a project specific instructions link available in the description section that takes the user to the instructions page. This means there should be a `instructions` specific url.

Similar to https://tasks.hotosm.org/projects/16950/tasks, create paths for:
*  instructions -> https://tasks.hotosm.org/projects/16950/instructions
*  contributions -> https://tasks.hotosm.org/projects/16950/contributions

If not logged in, tasks and contributions tabs don't appear and while clicking to map a task, user should be prompted to login. 
<img width="780" alt="image" src="https://github.com/user-attachments/assets/0d89d71c-1d4f-475a-a286-bcf72fb10062">

<img width="1423" alt="image" src="https://github.com/user-attachments/assets/f1b86689-0031-426a-81c8-ccd6197236dd">

**Comment by manjitapandey** [comment]
The map section on the task page is currently authenticated and can only be accessed when the user is logged in. As a result, we encounter an error when trying to integrate the map for non-logged-in users. We are considering using the same map from the project's page when the user is not logged in, and then loading the map of tasks API once they log in. @ramyaragupathy, what are your thoughts on this approach?

**Comment by ramyaragupathy** [comment]
Good catch, your suggestion sounds good to me
