### ISSUE TITLE
Activity and Stats page - hard to figure out how to return to the project

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#631]
Need to make the link back to the project more clear, probably at top and bottom of the page. multiple people have reported it is hard to figure out how to get back to the project.

**Comment by xamanu** [comment]
This is ongoing work with the current design imrprovements with @hotosm/major hotosm/projects#21

**Comment by xamanu** [comment]
This page is now parts of the tabs and this should not be an issue anymore. Closing here.
