### ISSUE TITLE
[BUG] Unable to validate a specific task, I am able to validate other tasks in the same project

### ISSUE THREAD

**Issue by Patrik-Br** [hotosm/tasking-manager#6320]
**Describe the bug**
I am unable to mark a specific task as validated  (https://tasks.hotosm.org/projects/15834/tasks/?search=1133), keeps getting the "An error occured while submitting your task." pop up error. I am able to validate other tasks in this project but not this one. anthaas noticed this behaviour on this task yesterday. Today I tested and I am having the same result. Neither me or him worked on this task before.

**To Reproduce**
1. Go to https://tasks.hotosm.org/projects/15834/tasks/?search=1133
2. Lock the task 1133 for validation
3. Submit task as validated
4. See the error

**Expected behavior**
Be able to validate the task since I can validate other tasks in the same project.

**Screenshots**
Here is a screen record of how it looks: https://sendspark.com/share/kx6dm2z4odqnwgaz
![image](https://github.com/hotosm/tasking-manager/assets/83399473/a7392e07-13f4-4826-91d4-d75ebec90842)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Vivaldi
 - Version TM v4.7.1

**Additional context**
As you can see in the video I tried to refresh my cache using Ctrl+Shift+R shortcut, didn't helped. In the history of the task I can see that the task was marked as more mapping needed in the past, so someone was able to invalidate it before, I haven't tried to invalidate it, just to see if that would work....

**Comment by martien-176** [comment]
Tested and have the same result.

I added a screenshot with Inspector report showing a 500 error.

- Windows 10
- browser Firefox

![TM-error500](https://github.com/hotosm/tasking-manager/assets/17877665/3c8bc39b-a752-4d3b-90b0-0cb49e2b67c3)

**Comment by anthaas** [comment]
This specific task is still corrupted and I'm still not able to submit validation.

**Comment by anthaas** [comment]
Another task to be validated after this bug is fixed. https://tasks.hotosm.org/projects/16303/tasks/?search=831

**Comment by manjitapandey** [comment]
I tried to reproduce the issue on local server by replicating the tasks history similar to this but On repeating the same task history too, I was unable to reproduce this issue.
 cc: @ramyaragupathy , @kaditya97

**Comment by manjitapandey** [comment]
> Another task to be validated after this bug is fixed. https://tasks.hotosm.org/projects/16303/tasks/?search=831

I can't test on this task since this project has been already archived.

**Comment by ramyaragupathy** [comment]
could be related https://github.com/hotosm/tasking-manager/issues/6198 cc @kaditya97 @prabinoid @manjitapandey

**Comment by prabinoid** [comment]
<img width="1440" alt="unlock after validation" src="https://github.com/hotosm/tasking-manager/assets/38830224/bd8596d3-dcd5-47f4-b23c-db54681bdcdc">
<img width="1440" alt="duplicates" src="https://github.com/hotosm/tasking-manager/assets/38830224/a73cf2b1-eac6-4a74-b089-a6763bc1e299">

**Comment by ramyaragupathy** [comment]
Thanks for capturing the information here @prabinoid. It is good to see have a handy list of projects that are affected by this behaviour.

Next actions here:

- [ ] Ramya to coordinate a time with DK and Prabin to remove duplicates from the database. This is a short term fix to remove the blockers from the validation workflow
- [ ] Prabin to investigate and document the steps captured in the database for an invalidation workflow. A task could be invalidated at multiple levels - directly after mapping or after successful validation. It is important the flow in each of the workflow and how it is captured in the backend.

cc @manjitapandey @kaditya97 @dakotabenjamin @prabinoid

**Comment by anthaas** [comment]
Another problematic task right now. https://tasks.hotosm.org/projects/15834/tasks/?search=1133
