### ISSUE TITLE
Activity and stats - show number of objects a user mapped (via osmstats api)

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#633]
American Red Cross makes some stats available that TM3 might make use of, for example:

http://osmstats.redcross.org/hashtags/mmcambridge/users

Those seem to be based on hashtags so not sure if they also make the stats available by project number, which also has a hashtag.

**Comment by xamanu** [comment]
There is quite some stats work going on (see #1147), this is not related to the osmstats tool. Closing here.
