### ISSUE TITLE
[BUG] Clicking on a task pin on the map doesn't display that task

### ISSUE THREAD

**Issue by CurtisGreen** [hotosm/tasking-manager#6342]
**Describe the bug**
When you click on a pin on the map it shows no results in the main page

**To Reproduce**
1. Go to https://tasks.openstreetmap.us/explore
2. Toggle show map
3. Scroll into an area until the individual pins are shown
4. Click on one of the pins
5. See `showing 0 of 0 projects`

**Expected behavior**
Expect to see details of selected task

**Screenshots**
After clicking:
![image](https://github.com/hotosm/tasking-manager/assets/9402065/60ac2c52-f7c4-4a81-bac0-33cebfe62a4c)

After removing `#`
![image](https://github.com/hotosm/tasking-manager/assets/9402065/e083d313-c6f7-4e69-bc6e-314b7bb96b0b)

**Desktop (please complete the following information):**
 - Browser: chrome

**Additional context**
If you remove the `#` from the task number in the search it works as expected. So the fix is fairly straightforward, either remove the `#` on click or handle the `#` in the filter logic

**Comment by Chaimann2** [comment]
Hello has anyone claimed this task and are we able to claim this task?

**Comment by ramyaragupathy** [comment]
@CurtisGreen @Chaimann2 - this issue is specific to TeachOSM instance. Please go ahead filing it under https://github.com/osmus/teachosm.org
