### ISSUE TITLE
Create a leaderboard table in the database

### ISSUE THREAD

**Issue by emi420** [hotosm/tasking-manager#6346]
This is the proposed schema:

- Name (name)
- Primary hashtag (primary_hashtag)
- Secondary hashtag (secondary_hashtag)
- Logo (logo)
- Social media links (logo)
   - Meta Link (meta_link)
   - X Link (x_link)
   - Instagram Link (insta_link)
- Other links, 5 max (links)
   - This could be a JSONB with `{"title": "A title for the link", "url": "https://thelink.com"}`

**Comment by lotjulieta** [comment]
![model-partner-tasking-manager](https://github.com/hotosm/tasking-manager/assets/100032186/fb194213-2e14-41fd-b2a6-95fa9a0c1827)
![model-partner](https://github.com/hotosm/tasking-manager/assets/100032186/d2ddcd64-5673-481f-990d-e614fe2eb15e)

partner model and its methods

**Comment by lotjulieta** [comment]
![partner-dto](https://github.com/hotosm/tasking-manager/assets/100032186/122deb23-044c-47be-af3e-4ca76f75dd91)
![dto-methods](https://github.com/hotosm/tasking-manager/assets/100032186/37fc0831-3c0f-4a9b-977d-869f6890d5a8)

partner DTO and its methods

**Comment by lotjulieta** [comment]
![partner-service](https://github.com/hotosm/tasking-manager/assets/100032186/8ee85c04-3dc4-4596-bdd6-b270f924632a)
![methods services](https://github.com/hotosm/tasking-manager/assets/100032186/efcd40cc-ad61-40c8-b6a8-16c4173f240b)

partner service and its methods

**Comment by lotjulieta** [comment]
![api-partner](https://github.com/hotosm/tasking-manager/assets/100032186/64c0c63f-a712-44bc-a2e1-2100c869e175)
![partner-id](https://github.com/hotosm/tasking-manager/assets/100032186/c60f7ab6-0fdd-47c5-b512-0aa6a54a5816)

API for all partners and API for a single partner by ID.

**Comment by lotjulieta** [comment]
![endpoints](https://github.com/hotosm/tasking-manager/assets/100032186/082beec9-6ab0-433c-a6b6-fff4a47845f0)

Endpoints and API url's.
