### ISSUE TITLE
Problems with swagger on local

### ISSUE THREAD

**Issue by dgquail** [hotosm/tasking-manager#6349]
We want to configure swagger on the backend in a local environment and we are not able to. Is there any recommendation for this that you can give us? Thank you

we are listening here: 
http://127.0.0.1:3000/api/v2/system/docs/json/

**Comment by emi420** [comment]
Hi @dgquail , there's something about the token here:

https://github.com/hotosm/tasking-manager/blob/develop/docs/developers/development-setup.md#api-authentication

Can you provide more information about the issue?

**Comment by dgquail** [comment]
It seems that swagger is not running, or at least we do not see it when invoking that URL

**Comment by ramyaragupathy** [comment]
@kaditya97 - could this be related to docker setup?

**Comment by kaditya97** [comment]
Hi @dgquail can you provide more information regarding your local setup of docker-compose file.
If you are using current docker compose file there is [swagger service](https://github.com/hotosm/tasking-manager/blob/8ce70d140ef7e6c88bb621b34ce390a751281eb5/docker-compose.yml#L85) which serves the docs at http://127.0.0.1:3000/docs/
