### ISSUE TITLE
iD editor task outline - too many "Do not edit outside this box" labels

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#636]
With the new trim to AoI feature, adding the label that says do not edit outside this box to every node can be a little too much.
![2017-06-27_14h50_02](https://user-images.githubusercontent.com/265831/27588401-466eb306-5b48-11e7-8ceb-9ee2e7d27bb7.png)

**Comment by ethan-nelson** [comment]
This was fixed in #1106 --thanks for the report!
