### ISSUE TITLE
New view for list partners, with buttons for create, edit and delete

### ISSUE THREAD

**Issue by dgquail** [hotosm/tasking-manager#6366]
![Image](https://github.com/hotosm/tasking-manager/assets/72893031/6aca0f45-8688-47bb-b616-bafb315c3b3f)

We create a list of cars with the partner's name, the first hashtag, and two buttons: one for editing the partner and the other for accessing the partner's statistics page.

**Comment by CristianAmici** [comment]
![Image](https://github.com/hotosm/tasking-manager/assets/72893031/553a2d9a-a696-4f82-986e-bfe4d7cba8e1)

We added a search bar component, similar to the one used in the project list, and applied the same logic to the new button.
