### ISSUE TITLE
New view create or edit a partner

### ISSUE THREAD

**Issue by dgquail** [hotosm/tasking-manager#6368]

**Comment by CristianAmici** [comment]
The Create form view:

![Image](https://github.com/hotosm/tasking-manager/assets/72893031/cd835279-2f4e-43d5-a0dc-dc66fc3c0804)

**Comment by CristianAmici** [comment]
The edit view with the delete button:
![Image](https://github.com/hotosm/tasking-manager/assets/72893031/2db7ed65-6dc8-43b1-b926-4f74e313adba)

The forms' behavior resembles that of the orgs CRUD.
