### ISSUE TITLE
Gulp browser-sync task does not include sass files.

### ISSUE THREAD

**Issue by sharkinsspatial** [hotosm/tasking-manager#638]
Changes to .scss files are not injected by the current browser-sync or compile-sass task.  I investigated several approaches to remedy this.  Both piping the compiled css via 
```javascript
.pipe(browserSync.stream());
```
and by directly monitoring the compiled css in the browser-sync task with no luck.  BrowserSync successfully injects the changes but no style information is available to the browser.

**Comment by LindaAlblas** [comment]
This is a known issue. We have just been refreshing the browser after the CSS finished compiling.

**Comment by xamanu** [comment]
This seems to being fixed with the ongoing redesign work. Leaving it open to check, once it is live.

**Comment by xamanu** [comment]
It has been fixed with the new redesign and frontend on TM4
