### ISSUE TITLE
[BUG] PR build failures at build and push image step

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#6405]
All the PRs we made recently have been failing at the `build and push docker image` step.

<img width="990" alt="image" src="https://github.com/hotosm/tasking-manager/assets/12103383/7c85f775-4cd9-427a-b07f-1c5acd0031ea">

Not sure what led to this, it will be great if we look into this at the earliest.

cc @mahesh-naxa @dakotabenjamin @eternaltyro

**Comment by eternaltyro** [comment]
Push to ghcr won't be allowed from third party repos or PR from third party. I will modify the workflow to remove the step so the failure does not happen.

**Comment by eternaltyro** [comment]
Made the changes to exclude develop branch from triggering a container image build when receiving PR.
