### ISSUE TITLE
Packages are not allowed to be pushed to github container registry from a forked repo

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#6408]
_Originally posted by @mahesh-naxa in https://github.com/hotosm/tasking-manager/issues/6375#issuecomment-2092437984_

@ramyaragupathy I have updated circleci with the newer node versions, this one is specific to this PR, as this PR is generated from a fork by @varun2948. 
```
#31 ERROR: denied: installation not allowed to Write organization package
```
Its an an auth issue where packages are not allowed to be pushed to github container registry from a forked repo.
(also its safe to ignore github actions related workflows for building docker images, as they are still being worked on, and is seperate from CircleCI's jobs.)

**Comment by mahesh-naxa** [comment]
related to: #6405

**Comment by eternaltyro** [comment]
Push to ghcr won't be allowed from third party repos or PR from third party. I will modify the workflow to remove the step so the failure does not happen.

**Comment by eternaltyro** [comment]
Made the changes to exclude develop branch from triggering a container image build when receiving PR.
