### ISSUE TITLE
Using the TM for Community Building

### ISSUE THREAD

**Issue by rachblevine** [hotosm/tasking-manager#641]
I wanted to suggest 2 things:
1) We stop archiving our tasks.  We've accomplished so much, and hiding that doesn't help.  This is the best way for local groups or even random volunteers, to be aware of the work we've done in a community, so why not make it easier for them?
2) Have a logged in- people counter on the main TM page.  Knowing how many others are helping out at any random time can only help boost our sense on community!
Thanks!

**Comment by hunt3ri** [comment]
Hi @rachblevine this came up on the slack channel yesterday.  I'm proposing the following solution, let me know what you think

![image](https://user-images.githubusercontent.com/1523510/32885551-b9f510e0-cab5-11e7-9461-aaaed0e0d7a3.png)

The text is just suggested by me, and can be easily altered.  cc @russdeffner @ethan-nelson @pgiraud  @dalekunce

**Comment by smit1678** [comment]
I like the idea. I know your mockup isn't the final solution, but in terms of design and placement of the data, I might suggest a fully separate section in order to help keep the text hierarchy and flow. Perhaps something along the lines of [OAM](https://openaerialmap.org/), but styled and a better layout to fit the numbers we want to show for the TM: 

![openaerialmap 2017-11-16 10-09-34](https://user-images.githubusercontent.com/796838/32885772-681765f6-cab6-11e7-87e0-e31fb5551f4d.png)

**Comment by hunt3ri** [comment]
Thanks @smit1678 I hear you - although you're pushing my v. limited design skills to the limit 😉 Consistency is good, and your design will be easier to implement on page.  Second draft (colours/fonts to be tweaked by an actual designer)

![image](https://user-images.githubusercontent.com/1523510/32887638-7f19f880-cabc-11e7-8c79-15aef6783401.png)

**Comment by rachblevine** [comment]
I love it! I think having it down at the bottom there on the homepage will be a wonderful welcome for our new mappers.  Thanks so much for following up on this.

Rachel Levine
GIS Operations and Training Coordinator
International Services | American Red Cross
202-536-7535 | skype: rachblevine

**Comment by hunt3ri** [comment]
Hi @felskia 

I've got a rough and ready version of the homepage stats working on the branch called **homepage-stats**.  It would be awesome if you could find some time to style it, as per discussion above.

As you can see from attached image it needs some love 😉 but functionally it's all working.  I'm hoping it should be a very quick win to align and set fonts, but thought you'd be best placed to advise.  Any help would be greatly appreciated 

![image](https://user-images.githubusercontent.com/1523510/33403252-8557d8c0-d557-11e7-9309-f7f16312bd00.png)

Thanks 
Iain

**Comment by hunt3ri** [comment]
Hi @LindaAlblas would be great if we can get this styled :)

**Comment by LindaAlblas** [comment]
I've added a commit to the homepage-stats bramch which styles the stats very similar to the OAM stats and the mockup provided. See below. @hunt3ri is the branch ready for a PR?

<img width="654" alt="homepage-stats-large" src="https://user-images.githubusercontent.com/3329074/33877693-10f904da-df21-11e7-8a96-1d75462ac2d3.PNG">

**Comment by bgirardot** [comment]
This was implemented and deployed to production. Thank you very much everyone.
