### ISSUE TITLE
New dev setup for fastapi

### ISSUE THREAD

**Issue by kaditya97** [hotosm/tasking-manager#6413]
- The branch that needs to be deployed [https://github.com/hotosm/tasking-manager/tree/tasking-manager-fastapi](https://github.com/hotosm/tasking-manager/tree/tasking-manager-fastapi)
- The docker-compose file has services that need to be setup
@eternaltyro 

Main issue: #6332

**Comment by eternaltyro** [comment]
I will deploy this manually on AWS.

**Comment by eternaltyro** [comment]
This is done. Including CD via Github workflows.
