### ISSUE TITLE
[BUG] Live monitoring view alters nav menu alignment

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#6415]
**Describe the bug**
While accessing the data live monitoring page, icons on nav menu are misaligned. Misalignment continues even after you move away from the page and continue to map tasks. However after a hard refresh the alignment is fixed.

**To Reproduce**
1. Go to any project's live monitoring view
2. Check the nav menu on top. You will see the support icon moved to bottom and the dropdown next to user's name missing
3. Next come back to the project and try locking a task with iD editor
4. You will notice the icons displaced in the nav menu and also in the iD editor's sidebar

**Expected behavior**
Accessing the data live monitoring page should not affect other sections of the frontend

**Screenshots**
<img width="1431" alt="image" src="https://github.com/hotosm/tasking-manager/assets/12103383/8dd9e983-9cd0-4726-9cc1-9b2328866620">

<img width="1437" alt="image" src="https://github.com/hotosm/tasking-manager/assets/12103383/c4b40d15-3727-4378-ac5b-832338a1f1fb">

**Desktop (please complete the following information):**
 - MacOS
 - Chrome, Firefox

**Comment by ramyaragupathy** [comment]
cc @emi420 @royallsilwallz @manjitapandey

**Comment by emi420** [comment]
I suspect this is related to the Tailwind CSS loading that we use with the Underpass UI component. It should be isolated and not affecting the rest of the pages. I'll take a look.

**Comment by emi420** [comment]
I made changes to the Underpass UI components to isolate all styles with a className prefix. 

It has to be tested but it's available on the `dev` branch:

https://github.com/hotosm/underpass-ui/tree/dev

This should fix the issue. Maybe some changes will be needed on the TM side, as there are styles that need to be removed here:

https://github.com/hotosm/tasking-manager/blob/develop/frontend/src/views/projectLiveMonitoring.css

**Comment by emi420** [comment]
Update: Underpass UI new version (0.1.2) is published, I tested it today in the Tasking Manager and is working fine, but some changes are needed for the Live Monitoring view, I'm working on it. 

I'll create a PR next week that will include:

- Fix for this styling issue
- Performance improvements
- Fixes for React state management issues
- New feature for render the project AOI on the map
