### ISSUE TITLE
[BUG] Live monitoring not accessible for expert mode users

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#6416]
**Describe the bug**
Wit expert mode turned on, I am unable to see `Live monitoring` button enabled for a project. This project is in Malawi and it is present in the list of available countries(Bangladesh, Malawi, Ecuador, Morocco, and Nigeria). However I can directly access the live monitoring page via the link https://tasks.hotosm.org/projects/12918/live. But the page does not load any feature list. On checking console, there are a bunch of CORS errors reported

**To Reproduce**
1. Go to 'https://tasks.hotosm.org/'
2. Make sure you have `Expert mode` turned on in your `user settings`
3. From explore projects, filter out projects present in one of the five available countries(Bangladesh, Malawi, Ecuador, Morocco, and Nigeria)
4. Scroll down to 'Contributors timeline'
5. See if the `live monitoring` button is enabled below this graph. Ideally it should be present, but it is missing
6. Now add a `live` text to the project url, for example: https://tasks.hotosm.org/projects/12918/live and hit `enter`
7.  Live monitoring page view  loads with a map and a side bar, but there is no feature list and no objects show up on the map
8. Check the browser console and you will notice CORS errors

**Expected behavior**
Ideally live monitoring option should be enabled for expert mode users, provided the project is in the list of available countries (Bangladesh, Malawi, Ecuador, Morocco, and Nigeria). When the live monitoring page loads, there should be a list of buildings features mapped through that project.

**Screenshots**

<img width="1392" alt="image" src="https://github.com/hotosm/tasking-manager/assets/12103383/91a47cf7-fe44-4bda-a07b-31318f194c93">

**Desktop (please complete the following information):**
 - MacOS
 - Chrome

**Comment by emi420** [comment]
Fixed! I've added https:://tasks.hotosm.org to the list of domains enabled for the https://underpass.hotosm.org API.

CC @ramyaragupathy
