### ISSUE TITLE
Update docker related files, requirements for FastAPI

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#6417]
@kaditya97 updates

**Comment by kaditya97** [comment]
- Added requirements for fastapi setup `fastapi==0.108.0`, `pydantic==2.5.3`, `pydantic-settings==2.1.0`
- Rewritten docker file to include fatapi setup, changed image cmd to address fatapi
- Rewritten docker-compose file, removed swagger service as fastapi natively supports swagger docs
