### ISSUE TITLE
[BUG] Not possible to map, only to validate

### ISSUE THREAD

**Issue by angoca** [hotosm/tasking-manager#6423]
**Describe the bug**
This project https://tasks.hotosm.org/projects/16723/tasks/ has a dozens of squares to map, but it is not possible to select one of them:

<img width="682" alt="image" src="https://github.com/hotosm/tasking-manager/assets/294317/63ab00b6-3584-4331-b50f-eb971f224874">

I have am part of the validator's team, but in this moment, I want just to map, not to validate.

**Comment by manjitapandey** [comment]
Hello, I see all the tasks in this project has been already mapped. Could you be able to share the same behavior, if exist, on other projects?

**Comment by angoca** [comment]
It was blocked from 4 am to 4:20 am UTC.
It was not only me, all other mappers working on the same project faced the same issue.
After that, we could finish the project.

**Comment by manjitapandey** [comment]
Was it because project creator changed the settings? If it works good, are we good to close this issue?

**Comment by angoca** [comment]
I think we can close it.
