### ISSUE TITLE
Page goes blank when user selects language to Netherlands

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/tasking-manager#6425]
**Describe the bug**
When user changes their language to netherlands, the website of tasking manager goes blank. 

**To Reproduce**
1. Go to 'settings
2. Click on 'language'
3. change language from English to Netherlands. 

**Expected behavior**
The page should function smooth instead of showing blank page. 

**Screenshots**
![image](https://github.com/hotosm/tasking-manager/assets/97273021/b7460b5b-6b3b-4228-a57e-cd958ada6b61)

**Additional **
https://hotosm.slack.com/archives/C319P09PB/p1715157425925069 : slack conversation

**Comment by SiemHW** [comment]
LS, I'm having the same problem since the website requested an update. I think it was May 8th. So I haven't been able to map for a few days now because the website (https://tasks.hotosm.org/) does not show any images.
Kind regards, SiemHW

**Comment by manjitapandey** [comment]
My contribution page shows unknown error changing from english to other languages. More details on : #6429

steps to reproduce:

- change language settings to netherlands
- go to my contributon page
- see error

![image (9)](https://github.com/hotosm/tasking-manager/assets/97273021/03b1c88d-3b00-4f1b-96c7-d1a229549f69)

**Comment by royallsilwallz** [comment]
**Findings**
This issue stemmed from [frontend dependency updates](https://github.com/hotosm/tasking-manager/pull/5721) PR, changes in `frontend/src/utils/internationalization.js` file, where Taylor refactored [this](https://github.com/hotosm/tasking-manager/pull/5721/files#diff-fe61c5fd62dec29e3ba357a2cf9621065e62140ed4010c66c7949b48433b700dL36) part of the code. This resulted the mappings for static language json files to be handled improperly, and thus caused the page to crash when the json files were not found.
