### ISSUE TITLE
"Manage" menu

### ISSUE THREAD

**Issue by dgquail** [hotosm/tasking-manager#6427]
The menu under "Manage" should remain visible and respond when switching between its different sections. However, while clicking on "organizations" keeps the menu intact, clicking on "partners" seems to make the menu disappear and take you to an unexpected place. 
Could it be that this problem also causes us routing problems?
Do you have any suggestions or recommendations for using this component?

**Comment by emi420** [comment]
The menu that @dgquail is mentioning is the submenu with the links for "Overview, Projects, ..." where there will be a new "Partners" link:

<img width="1044" alt="Screenshot 2024-05-14 at 11 01 09" src="https://github.com/hotosm/tasking-manager/assets/1226194/ffb4be68-df8f-48bc-8076-512fb6f50a31">

**Comment by ramyaragupathy** [comment]
cc @royallsilwallz @varun2948 @manjitapandey

**Comment by dgquail** [comment]
Thanks @emi420 and @ramyaragupathy . The problem is not that the 'Partners' menu is displayed, we have already added that. The fundamental problem is that when we enter the partners page the manage menu disappears and we are not finding a way for the Partner's CRUD to always be visible.
What do we have to take into account so that the manage menu is always visible while managing partners?

Thanks all

**Comment by royallsilwallz** [comment]
hey @dgquail, I'll be looking into this issue today and get back to you with my findings.

**Comment by ramyaragupathy** [comment]
@dgquail - please share the link to your code for @royallsilwallz to review this further

**Comment by royallsilwallz** [comment]
hey @dgquail, it worked fine for me in the latest develop branch. I created a view with partners page and added the partners link to the tab like in the screenshot below. I think I'll have to take a deeper look into your code to see the issue.

![image](https://github.com/hotosm/tasking-manager/assets/51167861/fb58a7a0-547c-4178-8fa3-ef93963af6ac)
