### ISSUE TITLE
Error in My contribution page due to change in language from english to other few languages. 

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/tasking-manager#6429]
**Describe the bug**
My contribution page shows error message after i changed my language settings from english to few other languages. I could reproduce those error while changing language from English to nederlands and svenska.

**To Reproduce**
1. Go to my settings. Make sure that you are signed and have english default language.
2. Change Language to Nederlands or svenska.
3. Click on my contribution page

**Screenshots**
![image](https://github.com/hotosm/tasking-manager/assets/97273021/c9a5fe08-85fc-42e5-aa36-da59e81abf07)

**Additional context**
this problem could be on other languages too. Will dig in further and provide update on comment. 

Update: This error is not only limited to my contribution page but on all pages consisting map like project page, tasks page and more.

**Comment by royallsilwallz** [comment]
After some digging in, I found that this is related to Mapbox not supporting all the TM selected languages, causing errors due to unsupported languages.

**Comment by royallsilwallz** [comment]
Mapbox supported language (provided by `@mapbox/mapbox-gl-language` package) 
- ["ar", "en", "es", "fr", "de", "ja", "ko", "mul", "pt", "ru", "zh"]
