### ISSUE TITLE
[BUG] Unable to clone project due to name validation

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/tasking-manager#6442]
**Describe the bug**
I am unable to clone the project. On trying 

**To Reproduce**
1. Go to 'edit project'
2. Click on 'Actions and clone project'
3. Try cloning the project

**Expected behavior**
The project should be cloned without any error message. 

**Screenshots**
![image (9)](https://github.com/hotosm/tasking-manager/assets/97273021/5d1bf861-07ac-40f7-a3d6-335e9d5d114b)

**Comment by royallsilwallz** [comment]
Stemmed from #6376

**Comment by SColchester** [comment]
Project cloning is essential for many project creators (saves many hours of work) - the sooner that this can be resolved the better! Thanks for spinning up the issue 👍

**Comment by ramyaragupathy** [comment]
Sure @SColchester - this fix is under testing and we are aiming to make a release at the earliest.

cc @manjitapandey @royallsilwallz @dakotabenjamin
