### ISSUE TITLE
current project list doesn't load in partners page

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/tasking-manager#6461]
**Describe the bug**
While viewing the statistics of partners page, the current project list goes on loading for ever and no API is hit during the time to provide list of current projects

**To Reproduce**
Make sure that you have admin access on the platform
1. Go to 'manage and partners page'
2. Click on 'statistics of any partners card '
3. Scroll down to 'current project list'

**Expected behavior**
The list of current project from that partners should be visible. If there is no current project, then message to indicate no projects are running during this time should appear instead of making it loading forvever. 

**Screenshots**
![image](https://github.com/hotosm/tasking-manager/assets/97273021/1dbb8cde-f683-4d50-a0cf-d1a5d4bfbb9a)

**Comment by emi420** [comment]
@manjitapandey error happens when the project doesn't exist right?

**Comment by manjitapandey** [comment]
Yes @emi420 looks like this behavior is only when there is no project added.

**Comment by ramyaragupathy** [comment]
If one of the project added to the list is not valid, the entire project section does not load. Ideally it should load with project IDs that are valid. If none of the project exists, then there should be a message for the user `there are no projects to show`.

In an ideal world, we will have validation for project IDs in the partner edit page.
