### ISSUE TITLE
Partners: secondary hashtag field size is too small in the DB

### ISSUE THREAD

**Issue by emi420** [hotosm/tasking-manager#6464]
**Describe the bug**
The limit for the secondary hashtag column is 50 characters, which is too small.

**To Reproduce**

1. Go to create a partner
2. Try with several hashtags (+50 characters) in the secondary hashtag field
3. Click "Save"
4. It will fail because the API returns Error 500

**Expected behavior**

To accept more than 50 characters for the secondary hashtag.

**Additional info**

Check this migration file:

https://github.com/hotosm/tasking-manager/blob/develop/migrations/versions/e8ffa33a9c18_.py#L26C1-L26C23

**Comment by ramyaragupathy** [comment]
cc @manjitapandey @prabinoid @kaditya97
