### ISSUE TITLE
Consistent UI for partners management 

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#6465]
#6468

<img width="1048" alt="image" src="https://github.com/hotosm/tasking-manager/assets/12103383/041ebf42-fba3-460c-be7a-5f4bb7df579e">

Rest of the pages have a card view in a non dotted background. we should maintain consistency in partner section as well

<img width="1324" alt="image" src="https://github.com/hotosm/tasking-manager/assets/12103383/8b81e709-8efe-43c2-bf6d-09c7dbe9c65e">

**Comment by ramyaragupathy** [comment]
Also the `manage partners` text and `search partners` component should be left aligned similar to the look and feel in other management sections. It is now centered which is different from rest of the managed resources

cc @royallsilwallz @manjitapandey @emi420

**Comment by manjitapandey** [comment]
The space between the component is also not consistent on partner's editing and creation. See the gap between manage and the form component. 
![image](https://github.com/hotosm/tasking-manager/assets/97273021/11d954a3-9f23-47f7-b32c-8b1593e99f57)
![image](https://github.com/hotosm/tasking-manager/assets/97273021/cd494067-d206-4eec-803c-c6c23d22c543)
