### ISSUE TITLE
Connection time out

### ISSUE THREAD

**Issue by TeBaMa** [hotosm/tasking-manager#6492]
**Describe the bug**
When I hit the 'sign in' button on https://tasks.hotosm.org/login  a get a pop up 'connection time out' (see screenshot)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser chrome
 - Version 126.0.6478.127 (Officiële build) (64-bits)

**Comment by TeBaMa** [comment]
![TimeOut](https://github.com/hotosm/tasking-manager/assets/93079314/5fb91156-9270-4cdc-857d-879a72f247cf)

**Comment by TeBaMa** [comment]
My problems seem to be resolved :-)
I can log in now.
Sorry for this ticket

**Comment by manjitapandey** [comment]
No worries @TeBaMa , there was technical problem with openstreetmap yesterday causing the issue you raise above. Now it has been fixed.
