### ISSUE TITLE
[BUG] Downloading GeoJSON of archived task 

### ISSUE THREAD

**Issue by nashmsf** [hotosm/tasking-manager#6499]
**Describe the bug**
Unable to download footprints of archived tasks. Specifically Rafah 1 and 2 of Gaza Private project

**Additional context**
This was an issue before too, see Slack thread https://hotosm.slack.com/archives/C06KW4SRQG4/p1710934534176699

**Comment by manjitapandey** [comment]
@nashmsf , Can you provide me few contexts around it? Like how older is the task and Was it archived recently?

cc: @kshitijrajsharma

**Comment by nashmsf** [comment]
@kshitijrajsharma found a work around in the Slack channel by commenting on the task to make it active. And as such the exports will then become available.
