### ISSUE TITLE
Server Error when I invalidate all tasks for a project with multiple tasks locked

### ISSUE THREAD

**Issue by popelnuh** [hotosm/tasking-manager#650]
When I have multiple tasks selectd for mapping  or validation
And I validate/invalidate all tasks (edit project>actions>Invalidate All taks)
I get 'Invalidating all the tasks failed for an unknown reason.' message
And response code is 500
And the message is '{"error": "Project GET - unhandled error: Multiple rows were found for one()"}'

**Comment by popelnuh** [comment]
This is a bug which requires thinkWhere investigation. 
This is also an edge case, as the bug is limited to admin/project manager role & does not affect the majority of end users.

**Comment by hunt3ri** [comment]
Deployed to staging environment, ready to test.
