### ISSUE TITLE
Project Summary Table View

### ISSUE THREAD

**Issue by AkshayGuptaK** [hotosm/tasking-manager#6500]
**Is your feature request related to a problem? Please describe.**
Currently the project summary statistics page supports only a grid view, with no partner filtering and option to download data.

**Describe the solution you'd like**
Option for toggling between existing grid + map view and a new table only view. Support filtering by partner and associated duration. Support downloading all data for filters as CSV.

**Additional context**
TBD

**Comment by ramyaragupathy** [comment]
related https://github.com/hotosm/tasking-manager/issues/3394

**Comment by emi420** [comment]
Hey everyone, I share here a design proposal for the table view, please tell me what do you think, this is not the final version and will be adjusted after your feedback, thanks!

![tasking-manager-table-view-1](https://github.com/user-attachments/assets/6e44d0c2-2135-40f9-9f0f-742b3d713295)

**Comment by emi420** [comment]
I made a few changes as we discussed.

- List/table view are now icons
- Removed map view for location
- Removed "sort by" icon
- Moved "Download CSV" to the top
- "Showing XX of YY projects" is now in the same position that in the list view
- "Show map" is disabled when in the table view
- Pagination styling is the same than in the table view

![tm-projects-table-view](https://github.com/user-attachments/assets/b2eba28c-90b9-4789-9b27-d801f2cc9358)
