### ISSUE TITLE
Partner pages: design proposal for social icons & resources

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#6513]
_Originally posted by @emi420 in https://github.com/hotosm/tasking-manager/issues/6502#issuecomment-2256359515_

As we discussed, here's the design proposal for social icons + resources, trying to keep information organized and clean.

<img width="698" alt="Screenshot 2024-07-29 at 13 15 52" src="https://github.com/user-attachments/assets/051d746c-e27a-4c38-aa26-e70a0656378e">

<img width="688" alt="Screenshot 2024-07-29 at 13 16 04" src="https://github.com/user-attachments/assets/db785e92-1639-4d57-a096-979fe023c04a">

**Comment by ramyaragupathy** [comment]
cc @royallsilwallz @manjitapandey

**Comment by emi420** [comment]
This design changed a little bit because the new partner stats page, the dropdown is still there but the links background and the position of the social links changed?

![362691123-03d6245a-6909-4283-bc4e-336a8710c905](https://github.com/user-attachments/assets/6f271c01-3baf-408b-a4ef-73836bc0e80c)

**Comment by emi420** [comment]
![Screenshot 2024-08-29 at 14 59 42](https://github.com/user-attachments/assets/58a3b8d3-123b-4121-94df-95c5bc8177c0)
