### ISSUE TITLE
Contribution Card Component for Partner Statistics Page

### ISSUE THREAD

**Issue by AkshayGuptaK** [hotosm/tasking-manager#6537]
**Describe the solution you'd like**
A set of card components for showing MapSwipe DTO data in the partner statistics page.

<img width="289" alt="Screenshot 2024-08-21 at 9 11 43 PM" src="https://github.com/user-attachments/assets/e908fe25-7e7c-4654-a054-0e0aad9f4e93">

**Comment by AkshayGuptaK** [comment]
@emi420 Please let us know the final designs.

**Comment by emi420** [comment]
![tm-mapswipe-stats-1](https://github.com/user-attachments/assets/6710f89e-e4ee-4f44-a35a-0b783937c095)
