### ISSUE TITLE
Contribution Table Component for Partner Statistics Page

### ISSUE THREAD

**Issue by AkshayGuptaK** [hotosm/tasking-manager#6538]
**Describe the solution you'd like**
A table component for showing MapSwipe DTO data in the partner statistics page.

**Additional context**
Using TanStack table component library.

<img width="618" alt="Screenshot 2024-08-21 at 9 15 22 PM" src="https://github.com/user-attachments/assets/da22db1d-bdd1-43de-8bf7-25f2f6429246">

**Comment by AkshayGuptaK** [comment]
@emi420 Please let us know the final design.

**Comment by emi420** [comment]
@AkshayGuptaK

![table](https://github.com/user-attachments/assets/eccd349f-fde7-4640-a034-3e52aae9c4ab)

**Comment by emi420** [comment]
![tm-mapswipe-stats-1](https://github.com/user-attachments/assets/03d6245a-6909-4283-bc4e-336a8710c905)
