### ISSUE TITLE
Have unified language across the partnership page and it's URL

### ISSUE THREAD

**Issue by nicolelaine** [hotosm/tasking-manager#6622]
**Is your feature request related to a problem? Please describe.**
The Tasking Manager tab is called "Tasking Manager" but the URL called it a "leaderboard", which is language that we are moving away from. 

Screenshot:
![Screenshot 2024-11-06 at 13 34 17](https://github.com/user-attachments/assets/9b3cb141-547b-4ddc-bfbf-abffb02d8a38)

**Describe the solution you'd like**
It would be good to unify the language across the entire partnership page, and have this page indicate that this is the tasking manager tab in the URL

**Comment by ramyaragupathy** [comment]
fixed through https://github.com/hotosm/tasking-manager/pull/6601
