### ISSUE TITLE
List the partners' MapSwipe group name on the MapSwipe tab on the new partnership page

### ISSUE THREAD

**Issue by nicolelaine** [hotosm/tasking-manager#6623]
**Is your feature request related to a problem? Please describe.**
Partner's don't have easy access to the name of their group on MapSwipe, as it's not listed at the top of the MapSwipe tab

**Describe the solution you'd like**
On the Tasking Manager tab, you can see the main hashtag at the top of the page. It would be nice if the partner's MapSwipe group name was listed at the top of the MapSwipe tab as well. This is listed at the top of the group's page on MapSwipe, so it seems like it could be pulled over.

**Comment by ramyaragupathy** [comment]
fixed through https://github.com/hotosm/tasking-manager/pull/6601
