### ISSUE TITLE
Make Landing page content more dynamic

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#678]
It would be good if the landing page could have more dynamic content about what campaigns are currently going on, with links to all the current projects in the campaign.

**Comment by cgiovando** [comment]
@russdeffner can you help us draft three current campaign highlights for the `Causes You Can Help` on  http://tm3.hotosm.org/ ?

**Comment by russdeffner** [comment]
I don't know about 3, but the malaria one is still fairly relevant or will be again in near future but should maybe be "Global-Malaria". Although, for the record, I don't remember saying that ;) We could use a quote from CHAI instead.
I can work on one for "Disasters" maybe that is more permanent, and then the last one should maybe be from our field work? Was thinking one of the refugee crises or maybe Ramani Huria itself?

**Comment by cgiovando** [comment]
Yes, that sounds good @russdeffner - let's tweak the malaria one and add one for current disaster activations and one for the refugee camp mapping. Please draft proposed text/links/visuals here as a comment, unless you want to send a PR directly for that page. Thanks!

@PaulUithol can you draft the one for refugee camp mapping campaign?

**Comment by russdeffner** [comment]
Here's a disaster one, I'll see what I can do about the malaria one:
"With our disaster mapping program, what we are trying to provide is a common operating picture for the first responders, aid organizations, governments and the affected people to make informed decisions. When all parties are working with the same information, the better situated the community is for quick and effective recovery."

**Comment by xamanu** [comment]
This is currently tackled with the redesign by @hotosm/major in https://github.com/hotosm/projects/issues/17

**Comment by xamanu** [comment]
This has been improved with the redesign for Tm4.
