### ISSUE TITLE
Project Contribute page - Activity and Stats could be a tab

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#683]
Is there a way to move the "activity and stats" button off of the map and make it a tab? Since it is a full page and dedicated to stats and activity, maybe it could be a "fly out" or something the pops down.

**Comment by dalekunce** [comment]
+1 for this its very confusing why the button is here if it doesn't have _anything_ to do with the map.

**Comment by giblet22** [comment]
Bumping this. Even if it's not a separate tab, the % completed and validated should should be more easily seen. Maybe where the project description is.

**Comment by xamanu** [comment]
This became the "contributions" tab on projects in TM4. :+1:
