### ISSUE TITLE
Project mapping page - map legend has a lot of colors

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#684]
There are new options for the map legend, but it ends up a little complicated. Is there a way to reduce the number of colors used?

**Comment by hunt3ri** [comment]
The only new state over TM2 is Bad Imagery all previous states previously existed, and this had been agreed at the start of the project.

These mapping states are deeply embedded in the application, so reducing them would not be trivial, as new flows would need to be designed.

**Comment by xamanu** [comment]
This is being tackled in #1257
