### ISSUE TITLE
Wrong type errors in API not always handled gracefully

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#685]
Somewhat related to #543, except this deals specifically with passing a wrong variable type to certain API endpoints.

http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/api/v1/project/2  (a non-existent project) returns a 'project not found' error.

http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/api/v1/project/new returns an HTML page with the navigation header as opposed to returning a JSON.

Non-existent projects are handled in https://github.com/hotosm/tasking-manager/blob/6962af3162fe63f7d0301279803f671a175d8612/server/services/project_service.py#L24-L31 but there isn't an exception handling in the function that calls this from the API endpoint for inputs of the wrong type: https://github.com/hotosm/tasking-manager/blob/6962af3162fe63f7d0301279803f671a175d8612/server/services/project_service.py#L37-L46

This is likely causing the strange behavior of HTML being returned from the API endpoint.

We could add a few [`InvalidData`](https://github.com/hotosm/tasking-manager/blob/6962af3162fe63f7d0301279803f671a175d8612/server/models/postgis/utils.py#L25-L29) catches in these functions (which might be a good task for someone trying to learn the codebase if a fix is not immediately necessary), unless there's a better strategy for enforcing type in the API calls.

**Comment by akankshanayak2111** [comment]
Hi, I was wondering if I can take up this issue?

**Comment by bgirardot** [comment]
@akankshanayak2111 There is no one available who can do testing and give feedback on this issue at the moment so I would not start working on it. I see you asked about some other issues so those would be best to start with.

**Comment by xamanu** [comment]
This has been improved as by the API review for TM4.
