### ISSUE TITLE
Reduce the white space between menu bar and page content

### ISSUE THREAD

**Issue by bgirardot-np** [hotosm/tasking-manager#688]
On the contribute page and the individual project pages there is a large gap of white space. If we could reduce that as much as possible to get the content right below the menu bar.

![2017-08-17_15h36_11](https://user-images.githubusercontent.com/12796805/29415026-e59b0c2c-8361-11e7-8353-510a74a6eecd.png)

![2017-08-17_15h37_14](https://user-images.githubusercontent.com/12796805/29415116-2fbca78e-8362-11e7-8a89-03f7b084dac1.png)

**Comment by felskia** [comment]
@bgirardot looks like this is already fixed. Closing this for now.

**Comment by bgirardot** [comment]
There is still a lot of white space that could get removed. I am going to re-open this as we have some folks who might want to work on this.

**Comment by bgirardot** [comment]
@Madhumathi97 This is the one I had in mind, if you wanted to work on this.

It is harder than it looks to fix :)

**Comment by Madhumathi97** [comment]
Ok thank you.I will work on it.:)
