### ISSUE TITLE
Contribute Page - Applying a filter that returns no results loses the filter controls

### ISSUE THREAD

**Issue by bgirardot-np** [hotosm/tasking-manager#690]
If you apply a filter on the contribute page that returns no results, the filter controls are lost so there is no easy way to correct the issue and apply filters that do return results.

![2017-08-17_15h41_40](https://user-images.githubusercontent.com/12796805/29415265-c9207cde-8362-11e7-9ca5-bbb53ee79ff8.png)

**Comment by bgirardot** [comment]
@felskia Hi Ali, the fix for this works well, it does still leave the navigation in place.

![2017-08-17_23h49_19](https://user-images.githubusercontent.com/265831/29435341-fab2e248-83a6-11e7-9145-56f726a542c8.png)

**Comment by felskia** [comment]
@LindaAlblas would you be able to help with this? I'm not sure where to place the pagination in the HTML for it to disappear with the cards. 

Thanks!

**Comment by LindaAlblas** [comment]
@bgirardot @felskia this should be fixed now

**Comment by cgiovando** [comment]
@bgirardot can you test this and close?

**Comment by bgirardot** [comment]
Fixed, thank you Linda.
