### ISSUE TITLE
clickable elements don't necessarily change cursor to pointer

### ISSUE THREAD

**Issue by pgiraud** [hotosm/tasking-manager#696]
A lot of elements in the UI are clickable. A lot of them don't change cursor on hover. Usually clickable elements show a "pointer" cursor on hover.
This is for example the case for tabs (in the front page, or in the project page) or for the dropdown to change the language.

I'd be happy to provide a pull request. But do you guys prefer to add an `<a>` HTML tag or should we try to handle this only with CSS?

**Comment by bgirardot-np** [comment]
Whatever you and @LindaAlblas think is best way to handle.

**Comment by LindaAlblas** [comment]
@pgiraud there is a .pointer helper class that you can use (in _helpers.scss). It is probably easiest to use this class.
