### ISSUE TITLE
Dropdown arrow don't show up

### ISSUE THREAD

**Issue by pgiraud** [hotosm/tasking-manager#697]
The link to the svg file seems broken.
See language switcher in the main menu.

**Comment by bgirardot-np** [comment]
@LindaAlblas Do you have any idea why the down arrows (chevrons) show up if you run the UI via gulp run, but not if you gulp build and then launch the server instead of 'gulp run'?

**Comment by LindaAlblas** [comment]
@bgirardot-np I assume you mean on Ali's branch? I have pushed a fix for it on Ali's branch. It was putting the new icons folder in the images folder which is why it couldn't find the icons.

**Comment by LindaAlblas** [comment]
@pgiraud @bgirardot it is fixed on the demo site.

**Comment by bgirardot** [comment]
Looks fixed to me. Thank you Linda
