### ISSUE TITLE
Overview map on project page is distorted

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#699]
If you click on the small overview map icon in the upper left of the task map, the resulting overview map is stretched the full length of the task/project map.

![2017-08-21_03h40_23](https://user-images.githubusercontent.com/265831/29500623-b01459be-8622-11e7-9f93-7aa89afd0792.png)

**Comment by alekno** [comment]
#840 #719 map issues related

**Comment by smit1678** [comment]
Just to follow up this is still an issue, I've just tested in Chrome and Firefox. Below is the difference between the two browsers: 

## Chrome
![tasks-overviewmap](https://user-images.githubusercontent.com/796838/46289531-866e6600-c5b3-11e8-89ad-f1bd5b7b3596.gif)

## Firefox 
![tasks-overviewmap-firefox](https://user-images.githubusercontent.com/796838/46289520-7eaec180-c5b3-11e8-98a0-0692b3726789.gif)
