### ISSUE TITLE
Can checkout more tasks for validation after checking initial one or set of tasks

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#700]
If I checkout multiple tasks for validation from the user list and then click off of the map, I can select another set or individual task for validation.

It also seems that if I properly select multiple tasks for validation and click off of them by clicking outside of the map, I can never get them all selected again to mark valid/invalid/stop validation.

I would expect it work like mapping does, once I select a task or in this case, tasks, it would say you already have some checked out, reselect them.

![2017-08-21_03h49_14](https://user-images.githubusercontent.com/265831/29500916-c1aec086-8624-11e7-8c24-127c6491269f.png)
![2017-08-21_03h49_29](https://user-images.githubusercontent.com/265831/29500915-c1ad1682-8624-11e7-9eb5-e17e8c92ec5d.png)

@hunt3ri @LindaAlblas  Can you take a look at this? Not sure if it is front end or back end issue.

**Comment by bgirardot** [comment]
Oh I see, there is a "reselect tasks for validation" button. that works. It also works if I then checkout more tasks for validation.

I am happy to get your feedback on this. Still seems like a bug to me that I can select more tasks after I have already checked some out, but perhaps since you can still reselect them all, it is not very critical bug.

**Comment by ethan-nelson** [comment]
I just came across this with some local testing. My thought is a validator may want to add more tiles to their validation check (e.g. more than one user's worth), but perhaps that is something we don't want to encourage.

**Comment by willemarcel** [comment]
On TM4 we allow only one lock action at a time.
