### ISSUE TITLE
Logo and title need polishing

### ISSUE THREAD

**Issue by cgiovando** [hotosm/tasking-manager#703]
As reported by @smit1678 the current title text looks grainy and we could remove "HOT" from the it, since it's already in the logo.

It refers to this PR which is currently merged in master --> https://github.com/hotosm/tasking-manager/pull/676

**Comment by smit1678** [comment]
Big bold text also clashes with the regular text right next to it. I would suggest either just using the core HOT symbol without any text, use the HOT logo with full name text, or consider using the recommendation from Vizzuality: 

<img width="831" alt="screen shot 2017-08-21 at 11 47 53 pm" src="https://user-images.githubusercontent.com/796838/29537662-36eb4a30-86cb-11e7-8ab9-652e4825cff6.png">

**Comment by cgiovando** [comment]
We discuss those options, but having "Team" and "Tasking Manager" on the same line seemed a bit odd. Also, would be good to put more emphasis on the tool name, more than just using a different color.

Using the HOT logo without always carrying the full text acronym explainer might also make it easier to brand HOT products.

**Comment by bgirardot** [comment]
I find the suggested logo for Core Tools/ Sites unappealing and distracting from the name of the tool.

As I suggested, it makes more sense for that arrangement to be used for initiatives where we want to emphasize the name of the organization, instead of tools where we want to emphasize the name of the tool.

**Comment by DylanMoriarty** [comment]
[Cross posting from here](https://github.com/hotosm/osm-export-tool2/issues/217#issuecomment-325423661)

It would help a good deal to add another separator line between the logo and the nav items. Right now they're just slightly too similar in size/style. Something ala:

<img width="789" alt="screenshot 2017-08-28 13 41 29" src="https://user-images.githubusercontent.com/9341928/29787769-23aa7990-8bfe-11e7-9295-33064567a705.png">

Also a few logo options:

<img width="809" alt="screenshot 2017-08-28 13 36 17" src="https://user-images.githubusercontent.com/9341928/29787790-3413ccf0-8bfe-11e7-9d62-5852cf5b7289.png">

I lean towards a darker, semi-bold tool text.

**Comment by cgiovando** [comment]
@smit1678 is this something you can quickly send a PR from @DylanMoriarty's high-res logos? Thanks
