### ISSUE TITLE
Mapper experience level for imported data

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#706]
Hi @hunt3ri @david-hotosm Wasn't the data import process or some part of that workflow going to update the mapper experience levels? I see on the tW staging site, all the imported users have the correct mapper experience level, but not on HOT's staging sites.

And, can we adjust those changeset buckets before we go live?

**Comment by bgirardot** [comment]
@hunt3ri Hi Iain, I see issue #458 says when they visit their profile page. 

Is that the current functionality? How did the thinkWhere stage site get everyone's mapper experience level correct?

Is there any other way to get their experience level updated? as mentioned on 458, it would be better if it happened on login as well.

**Comment by hunt3ri** [comment]
Hi @bgirardot I think I must have written a wee script to do it, I can't remember now.  It must have been a few lines that I had locally to call the appropriate function to do the update.

As you say the experience level will fill in, as user log in or people view the profiles.

**Comment by bgirardot** [comment]
@hunt3ri If you can just confirm it gets updated on login that would be great. I just do not want everyone to have to visit their user profile to get that stat updated.

**Comment by hunt3ri** [comment]
If they are a new user, it will create the stats, otherwise they need to visit their profile.  But to see their experience level they need to visit their profile anyway, right?

**Comment by bgirardot** [comment]
@hunt3ri The main impact is on the validation process. Everyone is a beginner and those will be stuck at whatever level they were at when they did visit their user profile last.

On login would be great, or a wee script that could run on a regular basis, maybe weekly.

It caught me by surprise because on the tW staging server everyone's was updated so I thought it was part of the import process or ran at another time.

**Comment by hunt3ri** [comment]
Script added in PR #764 let me know if you have any questions

**Comment by bgirardot** [comment]
@david-hotosm can you try this on the next database import please?
