### ISSUE TITLE
Images in a project description won't fit in the compact tiled presentation (in the list of projects) and overlap other fields

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#712]
Projects that include images need to have a width restriction
![roads](https://user-images.githubusercontent.com/8775395/29644987-ea2d64fe-88bd-11e7-8157-439d25e45547.JPG)

**Comment by verdy-p** [comment]
it would need rescaling the images by allowing them to fit the available width in the container. This could be achieved by CSS (using a contextual class for the tiled compact presentation in the list of projects.

**Comment by 2Clutch** [comment]
Does this still need to be worked on?

**Comment by xamanu** [comment]
I think it is worth it to check whether this is still the case on the new frontend we are implementing. I would wait a bit until we elaborate whether this has been solved or needs to be addressed, still.

**Comment by xamanu** [comment]
This needs to be rechecked with TM4.

**Comment by xamanu** [comment]
Pictures are not getting rendered anymore in the description text in TM4.

**Comment by xamanu** [comment]
Works well in TM4.
