### ISSUE TITLE
Translations in French displaying "&nbsp;"

### ISSUE THREAD

**Issue by pgiraud** [hotosm/tasking-manager#715]
<img width="419" alt="capture d ecran 2017-08-24 a 08 25 52" src="https://user-images.githubusercontent.com/319774/29652479-e6c50960-88a5-11e7-8b68-07c7a28a09c1.png">

A lot of translation in French show a "&nbsp;". Usually it's when there's a question mark. In French we indeed put a space before the double punctuations (exclamation, question, etc marks).

The translator on transifex may have added a non-blank space before them in the translated strings so that the line doesn't break before the punctuation.

It looks like it turns automatically to "&nbsp;" while displayed.

**Comment by ethan-nelson** [comment]
This seems to be fixed now that we updated the translation files...I think the last time they were uploaded, the encoding was not set properly. Please reopen if that is not the case.
