### ISSUE TITLE
Questions and Comments: no paging/scrolling

### ISSUE THREAD

**Issue by popelnuh** [hotosm/tasking-manager#717]
There is no paging or scrolling available for 'Questions and Comments' section on the project page.

The end user willl need to scroll the whole page to view the messages, 

![messagin_scrollbar](https://user-images.githubusercontent.com/18286711/29666544-9ab55d38-88d0-11e7-9b05-377236c605a9.PNG)

**Comment by willemarcel** [comment]
It doesn't apply to TM4.
