### ISSUE TITLE
Project Creation: Error Message alignment 

### ISSUE THREAD

**Issue by popelnuh** [hotosm/tasking-manager#721]
The error message is not well aligned. 
![projecct_creation_error_alignment](https://user-images.githubusercontent.com/18286711/29667149-427e5f68-88d3-11e7-9ec8-54cd3b462195.png)

To recreate:

1. Go to http://tm3.hotosm.org/admin/create-project
2. Click 'Draw'
3. Draw a self-intersecting shape.
4. Click next.

**Comment by Thrazadin** [comment]
Do you guys mind if I try to fix this one?

**Comment by Thrazadin** [comment]
I've submitted a pull request for this.

**Comment by ethan-nelson** [comment]
Fixed with #1194 thank you again @Thrazadin
