### ISSUE TITLE
Project Creation: Element overlapping menu

### ISSUE THREAD

**Issue by popelnuh** [hotosm/tasking-manager#724]
Project Creation: Step 2: Choose Tasks Type

(1) It is not cleat what the button for adding WMS/TMS does.

(2) The button element overlaps the drop-down menu,

![project_creation_element_over_menu](https://user-images.githubusercontent.com/18286711/29667746-77823872-88d5-11e7-90a6-2d26f17d6235.PNG)

**Comment by ethan-nelson** [comment]
It looks like this has been fixed. Thanks!
