### ISSUE TITLE
Messaging: Cannot open message without subject

### ISSUE THREAD

**Issue by popelnuh** [hotosm/tasking-manager#731]
Edit Project: Actions: Message All Contributors
(this is an edge case)
Front end validation for the message subject is no longer working. 

When sending a message without a subject, the users will not be able to view the message in their inbox. 

![message_no_subj](https://user-images.githubusercontent.com/18286711/29668386-dfdca8e2-88d7-11e7-95ba-69d4d25fbc80.PNG)

**Comment by LindaAlblas** [comment]
We can solve this by making the subject a required field.
