### ISSUE TITLE
Project Dashboard: Existing projects are not visible on the map

### ISSUE THREAD

**Issue by popelnuh** [hotosm/tasking-manager#732]
On the [admin project page,](http://tm3.hotosm.org/admin/dashboard), ticking 'Toggle the Area of Interest of existing projects' is not returning any layers.

Not sure if this functionality should be there. 

![toggle_view_is_not_working](https://user-images.githubusercontent.com/18286711/29668624-c7a07406-88d8-11e7-855b-555a9303734a.PNG)

**Comment by LindaAlblas** [comment]
It will only show projects you've created. I've tested this with my projects and it works fine.
