### ISSUE TITLE
Project Map

### ISSUE THREAD

**Issue by dalekunce** [hotosm/tasking-manager#735]
The project map should show the actual bbox of the tasks. Just showing the center point is actually not that helpful. Its not that many features to show on the map.

<img width="823" alt="screen shot 2017-08-24 at 9 48 40 pm" src="https://user-images.githubusercontent.com/1913857/29700005-305e19c0-8916-11e7-8d02-438266febb77.png">

**Comment by xamanu** [comment]
This seems to be fixed on the current version. @dalekunce can you confirm?

**Comment by xamanu** [comment]
We went through that, also in communication with our designers and came to the conclusion that the points are a good trade-off for the overview map. Showing polygons would give us hard times on performance and also design.
