### ISSUE TITLE
load test

### ISSUE THREAD

**Issue by dalekunce** [hotosm/tasking-manager#737]
ideally part of the CI during staging a test will run to ensure the tasking manager can support 1,000+ simultaneous users. This will ensure code changes don't have a negative impact on performance.

**Comment by ethan-nelson** [comment]
@dakotabenjamin do you have any input on possible implementation of this? Is there a service that does this? I imagine we probably need to define some workflow that the workers are following as part of the "test" if so.

**Comment by xamanu** [comment]
Not sure whether we can bring up the resources for load testing in each and every CI run. Probably it makes sense to automatize such a testing for a release candidate, however.

@arunasank, do you have some idea on how we could tackle this with the new infrastructure improvements?

**Comment by arunasank** [comment]
We have an internal load testing repository at HOT that has a template to set up a small instance to be able to run load tests.

I like the idea of integrating the load tests with the Circle CI. Here's what we can do:
* When we merge a PR into develop, we trigger a locust stack, and use the results of the locust stack to inform our merge with master. The load test can be customised to hit the right APIs, based on the locust test file we are customising. It can also be configured with a custom duration for the load tests.
* We don't trigger load tests when a merge is made with master.

What do you think?
