### ISSUE TITLE
black and white map tiles for easier reading.

### ISSUE THREAD

**Issue by dalekunce** [hotosm/tasking-manager#738]
the map tiles on the contribute page have a lot of color that competes with the colors of the task progress. I suggest moving to an easier to read map tile base like MapBox grey.

**Comment by xamanu** [comment]
Pinging @hotosm/major here, as we are going to redesign this part in the next couple of weeks.

**Comment by xamanu** [comment]
This has been a part of the redesign conversation. We ended up using another style but reviewed the colors for tasks.
