### ISSUE TITLE
Call to action on Contribute page is "below the fold"

### ISSUE THREAD

**Issue by dalekunce** [hotosm/tasking-manager#739]
On the contribute page you have to scroll down to see the call to action buttons for Map and Validate. These should be high on the page. Otherwise its one more action the user has to take potentially losing people and making training more difficult.

**Comment by xamanu** [comment]
This is currently being improved in the ongoing redesign with @hotosm/major: https://github.com/hotosm/projects/issues/24

**Comment by xamanu** [comment]
This has been reviewed and improved in the redesign for TM4.
