### ISSUE TITLE
News tab is blank

### ISSUE THREAD

**Issue by dalekunce** [hotosm/tasking-manager#740]
The news tab doesn't seem to have anything in it. What is the purpose of this tab, republish of HOT blog?

**Comment by IknowJoseph** [comment]
This looks to have been fixed by https://github.com/hotosm/tasking-manager/pull/708

However, I'd say that "News" doesn't fit with the page content of "What's new"

**Comment by bgirardot** [comment]
Hi, both of these are fixed in the develop branch. currently building to deploy on tasks-stage.hotosm.org in a few minutes.
