### ISSUE TITLE
map callout on project dashboard is misshapen

### ISSUE THREAD

**Issue by dalekunce** [hotosm/tasking-manager#741]
The map ballon on the project dashboard has issues. 

- [ ] doesn't display the full content
- [ ] often is not centered in the map pane
- [ ] is not fully shown 100% of the time
- [ ] cannot be closed all the time

<img width="1313" alt="screen shot 2017-08-24 at 10 10 50 pm" src="https://user-images.githubusercontent.com/1913857/29700425-41ed5dd8-8919-11e7-9d21-3058d53432a4.png">

**Comment by willemarcel** [comment]
Outdated TM3 issue
