### ISSUE TITLE
map on project dashboard needs actual tiles

### ISSUE THREAD

**Issue by dalekunce** [hotosm/tasking-manager#742]
Not actually showing the grid of the tasks with completed and/or validated tiles doesn't actually do any good to a project administrator. The current map in TM2 provides more information. The current map is useless, a project admin knows where the project is. Why not show more useful information.

<img width="1264" alt="screen shot 2017-08-24 at 10 14 15 pm" src="https://user-images.githubusercontent.com/1913857/29700484-c0e11120-8919-11e7-8d0b-3bf57a7a0ed4.png">

**Comment by xamanu** [comment]
Is this still an issue, @dalekunce?

**Comment by willemarcel** [comment]
TM3 related, so closing.
