### ISSUE TITLE
Chat box for users to ask for help

### ISSUE THREAD

**Issue by awisemanapple** [hotosm/tasking-manager#750]
This was discussed at the TM chat a while ago I think, but it would be great to add in a chat box so people could ask for help on tasks -- I've heard of this issue many times during mapathons or just wanting to get more help from somebody knowledgeable. It could be linked to the HOT Slack channel. Something like https://chatlio.com maybe? I think @dalekunce had an open source one too

**Comment by bgirardot** [comment]
There is now a "Questions and Comments" tab on every project that was meant to address this issue. Along with a link to address the question or comment to the project manager.

Adding in some sort of live chat would still be a good idea as well, but hopefully using the system built into the new Tasking Manager will help address a good percentage of questions.

We did specifically set up a slack channel for mapper help, but embedding slack in a web page is not as easy as we would have liked. The quickest path to embedded live chat would be to probably look at a different comms platform.

**Comment by ethan-nelson** [comment]
Is the questions and comments sufficient to solve this, Andrew? I've also noticed since the launch we've had quite a few postings on the mapper support mailing group.

**Comment by awisemanapple** [comment]
@ethan-nelson I think that covers it! Thanks!
