### ISSUE TITLE
Limit multi task validation to experienced mappers

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#754]
We now have the ability to validate multiple tasks at once. However, as was demonstrated recently, very inexperienced mappers can sometimes attempt the validation process.

We might want to limit the folks who can checkout multiple tasks to folks who are experienced.

There are two ways to do this in the new Tasking Manager, require a certain mapper experience level (based on osm changesets) or limit that functionality to experienced validators (a setting on users now available).

**Comment by ethan-nelson** [comment]
Note that https://github.com/hotosm/tasking-manager/wiki/Restricting-features-to-certain-users now contains some information about implementing mapping level permissions on features within the TM--may be useful for this request.

**Comment by xamanu** [comment]
I would attach this to the "Expert mode" and to the roles Validator, Project Manager and Admin. @russdeffner how does this fit best in regular use cases?

**Comment by russdeffner** [comment]
I would think it should be restricted to the Validator role; i.e. usually we aren't giving validator role to beginners, or even intermediate, without reason. I guess additionally, toggling on/off with Expert mode could be a way to 'hide' it from inexperienced validators on unrestricted validator role projects?

**Comment by russdeffner** [comment]
This is now 'rectified' with the ability to limit validation to only Intermediate and Advanced users.

**Comment by bopercival-hot** [comment]
Closed as per comment above.
