### ISSUE TITLE
Strange task selection behavior - arbitrary tasks

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#756]
With this project: http://tm3.hotosm.org/project/3357

In Chrome when clicking a task, it makes the task disappear. When I move the map the task re-appears.

But when clicking off a task to select it. It selects the entire project area, the part outlined in blue, as if it were a task that can be selected, it even highlights it yellow (you might have to move the map to see it get outlined in yellow).

When I click outside of the blue outline, about 1/2 of the time it de-selects the project area, and 1/2 of the time it seems to do nothing.

Any idea what is going on @LindaAlblas ?

(I have requested the source file for the project creation so you can test it locally)

![tm3-select-task-oddness](https://user-images.githubusercontent.com/265831/29798148-9224dbe2-8c5b-11e7-8440-61f6decc3aed.gif)

**Comment by RebeccaFirthy** [comment]
i just tried with about 6 squares in Chrome, and it worked fine for me for mapping. However, I could recreate the 'disappearing' thing Blake demonstrated by zooming in and out quite a few times, and then clicking around. If I didn't zoom, this didn't happen.

**Comment by LindaAlblas** [comment]
I can recreate it here. Is this a project that was created in TM2 and moved across to TM3 or was it created with TM3?

**Comment by pgiraud** [comment]
This project was imported from TM2. http://tasks.hotosm.org/project/3357#task/2722

It looks like the project area is selectable and taken into account as if it was a task.

**Comment by pgiraud** [comment]
Side note: in TM2 when a project with arbitrary tasks was created a buffer was added to the project area. It may (or may not) be useful in some cases. Is there any reason why this feature hasn't been kept?

**Comment by bgirardot** [comment]
@LindaAlblas Yes, as Pierre says, created in tm2 and imported to tm3.

@pgiraud I do not think we intentionally excluded the buffer area. I always thought that was just decoration or a by product of how the project was created.  What was it's original purpose?

Do you think we still need the buffer?

**Comment by pgiraud** [comment]
I just can't remember why I did this actually. I tried to look at the commit history, but couldn't find anything obvious.
I don't think we really need this.
Re-creating the project areas when importing projects (with arbitrary taks) from v2 would help I think.

Preventing OL3 to select elements other than actual tasks would also make sense.

**Comment by bgirardot** [comment]
@LindaAlblas @hunt3ri @pgiraud 

This project seems to work much much better if I just create it from scratch.  Please see:
http://tm3.hotosm.org/project/3454

It looks like this might be related to the buffer around the project really making things work oddly.

**Comment by bgirardot** [comment]
@LindaAlblas @hunt3ri Hi Linda, Iain, I was wondering if you had a chance to look at this further yet.

**Comment by bgirardot** [comment]
This was fixed long ago, cheers!
