### ISSUE TITLE
LinkedIn Share Functionality

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#778]
The LinkedIn Share functionality seems to not be ideal. The 'link' appears just as "tm3.hotosm.org" but it actually (in my case) was to the task (i.e. http://tm3.hotosm.org/project/2288?task=245). First, I would suggest that if a share originates with a task selected, truncate to the project and display the entire URL.  Second, maybe this is normal/expected by regular users of LinkedIn but I didn't immediately know the difference between just posting and 'share an update' option, maybe there's a way to make that more clear.  Last, it may be best to limit the 'title' of the post as it gets cut off and doesn't seem to be any way to view the whole thing.
![tm3linkedin](https://user-images.githubusercontent.com/6763645/29935871-87c3ceae-8e3d-11e7-81e8-88111439a42c.PNG)

**Comment by russdeffner** [comment]
Oh, one other thing, similar to #776 it would be better to display the project description vs. TM info.

**Comment by willemarcel** [comment]
LinkedIn share is working on the better way possible.
