### ISSUE TITLE
Contact button with no action connected

### ISSUE THREAD

**Issue by michael63-osm** [hotosm/tasking-manager#779]
The "contact us" button targeted at future sponsors in the lower right corner of http://tm3.hotosm.org/about does not have any action attached. Looks as if we would not welcome sponsors.

**Comment by bgirardot** [comment]
fixed, thank you very much @michael63-osm

**Comment by michael63-osm** [comment]
Just had a look at http://tasks-stage.hotosm.org/about

The action for the button is fixed but the button does no longer look like a button. Can we let it stand out somewhat better?

**Comment by bgirardot** [comment]
I think it is going to have to stay the way it is for now.
