### ISSUE TITLE
Translation probably needs updated sources

### ISSUE THREAD

**Issue by michael63-osm** [hotosm/tasking-manager#781]
Looking at the German interface I see lots of untranslated strings. But https://www.transifex.com/hotosm/tasking-manager-3/ tells me that all strings have been translated.

**Comment by bgirardot** [comment]
Yes, this correct, the initial application was translated, but since then there have been a number of small adjustments to text based on feedback. We will need to update the sources for transifex and push them up to get the new strings translated.

**Comment by arun-aji-balaji** [comment]
There is no resource for Tamil strings

**Comment by Andygol** [comment]
It would be great when transifex source was updated for the further translation

**Comment by ethan-nelson** [comment]
@arun-aji-balaji I have added Tamil as a language on transifex and is now ready for translating https://www.transifex.com/hotosm/tasking-manager-3/language/ta/.

For the others, many languages were updated two months ago (https://github.com/hotosm/tasking-manager/tree/develop/client/locale). I will look into the ones that weren't.

**Comment by ethan-nelson** [comment]
I'm closing this for now as we have a few tickets open regarding translation and the general idea is it's always in progress. The process of updating strings is now a bit more integrated into our deployment workflow, so be sure to check out Transifex for translating and reviewing if you see most strings out of date.
