### ISSUE TITLE
streamline text when creating a private project 

### ISSUE THREAD

**Issue by michael63-osm** [hotosm/tasking-manager#783]
The explanation near the checkbox says: 
> In order for the users name to be available to add to the Allowed Users list - they first must visit the URL for this installation of OSM Tasking Manager and Authorize access to their OpenStreetMap account.

This might be shortened to something like
> Before a user name can be added to the Allowed Users list this user must first login to this installation of OSM Tasking Manager.

Might be misleading for translators as well - the current German localization reads that users first have to visit the URL in order to install the tasking manager...

**Comment by bgirardot** [comment]
fixed, thank you very much @michael63-osm
