### ISSUE TITLE
Duplicate URL method of getting geojsons from TM3

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#789]
@ethan-nelson This is a good place to point out, in TM3 you can NOT get the aoi and tasks geojson easily now
[5:55 PM] 
it would be good to at least duplicate the below url schemes so it works exactly as tm2, but also add some simple ui to get them somewhere too. url manipution is great, but you know, not friendly ui

/project/nnnn.json = aoi only, not actual task squares

[5:51 PM] 
smit1678 i’ve just been hitting the project.json endpoint to download
[5:52 PM] 
ah ok
[5:52 PM] 
blake_hot /project/nnnn/tasks.json = the actual task boundaries as the project was actually created (larger than aoi)

[5:52 PM] 
I focus on tasks.json

[5:53 PM] 
because I load them in JOSM and trace the edge, the go out to next area so the projects fit like tetris objects

[5:53 PM] 
aoi is less interesting as I know we mapped more area with our boxes stair step.

**Comment by ethan-nelson** [comment]
Fixed in #790 and #934
