### ISSUE TITLE
User profile - stats, number of mapped/validated tasks in project list is incorrect

### ISSUE THREAD

**Issue by rwst** [hotosm/tasking-manager#792]
The **total** number of mapped/validated tasks displayed on top looks right. The project-specific numbers however are way off. Most validated numbers are zero and don't add up to the total by far. Also the mapped numbers look too small.

**Comment by majkaz** [comment]
Even the list of the projects on the profile page is wrong.
For me, only a part of the project list is actually there. The whole Iran-Iraq Earthquake 2017 is completely missing (not in projects, not in maps), some other projects I have participated are missing too. And yes, the numbers for individual projects mentioned there are wrong as well.

**Comment by bgirardot** [comment]
Just for reference, @majkaz has contributed to https://tasks.hotosm.org/project/3833 but that project does not show up in their user profile page.

**Comment by SDavies-OSM** [comment]
Would love this to be bumped up the priority list a bit. The user stats are like a list of personal achievements, this is like a recognition of work done. Human psychology means people being able to see their totals increasing will help inspire them to do more. Conversely, if their contributions aren't showing up, they may get dispirited.

**Comment by majkaz** [comment]
@bgirardot 
I have just noticed additional difference - the number of tasks i can see for myself in one project is different on the user profile (8) and in the project activity table (11) - see attached screenshots.

As unconnected note, the validated count shows only the tasks marked as validated. It might be a good idea to show the invalidated count in the project activity tab as well (in this project, I would see my activity as validator as suspect by the numbers only, because I have invalidated quite a number of tasks). High number of invalidated tasks compared to validated ones might indicate problems - with validator/users/project. 

![2017-12-14_102440](https://user-images.githubusercontent.com/23097386/33985057-b22ea410-e0b9-11e7-8fc0-622a5a867009.png)
![2017-12-14_102510](https://user-images.githubusercontent.com/23097386/33985058-b2944054-e0b9-11e7-9610-f896b9d874d4.png)

**Comment by bgirardot** [comment]
Additional information on this.

On the user's profile page, the listing of projects they have contributed to, the number of tasks mapped in a project listing is actually showing the number of tasks they have mapped that are not yet validated. In other words that individual listing is not showing the number of tasks that a user mapped, but only the number of unvalidated tasks the user has in that project.

You can see below that it shows 0 when in actually that user has mapped 4 tasks, which are all validated.

![2018-06-08_19h22_04](https://user-images.githubusercontent.com/265831/41171778-082b7dd4-6b52-11e8-8af6-1a31fe9a7030.png)

**Comment by bgirardot** [comment]
Additional information on this.

The number of tasks validated is just wrong. In the below project listing, 4396 was added to my list when I validated some task squares, I have not mapped any, only validated. You can see it got added to my list of projects, but the number of tasks validated is at 0.

![2018-06-08_19h22_04](https://user-images.githubusercontent.com/265831/41171890-58a2c15a-6b52-11e8-9f93-fd0c3065d06b.png)

**Comment by daisygrubber** [comment]
Can I add my vote for this to be addressed? I had someone take strong exception to one of my validating decisions and it's hard to look credible when it looks like you've never done any validating before.

**Comment by bgirardot** [comment]
The OSM changesets and time mapping hopefully help with credibility, but yes, for sure we need to get this fixed. Thank you for your input on the priority.

@daisygrubber Sorry to hear about the ... strong exception. You can always forward or contact the mapper-support@hotosm.org email address too, that has a lot of experienced folks who can help in situations like that. It is not private, but as I said, lots of experienced folks. And I am happy to follow up on anything related to that. We really shouldn't be having folks take strong exception to anything as nothing is really that big of a deal. Either there is a simple right or wrong answer, or there is not a simple right or wrong answer and then we all just take it as interesting and note people can do it different ways for different reasons or in different contexts, and perhaps there is a preference unique to the mapping project, in which case we should try and do it that way.

info@hotosm.org is private, and you can always contact that email address for help with anything.

Thank you for all your help @daisygrubber !
