### ISSUE TITLE
Add Bing imagery layer to TM3 map views

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#793]
Hi Linda,

We have the key from microsoft,

> AioPAglzP9Qw32KN17dOkKYRdSlzj7W5kIQY6zct_UCmGc0WRxAh-QeiRBpRUgrv

This is the page about how to do it in OL3:

https://openlayersbook.github.io/ch04-interacting-with-raster-data-source/example-04.html

And this is the place in the code I think it needs to go, I am not 100% sure, but I think:
https://github.com/hotosm/tasking-manager/blob/develop/client/taskingmanager.config.json

Could you add that in at your earliest convenience please?
 cheer
blake

**Comment by dcfrankland** [comment]
Hi Blake - just to inform that Linda is away training this week and committed to various other projects next week. If someone else is able to take this on then I would suggest doing so. 

Thanks,
Dave
