### ISSUE TITLE
Re-add video embed code

### ISSUE THREAD

**Issue by aawiseman** [hotosm/tasking-manager#795]
The Tasking Manager 2 had an embed video functionality, which was added to Markdown here: https://github.com/hotosm/osm-tasking-manager2/pull/739 

I think TM3 should have video embed functionality too so that organizers can include tutorial videos to improve the quality of map data.

**Comment by aawiseman** [comment]
Any luck with this? There are a lot of broken links from tasks that were brought over

**Comment by bgirardot** [comment]
Hi Andrew, no, no progress on this that I know of. There is a work around, I thought I shared that with you before, I will try and find it again.

**Comment by bgirardot** [comment]
Also, thank you to @aawiseman who points out in the TM2 code where the video support code is:

https://github.com/hotosm/osm-tasking-manager2/compare/2.11.0...2.12.0

Which should hopefully make it easier to add to tm3.

**Comment by bgirardot** [comment]
@aawiseman Ya, it is not pretty and it does not help existing video automatically, but the standard youtube embed code with an iframe seems to work. I just copy pasted the embed code of YT and put it in the instructions.

https://tasks-stage.hotosm.org/project/3635

**Comment by xamanu** [comment]
TM4 allows markdown including embedding videos.
