### ISSUE TITLE
Message users when reaching new levels or number of changesets; encourage validation

### ISSUE THREAD

**Issue by aawiseman** [hotosm/tasking-manager#796]
I think it would be good to contact users when they reach certain mapping levels like intermediate, expert etc. and also contact them when they reach a certain number of changesets or levels to suggest they try validating. That might encourage more people to validate.

**Comment by aawiseman** [comment]
Hey, just wanted to check on this @bgirardot @ethan-nelson . Thanks. Think it would be a good way to get people to validate and get more involved.

**Comment by ethan-nelson** [comment]
Hey Andrew, I may have someone working on this as an intro to TM dev. Otherwise, since it has been sitting on my to-do list for a while, I will knock it out.

**Comment by ramyaragupathy** [comment]
@ethan-nelson @bgirardot - I'm going to give this a try this week as a starter task

**Comment by ramyaragupathy** [comment]
This is done through #1483
