### ISSUE TITLE
Allow sorting of projects by last update time in explore projects page

### ISSUE THREAD

**Issue by verdy-p** [hotosm/tasking-manager#803]
I note that in TM3 we can no longer **sort the list of projects** by creation date, or by last update time, we only see them sorted by priority and then by decreasing id (last created ones first) (modifié)

This makes difficult to find newly created tasks that have the incorrect priority.

In TM2, we have the combobox to select the sort order, and it is very convenient to manage projects.

The choices are:
- (by default) sort by priority (decreasing), then by creation date with most recent first i.e. by decreasing project number)
- sort by creation date with most recent first (highest id first) - very useful to manage projects or when adding new ones as drafts (difficult to locate withe the default sort by priority)
- sort by last update time (useful sometimes to detect recent changes in descriptions/goals/imagery and perform some checks on existing completed tasks)

This sort order should be independant of the project status selected in filters.

**Comment by willemarcel** [comment]
Sorting by priority and creation data is already possible. Renaming the issue to match the current status.

**Comment by bopercival-hot** [comment]
resolved and closed
