### ISSUE TITLE
Make pagination links buttons

### ISSUE THREAD

**Issue by smit1678** [hotosm/tasking-manager#808]
Small usability issue. Helpful to have a pointer hand when mousing over the pagination links. 

![tm-mouseover](https://user-images.githubusercontent.com/796838/31701222-af37dea4-b3c6-11e7-8518-9dda02d0ba0d.gif)

**Comment by pgiraud** [comment]
I missed that one when I worked on this PR https://github.com/hotosm/tasking-manager/pull/752

**Comment by verdy-p** [comment]
I vote for it !

**Comment by verdy-p** [comment]
And may be the list could be just refilling automatically when we reach the bottom, or could be refilled at bottom by clicking on a "Load more" button.

As each project is a now in a tile with constant width and height, these tiles should flow as inline boxes automatically and fill up the available width on screen (not necessarily two columns, may only one on smartphones in portrait mode, may be more on large screens...)
But it was designed here only as a table with two columns (not fun for mobile phone users).

**Comment by xamanu** [comment]
Done for TM4.
