### ISSUE TITLE
Redirect tm3 subdomain to tasks

### ISSUE THREAD

**Issue by smit1678** [hotosm/tasking-manager#809]
Once live, we need to set up a redirect `tm3.hotosm.org` ---> `tasks.hotosm.org`. Along with the main url, there are a few urls out there with tm3 subdomain: 

* http://tm3.hotosm.org/what-is-new
* http://tm3.hotosm.org/faq

**Comment by ethan-nelson** [comment]
Per Slack conversation, plus testing, this is implemented.
