### ISSUE TITLE
Make maps more visible, closer to project name

### ISSUE THREAD

**Issue by cgiovando** [hotosm/tasking-manager#810]
In TM2 the map showing progress is right next to the project title, which makes is easier to understand the area to be mapped and gives an idea of what's going on. It also helps when taking screenshots for articles and other media:

![screen shot 2017-10-18 at 17 10 59](https://user-images.githubusercontent.com/10201533/31726821-3e3de2a4-b428-11e7-850b-5689aaddb639.jpg)

In the current TM3 layout, each map is one page down from the title and the main project description. Scrolling down to the map doesn't show the project title anymore:

![screen shot 2017-10-18 at 17 11 11](https://user-images.githubusercontent.com/10201533/31726887-677c02ea-b428-11e7-8712-da68b34686ef.jpg)

This could be improved by bringing the map up closer to the title section, or change the title to a fixed element in the page when scrolling (same as the header and top menu).

**Comment by verdy-p** [comment]
Fully agree ! the map is too low on page, we need to scroll down the page and most often when scrolling it, the mouse will start hovering the map and continuing to scroll will instead zoom out on the map.

That map should be just at top, to the right of project description (and there's ample margin most often on PC, I don't understand why you restrict the width so much with very wide margins, when you can perfectly use CSS to put the map on right where there's enough space and float the project description to the left if it has a minimum width (a minimum of 18em is suitable for a column of text)

I think there are enough example of flexible layouts on the web that allow pages to reflow correctly depending on screen sizes (or screen orientation: portrait or landscape) without wasting screen space or packing too many things horizontally: don't use HTML tables but floatting blocks)

**Comment by cgiovando** [comment]
Thanks for the detailed analysis @verdy-p - it sounds like you may have a PR ready to submit? ;)

**Comment by xamanu** [comment]
This is currently being improved with the redesign together with @hotosm/major in https://github.com/hotosm/projects/issues/24

**Comment by xamanu** [comment]
This has been improved and implemented as suggested here with TM4.
