### ISSUE TITLE
TM3 bug: impossible to see all projects (drafted, or archived are now invisible) in list of projects

### ISSUE THREAD

**Issue by verdy-p** [hotosm/tasking-manager#814]
We can no longer see the list of all projects (including drafts and archived)
We only see those that are published.

This was in TM2, making the admisnitration of projects now difficult if we can't find them easily: a draft is created, but will be published later, but how to see it? A project completes, but we want to edit some properties (e.g. post a link to download data), or just this archival is temporary to suspend a project that will continue later (e.g. after making instruction changes, or changing and testing a better imagery source).
The project can then be forgotten and will be difficult to locate.

Note how some users have already had difficulties to create projects that they did not fill completely (multiple attempts were they left the draft half-completed, sometimes completely empty, or duplicated by error): we need a way to maintain the list of active projects or modify some of them to put a lionk going to another project or explaning that it is currently suspended.

The status of projects is then likely to be changed at any time by project admins but we need to see the whole set of projects when we are logged in as project admins.

So please restore that functionality !

**Comment by bgirardot** [comment]
We need to clone the user contributor page and make it by campaign and/or organization tag and fully public instead.

**Comment by verdy-p** [comment]
Solving bug #814 will NOT solve this #815 bug, they are totally indedependant of each other. Reopen #815 and see my comment, you've not understood the issue correctly !

**Comment by alekno** [comment]
the problem is in 
tasking-manager/client/app/services/project.service.js 
tasking-manager/client/app/admin/dashboard/dashboard.controller.js 

function getProjects() needs an equivalent for global tasks
