### ISSUE TITLE
Disable OpenLayers zoom when page scrolling

### ISSUE THREAD

**Issue by cgiovando** [hotosm/tasking-manager#816]
This may not apply to other computers/OS/trackpads, but on a Macbook when using two fingers to scroll down a page, if the cursor goes over one of the (OpenLayers) maps, then the default behavior is zoom in/out and the scrolling doesn't work anymore.

Here's a example of the suggested improved behavior: https://coordination.openaerialmap.org/#/imagery-search (although that's a Leaflet map...)

A possible fix? `https://gis.stackexchange.com/questions/136782/how-do-i-disable-mouse-scroll-zoom-in-openlayers-3`

Or maybe just `http://openlayers.org/en/latest/apidoc/ol.interaction.Interaction.html#setActive` ?

**Comment by verdy-p** [comment]
similar to the remark made in bug 810: the map is no nologer visible immediately without scrolling down, before we did not need to scroll, we just  clicked on buttons at top to select tabs, and the map was still zoomable.
Now when we scroll down to see the map, we reach the map area and this zooms out, if we want to scroll up gain to reach the top of page, the page no longer scoll but we get a zoom in.

There was no such problem in TM2, but TM3 wants to display everything at once on the same page. I don't think this is a good choice, it was much faster to navigate with TM2 tabs without scrolling needed most of the time and the map could still be zoomed in/out easily.

One suggestion: do not allow zooming out with the mouse scroll below the initial zoom level, instead continue scrolling down the page.

And do not allow zooming in an area that is not part of an tile. If zooming in has already reached the maximum zoom level, do not zoom but fallback to scroll up the page instead.

**Comment by xamanu** [comment]
This has been addressed in TM4. As per design decision on the project overview zoom on scrolling is being disabled, so people can reach the content below. On the task selection page, zooming is enabled as a desired feature.
