### ISSUE TITLE
TM3: project page layout to improve: refine tab contents, group buttons

### ISSUE THREAD

**Issue by verdy-p** [hotosm/tasking-manager#817]
In TM3, the two tabs "Map" and "Validate" should be only one the only difference being the action buttons we can click depending on the state of the currently selected tile. These buttons should be visible/hidden on the same tab depending on the tile state (unmapped, done, or validated). We should not have to see error messages when we are on the wrong tab !

And please put the top of the page (the long description) and the bottom table of project properties in one of these selectable tabs: put the tabs selector at top, just below the missing project status (archived/drafted), the priority (urgent/high/medium/low), the missing completion levels (% done/% validated) and the title (currently below). Keep the map of tiles on the right (without having to scroll down), and use tabs to select what to show on the left.

And please group the two buttons "Edit project" and "Share" together to the right (add a third button "..." for possibly more actions in a menu) instead of putting "Edit project" below the title (this wastes vertical space for a single button).

Please remove (or reduce significantly) the unnecessarily large white margin at the top above the title (this will also allow the map to move up to avoid having to scroll down the page).

**Comment by xamanu** [comment]
Done in TM4. Thanks.
