### ISSUE TITLE
Project Dashboard Not Available

### ISSUE THREAD

**Issue by giblet22** [hotosm/tasking-manager#818]
When I go to open my project dashboard, none of my projects are there, just `An error occurred.`

**Comment by giblet22** [comment]
<img width="1260" alt="screen shot 2017-10-18 at 5 09 36 pm" src="https://user-images.githubusercontent.com/7945333/31742884-2aff4314-b427-11e7-83e5-da6c27dd637a.png">

**Comment by giblet22** [comment]
This is my project dashboard under my username, then `Project Dashboard`.

**Comment by cgiovando** [comment]
Can anyone else please check if this affects other users? My dashboard seems to be working fine, so I can't reproduce and debug...  @smit1678 @russdeffner ?

![screen shot 2017-10-18 at 23 11 30](https://user-images.githubusercontent.com/10201533/31743079-159fcaba-b45a-11e7-9694-8c877dea45e8.jpg)

**Comment by ethan-nelson** [comment]
Are there any error messages in the browser web console @giblet22 ?

**Comment by ethan-nelson** [comment]
Just as another data point (and to rule out it being an issue with someone who has created no projects), it seems to work okay on mine. 

![tm3dashboard](https://user-images.githubusercontent.com/8998918/31743594-48780f8a-b421-11e7-91f1-17affaa8cec0.png)

**Comment by giblet22** [comment]
@ethan-nelson In the console I get `/api/v1/admin/my-projects   Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)`

**Comment by giblet22** [comment]
@ethan-nelson @cgiovando Can confirm that new projects I've made in TM3 also do not show up.

**Comment by bgirardot** [comment]
@giblet22 Is this still an issue

**Comment by giblet22** [comment]
@bgirardot nope, looks like recent updates have fixed it. Thanks!

**Comment by giblet22** [comment]
@bgirardot Sorry I looked at the wrong screen. Still have the same issue.

**Comment by fitoria** [comment]
could not reproduce with clean db or populated db.
