### ISSUE TITLE
Invalidated tasks marked as Mapped in new HOT Tasking Manager

### ISSUE THREAD

**Issue by marxin** [hotosm/tasking-manager#819]
Example can be seen here:
http://tasks.hotosm.org/project/3357?task=2296

**Comment by marxin** [comment]
I'm gently reminding this as I consider it as quite serious. Thanks.

**Comment by marxin** [comment]
There's script that can fix that via JSON API:
https://github.com/marxin/script-misc/blob/master/hotosm-fix-invalidated.py

**Comment by pgiraud** [comment]
hi @marxin 
I tend to agree with you that invalidated tasks should not be considered as mapped. It was not the case in TM2.
Thanks for your the feedback. We will give it a look as soon as possible. And thanks for script.

**Comment by xamanu** [comment]
Related to #1460

**Comment by bopercival-hot** [comment]
archived & closed
