### ISSUE TITLE
TM3: edit project > metadata > types of mapping: missing "residential areas"

### ISSUE THREAD

**Issue by verdy-p** [hotosm/tasking-manager#821]
TM3 edit project > metadata > types of mapping
missing item: "residential areas" (very common in HOT where buildings are not immediate goals, and road network construction is still requested). For now I checked "other" (this is not really the same as "landuse" which is more general land cover)

**Comment by bopercival-hot** [comment]
archived in case anyone using tm3 wants to pick this up
