### ISSUE TITLE
Some Markdown no longer works in project instructions

### ISSUE THREAD

**Issue by verdy-p** [hotosm/tasking-manager#822]
Markdown does not work in project instructions for links with the syntax `[text](URL)`.
Links are used in instructions for example to refer to another project in TM.

The edit form suggests using Markdown, but visibly markdown is no longer parsed in instructions.

Markdown only works in project descriptions.

Note: in the edit form, the term "Markdown" display below the input field should link to https://help.github.com/articles/basic-writing-and-formatting-syntax or similar guide, in a new window/tab, or when clicked, should open a panel with small summary of the syntax supported.

This is a regression bug.

**Comment by verdy-p** [comment]
Apparently this occurs when Markdown is used within sections of text between ``backquotes``. In TM2 this was displayed using a monospaced font and in a distinctive box with colored background (to emphasize the text in that box).

In TM3, backquotes are just discarded (double backquotes are rendered literally as single backquotes), and text is displayed using standard font and markup is disabled within that text. This makes links very difficult to read and not clickable.

**Comment by ethan-nelson** [comment]
This should be fixed with #1209 on stage and soon to be deployed to live. Please reopen if it doesn't fix it.
