### ISSUE TITLE
TM3: "Per Task instructions" are not currently displayed

### ISSUE THREAD

**Issue by verdy-p** [hotosm/tasking-manager#823]
"Per Task instructions" are not currently displayed in TM when we select a tile to map or validate.

But I've always wondered if these were really useful where they should be in general instructions for the project.

This is a minor regression (probably forgot to implement it).

**Comment by bgirardot** [comment]
Per task instructions work in regular projects that have the grid created and do not trim to AoI.

For example: https://tasks.hotosm.org/project/3420

There is still an outstanding issue with them, but I can not find it it in the list of issues unfortunately.
