### ISSUE TITLE
Inbox Messaging

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#824]
Would be much easier to have a way to directly reply from your inbox versus having to navigate back to the task/project where then you may have to select it for mapping/validating before finally able to reply to the comment.

**Comment by OttoROSM** [comment]
Hi, made the following comment at issue #635:
Came here to report this. At least do not send a standardized message to the e-mail address that there is a message in the tasking manager. Especially when the message in the Tasking Manager is a standard message where someone validated a tile.

Typically I would map multiple tiles after each other, so when someone else validates 10 in a row, I get 10 e-mails saying there is a message in the tasking manager for me.
Then I go to the tasking manager and need to open 10 times a similar message saying that my tile was validated and I need to keep up the good work. Then click delete for each message and confirm I want to delete each message and then go back to my e-mail inbox and delete 10 e-mails.

Rather I would receive the message directly in my inbox, or receive a summary report saying, 10 tiles were validated, or you have 10 messages in the tasking manager.

Basically unless someone made a specific comment, I am fine with getting a simpel statistic saying 10/10 tiles you mapped were validated.

**Comment by bgirardot** [comment]
The message system is not really intended to be a private message system, it is for public comments and questions.

The best fix is to make the message box available on a task even when it is not checked out for mapping or validation as required at the moment.

But I really do not want to have a private message system, that just leads to more overhead for admins. Nice public comments and questions about mapping is what the "message" system is intended to be used for.

**Comment by russdeffner** [comment]
Yes, I agree - wasn't suggesting a private message just the ability to hit a 'reply button' and either type message from inbox and it appears on project/task or you get re-directed to the project/task so you can reply.  Caught me and there was a recent tweet where the user was confused of how to actually reply (i.e. great, I got a message, now what?)

**Comment by bgirardot** [comment]
ya, if there was a comment box on a task all the time it would be more obvious how to reply. at the moment there is no good way really. you either have to check out the task for mapping or validation, which does not work well because it is probably already marked mapped and it might require validator status to check out for validation. I have taken to just replying via the q and a tab as that always has a comment box, but is obviously not a great solution.

**Comment by russdeffner** [comment]
Yes, more concerned about the new user experience - mine was pretty much exactly this: https://twitter.com/sepzilla/status/964702122955567104

**Comment by xamanu** [comment]
This is related to the ongoing redesign with @hotosm/major.

**Comment by xamanu** [comment]
Connected to this #1644

**Comment by xamanu** [comment]
Unfortunately this was descoped from the redesign. Keeping it open for later.

**Comment by bopercival-hot** [comment]
pre2019 - closed
