### ISSUE TITLE
No OSM data opens in JOSM when trying to validate multiple tiles simultaneously.

### ISSUE THREAD

**Issue by pedrito1414** [hotosm/tasking-manager#827]
Trying out validation of multiple tiles simultaneously (chosen by drawing polygon) but no OSM data is opening in JOSM, just imagery and the task boundaries.

![image](https://user-images.githubusercontent.com/8447248/31760643-448c6c7c-b4ad-11e7-82dd-a640e806c8d6.png)

![image](https://user-images.githubusercontent.com/8447248/31760659-51fa09e6-b4ad-11e7-8d69-bde954fe91d4.png)

**Comment by cgiovando** [comment]
@bgirardot explained this behavior here https://youtu.be/yLTubyUePG8?t=645

Feel free to close this issue, or propose a different approach.

Thanks!

**Comment by pedrito1414** [comment]
Thanks...
