### ISSUE TITLE
Completion stats appear to be borked

### ISSUE THREAD

**Issue by Boggedy** [hotosm/tasking-manager#829]
Prior to cutover this task was at 80% vaild and has been worked on continually since.

http://tasks.hotosm.org/project/3643/dashboard

Since cutover to TM3 the validation counter appears frozen @ 77%

Since cutover to TM3  some tasks have been invalidated from time to time and the task completion metric should therefore vary from time to time between 99% and 100% depending. It is nailed on 100% despite some tasks being invalidated right now

**Comment by verdy-p** [comment]
I see only 100%/99%, so it's not frozen.
You've probably got a proxy caching issue on your side (possibly still using the former server address even if the DNS was changed so the domain name go to the new server instance after the version switch).

**Comment by ethan-nelson** [comment]
This should be fixed now based on #913 and #1123. Please reopen if you continue to see issues.

**Comment by ethan-nelson** [comment]
Nevermind, I see validation is stuck at 99%. This could be a corner case of a bad imagery task that was validated, then invalidated. It will require some more DB digging.

**Comment by xamanu** [comment]
Related to #1460

**Comment by xamanu** [comment]
Closed in favour of the follow up issue #1527
