### ISSUE TITLE
automatic switch between `map` and `validate` tabs

### ISSUE THREAD

**Issue by pgiraud** [hotosm/tasking-manager#831]
I think this is small usability issue since it took me some seconds to understand
Imagine the following use case:
 - open a project page,
 - `instructions` is selected,
 - click on map to select a task which is ready for validation (marked as mapped),
 - `validate` tab is automatically selected,
 - click on the map to select a `ready` task,
 - message tells you that the task is `not in a state that allows validation`.

It can happen the other way as well.

This may not be an issue but it took me a while to understand that I had to manually switch to `mapping` tab.

2 options:
 - auto switch to the more relevant tab,
 - add a link (or message) to invite user to switch tab.

**Comment by Boggedy** [comment]
another " the task is not in a state that allows validation." condition is where you marked a tile done. You cannot revisit that tile in any way. 

I believe this is to prevent users from validating their own work but what if they clicked something done and then remembered to add something they forgot afterwards. ?

**Comment by harry-wood** [comment]
It's definitely an area where it behaves differently from the old tasking manager. I guess it's more designed to keep you in one mode, so you're clearly either mapping or validating.

I think the message could be clearer, more friendly, and more nuanced though. Currently we say 
*"The selected task is not in a state that allows mapping."* or *"The selected task is not in a state that allows validating."*

Instead we could say these different messages (They feel more like information and less like an error):

When you're mapping: *"This task is already mapped"* or *"This task is already mapped and validated"*

When you're validating *"This task is already validated"* or *"This task hasn't been mapped yet"*

...and with that last one, the word "mapped" could be a link to the map tab.

**Comment by verdy-p** [comment]
See also bug #817

**Comment by ethan-nelson** [comment]
I would suggest for any Hacktoberfest participants the following:

If the map tab is selected and the task state is in one that only allows validating, add a button to switch to validation mode as something like:

![buttonmockup](https://user-images.githubusercontent.com/8998918/46648631-c6e95900-cb4a-11e8-9dcc-be370534abd5.png)

And similarly for if a task state is in one that only allows mapping to switch to mapping mode.

**Comment by xamanu** [comment]
This last suggestion has been implemented in TM4.
