### ISSUE TITLE
impossible to login after OSM username change

### ISSUE THREAD

**Issue by pgiraud** [hotosm/tasking-manager#832]
In OSM, it's possible to change its username (osm_id doesn't change).
It looks like TM3 doesn't handle username changes and it's impossible to login the tasking manager after a username change.
I fixed the problem in TM2: see https://github.com/hotosm/osm-tasking-manager2/pull/302

Ask me for further information.

**Comment by maddixm** [comment]
I am having the same problem and can no longer work on any tasks.
Steps to reproduce:
1) Change Display Name in openstreetmaps My Settings
2) Go to http://tasks.hotosm.org/ and click Login
3) Click Grant Access button
4) Get redirected back to http://tasks.hotosm.org/, not logged in.

I've tried logging in with Chrome and IE and get the same result. I was able to use TM3 up until the username change.
