### ISSUE TITLE
Validating: Multi select state but with only 1 task selected

### ISSUE THREAD

**Issue by harry-wood** [hotosm/tasking-manager#833]
On the validation tab where the contributors are listed in a table, there's a "LOCK" column with "Start" links. These are designed to select multiple tasks all by the same user (Multi select mode of validation).

BUT this seems wrong if you find somebody who only mapped 1 task and click "Start".  We see this:

![screen shot 2017-10-19 at 14 29 54](https://user-images.githubusercontent.com/227525/31773566-0f5d2518-b4db-11e7-8dae-51a609ea1bd5.png)

Which is a display bug, but also just generally being in the multi-select state is confusing. I don't want to see the "Mark ALL as invalid" button, because I've only got one selected, and I do want to see the "history" section showing what's happened with this task so far. In other words I don't want to be in multi-select mode at all.

(A workaround I notice, is to go to the "map" tab where there's an error message *"You cannot select tasks for mapping because you already have task(s) locked."* but the button *"Reselect tasks you locked for validation"*  brings me to the view I'm expecting)

I wonder if there are other buggy ways of arriving in a state where there's one task selected, but we're still in multi-select mode. Basically multi-select of just one task should not be possible.

**Comment by willemarcel** [comment]
This issue is outdated, so closing it
