### ISSUE TITLE
Individual Task. Map Controls disappear as one zooms in

### ISSUE THREAD

**Issue by Boggedy** [hotosm/tasking-manager#840]
The zoom in/out icons are not permanently visible in a task map unless one zooms into the top  left corner. 

They should populate the top left corner of the task tile map at every zoom level. This affects both mapping  and validation.

**Comment by pgiraud** [comment]
@Boggedy Can you please tell us how you usually zoom in the map? Double click? Using scroll wheel? What device or browser are you using?
I can't figure out how to reproduce the issue.

**Comment by Boggedy** [comment]
I have the latest chrome.

If I double click in towards a particular tile not in the NW corner the +- will disappear

Start here

http://tasks.hotosm.org/project/3643

double click on very small tile at bottom 

if I double click on a large tile (top or bottom) I cannot replicate it. +-  option remains visible

**Comment by ethan-nelson** [comment]
I'm going to go ahead and close this. I can't seem to replicate the issue nor could Pierre. Additionally we've made some changes to the way the map is handled during resizing, in case that was part of the issue. Please reopen if you can still get the bug to occur. Thanks for the report!
