### ISSUE TITLE
Shrinking then unshrinking window leaves map malformed

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#843]
While viewing a project, drag a side of the screen to make the window narrower, then drag it back to the original size. The result is an elongated map.

Before:

![original-fullpage](https://user-images.githubusercontent.com/8998918/31822304-ec3b8672-b56d-11e7-8222-edf58e1a30d4.png)

After:

![result-fullpage](https://user-images.githubusercontent.com/8998918/31822255-c3362c1e-b56d-11e7-9d28-33f6f9436809.png)

**Comment by verdy-p** [comment]
I've also seen that problem when resizing the window: the central position of the map slides at the same time and is not preserved, this sliding is not even reversed in the opposite direction when we restore the initial size. So the current map focus is lost. However I've not seen the zoom level changing at the same time, only the central position.
It seems that there's an initial javascript handler which is supposed offset the initial map, according to the initial window size, but this handler is still active and continues offseting the position each time there's some window layout reflowing event posted by the browser.
The event handler should be able to record the central position to preserve before the window size is adjusted, and then readjust it after the window size has been finalized, but not using the same initial offset measurement when the map was loaded into the window

**Comment by alekno** [comment]
Seems to be an asynchronous event lag. Collected the lagging map updates in 699
