### ISSUE TITLE
Update unread count in the popup

### ISSUE THREAD

**Issue by roomthily** [hotosm/tasking-manager#847]
Using Chrome (Version 61.0.3163.100), the notification popup over the user name doesn't update the count as messages are read until the page is refreshed. Not a big thing, but one that is more noticeable with the new messages posted on validation.

(Also, a "mark [checked || all] as read" would be great for a future feature.)

Thanks.

**Comment by roomthily** [comment]
There's a difference when using the browser back button (not updated) and the "Return to inbox" button (updated).

**Comment by xamanu** [comment]
This is fixed by now.
And the mark all as read is part of #1401
