### ISSUE TITLE
Leaving a comment and "stop validating" lose selected task square

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#849]

**Comment by bgirardot** [comment]
If you select a task square, "start validating", then type in a comment, then click "stop validating" (currently the only way to reply to a comment).

The selected task square is de-selected so you can't see your reply. It looks like it was lost.

This might happen on start/stop mapping too.

**Comment by ethan-nelson** [comment]
I've been playing with this workflow a bit and I think the idea is it's supposed to improve the iteration speed of validating. After you validate a tile, the tile is unselected and the user is brought back to the table of users with number of tiles mapped, prompting to select another user's work for validation. Perhaps we can refine this flow such that 1) if a user leaves a comment, after validating the tile remains selected, or 2) if the user does not leave a comment, the current behavior is retained and they are taken to the validation select screen.

**Comment by xamanu** [comment]
This has been addressed by @JorgeMartinezG with https://github.com/hotosm/tasking-manager/pull/1538. Thanks! Closing here.
