### ISSUE TITLE
Dashboard shows 0% / 0% for archived projects

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#861]
![2017-10-23_03h29_39](https://user-images.githubusercontent.com/265831/31876921-7349a118-b7a2-11e7-8f4c-977490b36ede.png)

**Comment by bgirardot** [comment]
I can not reproduce this, it seems to work for me.

At least with a project I created in TM3, I have no way to test an imported project

**Comment by alekno** [comment]
I reinvestigated this bug. My error. All is fine. We can close this.

**Comment by bgirardot** [comment]
Sounds good, thank you for the follow up @alekno
