### ISSUE TITLE
Last user that worked on a task is not selected after typing '@'

### ISSUE THREAD

**Issue by marxin** [hotosm/tasking-manager#864]
It was very useful feature when one was writing a comment that affected user was selected as first before a letter was following '@' character.

**Comment by alekno** [comment]
In validation and mapping mode I can't confirm this issue. After entering @ key a drop down list appears as in TM2.

**Comment by pgiraud** [comment]
I don't think @marxin complains about the list not showing. It does most probably, but in TM2 the user who last worked on the dropdown list would appear first. Which make it easier to select it for a mention.

**Comment by marxin** [comment]
Exactly as @pgiraud explained!

**Comment by ethan-nelson** [comment]
PR #1180 added a "users participating" group at the top of the suggest window.
