### ISSUE TITLE
Overachieving projects

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#868]
We seem to have at least one project trying to out-do the others: 
![overachiever](https://user-images.githubusercontent.com/6763645/31917677-f850d0a2-b815-11e7-9325-63c6b299a5c3.PNG)

101% validated?

**Comment by verdy-p** [comment]
I archived that project, but possibly a tile was counted twice (two records in the DB due to double click on the button), or validated once then invalidated and revalidated after corrections.

**Comment by ethan-nelson** [comment]
#1123 should have rounded out most of these issues. Please reopen if you continue to see this problem.
