### ISSUE TITLE
Contributions - sort by username

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#871]
It would be neat if you could sort by each of the columns, but currently having it only sorted by number of tiles mapped makes it too difficult to find a specific user.  Even if option to sort is down the line in priority; switching to sorting by username should be somewhat elevated as trying to find a specific username in a project with 500+ contributors is a bit difficult.

**Comment by Boggedy** [comment]
It is selected by mapper with most tiles mapped descending. 

A useful refinement would be to make it sortable by mappers ascending or descending and also sortable by validators ascending or descending.

**Comment by xamanu** [comment]
Still a to do in TM4.

![image](https://user-images.githubusercontent.com/97706/77065930-15ef1b00-69da-11ea-921a-08e799160894.png)

**Comment by ritvikjain99** [comment]
@xamanu I will get it done !

**Comment by willemarcel** [comment]
Replaced by https://github.com/hotosm/tasking-manager/issues/3949
