### ISSUE TITLE
Current Mappers Count

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#872]
Please correct me if I'm wrong, but there is no more count of the number of mappers currently working a project displayed somewhere? As an enhancement, it would be great to have also the total number of mappers on the whole TM somewhere.

**Comment by pgiraud** [comment]
I miss that feature a lot too. It was a good way to be aware of activity.

**Comment by bgirardot** [comment]
This should probably be a high priority issue. With the regression label.

**Comment by Boggedy** [comment]
should be high priority....it acts as a magnet and the overall tempo will drop without it.

**Comment by pgiraud** [comment]
Duplicate of #627.
