### ISSUE TITLE
Feature Request url redirect for registered and logged in users. 

### ISSUE THREAD

**Issue by Boggedy** [hotosm/tasking-manager#873]
The home page is essentially useless on a pc  (tasks.hotosm.org) and worse on an android device with the mapswype nagging.  

Is there any way that already registered and logged in users can be redirected ( by a cookie interaction ) to 

http://tasks.hotosm.org/contribute?difficulty=ALL instead 

and no mapswype nagging on that page please....especially in Android. 

as it is the closest there is to the old home page. Otherwise there will be some confused returning editors of long standing!

**Comment by hunt3ri** [comment]
Creating a bookmark on your browser for that page would mean you could skip the home page in the short term?

**Comment by ethan-nelson** [comment]
Hi Boggedy, the issue of not being able to dismiss the Mapswipe banner should be resolved--it was related to a broken UI element. Please reopen this though if you continue to have issues.

In regards to redirecting users, I don't think we want to push registered users past the home page immediately as there are mapping campaign highlights and calls to action on there.
