### ISSUE TITLE
Who locked a task?

### ISSUE THREAD

**Issue by pgiraud** [hotosm/tasking-manager#875]
If you select a locked task on the map, it looks like it's impossible to know who's working on it currently.
The history only shows actions when they're finished.

In TM2, this information was at the top of the "contribute tab" by giving information about the task current status (locked or not) and the user name.
And it was also available in the history for the task.

![screenshot from 2017-10-25 09-29-13](https://user-images.githubusercontent.com/319774/31985966-097c9300-b967-11e7-80a0-8931482342cc.png)

**Comment by pgiraud** [comment]
See https://github.com/hotosm/tasking-manager/issues/588 as well.

**Comment by pgiraud** [comment]
My mistake, the information is already available on the `advanced` block. I still think that the current locked status should be available in the history block.

**Comment by bgirardot** [comment]
@pgiraud It is also available on the "Activity and Stats" page.

It should be on the Task like your example, easy to find, otherwise you have no idea who is working on a task.

If we could get it to the main Task page that would be great.

**Comment by olafveerman** [comment]
We ran into the same issue today during a validation effort. It would be great if the current mapper would be shown more clearly.

**Comment by bgirardot** [comment]
pierre fixed this a while back, thank you @pgiraud
