### ISSUE TITLE
select random task for validation selecting ineligible tiles

### ISSUE THREAD

**Issue by johnwhelan** [hotosm/tasking-manager#876]
Unfortunately it will select tasks you have mapped thus are not able to validate.

**Comment by m-agboola** [comment]
Hi, I'd like to work on this issue if it's still open

**Comment by m-agboola** [comment]
I'd need some more information about this issue to be able to fix it. Please put me through

**Comment by xamanu** [comment]
Thanks @m-agboola for jumping into this! What are your concrete doubts?

**Comment by m-agboola** [comment]
@xamanu Sorry for the late reply, Where can I find this bug?

**Comment by xamanu** [comment]
Related  to and will be solved with #877
