### ISSUE TITLE
Mapping box snapped to admin boundaries

### ISSUE THREAD

**Issue by jharpster** [hotosm/tasking-manager#878]
Maybe not a real issue but certainly confusing for one of our mapathon editors. 

![microsoftteams-image](https://user-images.githubusercontent.com/224853/32020846-69b172e4-b986-11e7-9d9d-2d5e74ecd687.png)

**Comment by ethan-nelson** [comment]
That......is very interesting.

**Comment by ethan-nelson** [comment]
Actually it looks like in this case the task is shaped about some boundary: http://tasks.hotosm.org/project/3386?task=13

**Comment by bgirardot** [comment]
Yes, I am fairly certain that the project creation process and task trimming has no connection to data in OSM and they are not connected in the iD editor either.

I think this is just an artifact of the actual boundaries being used to create the project originally.

If I have misunderstood something, please re-open this issue.
