### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by sjparkinson** [hotosm/tasking-manager#880]
I'd opened an issue on the old task manager regarding `https://` support, and just wanted to re-open it here.

https://github.com/hotosm/osm-tasking-manager2/issues/988

> Currently the main site only works over plain text, while OpenStreetMap works over TLS.
> 
> As described in openstreetmap/iD#3771, this is causing a mixed content warning when using the iD editor for loading boundaries.

```
Mixed Content: The page at 'https://www.openstreetmap.org/edit?editor=id&#map=18/-18.7024446936/30.4725…' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://tasks.hotosm.org/project/3182/task/669.gpx'. This request has been blocked; the content must be served over HTTPS.
```

> With free services like Let's Encrypt and CloudFlare, it'd be great to serve the site with a certificate.

This was because I use an extension called HTTPS Everywhere which has rules for Open Street Map.

**Comment by alekno** [comment]
See #639

**Comment by sjparkinson** [comment]
Ah will close as duplicate and copy over my comment.
