### ISSUE TITLE
Organization Tags Still show in filter list even with no projects with that tag

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#881]
There are currently no MSF tagged projects (unless they are archived or draft and I can not see them) but MSF still shows up in the Organization list.

**Comment by fiennyangeln** [comment]
hi @bgirardot I want to take this issue.

**Comment by bgirardot** [comment]
@fiennyangeln Yes, please do take this on. As I mentioned previously, I am not a programmer so I can not give much guidance in the code.

But however that list on the the contribute page is generated, it should not display tags that are not actually in use.

https://tasks.hotosm.org/contribute?difficulty=ALL

![2018-02-20_15h23_12](https://user-images.githubusercontent.com/265831/36429173-45272c10-1652-11e8-93ef-7bc2b77da1c9.png)

more .....

**Comment by bgirardot** [comment]
Please be very aware of performance issues, it probably can not be something that happens everytime the page is loaded.

It does not have to be super time sensitive, adding organizations to the list seems to happen instantly, which is very good, we do not want to change that.

but removing them once there are no longer any projects, published, archived or draft with that organization tab is important, it just does not have to happen instantly if that would impact performance.

I will find an example tag that has no projects under it to help you explore the issue.

**Comment by bgirardot** [comment]
Here is one:

https://tasks.hotosm.org/contribute?difficulty=ALL&organisation=OSM%20Togo

That example is of an organization that has not projects with that tag, published, archived or draft status.

Please note, unless you are a project manager, you will not see the "include draft" and "include archived" options along the left of the screen.

We do need to keep organizations that have projects in draft and archive status.

**Comment by bgirardot** [comment]
also: EUROSHA, MSF, OSM Ghana

let me know if you need more examples.

**Comment by bgirardot** [comment]
@fiennyangeln I know there is no issue for it, but if you wanted to sort that list alphabetically ascending (A-Z) that would be pretty cool too :)

**Comment by ethan-nelson** [comment]
Pinging #1148 when merged

**Comment by xamanu** [comment]
This has been merged: https://github.com/hotosm/tasking-manager/pull/1148 Closing here, too.
