### ISSUE TITLE
What does mark mean when validating?

### ISSUE THREAD

**Issue by johnwhelan** [hotosm/tasking-manager#884]
It's not clear some other words perhaps?

John

**Comment by ethan-nelson** [comment]
Could you clarify what you mean, John? I think you may have left a word out of the title.

**Comment by johnwhelan** [comment]
On the validate screen it now reads mark as valid etc but one of the buttons only had teh word mark on it when I viewed and made the comment so it looks like its been fixed or part of the html was corrupted once when displayed.  Either way knock this one off the list.  John

**Comment by ethan-nelson** [comment]
Okay that was my bad in the interpretation. Thanks for the followup John, and glad it's fixed!
