### ISSUE TITLE
Reintroduce the gpx trace to mark the edge of a tile.

### ISSUE THREAD

**Issue by OttoROSM** [hotosm/tasking-manager#887]
when mapping a tile or validating tiles in JOSM and downloading outside of your tile to make sure a connection is made to a road or to ensure buildings on the border of the tile are mapped, you loose the information of what your tile is. Can you reintroduce the option to download a gpx trace?

**Comment by ethan-nelson** [comment]
This was recently built into the API again, but we need to add a link to it on the frontend as you mention. That said, this was brought up in #616 so I'm going to close this as a duplicate. Thank you for the comments Otto--this is actually near the top of my priority list for next week to knock out.
