### ISSUE TITLE
Page load flicker

### ISSUE THREAD

**Issue by alekno** [hotosm/tasking-manager#888]
When opening the TM first it displays the pure html before the java script does its job. A `<div ng-app="demo" ng-controller="DemoController" ng-cloak>` directive would prevent this 2 step display. So this is a request to add ng-cloak wherever neccessary.

**Comment by nidhinmahesh** [comment]
@ramyaragupathy can I work on this issue?

**Comment by xamanu** [comment]
Pinging @willemarcel  here.

**Comment by xamanu** [comment]
This has been fixed with the new frontend of TM4.
