### ISSUE TITLE
Spurious text

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#895]
http://tasks.hotosm.org/contribute?difficulty=ALL&page=96

![spurious text](https://user-images.githubusercontent.com/8775395/32140874-23025ebc-bcc4-11e7-8161-15dac5194156.JPG)

**Comment by tastrax** [comment]
![spurious text2](https://user-images.githubusercontent.com/8775395/32140882-81231d74-bcc4-11e7-968a-1378cf638c37.JPG)

**Comment by tastrax** [comment]
![spurious text3](https://user-images.githubusercontent.com/8775395/32140885-ce605282-bcc4-11e7-9ca0-2b16355551da.JPG)

**Comment by tastrax** [comment]
Also projects 1204, 1202, 1167, 1235

**Comment by alekno** [comment]
![grafik](https://user-images.githubusercontent.com/32923310/32143132-451156e4-bca5-11e7-81a7-c75b9da60a2c.png)

Does this look better?
(from current develop branch)

**Comment by tastrax** [comment]
Yep, looking good! Is there somewhere I can look at the development branch online (I should have checked...)?
