### ISSUE TITLE
Contribute project listing page with no projects listed

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#896]
http://tasks.hotosm.org/contribute?difficulty=ALL&page=54 

Seems a bit strange as there are projects on 53 and 55?

**Comment by alekno** [comment]
confirmed; a bug in the project listing.

**Comment by pgiraud** [comment]
http://tasks.hotosm.org/api/v1/project/search?mapperLevel=ALL&page=54

```
{
  "error": "Project GET - unhandled error: division by zero"
}
```

**Comment by bgirardot** [comment]
https://tasks.hotosm.org/contribute?difficulty=ALL&page=58

This reflects the issue via the front end. This exact page may change, so using next and previous to find one of these pages may be needed.

**Comment by willemarcel** [comment]
It doesn't apply to TM4.
