### ISSUE TITLE
search by place name to begin task creation

### ISSUE THREAD

**Issue by nualacowan** [hotosm/tasking-manager#90]
I really like the flow of this already, and echo many of Matt's comments (splitting cells). One thing I would love to have on the opening project creation page, is a search by place name box! It's a nuisance to have to zoom in manually

**Comment by bgirardot** [comment]
that is a great idea nuala.

**Comment by pgiraud** [comment]
It was a bit hidden but available in v2. ;-)

**Comment by bgirardot** [comment]
@nualacowan This is now in the new Tasking Manager, the magnifying glass icon on the map on step 1.
