### ISSUE TITLE
Organisation and Campaign list - sorting

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#902]
Given the lists in both these areas will continue to grow is it possible to have then sorted alphabetically to make it easier to find things.
![tm3-list-sort](https://user-images.githubusercontent.com/8775395/32154762-e925654a-bd86-11e7-8f25-bab2f0df97bf.png)
?

**Comment by verdy-p** [comment]
See also bug #509

**Comment by aaj013** [comment]
I'll try to do this @tastrax

**Comment by aaj013** [comment]
Please check my PR @tastrax  @bgirardot

**Comment by uwaiszaki** [comment]
@ramyaragupathy I think the issue is solved.

**Comment by ethan-nelson** [comment]
Yes--indeed completed!
