### ISSUE TITLE
Map view - project pop up obscured

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#903]
When using the map view, when zoomed in, occasionally (often the first time) the project popup does not appear completely  within the map frame

![tm3-map-project-popup](https://user-images.githubusercontent.com/8775395/32154920-34cf4e2e-bd88-11e7-96b2-4c9da9c7e514.JPG)

**Comment by bgirardot** [comment]
Hi @tastrax This was specifically addressed during development and works most of the time for me. I will make sure we keep looking into it. Thank you for making the issue.

**Comment by xamanu** [comment]
The new design in TM4 doesn't have popups anymore but selects the project in the list. So this has been fixed.
