### ISSUE TITLE
Encoding for embedded URLs

### ISSUE THREAD

**Issue by smit1678** [hotosm/tasking-manager#904]
From https://github.com/hotosm/tasking-manager/pull/874 a number of issues were raised regarding how the embedded URLs are encoded because they are not HTML5 valid. 

@alekno @verdy-p Thanks for the discussion thus far. Can one of you take this forward and propose the correct changes to the code you're talking about?

**Comment by xamanu** [comment]
The `ng-href` is only useful if we have some variable on the link like `/{{section}}`, it's not a problem using it without a var though.
On the jsFiddle tests we don't see any difference between replacing `&` by `&amp;`, @willemarcel and I prefer to use the first one.
In general, HTML5 validators are not a good reference when using a modern frontend JS framework. They won't recognize a lot of tags that that are useed, like ng-model, ng-if, etc. However, @willemarcel tested the url encoding and both were accepted by the W3C validators
