### ISSUE TITLE
Host javascript resources ourselves

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#912]
Feature request from #886 discussion: host javascript resources ourselves instead of CDN.

**Comment by Boggedy** [comment]
might explain the sluggish javascript. which CDN??

**Comment by OttoROSM** [comment]
@ethan-nelson,
The original issue of #886 in so far is solved by shutting down my security suite, each time when I use the tasking manager. I would say it is a workaround, but not a real resolution. :-)

Looking at the arguments from others more knowledgeable about why this happens, it seems good practice to not host on CDN and host on OSM or a more thrustworthy partner instead,

**Comment by dakotabenjamin** [comment]
FYI We have our own CDN now, hosted on aws s3.

**Comment by arunasank** [comment]
Can we close here?

**Comment by Boggedy** [comment]
yes

**Comment by ethan-nelson** [comment]
We haven't moved any of the resources to our CDN yet

**Comment by arunasank** [comment]
Oops sorry @ethan-nelson, thought that we had moved the resources to our CDN. Reopened!

**Comment by Boggedy** [comment]
The HOTOSM JS is notably faster in the last 8-12 months, perhaps it was
optimised making the CDN dispersal less pressing.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by xamanu** [comment]
Is it correct that we host the javascript resources ourselves by now? We just don't use a fully configured CDN. As far as I see we haven't identified this as a crucial bottleneck of our performance, which we are constantly increasing anyway through the new setup.

In case this is true, I suggest closing this issue for now. Eventually we bring it up, once it might become relevant for performance. What do you think?

**Comment by eternaltyro** [comment]
Five javascript resources that are hosted on `cdn.jsdelivr.net` are now available in our CDN. 

https://cdn.hotosm.org/js/osmtogeojson.js
https://cdn.hotosm.org/js/mentio.min.js
https://cdn.hotosm.org/js/geo-viewport.js
https://cdn.hotosm.org/js/ol3-layerswitcher.js
https://cdn.hotosm.org/js/ol3-geocoder.js

I'll use these to test the client and add more static resources when I find them.

**Comment by xamanu** [comment]
The downside of just using HOT's CDN is that all instances will use these resources. Ideally a TM should be able to live on it's own and without connections to anywhere (thinking about a use case inside of POSM, ...).

Probably we want to make this configurable for big instances to use any CDN they want to chose. And fallback to a local serving of the libraries if not configured otherwise.

In any case we can increase the max-age value so that the resources are cached in the browser for longer.

**Comment by eternaltyro** [comment]
@xamanu the original issue of #886 remains, no?
