### ISSUE TITLE
Allow deleting multiple TM messages at once

### ISSUE THREAD

**Issue by johnwhelan** [hotosm/tasking-manager#916]
Can this be made easier.  Sounds daft but with osteoarthritis in my fingers every mouse click counts.  I have a certain number per day before it starts to get painful. The choice is between clicking to delete them, each one currently requires multiple mouse clicks, and clicking to validate.

Thanks John

**Comment by tastrax** [comment]
It would be good to have a radio button to ‘select all’ before deleting

**Comment by xamanu** [comment]
This has been achieved in #1423. This issue can be closed.
