### ISSUE TITLE
searching for projects by project manager's name

### ISSUE THREAD

**Issue by johnwhelan** [hotosm/tasking-manager#921]
This used to work in TM2 but doesn't apparently work in TM3.

Thanks John

**Comment by bgirardot** [comment]
This falls under the general issue of improving the full text search, which leaves out a few fields that apparently tm2 used to include.

thanks for the heads up @johnwhelan I never searched that way so had no idea it used to work that way in tm2.

I am going to close this one and use the larger issue of improving the full text search as the main issue. Please see #926
