### ISSUE TITLE
Tasks lose focus/selection after marking mapped/validated or stopping

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#924]
A selected task loses its selection after someone 'starts' and then 'stops' or marks the task as completed, validated, invalidated, bad imagery.

The task should stay selected. This would allow the user to see the comment they left or perhaps check it out again.

**Comment by xamanu** [comment]
Fixed by @JorgeMartinezG and just merged into `develop`. Closing here.
