### ISSUE TITLE
selecting tiles to validate under legend

### ISSUE THREAD

**Issue by johnwhelan** [hotosm/tasking-manager#925]
It doesn't work.  I need to move the map so they aren't under the legend.

**Comment by verdy-p** [comment]
This does not seem like a bug, given you can zomm in/out, and not all tiles will be visible, even if the legend is hidden or moved elsewhere. so panning the map is necessary. Not specific to the TM, or even to OSM itself, but for any site or application that displays a map, and independantly of whever this map is partly covered by tools or button.
A click somewhere in the legend would only perform the action for the legend and not for any tiles hidden behind it (or partially visible if the legent is half-transparent).
