### ISSUE TITLE
Mapped Stats should reflect Invalidated tasks

### ISSUE THREAD

**Issue by marxin** [hotosm/tasking-manager#928]
Hello.

After migration, I would recommend to follow behavior of TM2, where Mapped reflected Invalidated. If you look here:
https://tasks.hotosm.org/project/3357/dashboard

Mapped is about 97%, while there are more than 10% of invalidated tasks. I understand Mapped as work that still needs to be done for mappers and invalidated tasks are work ;)

**Comment by verdy-p** [comment]
fully agree. The way the stats are computed now is non-sense, an invalid task is just the same as a task that has never been done, both require the same actions (mapping>done, or mapping>bad imagery, or mapping>split), none of them can be validated

**Comment by xamanu** [comment]
This is probably related to the data audit (#1460).

**Comment by willemarcel** [comment]
It's fixed with TM4
