### ISSUE TITLE
Maybe introduce graph for Mapped and Validated tasks as was used in TM2

### ISSUE THREAD

**Issue by marxin** [hotosm/tasking-manager#931]
I considered the feature quite successful and would be nice to have it also in TM3.
Thoughts?

**Comment by Rovastar** [comment]
So disappointed that the graphs are not there now.

**Comment by bgirardot** [comment]
We plan on re-introducing the graph or something very much like it. It should not be too hard to add back in.

Can you help us understand how you used them?

What information did it give that you found useful?

**Comment by marxin** [comment]
Good to hear that it's planned.
Use case was quite easy, it motivates people to see how Mapped and Validated numbers are increasing. For Mapathons, one can identify that a task was massively improved in a shore time period.

**Comment by xamanu** [comment]
This is included in the ongoing design work with @hotosm/major

**Comment by xamanu** [comment]
This has been included in TM4 like this:

![image](https://user-images.githubusercontent.com/97706/77065497-54380a80-69d9-11ea-8f2a-51fc6808a037.png)
