### ISSUE TITLE
mappers name not visible when validating

### ISSUE THREAD

**Issue by johnwhelan** [hotosm/tasking-manager#932]
for a mapper who only has one tile available selecting start brings up[just that tile in JOSM but you are unable to see their name.  makes leaving a comment difficult.

**Comment by FransS1945** [comment]
I support this issue

**Comment by xamanu** [comment]
This is to be considered in the ongoing redesign with @hotosm/major.

**Comment by xamanu** [comment]
This is now being part of the history tab on the sidebar while validating in TM4.
