### ISSUE TITLE
Enable a way to dismiss the MapSwipe banner

### ISSUE THREAD

**Issue by nerdanel** [hotosm/tasking-manager#933]
There doesn't seem to be a way to get rid of the MapSwipe banner when viewing the TM on mobile devices or at a smaller screen resolution (e.g. a resized window on a laptop). We had this issue crop up at the mapathon tonight where a low-res projector effectively made the TM think it's open on a mobile device and the MapSwipe banner was obscuring the actual task window.

**Comment by bgirardot** [comment]
Also see #820 which is related.

**Comment by harry-wood** [comment]
This issue duplicated https://github.com/hotosm/tasking-manager/issues/673

...but anyway, fixed! hurray!

**Comment by ethan-nelson** [comment]
This is now live
