### ISSUE TITLE
Allow marking as bad imagery in validation

### ISSUE THREAD

**Issue by dbdean** [hotosm/tasking-manager#936]
Can we get functionality so that areas of bad imagery can be marked during validation, as well as during mapping, or is it by design that you should have to invalidate the tile first, then map, then select bad imagery?

**Comment by ethan-nelson** [comment]
I believe it's by design that mapping sets the task as bad imagery, which can then be confirmed or invalidated during validation.

**Comment by ramyaragupathy** [comment]
bad imagery option is part of mapping workflow
