### ISSUE TITLE
Duplicated organisation and meaningless campaign names in list

### ISSUE THREAD

**Issue by Jorieke** [hotosm/tasking-manager#943]
For example 
Médecins Sans Frontières and MSF 
Clinton Health Access Initiative and Clinton Access Health Initiative

**Comment by verdy-p** [comment]
See also bug #509

**Comment by ethan-nelson** [comment]
This would be a good project for someone interested in diving into all of the components that make up the server backend. To implement a removal mechanism for tags, it will entail:

* Adding a method in the Postgres model for the tag table that will remove a given organization (https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/tags.py)
* Adding a service function that 1) ensures no projects currently are assigned to a given organization then 2) calls that method to remove the organization (https://github.com/hotosm/tasking-manager/blob/develop/server/services/tags_service.py)
* Adding an API endpoint to call that service with a given tag (https://github.com/hotosm/tasking-manager/blob/master/server/api/tags_apis.py)

Also note that organizations and campaigns are part of the same table and have essentially duplicate calls, so once you have done this for an organization you can copy+paste the code again and swap out organization for campaign.

**Comment by hunt3ri** [comment]
Hi folks, if there's community interest, I'd be happy to do a Google Hangout / screen share on this

Live coding, what could possibly go wrong 😉 

cc @ethan-nelson @pgiraud @smit1678 @bgirardot

**Comment by verdy-p** [comment]
I think that the organization name and its tag will likely be often different (e.g. no whitespace in hashtags, or possibly abbreviations, but whitespace in real unabbreviated organization name, shown on its profile page). Tags tend to be shorter as they are easier to type (note how we can select user names or organization names page names in social networks: we also have a disambiguating description which is useful to display along with the tag matched, there's a prefered tag along other possible aliases all disambiguated by the added description shown in the list of search results, and a prefered name)

**Comment by verdy-p** [comment]
Also, like users, organizations may have a registered icon in their profile, which can be shown when they talk by themselves or in lists or organization. These small icons would be smaller derivations from their logo (which is displayed more completely in their own profile page).

**Comment by fiennyangeln** [comment]
hi i want to take this. is it still available?

**Comment by bgirardot** [comment]
@fiennyangeln You are already working on this :)

This is directly related to your work on the campaign tags only showing tags that have project associated with them.

I can review this more, but the key is, if a campaign or organization has no projects (draft, archived or published), it should just disappear from the lists

**Comment by bgirardot** [comment]
@fiennyangeln I realize these are slightly different, but very related issues with the one you are already working on.

**Comment by fiennyangeln** [comment]
I tried adding API, service, method to delete the organisation_tag

**Comment by xamanu** [comment]
We are considering to improve campaigns as a whole (#1590), in parallel and similarily as we are improving organizations within the teams implementation (#1531). The migration of organizations as tags to the new database table, should address this issue here.

**Comment by xamanu** [comment]
We finished going through the list and consolidated them. Currently this is being tested on our database.
