### ISSUE TITLE
Add link to project home from dashboard

### ISSUE THREAD

**Issue by marxin** [hotosm/tasking-manager#947]
Being here:
https://tasks.hotosm.org/project/3357/dashboard

one can't find way how to get to:
https://tasks.hotosm.org/project/3357

**Comment by ethan-nelson** [comment]
Just for current reference, you can click the project name and number under `Activity and Stats` at the top to go back to the project.

But I totally agree it's should definitely be made clear (maybe with a "Return to Project" button)!

**Comment by marxin** [comment]
You're right. However the subtitle is in background that I haven't tried to hover it.

Thanks for working on that.
