### ISSUE TITLE
Fast validate button

### ISSUE THREAD

**Issue by marxin** [hotosm/tasking-manager#948]
I would consider adding button that will do:
Validate a random task + Start validating + Start editor

As I'm validating quite a lot, I always repeat these steps.

**Comment by leonmvd** [comment]
in addition to this it would be nice to click something like validate and then move on to the next task to validate

**Comment by xamanu** [comment]
This validation flow is part of the new redesign with the integration of iD editor. Tagging it accordingly.

**Comment by xamanu** [comment]
This has been rethought and significantly improved in TM4.
