### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by smit1678** [hotosm/tasking-manager#950]
License file for v3 is not available. v2 was tagged as BSD 2-clause: https://github.com/hotosm/osm-tasking-manager2/blob/master/LICENSE.txt. Proposing that we keep the same license.

**Comment by ethan-nelson** [comment]
Are dependency licenses a factor in this? Looks like the core components at least--namely Flask and AngularJS--are compatible with BSD 2-cl.

**Comment by smit1678** [comment]
@ethan-nelson Good call. Only concern would be if any dependencies were copy-left licenses.
