### ISSUE TITLE
Improve validation email subject line to indicate project

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#952]
![2017-11-14_04h36_29](https://user-images.githubusercontent.com/265831/32761763-721e03d8-c8f5-11e7-8819-99e43c890d72.png)

**Comment by mnoblecourt** [comment]
Hi,
Could we had an option "not receive messages when your task is validated" (unless there's a comment, like TMv2) to avoid advanced mappers being spammed? For some of our volunteers, they receive so many of these automatic messages (which need to be deleted manually!) that they don't even check their inbox anymore, and miss important communications.
Thanks!
Martin

**Comment by fiennyangeln** [comment]
@bgirardot Hi I wanna work on this issue. Can I add [ProjectID] in the beginning of the subject?

**Comment by bgirardot** [comment]
How about:

"Your mapping in Project nnnn, on Task nnn has just been validated"

@fiennyangeln Thank you for working on this!

**Comment by ethan-nelson** [comment]
I believe the original issue (as well as the secondary regarding opt out) has been fixed now in #1051. Please reopen if that is not the case--thanks!
