### ISSUE TITLE
Menu not automatically closing when clicking on items

### ISSUE THREAD

**Issue by cgiovando** [hotosm/tasking-manager#953]
The expected behavior should be that after clicking on any of the dropdown items, the menu would close, but at the moment it stays open. See screenshot below:

![screen shot 2017-11-14 at 19 05 26](https://user-images.githubusercontent.com/10201533/32796402-f6501b7c-c96e-11e7-87ff-4b03b0540f56.jpg)

**Comment by verdy-p** [comment]
I'd like to add that there's no viosual hint that the menu which is open is the "username" menu and not the Language menu (that use the same "V" icon after showing the currently selected language name).
If the menu is open, the top selected item in the menu bar (or its "V" icon) should be colored, or bordered (with its bottom border hidden and collapsed with the part of the top border of the popup, as if the "V" button was a tab).

This is minor though and I agree that the menu should close if we click any where outside it to close it (not just if we click again the "V" button).

**Comment by bgirardot** [comment]
My understanding is Soundharya is working on this.

**Comment by Soundharyaam** [comment]
Yup, Blake. I am working on it. Soon, I will create a PR for this bug.

**Comment by smit1678** [comment]
Tagging this for hacktoberfest as an issue that can be picked up. @Soundharyaam I didn't see a PR for the work so I'm assuming that this wasn't completed and this is still open for someone to pick up but let us know if this was finished but a PR was never created. 

Below is a gif that shows the menu not closing in action: 

![tasks-dropdown](https://user-images.githubusercontent.com/796838/46270823-b433ba80-c573-11e8-9a73-05d3c263a0b7.gif)

**Comment by uwaiszaki** [comment]
@smit1678 I would like to work on this issue if no one is currently working.

**Comment by uwaiszaki** [comment]
@ramyaragupathy I am trying to fix this issue.

**Comment by uwaiszaki** [comment]
@smit1678 @xamanu @ramyaragupathy can anyone explain me the purpose of the function 
vm.toggleMenu in account-nav.directive.js if we are not calling it anywhere?
![hotosmtaskmanagerissue953](https://user-images.githubusercontent.com/32809190/54425753-22dc8d00-473c-11e9-8ab2-b3f9c1be1001.png)

**Comment by uwaiszaki** [comment]
@xamanu @smit1678 @ramyaragupathy. Please review my pr [https://github.com/hotosm/tasking-manager/pull/1397](pr)

**Comment by ethan-nelson** [comment]
Closing thanks to fix in #1397
