### ISSUE TITLE
Can't add new organization

### ISSUE THREAD

**Issue by cgiovando** [hotosm/tasking-manager#954]
Typing in the name of a new organization does not add it, but instead the first one from the list gets selected.

![nov-14-2017 21-36-31](https://user-images.githubusercontent.com/10201533/32803609-5ef196fa-c984-11e7-906c-48657a45c6ca.gif)

**Comment by verdy-p** [comment]
I have seen the same bug: pressing TAB is equivalent to pressing ENTER: it selects the first proposed item.

Workaround: press SHIFT+TAB and you dismiss the proposals and the edit cursor will move to the start of the editable field. Then what you typed can be kept to create the org name.

The same bug occurs with the "Campaign Tag" field.

**Comment by xamanu** [comment]
This has been fixed with organizations in TM4.
