### ISSUE TITLE
Random task not taken in priority area

### ISSUE THREAD

**Issue by pgiraud** [hotosm/tasking-manager#955]
Reported on the mailing list by Florian:
> When mapping on task #3837 if I click "select random task" for mapping, I get tasks outside the priority area, but there are free unlocked, unmapped task in the priority area as well. I guess this is a bug?

This seems to be a regression since it was supported in TM2. Random tasks were preferably taken in the priority areas if available.

**Comment by majkaz** [comment]
Just happened to me, couldn't get single task in priority area.
See [this gif](https://drive.google.com/open?id=1Zkq9v3E4XN3Afrwcw6JOARR44OplyATX) - screenshots taken as the tasks came up for mapping for project [3899](https://tasks.hotosm.org/project/3899). 

Got few in the priority area after taking the screenshots - but got about 10 tasks before this from outside.

**Comment by xamanu** [comment]
Closing here, as this is getting tackled actively in #1583
