### ISSUE TITLE
Add Malagasy language to translations, both UI and Instructions

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#959]

**Comment by aaj013** [comment]
I'll try to add this

**Comment by bgirardot** [comment]
This was urgent due to an upcoming mapathon at the time. That has long passed, but this is still high priority if it has not been completed yet.

**Comment by ethan-nelson** [comment]
Malagasy was added a while back so I will go ahead and close this ticket out. Updated translations are pushed with other languages as available.
