### ISSUE TITLE
Message all contributors not working

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#961]
I have not been able to message all contributors for any of the Iran Earthquake 2017 projects.

**Comment by ethan-nelson** [comment]
Has it worked on other projects?

**Comment by bgirardot** [comment]
I have not tested it on other projects yet. it is hard to test on the live system as I don't want to needlessly message people :)

If they have their email address entered, even testing it on stage would send them emails.

I will try it on a another live project in a little while though.

**Comment by bgirardot** [comment]
Sorry I should add the error message is just that "message all contributors failed for an unknown reason" after about 1 to 2 minutes of "sending....."

No one seems to get the emails but that is hard to verify too, but my user never gets one and when i asked in slack no one said they received one.

**Comment by majkaz** [comment]
Just confirming - never received a message to the hotosm inbox.
The only messages into inbox I have got from this project are the throw-away automatic messages on validation and the direct one you have sent me on one of the projects. 

But where exactly is the message to all contributor addressed to? To the TM-inbox or to a "real" mail address?

I have just now added the email address to my profile in TM3. As I have already been a mapper, I have never got the "new user message" advising to do so. I don't expect to be the only "old" mapper, who simply logged in and started mapping, despite the TM-upgrade.

**Comment by hunt3ri** [comment]
@bgirardot we saw similar behaviour locally.  I think the issue is that sending messages to all contributors hits a rate limit on AWS SES, that they set quite low to stop people spamming.

I believe you can contact AWS to ask them to increase the rate limit cc @david-hotosm

**Comment by bgirardot** [comment]
Jorieke just confirmed it did not work for her either. I believe we already did as @hunt3ri mentioned, but maybe not.

@smit1678 I saw you mention we can review logs via aws, can we review some logs, perhaps with a real time effort to message all users and see if we can determine what is causing the failure?

**Comment by bgirardot** [comment]
@smit1678 I found the logs in aws, looking now.

Also @hunt3ri below is our SES settings and statistics. I was under the impression that we could push as many as we wanted to SES and it would rate limit the sending themselves, but queue and send at whatever the limit was.

![2017-12-07_16h13_11](https://user-images.githubusercontent.com/265831/33722337-f6f6517e-db69-11e7-9f4a-bc89ff17c319.png)

**Comment by hunt3ri** [comment]
Hi @bgirardot I'm guessing the message all contributors breaches the 14 emails per second limit.  The solution would be to add a small wait of 1 second after every 10 emails sent.  Assuming that is indeed the problem should be easy enough to add a patch - will try to submit next week.

**Comment by Jorieke** [comment]
Yes it is failing. This is what I get as error "Failed to message all contributors for an unknown reason."

**Comment by bgirardot** [comment]
Follow up: Jorieke reported that for another project with only a few contributors the process worked.

**Comment by bgirardot** [comment]
Gowin reports it failed for them, but they also received an email, and they happen to be among the first contributors.

![2018-01-25_03h29_26](https://user-images.githubusercontent.com/265831/35367866-eef32488-0180-11e8-8881-52124f20c223.png)

**Comment by bgirardot** [comment]
Gowin says it worked fine on this project, not a lot of contributors:

https://tasks.hotosm.org/project/4027

**Comment by hunt3ri** [comment]
@bgirardot I'm 90% convinced it's hitting AWS rate-limiting.  I'll try and find time for a PR

**Comment by hunt3ri** [comment]
Hey @bgirardot @ethan-nelson added a small PR for this https://github.com/hotosm/tasking-manager/pull/1036

**Comment by bgirardot** [comment]
@hunt3ri We deployed this and I just tested it, it seemed to go a lot longer in the sending process before it returned with the unknown error. :(

**Comment by bgirardot** [comment]
@hunt3ri This is still not working. Further, we got amazon to increase our send rate to 28/second (they just doubled it) and it still errors out.

Any chance we (someone not me because I do not know how/where) could put in some debug statements so we could log the actual error? I looked through the logs previously and did not see any errors that seemed related to this.

Even just a pointer to where I should stick the debug statements would help a lot and I might be able to take it from there.

**Comment by hunt3ri** [comment]
Hi @bgirardot this really is a bit of a head scratcher.  What I'll try and do is write a little test-harness spam-bot using the same code then will attempt to send 100 emails to myself, and try and figure out why we're getting this lock/timeout issue.  Will keep you posted.

**Comment by hunt3ri** [comment]
Hi @smit1678 I did some reasonably extensive testing on this locally - and have not managed to replicate the error.  I successfully sent 100 emails to myself with no obvious problems.  AWS seem pretty generous with the buffer - as it said I was only supposed to be send 14 emails per sec.

So I need you to check a couple of things:

1.  Can you confirm that the environment vars in prod point to the SMTP server you expect and that Blake mentions above, eg TM_SMTP_HOST,  TM_SMTP_USER, TM_SMTP_PASSWORD.  Note that SMTP server is region specific
2.  I added a small PR #1069 that tidies things up a little, but importantly now logs unhandled errors for send all with the string "Send message all - unhandled error"   so we should be able to find them in the logfile

So if you can merge that, re-run and immediately get the AWS log we see if that will shed some light on the problem.

If you're not sure how to get the logfile, ping me on slack.

**Comment by bgirardot** [comment]
Hi @hunt3ri I am pretty sure the env variables are set correctly. The tasking manager sends emails currently, just message all contributors does not usually complete. Hopefully we can get the pr deployed quickly.

**Comment by bgirardot** [comment]
@hunt3ri @smit1678 After nate merged in your latest change Iain to improve the logging, I used the message all contributors feature and it errorred and I immediately captured the last 100 lines logs and they are attached to this issue.

[TM3-message-all-contributors-error-logs.zip](https://github.com/hotosm/tasking-manager/files/1816017/TM3-message-all-contributors-error-logs.zip)

**Comment by verdy-p** [comment]
Be careful: such logs should be sent via private messages, not on this public thread!
There are visible security tokens in it, as well as privacy-sensitive data about users.
So next time, put the logs in a Google Drive or similar, and sent links only to authorized people.
