### ISSUE TITLE
How to find the squares I mapped recently?

### ISSUE THREAD

**Issue by akimmig** [hotosm/tasking-manager#965]
I started mapping a square yesterday and wanted to continue today. Is there an easy way to find the square I was working on?
Unfortunately the Last Activity in the Activity and Stats dashboard doesn't show the square number of the activity. Would be nice if the messages there would contain this number with an underlying link:

Task #nnn  locked for mapping by XXX
Task #nnn locked for validation by XXX

IIRC TM2 had this feature

**Comment by xamanu** [comment]
This is solved by the newly introduce section "My Contributions" in TM4.
