### ISSUE TITLE
Show archived projects in all search results / contribute / map page with checkbox toggle

### ISSUE THREAD

**Issue by mnoblecourt** [hotosm/tasking-manager#967]
Unless I missed it there is currently no way to filter manually Archived from non-Archived projects (and no existing issue related to that).
In fact I'm not even clear how to display archived projects.
Currently, when using the "Search" field, first time I press enter I only see the active projects, but if I press enter again I then see the archived projects... I am not sure if this is an intended behavior but if so it is not super optimal in term of user friendliness.
I would suggest to simply add a a filter "Archived projects" on the left menu that is by default un-ticked, a bit like on TM2.
Thanks!

PS: I created by mistake [the same issue with the wrong Github account](https://github.com/hotosm/tasking-manager/issues/966) and closed it, feel free to delete it.

**Comment by bgirardot** [comment]
Hi Martin,

Yes, we need this. We have a fix for the inconsistent display of archived projects that is waiting for deployment to the live server and we will need this more.

**Comment by bgirardot** [comment]
We need to optionally allow anyone to search for, find and see archived projects.

Right now this is only allowed for Project Managers, it should be an option for everyone.

**Comment by bgirardot** [comment]
@ethan-nelson Just recently added this feature for Project Managers with pull request #1025

**Comment by ethan-nelson** [comment]
This has been added for everyone now in #1130, so I think the issue has now been resolved. Please reopen if that is not the case--thanks!
