### ISSUE TITLE
Increase allowed length of comments

### ISSUE THREAD

**Issue by shiller27** [hotosm/tasking-manager#970]
Hi, unlike in TM2, the comment boxes in TM3 have a character limit (500 or so?). I am trying to give feedback to a new mapper and be friendly and supportive at the same time - very difficult to do within those restraints... Could the limit be extended, or better still, lifted? Many thanks :)

**Comment by ethan-nelson** [comment]
In the mean time, a private message through OSM may be a workaround. That also has the benefit of the user receiving notification via email.
