### ISSUE TITLE
Add OSM `uid` to API replies

### ISSUE THREAD

**Issue by kamicut** [hotosm/tasking-manager#975]
When requesting information about a user (for example in [/users/search-all](https://tasks.hotosm.org/api/v1/user/search-all)), it would be useful to have their OSM id alongside their username. This would help join API replies to other OSM information.

**Comment by verdy-p** [comment]
Yes, because sometimes user names are changing or are removed (when a user account is deleted), when uid are stable over time (they are kept when a user account is deleted, but there are no more user name).

**Comment by ethan-nelson** [comment]
For the end point given as an example, this will entail:

1. Add id as an attribute of the listed user data structure to hold `id` data (https://github.com/hotosm/tasking-manager/blob/develop/server/models/dtos/user_dto.py#L82)
2. Assign the user `id` to each user data structure in (https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/user.py#L87-L92)

Ideally `id` would be added to all of the endpoints listed on https://github.com/hotosm/tasking-manager/blob/develop/server/api/users/user_apis.py.

**Comment by fiennyangeln** [comment]
Hi can I work on this?

**Comment by bgirardot** [comment]
This is not closed I do not think, it looks like pr #1052 was just part of the solution. Someone correct me if I am wrong :)

**Comment by ethan-nelson** [comment]
I've checked that all of the API endpoints in /user now return the OSM user id.
