### ISSUE TITLE
Project Creation Organization Tag Autocomplete does not work

### ISSUE THREAD

**Issue by Nieldejong** [hotosm/tasking-manager#977]
Me and my colleagues have published multiple projects in the name of the 'Netherlands Red Cross', but the tag has never been saved as a default. @russdeffner mentioned that the organization should be saved in the TM3 after the first entry, but that does not happen at the moment. Therefore, it prob is a bug.

If this is not a bug, could the Netherlands Red Cross organization be added manually? 

When searching through projects by organization, you can see that multiple organizations have encountered this problem. For example, both the Clinton Health Access Initiative and the Clinton Access Health Initiative have been entered and are searchable:

![image](https://user-images.githubusercontent.com/31616896/33383251-1bf4a4dc-d523-11e7-8732-933c3eea0c43.png)

**Comment by verdy-p** [comment]
To create an organization tag in the project, so that you can select it later, you need to type its name, but DON'T press TAB or click outside, when the combobox opens its popup, press SHIFT+TAB which will keep you in the Combox editable field, but will place your cursor at start: the string will be transformed into a tag "button" and then you can save the edit, which will create the tag. Later, you'll be able to select this tag in any other project.
But I agree that we should have a better way to create an organization, not just as a simple tag, but as a real object which could have its own properties and profile, and its own list of sponsored TM projects

**Comment by Nieldejong** [comment]
Hi @verdy-p, thank you for your prompt response. 

Until now we have tagged our projects by writing the full name and then clicking outside of the box. It is not the exact same way as you described, but we have managed to attach the right tag to our project. The problem was that afterward, the tag was not automatically saved, so it never came up in the drop-down menu for a next projects. Not a huge problem, but it does make the process prone to, for example, spelling mistakes. 
I just tried it your way, which was more convenient. But it did not solve the problem yet.

To show you an example, we have a couple of projects with the right tags (as in the print screen below), but the name 'Netherlands Red Cross' still does not come up automatically (also in the print screen). 

![image](https://user-images.githubusercontent.com/31616896/33437706-0e8fc1d4-d5e9-11e7-9070-565946d1f47f.png)

**Comment by ethan-nelson** [comment]
If someone is interested in tackling this problem, the issue stems from https://github.com/hotosm/tasking-manager/blob/develop/client/app/admin/edit-project/edit-project.html#L304-L321 and the way the `<auto-complete ...>` field handles results. All of the past tags are loaded in from the server, but it seems the field only shows the first 10 and highlights words that match, as opposed to narrowing the list based on what you have typed so far. 

Given that we are already using angular-ui-bootstrap, a good start may be looking at another auto completion mechanism such as http://angular-ui.github.io/bootstrap/#!#typeahead. To be honest, I'm not quite sure which library the current auto complete is even coming from.

**Comment by verdy-p** [comment]
Well, you could actually set the tag you wanted in project 3571: it was correctly saved (and is also visible in the global list of projects)

But you are right! this is the autocompletion that does not work at all and statically displays the same list of 10 items, from apparently the same query of all organizations (in unspecified order) limited to 10 results (and no way to get more). It seems that autocompletion was never written and instead only some dummy code to prefill the list in the combobox before you even type into its edit field, and which is never refreshed if you type anything (what you've typed is completely ignored).
The second bug is that when you dismiss the combo menu (or move the input focus to outside by selecting another field), its currently preselected item is used in all case even if you never actually performed any action to select it. Only SHIFT+TAB keeps the focus within the editable field so when the popup menu disappears, the combo still has the focus but then nothing is currently selected in the popup and the content of the editable field is preserved, and this allows transforming the input text into a visible button and saving the tag with the form.
Any content can be then entered in this field, there's no validation performed at all, you can mistype the value and it will be recorded as is.

**Comment by bgirardot** [comment]
Yes, I just discovered this bug as well, a little late to the game, but it does not matter what you type in, you get the same list of 10 options:

![2018-02-20_17h52_28](https://user-images.githubusercontent.com/265831/36437467-5784775e-1667-11e8-9c5a-40072bf24972.png)
![2018-02-20_17h52_10](https://user-images.githubusercontent.com/265831/36437472-5b6865d8-1667-11e8-862c-34346fd819a0.png)
![2018-02-20_17h49_58](https://user-images.githubusercontent.com/265831/36437475-5f8a2fde-1667-11e8-825e-6522d887ed66.png)

**Comment by bgirardot** [comment]
@fiennyangeln Do you have any interest in taking a look at this one I now understand while testing your other fix :)

**Comment by fiennyangeln** [comment]
@bgirardot ok sure.

**Comment by bgirardot** [comment]
@Nieldejong pull request #1054 fixes this issue and has been merged in.

You can try out the fix on https://tasks-stage.hotosm.org/

Sorry for the long time it took to get this fixed.

We also have another pull request waiting to get the list of organization tags cleaned up that is partly a result of this issue.
