### ISSUE TITLE
Slippy map not working correctly with plus and minus keys - should stay centered on selected task

### ISSUE THREAD

**Issue by johnwhelan** [hotosm/tasking-manager#978]
the minus sign moves the map and when selecting for validation the map is not centered on the tile.

**Comment by bgirardot** [comment]
This needs more information please john.

The plus and minus signs on my windows 7 machine in chrome have no affect on the slippy map at all.

**Comment by johnwhelan** [comment]
Working fine this morning.  So some sort of temporary hiccup.
 
John
