### ISSUE TITLE
Project map Legend - change "ready" to "unmapped" or something

### ISSUE THREAD

**Issue by Nieldejong** [hotosm/tasking-manager#981]
I think the mark 'Ready' for empty tiles in the legend of the project map is confusing to many. Should this not be 'Not ready'? Or 'Empty' or 'Unmapped'. I understand they are ready to map, but I have experienced that many people read it as if they are readily mapped.

Also, I believe the border around the tile 'Locked by you' should be yellow instead of blue.

**Comment by Nieldejong** [comment]
In addition: in Dutch the translation 'Voltooid' is even more confusing as it really means 'Done' (when it is still to be done). 'Voltooid' should be 'Leeg'

**Comment by bgirardot** [comment]
@Nieldejong Hi Niel, i fixed the translation issue in transifex, which anyone is welcome to join and help with TM translations.

https://www.transifex.com/hotosm/tasking-manager-3/dashboard/

Getting it into the live version will take a little longer. 

Thank you for feedback on this. I tend to agree, unmapped is probably more clear.

**Comment by xamanu** [comment]
A whole conversation around layers, their names and colours is being covered in #1257. Closing here, to concentrate all thoughts there.
