### ISSUE TITLE
Add CC-BY in imagery license dropdown

### ISSUE THREAD

**Issue by cgiovando** [hotosm/tasking-manager#983]
I would have tried to add it myself, but `https://github.com/hotosm/tasking-manager/search?utf8=%E2%9C%93&q=NextView&type=` does not return any result, so I'm not sure where to find the config file to edit...

**Comment by althio** [comment]
are you looking for attribution ?
[tasking-manager/client/taskingmanager.config.json](https://github.com/hotosm/tasking-manager/blob/master/client/taskingmanager.config.json)

**Comment by bgirardot** [comment]
@cgiovando You should be able to do this via the UI in the tasking manager under your username, as you are now an administrator for on HOT's instance. Please re-open if that is not the case.
