### ISSUE TITLE
Banner or section for time-sensitive site-wide messages

### ISSUE THREAD

**Issue by smit1678** [hotosm/tasking-manager#990]
We don't have a good way of displaying a message or alert to all users that visit the site. Current need is a banner or notification that there is currently a fundraising campaign happening. A closable banner at the top may be an ok solution (like what Wikipedia does) but the fundraising campaign might not be the only time we want to put up an alert message (promote a mapping project or provide other information to all users).

I don't love a banner solution and so it could be useful to think through the use cases more and come up with a solution that works well for a lot of use cases and fits well with our current way we display messages to users. 

Donate message is also custom towards HOT's current deployment and so we need to think through how it could be made more configurable and useful for non-HOT deployments.

**Comment by xamanu** [comment]
These kind of notes are still relevant. Here I collect what messages we would like to get out to our users prominently:

- Fundraising/donation campaigns
- Planned downtimes for upgrading the Tasking Manager
- A message for mobile users to use MapSwipe

We might consider to make these messages editable through the UI, so we don't rely on deployments for introducing them, and we don't include such messages for people who just install/host their own TM. When doing so, we have to consider translations for it, too.

**Comment by Aadesh-Baral** [comment]
Closed by #5320
