### ISSUE TITLE
Splitting tasks loses previous comments

### ISSUE THREAD

**Issue by shiller27** [hotosm/tasking-manager#992]
Hi, 

it seems that when a tile is split, all the comments made on the 'tile of origin' disappear. This used not to happen in TM2. 

I left a lengthy comment on a task I was invalidating and decided to split the tile afterwards. The smaller tiles now show "nothing happened yet" in the comment section, and as far as I can make out my detailed feedback re mistakes/omissions will only be seen by the one user I tagged - or am I missing something?

Thanks!
Sabine

**Comment by shiller27** [comment]
Possibly connected to this is the fact that it is no longer possible to add a comment to a tile one has previously mapped/validated. It just happened to me that the comment I had written for a tile to be invalidated disappeared after I clicked 'invalidate' (not sure was that my mistake or a glitch). However, I couldn't rewrite the comment after invalidation. Again, in TM2  the ability to add comments to a tile was independent of one's mapping/validation involvement in that tile - definitely better!

**Comment by ethan-nelson** [comment]
This should be fixed and is now available on the live instance. Please let me know if you are still running into problems. Cheers!

**Comment by shiller27** [comment]
Brilliant, all working great :) Thanks!
