### ISSUE TITLE
Need a workflow to keep stage and demo databases kind of up to date with production

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#994]
We do need to periodically update the databases used by stage and demo to be the same as production.

I know production gets backed up, hopefully we can use the restore process to keep stage and demo somewhat sync'ed 

It would also probably just be good to help keep our restore workflow exercised.

**Comment by xamanu** [comment]
Just a little update:

* [ ] Currently there is only `stage` left that needs to be periodically updated from `live`.
* [ ] It would be great to have existing user permissions (AIM rules) applied and ideally the url is persistent for developers to connect, without digging into AWS each time.

There are two ways to approach this probably:

* *Simple*: Documentation on how to trigger this process
* *Better*: Automatic periodical update (once a week?).

**Comment by bopercival-hot** [comment]
closed as per the referenced commit
