### ISSUE TITLE
List validated tasks by user

### ISSUE THREAD

**Issue by johnwhelan** [hotosm/tasking-manager#998]
If I can't see which tiles they have validated it makes it very difficult to give feedback and I have someone interested in becoming a validator at the moment.

**Comment by bgirardot** [comment]
This is increasing in priority because more and more new mappers are being encouraged to do validation and we are finding very low quality validation as a result. But then we have no way to locate other tasks the user has validated to review them or un-validate them.

**Comment by ethan-nelson** [comment]
Do either of you all have an idea of what this might take the form of? Would it be similar to the user mapped part of validation tab (where you can select one person and it selects all their tiles) but a 'revalidation' section instead?

**Comment by willemarcel** [comment]
We will implement this on the redesign, so I'm closing this issue in favour of https://github.com/hotosm/tasking-manager/issues/1599
